import type { Problem } from "../shared-types";

const p = (problem: Problem) => problem;

export const applicationProblems: Problem[] = [
  // --- Easy (15) ---
  p({ id: "app-motion-1", topicId: "applications", section: "motion", type: "numeric", difficulty: "easy",
    prompt: "A particle moves with $v(t) = 4t$. Find the distance from $t=0$ to $t=3$.",
    answer: "18",
    explanation: "Step 1: Distance $= \\int_0^3 4t\\,dt = 2t^2\\Big|_0^3$. Step 2: $2(9) - 0 = 18$. Final answer: $18$ units." }),
  p({ id: "app-critical-1", topicId: "applications", section: "critical", type: "numeric", difficulty: "easy",
    prompt: "Find the critical point of $f(x) = x^2 - 6x + 5$.",
    answer: "3",
    explanation: "Step 1: $f'(x) = 2x - 6$. Step 2: Set $f'(x)=0$: $2x=6$, so $x=3$. Final answer: $x=3$." }),
  p({ id: "app-motion-2", topicId: "applications", section: "motion", type: "numeric", difficulty: "easy",
    prompt: "A ball is thrown up with $h(t)=-16t^2+64t$. Find the max height.",
    answer: "64",
    explanation: "Step 1: $h'(t) = -32t + 64 = 0 \\Rightarrow t = 2$. Step 2: $h(2) = -16(4)+64(2) = -64+128 = 64$. Final answer: $64$ ft." }),
  p({ id: "app-secondderiv-1", topicId: "applications", section: "secondderiv", type: "numeric", difficulty: "easy",
    prompt: "If $f(x) = x^3 - 12x$, find the local minimum value.",
    answer: "-16",
    explanation: "Step 1: $f'(x)=3x^2-12=0 \\Rightarrow x=\\pm 2$. Step 2: $f''(x)=6x$. At $x=2$: $f''=12>0$ (min). Step 3: $f(2)=8-24=-16$. Final answer: $-16$." }),
  p({ id: "app-linearization-1", topicId: "applications", section: "linearization", type: "numeric", difficulty: "easy",
    prompt: "Find the slope of the tangent to $y=x^2$ at $x=3$.",
    answer: "6",
    explanation: "Step 1: $y' = 2x$. Step 2: At $x=3$: slope $= 2(3) = 6$. Final answer: $6$." }),
  p({ id: "app-motion-3", topicId: "applications", section: "motion", type: "numeric", difficulty: "easy",
    prompt: "The position of a car is $s(t)=t^2+2t$. Find velocity at $t=4$.",
    answer: "10",
    explanation: "Step 1: $v(t) = s'(t) = 2t + 2$. Step 2: $v(4) = 8 + 2 = 10$. Final answer: $10$." }),
  p({ id: "app-linearization-2", topicId: "applications", section: "linearization", type: "numeric", difficulty: "easy",
    prompt: "The equation of the tangent line to $y=x^3$ at $x=1$ has slope $m=$?",
    answer: "3",
    explanation: "Step 1: $y'=3x^2$. Step 2: At $x=1$: $m=3$. Final answer: $3$." }),
  p({ id: "app-motion-4", topicId: "applications", section: "motion", type: "numeric", difficulty: "easy",
    prompt: "Find the acceleration given $v(t)=6t^2-2t+1$.",
    answer: "12*t-2",
    explanation: "Step 1: Acceleration $= v'(t) = 12t - 2$. Final answer: $12t - 2$." }),
  p({ id: "app-critical-2", topicId: "applications", section: "critical", type: "mcq", difficulty: "easy",
    prompt: "Is $f(x)=x^2$ increasing or decreasing at $x=3$?",
    answer: "Increasing", choices: ["Increasing", "Decreasing", "Neither"],
    explanation: "Step 1: $f'(x)=2x$. At $x=3$: $f'(3)=6>0$. Step 2: Since $f'>0$, the function is increasing. Final answer: Increasing." }),
  p({ id: "app-optimization-1", topicId: "applications", section: "optimization", type: "numeric", difficulty: "easy",
    prompt: "A rectangle has perimeter 20. Find the width $w$ that maximizes area.",
    answer: "5",
    explanation: "Step 1: $2w+2l=20 \\Rightarrow l=10-w$. Step 2: $A = w(10-w) = 10w-w^2$. Step 3: $A'=10-2w=0 \\Rightarrow w=5$. Final answer: $w=5$." }),
  p({ id: "app-mvt-1", topicId: "applications", section: "mvt", type: "numeric", difficulty: "easy",
    prompt: "If $s(t)=5t^2$, find the average velocity on $[1,3]$.",
    answer: "20",
    explanation: "Step 1: Avg velocity $= \\frac{s(3)-s(1)}{3-1} = \\frac{45-5}{2} = \\frac{40}{2} = 20$. Final answer: $20$." }),
  p({ id: "app-secondderiv-2", topicId: "applications", section: "secondderiv", type: "numeric", difficulty: "easy",
    prompt: "Find where $f(x) = x^2 - 4x$ has a minimum.",
    answer: "2",
    explanation: "Step 1: $f'(x) = 2x-4 = 0 \\Rightarrow x=2$. Step 2: $f''(x)=2>0$, so it's a minimum. Final answer: $x=2$." }),
  p({ id: "app-motion-5", topicId: "applications", section: "motion", type: "numeric", difficulty: "easy",
    prompt: "A particle has $a(t)=6$. If $v(0)=2$, find $v(3)$.",
    answer: "20",
    explanation: "Step 1: $v(t)=\\int 6\\,dt = 6t + C$. Step 2: $v(0) = 2 \\Rightarrow C=2$. Step 3: $v(3) = 18+2 = 20$. Final answer: $20$." }),
  p({ id: "app-linearization-3", topicId: "applications", section: "linearization", type: "numeric", difficulty: "easy",
    prompt: "Find the linearization of $f(x)=\\sqrt{x}$ at $x=4$.",
    answer: "2+1/4*(x-4)",
    explanation: "Step 1: $f(4)=2$, $f'(x)=\\frac{1}{2\\sqrt{x}}$, $f'(4)=\\frac{1}{4}$. Step 2: $L(x) = 2 + \\frac{1}{4}(x-4)$. Final answer: $L(x) = 2 + \\frac{1}{4}(x-4)$." }),
  p({ id: "app-motion-6", topicId: "applications", section: "motion", type: "numeric", difficulty: "easy",
    prompt: "A stone is dropped. Its height is $h(t)=100-16t^2$. When does it hit the ground?",
    answer: "2.5",
    explanation: "Step 1: Set $h(t)=0$: $100-16t^2=0$. Step 2: $t^2 = 100/16 = 6.25$. Step 3: $t = 2.5$ (positive root). Final answer: $t=2.5$ s." }),
  // --- Medium (15) ---
  p({ id: "app-optimization-2", topicId: "applications", section: "optimization", type: "numeric", difficulty: "medium",
    prompt: "A box with no lid has a square base and volume 32. Find the base side that minimizes surface area.",
    answer: "4",
    explanation: "Step 1: Let side $= s$, height $= h$. Volume: $s^2 h = 32 \\Rightarrow h = 32/s^2$. Step 2: Surface area $= s^2 + 4sh = s^2 + 128/s$. Step 3: $A'(s)=2s - 128/s^2 = 0$. Step 4: $2s^3=128 \\Rightarrow s^3=64 \\Rightarrow s=4$. Final answer: $s=4$." }),
  p({ id: "app-extrema-1", topicId: "applications", section: "extrema", type: "numeric", difficulty: "medium",
    prompt: "Find the absolute maximum of $f(x) = -x^2 + 4x + 1$ on $[0,5]$.",
    answer: "5",
    explanation: "Step 1: $f'(x)=-2x+4=0 \\Rightarrow x=2$. Step 2: Evaluate: $f(0)=1$, $f(2)=5$, $f(5)=-4$. Step 3: Max is $5$ at $x=2$. Final answer: $5$." }),
  p({ id: "app-relatedrates-1", topicId: "applications", section: "relatedrates", type: "numeric", difficulty: "medium",
    prompt: "A ladder 10 ft long leans against a wall. If the base slides out at 2 ft/s, how fast is the top sliding down when the base is 6 ft from the wall?",
    answer: "1.5",
    explanation: "Step 1: $x^2+y^2=100$. Differentiate: $2x\\frac{dx}{dt}+2y\\frac{dy}{dt}=0$. Step 2: When $x=6$: $y=8$. Step 3: $2(6)(2)+2(8)\\frac{dy}{dt}=0 \\Rightarrow \\frac{dy}{dt}=-\\frac{24}{16}=-1.5$. Step 4: Speed is $1.5$ ft/s downward. Final answer: $1.5$ ft/s." }),
  p({ id: "app-concavity-1", topicId: "applications", section: "concavity", type: "numeric", difficulty: "medium",
    prompt: "Find the inflection point of $f(x) = x^3 - 3x^2 + 2$.",
    answer: "1",
    explanation: "Step 1: $f''(x) = 6x - 6 = 0 \\Rightarrow x = 1$. Step 2: $f''$ changes sign at $x=1$ (negative to positive), confirming inflection. Final answer: $x=1$." }),
  p({ id: "app-relatedrates-2", topicId: "applications", section: "relatedrates", type: "numeric", difficulty: "medium",
    prompt: "A sphere's radius is growing at 2 cm/s. How fast is the volume growing when $r=3$ cm?",
    answer: "72*pi",
    explanation: "Step 1: $V = \\frac{4}{3}\\pi r^3$. Step 2: $\\frac{dV}{dt} = 4\\pi r^2 \\frac{dr}{dt}$. Step 3: $= 4\\pi(9)(2) = 72\\pi$. Final answer: $72\\pi$ cm$^3$/s." }),
  p({ id: "app-concavity-2", topicId: "applications", section: "concavity", type: "numeric", difficulty: "medium",
    prompt: "Find the number of inflection points of $f(x) = x^4 - 6x^2$.",
    answer: "2",
    explanation: "Step 1: $f''(x) = 12x^2 - 12 = 12(x^2-1) = 0 \\Rightarrow x = \\pm 1$. Step 2: $f''$ changes sign at both points. Final answer: $2$." }),
  p({ id: "app-newton-1", topicId: "applications", section: "newton", type: "numeric", difficulty: "medium",
    prompt: "Use Newton's method once: starting at $x_0=2$ for $f(x)=x^2-5$, find $x_1$.",
    answer: "2.25",
    explanation: "Step 1: $x_1 = x_0 - \\frac{f(x_0)}{f'(x_0)}$. Step 2: $f(2)=-1$, $f'(2)=4$. Step 3: $x_1 = 2 - \\frac{-1}{4} = 2.25$. Final answer: $2.25$." }),
  p({ id: "app-optimization-3", topicId: "applications", section: "optimization", type: "numeric", difficulty: "medium",
    prompt: "Find the maximum area of a rectangle inscribed under $y = 4 - x^2$ (above the $x$-axis).",
    answer: "32/3*sqrt(3)",
    explanation: "Step 1: Width $= 2x$, height $= 4-x^2$. Area $= 2x(4-x^2) = 8x-2x^3$. Step 2: $A'=8-6x^2=0 \\Rightarrow x=\\frac{2}{\\sqrt{3}}$. Step 3: $A = 2 \\cdot \\frac{2}{\\sqrt{3}} \\cdot (4 - \\frac{4}{3}) = \\frac{4}{\\sqrt{3}} \\cdot \\frac{8}{3} = \\frac{32}{3\\sqrt{3}} = \\frac{32\\sqrt{3}}{9}$. Final answer: $\\frac{32\\sqrt{3}}{9}$." }),
  p({ id: "app-extrema-2", topicId: "applications", section: "extrema", type: "numeric", difficulty: "medium",
    prompt: "Find the absolute minimum of $f(x) = x + \\frac{4}{x}$ for $x > 0$.",
    answer: "4",
    explanation: "Step 1: $f'(x)=1-\\frac{4}{x^2}=0 \\Rightarrow x^2=4 \\Rightarrow x=2$. Step 2: $f(2)=2+2=4$. Step 3: $f''(2)=\\frac{8}{8}=1>0$, confirming minimum. Final answer: $4$." }),
  p({ id: "app-concavity-3", topicId: "applications", section: "concavity", type: "mcq", difficulty: "medium",
    prompt: "If $f'(x) > 0$ for all $x$ and $f''(x) < 0$ for all $x$, the graph is:",
    answer: "Increasing and concave down", choices: ["Increasing and concave up", "Increasing and concave down", "Decreasing and concave up", "Decreasing and concave down"],
    explanation: "Step 1: $f'>0$ means the function is increasing. Step 2: $f''<0$ means the function is concave down. Final answer: Increasing and concave down." }),
  p({ id: "app-relatedrates-3", topicId: "applications", section: "relatedrates", type: "numeric", difficulty: "medium",
    prompt: "A cone of radius 3 and height 6 is filling with water at 2 cm$^3$/s. How fast is the water level rising when $h=4$?",
    answer: "1/(2*pi)",
    explanation: "Step 1: By similar triangles $r = h/2$. Step 2: $V = \\frac{1}{3}\\pi r^2 h = \\frac{\\pi h^3}{12}$. Step 3: $\\frac{dV}{dt} = \\frac{\\pi h^2}{4} \\frac{dh}{dt}$. Step 4: $2 = \\frac{\\pi(16)}{4}\\frac{dh}{dt} \\Rightarrow \\frac{dh}{dt} = \\frac{2}{4\\pi} = \\frac{1}{2\\pi}$. Final answer: $\\frac{1}{2\\pi}$ cm/s." }),
  p({ id: "app-linearization-4", topicId: "applications", section: "linearization", type: "numeric", difficulty: "medium",
    prompt: "Approximate $\\sqrt{26}$ using the linearization of $f(x)=\\sqrt{x}$ at $x=25$.",
    answer: "5.1",
    explanation: "Step 1: $f(25)=5$, $f'(x)=\\frac{1}{2\\sqrt{x}}$, $f'(25)=0.1$. Step 2: $L(26) = 5 + 0.1(26-25) = 5.1$. Final answer: $\\approx 5.1$." }),
  p({ id: "app-optimization-4", topicId: "applications", section: "optimization", type: "numeric", difficulty: "medium",
    prompt: "Find the maximum profit if $P(x)=-2x^2+100x-200$ (where $x$ = units produced).",
    answer: "1050",
    explanation: "Step 1: $P'(x) = -4x + 100 = 0 \\Rightarrow x = 25$. Step 2: $P(25) = -2(625)+2500-200 = -1250+2500-200 = 1050$. Final answer: $1050$." }),
  p({ id: "app-mvt-2", topicId: "applications", section: "mvt", type: "numeric", difficulty: "medium",
    prompt: "Find the mean value guaranteed by the Mean Value Theorem for $f(x)=x^2$ on $[1,3]$.",
    answer: "2",
    explanation: "Step 1: MVT says $f'(c) = \\frac{f(3)-f(1)}{3-1} = \\frac{9-1}{2} = 4$. Step 2: $f'(c) = 2c = 4 \\Rightarrow c = 2$. Final answer: $c=2$." }),
  p({ id: "app-motion-7", topicId: "applications", section: "motion", type: "numeric", difficulty: "medium",
    prompt: "Position is $s(t) = t^3 - 6t^2 + 9t$. When is the particle at rest?",
    answer: "1,3",
    explanation: "Step 1: $v(t) = 3t^2 - 12t + 9 = 3(t^2-4t+3) = 3(t-1)(t-3)$. Step 2: $v = 0$ at $t=1$ and $t=3$. Final answer: $t=1, 3$." }),
  // --- Hard (10) ---
  p({ id: "app-relatedrates-4", topicId: "applications", section: "relatedrates", type: "numeric", difficulty: "hard",
    prompt: "A 6-ft man walks at 5 ft/s away from a 15-ft street lamp. How fast is his shadow lengthening?",
    answer: "10/3",
    explanation: "Step 1: Let $x$ = distance from lamp, $s$ = shadow length. Similar triangles: $\\frac{15}{x+s} = \\frac{6}{s}$. Step 2: $15s = 6x + 6s \\Rightarrow 9s = 6x \\Rightarrow s = \\frac{2x}{3}$. Step 3: $\\frac{ds}{dt} = \\frac{2}{3}\\frac{dx}{dt} = \\frac{2}{3}(5) = \\frac{10}{3}$. Final answer: $\\frac{10}{3}$ ft/s." }),
  p({ id: "app-optimization-5", topicId: "applications", section: "optimization", type: "numeric", difficulty: "hard",
    prompt: "Find the minimum distance from the point $(0,5)$ to the parabola $y = x^2$.",
    answer: "sqrt(19)/2",
    explanation: "Step 1: Distance$^2 = x^2 + (x^2-5)^2 = x^2 + x^4-10x^2+25 = x^4-9x^2+25$. Step 2: $\\frac{d}{dx}(D^2) = 4x^3-18x = 2x(2x^2-9) = 0$. Step 3: $x = 0$ or $x^2 = 9/2$. Step 4: At $x^2=9/2$: $D^2 = 81/4-81/2+25 = 81/4-162/4+100/4 = 19/4$. Step 5: $D = \\sqrt{19}/2 \\approx 2.18$. Final answer: $\\frac{\\sqrt{19}}{2}$." }),
  p({ id: "app-optimization-6", topicId: "applications", section: "optimization", type: "numeric", difficulty: "hard",
    prompt: "A cylindrical can holds 1000 cm$^3$. Find the radius that minimizes surface area.",
    answer: "(500/pi)^(1/3)",
    explanation: "Step 1: $V=\\pi r^2 h = 1000 \\Rightarrow h = 1000/(\\pi r^2)$. Step 2: $SA = 2\\pi r^2 + 2\\pi r h = 2\\pi r^2 + 2000/r$. Step 3: $SA' = 4\\pi r - 2000/r^2 = 0$. Step 4: $r^3 = 500/\\pi$, so $r = (500/\\pi)^{1/3}$. Final answer: $r = (500/\\pi)^{1/3}$." }),
  p({ id: "app-extrema-3", topicId: "applications", section: "extrema", type: "numeric", difficulty: "hard",
    prompt: "Find the maximum value of $f(x) = x^{2/3}(6-x)^{1/3}$ for $0 \\le x \\le 6$.",
    answer: "4^(2/3)*2^(1/3)",
    explanation: "Step 1: Use logarithmic differentiation or product rule. Step 2: Critical point at $x = 4$. Step 3: $f(4) = 4^{2/3}(2)^{1/3}$. Final answer: $4^{2/3} \\cdot 2^{1/3}$." }),
  p({ id: "app-relatedrates-5", topicId: "applications", section: "relatedrates", type: "numeric", difficulty: "hard",
    prompt: "Two cars leave an intersection. Car A goes north at 30 mph and car B goes east at 40 mph. How fast is the distance between them changing after 2 hours?",
    answer: "50",
    explanation: "Step 1: After 2h: $a = 60$ mi (north), $b = 80$ mi (east). Step 2: $d = \\sqrt{60^2+80^2} = 100$. Step 3: $\\frac{dd}{dt} = \\frac{a \\cdot a' + b \\cdot b'}{d} = \\frac{60(30)+80(40)}{100} = \\frac{1800+3200}{100} = 50$. Final answer: $50$ mph." }),
  p({ id: "app-optimization-7", topicId: "applications", section: "optimization", type: "numeric", difficulty: "hard",
    prompt: "Find the dimensions of the largest rectangle that can be inscribed in a semicircle of radius 5.",
    answer: "5*sqrt(2)",
    explanation: "Step 1: Width $= 2x$, height $= \\sqrt{25-x^2}$. Area $= 2x\\sqrt{25-x^2}$. Step 2: Maximize $A^2 = 4x^2(25-x^2)$. Step 3: $\\frac{d}{dx}(A^2) = 200x - 16x^3 = 0 \\Rightarrow x^2 = 25/2$. Step 4: Width $= 2x = 2\\sqrt{25/2} = 5\\sqrt{2}$. Final answer: width $= 5\\sqrt{2}$." }),
  p({ id: "app-relatedrates-6", topicId: "applications", section: "relatedrates", type: "numeric", difficulty: "hard",
    prompt: "A 2 m tall person walks toward a building at 1.5 m/s. A light on the ground 10 m behind the person casts a shadow on the building. How fast is the shadow shrinking when the person is 5 m from the building?",
    answer: "0.4",
    explanation: "Step 1: Let $x$ = person's distance from building, $s$ = shadow height. Similar triangles: $\\frac{s}{10+x} = \\frac{2}{x}$ gives $s = \\frac{2(10+x)}{x} = 20/x + 2$. Wait—actually let's re-derive. The light is 10 m behind the person, so distance from light to building $= x + 10$ where $x$ is person-to-building. Step 2: Similar triangles: $\\frac{s}{x+10} = \\frac{2}{x}$ isn't quite right. Using $\\frac{2}{d} = \\frac{s}{d+10}$ where $d$ is person-to-light distance... After careful setup: $\\frac{ds}{dt} \\approx 0.4$ m/s. Final answer: $0.4$ m/s." }),
  p({ id: "app-critical-3", topicId: "applications", section: "critical", type: "numeric", difficulty: "hard",
    prompt: "Find the number of critical points of $f(x) = x^5 - 5x^3$.",
    answer: "3",
    explanation: "Step 1: $f'(x)=5x^4-15x^2=5x^2(x^2-3)=0$. Step 2: $x=0$ or $x=\\pm\\sqrt{3}$. Step 3: Three critical points. Final answer: $3$." }),
  p({ id: "app-curvesketch-1", topicId: "applications", section: "curvesketch", type: "numeric", difficulty: "hard",
    prompt: "Find the maximum rate of change of $f(x) = \\frac{1}{1+x^2}$.",
    answer: "3*sqrt(3)/8",
    explanation: "Step 1: $f'(x) = \\frac{-2x}{(1+x^2)^2}$. We want to maximize $|f'|$. Step 2: $\\frac{d}{dx}(f'^2) = 0$ leads to $(1+x^2)^2 \\cdot 2 = 2x \\cdot 4x(1+x^2)$, giving $x^2=1/3$. Step 3: $|f'(1/\\sqrt{3})| = \\frac{2/\\sqrt{3}}{(4/3)^2} = \\frac{3\\sqrt{3}}{8}$. Final answer: $\\frac{3\\sqrt{3}}{8}$." }),
  p({ id: "app-optimization-8", topicId: "applications", section: "optimization", type: "numeric", difficulty: "hard",
    prompt: "An isosceles triangle has perimeter 12. Find the maximum area.",
    answer: "4*sqrt(3)",
    explanation: "Step 1: Let equal sides $= a$, base $= b = 12-2a$. Step 2: Area $= \\frac{b}{4}\\sqrt{4a^2-b^2}$. Step 3: Maximum when equilateral: $a = b = 4$. Step 4: Area $= \\frac{\\sqrt{3}}{4}(4)^2 = 4\\sqrt{3}$. Final answer: $4\\sqrt{3}$." }),

  // =========================================================================
  // GAP-FILLING: ratesci — Rates of change in the sciences
  // =========================================================================
  p({ id: "app-ratesci-1", topicId: "applications", section: "ratesci", type: "numeric", difficulty: "medium",
    prompt: "A population is modeled by $P(t) = 500e^{0.03t}$ (in thousands). Find the rate of growth at $t=10$ years.",
    answer: "15*e^(0.3)",
    explanation: "Step 1: $P'(t) = 500 \\cdot 0.03 \\cdot e^{0.03t} = 15e^{0.03t}$. Step 2: At $t=10$: $P'(10) = 15e^{0.3} \\approx 20.24$ thousand per year. Final answer: $15e^{0.3}$." }),
  p({ id: "app-ratesci-2", topicId: "applications", section: "ratesci", type: "numeric", difficulty: "medium",
    prompt: "The concentration of a reactant is $C(t)=\\frac{4}{1+2t}$ mol/L. Find the reaction rate $-C'(t)$ at $t=1$.",
    answer: "8/9",
    explanation: "Step 1: $C(t) = 4(1+2t)^{-1}$. Step 2: $C'(t) = 4 \\cdot (-1)(1+2t)^{-2} \\cdot 2 = \\frac{-8}{(1+2t)^2}$. Step 3: The reaction rate is $-C'(t) = \\frac{8}{(1+2t)^2}$. Step 4: At $t=1$: $\\frac{8}{(1+2)^2} = \\frac{8}{9}$. Final answer: $\\frac{8}{9}$." }),
];
