import type { Problem } from "../shared-types";

const p = (problem: Problem) => problem;

export const appIntProblems: Problem[] = [
  // ── EASY (15) ──────────────────────────────────────────────
  p({ id: "appint-areacurves-1", topicId: "applications-of-integration", section: "areacurves", type: "numeric", difficulty: "easy",
    prompt: "Find the area between $y = x^2$ and $y = x$ from $x=0$ to $x=1$.",
    answer: "1/6",
    explanation: "Step 1: Top minus bottom: $x - x^2$ on $[0,1]$. Step 2: $\\int_0^1 (x - x^2)\\,dx = \\left[\\frac{x^2}{2} - \\frac{x^3}{3}\\right]_0^1 = \\frac{1}{2} - \\frac{1}{3} = \\frac{1}{6}$. Final answer: $\\frac{1}{6}$." }),
  p({ id: "appint-areacurves-2", topicId: "applications-of-integration", section: "areacurves", type: "numeric", difficulty: "easy",
    prompt: "Find the area between $y = 4$ and $y = x^2$ from $x = -2$ to $x = 2$.",
    answer: "32/3",
    explanation: "Step 1: $4 - x^2 \\ge 0$ on $[-2,2]$. Step 2: $\\int_{-2}^{2}(4 - x^2)\\,dx = \\left[4x - \\frac{x^3}{3}\\right]_{-2}^{2} = \\left(8 - \\frac{8}{3}\\right) - \\left(-8 + \\frac{8}{3}\\right) = \\frac{32}{3}$. Final answer: $\\frac{32}{3}$." }),
  p({ id: "appint-diskwasher-1", topicId: "applications-of-integration", section: "diskwasher", type: "numeric", difficulty: "easy",
    prompt: "Find the volume when $y = x$ on $[0,3]$ is revolved about the $x$-axis using the disk method.",
    answer: "9*pi",
    explanation: "Step 1: $V = \\pi\\int_0^3 x^2\\,dx$. Step 2: $= \\pi\\left[\\frac{x^3}{3}\\right]_0^3 = 9\\pi$. Final answer: $9\\pi$." }),
  p({ id: "appint-diskwasher-2", topicId: "applications-of-integration", section: "diskwasher", type: "numeric", difficulty: "easy",
    prompt: "Find the volume when $y = \\sqrt{x}$ on $[0,4]$ is revolved about the $x$-axis.",
    answer: "8*pi",
    explanation: "Step 1: $V = \\pi\\int_0^4 (\\sqrt{x})^2\\,dx = \\pi\\int_0^4 x\\,dx$. Step 2: $= \\pi\\left[\\frac{x^2}{2}\\right]_0^4 = 8\\pi$. Final answer: $8\\pi$." }),
  p({ id: "appint-shells-1", topicId: "applications-of-integration", section: "shells", type: "numeric", difficulty: "easy",
    prompt: "Use cylindrical shells to find the volume when $y = x^2$ on $[0,2]$ is revolved about the $y$-axis.",
    answer: "8*pi",
    explanation: "Step 1: $V = 2\\pi\\int_0^2 x \\cdot x^2\\,dx = 2\\pi\\int_0^2 x^3\\,dx$. Step 2: $= 2\\pi\\left[\\frac{x^4}{4}\\right]_0^2 = 2\\pi \\cdot 4 = 8\\pi$. Final answer: $8\\pi$." }),
  p({ id: "appint-shells-2", topicId: "applications-of-integration", section: "shells", type: "numeric", difficulty: "easy",
    prompt: "Use shells to find the volume when $y = x$ on $[0,1]$ is revolved about the $y$-axis.",
    answer: "2*pi/3",
    explanation: "Step 1: $V = 2\\pi\\int_0^1 x \\cdot x\\,dx = 2\\pi\\int_0^1 x^2\\,dx$. Step 2: $= 2\\pi\\left[\\frac{x^3}{3}\\right]_0^1 = \\frac{2\\pi}{3}$. Final answer: $\\frac{2\\pi}{3}$." }),
  p({ id: "appint-arclength-1", topicId: "applications-of-integration", section: "arclength", type: "numeric", difficulty: "easy",
    prompt: "Find the arc length of $y = 3x + 1$ from $x = 0$ to $x = 4$.",
    answer: "4*sqrt(10)",
    explanation: "Step 1: $y' = 3$, so $\\sqrt{1 + 9} = \\sqrt{10}$. Step 2: $L = \\int_0^4 \\sqrt{10}\\,dx = 4\\sqrt{10}$. Final answer: $4\\sqrt{10}$." }),
  p({ id: "appint-parametric-1", topicId: "applications-of-integration", section: "parametric", type: "numeric", difficulty: "easy",
    prompt: "Given $x = t^2$ and $y = t^3$, find $\\frac{dy}{dx}$ at $t = 2$.",
    answer: "3",
    explanation: "Step 1: $\\frac{dx}{dt} = 2t$, $\\frac{dy}{dt} = 3t^2$. Step 2: $\\frac{dy}{dx} = \\frac{3t^2}{2t} = \\frac{3t}{2}$. Step 3: At $t=2$: $\\frac{3(2)}{2} = 3$. Final answer: $3$." }),
  p({ id: "appint-surfacearea-1", topicId: "applications-of-integration", section: "surfacearea", type: "numeric", difficulty: "easy",
    prompt: "Find the surface area when $y = 2$ on $[0,5]$ is revolved about the $x$-axis.",
    answer: "20*pi",
    explanation: "Step 1: $y' = 0$, so $\\sqrt{1+0} = 1$. Step 2: $S = 2\\pi\\int_0^5 2\\,dx = 4\\pi \\cdot 5 = 20\\pi$. Final answer: $20\\pi$." }),
  p({ id: "appint-work-1", topicId: "applications-of-integration", section: "work", type: "numeric", difficulty: "easy",
    prompt: "A constant force of $10$ N moves an object from $x = 0$ to $x = 6$ m. Find the work done.",
    answer: "60",
    explanation: "Step 1: $W = \\int_0^6 10\\,dx = 10 \\cdot 6 = 60$ J. Final answer: $60$." }),
  p({ id: "appint-work-2", topicId: "applications-of-integration", section: "work", type: "numeric", difficulty: "easy",
    prompt: "A spring has spring constant $k = 8$ N/m. Find the work to stretch it from $x = 0$ to $x = 3$ m.",
    answer: "36",
    explanation: "Step 1: $W = \\int_0^3 8x\\,dx = 8\\left[\\frac{x^2}{2}\\right]_0^3 = 4 \\cdot 9 = 36$ J. Final answer: $36$." }),
  p({ id: "appint-areacurves-3", topicId: "applications-of-integration", section: "areacurves", type: "mcq", difficulty: "easy",
    prompt: "To find the area between $y = f(x)$ and $y = g(x)$ when $f(x) \\ge g(x)$ on $[a,b]$, which integral do you evaluate?",
    answer: "∫[a,b] (f(x)-g(x)) dx",
    choices: ["∫[a,b] (f(x)-g(x)) dx", "∫[a,b] (g(x)-f(x)) dx", "∫[a,b] f(x)*g(x) dx", "∫[a,b] |f(x)+g(x)| dx"],
    explanation: "Step 1: Area between curves is top minus bottom integrated. Step 2: Since $f(x) \\ge g(x)$, the integrand is $f(x)-g(x)$. Final answer: $\\int_a^b (f(x)-g(x))\\,dx$." }),
  p({ id: "appint-diskwasher-3", topicId: "applications-of-integration", section: "diskwasher", type: "mcq", difficulty: "easy",
    prompt: "When revolving $y = f(x)$ about the $x$-axis, the disk method gives volume $V = $?",
    answer: "pi*∫[a,b] [f(x)]^2 dx",
    choices: ["pi*∫[a,b] [f(x)]^2 dx", "2*pi*∫[a,b] x*f(x) dx", "∫[a,b] f(x) dx", "pi*∫[a,b] f(x) dx"],
    explanation: "Step 1: Cross-sections are disks of radius $f(x)$. Step 2: Area of each disk is $\\pi[f(x)]^2$. Step 3: Integrate to get $V = \\pi\\int_a^b [f(x)]^2\\,dx$. Final answer: $\\pi\\int_a^b [f(x)]^2\\,dx$." }),
  p({ id: "appint-shells-3", topicId: "applications-of-integration", section: "shells", type: "mcq", difficulty: "easy",
    prompt: "In the shell method revolving about the $y$-axis, each shell has volume $2\\pi \\cdot \\text{radius} \\cdot \\text{height} \\cdot dx$. What is the radius?",
    answer: "x",
    choices: ["x", "f(x)", "y", "dx"],
    explanation: "Step 1: When revolving around the $y$-axis, the distance from a vertical strip at position $x$ to the axis is $x$. Final answer: $x$." }),
  p({ id: "appint-parametric-2", topicId: "applications-of-integration", section: "parametric", type: "numeric", difficulty: "easy",
    prompt: "Given $x = 3t$ and $y = 4t$ for $0 \\le t \\le 1$, find the arc length of the curve.",
    answer: "5",
    explanation: "Step 1: $\\frac{dx}{dt} = 3$, $\\frac{dy}{dt} = 4$. Step 2: $L = \\int_0^1 \\sqrt{9 + 16}\\,dt = \\int_0^1 5\\,dt = 5$. Final answer: $5$." }),

  // ── MEDIUM (15) ─────────────────────────────────────────────
  p({ id: "appint-areacurves-4", topicId: "applications-of-integration", section: "areacurves", type: "numeric", difficulty: "medium",
    prompt: "Find the area enclosed between $y = x^2$ and $y = 2x + 3$.",
    answer: "32/3",
    explanation: "Step 1: Set $x^2 = 2x + 3 \\Rightarrow x^2 - 2x - 3 = 0 \\Rightarrow (x-3)(x+1) = 0$, so $x = -1, 3$. Step 2: $\\int_{-1}^{3}(2x+3-x^2)\\,dx = \\left[x^2 + 3x - \\frac{x^3}{3}\\right]_{-1}^{3} = (9+9-9) - (1-3+\\frac{1}{3}) = 9 + \\frac{5}{3} = \\frac{32}{3}$. Final answer: $\\frac{32}{3}$." }),
  p({ id: "appint-areacurves-5", topicId: "applications-of-integration", section: "areacurves", type: "numeric", difficulty: "medium",
    prompt: "Find the area between $y = \\sin(x)$ and $y = 0$ from $x = 0$ to $x = \\pi$.",
    answer: "2",
    explanation: "Step 1: $\\sin(x) \\ge 0$ on $[0,\\pi]$. Step 2: $\\int_0^{\\pi} \\sin(x)\\,dx = [-\\cos(x)]_0^{\\pi} = -(-1) - (-1) = 2$. Final answer: $2$." }),
  p({ id: "appint-diskwasher-4", topicId: "applications-of-integration", section: "diskwasher", type: "numeric", difficulty: "medium",
    prompt: "Find the volume when the region between $y = x^2$ and $y = x$ is revolved about the $x$-axis using washers.",
    answer: "3*pi/10",
    explanation: "Step 1: Intersection: $x^2 = x \\Rightarrow x = 0,1$. Outer $R = x$, inner $r = x^2$. Step 2: $V = \\pi\\int_0^1(x^2 - x^4)\\,dx = \\pi\\left[\\frac{x^3}{3} - \\frac{x^5}{5}\\right]_0^1 = \\pi\\left(\\frac{1}{3} - \\frac{1}{5}\\right) = \\frac{3\\pi}{10}$. Final answer: $\\frac{3\\pi}{10}$." }),
  p({ id: "appint-diskwasher-5", topicId: "applications-of-integration", section: "diskwasher", type: "numeric", difficulty: "medium",
    prompt: "Find the volume when $y = e^x$ on $[0,1]$ is revolved about the $x$-axis.",
    answer: "pi*(e^2-1)/2",
    explanation: "Step 1: $V = \\pi\\int_0^1 e^{2x}\\,dx$. Step 2: $= \\pi\\left[\\frac{e^{2x}}{2}\\right]_0^1 = \\pi\\left(\\frac{e^2}{2} - \\frac{1}{2}\\right) = \\frac{\\pi(e^2-1)}{2}$. Final answer: $\\frac{\\pi(e^2-1)}{2}$." }),
  p({ id: "appint-shells-4", topicId: "applications-of-integration", section: "shells", type: "numeric", difficulty: "medium",
    prompt: "Use shells to find the volume when the region between $y = x$ and $y = x^2$ is revolved about the $y$-axis.",
    answer: "pi/6",
    explanation: "Step 1: $V = 2\\pi\\int_0^1 x(x - x^2)\\,dx = 2\\pi\\int_0^1(x^2 - x^3)\\,dx$. Step 2: $= 2\\pi\\left[\\frac{x^3}{3} - \\frac{x^4}{4}\\right]_0^1 = 2\\pi\\left(\\frac{1}{3} - \\frac{1}{4}\\right) = 2\\pi \\cdot \\frac{1}{12} = \\frac{\\pi}{6}$. Final answer: $\\frac{\\pi}{6}$." }),
  p({ id: "appint-shells-5", topicId: "applications-of-integration", section: "shells", type: "numeric", difficulty: "medium",
    prompt: "Use shells to find the volume when $y = 4 - x^2$ (above the $x$-axis) is revolved about the $y$-axis.",
    answer: "8*pi",
    explanation: "Step 1: $4 - x^2 = 0 \\Rightarrow x = 2$. Step 2: $V = 2\\pi\\int_0^2 x(4-x^2)\\,dx = 2\\pi\\int_0^2(4x - x^3)\\,dx$. Step 3: $= 2\\pi\\left[2x^2 - \\frac{x^4}{4}\\right]_0^2 = 2\\pi(8 - 4) = 8\\pi$. Final answer: $8\\pi$." }),
  p({ id: "appint-arclength-2", topicId: "applications-of-integration", section: "arclength", type: "numeric", difficulty: "medium",
    prompt: "Find the arc length of $y = \\frac{2}{3}x^{3/2}$ from $x = 0$ to $x = 3$.",
    answer: "14/3",
    explanation: "Step 1: $y' = x^{1/2}$, so $(y')^2 = x$ and $1+(y')^2 = 1+x$. Step 2: $L = \\int_0^3\\sqrt{1+x}\\,dx = \\left[\\frac{2}{3}(1+x)^{3/2}\\right]_0^3 = \\frac{2}{3}(8-1) = \\frac{14}{3}$. Final answer: $\\frac{14}{3}$." }),
  p({ id: "appint-arclength-3", topicId: "applications-of-integration", section: "arclength", type: "numeric", difficulty: "medium",
    prompt: "Find the arc length of $y = \\frac{x^2}{4} - \\frac{\\ln x}{2}$ from $x = 1$ to $x = 2$.",
    answer: "3/4+ln(2)/2",
    explanation: "Step 1: $y' = \\frac{x}{2} - \\frac{1}{2x}$. Step 2: $(y')^2 = \\frac{x^2}{4} - \\frac{1}{2} + \\frac{1}{4x^2}$. Step 3: $1 + (y')^2 = \\frac{x^2}{4} + \\frac{1}{2} + \\frac{1}{4x^2} = \\left(\\frac{x}{2} + \\frac{1}{2x}\\right)^2$. Step 4: $L = \\int_1^2 \\left(\\frac{x}{2} + \\frac{1}{2x}\\right)dx = \\left[\\frac{x^2}{4} + \\frac{\\ln x}{2}\\right]_1^2 = \\left(1 + \\frac{\\ln 2}{2}\\right) - \\frac{1}{4} = \\frac{3}{4} + \\frac{\\ln 2}{2}$. Final answer: $\\frac{3}{4} + \\frac{\\ln 2}{2}$." }),
  p({ id: "appint-parametric-3", topicId: "applications-of-integration", section: "parametric", type: "numeric", difficulty: "medium",
    prompt: "Find the arc length of $x = \\cos(t)$, $y = \\sin(t)$ from $t = 0$ to $t = \\pi$.",
    answer: "pi",
    explanation: "Step 1: $\\frac{dx}{dt} = -\\sin t$, $\\frac{dy}{dt} = \\cos t$. Step 2: $\\sqrt{\\sin^2 t + \\cos^2 t} = 1$. Step 3: $L = \\int_0^{\\pi} 1\\,dt = \\pi$. Final answer: $\\pi$." }),
  p({ id: "appint-surfacearea-2", topicId: "applications-of-integration", section: "surfacearea", type: "numeric", difficulty: "medium",
    prompt: "Find the surface area when $y = x$ on $[0,1]$ is revolved about the $x$-axis.",
    answer: "pi*sqrt(2)",
    explanation: "Step 1: $y' = 1$, $\\sqrt{1+1} = \\sqrt{2}$. Step 2: $S = 2\\pi\\int_0^1 x\\sqrt{2}\\,dx = 2\\pi\\sqrt{2}\\left[\\frac{x^2}{2}\\right]_0^1 = \\pi\\sqrt{2}$. Final answer: $\\pi\\sqrt{2}$." }),
  p({ id: "appint-surfacearea-3", topicId: "applications-of-integration", section: "surfacearea", type: "numeric", difficulty: "medium",
    prompt: "Find the surface area when $y = \\sqrt{x}$ on $[0,1]$ is revolved about the $x$-axis.",
    answer: "pi*(5*sqrt(5)-1)/6",
    explanation: "Step 1: $y' = \\frac{1}{2\\sqrt{x}}$, $(y')^2 = \\frac{1}{4x}$, $1+(y')^2 = \\frac{4x+1}{4x}$. Step 2: $S = 2\\pi\\int_0^1 \\sqrt{x}\\cdot\\frac{\\sqrt{4x+1}}{2\\sqrt{x}}\\,dx = \\pi\\int_0^1\\sqrt{4x+1}\\,dx$. Step 3: Let $u=4x+1$: $S = \\frac{\\pi}{4}\\cdot\\frac{2}{3}u^{3/2}\\Big|_1^5 = \\frac{\\pi}{6}(5\\sqrt{5}-1)$. Final answer: $\\frac{\\pi(5\\sqrt{5}-1)}{6}$." }),
  p({ id: "appint-work-3", topicId: "applications-of-integration", section: "work", type: "numeric", difficulty: "medium",
    prompt: "A spring requires $12$ N to hold it $0.2$ m past its natural length. Find the work to stretch it from $0.1$ m to $0.3$ m past natural length.",
    answer: "2.4",
    explanation: "Step 1: $k = 12/0.2 = 60$ N/m. Step 2: $W = \\int_{0.1}^{0.3}60x\\,dx = 60\\left[\\frac{x^2}{2}\\right]_{0.1}^{0.3} = 30(0.09 - 0.01) = 30 \\cdot 0.08 = 2.4$ J. Final answer: $2.4$." }),
  p({ id: "appint-diskwasher-6", topicId: "applications-of-integration", section: "diskwasher", type: "mcq", difficulty: "medium",
    prompt: "To find the volume of the solid formed by revolving the region between $y = x$ and $y = x^2$ about $y = -1$, what is the outer radius $R$ of the washer?",
    answer: "x+1",
    choices: ["x+1", "x", "x^2+1", "1-x"],
    explanation: "Step 1: Outer curve is $y = x$ (top). Step 2: Distance from $y = x$ to the axis $y = -1$ is $x - (-1) = x + 1$. Final answer: $x+1$." }),
  p({ id: "appint-parametric-4", topicId: "applications-of-integration", section: "parametric", type: "mcq", difficulty: "medium",
    prompt: "For $x = t^3 - t$ and $y = t^2$, $\\frac{dy}{dx}$ is undefined when:",
    answer: "3t^2-1=0",
    choices: ["3t^2-1=0", "2t=0", "t^3-t=0", "t^2=0"],
    explanation: "Step 1: $\\frac{dy}{dx} = \\frac{dy/dt}{dx/dt} = \\frac{2t}{3t^2-1}$. Step 2: Undefined when the denominator $3t^2 - 1 = 0$. Final answer: $3t^2 - 1 = 0$." }),
  p({ id: "appint-arclength-4", topicId: "applications-of-integration", section: "arclength", type: "mcq", difficulty: "medium",
    prompt: "The arc length formula $L = \\int_a^b \\sqrt{1 + [f'(x)]^2}\\,dx$ requires which condition on $f$?",
    answer: "f' is continuous on [a,b]",
    choices: ["f' is continuous on [a,b]", "f is positive on [a,b]", "f is increasing on [a,b]", "f'' exists on [a,b]"],
    explanation: "Step 1: The arc length integral requires the integrand to be well-defined and integrable. Step 2: This holds when $f'$ is continuous on $[a,b]$. Final answer: $f'$ is continuous on $[a,b]$." }),

  // ── HARD (10) ──────────────────────────────────────────────
  p({ id: "appint-areacurves-6", topicId: "applications-of-integration", section: "areacurves", type: "numeric", difficulty: "hard",
    prompt: "Find the total area enclosed by $y = x^3 - x$ and $y = 0$.",
    answer: "1/2",
    explanation: "Step 1: $x^3 - x = x(x-1)(x+1) = 0$ at $x = -1, 0, 1$. Step 2: On $[-1,0]$, $x^3 - x \\ge 0$; on $[0,1]$, $x^3 - x \\le 0$. Step 3: Area $= \\int_{-1}^{0}(x^3-x)\\,dx + \\int_0^1(x - x^3)\\,dx = \\left[\\frac{x^4}{4}-\\frac{x^2}{2}\\right]_{-1}^0 + \\left[\\frac{x^2}{2}-\\frac{x^4}{4}\\right]_0^1 = \\frac{1}{4} + \\frac{1}{4} = \\frac{1}{2}$. Final answer: $\\frac{1}{2}$." }),
  p({ id: "appint-areacurves-7", topicId: "applications-of-integration", section: "areacurves", type: "numeric", difficulty: "hard",
    prompt: "Find the area between $y = e^x$ and $y = e^{2x-1}$ from $x = 0$ to $x = 1$.",
    answer: "e/2-1+1/(2*e)",
    explanation: "Step 1: At $x=0$: $e^0=1$ vs $e^{-1}=1/e$, so $e^x > e^{2x-1}$ near $x=0$. They meet at $x=1$ where both equal $e$. Step 2: $\\int_0^1(e^x - e^{2x-1})\\,dx = \\left[e^x - \\frac{e^{2x-1}}{2}\\right]_0^1 = \\left(e - \\frac{e}{2}\\right) - \\left(1 - \\frac{1}{2e}\\right) = \\frac{e}{2} - 1 + \\frac{1}{2e}$. Final answer: $\\frac{e}{2} - 1 + \\frac{1}{2e}$." }),
  p({ id: "appint-diskwasher-7", topicId: "applications-of-integration", section: "diskwasher", type: "numeric", difficulty: "hard",
    prompt: "Find the volume when the region between $y = \\sqrt{x}$ and $y = x^2$ is revolved about $y = 1$ using washers.",
    answer: "11*pi/30",
    explanation: "Step 1: Intersection: $\\sqrt{x} = x^2 \\Rightarrow x = x^4 \\Rightarrow x(x^3-1)=0$, so $x=0,1$. On $[0,1]$, $\\sqrt{x} \\ge x^2$. Step 2: Outer radius $R = 1 - x^2$, inner radius $r = 1 - \\sqrt{x}$. Step 3: $V = \\pi\\int_0^1[(1-x^2)^2 - (1-\\sqrt{x})^2]\\,dx = \\pi\\int_0^1(-2x^2+x^4+2x^{1/2}-x)\\,dx$. Step 4: $= \\pi\\left[-\\frac{2x^3}{3}+\\frac{x^5}{5}+\\frac{4x^{3/2}}{3}-\\frac{x^2}{2}\\right]_0^1 = \\pi\\left(-\\frac{2}{3}+\\frac{1}{5}+\\frac{4}{3}-\\frac{1}{2}\\right) = \\pi\\cdot\\frac{11}{30} = \\frac{11\\pi}{30}$. Final answer: $\\frac{11\\pi}{30}$." }),
  p({ id: "appint-shells-6", topicId: "applications-of-integration", section: "shells", type: "numeric", difficulty: "hard",
    prompt: "Use shells to find the volume when the region bounded by $y = \\sin(x)$, $y = 0$, $x = 0$, and $x = \\pi$ is revolved about the $y$-axis.",
    answer: "2*pi^2",
    explanation: "Step 1: $V = 2\\pi\\int_0^{\\pi} x\\sin(x)\\,dx$. Step 2: Integration by parts: $u = x$, $dv = \\sin x\\,dx$, so $du = dx$, $v = -\\cos x$. Step 3: $= 2\\pi\\left[-x\\cos x + \\sin x\\right]_0^{\\pi} = 2\\pi[(\\pi + 0) - 0] = 2\\pi^2$. Final answer: $2\\pi^2$." }),
  p({ id: "appint-arclength-5", topicId: "applications-of-integration", section: "arclength", type: "numeric", difficulty: "hard",
    prompt: "Find the arc length of $y = \\frac{x^2}{2} - \\frac{\\ln x}{4}$ from $x = 1$ to $x = e$.",
    answer: "(e^2-1)/2+1/4",
    explanation: "Step 1: $y' = x - \\frac{1}{4x}$. Step 2: $(y')^2 = x^2 - \\frac{1}{2} + \\frac{1}{16x^2}$. Step 3: $1+(y')^2 = x^2 + \\frac{1}{2} + \\frac{1}{16x^2} = \\left(x + \\frac{1}{4x}\\right)^2$. Step 4: $L = \\int_1^e\\left(x + \\frac{1}{4x}\\right)dx = \\left[\\frac{x^2}{2} + \\frac{\\ln x}{4}\\right]_1^e = \\left(\\frac{e^2}{2}+\\frac{1}{4}\\right) - \\frac{1}{2} = \\frac{e^2-1}{2}+\\frac{1}{4}$. Final answer: $\\frac{e^2-1}{2}+\\frac{1}{4}$." }),
  p({ id: "appint-parametric-5", topicId: "applications-of-integration", section: "parametric", type: "numeric", difficulty: "hard",
    prompt: "Find the area enclosed by the ellipse $x = 3\\cos(t)$, $y = 2\\sin(t)$ for $0 \\le t \\le 2\\pi$.",
    answer: "6*pi",
    explanation: "Step 1: $A = -\\int_0^{2\\pi} y\\,\\frac{dx}{dt}\\,dt = -\\int_0^{2\\pi} 2\\sin t \\cdot (-3\\sin t)\\,dt = 6\\int_0^{2\\pi}\\sin^2 t\\,dt$. Step 2: $\\int_0^{2\\pi}\\sin^2 t\\,dt = \\pi$. Step 3: $A = 6\\pi$. Final answer: $6\\pi$." }),
  p({ id: "appint-surfacearea-4", topicId: "applications-of-integration", section: "surfacearea", type: "numeric", difficulty: "hard",
    prompt: "Find the surface area when $y = x^3$ on $[0,1]$ is revolved about the $x$-axis.",
    answer: "pi*(10*sqrt(10)-1)/27",
    explanation: "Step 1: $y' = 3x^2$, $1+(y')^2 = 1+9x^4$. Step 2: $S = 2\\pi\\int_0^1 x^3\\sqrt{1+9x^4}\\,dx$. Let $u = 1 + 9x^4$, $du = 36x^3\\,dx$. Step 3: $S = 2\\pi\\int_1^{10}\\frac{\\sqrt{u}}{36}\\,du = \\frac{\\pi}{18}\\cdot\\frac{2}{3}u^{3/2}\\Big|_1^{10} = \\frac{\\pi}{27}(10\\sqrt{10}-1)$. Final answer: $\\frac{\\pi(10\\sqrt{10}-1)}{27}$." }),
  p({ id: "appint-surfacearea-5", topicId: "applications-of-integration", section: "surfacearea", type: "numeric", difficulty: "hard",
    prompt: "Find the surface area when $y = \\sqrt{4-x^2}$ on $[-1,1]$ is revolved about the $x$-axis.",
    answer: "8*pi",
    explanation: "Step 1: This is the upper semicircle of radius 2. $y' = \\frac{-x}{\\sqrt{4-x^2}}$. Step 2: $1+(y')^2 = \\frac{4}{4-x^2}$, so $\\sqrt{1+(y')^2} = \\frac{2}{\\sqrt{4-x^2}}$. Step 3: $S = 2\\pi\\int_{-1}^{1}\\sqrt{4-x^2}\\cdot\\frac{2}{\\sqrt{4-x^2}}\\,dx = 4\\pi\\int_{-1}^1 dx = 4\\pi(2) = 8\\pi$. Final answer: $8\\pi$." }),
  p({ id: "appint-work-4", topicId: "applications-of-integration", section: "work", type: "numeric", difficulty: "hard",
    prompt: "A cable weighing $2$ lb/ft is used to lift a $100$ lb load from the bottom of a $50$ ft shaft. Find the total work done.",
    answer: "7500",
    explanation: "Step 1: Work to lift the load: $100 \\cdot 50 = 5000$ ft-lb. Step 2: Work to lift the cable: at height $x$, remaining cable weighs $2(50-x)$. $W_{\\text{cable}} = \\int_0^{50}2(50-x)\\,dx = 2\\left[50x - \\frac{x^2}{2}\\right]_0^{50} = 2(2500 - 1250) = 2500$ ft-lb. Step 3: Total $= 5000 + 2500 = 7500$ ft-lb. Final answer: $7500$." }),
  p({ id: "appint-work-5", topicId: "applications-of-integration", section: "work", type: "numeric", difficulty: "hard",
    prompt: "A tank shaped like an inverted cone (radius $3$ m at top, height $6$ m) is full of water ($\\rho g = 9800$ N/m³). Find the work to pump all the water to the top.",
    answer: "264600*pi",
    explanation: "Step 1: Place origin at the apex. At height $y$, radius $r = y/2$ by similar triangles ($3/6$). Step 2: Slice volume $= \\pi(y/2)^2\\,dy = \\frac{\\pi y^2}{4}\\,dy$. Lift distance $= 6-y$. Step 3: $W = 9800\\int_0^6\\frac{\\pi y^2}{4}(6-y)\\,dy = 2450\\pi\\int_0^6(6y^2-y^3)\\,dy = 2450\\pi\\left[2y^3-\\frac{y^4}{4}\\right]_0^6 = 2450\\pi(432-324) = 2450\\pi \\cdot 108 = 264600\\pi$. Final answer: $264600\\pi$." }),
];
