import type { Problem } from "../shared-types";

const p = (problem: Problem) => problem;

export const derivativeProblems: Problem[] = [
  // --- Easy (15) ---
  p({ id: "deriv-rules-1", topicId: "derivatives", section: "rules", type: "numeric", difficulty: "easy",
    prompt: "Find $\\frac{d}{dx}(5x^3)$",
    answer: "15*x^2",
    explanation: "Step 1: Power rule: $\\frac{d}{dx}(x^n) = nx^{n-1}$. Step 2: $5 \\cdot 3x^{3-1} = 15x^2$. Final answer: $15x^2$." }),
  p({ id: "deriv-rules-2", topicId: "derivatives", section: "rules", type: "numeric", difficulty: "easy",
    prompt: "Find $\\frac{d}{dx}(x^4 + 2x)$",
    answer: "4*x^3+2",
    explanation: "Step 1: Differentiate term by term. Step 2: $\\frac{d}{dx}(x^4) = 4x^3$ and $\\frac{d}{dx}(2x) = 2$. Final answer: $4x^3 + 2$." }),
  p({ id: "deriv-chain-1", topicId: "derivatives", section: "chain", type: "numeric", difficulty: "easy",
    prompt: "Find $\\frac{d}{dx}(e^{3x})$",
    answer: "3*e^(3*x)",
    explanation: "Step 1: Chain rule: $\\frac{d}{dx}(e^{kx}) = ke^{kx}$. Step 2: Here $k=3$: $3e^{3x}$. Final answer: $3e^{3x}$." }),
  p({ id: "deriv-common-1", topicId: "derivatives", section: "common", type: "numeric", difficulty: "easy",
    prompt: "Find $\\frac{d}{dx}(\\sin(x))$",
    answer: "cos(x)",
    explanation: "Step 1: This is a fundamental derivative. Step 2: $\\frac{d}{dx}(\\sin x) = \\cos x$. Final answer: $\\cos(x)$." }),
  p({ id: "deriv-common-2", topicId: "derivatives", section: "common", type: "numeric", difficulty: "easy",
    prompt: "Find $\\frac{d}{dx}(\\ln(x))$",
    answer: "1/x",
    explanation: "Step 1: This is a fundamental derivative. Step 2: $\\frac{d}{dx}(\\ln x) = \\frac{1}{x}$. Final answer: $\\frac{1}{x}$." }),
  p({ id: "deriv-rules-3", topicId: "derivatives", section: "rules", type: "numeric", difficulty: "easy",
    prompt: "Find $\\frac{d}{dx}(7x^2 - 3x + 1)$",
    answer: "14*x-3",
    explanation: "Step 1: Term by term: $14x - 3 + 0$. Step 2: Constants differentiate to 0. Final answer: $14x - 3$." }),
  p({ id: "deriv-chain-2", topicId: "derivatives", section: "chain", type: "numeric", difficulty: "easy",
    prompt: "Find $\\frac{d}{dx}(\\cos(2x))$",
    answer: "-2*sin(2*x)",
    explanation: "Step 1: Chain rule: $\\frac{d}{dx}(\\cos(u)) = -\\sin(u) \\cdot u'$. Step 2: $u = 2x$, so $u' = 2$. Step 3: $-2\\sin(2x)$. Final answer: $-2\\sin(2x)$." }),
  p({ id: "deriv-rules-4", topicId: "derivatives", section: "rules", type: "numeric", difficulty: "easy",
    prompt: "Find $\\frac{d}{dx}(\\sqrt{x})$",
    answer: "1/(2*sqrt(x))",
    explanation: "Step 1: Rewrite $\\sqrt{x} = x^{1/2}$. Step 2: Power rule: $\\frac{1}{2}x^{-1/2} = \\frac{1}{2\\sqrt{x}}$. Final answer: $\\frac{1}{2\\sqrt{x}}$." }),
  p({ id: "deriv-common-3", topicId: "derivatives", section: "common", type: "numeric", difficulty: "easy",
    prompt: "Find $\\frac{d}{dx}(3e^x + 4)$",
    answer: "3*e^x",
    explanation: "Step 1: $\\frac{d}{dx}(e^x) = e^x$ and constants vanish. Step 2: $3e^x + 0 = 3e^x$. Final answer: $3e^x$." }),
  p({ id: "deriv-rules-5", topicId: "derivatives", section: "rules", type: "numeric", difficulty: "easy",
    prompt: "Find $\\frac{d}{dx}\\left(\\frac{1}{x}\\right)$",
    answer: "-1/x^2",
    explanation: "Step 1: Rewrite as $x^{-1}$. Step 2: Power rule: $-1 \\cdot x^{-2} = -\\frac{1}{x^2}$. Final answer: $-\\frac{1}{x^2}$." }),
  p({ id: "deriv-rules-6", topicId: "derivatives", section: "rules", type: "numeric", difficulty: "easy",
    prompt: "Find $\\frac{d}{dx}(x^5)$",
    answer: "5*x^4",
    explanation: "Step 1: Power rule: $5x^{5-1} = 5x^4$. Final answer: $5x^4$." }),
  p({ id: "deriv-common-4", topicId: "derivatives", section: "common", type: "numeric", difficulty: "easy",
    prompt: "Find $\\frac{d}{dx}(\\tan(x))$",
    answer: "sec(x)^2",
    explanation: "Step 1: Standard derivative: $\\frac{d}{dx}(\\tan x) = \\sec^2 x$. Final answer: $\\sec^2(x)$." }),
  p({ id: "deriv-rules-7", topicId: "derivatives", section: "rules", type: "numeric", difficulty: "easy",
    prompt: "If $f(x) = 2x^3$, find $f'(1)$",
    answer: "6",
    explanation: "Step 1: $f'(x) = 6x^2$. Step 2: $f'(1) = 6(1)^2 = 6$. Final answer: $6$." }),
  p({ id: "deriv-common-5", topicId: "derivatives", section: "common", type: "numeric", difficulty: "easy",
    prompt: "Find $\\frac{d}{dx}(4\\ln(x))$",
    answer: "4/x",
    explanation: "Step 1: $4 \\cdot \\frac{1}{x} = \\frac{4}{x}$. Final answer: $\\frac{4}{x}$." }),
  p({ id: "deriv-common-6", topicId: "derivatives", section: "common", type: "numeric", difficulty: "easy",
    prompt: "Find $\\frac{d}{dx}(x^2 + e^x)$",
    answer: "2*x+e^x",
    explanation: "Step 1: Differentiate each term. Step 2: $2x + e^x$. Final answer: $2x + e^x$." }),
  // --- Medium (15) ---
  p({ id: "deriv-product-1", topicId: "derivatives", section: "product", type: "numeric", difficulty: "medium",
    prompt: "Find $\\frac{d}{dx}(x^2 \\sin(x))$",
    answer: "2*x*sin(x)+x^2*cos(x)",
    explanation: "Step 1: Product rule: $(fg)' = f'g + fg'$. Step 2: $f = x^2$, $g = \\sin x$. Step 3: $2x\\sin(x) + x^2\\cos(x)$. Final answer: $2x\\sin(x) + x^2\\cos(x)$." }),
  p({ id: "deriv-quotient-1", topicId: "derivatives", section: "quotient", type: "numeric", difficulty: "medium",
    prompt: "Find $\\frac{d}{dx}\\left(\\frac{x}{x+1}\\right)$",
    answer: "1/(x+1)^2",
    explanation: "Step 1: Quotient rule: $\\frac{(x+1)(1) - x(1)}{(x+1)^2}$. Step 2: $\\frac{x+1-x}{(x+1)^2} = \\frac{1}{(x+1)^2}$. Final answer: $\\frac{1}{(x+1)^2}$." }),
  p({ id: "deriv-chain-3", topicId: "derivatives", section: "chain", type: "numeric", difficulty: "medium",
    prompt: "Find $\\frac{d}{dx}(\\ln(x^2 + 1))$",
    answer: "2*x/(x^2+1)",
    explanation: "Step 1: Chain rule: $\\frac{1}{x^2+1} \\cdot \\frac{d}{dx}(x^2+1)$. Step 2: $\\frac{2x}{x^2+1}$. Final answer: $\\frac{2x}{x^2+1}$." }),
  p({ id: "deriv-chain-4", topicId: "derivatives", section: "chain", type: "numeric", difficulty: "medium",
    prompt: "Find $\\frac{d}{dx}(e^{x^2})$",
    answer: "2*x*e^(x^2)",
    explanation: "Step 1: Chain rule: $e^{x^2} \\cdot \\frac{d}{dx}(x^2) = 2x \\cdot e^{x^2}$. Final answer: $2xe^{x^2}$." }),
  p({ id: "deriv-chain-5", topicId: "derivatives", section: "chain", type: "numeric", difficulty: "medium",
    prompt: "Find $\\frac{d}{dx}(\\sin^2(x))$",
    answer: "2*sin(x)*cos(x)",
    explanation: "Step 1: Chain rule on $(\\sin x)^2$: $2\\sin(x) \\cdot \\cos(x)$. Step 2: This also equals $\\sin(2x)$. Final answer: $2\\sin(x)\\cos(x)$." }),
  p({ id: "deriv-product-2", topicId: "derivatives", section: "product", type: "numeric", difficulty: "medium",
    prompt: "Find $\\frac{d}{dx}(x e^x)$",
    answer: "e^x+x*e^x",
    explanation: "Step 1: Product rule: $1 \\cdot e^x + x \\cdot e^x$. Step 2: Factor: $e^x(1+x)$. Final answer: $e^x + xe^x$." }),
  p({ id: "deriv-quotient-2", topicId: "derivatives", section: "quotient", type: "numeric", difficulty: "medium",
    prompt: "Find $\\frac{d}{dx}\\left(\\frac{\\sin(x)}{x}\\right)$",
    answer: "(x*cos(x)-sin(x))/x^2",
    explanation: "Step 1: Quotient rule: $\\frac{x\\cos(x) - \\sin(x)(1)}{x^2}$. Step 2: $\\frac{x\\cos(x) - \\sin(x)}{x^2}$. Final answer: $\\frac{x\\cos(x) - \\sin(x)}{x^2}$." }),
  p({ id: "deriv-chain-6", topicId: "derivatives", section: "chain", type: "numeric", difficulty: "medium",
    prompt: "Find $\\frac{d}{dx}(\\sqrt{x^2 + 9})$",
    answer: "x/sqrt(x^2+9)",
    explanation: "Step 1: Chain rule on $(x^2+9)^{1/2}$: $\\frac{1}{2}(x^2+9)^{-1/2} \\cdot 2x$. Step 2: $\\frac{x}{\\sqrt{x^2+9}}$. Final answer: $\\frac{x}{\\sqrt{x^2+9}}$." }),
  p({ id: "deriv-invtrig-1", topicId: "derivatives", section: "invtrig", type: "numeric", difficulty: "medium",
    prompt: "Find $\\frac{d}{dx}(\\arctan(x))$",
    answer: "1/(1+x^2)",
    explanation: "Step 1: This is a standard derivative. Step 2: $\\frac{d}{dx}(\\arctan x) = \\frac{1}{1+x^2}$. Final answer: $\\frac{1}{1+x^2}$." }),
  p({ id: "deriv-graphical-1", topicId: "derivatives", section: "graphical", type: "numeric", difficulty: "medium",
    prompt: "If $f(x) = x^3 - 3x$, find the $x$-values where $f'(x) = 0$",
    answer: "1,-1",
    explanation: "Step 1: $f'(x) = 3x^2 - 3$. Step 2: Set to 0: $3x^2 - 3 = 0 \\Rightarrow x^2 = 1 \\Rightarrow x = \\pm 1$. Final answer: $x = 1, -1$." }),
  p({ id: "deriv-product-3", topicId: "derivatives", section: "product", type: "numeric", difficulty: "medium",
    prompt: "Find $\\frac{d}{dx}(x^2 \\ln(x))$",
    answer: "2*x*ln(x)+x",
    explanation: "Step 1: Product rule: $2x \\ln(x) + x^2 \\cdot \\frac{1}{x}$. Step 2: $2x\\ln(x) + x$. Final answer: $2x\\ln(x) + x$." }),
  p({ id: "deriv-chain-7", topicId: "derivatives", section: "chain", type: "numeric", difficulty: "medium",
    prompt: "Find $\\frac{d}{dx}(\\cos(x^3))$",
    answer: "-3*x^2*sin(x^3)",
    explanation: "Step 1: Chain rule: $-\\sin(x^3) \\cdot 3x^2$. Final answer: $-3x^2\\sin(x^3)$." }),
  p({ id: "deriv-higherorder-1", topicId: "derivatives", section: "higherorder", type: "numeric", difficulty: "medium",
    prompt: "Find $\\frac{d^2}{dx^2}(x^4)$ (second derivative)",
    answer: "12*x^2",
    explanation: "Step 1: First derivative: $4x^3$. Step 2: Second derivative: $12x^2$. Final answer: $12x^2$." }),
  p({ id: "deriv-chain-8", topicId: "derivatives", section: "chain", type: "numeric", difficulty: "medium",
    prompt: "Find $\\frac{d}{dx}(e^{-x^2})$",
    answer: "-2*x*e^(-x^2)",
    explanation: "Step 1: Chain rule: $e^{-x^2} \\cdot (-2x) = -2xe^{-x^2}$. Final answer: $-2xe^{-x^2}$." }),
  p({ id: "deriv-chain-9", topicId: "derivatives", section: "chain", type: "numeric", difficulty: "medium",
    prompt: "Find $\\frac{d}{dx}(\\ln(\\sin(x)))$",
    answer: "cos(x)/sin(x)",
    explanation: "Step 1: Chain rule: $\\frac{1}{\\sin(x)} \\cdot \\cos(x) = \\frac{\\cos x}{\\sin x} = \\cot(x)$. Final answer: $\\frac{\\cos(x)}{\\sin(x)}$." }),
  // --- Hard (10) ---
  p({ id: "deriv-implicit-1", topicId: "derivatives", section: "implicit", type: "numeric", difficulty: "hard",
    prompt: "Find $\\frac{dy}{dx}$ if $x^2 + y^2 = 25$ (implicit differentiation)",
    answer: "-x/y",
    explanation: "Step 1: Differentiate both sides: $2x + 2y\\frac{dy}{dx} = 0$. Step 2: Solve: $\\frac{dy}{dx} = -\\frac{x}{y}$. Final answer: $-\\frac{x}{y}$." }),
  p({ id: "deriv-logdiff-1", topicId: "derivatives", section: "logdiff", type: "numeric", difficulty: "hard",
    prompt: "Find $\\frac{d}{dx}(x^x)$ for $x > 0$",
    answer: "x^x*(ln(x)+1)",
    explanation: "Step 1: Let $y = x^x$. Take $\\ln$: $\\ln y = x\\ln x$. Step 2: Differentiate: $\\frac{y'}{y} = \\ln x + 1$. Step 3: $y' = x^x(\\ln x + 1)$. Final answer: $x^x(\\ln x + 1)$." }),
  p({ id: "deriv-implicit-2", topicId: "derivatives", section: "implicit", type: "numeric", difficulty: "hard",
    prompt: "Find $\\frac{dy}{dx}$ if $e^{xy} = x + y$",
    answer: "(1-y*e^(xy))/(e^(xy)-1)",
    explanation: "Step 1: Differentiate: $e^{xy}(y + xy') = 1 + y'$. Step 2: Expand: $ye^{xy} + xy'e^{xy} = 1 + y'$. Step 3: Collect $y'$: $y'(xe^{xy} - 1) = 1 - ye^{xy}$. Step 4: $y' = \\frac{1 - ye^{xy}}{xe^{xy} - 1}$. Final answer: $\\frac{1 - ye^{xy}}{e^{xy} - 1}$ (when $x=1$)." }),
  p({ id: "deriv-invtrig-2", topicId: "derivatives", section: "invtrig", type: "numeric", difficulty: "hard",
    prompt: "Find $\\frac{d}{dx}(\\arcsin(2x))$",
    answer: "2/sqrt(1-4*x^2)",
    explanation: "Step 1: Chain rule: $\\frac{1}{\\sqrt{1-(2x)^2}} \\cdot 2 = \\frac{2}{\\sqrt{1-4x^2}}$. Final answer: $\\frac{2}{\\sqrt{1-4x^2}}$." }),
  p({ id: "deriv-quotient-3", topicId: "derivatives", section: "quotient", type: "numeric", difficulty: "hard",
    prompt: "If $f(x) = \\frac{e^x}{1+e^x}$, find $f'(x)$",
    answer: "e^x/(1+e^x)^2",
    explanation: "Step 1: Quotient rule: $\\frac{e^x(1+e^x) - e^x \\cdot e^x}{(1+e^x)^2}$. Step 2: $\\frac{e^x + e^{2x} - e^{2x}}{(1+e^x)^2} = \\frac{e^x}{(1+e^x)^2}$. Final answer: $\\frac{e^x}{(1+e^x)^2}$." }),
  p({ id: "deriv-higherorder-2", topicId: "derivatives", section: "higherorder", type: "numeric", difficulty: "hard",
    prompt: "Find the third derivative of $f(x) = e^{2x}$",
    answer: "8*e^(2*x)",
    explanation: "Step 1: $f'(x) = 2e^{2x}$. Step 2: $f''(x) = 4e^{2x}$. Step 3: $f'''(x) = 8e^{2x}$. Final answer: $8e^{2x}$." }),
  p({ id: "deriv-implicit-3", topicId: "derivatives", section: "implicit", type: "numeric", difficulty: "hard",
    prompt: "Find $\\frac{dy}{dx}$ if $\\sin(xy) = x$",
    answer: "(1-y*cos(xy))/(x*cos(xy))",
    explanation: "Step 1: Differentiate: $\\cos(xy)(y + xy') = 1$. Step 2: $y\\cos(xy) + xy'\\cos(xy) = 1$. Step 3: $y' = \\frac{1 - y\\cos(xy)}{x\\cos(xy)}$. Final answer: $\\frac{1 - y\\cos(xy)}{x\\cos(xy)}$." }),
  p({ id: "deriv-chain-10", topicId: "derivatives", section: "chain", type: "numeric", difficulty: "hard",
    prompt: "Find $\\frac{d}{dx}\\left(\\int_0^{x^2} e^{t^2} dt\\right)$",
    answer: "2*x*e^(x^4)",
    explanation: "Step 1: By the Fundamental Theorem of Calculus with chain rule: $\\frac{d}{dx}\\int_0^{g(x)} f(t)\\,dt = f(g(x))\\cdot g'(x)$. Step 2: $f(t) = e^{t^2}$, $g(x) = x^2$, $g'(x) = 2x$. Step 3: $e^{(x^2)^2} \\cdot 2x = 2xe^{x^4}$. Final answer: $2xe^{x^4}$." }),
  p({ id: "deriv-chain-11", topicId: "derivatives", section: "chain", type: "numeric", difficulty: "hard",
    prompt: "Find $\\frac{d}{dx}(\\ln(\\sqrt{x^2+1}))$",
    answer: "x/(x^2+1)",
    explanation: "Step 1: Simplify: $\\ln(x^2+1)^{1/2} = \\frac{1}{2}\\ln(x^2+1)$. Step 2: $\\frac{1}{2} \\cdot \\frac{2x}{x^2+1} = \\frac{x}{x^2+1}$. Final answer: $\\frac{x}{x^2+1}$." }),
  p({ id: "deriv-common-7", topicId: "derivatives", section: "common", type: "numeric", difficulty: "hard",
    prompt: "Find $\\frac{d}{dx}(\\sec(x))$",
    answer: "sec(x)*tan(x)",
    explanation: "Step 1: $\\sec(x) = \\frac{1}{\\cos(x)}$. Step 2: Quotient rule: $\\frac{\\sin(x)}{\\cos^2(x)} = \\frac{1}{\\cos x} \\cdot \\frac{\\sin x}{\\cos x} = \\sec x \\tan x$. Final answer: $\\sec(x)\\tan(x)$." }),

  // =========================================================================
  // GAP-FILLING: definition — The definition of derivative
  // =========================================================================
  p({ id: "deriv-definition-1", topicId: "derivatives", section: "definition", type: "numeric", difficulty: "easy",
    prompt: "Using the limit definition, find $f'(x)$ for $f(x) = 3x + 1$. That is, compute $\\lim_{h\\to 0}\\frac{f(x+h)-f(x)}{h}$.",
    answer: "3",
    explanation: "Step 1: $f(x+h) = 3(x+h)+1 = 3x+3h+1$. Step 2: $f(x+h)-f(x) = 3h$. Step 3: $\\frac{3h}{h} = 3$. Step 4: $\\lim_{h\\to 0} 3 = 3$. Final answer: $3$." }),
  p({ id: "deriv-definition-2", topicId: "derivatives", section: "definition", type: "numeric", difficulty: "medium",
    prompt: "Use the limit definition $f'(x)=\\lim_{h\\to 0}\\frac{f(x+h)-f(x)}{h}$ to find $f'(x)$ for $f(x)=x^2$.",
    answer: "2*x",
    explanation: "Step 1: $f(x+h)=(x+h)^2=x^2+2xh+h^2$. Step 2: $f(x+h)-f(x)=2xh+h^2$. Step 3: $\\frac{2xh+h^2}{h}=2x+h$. Step 4: $\\lim_{h\\to 0}(2x+h)=2x$. Final answer: $2x$." }),

  // =========================================================================
  // GAP-FILLING: tangent — Tangent lines and linearization
  // =========================================================================
  p({ id: "deriv-tangent-1", topicId: "derivatives", section: "tangent", type: "numeric", difficulty: "easy",
    prompt: "Find the equation of the tangent line to $f(x)=x^2$ at $x=2$. Give the $y$-intercept of this line.",
    answer: "-4",
    explanation: "Step 1: $f(2)=4$, $f'(x)=2x$, $f'(2)=4$. Step 2: Tangent line: $y-4=4(x-2)$, i.e. $y=4x-4$. Step 3: The $y$-intercept is $-4$. Final answer: $-4$." }),
  p({ id: "deriv-tangent-2", topicId: "derivatives", section: "tangent", type: "numeric", difficulty: "medium",
    prompt: "Find the equation of the tangent line to $f(x)=\\sin(x)$ at $x=0$. What is the slope?",
    answer: "1",
    explanation: "Step 1: $f(0)=\\sin(0)=0$, $f'(x)=\\cos(x)$, $f'(0)=\\cos(0)=1$. Step 2: Tangent line: $y-0=1(x-0)$, i.e. $y=x$. Step 3: The slope is $1$. Final answer: $1$." }),

  // =========================================================================
  // GAP-FILLING: hyperbolic — Hyperbolic functions
  // =========================================================================
  p({ id: "deriv-hyperbolic-1", topicId: "derivatives", section: "hyperbolic", type: "numeric", difficulty: "easy",
    prompt: "Find $\\frac{d}{dx}(\\sinh(x))$",
    answer: "cosh(x)",
    explanation: "Step 1: $\\sinh(x) = \\frac{e^x - e^{-x}}{2}$. Step 2: $\\frac{d}{dx}\\sinh(x) = \\frac{e^x+e^{-x}}{2} = \\cosh(x)$. Final answer: $\\cosh(x)$." }),
  p({ id: "deriv-hyperbolic-2", topicId: "derivatives", section: "hyperbolic", type: "numeric", difficulty: "medium",
    prompt: "Find $\\frac{d}{dx}(\\cosh(2x))$",
    answer: "2*sinh(2*x)",
    explanation: "Step 1: $\\frac{d}{dx}\\cosh(u) = \\sinh(u) \\cdot u'$ by the chain rule. Step 2: Here $u=2x$, so $u'=2$. Step 3: $\\sinh(2x) \\cdot 2 = 2\\sinh(2x)$. Final answer: $2\\sinh(2x)$." }),
];
