import type { Problem } from "../shared-types";

const p = (problem: Problem) => problem;

export const differentialEquationProblems: Problem[] = [
  // --- Easy (15) ---
  p({ id: "de-separable-1", topicId: "differential-equations", section: "separable", type: "numeric", difficulty: "easy",
    prompt: "Solve $\\frac{dy}{dx} = 3$",
    answer: "y=3*x+C",
    explanation: "Step 1: Integrate both sides: $y = \\int 3\\,dx = 3x + C$. Final answer: $y = 3x + C$." }),
  p({ id: "de-separable-2", topicId: "differential-equations", section: "separable", type: "numeric", difficulty: "easy",
    prompt: "Solve $\\frac{dy}{dx} = 2x$",
    answer: "y=x^2+C",
    explanation: "Step 1: $y = \\int 2x\\,dx = x^2 + C$. Final answer: $y = x^2 + C$." }),
  p({ id: "de-separable-3", topicId: "differential-equations", section: "separable", type: "numeric", difficulty: "easy",
    prompt: "Solve $\\frac{dy}{dx} = e^x$",
    answer: "y=e^x+C",
    explanation: "Step 1: $y = \\int e^x\\,dx = e^x + C$. Final answer: $y = e^x + C$." }),
  p({ id: "de-expgrowth-1", topicId: "differential-equations", section: "expgrowth", type: "numeric", difficulty: "easy",
    prompt: "Solve $\\frac{dy}{dx} = 2y$ (general solution)",
    answer: "y=Ce^(2x)",
    explanation: "Step 1: Separate: $\\frac{dy}{y} = 2\\,dx$. Step 2: $\\ln|y| = 2x + C_1$. Step 3: $y = Ce^{2x}$. Final answer: $y = Ce^{2x}$." }),
  p({ id: "de-expgrowth-2", topicId: "differential-equations", section: "expgrowth", type: "numeric", difficulty: "easy",
    prompt: "Solve $\\frac{dy}{dx} = -y$ (general solution)",
    answer: "y=Ce^(-x)",
    explanation: "Step 1: Separate: $\\frac{dy}{y} = -dx$. Step 2: $\\ln|y| = -x + C_1$. Step 3: $y = Ce^{-x}$. Final answer: $y = Ce^{-x}$." }),
  p({ id: "de-ivp-1", topicId: "differential-equations", section: "ivp", type: "numeric", difficulty: "easy",
    prompt: "Solve $\\frac{dy}{dx} = x^2$ with $y(0) = 1$.",
    answer: "y=x^3/3+1",
    explanation: "Step 1: $y = x^3/3 + C$. Step 2: $y(0) = 1 \\Rightarrow C = 1$. Final answer: $y = \\frac{x^3}{3} + 1$." }),
  p({ id: "de-separable-4", topicId: "differential-equations", section: "separable", type: "numeric", difficulty: "easy",
    prompt: "Solve $\\frac{dy}{dx} = \\cos(x)$",
    answer: "y=sin(x)+C",
    explanation: "Step 1: $y = \\int\\cos x\\,dx = \\sin x + C$. Final answer: $y = \\sin(x) + C$." }),
  p({ id: "de-expgrowth-3", topicId: "differential-equations", section: "expgrowth", type: "numeric", difficulty: "easy",
    prompt: "If $y' = 5y$ and $y(0) = 2$, find $y(t)$.",
    answer: "y=2*e^(5*t)",
    explanation: "Step 1: General solution: $y = Ce^{5t}$. Step 2: $y(0) = C = 2$. Final answer: $y = 2e^{5t}$." }),
  p({ id: "de-separable-5", topicId: "differential-equations", section: "separable", type: "numeric", difficulty: "easy",
    prompt: "Solve $\\frac{dy}{dx} = 3x^2 + 1$",
    answer: "y=x^3+x+C",
    explanation: "Step 1: $y = x^3 + x + C$. Final answer: $y = x^3 + x + C$." }),
  p({ id: "de-intro-1", topicId: "differential-equations", section: "intro", type: "mcq", difficulty: "easy",
    prompt: "What type of DE is $\\frac{dy}{dx} = xy$?",
    answer: "Separable", choices: ["Separable", "Linear (non-separable)", "Exact", "Bernoulli"],
    explanation: "Step 1: We can write $\\frac{dy}{y} = x\\,dx$. Step 2: Variables separate. Final answer: Separable." }),
  p({ id: "de-separable-6", topicId: "differential-equations", section: "separable", type: "numeric", difficulty: "easy",
    prompt: "Solve $\\frac{dy}{dx} = \\frac{1}{x}$ for $x > 0$.",
    answer: "y=ln(x)+C",
    explanation: "Step 1: $y = \\int\\frac{1}{x}dx = \\ln(x) + C$. Final answer: $y = \\ln(x) + C$." }),
  p({ id: "de-expgrowth-4", topicId: "differential-equations", section: "expgrowth", type: "numeric", difficulty: "easy",
    prompt: "Solve $y' = -3y$ with $y(0)=10$.",
    answer: "y=10*e^(-3*t)",
    explanation: "Step 1: General: $y = Ce^{-3t}$. Step 2: $C = 10$. Final answer: $y = 10e^{-3t}$." }),
  p({ id: "de-separable-7", topicId: "differential-equations", section: "separable", type: "numeric", difficulty: "easy",
    prompt: "Solve $\\frac{dy}{dx} = 6x^2 - 2x$",
    answer: "y=2*x^3-x^2+C",
    explanation: "Step 1: $y = 2x^3 - x^2 + C$. Final answer: $y = 2x^3 - x^2 + C$." }),
  p({ id: "de-intro-2", topicId: "differential-equations", section: "intro", type: "mcq", difficulty: "easy",
    prompt: "Is $y = e^{3x}$ a solution to $y' = 3y$?",
    answer: "Yes", choices: ["Yes", "No"],
    explanation: "Step 1: $y' = 3e^{3x}$ and $3y = 3e^{3x}$. Step 2: They're equal. Final answer: Yes." }),
  p({ id: "de-expgrowth-5", topicId: "differential-equations", section: "expgrowth", type: "numeric", difficulty: "easy",
    prompt: "A population doubles every hour. If $P(0)=100$, find $P(t)$.",
    answer: "P=100*2^t",
    explanation: "Step 1: Exponential growth with doubling time 1 hour. Step 2: $P(t) = 100 \\cdot 2^t$. Final answer: $P = 100 \\cdot 2^t$." }),
  // --- Medium (15) ---
  p({ id: "de-separable-8", topicId: "differential-equations", section: "separable", type: "numeric", difficulty: "medium",
    prompt: "Solve $\\frac{dy}{dx} = xy$ (general solution).",
    answer: "y=Ce^(x^2/2)",
    explanation: "Step 1: Separate: $\\frac{dy}{y} = x\\,dx$. Step 2: $\\ln|y| = \\frac{x^2}{2} + C_1$. Step 3: $y = Ce^{x^2/2}$. Final answer: $y = Ce^{x^2/2}$." }),
  p({ id: "de-linear-1", topicId: "differential-equations", section: "linear", type: "numeric", difficulty: "medium",
    prompt: "Solve $\\frac{dy}{dx} + y = e^x$.",
    answer: "y=e^x/2+Ce^(-x)",
    explanation: "Step 1: Integrating factor: $\\mu = e^{\\int 1\\,dx} = e^x$. Step 2: $(e^x y)' = e^{2x}$. Step 3: $e^x y = \\frac{e^{2x}}{2} + C$. Step 4: $y = \\frac{e^x}{2} + Ce^{-x}$. Final answer: $y = \\frac{e^x}{2} + Ce^{-x}$." }),
  p({ id: "de-separable-9", topicId: "differential-equations", section: "separable", type: "numeric", difficulty: "medium",
    prompt: "Solve $\\frac{dy}{dx} = \\frac{y}{x}$ for $x>0$.",
    answer: "y=Cx",
    explanation: "Step 1: Separate: $\\frac{dy}{y} = \\frac{dx}{x}$. Step 2: $\\ln|y| = \\ln|x| + C_1$. Step 3: $y = Cx$. Final answer: $y = Cx$." }),
  p({ id: "de-linear-2", topicId: "differential-equations", section: "linear", type: "numeric", difficulty: "medium",
    prompt: "Solve $y' + 2y = 6$ (general solution).",
    answer: "y=3+Ce^(-2x)",
    explanation: "Step 1: Integrating factor $\\mu = e^{2x}$. Step 2: $(e^{2x}y)' = 6e^{2x}$. Step 3: $e^{2x}y = 3e^{2x}+C$. Step 4: $y = 3 + Ce^{-2x}$. Final answer: $y = 3 + Ce^{-2x}$." }),
  p({ id: "de-separable-10", topicId: "differential-equations", section: "separable", type: "numeric", difficulty: "medium",
    prompt: "Solve $\\frac{dy}{dx} = y^2$ with $y(0) = 1$.",
    answer: "y=1/(1-x)",
    explanation: "Step 1: Separate: $y^{-2}dy = dx$. Step 2: $-1/y = x + C$. Step 3: $y(0)=1 \\Rightarrow C=-1$. Step 4: $y = \\frac{1}{1-x}$. Final answer: $y = \\frac{1}{1-x}$." }),
  p({ id: "de-expgrowth-6", topicId: "differential-equations", section: "expgrowth", type: "numeric", difficulty: "medium",
    prompt: "A substance decays at rate proportional to amount: $N'=-0.05N$, $N(0)=200$. Find the half-life.",
    answer: "ln(2)/0.05",
    explanation: "Step 1: $N = 200e^{-0.05t}$. Step 2: Half-life when $N = 100$: $e^{-0.05t} = 1/2$. Step 3: $t = \\frac{\\ln 2}{0.05}$. Final answer: $\\frac{\\ln 2}{0.05} \\approx 13.86$." }),
  p({ id: "de-separable-11", topicId: "differential-equations", section: "separable", type: "numeric", difficulty: "medium",
    prompt: "Solve $\\frac{dy}{dx} = \\frac{x}{y}$ with $y > 0$ (general solution).",
    answer: "y=sqrt(x^2+C)",
    explanation: "Step 1: $y\\,dy = x\\,dx$. Step 2: $\\frac{y^2}{2} = \\frac{x^2}{2} + C_1$. Step 3: $y^2 = x^2 + C$, so $y = \\sqrt{x^2+C}$. Final answer: $y = \\sqrt{x^2+C}$." }),
  p({ id: "de-expgrowth-7", topicId: "differential-equations", section: "expgrowth", type: "numeric", difficulty: "medium",
    prompt: "Solve $y' - 3y = 0$.",
    answer: "y=Ce^(3x)",
    explanation: "Step 1: This is $y'=3y$. Step 2: $y = Ce^{3x}$. Final answer: $y = Ce^{3x}$." }),
  p({ id: "de-linear-3", topicId: "differential-equations", section: "linear", type: "numeric", difficulty: "medium",
    prompt: "Solve $\\frac{dy}{dx} + \\frac{y}{x} = x$ for $x > 0$.",
    answer: "y=x^2/3+C/x",
    explanation: "Step 1: Integrating factor $\\mu = e^{\\int 1/x\\,dx} = x$. Step 2: $(xy)' = x^2$. Step 3: $xy = x^3/3 + C$. Step 4: $y = x^2/3 + C/x$. Final answer: $y = \\frac{x^2}{3} + \\frac{C}{x}$." }),
  p({ id: "de-separable-12", topicId: "differential-equations", section: "separable", type: "numeric", difficulty: "medium",
    prompt: "Solve $\\frac{dy}{dx} = e^{x+y}$ (hint: $e^{x+y}=e^x e^y$).",
    answer: "y=-ln(C-e^x)",
    explanation: "Step 1: $e^{-y}dy = e^x dx$. Step 2: $-e^{-y} = e^x + C_1$. Step 3: $e^{-y} = C - e^x$. Step 4: $y = -\\ln(C-e^x)$. Final answer: $y = -\\ln(C-e^x)$." }),
  p({ id: "de-cooling-1", topicId: "differential-equations", section: "cooling", type: "mcq", difficulty: "medium",
    prompt: "Newton's law of cooling says $T' = -k(T-T_s)$ where $T_s$ is ambient temp. What type of solution does this have?",
    answer: "Exponential decay toward $T_s$", choices: ["Exponential decay toward $T_s$", "Exponential growth", "Oscillating", "Linear"],
    explanation: "Step 1: Solution is $T = T_s + (T_0 - T_s)e^{-kt}$. Step 2: Temperature exponentially approaches ambient. Final answer: Exponential decay toward $T_s$." }),
  p({ id: "de-secondorder-1", topicId: "differential-equations", section: "secondorder", type: "numeric", difficulty: "medium",
    prompt: "Solve $y'' = 0$ (general solution).",
    answer: "y=Ax+B",
    explanation: "Step 1: Integrate once: $y' = A$. Step 2: Integrate again: $y = Ax + B$. Final answer: $y = Ax + B$." }),
  p({ id: "de-secondorder-2", topicId: "differential-equations", section: "secondorder", type: "numeric", difficulty: "medium",
    prompt: "Solve $y'' + y = 0$ (general solution).",
    answer: "y=Acos(x)+Bsin(x)",
    explanation: "Step 1: Characteristic equation: $r^2+1=0 \\Rightarrow r=\\pm i$. Step 2: General solution with complex roots: $y = A\\cos(x) + B\\sin(x)$. Final answer: $y = A\\cos(x) + B\\sin(x)$." }),
  p({ id: "de-secondorder-3", topicId: "differential-equations", section: "secondorder", type: "numeric", difficulty: "medium",
    prompt: "Solve $y'' - y = 0$.",
    answer: "y=Ae^x+Be^(-x)",
    explanation: "Step 1: $r^2-1=0 \\Rightarrow r=\\pm 1$. Step 2: $y = Ae^x + Be^{-x}$. Final answer: $y = Ae^x + Be^{-x}$." }),
  p({ id: "de-secondorder-4", topicId: "differential-equations", section: "secondorder", type: "numeric", difficulty: "medium",
    prompt: "Solve $y'' - 4y' + 4y = 0$.",
    answer: "y=(A+Bx)e^(2x)",
    explanation: "Step 1: $r^2-4r+4=(r-2)^2=0$, repeated root $r=2$. Step 2: $y = (A+Bx)e^{2x}$. Final answer: $y = (A+Bx)e^{2x}$." }),
  // --- Hard (10) ---
  p({ id: "de-ivp-2", topicId: "differential-equations", section: "ivp", type: "numeric", difficulty: "hard",
    prompt: "Solve $y'' + 4y = 0$ with $y(0)=1$ and $y'(0)=0$.",
    answer: "y=cos(2x)",
    explanation: "Step 1: $r^2+4=0 \\Rightarrow r=\\pm 2i$. Step 2: $y = A\\cos(2x)+B\\sin(2x)$. Step 3: $y(0)=A=1$. $y'(0)=2B=0 \\Rightarrow B=0$. Final answer: $y = \\cos(2x)$." }),
  p({ id: "de-separable-13", topicId: "differential-equations", section: "separable", type: "numeric", difficulty: "hard",
    prompt: "Solve $y' = \\frac{x^2+y^2}{xy}$ (hint: let $v = y/x$).",
    answer: "y^2=x^2(2*ln|x|+C)",
    explanation: "Step 1: Let $v = y/x$, so $y = vx$ and $y' = v + xv'$. Step 2: Substitute: $v + xv' = \\frac{x^2+v^2x^2}{vx^2} = \\frac{1+v^2}{v}$. Step 3: $xv' = \\frac{1}{v}$, so $v\\,dv = \\frac{dx}{x}$. Step 4: $v^2/2 = \\ln|x|+C_1$. Step 5: $y^2/x^2 = 2\\ln|x| + C$, so $y^2 = x^2(2\\ln|x|+C)$. Final answer: $y^2 = x^2(2\\ln|x|+C)$." }),
  p({ id: "de-bernoulli-1", topicId: "differential-equations", section: "bernoulli", type: "numeric", difficulty: "hard",
    prompt: "Solve the Bernoulli equation $y' + y = y^2$.",
    answer: "y=1/(1+Ce^x)",
    explanation: "Step 1: Divide by $y^2$: $y^{-2}y' + y^{-1} = 1$. Step 2: Let $v = y^{-1}$, $v' = -y^{-2}y'$. Step 3: $-v' + v = 1$, or $v' - v = -1$. Step 4: IF $= e^{-x}$: $(e^{-x}v)' = -e^{-x}$. Step 5: $v = 1 + Ce^x$, so $y = \\frac{1}{1+Ce^x}$. Final answer: $y = \\frac{1}{1+Ce^x}$." }),
  p({ id: "de-secondorder-5", topicId: "differential-equations", section: "secondorder", type: "numeric", difficulty: "hard",
    prompt: "Solve $y'' - 5y' + 6y = 0$.",
    answer: "y=Ae^(2x)+Be^(3x)",
    explanation: "Step 1: $r^2-5r+6 = (r-2)(r-3) = 0$. Step 2: $r=2,3$. Step 3: $y = Ae^{2x}+Be^{3x}$. Final answer: $y = Ae^{2x}+Be^{3x}$." }),
  p({ id: "de-secondorder-6", topicId: "differential-equations", section: "secondorder", type: "numeric", difficulty: "hard",
    prompt: "Solve $y'' + 2y' + 5y = 0$.",
    answer: "y=e^(-x)*(Acos(2x)+Bsin(2x))",
    explanation: "Step 1: $r^2+2r+5=0 \\Rightarrow r = -1 \\pm 2i$. Step 2: $y = e^{-x}(A\\cos 2x + B\\sin 2x)$. Final answer: $y = e^{-x}(A\\cos(2x)+B\\sin(2x))$." }),
  p({ id: "de-logistic-1", topicId: "differential-equations", section: "logistic", type: "numeric", difficulty: "hard",
    prompt: "Solve the logistic equation $P' = 0.1P(1-P/1000)$ with $P(0) = 100$. What is the carrying capacity?",
    answer: "1000",
    explanation: "Step 1: The logistic equation $P' = rP(1-P/K)$ has carrying capacity $K$. Step 2: Here $K=1000$. The population approaches this as $t\\to\\infty$. Final answer: $1000$." }),
  p({ id: "de-nonhomog-1", topicId: "differential-equations", section: "nonhomog", type: "numeric", difficulty: "hard",
    prompt: "Solve $y'' + y = \\sin(x)$ (find a particular solution).",
    answer: "y_p=-x*cos(x)/2",
    explanation: "Step 1: Since $\\sin(x)$ is a solution of the homogeneous equation, use $y_p = x(A\\cos x + B\\sin x)$. Step 2: Substituting and solving: $A = -1/2$, $B = 0$. Step 3: $y_p = -\\frac{x\\cos(x)}{2}$. Final answer: $y_p = -\\frac{x\\cos(x)}{2}$." }),
  p({ id: "de-separable-14", topicId: "differential-equations", section: "separable", type: "numeric", difficulty: "hard",
    prompt: "Solve $y' = y\\tan(x)$.",
    answer: "y=C*sec(x)",
    explanation: "Step 1: $\\frac{dy}{y} = \\tan(x)\\,dx$. Step 2: $\\ln|y| = -\\ln|\\cos x| + C_1 = \\ln|\\sec x| + C_1$. Step 3: $y = C\\sec(x)$. Final answer: $y = C\\sec(x)$." }),
  p({ id: "de-secondorder-7", topicId: "differential-equations", section: "secondorder", type: "numeric", difficulty: "hard",
    prompt: "Find the Wronskian of $y_1 = e^x$ and $y_2 = e^{2x}$.",
    answer: "e^(3x)",
    explanation: "Step 1: $W = \\begin{vmatrix} e^x & e^{2x} \\\\ e^x & 2e^{2x} \\end{vmatrix} = 2e^{3x} - e^{3x} = e^{3x}$. Final answer: $e^{3x}$." }),
  p({ id: "de-ivp-3", topicId: "differential-equations", section: "ivp", type: "numeric", difficulty: "hard",
    prompt: "Solve $y'' - y' - 6y = 0$ with $y(0) = 0$, $y'(0) = 5$.",
    answer: "y=e^(3x)-e^(-2x)",
    explanation: "Step 1: $r^2-r-6 = (r-3)(r+2) = 0$. Step 2: $y = Ae^{3x} + Be^{-2x}$. Step 3: $y(0)=A+B=0$ and $y'(0)=3A-2B=5$. Step 4: $B=-A$, so $3A+2A=5 \\Rightarrow A=1, B=-1$. Final answer: $y = e^{3x}-e^{-2x}$." }),

  // ===================================================================
  // GAP-FILLING: slopefields — Direction fields / slope fields
  // ===================================================================
  p({ id: "de-slopefields-1", topicId: "differential-equations", section: "slopefields", type: "mcq", difficulty: "medium",
    prompt: "Consider the slope field for $\\frac{dy}{dx} = x - y$. At the point $(2, 2)$, what is the slope of the line segment?",
    answer: "0", choices: ["0", "1", "-1", "2"],
    explanation: "Step 1: Substitute into $\\frac{dy}{dx} = x - y$. Step 2: At $(2,2)$: slope $= 2 - 2 = 0$. Step 3: The line segment at $(2,2)$ is horizontal. Final answer: $0$." }),
  p({ id: "de-slopefields-2", topicId: "differential-equations", section: "slopefields", type: "mcq", difficulty: "medium",
    prompt: "A slope field for $\\frac{dy}{dx} = y$ shows horizontal segments along which line?",
    answer: "y = 0", choices: ["y = 0", "x = 0", "y = x", "y = 1"],
    explanation: "Step 1: The slope is $\\frac{dy}{dx} = y$. Step 2: The slope equals zero when $y = 0$. Step 3: Along the $x$-axis ($y=0$), all line segments are horizontal. Final answer: $y = 0$." }),

  // ===================================================================
  // GAP-FILLING: springs — Springs and oscillations
  // ===================================================================
  p({ id: "de-springs-1", topicId: "differential-equations", section: "springs", type: "numeric", difficulty: "hard",
    prompt: "A spring-mass system satisfies $x'' + 9x = 0$ with $x(0) = 2$ and $x'(0) = 0$. Find $x(t)$.",
    answer: "x=2*cos(3*t)",
    explanation: "Step 1: Characteristic equation: $r^2 + 9 = 0 \\Rightarrow r = \\pm 3i$. Step 2: General solution: $x(t) = A\\cos(3t) + B\\sin(3t)$. Step 3: $x(0) = A = 2$. Step 4: $x'(t) = -3A\\sin(3t) + 3B\\cos(3t)$, so $x'(0) = 3B = 0 \\Rightarrow B = 0$. Final answer: $x = 2\\cos(3t)$." }),
  p({ id: "de-springs-2", topicId: "differential-equations", section: "springs", type: "numeric", difficulty: "hard",
    prompt: "A damped harmonic oscillator satisfies $x'' + 2x' + 5x = 0$ with $x(0) = 1$ and $x'(0) = 0$. What is the angular frequency of the oscillation?",
    answer: "2",
    explanation: "Step 1: Characteristic equation: $r^2 + 2r + 5 = 0$. Step 2: $r = \\frac{-2 \\pm \\sqrt{4-20}}{2} = -1 \\pm 2i$. Step 3: The solution has the form $x(t) = e^{-t}(A\\cos(2t) + B\\sin(2t))$. Step 4: The angular frequency of oscillation is $\\omega_d = 2$. Final answer: $2$." }),
];
