import type { Problem } from "../shared-types";

const p = (problem: Problem) => problem;

export const integralProblems: Problem[] = [
  // --- Easy (15) ---
  p({ id: "integ-toolbox-1", topicId: "integrals", section: "toolbox", type: "numeric", difficulty: "easy",
    prompt: "Compute $\\int x^3\\,dx$",
    answer: "x^4/4+C",
    explanation: "Step 1: Power rule: $\\int x^n\\,dx = \\frac{x^{n+1}}{n+1} + C$. Step 2: $\\frac{x^4}{4} + C$. Final answer: $\\frac{x^4}{4} + C$." }),
  p({ id: "integ-toolbox-2", topicId: "integrals", section: "toolbox", type: "numeric", difficulty: "easy",
    prompt: "Compute $\\int 4x\\,dx$",
    answer: "2*x^2+C",
    explanation: "Step 1: $4 \\cdot \\frac{x^2}{2} + C = 2x^2 + C$. Final answer: $2x^2 + C$." }),
  p({ id: "integ-toolbox-3", topicId: "integrals", section: "toolbox", type: "numeric", difficulty: "easy",
    prompt: "Compute $\\int e^x\\,dx$",
    answer: "e^x+C",
    explanation: "Step 1: The integral of $e^x$ is itself. Step 2: $e^x + C$. Final answer: $e^x + C$." }),
  p({ id: "integ-toolbox-4", topicId: "integrals", section: "toolbox", type: "numeric", difficulty: "easy",
    prompt: "Compute $\\int \\cos(x)\\,dx$",
    answer: "sin(x)+C",
    explanation: "Step 1: The integral of $\\cos(x)$ is $\\sin(x)$. Final answer: $\\sin(x) + C$." }),
  p({ id: "integ-toolbox-5", topicId: "integrals", section: "toolbox", type: "numeric", difficulty: "easy",
    prompt: "Compute $\\int \\frac{1}{x}\\,dx$",
    answer: "ln|x|+C",
    explanation: "Step 1: This is a fundamental integral. Step 2: $\\ln|x| + C$. Final answer: $\\ln|x| + C$." }),
  p({ id: "integ-toolbox-6", topicId: "integrals", section: "toolbox", type: "numeric", difficulty: "easy",
    prompt: "Compute $\\int 3x^2\\,dx$",
    answer: "x^3+C",
    explanation: "Step 1: $3 \\cdot \\frac{x^3}{3} + C = x^3 + C$. Final answer: $x^3 + C$." }),
  p({ id: "integ-toolbox-7", topicId: "integrals", section: "toolbox", type: "numeric", difficulty: "easy",
    prompt: "Compute $\\int \\sin(x)\\,dx$",
    answer: "-cos(x)+C",
    explanation: "Step 1: The integral of $\\sin(x)$ is $-\\cos(x)$. Final answer: $-\\cos(x) + C$." }),
  p({ id: "integ-ftc-1", topicId: "integrals", section: "ftc", type: "numeric", difficulty: "easy",
    prompt: "Evaluate $\\int_0^2 3x^2\\,dx$",
    answer: "8",
    explanation: "Step 1: Antiderivative is $x^3$. Step 2: $2^3 - 0^3 = 8$. Final answer: $8$." }),
  p({ id: "integ-ftc-2", topicId: "integrals", section: "ftc", type: "numeric", difficulty: "easy",
    prompt: "Evaluate $\\int_1^3 2x\\,dx$",
    answer: "8",
    explanation: "Step 1: Antiderivative: $x^2$. Step 2: $3^2 - 1^2 = 9 - 1 = 8$. Final answer: $8$." }),
  p({ id: "integ-toolbox-8", topicId: "integrals", section: "toolbox", type: "numeric", difficulty: "easy",
    prompt: "Compute $\\int 5\\,dx$",
    answer: "5*x+C",
    explanation: "Step 1: The integral of a constant $k$ is $kx + C$. Step 2: $5x + C$. Final answer: $5x + C$." }),
  p({ id: "integ-toolbox-9", topicId: "integrals", section: "toolbox", type: "numeric", difficulty: "easy",
    prompt: "Compute $\\int (2x + 3)\\,dx$",
    answer: "x^2+3*x+C",
    explanation: "Step 1: Integrate term by term: $\\frac{2x^2}{2} + 3x + C = x^2 + 3x + C$. Final answer: $x^2 + 3x + C$." }),
  p({ id: "integ-toolbox-10", topicId: "integrals", section: "toolbox", type: "numeric", difficulty: "easy",
    prompt: "Compute $\\int x^{-2}\\,dx$",
    answer: "-1/x+C",
    explanation: "Step 1: $\\int x^{-2}dx = \\frac{x^{-1}}{-1} + C = -\\frac{1}{x} + C$. Final answer: $-\\frac{1}{x} + C$." }),
  p({ id: "integ-ftc-3", topicId: "integrals", section: "ftc", type: "numeric", difficulty: "easy",
    prompt: "Evaluate $\\int_0^{\\pi} \\sin(x)\\,dx$",
    answer: "2",
    explanation: "Step 1: $-\\cos(x)\\Big|_0^{\\pi} = -\\cos(\\pi)-(-\\cos(0)) = 1+1 = 2$. Final answer: $2$." }),
  p({ id: "integ-toolbox-11", topicId: "integrals", section: "toolbox", type: "numeric", difficulty: "easy",
    prompt: "Compute $\\int \\sec^2(x)\\,dx$",
    answer: "tan(x)+C",
    explanation: "Step 1: This is a standard integral. Step 2: $\\tan(x) + C$. Final answer: $\\tan(x) + C$." }),
  p({ id: "integ-ftc-4", topicId: "integrals", section: "ftc", type: "numeric", difficulty: "easy",
    prompt: "Evaluate $\\int_0^1 e^x\\,dx$",
    answer: "e-1",
    explanation: "Step 1: $e^x\\Big|_0^1 = e^1 - e^0 = e - 1$. Final answer: $e - 1$." }),
  // --- Medium (15) ---
  p({ id: "integ-usub-1", topicId: "integrals", section: "usub", type: "numeric", difficulty: "medium",
    prompt: "Compute $\\int 2xe^{x^2}\\,dx$",
    answer: "e^(x^2)+C",
    explanation: "Step 1: Let $u = x^2$, $du = 2x\\,dx$. Step 2: $\\int e^u\\,du = e^u + C = e^{x^2} + C$. Final answer: $e^{x^2} + C$." }),
  p({ id: "integ-usub-2", topicId: "integrals", section: "usub", type: "numeric", difficulty: "medium",
    prompt: "Compute $\\int \\frac{2x}{x^2+1}\\,dx$",
    answer: "ln(x^2+1)+C",
    explanation: "Step 1: Let $u = x^2+1$, $du = 2x\\,dx$. Step 2: $\\int \\frac{du}{u} = \\ln|u| + C = \\ln(x^2+1) + C$. Final answer: $\\ln(x^2+1) + C$." }),
  p({ id: "integ-usub-3", topicId: "integrals", section: "usub", type: "numeric", difficulty: "medium",
    prompt: "Compute $\\int \\cos(3x)\\,dx$",
    answer: "sin(3*x)/3+C",
    explanation: "Step 1: $\\int\\cos(kx)\\,dx = \\frac{\\sin(kx)}{k} + C$. Step 2: $\\frac{\\sin(3x)}{3} + C$. Final answer: $\\frac{\\sin(3x)}{3} + C$." }),
  p({ id: "integ-parts-1", topicId: "integrals", section: "parts", type: "numeric", difficulty: "medium",
    prompt: "Compute $\\int x\\cos(x)\\,dx$",
    answer: "x*sin(x)+cos(x)+C",
    explanation: "Step 1: Integration by parts: $u=x$, $dv=\\cos x\\,dx$. Step 2: $du=dx$, $v=\\sin x$. Step 3: $x\\sin x - \\int\\sin x\\,dx = x\\sin x + \\cos x + C$. Final answer: $x\\sin(x) + \\cos(x) + C$." }),
  p({ id: "integ-parts-2", topicId: "integrals", section: "parts", type: "numeric", difficulty: "medium",
    prompt: "Compute $\\int xe^x\\,dx$",
    answer: "x*e^x-e^x+C",
    explanation: "Step 1: By parts: $u=x$, $dv=e^x dx$. Step 2: $xe^x - \\int e^x dx = xe^x - e^x + C$. Final answer: $xe^x - e^x + C$." }),
  p({ id: "integ-usub-4", topicId: "integrals", section: "usub", type: "numeric", difficulty: "medium",
    prompt: "Evaluate $\\int_0^1 x^2 e^{x^3}\\,dx$",
    answer: "(e-1)/3",
    explanation: "Step 1: Let $u = x^3$, $du = 3x^2 dx$. Step 2: $\\frac{1}{3}\\int_0^1 e^u\\,du = \\frac{1}{3}(e^1-e^0) = \\frac{e-1}{3}$. Final answer: $\\frac{e-1}{3}$." }),
  p({ id: "integ-trigint-1", topicId: "integrals", section: "trigint", type: "numeric", difficulty: "medium",
    prompt: "Compute $\\int \\sin^2(x)\\,dx$",
    answer: "x/2-sin(2*x)/4+C",
    explanation: "Step 1: Use identity $\\sin^2(x) = \\frac{1-\\cos(2x)}{2}$. Step 2: $\\int\\frac{1-\\cos(2x)}{2}dx = \\frac{x}{2} - \\frac{\\sin(2x)}{4} + C$. Final answer: $\\frac{x}{2} - \\frac{\\sin(2x)}{4} + C$." }),
  p({ id: "integ-toolbox-12", topicId: "integrals", section: "toolbox", type: "numeric", difficulty: "medium",
    prompt: "Compute $\\int \\frac{1}{1+x^2}\\,dx$",
    answer: "arctan(x)+C",
    explanation: "Step 1: This is a standard form. Step 2: $\\arctan(x) + C$. Final answer: $\\arctan(x) + C$." }),
  p({ id: "integ-ftc-5", topicId: "integrals", section: "ftc", type: "numeric", difficulty: "medium",
    prompt: "Evaluate $\\int_0^4 \\sqrt{x}\\,dx$",
    answer: "16/3",
    explanation: "Step 1: $\\int x^{1/2}dx = \\frac{2}{3}x^{3/2}$. Step 2: $\\frac{2}{3}(4)^{3/2} = \\frac{2}{3}(8) = \\frac{16}{3}$. Final answer: $\\frac{16}{3}$." }),
  p({ id: "integ-parts-3", topicId: "integrals", section: "parts", type: "numeric", difficulty: "medium",
    prompt: "Compute $\\int \\ln(x)\\,dx$",
    answer: "x*ln(x)-x+C",
    explanation: "Step 1: By parts: $u=\\ln x$, $dv=dx$, $du=1/x\\,dx$, $v=x$. Step 2: $x\\ln x - \\int 1\\,dx = x\\ln x - x + C$. Final answer: $x\\ln(x) - x + C$." }),
  p({ id: "integ-usub-5", topicId: "integrals", section: "usub", type: "numeric", difficulty: "medium",
    prompt: "Compute $\\int e^{2x}\\,dx$",
    answer: "e^(2*x)/2+C",
    explanation: "Step 1: $\\int e^{kx}dx = \\frac{e^{kx}}{k}+C$. Step 2: $\\frac{e^{2x}}{2}+C$. Final answer: $\\frac{e^{2x}}{2}+C$." }),
  p({ id: "integ-ftc-6", topicId: "integrals", section: "ftc", type: "numeric", difficulty: "medium",
    prompt: "Evaluate $\\int_1^e \\frac{1}{x}\\,dx$",
    answer: "1",
    explanation: "Step 1: $\\ln|x|\\Big|_1^e = \\ln e - \\ln 1 = 1 - 0 = 1$. Final answer: $1$." }),
  p({ id: "integ-usub-6", topicId: "integrals", section: "usub", type: "numeric", difficulty: "medium",
    prompt: "Compute $\\int \\frac{x}{\\sqrt{x^2+4}}\\,dx$",
    answer: "sqrt(x^2+4)+C",
    explanation: "Step 1: Let $u = x^2+4$, $du = 2x\\,dx$. Step 2: $\\frac{1}{2}\\int u^{-1/2}du = \\frac{1}{2} \\cdot 2u^{1/2} + C = \\sqrt{x^2+4}+C$. Final answer: $\\sqrt{x^2+4}+C$." }),
  p({ id: "integ-usub-7", topicId: "integrals", section: "usub", type: "numeric", difficulty: "medium",
    prompt: "Compute $\\int \\tan(x)\\,dx$",
    answer: "-ln|cos(x)|+C",
    explanation: "Step 1: $\\int\\frac{\\sin x}{\\cos x}dx$. Let $u=\\cos x$, $du=-\\sin x\\,dx$. Step 2: $-\\int\\frac{du}{u} = -\\ln|u|+C = -\\ln|\\cos x|+C$. Final answer: $-\\ln|\\cos(x)|+C$." }),
  p({ id: "integ-ftc-7", topicId: "integrals", section: "ftc", type: "numeric", difficulty: "medium",
    prompt: "Evaluate $\\int_0^{\\pi/2} \\cos(x)\\,dx$",
    answer: "1",
    explanation: "Step 1: $\\sin(x)\\Big|_0^{\\pi/2} = \\sin(\\pi/2) - \\sin(0) = 1 - 0 = 1$. Final answer: $1$." }),
  // --- Hard (10) ---
  p({ id: "integ-parts-4", topicId: "integrals", section: "parts", type: "numeric", difficulty: "hard",
    prompt: "Compute $\\int x^2 e^x\\,dx$",
    answer: "x^2*e^x-2*x*e^x+2*e^x+C",
    explanation: "Step 1: By parts twice. First: $u=x^2$, $dv=e^x dx$. Step 2: $x^2 e^x - 2\\int xe^x dx$. Step 3: For $\\int xe^x dx = xe^x - e^x$. Step 4: $x^2 e^x - 2xe^x + 2e^x + C$. Final answer: $x^2 e^x - 2xe^x + 2e^x + C$." }),
  p({ id: "integ-partial-1", topicId: "integrals", section: "partial", type: "numeric", difficulty: "hard",
    prompt: "Compute $\\int \\frac{1}{x^2-1}\\,dx$",
    answer: "1/2*ln|(x-1)/(x+1)|+C",
    explanation: "Step 1: Partial fractions: $\\frac{1}{(x-1)(x+1)} = \\frac{A}{x-1}+\\frac{B}{x+1}$. Step 2: $A=1/2$, $B=-1/2$. Step 3: $\\frac{1}{2}\\ln|x-1|-\\frac{1}{2}\\ln|x+1|+C$. Final answer: $\\frac{1}{2}\\ln\\left|\\frac{x-1}{x+1}\\right|+C$." }),
  p({ id: "integ-usub-8", topicId: "integrals", section: "usub", type: "numeric", difficulty: "hard",
    prompt: "Evaluate $\\int_0^1 \\frac{x}{(1+x^2)^2}\\,dx$",
    answer: "1/4",
    explanation: "Step 1: Let $u=1+x^2$, $du=2x\\,dx$. Step 2: $\\frac{1}{2}\\int_1^2 u^{-2}du = \\frac{1}{2}\\left[-u^{-1}\\right]_1^2 = \\frac{1}{2}(-1/2+1) = \\frac{1}{4}$. Final answer: $\\frac{1}{4}$." }),
  p({ id: "integ-trigsub-1", topicId: "integrals", section: "trigsub", type: "numeric", difficulty: "hard",
    prompt: "Compute $\\int \\frac{1}{\\sqrt{9-x^2}}\\,dx$",
    answer: "arcsin(x/3)+C",
    explanation: "Step 1: This matches $\\int\\frac{dx}{\\sqrt{a^2-x^2}} = \\arcsin(x/a)+C$. Step 2: Here $a=3$. Final answer: $\\arcsin(x/3)+C$." }),
  p({ id: "integ-parts-5", topicId: "integrals", section: "parts", type: "numeric", difficulty: "hard",
    prompt: "Compute $\\int e^x\\sin(x)\\,dx$",
    answer: "e^x*(sin(x)-cos(x))/2+C",
    explanation: "Step 1: By parts twice; the integral repeats. Step 2: Let $I=\\int e^x\\sin x\\,dx$. After two integrations by parts: $I = e^x\\sin x - e^x\\cos x - I$. Step 3: $2I = e^x(\\sin x - \\cos x)$. Step 4: $I = \\frac{e^x(\\sin x - \\cos x)}{2}+C$. Final answer: $\\frac{e^x(\\sin x-\\cos x)}{2}+C$." }),
  p({ id: "integ-trigint-2", topicId: "integrals", section: "trigint", type: "numeric", difficulty: "hard",
    prompt: "Evaluate $\\int_0^{\\pi/4} \\tan^2(x)\\,dx$",
    answer: "1-pi/4",
    explanation: "Step 1: Use $\\tan^2 x = \\sec^2 x - 1$. Step 2: $\\int_0^{\\pi/4}(\\sec^2 x - 1)dx = [\\tan x - x]_0^{\\pi/4}$. Step 3: $(1-\\pi/4)-(0) = 1-\\pi/4$. Final answer: $1-\\frac{\\pi}{4}$." }),
  p({ id: "integ-technique-1", topicId: "integrals", section: "technique", type: "numeric", difficulty: "hard",
    prompt: "Compute $\\int \\frac{x^2}{x^2+1}\\,dx$",
    answer: "x-arctan(x)+C",
    explanation: "Step 1: Rewrite: $\\frac{x^2}{x^2+1} = 1 - \\frac{1}{x^2+1}$. Step 2: $\\int\\left(1 - \\frac{1}{x^2+1}\\right)dx = x - \\arctan(x) + C$. Final answer: $x - \\arctan(x) + C$." }),
  p({ id: "integ-usub-9", topicId: "integrals", section: "usub", type: "numeric", difficulty: "hard",
    prompt: "Compute $\\int \\frac{\\ln(x)}{x}\\,dx$",
    answer: "(ln(x))^2/2+C",
    explanation: "Step 1: Let $u=\\ln x$, $du = 1/x\\,dx$. Step 2: $\\int u\\,du = \\frac{u^2}{2}+C = \\frac{(\\ln x)^2}{2}+C$. Final answer: $\\frac{(\\ln x)^2}{2}+C$." }),
  p({ id: "integ-parts-6", topicId: "integrals", section: "parts", type: "numeric", difficulty: "hard",
    prompt: "Evaluate $\\int_0^{\\ln 2} xe^{-x}\\,dx$",
    answer: "1-3/(2*e^(ln(2)))",
    explanation: "Step 1: By parts: $u=x$, $dv=e^{-x}dx$. Step 2: $-xe^{-x}+\\int e^{-x}dx = -xe^{-x}-e^{-x}$. Step 3: Evaluate from 0 to $\\ln 2$: $(-\\ln 2 \\cdot 1/2 - 1/2) - (0-1) = -\\frac{\\ln 2}{2}-\\frac{1}{2}+1 = \\frac{1}{2}-\\frac{\\ln 2}{2}$. Final answer: $\\frac{1-\\ln 2}{2}$." }),
  p({ id: "integ-partial-2", topicId: "integrals", section: "partial", type: "numeric", difficulty: "hard",
    prompt: "Compute $\\int \\frac{1}{x(x+1)}\\,dx$",
    answer: "ln|x|-ln|x+1|+C",
    explanation: "Step 1: Partial fractions: $\\frac{1}{x(x+1)} = \\frac{1}{x} - \\frac{1}{x+1}$. Step 2: $\\ln|x| - \\ln|x+1| + C = \\ln\\left|\\frac{x}{x+1}\\right| + C$. Final answer: $\\ln|x| - \\ln|x+1| + C$." }),

  // =========================================================================
  // GAP-FILLING: riemann — Riemann sums
  // =========================================================================
  p({ id: "integ-riemann-1", topicId: "integrals", section: "riemann", type: "numeric", difficulty: "easy",
    prompt: "Estimate $\\int_0^4 x\\,dx$ using a right Riemann sum with $n=4$ equal sub-intervals.",
    answer: "10",
    explanation: "Step 1: $\\Delta x = 4/4 = 1$. Right endpoints: $1,2,3,4$. Step 2: Sum $= 1(1)+1(2)+1(3)+1(4) = 1+2+3+4 = 10$. Final answer: $10$." }),
  p({ id: "integ-riemann-2", topicId: "integrals", section: "riemann", type: "numeric", difficulty: "medium",
    prompt: "Estimate $\\int_0^2 x^2\\,dx$ using a left Riemann sum with $n=4$ equal sub-intervals.",
    answer: "1.75",
    explanation: "Step 1: $\\Delta x = 2/4 = 0.5$. Left endpoints: $0, 0.5, 1, 1.5$. Step 2: $f(0)=0$, $f(0.5)=0.25$, $f(1)=1$, $f(1.5)=2.25$. Step 3: Sum $= 0.5(0+0.25+1+2.25) = 0.5(3.5) = 1.75$. Final answer: $1.75$." }),

  // =========================================================================
  // GAP-FILLING: netarea — Net area vs total area
  // =========================================================================
  p({ id: "integ-netarea-1", topicId: "integrals", section: "netarea", type: "numeric", difficulty: "medium",
    prompt: "Compute the net signed area: $\\int_{-1}^{1} x\\,dx$.",
    answer: "0",
    explanation: "Step 1: $\\int_{-1}^{1} x\\,dx = \\frac{x^2}{2}\\Big|_{-1}^{1} = \\frac{1}{2}-\\frac{1}{2} = 0$. Step 2: The function $x$ is odd and the interval is symmetric, so the positive and negative areas cancel. Final answer: $0$." }),
  p({ id: "integ-netarea-2", topicId: "integrals", section: "netarea", type: "numeric", difficulty: "medium",
    prompt: "Find the total area (not net) between $f(x)=x$ and the $x$-axis on $[-2, 2]$.",
    answer: "4",
    explanation: "Step 1: $f(x)=x$ is negative on $[-2,0)$ and positive on $(0,2]$. Step 2: Total area $= \\int_{-2}^{0}|x|\\,dx + \\int_{0}^{2}|x|\\,dx = \\int_{-2}^{0}(-x)\\,dx + \\int_{0}^{2}x\\,dx$. Step 3: $= \\frac{x^2}{2}\\Big|_{0}^{2} + \\frac{x^2}{2}\\Big|_{0}^{2} = 2 + 2 = 4$ (by symmetry). Final answer: $4$." }),

  // =========================================================================
  // GAP-FILLING: antideriv — Antiderivatives and constant of integration
  // =========================================================================
  p({ id: "integ-antideriv-1", topicId: "integrals", section: "antideriv", type: "numeric", difficulty: "easy",
    prompt: "Find $F(x)$ such that $F'(x)=6x^2$ and $F(0)=5$.",
    answer: "2*x^3+5",
    explanation: "Step 1: General antiderivative: $F(x)=\\int 6x^2\\,dx = 2x^3 + C$. Step 2: $F(0)=0+C=5$, so $C=5$. Final answer: $F(x) = 2x^3+5$." }),
  p({ id: "integ-antideriv-2", topicId: "integrals", section: "antideriv", type: "mcq", difficulty: "easy",
    prompt: "Why do we write $+C$ for indefinite integrals?",
    answer: "Because any constant differentiates to zero, so infinitely many antiderivatives exist",
    choices: [
      "Because any constant differentiates to zero, so infinitely many antiderivatives exist",
      "Because definite integrals always equal zero",
      "Because integration is always approximate",
      "Because C stands for 'calculus'"
    ],
    explanation: "Step 1: If $F'(x) = f(x)$, then $(F(x)+C)' = f(x)$ for any constant $C$. Step 2: Constants have derivative zero, so every antiderivative differs by a constant. Final answer: Because any constant differentiates to zero, so infinitely many antiderivatives exist." }),

  // =========================================================================
  // GAP-FILLING: improper — Improper integrals
  // =========================================================================
  p({ id: "integ-improper-1", topicId: "integrals", section: "improper", type: "numeric", difficulty: "hard",
    prompt: "Evaluate $\\int_1^{\\infty} \\frac{1}{x^2}\\,dx$.",
    answer: "1",
    explanation: "Step 1: $\\int_1^{\\infty}x^{-2}\\,dx = \\lim_{b\\to\\infty}\\left[-\\frac{1}{x}\\right]_1^b = \\lim_{b\\to\\infty}\\left(-\\frac{1}{b}+1\\right)$. Step 2: As $b\\to\\infty$, $-1/b\\to 0$. Step 3: The integral equals $1$. Final answer: $1$." }),
  p({ id: "integ-improper-2", topicId: "integrals", section: "improper", type: "mcq", difficulty: "hard",
    prompt: "Does the improper integral $\\int_1^{\\infty}\\frac{1}{x}\\,dx$ converge or diverge?",
    answer: "Diverges",
    choices: ["Converges", "Diverges"],
    explanation: "Step 1: $\\int_1^{b}\\frac{1}{x}\\,dx = \\ln(b)$. Step 2: $\\lim_{b\\to\\infty}\\ln(b) = \\infty$. Step 3: The integral diverges. Final answer: Diverges." }),

  // =========================================================================
  // GAP-FILLING: areaprev — Area between curves preview
  // =========================================================================
  p({ id: "integ-areaprev-1", topicId: "integrals", section: "areaprev", type: "numeric", difficulty: "medium",
    prompt: "Find the area between $f(x)=x^2$ and $g(x)=x$ on $[0,1]$.",
    answer: "1/6",
    explanation: "Step 1: On $[0,1]$, $x \\ge x^2$, so area $= \\int_0^1(x-x^2)\\,dx$. Step 2: $= \\left[\\frac{x^2}{2}-\\frac{x^3}{3}\\right]_0^1 = \\frac{1}{2}-\\frac{1}{3} = \\frac{1}{6}$. Final answer: $\\frac{1}{6}$." }),
  p({ id: "integ-areaprev-2", topicId: "integrals", section: "areaprev", type: "numeric", difficulty: "medium",
    prompt: "Find the area enclosed between $y=x^2$ and $y=4$.",
    answer: "32/3",
    explanation: "Step 1: Intersection: $x^2=4 \\Rightarrow x=\\pm 2$. Step 2: Area $= \\int_{-2}^{2}(4-x^2)\\,dx = \\left[4x-\\frac{x^3}{3}\\right]_{-2}^{2}$. Step 3: $= (8-8/3)-(-8+8/3) = 2(8-8/3) = 2 \\cdot 16/3 = 32/3$. Final answer: $\\frac{32}{3}$." }),
];
