import type { Problem } from "../shared-types";

const p = (problem: Problem) => problem;

export const limitsProblems: Problem[] = [
  // --- Easy (15) ---
  p({ id: "limits-directsub-1", topicId: "limits", section: "directsub", type: "numeric", difficulty: "easy",
    prompt: "Compute: $\\lim_{x\\to 3} (2x + 1)$",
    answer: "7",
    explanation: "Step 1: This is a polynomial, so we can use direct substitution. Step 2: Substitute $x = 3$: $2(3) + 1 = 6 + 1 = 7$. Final answer: $7$." }),
  p({ id: "limits-directsub-2", topicId: "limits", section: "directsub", type: "numeric", difficulty: "easy",
    prompt: "Compute: $\\lim_{x\\to 2} (x^2 - 1)$",
    answer: "3",
    explanation: "Step 1: Since $x^2 - 1$ is a polynomial, we substitute directly. Step 2: $2^2 - 1 = 4 - 1 = 3$. Final answer: $3$." }),
  p({ id: "limits-trig-1", topicId: "limits", section: "trig", type: "numeric", difficulty: "easy",
    prompt: "Evaluate: $\\lim_{x\\to 0} \\frac{\\sin(3x)}{x}$",
    answer: "3",
    explanation: "Step 1: Recall the standard limit $\\lim_{u\\to 0} \\frac{\\sin u}{u} = 1$. Step 2: Rewrite as $3 \\cdot \\frac{\\sin(3x)}{3x}$. Step 3: As $x\\to 0$, let $u = 3x \\to 0$. So this becomes $3 \\cdot 1 = 3$. Final answer: $3$." }),
  p({ id: "limits-indeterminate-1", topicId: "limits", section: "indeterminate", type: "numeric", difficulty: "easy",
    prompt: "Compute: $\\lim_{x\\to 4} \\frac{x^2 - 16}{x - 4}$",
    answer: "8",
    explanation: "Step 1: Direct substitution gives $\\frac{0}{0}$, so we factor. Step 2: $x^2 - 16 = (x-4)(x+4)$. Step 3: Cancel $(x-4)$: $\\lim_{x\\to 4}(x+4) = 4+4 = 8$. Final answer: $8$." }),
  p({ id: "limits-trig-2", topicId: "limits", section: "trig", type: "numeric", difficulty: "easy",
    prompt: "Evaluate: $\\lim_{x\\to 0} \\frac{\\sin(5x)}{x}$",
    answer: "5",
    explanation: "Step 1: Rewrite as $5 \\cdot \\frac{\\sin(5x)}{5x}$. Step 2: Using $\\lim_{u\\to 0}\\frac{\\sin u}{u} = 1$, this equals $5 \\cdot 1 = 5$. Final answer: $5$." }),
  p({ id: "limits-indeterminate-2", topicId: "limits", section: "indeterminate", type: "numeric", difficulty: "easy",
    prompt: "Compute: $\\lim_{x\\to 1} \\frac{x^2 - 1}{x - 1}$",
    answer: "2",
    explanation: "Step 1: Factor the numerator: $x^2 - 1 = (x-1)(x+1)$. Step 2: Cancel $(x-1)$: $\\lim_{x\\to 1}(x+1) = 2$. Final answer: $2$." }),
  p({ id: "limits-directsub-3", topicId: "limits", section: "directsub", type: "numeric", difficulty: "easy",
    prompt: "Compute: $\\lim_{x\\to 5} \\sqrt{x + 4}$",
    answer: "3",
    explanation: "Step 1: Square root is continuous at $x = 5$. Step 2: Substitute: $\\sqrt{5 + 4} = \\sqrt{9} = 3$. Final answer: $3$." }),
  p({ id: "limits-trig-3", topicId: "limits", section: "trig", type: "numeric", difficulty: "easy",
    prompt: "Evaluate: $\\lim_{x\\to 0} \\frac{\\tan(x)}{x}$",
    answer: "1",
    explanation: "Step 1: Rewrite $\\tan(x) = \\frac{\\sin(x)}{\\cos(x)}$. Step 2: So $\\frac{\\tan(x)}{x} = \\frac{\\sin(x)}{x} \\cdot \\frac{1}{\\cos(x)}$. Step 3: As $x\\to 0$: $\\frac{\\sin x}{x} \\to 1$ and $\\frac{1}{\\cos 0} = 1$. Step 4: Product is $1 \\cdot 1 = 1$. Final answer: $1$." }),
  p({ id: "limits-indeterminate-3", topicId: "limits", section: "indeterminate", type: "numeric", difficulty: "easy",
    prompt: "Compute: $\\lim_{x\\to 2} \\frac{x^3 - 8}{x - 2}$",
    answer: "12",
    explanation: "Step 1: Factor using difference of cubes: $x^3 - 8 = (x-2)(x^2 + 2x + 4)$. Step 2: Cancel $(x-2)$: $\\lim_{x\\to 2}(x^2 + 2x + 4)$. Step 3: Substitute: $4 + 4 + 4 = 12$. Final answer: $12$." }),
  p({ id: "limits-directsub-4", topicId: "limits", section: "directsub", type: "numeric", difficulty: "easy",
    prompt: "Compute: $\\lim_{x\\to -1} (x^2 + 3x + 5)$",
    answer: "3",
    explanation: "Step 1: Polynomial, so substitute directly. Step 2: $(-1)^2 + 3(-1) + 5 = 1 - 3 + 5 = 3$. Final answer: $3$." }),
  p({ id: "limits-trig-4", topicId: "limits", section: "trig", type: "numeric", difficulty: "easy",
    prompt: "Evaluate: $\\lim_{x\\to 0} \\frac{1 - \\cos(x)}{x}$",
    answer: "0",
    explanation: "Step 1: This is a standard limit. We can use L'Hôpital's Rule since it's $\\frac{0}{0}$. Step 2: Differentiate: $\\frac{\\sin(x)}{1}$. Step 3: As $x\\to 0$: $\\sin(0) = 0$. Final answer: $0$." }),
  p({ id: "limits-indeterminate-4", topicId: "limits", section: "indeterminate", type: "numeric", difficulty: "easy",
    prompt: "Compute: $\\lim_{x\\to 3} \\frac{x^2 - 9}{x - 3}$",
    answer: "6",
    explanation: "Step 1: Factor: $x^2 - 9 = (x-3)(x+3)$. Step 2: Cancel $(x-3)$: $\\lim_{x\\to 3}(x+3) = 6$. Final answer: $6$." }),
  p({ id: "limits-indeterminate-5", topicId: "limits", section: "indeterminate", type: "numeric", difficulty: "easy",
    prompt: "Compute: $\\lim_{h\\to 0} \\frac{(2+h)^2 - 4}{h}$",
    answer: "4",
    explanation: "Step 1: Expand $(2+h)^2 = 4 + 4h + h^2$. Step 2: So the numerator is $4 + 4h + h^2 - 4 = 4h + h^2 = h(4+h)$. Step 3: $\\frac{h(4+h)}{h} = 4 + h$. Step 4: As $h\\to 0$: $4 + 0 = 4$. Final answer: $4$." }),
  p({ id: "limits-lhopital-1", topicId: "limits", section: "lhopital", type: "numeric", difficulty: "easy",
    prompt: "Evaluate: $\\lim_{x\\to 0} \\frac{e^x - 1}{x}$",
    answer: "1",
    explanation: "Step 1: This is a well-known limit (also the definition of the derivative of $e^x$ at 0). Step 2: By L'Hôpital's Rule: $\\frac{e^x}{1} \\to e^0 = 1$. Final answer: $1$." }),
  p({ id: "limits-trig-5", topicId: "limits", section: "trig", type: "numeric", difficulty: "easy",
    prompt: "Compute: $\\lim_{x\\to 0} \\frac{\\sin(x)}{x}$",
    answer: "1",
    explanation: "Step 1: This is the fundamental trigonometric limit. Step 2: $\\lim_{x\\to 0}\\frac{\\sin x}{x} = 1$. This can be proven by the squeeze theorem. Final answer: $1$." }),
  // --- Medium (15) ---
  p({ id: "limits-trig-6", topicId: "limits", section: "trig", type: "numeric", difficulty: "medium",
    prompt: "Compute: $\\lim_{x\\to 0} \\frac{\\sin(2x)}{\\sin(3x)}$",
    answer: "2/3",
    explanation: "Step 1: Rewrite as $\\frac{\\sin(2x)}{2x} \\cdot \\frac{3x}{\\sin(3x)} \\cdot \\frac{2x}{3x}$. Step 2: As $x\\to 0$, each ratio $\\frac{\\sin(kx)}{kx} \\to 1$. Step 3: So the limit equals $1 \\cdot 1 \\cdot \\frac{2}{3} = \\frac{2}{3}$. Final answer: $\\frac{2}{3}$." }),
  p({ id: "limits-lhopital-2", topicId: "limits", section: "lhopital", type: "numeric", difficulty: "medium",
    prompt: "Evaluate: $\\lim_{x\\to 0} \\frac{e^{2x} - 1}{x}$",
    answer: "2",
    explanation: "Step 1: This is $\\frac{0}{0}$, so apply L'Hôpital's Rule. Step 2: Differentiate top and bottom: $\\frac{2e^{2x}}{1}$. Step 3: As $x\\to 0$: $2e^0 = 2$. Final answer: $2$." }),
  p({ id: "limits-lhopital-3", topicId: "limits", section: "lhopital", type: "numeric", difficulty: "medium",
    prompt: "Compute: $\\lim_{x\\to 0} \\frac{x^2}{1 - \\cos(x)}$",
    answer: "2",
    explanation: "Step 1: Both numerator and denominator approach 0. Apply L'Hôpital twice. Step 2: First application: $\\frac{2x}{\\sin(x)}$. Still $\\frac{0}{0}$. Step 3: Second application: $\\frac{2}{\\cos(x)}$. Step 4: As $x\\to 0$: $\\frac{2}{1} = 2$. Final answer: $2$." }),
  p({ id: "limits-atinfinity-1", topicId: "limits", section: "atinfinity", type: "numeric", difficulty: "medium",
    prompt: "Evaluate: $\\lim_{x\\to \\infty} \\frac{3x^2 + 2x}{5x^2 - 1}$",
    answer: "3/5",
    explanation: "Step 1: Divide numerator and denominator by $x^2$ (highest power). Step 2: $\\frac{3 + 2/x}{5 - 1/x^2}$. Step 3: As $x\\to\\infty$: $2/x \\to 0$ and $1/x^2 \\to 0$. Step 4: Limit is $\\frac{3}{5}$. Final answer: $\\frac{3}{5}$." }),
  p({ id: "limits-lhopital-4", topicId: "limits", section: "lhopital", type: "numeric", difficulty: "medium",
    prompt: "Compute: $\\lim_{x\\to 0} \\frac{\\ln(1+x)}{x}$",
    answer: "1",
    explanation: "Step 1: This is $\\frac{0}{0}$. Apply L'Hôpital's Rule. Step 2: $\\frac{\\frac{1}{1+x}}{1} = \\frac{1}{1+x}$. Step 3: As $x\\to 0$: $\\frac{1}{1} = 1$. Final answer: $1$." }),
  p({ id: "limits-atinfinity-2", topicId: "limits", section: "atinfinity", type: "numeric", difficulty: "medium",
    prompt: "Evaluate: $\\lim_{x\\to \\infty} \\frac{5x^3 - x}{2x^3 + 4x^2}$",
    answer: "5/2",
    explanation: "Step 1: Divide by $x^3$: $\\frac{5 - 1/x^2}{2 + 4/x}$. Step 2: As $x\\to\\infty$: terms with $x$ in the denominator vanish. Step 3: Limit is $\\frac{5}{2}$. Final answer: $\\frac{5}{2}$." }),
  p({ id: "limits-trig-7", topicId: "limits", section: "trig", type: "numeric", difficulty: "medium",
    prompt: "Compute: $\\lim_{x\\to 0} \\frac{\\tan(4x)}{\\sin(2x)}$",
    answer: "2",
    explanation: "Step 1: Rewrite $\\tan(4x) = \\frac{\\sin(4x)}{\\cos(4x)}$. Step 2: $\\frac{\\sin(4x)}{\\cos(4x)\\sin(2x)}$. Near 0: $\\sin(kx) \\approx kx$. Step 3: $\\frac{4x}{\\cos(0) \\cdot 2x} = \\frac{4x}{2x} = 2$. Final answer: $2$." }),
  p({ id: "limits-lhopital-5", topicId: "limits", section: "lhopital", type: "numeric", difficulty: "medium",
    prompt: "Evaluate: $\\lim_{x\\to 0} \\frac{e^x - e^{-x}}{x}$",
    answer: "2",
    explanation: "Step 1: $\\frac{0}{0}$ form. Apply L'Hôpital. Step 2: $\\frac{e^x + e^{-x}}{1}$. Step 3: At $x = 0$: $e^0 + e^0 = 1 + 1 = 2$. Final answer: $2$." }),
  p({ id: "limits-indeterminate-6", topicId: "limits", section: "indeterminate", type: "numeric", difficulty: "medium",
    prompt: "Compute: $\\lim_{x\\to 0} \\frac{\\sqrt{1+x} - 1}{x}$",
    answer: "1/2",
    explanation: "Step 1: Rationalize by multiplying by $\\frac{\\sqrt{1+x}+1}{\\sqrt{1+x}+1}$. Step 2: Numerator becomes $(1+x)-1 = x$. Step 3: $\\frac{x}{x(\\sqrt{1+x}+1)} = \\frac{1}{\\sqrt{1+x}+1}$. Step 4: As $x\\to 0$: $\\frac{1}{1+1} = \\frac{1}{2}$. Final answer: $\\frac{1}{2}$." }),
  p({ id: "limits-trig-8", topicId: "limits", section: "trig", type: "numeric", difficulty: "medium",
    prompt: "Evaluate: $\\lim_{x\\to 0} \\frac{\\sin(x)\\cos(x)}{x}$",
    answer: "1",
    explanation: "Step 1: Rewrite as $\\frac{\\sin(x)}{x} \\cdot \\cos(x)$. Step 2: As $x \\to 0$: $\\frac{\\sin x}{x} \\to 1$ and $\\cos(0) = 1$. Step 3: Product is $1 \\cdot 1 = 1$. Final answer: $1$." }),
  p({ id: "limits-continuity-1", topicId: "limits", section: "continuity", type: "mcq", difficulty: "medium",
    prompt: "What type of discontinuity does $f(x) = \\frac{x^2 - 4}{x - 2}$ have at $x = 2$?",
    answer: "Removable", choices: ["Removable", "Jump", "Infinite", "None"],
    explanation: "Step 1: Factor: $\\frac{(x-2)(x+2)}{x-2} = x+2$ for $x \\neq 2$. Step 2: The limit exists ($\\lim_{x\\to 2} = 4$) but $f(2)$ is undefined. Step 3: Since the limit exists but the function value doesn't, this is a removable discontinuity. Final answer: Removable." }),
  p({ id: "limits-atinfinity-3", topicId: "limits", section: "atinfinity", type: "numeric", difficulty: "medium",
    prompt: "Compute: $\\lim_{x\\to \\infty} \\left(1 + \\frac{3}{x}\\right)^x$",
    answer: "e^3",
    explanation: "Step 1: This is of the form $(1 + a/x)^x$ as $x \\to \\infty$. Step 2: The general result is $\\lim_{x\\to\\infty}(1+a/x)^x = e^a$. Step 3: Here $a = 3$. Final answer: $e^3$." }),
  p({ id: "limits-lhopital-6", topicId: "limits", section: "lhopital", type: "numeric", difficulty: "medium",
    prompt: "Evaluate: $\\lim_{x\\to 0} \\frac{\\arctan(x)}{x}$",
    answer: "1",
    explanation: "Step 1: $\\frac{0}{0}$ form. Apply L'Hôpital. Step 2: $\\frac{\\frac{1}{1+x^2}}{1} = \\frac{1}{1+x^2}$. Step 3: At $x=0$: $\\frac{1}{1} = 1$. Final answer: $1$." }),
  p({ id: "limits-lhopital-7", topicId: "limits", section: "lhopital", type: "numeric", difficulty: "medium",
    prompt: "Compute: $\\lim_{x\\to 0} \\frac{3^x - 1}{x}$",
    answer: "ln(3)",
    explanation: "Step 1: This equals the derivative of $3^x$ at $x=0$. Step 2: $\\frac{d}{dx}3^x = 3^x \\ln(3)$. Step 3: At $x=0$: $3^0 \\ln(3) = \\ln(3)$. Final answer: $\\ln(3)$." }),
  p({ id: "limits-trig-9", topicId: "limits", section: "trig", type: "numeric", difficulty: "medium",
    prompt: "Evaluate: $\\lim_{x\\to 0}\\frac{1-\\cos(2x)}{x^2}$",
    answer: "2",
    explanation: "Step 1: Use the identity $1-\\cos(2x) = 2\\sin^2(x)$. Step 2: $\\frac{2\\sin^2(x)}{x^2} = 2\\left(\\frac{\\sin x}{x}\\right)^2$. Step 3: As $x\\to 0$: $2 \\cdot 1^2 = 2$. Final answer: $2$." }),
  // --- Hard (10) ---
  p({ id: "limits-lhopital-8", topicId: "limits", section: "lhopital", type: "numeric", difficulty: "hard",
    prompt: "Compute: $\\lim_{x\\to 0} \\frac{x - \\sin(x)}{x^3}$",
    answer: "1/6",
    explanation: "Step 1: $\\frac{0}{0}$ form. Apply L'Hôpital: $\\frac{1 - \\cos(x)}{3x^2}$. Step 2: Still $\\frac{0}{0}$. Apply again: $\\frac{\\sin(x)}{6x}$. Step 3: Still $\\frac{0}{0}$. Apply once more: $\\frac{\\cos(x)}{6}$. Step 4: At $x=0$: $\\frac{1}{6}$. Final answer: $\\frac{1}{6}$." }),
  p({ id: "limits-lhopital-9", topicId: "limits", section: "lhopital", type: "numeric", difficulty: "hard",
    prompt: "Evaluate: $\\lim_{x\\to 0^+} x \\ln(x)$",
    answer: "0",
    explanation: "Step 1: This is $0 \\cdot (-\\infty)$ form. Rewrite as $\\frac{\\ln(x)}{1/x}$. Step 2: Now it's $\\frac{-\\infty}{\\infty}$. Apply L'Hôpital: $\\frac{1/x}{-1/x^2} = \\frac{x^2}{x \\cdot (-1)} = -x$. Step 3: As $x\\to 0^+$: $-x \\to 0$. Final answer: $0$." }),
  p({ id: "limits-lhopital-10", topicId: "limits", section: "lhopital", type: "numeric", difficulty: "hard",
    prompt: "Compute: $\\lim_{x\\to 0} \\left(\\frac{\\sin x}{x}\\right)^{1/x^2}$",
    answer: "e^(-1/6)",
    explanation: "Step 1: Let $L = \\lim_{x\\to 0}(\\sin x / x)^{1/x^2}$. Take $\\ln$: $\\frac{1}{x^2}\\ln\\left(\\frac{\\sin x}{x}\\right)$. Step 2: Use Taylor series: $\\frac{\\sin x}{x} \\approx 1 - \\frac{x^2}{6}$, so $\\ln(1 - x^2/6) \\approx -x^2/6$. Step 3: $\\frac{-x^2/6}{x^2} = -\\frac{1}{6}$. Step 4: $L = e^{-1/6}$. Final answer: $e^{-1/6}$." }),
  p({ id: "limits-atinfinity-4", topicId: "limits", section: "atinfinity", type: "numeric", difficulty: "hard",
    prompt: "Evaluate: $\\lim_{x\\to \\infty} x\\left(\\sqrt{x^2+1} - x\\right)$",
    answer: "1/2",
    explanation: "Step 1: Multiply by $\\frac{\\sqrt{x^2+1}+x}{\\sqrt{x^2+1}+x}$: $\\frac{x(x^2+1-x^2)}{\\sqrt{x^2+1}+x} = \\frac{x}{\\sqrt{x^2+1}+x}$. Step 2: Divide by $x$: $\\frac{1}{\\sqrt{1+1/x^2}+1}$. Step 3: As $x\\to\\infty$: $\\frac{1}{1+1} = \\frac{1}{2}$. Final answer: $\\frac{1}{2}$." }),
  p({ id: "limits-lhopital-11", topicId: "limits", section: "lhopital", type: "numeric", difficulty: "hard",
    prompt: "Compute: $\\lim_{x\\to 0} \\frac{e^x - 1 - x}{x^2}$",
    answer: "1/2",
    explanation: "Step 1: $\\frac{0}{0}$. L'Hôpital: $\\frac{e^x - 1}{2x}$. Step 2: Still $\\frac{0}{0}$. L'Hôpital again: $\\frac{e^x}{2}$. Step 3: At $x=0$: $\\frac{1}{2}$. Final answer: $\\frac{1}{2}$." }),
  p({ id: "limits-lhopital-12", topicId: "limits", section: "lhopital", type: "mcq", difficulty: "hard",
    prompt: "Evaluate $\\lim_{x\\to\\infty} \\frac{x}{e^x}$.",
    answer: "0", choices: ["0", "1", "$\\infty$", "Does not exist"],
    explanation: "Step 1: $\\frac{\\infty}{\\infty}$ form. Apply L'Hôpital: $\\frac{1}{e^x}$. Step 2: As $x\\to\\infty$: $e^x \\to \\infty$, so $\\frac{1}{e^x} \\to 0$. Final answer: $0$." }),
  p({ id: "limits-lhopital-13", topicId: "limits", section: "lhopital", type: "numeric", difficulty: "hard",
    prompt: "Compute: $\\lim_{x\\to 0^+} x^x$",
    answer: "1",
    explanation: "Step 1: Write $x^x = e^{x\\ln x}$. Step 2: We need $\\lim_{x\\to 0^+} x\\ln x$. Rewrite as $\\frac{\\ln x}{1/x}$. Step 3: L'Hôpital: $\\frac{1/x}{-1/x^2} = -x \\to 0$. Step 4: So $x^x \\to e^0 = 1$. Final answer: $1$." }),
  p({ id: "limits-trig-10", topicId: "limits", section: "trig", type: "numeric", difficulty: "hard",
    prompt: "Evaluate: $\\lim_{x\\to 0} \\frac{\\tan(x) - \\sin(x)}{x^3}$",
    answer: "1/2",
    explanation: "Step 1: $\\tan x - \\sin x = \\frac{\\sin x}{\\cos x} - \\sin x = \\sin x \\left(\\frac{1-\\cos x}{\\cos x}\\right)$. Step 2: Near 0: $\\sin x \\approx x$, $1-\\cos x \\approx x^2/2$, $\\cos x \\approx 1$. Step 3: So $\\frac{x \\cdot x^2/2}{x^3} = \\frac{1}{2}$. Final answer: $\\frac{1}{2}$." }),
  p({ id: "limits-atinfinity-5", topicId: "limits", section: "atinfinity", type: "numeric", difficulty: "hard",
    prompt: "Compute: $\\lim_{n\\to\\infty} \\left(1 + \\frac{1}{n}\\right)^{2n}$",
    answer: "e^2",
    explanation: "Step 1: Write as $\\left[\\left(1 + \\frac{1}{n}\\right)^n\\right]^2$. Step 2: We know $\\lim_{n\\to\\infty}(1+1/n)^n = e$. Step 3: So the answer is $e^2$. Final answer: $e^2$." }),
  p({ id: "limits-trig-11", topicId: "limits", section: "trig", type: "numeric", difficulty: "hard",
    prompt: "Evaluate: $\\lim_{x\\to 0} \\frac{\\sin(x^2)}{x \\sin(x)}$",
    answer: "1",
    explanation: "Step 1: Near 0: $\\sin(x^2) \\approx x^2$ and $\\sin(x) \\approx x$. Step 2: $\\frac{x^2}{x \\cdot x} = \\frac{x^2}{x^2} = 1$. Step 3: Alternatively, L'Hôpital or series confirm this. Final answer: $1$." }),

  // ============================================================================
  // NEW GAP-FILLING QUESTIONS (12 problems)
  // ============================================================================

  // --- funcrep: Functional representations (2) ---
  p({ id: "limits-funcrep-1", topicId: "limits", section: "funcrep", type: "mcq", difficulty: "easy",
    prompt: "Which type of function is $f(x) = 3x^4 - 2x^2 + 7$?",
    answer: "Polynomial", choices: ["Polynomial", "Rational", "Trigonometric", "Exponential"],
    explanation: "Step 1: The function is a sum of terms of the form $ax^n$ where $n$ is a non-negative integer. Step 2: There are no fractions of polynomials, no trig functions, and no exponentials. Step 3: A function built from powers of $x$ with constant coefficients is a polynomial. Final answer: Polynomial." }),
  p({ id: "limits-funcrep-2", topicId: "limits", section: "funcrep", type: "mcq", difficulty: "medium",
    prompt: "What is the domain of $f(x) = \\frac{1}{x^2 - 9}$?",
    answer: "All real numbers except x = 3 and x = -3", choices: ["All real numbers", "All real numbers except x = 3 and x = -3", "All real numbers except x = 9", "x > 0"],
    explanation: "Step 1: A rational function is undefined where the denominator equals zero. Step 2: Set $x^2 - 9 = 0$, so $x^2 = 9$, giving $x = 3$ or $x = -3$. Step 3: The function is defined for all other real numbers. Final answer: All real numbers except $x = 3$ and $x = -3$." }),

  // --- intuition: Building intuition — what does "approaching" mean (2) ---
  p({ id: "limits-intuition-1", topicId: "limits", section: "intuition", type: "mcq", difficulty: "easy",
    prompt: "A function $f$ has the values: $f(1.9)=3.8$, $f(1.99)=3.98$, $f(1.999)=3.998$, $f(2.001)=4.002$, $f(2.01)=4.02$, $f(2.1)=4.2$. Based on this data, what does $f(x)$ appear to approach as $x \\to 2$?",
    answer: "4", choices: ["3.8", "4", "4.2", "Does not exist"],
    explanation: "Step 1: From the left, the values $3.8, 3.98, 3.998$ are getting closer to $4$. Step 2: From the right, the values $4.002, 4.02, 4.2$ are also getting closer to $4$. Step 3: Since both sides approach the same value, $f(x)$ appears to approach $4$ as $x \\to 2$. Final answer: $4$." }),
  p({ id: "limits-intuition-2", topicId: "limits", section: "intuition", type: "mcq", difficulty: "medium",
    prompt: "Consider $g(x) = \\frac{x^2 - 1}{x - 1}$. A student evaluates $g(0.9)=1.9$, $g(0.99)=1.99$, $g(0.999)=1.999$, $g(1.001)=2.001$, $g(1.01)=2.01$. What value does $g(x)$ approach as $x \\to 1$, even though $g(1)$ is undefined?",
    answer: "2", choices: ["1", "2", "0", "Does not exist"],
    explanation: "Step 1: From the left the values $1.9, 1.99, 1.999$ approach $2$. Step 2: From the right the values $2.001, 2.01$ also approach $2$. Step 3: Even though $g(1)$ is undefined (division by zero), the limit describes the value the outputs approach, which is $2$. Final answer: $2$." }),

  // --- onesided: One-sided limits (2) ---
  p({ id: "limits-onesided-1", topicId: "limits", section: "onesided", type: "numeric", difficulty: "easy",
    prompt: "Let $f(x) = \\begin{cases} 2x + 1 & x < 3 \\\\ x^2 - 2 & x \\geq 3 \\end{cases}$. Compute $\\lim_{x \\to 3^-} f(x)$.",
    answer: "7",
    explanation: "Step 1: For the left-hand limit $x \\to 3^-$, we use the branch where $x < 3$, which is $f(x) = 2x + 1$. Step 2: Substitute $x = 3$: $2(3) + 1 = 7$. Final answer: $7$." }),
  p({ id: "limits-onesided-2", topicId: "limits", section: "onesided", type: "numeric", difficulty: "medium",
    prompt: "Let $f(x) = \\begin{cases} x + 4 & x < 1 \\\\ 3x + 2 & x \\geq 1 \\end{cases}$. Compute $\\lim_{x \\to 1^+} f(x)$.",
    answer: "5",
    explanation: "Step 1: For the right-hand limit $x \\to 1^+$, we use the branch where $x \\geq 1$, which is $f(x) = 3x + 2$. Step 2: Substitute $x = 1$: $3(1) + 2 = 5$. Final answer: $5$." }),

  // --- squeeze: The Squeeze Theorem (2) ---
  p({ id: "limits-squeeze-1", topicId: "limits", section: "squeeze", type: "numeric", difficulty: "easy",
    prompt: "Evaluate: $\\lim_{x \\to 0}\\, x^2 \\sin\\!\\left(\\frac{1}{x}\\right)$",
    answer: "0",
    explanation: "Step 1: We know $-1 \\leq \\sin(1/x) \\leq 1$ for all $x \\neq 0$. Step 2: Multiplying by $x^2 \\geq 0$: $-x^2 \\leq x^2\\sin(1/x) \\leq x^2$. Step 3: Since $\\lim_{x\\to 0}(-x^2) = 0$ and $\\lim_{x\\to 0} x^2 = 0$, by the Squeeze Theorem the limit is $0$. Final answer: $0$." }),
  p({ id: "limits-squeeze-2", topicId: "limits", section: "squeeze", type: "numeric", difficulty: "medium",
    prompt: "Evaluate: $\\lim_{x \\to 0}\\, x^2 \\cos\\!\\left(\\frac{1}{x^2}\\right)$",
    answer: "0",
    explanation: "Step 1: We know $-1 \\leq \\cos(1/x^2) \\leq 1$ for all $x \\neq 0$. Step 2: Multiply through by $x^2 \\geq 0$: $-x^2 \\leq x^2\\cos(1/x^2) \\leq x^2$. Step 3: Both $-x^2$ and $x^2$ tend to $0$ as $x \\to 0$. Step 4: By the Squeeze Theorem, $\\lim_{x\\to 0} x^2\\cos(1/x^2) = 0$. Final answer: $0$." }),

  // --- piecewise: Evaluating limits of piecewise functions (2) ---
  p({ id: "limits-piecewise-1", topicId: "limits", section: "piecewise", type: "mcq", difficulty: "easy",
    prompt: "Let $f(x) = \\begin{cases} x + 3 & x < 2 \\\\ 2x - 1 & x \\geq 2 \\end{cases}$. Does $\\lim_{x \\to 2} f(x)$ exist?",
    answer: "No, the one-sided limits differ", choices: ["Yes, it equals 5", "Yes, it equals 3", "No, the one-sided limits differ", "No, f(2) is undefined"],
    explanation: "Step 1: Left-hand limit: $\\lim_{x \\to 2^-}(x+3) = 2+3 = 5$. Step 2: Right-hand limit: $\\lim_{x \\to 2^+}(2x-1) = 2(2)-1 = 3$. Step 3: Since $5 \\neq 3$, the one-sided limits disagree and the overall limit does not exist. Final answer: No, the one-sided limits differ." }),
  p({ id: "limits-piecewise-2", topicId: "limits", section: "piecewise", type: "numeric", difficulty: "medium",
    prompt: "Let $g(x) = \\begin{cases} x^2 - 3 & x < 2 \\\\ 2x - 3 & x \\geq 2 \\end{cases}$. Compute $\\lim_{x \\to 2} g(x)$ if it exists. If it does not exist, enter DNE.",
    answer: "1",
    explanation: "Step 1: Left-hand limit ($x \\to 2^-$): use $g(x) = x^2 - 3$. Substituting: $2^2 - 3 = 4 - 3 = 1$. Step 2: Right-hand limit ($x \\to 2^+$): use $g(x) = 2x - 3$. Substituting: $2(2) - 3 = 4 - 3 = 1$. Step 3: Both one-sided limits equal $1$, so the limit exists and equals $1$. Final answer: $1$." }),

  // --- infinite: Infinite limits and vertical asymptotes (2) ---
  p({ id: "limits-infinite-1", topicId: "limits", section: "infinite", type: "mcq", difficulty: "easy",
    prompt: "Evaluate $\\lim_{x \\to 0^+} \\frac{1}{x}$.",
    answer: "+infinity", choices: ["+infinity", "-infinity", "0", "Does not exist"],
    explanation: "Step 1: As $x$ approaches $0$ from the positive side, $x$ is a small positive number. Step 2: $\\frac{1}{x}$ becomes a very large positive number. Step 3: Therefore $\\frac{1}{x} \\to +\\infty$ as $x \\to 0^+$. Final answer: $+\\infty$." }),
  p({ id: "limits-infinite-2", topicId: "limits", section: "infinite", type: "mcq", difficulty: "medium",
    prompt: "Determine which value of $x$ is a vertical asymptote of $f(x) = \\frac{2x}{(x-5)(x+1)}$.",
    answer: "x = 5", choices: ["x = 0", "x = 5", "x = 2", "x = -5"],
    explanation: "Step 1: Vertical asymptotes occur where the denominator is zero and the numerator is nonzero. Step 2: Set $(x-5)(x+1) = 0$: $x = 5$ or $x = -1$. Step 3: At $x = 5$, the numerator is $2(5) = 10 \\neq 0$, so $x = 5$ is a vertical asymptote. Step 4: $x = -1$ is also a vertical asymptote but is not among the choices. Final answer: $x = 5$." }),
];
