import type { Problem } from "../content";

const p = (problem: Problem) => problem;

export const multivariableProblems: Problem[] = [
  // ===== EASY (15) =====
  p({ id: "multi-vectors-1", topicId: "multivariable", section: "vectors", type: "numeric", difficulty: "easy",
    prompt: "Find the magnitude of the vector $\\vec{v} = \\langle 3, 4 \\rangle$.",
    answer: "5",
    explanation: "Step 1: $|\\vec{v}| = \\sqrt{3^2 + 4^2} = \\sqrt{9+16} = \\sqrt{25}$. Final answer: $5$." }),
  p({ id: "multi-vectors-2", topicId: "multivariable", section: "vectors", type: "numeric", difficulty: "easy",
    prompt: "Compute the dot product $\\langle 1, 2, 3 \\rangle \\cdot \\langle 4, -1, 2 \\rangle$.",
    answer: "8",
    explanation: "Step 1: $1(4) + 2(-1) + 3(2) = 4 - 2 + 6 = 8$. Final answer: $8$." }),
  p({ id: "multi-vectors-3", topicId: "multivariable", section: "vectors", type: "numeric", difficulty: "easy",
    prompt: "Find the cross product $\\langle 1, 0, 0 \\rangle \\times \\langle 0, 1, 0 \\rangle$. Give your answer as a vector.",
    answer: "<0,0,1>",
    explanation: "Step 1: Using the determinant formula, $\\vec{i}(0\\cdot0 - 0\\cdot1) - \\vec{j}(1\\cdot0 - 0\\cdot0) + \\vec{k}(1\\cdot1 - 0\\cdot0) = \\langle 0, 0, 1 \\rangle$. Final answer: $\\langle 0, 0, 1 \\rangle$." }),
  p({ id: "multi-partials-1", topicId: "multivariable", section: "partials", type: "numeric", difficulty: "easy",
    prompt: "Find $\\frac{\\partial}{\\partial x}(x^2 y + 3y)$.",
    answer: "2*x*y",
    explanation: "Step 1: Treat $y$ as constant. $\\frac{\\partial}{\\partial x}(x^2 y) = 2xy$ and $\\frac{\\partial}{\\partial x}(3y) = 0$. Final answer: $2xy$." }),
  p({ id: "multi-partials-2", topicId: "multivariable", section: "partials", type: "numeric", difficulty: "easy",
    prompt: "Find $\\frac{\\partial}{\\partial y}(x^3 + 5xy^2)$.",
    answer: "10*x*y",
    explanation: "Step 1: Treat $x$ as constant. $\\frac{\\partial}{\\partial y}(x^3) = 0$ and $\\frac{\\partial}{\\partial y}(5xy^2) = 10xy$. Final answer: $10xy$." }),
  p({ id: "multi-gradient-1", topicId: "multivariable", section: "gradient", type: "numeric", difficulty: "easy",
    prompt: "Find $\\nabla f$ for $f(x,y) = x^2 + y^2$. Give the $x$-component at the point $(3,4)$.",
    answer: "6",
    explanation: "Step 1: $\\nabla f = \\langle 2x, 2y \\rangle$. Step 2: At $(3,4)$: $x$-component $= 2(3) = 6$. Final answer: $6$." }),
  p({ id: "multi-vectorfunc-1", topicId: "multivariable", section: "vectorfunc", type: "numeric", difficulty: "easy",
    prompt: "Given $\\vec{r}(t) = \\langle t^2, 3t, 1 \\rangle$, find $\\vec{r}'(1)$. Give the $x$-component.",
    answer: "2",
    explanation: "Step 1: $\\vec{r}'(t) = \\langle 2t, 3, 0 \\rangle$. Step 2: $\\vec{r}'(1) = \\langle 2, 3, 0 \\rangle$, so the $x$-component is $2$. Final answer: $2$." }),
  p({ id: "multi-multiint-1", topicId: "multivariable", section: "multiint", type: "numeric", difficulty: "easy",
    prompt: "Evaluate $\\int_0^1 \\int_0^2 (x + y)\\,dy\\,dx$.",
    answer: "3",
    explanation: "Step 1: Inner integral: $\\int_0^2 (x+y)\\,dy = [xy + \\frac{y^2}{2}]_0^2 = 2x + 2$. Step 2: $\\int_0^1 (2x+2)\\,dx = [x^2 + 2x]_0^1 = 1 + 2 = 3$. Final answer: $3$." }),
  p({ id: "multi-multiint-2", topicId: "multivariable", section: "multiint", type: "numeric", difficulty: "easy",
    prompt: "Evaluate $\\int_0^1 \\int_0^1 4xy\\,dx\\,dy$.",
    answer: "1",
    explanation: "Step 1: Inner integral: $\\int_0^1 4xy\\,dx = [2x^2 y]_0^1 = 2y$. Step 2: $\\int_0^1 2y\\,dy = [y^2]_0^1 = 1$. Final answer: $1$." }),
  p({ id: "multi-curldiv-1", topicId: "multivariable", section: "curldiv", type: "numeric", difficulty: "easy",
    prompt: "Find $\\text{div}\\,\\vec{F}$ for $\\vec{F} = \\langle x^2, y^2, z^2 \\rangle$.",
    answer: "2*x+2*y+2*z",
    explanation: "Step 1: $\\text{div}\\,\\vec{F} = \\frac{\\partial}{\\partial x}(x^2) + \\frac{\\partial}{\\partial y}(y^2) + \\frac{\\partial}{\\partial z}(z^2) = 2x + 2y + 2z$. Final answer: $2x+2y+2z$." }),
  p({ id: "multi-vectorfields-1", topicId: "multivariable", section: "vectorfields", type: "mcq", difficulty: "easy",
    prompt: "Is the vector field $\\vec{F} = \\langle y, x \\rangle$ conservative?",
    answer: "Yes",
    choices: ["Yes", "No"],
    explanation: "Step 1: Check $\\frac{\\partial P}{\\partial y} = 1$ and $\\frac{\\partial Q}{\\partial x} = 1$. Step 2: Since $P_y = Q_x$, the field is conservative. Final answer: $\\text{Yes}$." }),
  p({ id: "multi-lineint-1", topicId: "multivariable", section: "lineint", type: "numeric", difficulty: "easy",
    prompt: "Evaluate $\\int_C x\\,ds$ where $C$ is the line segment from $(0,0)$ to $(3,4)$.",
    answer: "15/2",
    explanation: "Step 1: Parametrize: $x = 3t$, $y = 4t$, $0 \\le t \\le 1$, so $ds = \\sqrt{9+16}\\,dt = 5\\,dt$. Step 2: $\\int_0^1 3t \\cdot 5\\,dt = 15\\int_0^1 t\\,dt = 15 \\cdot \\frac{1}{2} = \\frac{15}{2}$. Final answer: $\\frac{15}{2}$." }),
  p({ id: "multi-optimization-1", topicId: "multivariable", section: "optimization", type: "numeric", difficulty: "easy",
    prompt: "Find the critical point of $f(x,y) = x^2 + y^2 - 4x - 6y$. Give the $x$-coordinate.",
    answer: "2",
    explanation: "Step 1: $f_x = 2x - 4 = 0 \\Rightarrow x = 2$. Step 2: $f_y = 2y - 6 = 0 \\Rightarrow y = 3$. Final answer: $x = 2$." }),
  p({ id: "multi-theorems-1", topicId: "multivariable", section: "theorems", type: "mcq", difficulty: "easy",
    prompt: "Green's Theorem relates a line integral around a simple closed curve to which of the following?",
    answer: "A double integral over the enclosed region",
    choices: ["A double integral over the enclosed region", "A triple integral over a solid", "A surface integral over a sphere", "A single-variable integral"],
    explanation: "Step 1: Green's Theorem states $\\oint_C P\\,dx + Q\\,dy = \\iint_D \\left(\\frac{\\partial Q}{\\partial x} - \\frac{\\partial P}{\\partial y}\\right)dA$. Final answer: $\\text{A double integral over the enclosed region}$." }),
  p({ id: "multi-vectors-4", topicId: "multivariable", section: "vectors", type: "numeric", difficulty: "easy",
    prompt: "Find the scalar projection of $\\vec{a} = \\langle 3, 4 \\rangle$ onto $\\vec{b} = \\langle 1, 0 \\rangle$.",
    answer: "3",
    explanation: "Step 1: $\\text{comp}_{\\vec{b}}\\vec{a} = \\frac{\\vec{a} \\cdot \\vec{b}}{|\\vec{b}|} = \\frac{3(1)+4(0)}{1} = 3$. Final answer: $3$." }),

  // ===== MEDIUM (15) =====
  p({ id: "multi-vectors-5", topicId: "multivariable", section: "vectors", type: "numeric", difficulty: "medium",
    prompt: "Find the area of the parallelogram formed by $\\vec{u} = \\langle 1, 2, 0 \\rangle$ and $\\vec{v} = \\langle 0, 1, 3 \\rangle$.",
    answer: "sqrt(46)",
    explanation: "Step 1: $\\vec{u}\\times\\vec{v} = \\langle 2(3)-0(1),\\, 0(0)-1(3),\\, 1(1)-2(0) \\rangle = \\langle 6, -3, 1 \\rangle$. Step 2: $|\\vec{u}\\times\\vec{v}| = \\sqrt{36+9+1} = \\sqrt{46}$. Final answer: $\\sqrt{46}$." }),
  p({ id: "multi-partials-3", topicId: "multivariable", section: "partials", type: "numeric", difficulty: "medium",
    prompt: "Find $\\frac{\\partial^2 f}{\\partial x^2}$ for $f(x,y) = x^3 y^2 + \\sin(x)$.",
    answer: "6*x*y^2-sin(x)",
    explanation: "Step 1: $f_x = 3x^2 y^2 + \\cos(x)$. Step 2: $f_{xx} = 6xy^2 - \\sin(x)$. Final answer: $6xy^2 - \\sin(x)$." }),
  p({ id: "multi-partials-4", topicId: "multivariable", section: "partials", type: "mcq", difficulty: "medium",
    prompt: "For $f(x,y) = e^{xy}$, does $f_{xy} = f_{yx}$?",
    answer: "Yes, by Clairaut's theorem",
    choices: ["Yes, by Clairaut's theorem", "No, mixed partials are generally unequal", "Only if x = y", "Only at the origin"],
    explanation: "Step 1: $f$ is $C^2$ everywhere, so by Clairaut's theorem, $f_{xy} = f_{yx}$. Final answer: $\\text{Yes, by Clairaut's theorem}$." }),
  p({ id: "multi-gradient-2", topicId: "multivariable", section: "gradient", type: "numeric", difficulty: "medium",
    prompt: "Find the directional derivative of $f(x,y) = x^2 y - y^3$ at $(1,1)$ in the direction of $\\vec{u} = \\langle \\frac{3}{5}, \\frac{4}{5} \\rangle$.",
    answer: "-2/5",
    explanation: "Step 1: $\\nabla f = \\langle 2xy, x^2-3y^2 \\rangle$. Step 2: At $(1,1)$: $\\nabla f = \\langle 2, -2 \\rangle$. Step 3: $D_{\\vec{u}}f = \\nabla f \\cdot \\vec{u} = 2 \\cdot \\frac{3}{5} + (-2) \\cdot \\frac{4}{5} = \\frac{6}{5} - \\frac{8}{5} = -\\frac{2}{5}$. Final answer: $-\\frac{2}{5}$." }),
  p({ id: "multi-gradient-3", topicId: "multivariable", section: "gradient", type: "numeric", difficulty: "medium",
    prompt: "Find the equation of the tangent plane to $z = x^2 + y^2$ at $(1, 2, 5)$. What is the coefficient of $x$ in the plane equation $z = ax + by + c$?",
    answer: "2",
    explanation: "Step 1: $z_x = 2x$, $z_y = 2y$. Step 2: At $(1,2)$: $z_x = 2$, $z_y = 4$. Step 3: Tangent plane: $z - 5 = 2(x-1) + 4(y-2)$, i.e., $z = 2x + 4y - 5$. The coefficient of $x$ is $2$. Final answer: $2$." }),
  p({ id: "multi-vectorfunc-2", topicId: "multivariable", section: "vectorfunc", type: "numeric", difficulty: "medium",
    prompt: "Find the speed $|\\vec{r}'(t)|$ at $t = 1$ for $\\vec{r}(t) = \\langle t, t^2, t^3 \\rangle$.",
    answer: "sqrt(14)",
    explanation: "Step 1: $\\vec{r}'(t) = \\langle 1, 2t, 3t^2 \\rangle$. Step 2: At $t=1$: $\\vec{r}'(1) = \\langle 1, 2, 3 \\rangle$. Step 3: $|\\vec{r}'(1)| = \\sqrt{1+4+9} = \\sqrt{14}$. Final answer: $\\sqrt{14}$." }),
  p({ id: "multi-optimization-2", topicId: "multivariable", section: "optimization", type: "numeric", difficulty: "medium",
    prompt: "Classify the critical point of $f(x,y) = x^2 - y^2$ at $(0,0)$ using the second derivative test. What is the value of $D = f_{xx}f_{yy} - (f_{xy})^2$?",
    answer: "-4",
    explanation: "Step 1: $f_{xx} = 2$, $f_{yy} = -2$, $f_{xy} = 0$. Step 2: $D = (2)(-2) - 0^2 = -4$. Since $D < 0$, $(0,0)$ is a saddle point. Final answer: $-4$." }),
  p({ id: "multi-multiint-3", topicId: "multivariable", section: "multiint", type: "numeric", difficulty: "medium",
    prompt: "Evaluate $\\iint_D x^2 + y^2\\,dA$ where $D$ is the disk $x^2+y^2 \\le 1$, using polar coordinates.",
    answer: "pi/2",
    explanation: "Step 1: In polar: $\\int_0^{2\\pi}\\int_0^1 r^2 \\cdot r\\,dr\\,d\\theta = \\int_0^{2\\pi}\\int_0^1 r^3\\,dr\\,d\\theta$. Step 2: $\\int_0^1 r^3\\,dr = \\frac{1}{4}$. Step 3: $\\int_0^{2\\pi}\\frac{1}{4}\\,d\\theta = \\frac{2\\pi}{4} = \\frac{\\pi}{2}$. Final answer: $\\frac{\\pi}{2}$." }),
  p({ id: "multi-multiint-4", topicId: "multivariable", section: "multiint", type: "numeric", difficulty: "medium",
    prompt: "Evaluate $\\int_0^2 \\int_0^x x^2 y\\,dy\\,dx$.",
    answer: "16/5",
    explanation: "Step 1: Inner: $\\int_0^x x^2 y\\,dy = x^2 \\cdot \\frac{y^2}{2}\\Big|_0^x = \\frac{x^4}{2}$. Step 2: $\\int_0^2 \\frac{x^4}{2}\\,dx = \\frac{1}{2} \\cdot \\frac{x^5}{5}\\Big|_0^2 = \\frac{32}{10} = \\frac{16}{5}$. Final answer: $\\frac{16}{5}$." }),
  p({ id: "multi-vectorfields-2", topicId: "multivariable", section: "vectorfields", type: "mcq", difficulty: "medium",
    prompt: "Is $\\vec{F} = \\langle y^2, 2xy + 1 \\rangle$ conservative?",
    answer: "Yes",
    choices: ["Yes", "No"],
    explanation: "Step 1: $P = y^2$, $Q = 2xy + 1$. Step 2: $P_y = 2y$ and $Q_x = 2y$. Step 3: $P_y = Q_x$, so the field is conservative. Final answer: $\\text{Yes}$." }),
  p({ id: "multi-lineint-2", topicId: "multivariable", section: "lineint", type: "numeric", difficulty: "medium",
    prompt: "Evaluate $\\int_C \\vec{F} \\cdot d\\vec{r}$ where $\\vec{F} = \\langle 2x, 3y \\rangle$ and $C$ is the path $\\vec{r}(t) = \\langle t, t^2 \\rangle$ for $0 \\le t \\le 1$.",
    answer: "5/2",
    explanation: "Step 1: $\\vec{r}'(t) = \\langle 1, 2t \\rangle$. Step 2: $\\vec{F}(\\vec{r}(t)) = \\langle 2t, 3t^2 \\rangle$. Step 3: $\\vec{F} \\cdot \\vec{r}' = 2t + 6t^3$. Step 4: $\\int_0^1 (2t + 6t^3)\\,dt = [t^2 + \\frac{3t^4}{2}]_0^1 = 1 + \\frac{3}{2} = \\frac{5}{2}$. Final answer: $\\frac{5}{2}$." }),
  p({ id: "multi-lineint-3", topicId: "multivariable", section: "lineint", type: "numeric", difficulty: "medium",
    prompt: "If $\\vec{F} = \\nabla f$ where $f(x,y) = x^2 y$, evaluate $\\int_C \\vec{F}\\cdot d\\vec{r}$ from $(0,0)$ to $(2,3)$.",
    answer: "12",
    explanation: "Step 1: By the Fundamental Theorem for Line Integrals, $\\int_C \\nabla f \\cdot d\\vec{r} = f(2,3) - f(0,0)$. Step 2: $f(2,3) = 4 \\cdot 3 = 12$ and $f(0,0) = 0$. Final answer: $12$." }),
  p({ id: "multi-curldiv-2", topicId: "multivariable", section: "curldiv", type: "numeric", difficulty: "medium",
    prompt: "Find the $z$-component of $\\text{curl}\\,\\vec{F}$ for $\\vec{F} = \\langle -y, x, 0 \\rangle$.",
    answer: "2",
    explanation: "Step 1: The $z$-component of $\\text{curl}\\,\\vec{F}$ is $\\frac{\\partial Q}{\\partial x} - \\frac{\\partial P}{\\partial y}$. Step 2: $Q_x = 1$ and $P_y = -1$. Step 3: $1 - (-1) = 2$. Final answer: $2$." }),
  p({ id: "multi-optimization-3", topicId: "multivariable", section: "optimization", type: "numeric", difficulty: "medium",
    prompt: "Find the minimum value of $f(x,y) = x^2 + y^2 + 4x - 2y + 10$.",
    answer: "5",
    explanation: "Step 1: Complete the square: $f = (x+2)^2 - 4 + (y-1)^2 - 1 + 10 = (x+2)^2 + (y-1)^2 + 5$. Step 2: Minimum occurs when $(x+2)^2 = 0$ and $(y-1)^2 = 0$, giving $f_{\\min} = 5$. Final answer: $5$." }),
  p({ id: "multi-vectors-6", topicId: "multivariable", section: "vectors", type: "numeric", difficulty: "medium",
    prompt: "Find the angle (in radians) between $\\vec{a} = \\langle 1, 0, 1 \\rangle$ and $\\vec{b} = \\langle 0, 1, 1 \\rangle$.",
    answer: "pi/3",
    explanation: "Step 1: $\\vec{a}\\cdot\\vec{b} = 0+0+1 = 1$. Step 2: $|\\vec{a}| = \\sqrt{2}$, $|\\vec{b}| = \\sqrt{2}$. Step 3: $\\cos\\theta = \\frac{1}{2}$, so $\\theta = \\frac{\\pi}{3}$. Final answer: $\\frac{\\pi}{3}$." }),

  // ===== HARD (10) =====
  p({ id: "multi-partials-5", topicId: "multivariable", section: "partials", type: "numeric", difficulty: "hard",
    prompt: "For $f(x,y) = \\ln(x^2 + y^2)$, find $f_{xx} + f_{yy}$.",
    answer: "0",
    explanation: "Step 1: $f_x = \\frac{2x}{x^2+y^2}$, $f_y = \\frac{2y}{x^2+y^2}$. Step 2: $f_{xx} = \\frac{2(x^2+y^2) - 2x \\cdot 2x}{(x^2+y^2)^2} = \\frac{2y^2 - 2x^2}{(x^2+y^2)^2}$. Step 3: By symmetry $f_{yy} = \\frac{2x^2 - 2y^2}{(x^2+y^2)^2}$. Step 4: $f_{xx}+f_{yy} = 0$. Final answer: $0$." }),
  p({ id: "multi-gradient-4", topicId: "multivariable", section: "gradient", type: "numeric", difficulty: "hard",
    prompt: "Find the maximum rate of change of $f(x,y,z) = x e^{yz}$ at the point $(2, 0, 1)$.",
    answer: "sqrt(5)",
    explanation: "Step 1: $\\nabla f = \\langle e^{yz},\\, xze^{yz},\\, xye^{yz} \\rangle$. Step 2: At $(2,0,1)$: $\\nabla f = \\langle e^0,\\, 2(1)e^0,\\, 2(0)e^0 \\rangle = \\langle 1, 2, 0 \\rangle$. Step 3: $|\\nabla f| = \\sqrt{1+4+0} = \\sqrt{5}$. Final answer: $\\sqrt{5}$." }),
  p({ id: "multi-optimization-4", topicId: "multivariable", section: "optimization", type: "numeric", difficulty: "hard",
    prompt: "Use Lagrange multipliers to find the maximum value of $f(x,y) = xy$ subject to $x^2 + y^2 = 8$.",
    answer: "4",
    explanation: "Step 1: $\\nabla f = \\lambda \\nabla g$ gives $y = 2\\lambda x$ and $x = 2\\lambda y$. Step 2: From these, $y/(2x) = x/(2y)$ so $y^2 = x^2$, meaning $y = \\pm x$. Step 3: Substituting $y = x$ into $x^2+y^2=8$: $2x^2=8$, $x^2=4$, $x=2$. Step 4: $f(2,2) = 4$, $f(-2,-2) = 4$. The maximum is $4$. Final answer: $4$." }),
  p({ id: "multi-multiint-5", topicId: "multivariable", section: "multiint", type: "numeric", difficulty: "hard",
    prompt: "Evaluate $\\iiint_E z\\,dV$ where $E$ is the solid hemisphere $x^2+y^2+z^2 \\le 4$, $z \\ge 0$.",
    answer: "4*pi",
    explanation: "Step 1: In spherical: $z = \\rho\\cos\\phi$, $dV = \\rho^2\\sin\\phi\\,d\\rho\\,d\\phi\\,d\\theta$. Step 2: $\\int_0^{2\\pi}\\int_0^{\\pi/2}\\int_0^2 \\rho\\cos\\phi \\cdot \\rho^2\\sin\\phi\\,d\\rho\\,d\\phi\\,d\\theta$. Step 3: $\\int_0^2 \\rho^3\\,d\\rho = 4$. Step 4: $\\int_0^{\\pi/2}\\cos\\phi\\sin\\phi\\,d\\phi = \\frac{1}{2}$. Step 5: $\\int_0^{2\\pi}d\\theta = 2\\pi$. Step 6: Total $= 4 \\cdot \\frac{1}{2} \\cdot 2\\pi = 4\\pi$. Final answer: $4\\pi$." }),
  p({ id: "multi-multiint-6", topicId: "multivariable", section: "multiint", type: "numeric", difficulty: "hard",
    prompt: "Evaluate $\\iint_D e^{x^2}\\,dA$ where $D$ is the triangle with vertices $(0,0)$, $(1,0)$, $(1,1)$ by choosing the correct order of integration.",
    answer: "e/2-1/2",
    explanation: "Step 1: Switching order: $D = \\{(x,y): 0 \\le x \\le 1, 0 \\le y \\le x\\}$, so $\\int_0^1\\int_0^x e^{x^2}\\,dy\\,dx$. Step 2: Inner: $\\int_0^x e^{x^2}\\,dy = xe^{x^2}$. Step 3: $\\int_0^1 xe^{x^2}\\,dx = \\frac{1}{2}e^{x^2}\\Big|_0^1 = \\frac{e-1}{2}$. Final answer: $\\frac{e-1}{2}$." }),
  p({ id: "multi-vectorfields-3", topicId: "multivariable", section: "vectorfields", type: "numeric", difficulty: "hard",
    prompt: "Find the potential function $f(x,y)$ for $\\vec{F} = \\langle 2xy + 3, x^2 - 4y \\rangle$. Give $f(1,2)$ assuming $f(0,0)=0$.",
    answer: "-3",
    explanation: "Step 1: $f_x = 2xy+3$ so $f = x^2 y + 3x + g(y)$. Step 2: $f_y = x^2 + g'(y) = x^2 - 4y$, so $g'(y) = -4y$, $g(y) = -2y^2 + C$. Step 3: $f(0,0) = 0 \\Rightarrow C = 0$. Step 4: $f(x,y) = x^2y + 3x - 2y^2$. Step 5: $f(1,2) = 2 + 3 - 8 = -3$. Final answer: $-3$." }),
  p({ id: "multi-lineint-4", topicId: "multivariable", section: "lineint", type: "numeric", difficulty: "hard",
    prompt: "Evaluate $\\oint_C (x^2 - y)\\,dx + (y^2 + x)\\,dy$ where $C$ is the unit circle traversed counterclockwise, using Green's Theorem.",
    answer: "2*pi",
    explanation: "Step 1: $P = x^2-y$, $Q = y^2+x$. Step 2: $Q_x - P_y = 1-(-1) = 2$. Step 3: By Green's Theorem: $\\oint_C P\\,dx+Q\\,dy = \\iint_D 2\\,dA = 2 \\cdot \\pi(1)^2 = 2\\pi$. Final answer: $2\\pi$." }),
  p({ id: "multi-curldiv-3", topicId: "multivariable", section: "curldiv", type: "numeric", difficulty: "hard",
    prompt: "Find $\\text{curl}\\,\\vec{F}$ for $\\vec{F} = \\langle yz, xz, xy \\rangle$. Give the $x$-component.",
    answer: "0",
    explanation: "Step 1: $(\\text{curl}\\,\\vec{F})_x = \\frac{\\partial}{\\partial y}(xy) - \\frac{\\partial}{\\partial z}(xz) = x - x = 0$. Final answer: $0$." }),
  p({ id: "multi-vectorfunc-3", topicId: "multivariable", section: "vectorfunc", type: "numeric", difficulty: "hard",
    prompt: "Find the arc length of $\\vec{r}(t) = \\langle \\cos t, \\sin t, t \\rangle$ for $0 \\le t \\le 2\\pi$.",
    answer: "2*pi*sqrt(2)",
    explanation: "Step 1: $\\vec{r}'(t) = \\langle -\\sin t, \\cos t, 1 \\rangle$. Step 2: $|\\vec{r}'(t)| = \\sqrt{\\sin^2 t + \\cos^2 t + 1} = \\sqrt{2}$. Step 3: Arc length $= \\int_0^{2\\pi}\\sqrt{2}\\,dt = 2\\pi\\sqrt{2}$. Final answer: $2\\pi\\sqrt{2}$." }),
  p({ id: "multi-theorems-2", topicId: "multivariable", section: "theorems", type: "mcq", difficulty: "hard",
    prompt: "The Divergence Theorem relates the flux of a vector field through a closed surface to:",
    answer: "The triple integral of the divergence over the enclosed volume",
    choices: ["The triple integral of the divergence over the enclosed volume", "The double integral of the curl over the surface", "The line integral of the field around the boundary", "The gradient of the potential function"],
    explanation: "Step 1: The Divergence Theorem states $\\iint_S \\vec{F}\\cdot d\\vec{S} = \\iiint_E \\text{div}\\,\\vec{F}\\,dV$. Final answer: $\\text{The triple integral of the divergence over the enclosed volume}$." }),
];
