import type { Problem } from "../shared-types";

const p = (problem: Problem) => problem;

export const seriesProblems: Problem[] = [
  // --- Easy (15) ---
  p({ id: "series-geometric-1", topicId: "series", section: "geometric", type: "mcq", difficulty: "easy",
    prompt: "Does the geometric series $\\sum_{n=0}^{\\infty} \\left(\\frac{1}{2}\\right)^n$ converge or diverge?",
    answer: "Converges", choices: ["Converges", "Diverges"],
    explanation: "Step 1: Geometric series with $r = 1/2$. Step 2: Since $|r| = 1/2 < 1$, it converges. Final answer: Converges." }),
  p({ id: "series-geometric-2", topicId: "series", section: "geometric", type: "numeric", difficulty: "easy",
    prompt: "Find the sum: $\\sum_{n=0}^{\\infty} \\left(\\frac{1}{3}\\right)^n$",
    answer: "3/2",
    explanation: "Step 1: Sum $= \\frac{a}{1-r} = \\frac{1}{1-1/3} = \\frac{1}{2/3} = \\frac{3}{2}$. Final answer: $\\frac{3}{2}$." }),
  p({ id: "series-pseries-1", topicId: "series", section: "pseries", type: "mcq", difficulty: "easy",
    prompt: "Does $\\sum_{n=1}^{\\infty} \\frac{1}{n}$ converge?",
    answer: "Diverges", choices: ["Converges", "Diverges"],
    explanation: "Step 1: This is the harmonic series. Step 2: The harmonic series diverges (famous result). Final answer: Diverges." }),
  p({ id: "series-geometric-3", topicId: "series", section: "geometric", type: "numeric", difficulty: "easy",
    prompt: "Find the sum: $\\sum_{n=0}^{\\infty} \\left(\\frac{1}{4}\\right)^n$",
    answer: "4/3",
    explanation: "Step 1: $\\frac{1}{1-1/4} = \\frac{4}{3}$. Final answer: $\\frac{4}{3}$." }),
  p({ id: "series-pseries-2", topicId: "series", section: "pseries", type: "mcq", difficulty: "easy",
    prompt: "Does $\\sum_{n=1}^{\\infty} \\frac{1}{n^2}$ converge?",
    answer: "Converges", choices: ["Converges", "Diverges"],
    explanation: "Step 1: This is a $p$-series with $p=2>1$. Step 2: $p$-series converges when $p>1$. Final answer: Converges." }),
  p({ id: "series-geometric-4", topicId: "series", section: "geometric", type: "numeric", difficulty: "easy",
    prompt: "Find the sum: $\\sum_{n=0}^{\\infty} 3 \\cdot \\left(\\frac{1}{2}\\right)^n$",
    answer: "6",
    explanation: "Step 1: $\\frac{3}{1-1/2} = \\frac{3}{1/2} = 6$. Final answer: $6$." }),
  p({ id: "series-geometric-5", topicId: "series", section: "geometric", type: "mcq", difficulty: "easy",
    prompt: "Does $\\sum_{n=0}^{\\infty} 2^n$ converge?",
    answer: "Diverges", choices: ["Converges", "Diverges"],
    explanation: "Step 1: Geometric series with $r=2$. Step 2: $|r|=2>1$, so it diverges. Final answer: Diverges." }),
  p({ id: "series-sequences-1", topicId: "series", section: "sequences", type: "numeric", difficulty: "easy",
    prompt: "What is the 5th term of $a_n = \\frac{n}{n+1}$?",
    answer: "5/6",
    explanation: "Step 1: $a_5 = \\frac{5}{5+1} = \\frac{5}{6}$. Final answer: $\\frac{5}{6}$." }),
  p({ id: "series-sequences-2", topicId: "series", section: "sequences", type: "mcq", difficulty: "easy",
    prompt: "Does the sequence $a_n = \\frac{1}{n}$ converge?",
    answer: "Converges to 0", choices: ["Converges to 0", "Converges to 1", "Diverges"],
    explanation: "Step 1: As $n\\to\\infty$, $1/n \\to 0$. Final answer: Converges to 0." }),
  p({ id: "series-partialsums-1", topicId: "series", section: "partialsums", type: "numeric", difficulty: "easy",
    prompt: "Find $\\sum_{n=1}^{4} n^2$",
    answer: "30",
    explanation: "Step 1: $1+4+9+16 = 30$. Final answer: $30$." }),
  p({ id: "series-geometric-6", topicId: "series", section: "geometric", type: "numeric", difficulty: "easy",
    prompt: "Find the sum: $\\sum_{n=0}^{\\infty} \\left(-\\frac{1}{2}\\right)^n$",
    answer: "2/3",
    explanation: "Step 1: Geometric with $r=-1/2$, $|r|<1$. Step 2: $\\frac{1}{1-(-1/2)} = \\frac{1}{3/2} = \\frac{2}{3}$. Final answer: $\\frac{2}{3}$." }),
  p({ id: "series-pseries-3", topicId: "series", section: "pseries", type: "mcq", difficulty: "easy",
    prompt: "Does $\\sum_{n=1}^{\\infty} \\frac{1}{n^3}$ converge?",
    answer: "Converges", choices: ["Converges", "Diverges"],
    explanation: "Step 1: $p$-series with $p=3>1$. Converges. Final answer: Converges." }),
  p({ id: "series-sequences-3", topicId: "series", section: "sequences", type: "numeric", difficulty: "easy",
    prompt: "What does the sequence $a_n = \\frac{3n+1}{n}$ converge to?",
    answer: "3",
    explanation: "Step 1: $\\frac{3n+1}{n} = 3 + \\frac{1}{n} \\to 3$ as $n\\to\\infty$. Final answer: $3$." }),
  p({ id: "series-partialsums-2", topicId: "series", section: "partialsums", type: "numeric", difficulty: "easy",
    prompt: "Find $\\sum_{k=1}^{5} k$",
    answer: "15",
    explanation: "Step 1: $1+2+3+4+5 = 15$. Final answer: $15$." }),
  p({ id: "series-pseries-4", topicId: "series", section: "pseries", type: "mcq", difficulty: "easy",
    prompt: "Does $\\sum_{n=1}^{\\infty}\\frac{1}{\\sqrt{n}}$ converge?",
    answer: "Diverges", choices: ["Converges", "Diverges"],
    explanation: "Step 1: $p$-series with $p=1/2<1$. Step 2: Diverges. Final answer: Diverges." }),
  // --- Medium (15) ---
  p({ id: "series-ratioroot-1", topicId: "series", section: "ratioroot", type: "mcq", difficulty: "medium",
    prompt: "Use the ratio test on $\\sum \\frac{n!}{3^n}$. Does it converge?",
    answer: "Diverges", choices: ["Converges", "Diverges"],
    explanation: "Step 1: $\\frac{a_{n+1}}{a_n} = \\frac{(n+1)!}{3^{n+1}} \\cdot \\frac{3^n}{n!} = \\frac{n+1}{3}$. Step 2: $\\lim_{n\\to\\infty}\\frac{n+1}{3} = \\infty > 1$. Step 3: By ratio test, diverges. Final answer: Diverges." }),
  p({ id: "series-ratioroot-2", topicId: "series", section: "ratioroot", type: "mcq", difficulty: "medium",
    prompt: "Use the ratio test on $\\sum \\frac{2^n}{n!}$. Does it converge?",
    answer: "Converges", choices: ["Converges", "Diverges"],
    explanation: "Step 1: $\\frac{a_{n+1}}{a_n} = \\frac{2}{n+1} \\to 0 < 1$. Step 2: By ratio test, converges. Final answer: Converges." }),
  p({ id: "series-power-1", topicId: "series", section: "power", type: "numeric", difficulty: "medium",
    prompt: "Find the radius of convergence of $\\sum \\frac{x^n}{n}$.",
    answer: "1",
    explanation: "Step 1: Ratio test: $\\frac{|x|n}{n+1} \\to |x|$. Step 2: Converges when $|x|<1$. Step 3: Radius of convergence $R=1$. Final answer: $R=1$." }),
  p({ id: "series-taylor-1", topicId: "series", section: "taylor", type: "numeric", difficulty: "medium",
    prompt: "Find the 3rd-degree Taylor polynomial of $e^x$ centered at $x=0$.",
    answer: "1+x+x^2/2+x^3/6",
    explanation: "Step 1: $e^x = \\sum\\frac{x^n}{n!}$. Step 2: First 4 terms: $1 + x + \\frac{x^2}{2} + \\frac{x^3}{6}$. Final answer: $1+x+\\frac{x^2}{2}+\\frac{x^3}{6}$." }),
  p({ id: "series-alternating-1", topicId: "series", section: "alternating", type: "mcq", difficulty: "medium",
    prompt: "Does $\\sum_{n=1}^{\\infty} \\frac{(-1)^n}{n}$ converge?",
    answer: "Converges (conditionally)", choices: ["Converges (conditionally)", "Converges absolutely", "Diverges"],
    explanation: "Step 1: Alternating series test: $1/n$ is decreasing and $\\to 0$. Converges. Step 2: But $\\sum 1/n$ diverges, so not absolute. Final answer: Converges (conditionally)." }),
  p({ id: "series-taylor-2", topicId: "series", section: "taylor", type: "numeric", difficulty: "medium",
    prompt: "Find the Maclaurin series (first 3 nonzero terms) for $\\sin(x)$.",
    answer: "x-x^3/6+x^5/120",
    explanation: "Step 1: $\\sin(x) = x - \\frac{x^3}{3!} + \\frac{x^5}{5!} - \\cdots$. Step 2: $= x - \\frac{x^3}{6} + \\frac{x^5}{120}$. Final answer: $x - \\frac{x^3}{6} + \\frac{x^5}{120}$." }),
  p({ id: "series-power-2", topicId: "series", section: "power", type: "numeric", difficulty: "medium",
    prompt: "Find the interval of convergence of $\\sum \\frac{x^n}{2^n}$.",
    answer: "(-2,2)",
    explanation: "Step 1: Geometric with ratio $x/2$. Step 2: Converges when $|x/2|<1$, i.e., $|x|<2$. Step 3: At $x=\\pm 2$: diverges. Final answer: $(-2,2)$." }),
  p({ id: "series-ratioroot-3", topicId: "series", section: "ratioroot", type: "mcq", difficulty: "medium",
    prompt: "Does $\\sum_{n=1}^{\\infty} \\frac{n}{2^n}$ converge?",
    answer: "Converges", choices: ["Converges", "Diverges"],
    explanation: "Step 1: Ratio test: $\\frac{(n+1)/2^{n+1}}{n/2^n} = \\frac{n+1}{2n} \\to \\frac{1}{2} < 1$. Step 2: Converges. Final answer: Converges." }),
  p({ id: "series-telescoping-1", topicId: "series", section: "telescoping", type: "numeric", difficulty: "medium",
    prompt: "Find the sum of $\\sum_{n=1}^{\\infty} \\frac{1}{n(n+1)}$ (telescoping).",
    answer: "1",
    explanation: "Step 1: Partial fractions: $\\frac{1}{n(n+1)} = \\frac{1}{n}-\\frac{1}{n+1}$. Step 2: Telescopes to $(1-\\frac{1}{2})+(\\frac{1}{2}-\\frac{1}{3})+\\cdots = 1$. Final answer: $1$." }),
  p({ id: "series-power-3", topicId: "series", section: "power", type: "numeric", difficulty: "medium",
    prompt: "Find the radius of convergence of $\\sum \\frac{n!x^n}{n^n}$.",
    answer: "e",
    explanation: "Step 1: Ratio test: $\\frac{(n+1)!|x|^{n+1}}{(n+1)^{n+1}} \\cdot \\frac{n^n}{n!|x|^n} = |x|\\frac{n^n}{(n+1)^n}$. Step 2: $\\frac{n^n}{(n+1)^n} = \\frac{1}{(1+1/n)^n} \\to \\frac{1}{e}$. Step 3: $R = e$. Final answer: $R = e$." }),
  p({ id: "series-integraltest-1", topicId: "series", section: "integraltest", type: "mcq", difficulty: "medium",
    prompt: "Does $\\sum_{n=2}^{\\infty}\\frac{1}{n\\ln(n)}$ converge?",
    answer: "Diverges", choices: ["Converges", "Diverges"],
    explanation: "Step 1: Integral test: $\\int_2^{\\infty}\\frac{dx}{x\\ln x} = \\ln(\\ln x)\\Big|_2^\\infty = \\infty$. Step 2: Diverges. Final answer: Diverges." }),
  p({ id: "series-power-4", topicId: "series", section: "power", type: "numeric", difficulty: "medium",
    prompt: "Write $\\frac{1}{1-x}$ as a power series and give the radius of convergence.",
    answer: "1",
    explanation: "Step 1: $\\frac{1}{1-x} = \\sum_{n=0}^{\\infty} x^n$ for $|x|<1$. Step 2: Radius $R=1$. Final answer: $R=1$." }),
  p({ id: "series-geometric-7", topicId: "series", section: "geometric", type: "numeric", difficulty: "medium",
    prompt: "Find the sum $\\sum_{n=0}^{\\infty} \\frac{(-1)^n}{2^n}$.",
    answer: "2/3",
    explanation: "Step 1: Geometric with $r=-1/2$. Step 2: $\\frac{1}{1+1/2} = \\frac{2}{3}$. Final answer: $\\frac{2}{3}$." }),
  p({ id: "series-alternating-2", topicId: "series", section: "alternating", type: "mcq", difficulty: "medium",
    prompt: "Does $\\sum_{n=1}^{\\infty} \\frac{(-1)^n}{\\sqrt{n}}$ converge?",
    answer: "Converges (conditionally)", choices: ["Converges (conditionally)", "Converges absolutely", "Diverges"],
    explanation: "Step 1: Alternating series: $1/\\sqrt{n}$ decreasing to 0. Converges. Step 2: But $\\sum 1/\\sqrt{n}$ diverges ($p=1/2$). Not absolute. Final answer: Converges (conditionally)." }),
  p({ id: "series-taylor-3", topicId: "series", section: "taylor", type: "numeric", difficulty: "medium",
    prompt: "The first 3 terms of the Taylor series for $\\cos(x)$ at $x=0$ are:",
    answer: "1-x^2/2+x^4/24",
    explanation: "Step 1: $\\cos x = 1 - \\frac{x^2}{2!} + \\frac{x^4}{4!} - \\cdots$. Step 2: $= 1 - \\frac{x^2}{2} + \\frac{x^4}{24}$. Final answer: $1 - \\frac{x^2}{2} + \\frac{x^4}{24}$." }),
  // --- Hard (10) ---
  p({ id: "series-taylor-4", topicId: "series", section: "taylor", type: "numeric", difficulty: "hard",
    prompt: "Find the sum $\\sum_{n=0}^{\\infty} \\frac{(-1)^n}{(2n+1)!}$ (hint: think trig).",
    answer: "sin(1)",
    explanation: "Step 1: This is the Maclaurin series for $\\sin(x)$ evaluated at $x=1$. Step 2: $\\sin(1) = \\sum_{n=0}^{\\infty}\\frac{(-1)^n}{(2n+1)!}$. Final answer: $\\sin(1)$." }),
  p({ id: "series-power-5", topicId: "series", section: "power", type: "numeric", difficulty: "hard",
    prompt: "Find the radius of convergence of $\\sum_{n=1}^{\\infty} \\frac{n^n x^n}{n!}$.",
    answer: "1/e",
    explanation: "Step 1: Ratio test gives limit $|x| \\cdot e$. Step 2: Converges when $|x|e < 1$, i.e., $|x| < 1/e$. Step 3: $R = 1/e$. Final answer: $R = 1/e$." }),
  p({ id: "series-building-1", topicId: "series", section: "building", type: "numeric", difficulty: "hard",
    prompt: "Find $\\sum_{n=1}^{\\infty} \\frac{1}{n \\cdot 2^n}$.",
    answer: "ln(2)",
    explanation: "Step 1: Recall $-\\ln(1-x) = \\sum_{n=1}^{\\infty}\\frac{x^n}{n}$ for $|x|<1$. Step 2: At $x=1/2$: $-\\ln(1/2) = \\ln(2)$. Final answer: $\\ln(2)$." }),
  p({ id: "series-divergence-1", topicId: "series", section: "divergence", type: "mcq", difficulty: "hard",
    prompt: "Does $\\sum_{n=1}^{\\infty} \\frac{(-1)^n n}{n+1}$ converge?",
    answer: "Diverges", choices: ["Converges", "Diverges"],
    explanation: "Step 1: $\\lim_{n\\to\\infty}\\frac{n}{n+1} = 1 \\neq 0$. Step 2: The $n$-th term doesn't approach 0. Step 3: By the divergence test, diverges. Final answer: Diverges." }),
  p({ id: "series-building-2", topicId: "series", section: "building", type: "numeric", difficulty: "hard",
    prompt: "Find the Taylor series of $\\frac{1}{(1-x)^2}$ (first 4 terms).",
    answer: "1+2*x+3*x^2+4*x^3",
    explanation: "Step 1: $\\frac{d}{dx}\\frac{1}{1-x} = \\frac{1}{(1-x)^2}$. Step 2: $\\frac{d}{dx}\\sum x^n = \\sum nx^{n-1} = 1+2x+3x^2+4x^3+\\cdots$. Final answer: $1+2x+3x^2+4x^3$." }),
  p({ id: "series-taylor-5", topicId: "series", section: "taylor", type: "numeric", difficulty: "hard",
    prompt: "Find the coefficient of $x^3$ in the Taylor series of $e^x\\sin(x)$ around $x=0$.",
    answer: "-1/3",
    explanation: "Step 1: $e^x = 1+x+x^2/2+x^3/6+\\cdots$. $\\sin x = x-x^3/6+\\cdots$. Step 2: Product up to $x^3$: $x + x^2 + (1/2-1/6)x^3 = x+x^2+x^3/3$. Wait, let me recalculate carefully. Step 3: Coefficient of $x^3$: from $1 \\cdot(-x^3/6) + x \\cdot 0 + (x^2/2) \\cdot x = -1/6 + 0 + 1/2 \\cdot 0$... Actually $e^x\\sin x = x + x^2 + x^3/3 - x^5/30+\\cdots$. The coefficient of $x^3$ is $-1/3$. Final answer: $-\\frac{1}{3}$." }),
  p({ id: "series-absconv-1", topicId: "series", section: "absconv", type: "mcq", difficulty: "hard",
    prompt: "Does $\\sum_{n=1}^{\\infty} \\frac{\\sin(n)}{n^2}$ converge absolutely?",
    answer: "Yes", choices: ["Yes", "No"],
    explanation: "Step 1: $|\\sin(n)| \\le 1$, so $\\left|\\frac{\\sin(n)}{n^2}\\right| \\le \\frac{1}{n^2}$. Step 2: $\\sum 1/n^2$ converges. Step 3: By comparison, converges absolutely. Final answer: Yes." }),
  p({ id: "series-taylor-6", topicId: "series", section: "taylor", type: "numeric", difficulty: "hard",
    prompt: "Find $\\sum_{n=0}^{\\infty} \\frac{1}{n!}$ (exact value).",
    answer: "e",
    explanation: "Step 1: This is the Taylor series for $e^x$ at $x=1$. Step 2: $e^1 = e$. Final answer: $e$." }),
  p({ id: "series-power-6", topicId: "series", section: "power", type: "numeric", difficulty: "hard",
    prompt: "Find the interval of convergence of $\\sum_{n=1}^{\\infty} \\frac{(x-1)^n}{n}$.",
    answer: "[0,2)",
    explanation: "Step 1: Center $c=1$, radius $R=1$ (ratio test). Step 2: At $x=0$: $\\sum(-1)^n/n$ converges (alternating). Step 3: At $x=2$: $\\sum 1/n$ diverges. Final answer: $[0,2)$." }),
  p({ id: "series-taylor-7", topicId: "series", section: "taylor", type: "numeric", difficulty: "hard",
    prompt: "Find the Maclaurin series for $\\ln(1+x)$ (first 4 terms).",
    answer: "x-x^2/2+x^3/3-x^4/4",
    explanation: "Step 1: $\\ln(1+x) = \\sum_{n=1}^{\\infty}\\frac{(-1)^{n+1}x^n}{n}$. Step 2: First 4 terms: $x - \\frac{x^2}{2} + \\frac{x^3}{3} - \\frac{x^4}{4}$. Final answer: $x - \\frac{x^2}{2} + \\frac{x^3}{3} - \\frac{x^4}{4}$." }),

  // ===================================================================
  // GAP-FILLING: comparison — Comparison and Limit Comparison Tests
  // ===================================================================
  p({ id: "series-comparison-1", topicId: "series", section: "comparison", type: "mcq", difficulty: "medium",
    prompt: "Using the Direct Comparison Test, does $\\sum_{n=1}^{\\infty} \\frac{1}{n^2 + 1}$ converge or diverge?",
    answer: "Converges", choices: ["Converges", "Diverges"],
    explanation: "Step 1: For all $n \\ge 1$, $\\frac{1}{n^2+1} < \\frac{1}{n^2}$. Step 2: $\\sum \\frac{1}{n^2}$ is a convergent $p$-series ($p=2>1$). Step 3: By the Direct Comparison Test, $\\sum \\frac{1}{n^2+1}$ converges. Final answer: Converges." }),
  p({ id: "series-comparison-2", topicId: "series", section: "comparison", type: "mcq", difficulty: "medium",
    prompt: "Using the Limit Comparison Test with $b_n = \\frac{1}{n}$, does $\\sum_{n=1}^{\\infty} \\frac{n}{n^2 + 3}$ converge or diverge?",
    answer: "Diverges", choices: ["Converges", "Diverges"],
    explanation: "Step 1: Let $a_n = \\frac{n}{n^2+3}$ and $b_n = \\frac{1}{n}$. Step 2: $\\lim_{n\\to\\infty}\\frac{a_n}{b_n} = \\lim_{n\\to\\infty}\\frac{n^2}{n^2+3} = 1$, a finite positive number. Step 3: Since $\\sum b_n = \\sum \\frac{1}{n}$ diverges (harmonic series), by the Limit Comparison Test $\\sum a_n$ also diverges. Final answer: Diverges." }),

  // ===================================================================
  // GAP-FILLING: remainder — Taylor remainder and error bounds
  // ===================================================================
  p({ id: "series-remainder-1", topicId: "series", section: "remainder", type: "numeric", difficulty: "hard",
    prompt: "Using the Lagrange error bound, find the maximum error when approximating $e^1$ by the 3rd-degree Taylor polynomial $T_3(x) = 1 + x + \\frac{x^2}{2} + \\frac{x^3}{6}$ at $x = 1$. Use $e < 3$.",
    answer: "1/8",
    explanation: "Step 1: The Lagrange remainder is $|R_3(1)| \\le \\frac{M|1-0|^4}{4!}$ where $M = \\max_{c \\in [0,1]} |f^{(4)}(c)| = \\max_{c \\in [0,1]} e^c = e^1 < 3$. Step 2: $|R_3(1)| \\le \\frac{3}{24} = \\frac{1}{8}$. Final answer: $\\frac{1}{8}$." }),
  p({ id: "series-remainder-2", topicId: "series", section: "remainder", type: "numeric", difficulty: "hard",
    prompt: "The alternating series $\\sin(1) = \\sum_{n=0}^{\\infty}\\frac{(-1)^n}{(2n+1)!}$ is approximated by the first 3 terms: $1 - \\frac{1}{6} + \\frac{1}{120}$. By the Alternating Series Estimation Theorem, the error is at most:",
    answer: "1/5040",
    explanation: "Step 1: The Alternating Series Estimation Theorem says the error is bounded by the absolute value of the first omitted term. Step 2: The next term is $\\frac{1}{7!} = \\frac{1}{5040}$. Step 3: So the error $\\le \\frac{1}{5040}$. Final answer: $\\frac{1}{5040}$." }),

  // ===================================================================
  // GAP-FILLING: strategy — Choosing the right convergence test
  // ===================================================================
  p({ id: "series-strategy-1", topicId: "series", section: "strategy", type: "mcq", difficulty: "medium",
    prompt: "Which convergence test is most appropriate for $\\sum_{n=1}^{\\infty} \\frac{3^n}{n!}$?",
    answer: "Ratio Test", choices: ["Ratio Test", "Integral Test", "Comparison Test", "Alternating Series Test"],
    explanation: "Step 1: The series involves factorials and exponentials, which is the hallmark of the Ratio Test. Step 2: $\\frac{a_{n+1}}{a_n} = \\frac{3}{n+1} \\to 0 < 1$, so it converges. Step 3: The Ratio Test is the best choice when factorials or exponential terms appear. Final answer: Ratio Test." }),
  p({ id: "series-strategy-2", topicId: "series", section: "strategy", type: "mcq", difficulty: "medium",
    prompt: "Which convergence test is most appropriate for $\\sum_{n=1}^{\\infty} \\frac{(-1)^{n+1}}{\\sqrt{n+1}}$?",
    answer: "Alternating Series Test", choices: ["Ratio Test", "Integral Test", "Root Test", "Alternating Series Test"],
    explanation: "Step 1: The series has the factor $(-1)^{n+1}$, making it alternating. Step 2: $b_n = \\frac{1}{\\sqrt{n+1}}$ is decreasing and $\\lim_{n\\to\\infty} b_n = 0$. Step 3: The Alternating Series Test directly confirms convergence. Final answer: Alternating Series Test." }),
];
