export type ProblemType = "numeric" | "mcq";

export type Problem = {
  id: string;
  topicId: string;
  prompt: string;
  type: ProblemType;
  answer: string;
  choices?: string[];
  explanation: string;
  difficulty: "easy" | "medium" | "hard";
};

export type Topic = {
  id: string;
  title: string;
  description: string;
  order: number;
  estimatedMinutes: number;
};

export type LearningPath = {
  id: string;
  title: string;
  description: string;
  level: "intro" | "intermediate" | "advanced";
  steps: Array<{ topicId: string; targetProblems: number }>;
};

export const topics: Topic[] = [
  {
    id: "limits",
    title: "Limits & Continuity",
    description: "Build intuition for approaching values and continuity.",
    order: 1,
    estimatedMinutes: 90,
  },
  {
    id: "derivatives",
    title: "Derivatives",
    description: "Compute derivatives and interpret rates of change.",
    order: 2,
    estimatedMinutes: 120,
  },
  {
    id: "applications",
    title: "Applications of Derivatives",
    description: "Optimization, related rates, and motion.",
    order: 3,
    estimatedMinutes: 110,
  },
  {
    id: "integrals",
    title: "Integrals",
    description: "Understand accumulation and compute integrals.",
    order: 4,
    estimatedMinutes: 120,
  },
  {
    id: "series",
    title: "Series & Sequences",
    description: "Analyze convergence and common series tests.",
    order: 5,
    estimatedMinutes: 120,
  },
  {
    id: "differential-equations",
    title: "Differential Equations",
    description: "Solve basic differential equations and interpret models.",
    order: 6,
    estimatedMinutes: 90,
  },
];

const p = (problem: Problem) => problem;

// ============================================================================
// LIMITS & CONTINUITY (40 problems)
// ============================================================================
const limitsProblems: Problem[] = [
  // --- Easy (15) ---
  p({ id: "limits-1", topicId: "limits", type: "numeric", difficulty: "easy",
    prompt: "Compute: $\\lim_{x\\to 3} (2x + 1)$",
    answer: "7",
    explanation: "Step 1: This is a polynomial, so we can use direct substitution. Step 2: Substitute $x = 3$: $2(3) + 1 = 6 + 1 = 7$. Final answer: $7$." }),
  p({ id: "limits-2", topicId: "limits", type: "numeric", difficulty: "easy",
    prompt: "Compute: $\\lim_{x\\to 2} (x^2 - 1)$",
    answer: "3",
    explanation: "Step 1: Since $x^2 - 1$ is a polynomial, we substitute directly. Step 2: $2^2 - 1 = 4 - 1 = 3$. Final answer: $3$." }),
  p({ id: "limits-3", topicId: "limits", type: "numeric", difficulty: "easy",
    prompt: "Evaluate: $\\lim_{x\\to 0} \\frac{\\sin(3x)}{x}$",
    answer: "3",
    explanation: "Step 1: Recall the standard limit $\\lim_{u\\to 0} \\frac{\\sin u}{u} = 1$. Step 2: Rewrite as $3 \\cdot \\frac{\\sin(3x)}{3x}$. Step 3: As $x\\to 0$, let $u = 3x \\to 0$. So this becomes $3 \\cdot 1 = 3$. Final answer: $3$." }),
  p({ id: "limits-4", topicId: "limits", type: "numeric", difficulty: "easy",
    prompt: "Compute: $\\lim_{x\\to 4} \\frac{x^2 - 16}{x - 4}$",
    answer: "8",
    explanation: "Step 1: Direct substitution gives $\\frac{0}{0}$, so we factor. Step 2: $x^2 - 16 = (x-4)(x+4)$. Step 3: Cancel $(x-4)$: $\\lim_{x\\to 4}(x+4) = 4+4 = 8$. Final answer: $8$." }),
  p({ id: "limits-5", topicId: "limits", type: "numeric", difficulty: "easy",
    prompt: "Evaluate: $\\lim_{x\\to 0} \\frac{\\sin(5x)}{x}$",
    answer: "5",
    explanation: "Step 1: Rewrite as $5 \\cdot \\frac{\\sin(5x)}{5x}$. Step 2: Using $\\lim_{u\\to 0}\\frac{\\sin u}{u} = 1$, this equals $5 \\cdot 1 = 5$. Final answer: $5$." }),
  p({ id: "limits-6", topicId: "limits", type: "numeric", difficulty: "easy",
    prompt: "Compute: $\\lim_{x\\to 1} \\frac{x^2 - 1}{x - 1}$",
    answer: "2",
    explanation: "Step 1: Factor the numerator: $x^2 - 1 = (x-1)(x+1)$. Step 2: Cancel $(x-1)$: $\\lim_{x\\to 1}(x+1) = 2$. Final answer: $2$." }),
  p({ id: "limits-7", topicId: "limits", type: "numeric", difficulty: "easy",
    prompt: "Compute: $\\lim_{x\\to 5} \\sqrt{x + 4}$",
    answer: "3",
    explanation: "Step 1: Square root is continuous at $x = 5$. Step 2: Substitute: $\\sqrt{5 + 4} = \\sqrt{9} = 3$. Final answer: $3$." }),
  p({ id: "limits-8", topicId: "limits", type: "numeric", difficulty: "easy",
    prompt: "Evaluate: $\\lim_{x\\to 0} \\frac{\\tan(x)}{x}$",
    answer: "1",
    explanation: "Step 1: Rewrite $\\tan(x) = \\frac{\\sin(x)}{\\cos(x)}$. Step 2: So $\\frac{\\tan(x)}{x} = \\frac{\\sin(x)}{x} \\cdot \\frac{1}{\\cos(x)}$. Step 3: As $x\\to 0$: $\\frac{\\sin x}{x} \\to 1$ and $\\frac{1}{\\cos 0} = 1$. Step 4: Product is $1 \\cdot 1 = 1$. Final answer: $1$." }),
  p({ id: "limits-9", topicId: "limits", type: "numeric", difficulty: "easy",
    prompt: "Compute: $\\lim_{x\\to 2} \\frac{x^3 - 8}{x - 2}$",
    answer: "12",
    explanation: "Step 1: Factor using difference of cubes: $x^3 - 8 = (x-2)(x^2 + 2x + 4)$. Step 2: Cancel $(x-2)$: $\\lim_{x\\to 2}(x^2 + 2x + 4)$. Step 3: Substitute: $4 + 4 + 4 = 12$. Final answer: $12$." }),
  p({ id: "limits-10", topicId: "limits", type: "numeric", difficulty: "easy",
    prompt: "Compute: $\\lim_{x\\to -1} (x^2 + 3x + 5)$",
    answer: "3",
    explanation: "Step 1: Polynomial, so substitute directly. Step 2: $(-1)^2 + 3(-1) + 5 = 1 - 3 + 5 = 3$. Final answer: $3$." }),
  p({ id: "limits-11", topicId: "limits", type: "numeric", difficulty: "easy",
    prompt: "Evaluate: $\\lim_{x\\to 0} \\frac{1 - \\cos(x)}{x}$",
    answer: "0",
    explanation: "Step 1: This is a standard limit. We can use L'Hôpital's Rule since it's $\\frac{0}{0}$. Step 2: Differentiate: $\\frac{\\sin(x)}{1}$. Step 3: As $x\\to 0$: $\\sin(0) = 0$. Final answer: $0$." }),
  p({ id: "limits-12", topicId: "limits", type: "numeric", difficulty: "easy",
    prompt: "Compute: $\\lim_{x\\to 3} \\frac{x^2 - 9}{x - 3}$",
    answer: "6",
    explanation: "Step 1: Factor: $x^2 - 9 = (x-3)(x+3)$. Step 2: Cancel $(x-3)$: $\\lim_{x\\to 3}(x+3) = 6$. Final answer: $6$." }),
  p({ id: "limits-13", topicId: "limits", type: "numeric", difficulty: "easy",
    prompt: "Compute: $\\lim_{h\\to 0} \\frac{(2+h)^2 - 4}{h}$",
    answer: "4",
    explanation: "Step 1: Expand $(2+h)^2 = 4 + 4h + h^2$. Step 2: So the numerator is $4 + 4h + h^2 - 4 = 4h + h^2 = h(4+h)$. Step 3: $\\frac{h(4+h)}{h} = 4 + h$. Step 4: As $h\\to 0$: $4 + 0 = 4$. Final answer: $4$." }),
  p({ id: "limits-14", topicId: "limits", type: "numeric", difficulty: "easy",
    prompt: "Evaluate: $\\lim_{x\\to 0} \\frac{e^x - 1}{x}$",
    answer: "1",
    explanation: "Step 1: This is a well-known limit (also the definition of the derivative of $e^x$ at 0). Step 2: By L'Hôpital's Rule: $\\frac{e^x}{1} \\to e^0 = 1$. Final answer: $1$." }),
  p({ id: "limits-15", topicId: "limits", type: "numeric", difficulty: "easy",
    prompt: "Compute: $\\lim_{x\\to 0} \\frac{\\sin(x)}{x}$",
    answer: "1",
    explanation: "Step 1: This is the fundamental trigonometric limit. Step 2: $\\lim_{x\\to 0}\\frac{\\sin x}{x} = 1$. This can be proven by the squeeze theorem. Final answer: $1$." }),
  // --- Medium (15) ---
  p({ id: "limits-16", topicId: "limits", type: "numeric", difficulty: "medium",
    prompt: "Compute: $\\lim_{x\\to 0} \\frac{\\sin(2x)}{\\sin(3x)}$",
    answer: "2/3",
    explanation: "Step 1: Rewrite as $\\frac{\\sin(2x)}{2x} \\cdot \\frac{3x}{\\sin(3x)} \\cdot \\frac{2x}{3x}$. Step 2: As $x\\to 0$, each ratio $\\frac{\\sin(kx)}{kx} \\to 1$. Step 3: So the limit equals $1 \\cdot 1 \\cdot \\frac{2}{3} = \\frac{2}{3}$. Final answer: $\\frac{2}{3}$." }),
  p({ id: "limits-17", topicId: "limits", type: "numeric", difficulty: "medium",
    prompt: "Evaluate: $\\lim_{x\\to 0} \\frac{e^{2x} - 1}{x}$",
    answer: "2",
    explanation: "Step 1: This is $\\frac{0}{0}$, so apply L'Hôpital's Rule. Step 2: Differentiate top and bottom: $\\frac{2e^{2x}}{1}$. Step 3: As $x\\to 0$: $2e^0 = 2$. Final answer: $2$." }),
  p({ id: "limits-18", topicId: "limits", type: "numeric", difficulty: "medium",
    prompt: "Compute: $\\lim_{x\\to 0} \\frac{x^2}{1 - \\cos(x)}$",
    answer: "2",
    explanation: "Step 1: Both numerator and denominator approach 0. Apply L'Hôpital twice. Step 2: First application: $\\frac{2x}{\\sin(x)}$. Still $\\frac{0}{0}$. Step 3: Second application: $\\frac{2}{\\cos(x)}$. Step 4: As $x\\to 0$: $\\frac{2}{1} = 2$. Final answer: $2$." }),
  p({ id: "limits-19", topicId: "limits", type: "numeric", difficulty: "medium",
    prompt: "Evaluate: $\\lim_{x\\to \\infty} \\frac{3x^2 + 2x}{5x^2 - 1}$",
    answer: "3/5",
    explanation: "Step 1: Divide numerator and denominator by $x^2$ (highest power). Step 2: $\\frac{3 + 2/x}{5 - 1/x^2}$. Step 3: As $x\\to\\infty$: $2/x \\to 0$ and $1/x^2 \\to 0$. Step 4: Limit is $\\frac{3}{5}$. Final answer: $\\frac{3}{5}$." }),
  p({ id: "limits-20", topicId: "limits", type: "numeric", difficulty: "medium",
    prompt: "Compute: $\\lim_{x\\to 0} \\frac{\\ln(1+x)}{x}$",
    answer: "1",
    explanation: "Step 1: This is $\\frac{0}{0}$. Apply L'Hôpital's Rule. Step 2: $\\frac{\\frac{1}{1+x}}{1} = \\frac{1}{1+x}$. Step 3: As $x\\to 0$: $\\frac{1}{1} = 1$. Final answer: $1$." }),
  p({ id: "limits-21", topicId: "limits", type: "numeric", difficulty: "medium",
    prompt: "Evaluate: $\\lim_{x\\to \\infty} \\frac{5x^3 - x}{2x^3 + 4x^2}$",
    answer: "5/2",
    explanation: "Step 1: Divide by $x^3$: $\\frac{5 - 1/x^2}{2 + 4/x}$. Step 2: As $x\\to\\infty$: terms with $x$ in the denominator vanish. Step 3: Limit is $\\frac{5}{2}$. Final answer: $\\frac{5}{2}$." }),
  p({ id: "limits-22", topicId: "limits", type: "numeric", difficulty: "medium",
    prompt: "Compute: $\\lim_{x\\to 0} \\frac{\\tan(4x)}{\\sin(2x)}$",
    answer: "2",
    explanation: "Step 1: Rewrite $\\tan(4x) = \\frac{\\sin(4x)}{\\cos(4x)}$. Step 2: $\\frac{\\sin(4x)}{\\cos(4x)\\sin(2x)}$. Near 0: $\\sin(kx) \\approx kx$. Step 3: $\\frac{4x}{\\cos(0) \\cdot 2x} = \\frac{4x}{2x} = 2$. Final answer: $2$." }),
  p({ id: "limits-23", topicId: "limits", type: "numeric", difficulty: "medium",
    prompt: "Evaluate: $\\lim_{x\\to 0} \\frac{e^x - e^{-x}}{x}$",
    answer: "2",
    explanation: "Step 1: $\\frac{0}{0}$ form. Apply L'Hôpital. Step 2: $\\frac{e^x + e^{-x}}{1}$. Step 3: At $x = 0$: $e^0 + e^0 = 1 + 1 = 2$. Final answer: $2$." }),
  p({ id: "limits-24", topicId: "limits", type: "numeric", difficulty: "medium",
    prompt: "Compute: $\\lim_{x\\to 0} \\frac{\\sqrt{1+x} - 1}{x}$",
    answer: "1/2",
    explanation: "Step 1: Rationalize by multiplying by $\\frac{\\sqrt{1+x}+1}{\\sqrt{1+x}+1}$. Step 2: Numerator becomes $(1+x)-1 = x$. Step 3: $\\frac{x}{x(\\sqrt{1+x}+1)} = \\frac{1}{\\sqrt{1+x}+1}$. Step 4: As $x\\to 0$: $\\frac{1}{1+1} = \\frac{1}{2}$. Final answer: $\\frac{1}{2}$." }),
  p({ id: "limits-25", topicId: "limits", type: "numeric", difficulty: "medium",
    prompt: "Evaluate: $\\lim_{x\\to 0} \\frac{\\sin(x)\\cos(x)}{x}$",
    answer: "1",
    explanation: "Step 1: Rewrite as $\\frac{\\sin(x)}{x} \\cdot \\cos(x)$. Step 2: As $x \\to 0$: $\\frac{\\sin x}{x} \\to 1$ and $\\cos(0) = 1$. Step 3: Product is $1 \\cdot 1 = 1$. Final answer: $1$." }),
  p({ id: "limits-26", topicId: "limits", type: "mcq", difficulty: "medium",
    prompt: "What type of discontinuity does $f(x) = \\frac{x^2 - 4}{x - 2}$ have at $x = 2$?",
    answer: "Removable", choices: ["Removable", "Jump", "Infinite", "None"],
    explanation: "Step 1: Factor: $\\frac{(x-2)(x+2)}{x-2} = x+2$ for $x \\neq 2$. Step 2: The limit exists ($\\lim_{x\\to 2} = 4$) but $f(2)$ is undefined. Step 3: Since the limit exists but the function value doesn't, this is a removable discontinuity. Final answer: Removable." }),
  p({ id: "limits-27", topicId: "limits", type: "numeric", difficulty: "medium",
    prompt: "Compute: $\\lim_{x\\to \\infty} \\left(1 + \\frac{3}{x}\\right)^x$",
    answer: "e^3",
    explanation: "Step 1: This is of the form $(1 + a/x)^x$ as $x \\to \\infty$. Step 2: The general result is $\\lim_{x\\to\\infty}(1+a/x)^x = e^a$. Step 3: Here $a = 3$. Final answer: $e^3$." }),
  p({ id: "limits-28", topicId: "limits", type: "numeric", difficulty: "medium",
    prompt: "Evaluate: $\\lim_{x\\to 0} \\frac{\\arctan(x)}{x}$",
    answer: "1",
    explanation: "Step 1: $\\frac{0}{0}$ form. Apply L'Hôpital. Step 2: $\\frac{\\frac{1}{1+x^2}}{1} = \\frac{1}{1+x^2}$. Step 3: At $x=0$: $\\frac{1}{1} = 1$. Final answer: $1$." }),
  p({ id: "limits-29", topicId: "limits", type: "numeric", difficulty: "medium",
    prompt: "Compute: $\\lim_{x\\to 0} \\frac{3^x - 1}{x}$",
    answer: "ln(3)",
    explanation: "Step 1: This equals the derivative of $3^x$ at $x=0$. Step 2: $\\frac{d}{dx}3^x = 3^x \\ln(3)$. Step 3: At $x=0$: $3^0 \\ln(3) = \\ln(3)$. Final answer: $\\ln(3)$." }),
  p({ id: "limits-30", topicId: "limits", type: "numeric", difficulty: "medium",
    prompt: "Evaluate: $\\lim_{x\\to 0}\\frac{1-\\cos(2x)}{x^2}$",
    answer: "2",
    explanation: "Step 1: Use the identity $1-\\cos(2x) = 2\\sin^2(x)$. Step 2: $\\frac{2\\sin^2(x)}{x^2} = 2\\left(\\frac{\\sin x}{x}\\right)^2$. Step 3: As $x\\to 0$: $2 \\cdot 1^2 = 2$. Final answer: $2$." }),
  // --- Hard (10) ---
  p({ id: "limits-31", topicId: "limits", type: "numeric", difficulty: "hard",
    prompt: "Compute: $\\lim_{x\\to 0} \\frac{x - \\sin(x)}{x^3}$",
    answer: "1/6",
    explanation: "Step 1: $\\frac{0}{0}$ form. Apply L'Hôpital: $\\frac{1 - \\cos(x)}{3x^2}$. Step 2: Still $\\frac{0}{0}$. Apply again: $\\frac{\\sin(x)}{6x}$. Step 3: Still $\\frac{0}{0}$. Apply once more: $\\frac{\\cos(x)}{6}$. Step 4: At $x=0$: $\\frac{1}{6}$. Final answer: $\\frac{1}{6}$." }),
  p({ id: "limits-32", topicId: "limits", type: "numeric", difficulty: "hard",
    prompt: "Evaluate: $\\lim_{x\\to 0^+} x \\ln(x)$",
    answer: "0",
    explanation: "Step 1: This is $0 \\cdot (-\\infty)$ form. Rewrite as $\\frac{\\ln(x)}{1/x}$. Step 2: Now it's $\\frac{-\\infty}{\\infty}$. Apply L'Hôpital: $\\frac{1/x}{-1/x^2} = \\frac{x^2}{x \\cdot (-1)} = -x$. Step 3: As $x\\to 0^+$: $-x \\to 0$. Final answer: $0$." }),
  p({ id: "limits-33", topicId: "limits", type: "numeric", difficulty: "hard",
    prompt: "Compute: $\\lim_{x\\to 0} \\left(\\frac{\\sin x}{x}\\right)^{1/x^2}$",
    answer: "e^(-1/6)",
    explanation: "Step 1: Let $L = \\lim_{x\\to 0}(\\sin x / x)^{1/x^2}$. Take $\\ln$: $\\frac{1}{x^2}\\ln\\left(\\frac{\\sin x}{x}\\right)$. Step 2: Use Taylor series: $\\frac{\\sin x}{x} \\approx 1 - \\frac{x^2}{6}$, so $\\ln(1 - x^2/6) \\approx -x^2/6$. Step 3: $\\frac{-x^2/6}{x^2} = -\\frac{1}{6}$. Step 4: $L = e^{-1/6}$. Final answer: $e^{-1/6}$." }),
  p({ id: "limits-34", topicId: "limits", type: "numeric", difficulty: "hard",
    prompt: "Evaluate: $\\lim_{x\\to \\infty} x\\left(\\sqrt{x^2+1} - x\\right)$",
    answer: "1/2",
    explanation: "Step 1: Multiply by $\\frac{\\sqrt{x^2+1}+x}{\\sqrt{x^2+1}+x}$: $\\frac{x(x^2+1-x^2)}{\\sqrt{x^2+1}+x} = \\frac{x}{\\sqrt{x^2+1}+x}$. Step 2: Divide by $x$: $\\frac{1}{\\sqrt{1+1/x^2}+1}$. Step 3: As $x\\to\\infty$: $\\frac{1}{1+1} = \\frac{1}{2}$. Final answer: $\\frac{1}{2}$." }),
  p({ id: "limits-35", topicId: "limits", type: "numeric", difficulty: "hard",
    prompt: "Compute: $\\lim_{x\\to 0} \\frac{e^x - 1 - x}{x^2}$",
    answer: "1/2",
    explanation: "Step 1: $\\frac{0}{0}$. L'Hôpital: $\\frac{e^x - 1}{2x}$. Step 2: Still $\\frac{0}{0}$. L'Hôpital again: $\\frac{e^x}{2}$. Step 3: At $x=0$: $\\frac{1}{2}$. Final answer: $\\frac{1}{2}$." }),
  p({ id: "limits-36", topicId: "limits", type: "mcq", difficulty: "hard",
    prompt: "Evaluate $\\lim_{x\\to\\infty} \\frac{x}{e^x}$.",
    answer: "0", choices: ["0", "1", "$\\infty$", "Does not exist"],
    explanation: "Step 1: $\\frac{\\infty}{\\infty}$ form. Apply L'Hôpital: $\\frac{1}{e^x}$. Step 2: As $x\\to\\infty$: $e^x \\to \\infty$, so $\\frac{1}{e^x} \\to 0$. Final answer: $0$." }),
  p({ id: "limits-37", topicId: "limits", type: "numeric", difficulty: "hard",
    prompt: "Compute: $\\lim_{x\\to 0^+} x^x$",
    answer: "1",
    explanation: "Step 1: Write $x^x = e^{x\\ln x}$. Step 2: We need $\\lim_{x\\to 0^+} x\\ln x$. Rewrite as $\\frac{\\ln x}{1/x}$. Step 3: L'Hôpital: $\\frac{1/x}{-1/x^2} = -x \\to 0$. Step 4: So $x^x \\to e^0 = 1$. Final answer: $1$." }),
  p({ id: "limits-38", topicId: "limits", type: "numeric", difficulty: "hard",
    prompt: "Evaluate: $\\lim_{x\\to 0} \\frac{\\tan(x) - \\sin(x)}{x^3}$",
    answer: "1/2",
    explanation: "Step 1: $\\tan x - \\sin x = \\frac{\\sin x}{\\cos x} - \\sin x = \\sin x \\left(\\frac{1-\\cos x}{\\cos x}\\right)$. Step 2: Near 0: $\\sin x \\approx x$, $1-\\cos x \\approx x^2/2$, $\\cos x \\approx 1$. Step 3: So $\\frac{x \\cdot x^2/2}{x^3} = \\frac{1}{2}$. Final answer: $\\frac{1}{2}$." }),
  p({ id: "limits-39", topicId: "limits", type: "numeric", difficulty: "hard",
    prompt: "Compute: $\\lim_{n\\to\\infty} \\left(1 + \\frac{1}{n}\\right)^{2n}$",
    answer: "e^2",
    explanation: "Step 1: Write as $\\left[\\left(1 + \\frac{1}{n}\\right)^n\\right]^2$. Step 2: We know $\\lim_{n\\to\\infty}(1+1/n)^n = e$. Step 3: So the answer is $e^2$. Final answer: $e^2$." }),
  p({ id: "limits-40", topicId: "limits", type: "numeric", difficulty: "hard",
    prompt: "Evaluate: $\\lim_{x\\to 0} \\frac{\\sin(x^2)}{x \\sin(x)}$",
    answer: "1",
    explanation: "Step 1: Near 0: $\\sin(x^2) \\approx x^2$ and $\\sin(x) \\approx x$. Step 2: $\\frac{x^2}{x \\cdot x} = \\frac{x^2}{x^2} = 1$. Step 3: Alternatively, L'Hôpital or series confirm this. Final answer: $1$." }),
];

// ============================================================================
// DERIVATIVES (40 problems)
// ============================================================================
const derivativeProblems: Problem[] = [
  // --- Easy (15) ---
  p({ id: "deriv-1", topicId: "derivatives", type: "numeric", difficulty: "easy",
    prompt: "Find $\\frac{d}{dx}(5x^3)$",
    answer: "15*x^2",
    explanation: "Step 1: Power rule: $\\frac{d}{dx}(x^n) = nx^{n-1}$. Step 2: $5 \\cdot 3x^{3-1} = 15x^2$. Final answer: $15x^2$." }),
  p({ id: "deriv-2", topicId: "derivatives", type: "numeric", difficulty: "easy",
    prompt: "Find $\\frac{d}{dx}(x^4 + 2x)$",
    answer: "4*x^3+2",
    explanation: "Step 1: Differentiate term by term. Step 2: $\\frac{d}{dx}(x^4) = 4x^3$ and $\\frac{d}{dx}(2x) = 2$. Final answer: $4x^3 + 2$." }),
  p({ id: "deriv-3", topicId: "derivatives", type: "numeric", difficulty: "easy",
    prompt: "Find $\\frac{d}{dx}(e^{3x})$",
    answer: "3*e^(3*x)",
    explanation: "Step 1: Chain rule: $\\frac{d}{dx}(e^{kx}) = ke^{kx}$. Step 2: Here $k=3$: $3e^{3x}$. Final answer: $3e^{3x}$." }),
  p({ id: "deriv-4", topicId: "derivatives", type: "numeric", difficulty: "easy",
    prompt: "Find $\\frac{d}{dx}(\\sin(x))$",
    answer: "cos(x)",
    explanation: "Step 1: This is a fundamental derivative. Step 2: $\\frac{d}{dx}(\\sin x) = \\cos x$. Final answer: $\\cos(x)$." }),
  p({ id: "deriv-5", topicId: "derivatives", type: "numeric", difficulty: "easy",
    prompt: "Find $\\frac{d}{dx}(\\ln(x))$",
    answer: "1/x",
    explanation: "Step 1: This is a fundamental derivative. Step 2: $\\frac{d}{dx}(\\ln x) = \\frac{1}{x}$. Final answer: $\\frac{1}{x}$." }),
  p({ id: "deriv-6", topicId: "derivatives", type: "numeric", difficulty: "easy",
    prompt: "Find $\\frac{d}{dx}(7x^2 - 3x + 1)$",
    answer: "14*x-3",
    explanation: "Step 1: Term by term: $14x - 3 + 0$. Step 2: Constants differentiate to 0. Final answer: $14x - 3$." }),
  p({ id: "deriv-7", topicId: "derivatives", type: "numeric", difficulty: "easy",
    prompt: "Find $\\frac{d}{dx}(\\cos(2x))$",
    answer: "-2*sin(2*x)",
    explanation: "Step 1: Chain rule: $\\frac{d}{dx}(\\cos(u)) = -\\sin(u) \\cdot u'$. Step 2: $u = 2x$, so $u' = 2$. Step 3: $-2\\sin(2x)$. Final answer: $-2\\sin(2x)$." }),
  p({ id: "deriv-8", topicId: "derivatives", type: "numeric", difficulty: "easy",
    prompt: "Find $\\frac{d}{dx}(\\sqrt{x})$",
    answer: "1/(2*sqrt(x))",
    explanation: "Step 1: Rewrite $\\sqrt{x} = x^{1/2}$. Step 2: Power rule: $\\frac{1}{2}x^{-1/2} = \\frac{1}{2\\sqrt{x}}$. Final answer: $\\frac{1}{2\\sqrt{x}}$." }),
  p({ id: "deriv-9", topicId: "derivatives", type: "numeric", difficulty: "easy",
    prompt: "Find $\\frac{d}{dx}(3e^x + 4)$",
    answer: "3*e^x",
    explanation: "Step 1: $\\frac{d}{dx}(e^x) = e^x$ and constants vanish. Step 2: $3e^x + 0 = 3e^x$. Final answer: $3e^x$." }),
  p({ id: "deriv-10", topicId: "derivatives", type: "numeric", difficulty: "easy",
    prompt: "Find $\\frac{d}{dx}\\left(\\frac{1}{x}\\right)$",
    answer: "-1/x^2",
    explanation: "Step 1: Rewrite as $x^{-1}$. Step 2: Power rule: $-1 \\cdot x^{-2} = -\\frac{1}{x^2}$. Final answer: $-\\frac{1}{x^2}$." }),
  p({ id: "deriv-11", topicId: "derivatives", type: "numeric", difficulty: "easy",
    prompt: "Find $\\frac{d}{dx}(x^5)$",
    answer: "5*x^4",
    explanation: "Step 1: Power rule: $5x^{5-1} = 5x^4$. Final answer: $5x^4$." }),
  p({ id: "deriv-12", topicId: "derivatives", type: "numeric", difficulty: "easy",
    prompt: "Find $\\frac{d}{dx}(\\tan(x))$",
    answer: "sec(x)^2",
    explanation: "Step 1: Standard derivative: $\\frac{d}{dx}(\\tan x) = \\sec^2 x$. Final answer: $\\sec^2(x)$." }),
  p({ id: "deriv-13", topicId: "derivatives", type: "numeric", difficulty: "easy",
    prompt: "If $f(x) = 2x^3$, find $f'(1)$",
    answer: "6",
    explanation: "Step 1: $f'(x) = 6x^2$. Step 2: $f'(1) = 6(1)^2 = 6$. Final answer: $6$." }),
  p({ id: "deriv-14", topicId: "derivatives", type: "numeric", difficulty: "easy",
    prompt: "Find $\\frac{d}{dx}(4\\ln(x))$",
    answer: "4/x",
    explanation: "Step 1: $4 \\cdot \\frac{1}{x} = \\frac{4}{x}$. Final answer: $\\frac{4}{x}$." }),
  p({ id: "deriv-15", topicId: "derivatives", type: "numeric", difficulty: "easy",
    prompt: "Find $\\frac{d}{dx}(x^2 + e^x)$",
    answer: "2*x+e^x",
    explanation: "Step 1: Differentiate each term. Step 2: $2x + e^x$. Final answer: $2x + e^x$." }),
  // --- Medium (15) ---
  p({ id: "deriv-16", topicId: "derivatives", type: "numeric", difficulty: "medium",
    prompt: "Find $\\frac{d}{dx}(x^2 \\sin(x))$",
    answer: "2*x*sin(x)+x^2*cos(x)",
    explanation: "Step 1: Product rule: $(fg)' = f'g + fg'$. Step 2: $f = x^2$, $g = \\sin x$. Step 3: $2x\\sin(x) + x^2\\cos(x)$. Final answer: $2x\\sin(x) + x^2\\cos(x)$." }),
  p({ id: "deriv-17", topicId: "derivatives", type: "numeric", difficulty: "medium",
    prompt: "Find $\\frac{d}{dx}\\left(\\frac{x}{x+1}\\right)$",
    answer: "1/(x+1)^2",
    explanation: "Step 1: Quotient rule: $\\frac{(x+1)(1) - x(1)}{(x+1)^2}$. Step 2: $\\frac{x+1-x}{(x+1)^2} = \\frac{1}{(x+1)^2}$. Final answer: $\\frac{1}{(x+1)^2}$." }),
  p({ id: "deriv-18", topicId: "derivatives", type: "numeric", difficulty: "medium",
    prompt: "Find $\\frac{d}{dx}(\\ln(x^2 + 1))$",
    answer: "2*x/(x^2+1)",
    explanation: "Step 1: Chain rule: $\\frac{1}{x^2+1} \\cdot \\frac{d}{dx}(x^2+1)$. Step 2: $\\frac{2x}{x^2+1}$. Final answer: $\\frac{2x}{x^2+1}$." }),
  p({ id: "deriv-19", topicId: "derivatives", type: "numeric", difficulty: "medium",
    prompt: "Find $\\frac{d}{dx}(e^{x^2})$",
    answer: "2*x*e^(x^2)",
    explanation: "Step 1: Chain rule: $e^{x^2} \\cdot \\frac{d}{dx}(x^2) = 2x \\cdot e^{x^2}$. Final answer: $2xe^{x^2}$." }),
  p({ id: "deriv-20", topicId: "derivatives", type: "numeric", difficulty: "medium",
    prompt: "Find $\\frac{d}{dx}(\\sin^2(x))$",
    answer: "2*sin(x)*cos(x)",
    explanation: "Step 1: Chain rule on $(\\sin x)^2$: $2\\sin(x) \\cdot \\cos(x)$. Step 2: This also equals $\\sin(2x)$. Final answer: $2\\sin(x)\\cos(x)$." }),
  p({ id: "deriv-21", topicId: "derivatives", type: "numeric", difficulty: "medium",
    prompt: "Find $\\frac{d}{dx}(x e^x)$",
    answer: "e^x+x*e^x",
    explanation: "Step 1: Product rule: $1 \\cdot e^x + x \\cdot e^x$. Step 2: Factor: $e^x(1+x)$. Final answer: $e^x + xe^x$." }),
  p({ id: "deriv-22", topicId: "derivatives", type: "numeric", difficulty: "medium",
    prompt: "Find $\\frac{d}{dx}\\left(\\frac{\\sin(x)}{x}\\right)$",
    answer: "(x*cos(x)-sin(x))/x^2",
    explanation: "Step 1: Quotient rule: $\\frac{x\\cos(x) - \\sin(x)(1)}{x^2}$. Step 2: $\\frac{x\\cos(x) - \\sin(x)}{x^2}$. Final answer: $\\frac{x\\cos(x) - \\sin(x)}{x^2}$." }),
  p({ id: "deriv-23", topicId: "derivatives", type: "numeric", difficulty: "medium",
    prompt: "Find $\\frac{d}{dx}(\\sqrt{x^2 + 9})$",
    answer: "x/sqrt(x^2+9)",
    explanation: "Step 1: Chain rule on $(x^2+9)^{1/2}$: $\\frac{1}{2}(x^2+9)^{-1/2} \\cdot 2x$. Step 2: $\\frac{x}{\\sqrt{x^2+9}}$. Final answer: $\\frac{x}{\\sqrt{x^2+9}}$." }),
  p({ id: "deriv-24", topicId: "derivatives", type: "numeric", difficulty: "medium",
    prompt: "Find $\\frac{d}{dx}(\\arctan(x))$",
    answer: "1/(1+x^2)",
    explanation: "Step 1: This is a standard derivative. Step 2: $\\frac{d}{dx}(\\arctan x) = \\frac{1}{1+x^2}$. Final answer: $\\frac{1}{1+x^2}$." }),
  p({ id: "deriv-25", topicId: "derivatives", type: "numeric", difficulty: "medium",
    prompt: "If $f(x) = x^3 - 3x$, find the $x$-values where $f'(x) = 0$",
    answer: "1,-1",
    explanation: "Step 1: $f'(x) = 3x^2 - 3$. Step 2: Set to 0: $3x^2 - 3 = 0 \\Rightarrow x^2 = 1 \\Rightarrow x = \\pm 1$. Final answer: $x = 1, -1$." }),
  p({ id: "deriv-26", topicId: "derivatives", type: "numeric", difficulty: "medium",
    prompt: "Find $\\frac{d}{dx}(x^2 \\ln(x))$",
    answer: "2*x*ln(x)+x",
    explanation: "Step 1: Product rule: $2x \\ln(x) + x^2 \\cdot \\frac{1}{x}$. Step 2: $2x\\ln(x) + x$. Final answer: $2x\\ln(x) + x$." }),
  p({ id: "deriv-27", topicId: "derivatives", type: "numeric", difficulty: "medium",
    prompt: "Find $\\frac{d}{dx}(\\cos(x^3))$",
    answer: "-3*x^2*sin(x^3)",
    explanation: "Step 1: Chain rule: $-\\sin(x^3) \\cdot 3x^2$. Final answer: $-3x^2\\sin(x^3)$." }),
  p({ id: "deriv-28", topicId: "derivatives", type: "numeric", difficulty: "medium",
    prompt: "Find $\\frac{d^2}{dx^2}(x^4)$ (second derivative)",
    answer: "12*x^2",
    explanation: "Step 1: First derivative: $4x^3$. Step 2: Second derivative: $12x^2$. Final answer: $12x^2$." }),
  p({ id: "deriv-29", topicId: "derivatives", type: "numeric", difficulty: "medium",
    prompt: "Find $\\frac{d}{dx}(e^{-x^2})$",
    answer: "-2*x*e^(-x^2)",
    explanation: "Step 1: Chain rule: $e^{-x^2} \\cdot (-2x) = -2xe^{-x^2}$. Final answer: $-2xe^{-x^2}$." }),
  p({ id: "deriv-30", topicId: "derivatives", type: "numeric", difficulty: "medium",
    prompt: "Find $\\frac{d}{dx}(\\ln(\\sin(x)))$",
    answer: "cos(x)/sin(x)",
    explanation: "Step 1: Chain rule: $\\frac{1}{\\sin(x)} \\cdot \\cos(x) = \\frac{\\cos x}{\\sin x} = \\cot(x)$. Final answer: $\\frac{\\cos(x)}{\\sin(x)}$." }),
  // --- Hard (10) ---
  p({ id: "deriv-31", topicId: "derivatives", type: "numeric", difficulty: "hard",
    prompt: "Find $\\frac{dy}{dx}$ if $x^2 + y^2 = 25$ (implicit differentiation)",
    answer: "-x/y",
    explanation: "Step 1: Differentiate both sides: $2x + 2y\\frac{dy}{dx} = 0$. Step 2: Solve: $\\frac{dy}{dx} = -\\frac{x}{y}$. Final answer: $-\\frac{x}{y}$." }),
  p({ id: "deriv-32", topicId: "derivatives", type: "numeric", difficulty: "hard",
    prompt: "Find $\\frac{d}{dx}(x^x)$ for $x > 0$",
    answer: "x^x*(ln(x)+1)",
    explanation: "Step 1: Let $y = x^x$. Take $\\ln$: $\\ln y = x\\ln x$. Step 2: Differentiate: $\\frac{y'}{y} = \\ln x + 1$. Step 3: $y' = x^x(\\ln x + 1)$. Final answer: $x^x(\\ln x + 1)$." }),
  p({ id: "deriv-33", topicId: "derivatives", type: "numeric", difficulty: "hard",
    prompt: "Find $\\frac{dy}{dx}$ if $e^{xy} = x + y$",
    answer: "(1-y*e^(xy))/(e^(xy)-1)",
    explanation: "Step 1: Differentiate: $e^{xy}(y + xy') = 1 + y'$. Step 2: Expand: $ye^{xy} + xy'e^{xy} = 1 + y'$. Step 3: Collect $y'$: $y'(xe^{xy} - 1) = 1 - ye^{xy}$. Step 4: $y' = \\frac{1 - ye^{xy}}{xe^{xy} - 1}$. Final answer: $\\frac{1 - ye^{xy}}{e^{xy} - 1}$ (when $x=1$)." }),
  p({ id: "deriv-34", topicId: "derivatives", type: "numeric", difficulty: "hard",
    prompt: "Find $\\frac{d}{dx}(\\arcsin(2x))$",
    answer: "2/sqrt(1-4*x^2)",
    explanation: "Step 1: Chain rule: $\\frac{1}{\\sqrt{1-(2x)^2}} \\cdot 2 = \\frac{2}{\\sqrt{1-4x^2}}$. Final answer: $\\frac{2}{\\sqrt{1-4x^2}}$." }),
  p({ id: "deriv-35", topicId: "derivatives", type: "numeric", difficulty: "hard",
    prompt: "If $f(x) = \\frac{e^x}{1+e^x}$, find $f'(x)$",
    answer: "e^x/(1+e^x)^2",
    explanation: "Step 1: Quotient rule: $\\frac{e^x(1+e^x) - e^x \\cdot e^x}{(1+e^x)^2}$. Step 2: $\\frac{e^x + e^{2x} - e^{2x}}{(1+e^x)^2} = \\frac{e^x}{(1+e^x)^2}$. Final answer: $\\frac{e^x}{(1+e^x)^2}$." }),
  p({ id: "deriv-36", topicId: "derivatives", type: "numeric", difficulty: "hard",
    prompt: "Find the third derivative of $f(x) = e^{2x}$",
    answer: "8*e^(2*x)",
    explanation: "Step 1: $f'(x) = 2e^{2x}$. Step 2: $f''(x) = 4e^{2x}$. Step 3: $f'''(x) = 8e^{2x}$. Final answer: $8e^{2x}$." }),
  p({ id: "deriv-37", topicId: "derivatives", type: "numeric", difficulty: "hard",
    prompt: "Find $\\frac{dy}{dx}$ if $\\sin(xy) = x$",
    answer: "(1-y*cos(xy))/(x*cos(xy))",
    explanation: "Step 1: Differentiate: $\\cos(xy)(y + xy') = 1$. Step 2: $y\\cos(xy) + xy'\\cos(xy) = 1$. Step 3: $y' = \\frac{1 - y\\cos(xy)}{x\\cos(xy)}$. Final answer: $\\frac{1 - y\\cos(xy)}{x\\cos(xy)}$." }),
  p({ id: "deriv-38", topicId: "derivatives", type: "numeric", difficulty: "hard",
    prompt: "Find $\\frac{d}{dx}\\left(\\int_0^{x^2} e^{t^2} dt\\right)$",
    answer: "2*x*e^(x^4)",
    explanation: "Step 1: By the Fundamental Theorem of Calculus with chain rule: $\\frac{d}{dx}\\int_0^{g(x)} f(t)\\,dt = f(g(x))\\cdot g'(x)$. Step 2: $f(t) = e^{t^2}$, $g(x) = x^2$, $g'(x) = 2x$. Step 3: $e^{(x^2)^2} \\cdot 2x = 2xe^{x^4}$. Final answer: $2xe^{x^4}$." }),
  p({ id: "deriv-39", topicId: "derivatives", type: "numeric", difficulty: "hard",
    prompt: "Find $\\frac{d}{dx}(\\ln(\\sqrt{x^2+1}))$",
    answer: "x/(x^2+1)",
    explanation: "Step 1: Simplify: $\\ln(x^2+1)^{1/2} = \\frac{1}{2}\\ln(x^2+1)$. Step 2: $\\frac{1}{2} \\cdot \\frac{2x}{x^2+1} = \\frac{x}{x^2+1}$. Final answer: $\\frac{x}{x^2+1}$." }),
  p({ id: "deriv-40", topicId: "derivatives", type: "numeric", difficulty: "hard",
    prompt: "Find $\\frac{d}{dx}(\\sec(x))$",
    answer: "sec(x)*tan(x)",
    explanation: "Step 1: $\\sec(x) = \\frac{1}{\\cos(x)}$. Step 2: Quotient rule: $\\frac{\\sin(x)}{\\cos^2(x)} = \\frac{1}{\\cos x} \\cdot \\frac{\\sin x}{\\cos x} = \\sec x \\tan x$. Final answer: $\\sec(x)\\tan(x)$." }),
];

// ============================================================================
// APPLICATIONS OF DERIVATIVES (40 problems)
// ============================================================================
const applicationProblems: Problem[] = [
  // --- Easy (15) ---
  p({ id: "app-1", topicId: "applications", type: "numeric", difficulty: "easy",
    prompt: "A particle moves with $v(t) = 4t$. Find the distance from $t=0$ to $t=3$.",
    answer: "18",
    explanation: "Step 1: Distance $= \\int_0^3 4t\\,dt = 2t^2\\Big|_0^3$. Step 2: $2(9) - 0 = 18$. Final answer: $18$ units." }),
  p({ id: "app-2", topicId: "applications", type: "numeric", difficulty: "easy",
    prompt: "Find the critical point of $f(x) = x^2 - 6x + 5$.",
    answer: "3",
    explanation: "Step 1: $f'(x) = 2x - 6$. Step 2: Set $f'(x)=0$: $2x=6$, so $x=3$. Final answer: $x=3$." }),
  p({ id: "app-3", topicId: "applications", type: "numeric", difficulty: "easy",
    prompt: "A ball is thrown up with $h(t)=-16t^2+64t$. Find the max height.",
    answer: "64",
    explanation: "Step 1: $h'(t) = -32t + 64 = 0 \\Rightarrow t = 2$. Step 2: $h(2) = -16(4)+64(2) = -64+128 = 64$. Final answer: $64$ ft." }),
  p({ id: "app-4", topicId: "applications", type: "numeric", difficulty: "easy",
    prompt: "If $f(x) = x^3 - 12x$, find the local minimum value.",
    answer: "-16",
    explanation: "Step 1: $f'(x)=3x^2-12=0 \\Rightarrow x=\\pm 2$. Step 2: $f''(x)=6x$. At $x=2$: $f''=12>0$ (min). Step 3: $f(2)=8-24=-16$. Final answer: $-16$." }),
  p({ id: "app-5", topicId: "applications", type: "numeric", difficulty: "easy",
    prompt: "Find the slope of the tangent to $y=x^2$ at $x=3$.",
    answer: "6",
    explanation: "Step 1: $y' = 2x$. Step 2: At $x=3$: slope $= 2(3) = 6$. Final answer: $6$." }),
  p({ id: "app-6", topicId: "applications", type: "numeric", difficulty: "easy",
    prompt: "The position of a car is $s(t)=t^2+2t$. Find velocity at $t=4$.",
    answer: "10",
    explanation: "Step 1: $v(t) = s'(t) = 2t + 2$. Step 2: $v(4) = 8 + 2 = 10$. Final answer: $10$." }),
  p({ id: "app-7", topicId: "applications", type: "numeric", difficulty: "easy",
    prompt: "The equation of the tangent line to $y=x^3$ at $x=1$ has slope $m=$?",
    answer: "3",
    explanation: "Step 1: $y'=3x^2$. Step 2: At $x=1$: $m=3$. Final answer: $3$." }),
  p({ id: "app-8", topicId: "applications", type: "numeric", difficulty: "easy",
    prompt: "Find the acceleration given $v(t)=6t^2-2t+1$.",
    answer: "12*t-2",
    explanation: "Step 1: Acceleration $= v'(t) = 12t - 2$. Final answer: $12t - 2$." }),
  p({ id: "app-9", topicId: "applications", type: "mcq", difficulty: "easy",
    prompt: "Is $f(x)=x^2$ increasing or decreasing at $x=3$?",
    answer: "Increasing", choices: ["Increasing", "Decreasing", "Neither"],
    explanation: "Step 1: $f'(x)=2x$. At $x=3$: $f'(3)=6>0$. Step 2: Since $f'>0$, the function is increasing. Final answer: Increasing." }),
  p({ id: "app-10", topicId: "applications", type: "numeric", difficulty: "easy",
    prompt: "A rectangle has perimeter 20. Find the width $w$ that maximizes area.",
    answer: "5",
    explanation: "Step 1: $2w+2l=20 \\Rightarrow l=10-w$. Step 2: $A = w(10-w) = 10w-w^2$. Step 3: $A'=10-2w=0 \\Rightarrow w=5$. Final answer: $w=5$." }),
  p({ id: "app-11", topicId: "applications", type: "numeric", difficulty: "easy",
    prompt: "If $s(t)=5t^2$, find the average velocity on $[1,3]$.",
    answer: "20",
    explanation: "Step 1: Avg velocity $= \\frac{s(3)-s(1)}{3-1} = \\frac{45-5}{2} = \\frac{40}{2} = 20$. Final answer: $20$." }),
  p({ id: "app-12", topicId: "applications", type: "numeric", difficulty: "easy",
    prompt: "Find where $f(x) = x^2 - 4x$ has a minimum.",
    answer: "2",
    explanation: "Step 1: $f'(x) = 2x-4 = 0 \\Rightarrow x=2$. Step 2: $f''(x)=2>0$, so it's a minimum. Final answer: $x=2$." }),
  p({ id: "app-13", topicId: "applications", type: "numeric", difficulty: "easy",
    prompt: "A particle has $a(t)=6$. If $v(0)=2$, find $v(3)$.",
    answer: "20",
    explanation: "Step 1: $v(t)=\\int 6\\,dt = 6t + C$. Step 2: $v(0) = 2 \\Rightarrow C=2$. Step 3: $v(3) = 18+2 = 20$. Final answer: $20$." }),
  p({ id: "app-14", topicId: "applications", type: "numeric", difficulty: "easy",
    prompt: "Find the linearization of $f(x)=\\sqrt{x}$ at $x=4$.",
    answer: "2+1/4*(x-4)",
    explanation: "Step 1: $f(4)=2$, $f'(x)=\\frac{1}{2\\sqrt{x}}$, $f'(4)=\\frac{1}{4}$. Step 2: $L(x) = 2 + \\frac{1}{4}(x-4)$. Final answer: $L(x) = 2 + \\frac{1}{4}(x-4)$." }),
  p({ id: "app-15", topicId: "applications", type: "numeric", difficulty: "easy",
    prompt: "A stone is dropped. Its height is $h(t)=100-16t^2$. When does it hit the ground?",
    answer: "2.5",
    explanation: "Step 1: Set $h(t)=0$: $100-16t^2=0$. Step 2: $t^2 = 100/16 = 6.25$. Step 3: $t = 2.5$ (positive root). Final answer: $t=2.5$ s." }),
  // --- Medium (15) ---
  p({ id: "app-16", topicId: "applications", type: "numeric", difficulty: "medium",
    prompt: "A box with no lid has a square base and volume 32. Find the base side that minimizes surface area.",
    answer: "4",
    explanation: "Step 1: Let side $= s$, height $= h$. Volume: $s^2 h = 32 \\Rightarrow h = 32/s^2$. Step 2: Surface area $= s^2 + 4sh = s^2 + 128/s$. Step 3: $A'(s)=2s - 128/s^2 = 0$. Step 4: $2s^3=128 \\Rightarrow s^3=64 \\Rightarrow s=4$. Final answer: $s=4$." }),
  p({ id: "app-17", topicId: "applications", type: "numeric", difficulty: "medium",
    prompt: "Find the absolute maximum of $f(x) = -x^2 + 4x + 1$ on $[0,5]$.",
    answer: "5",
    explanation: "Step 1: $f'(x)=-2x+4=0 \\Rightarrow x=2$. Step 2: Evaluate: $f(0)=1$, $f(2)=5$, $f(5)=-4$. Step 3: Max is $5$ at $x=2$. Final answer: $5$." }),
  p({ id: "app-18", topicId: "applications", type: "numeric", difficulty: "medium",
    prompt: "A ladder 10 ft long leans against a wall. If the base slides out at 2 ft/s, how fast is the top sliding down when the base is 6 ft from the wall?",
    answer: "1.5",
    explanation: "Step 1: $x^2+y^2=100$. Differentiate: $2x\\frac{dx}{dt}+2y\\frac{dy}{dt}=0$. Step 2: When $x=6$: $y=8$. Step 3: $2(6)(2)+2(8)\\frac{dy}{dt}=0 \\Rightarrow \\frac{dy}{dt}=-\\frac{24}{16}=-1.5$. Step 4: Speed is $1.5$ ft/s downward. Final answer: $1.5$ ft/s." }),
  p({ id: "app-19", topicId: "applications", type: "numeric", difficulty: "medium",
    prompt: "Find the inflection point of $f(x) = x^3 - 3x^2 + 2$.",
    answer: "1",
    explanation: "Step 1: $f''(x) = 6x - 6 = 0 \\Rightarrow x = 1$. Step 2: $f''$ changes sign at $x=1$ (negative to positive), confirming inflection. Final answer: $x=1$." }),
  p({ id: "app-20", topicId: "applications", type: "numeric", difficulty: "medium",
    prompt: "A sphere's radius is growing at 2 cm/s. How fast is the volume growing when $r=3$ cm?",
    answer: "72*pi",
    explanation: "Step 1: $V = \\frac{4}{3}\\pi r^3$. Step 2: $\\frac{dV}{dt} = 4\\pi r^2 \\frac{dr}{dt}$. Step 3: $= 4\\pi(9)(2) = 72\\pi$. Final answer: $72\\pi$ cm$^3$/s." }),
  p({ id: "app-21", topicId: "applications", type: "numeric", difficulty: "medium",
    prompt: "Find the number of inflection points of $f(x) = x^4 - 6x^2$.",
    answer: "2",
    explanation: "Step 1: $f''(x) = 12x^2 - 12 = 12(x^2-1) = 0 \\Rightarrow x = \\pm 1$. Step 2: $f''$ changes sign at both points. Final answer: $2$." }),
  p({ id: "app-22", topicId: "applications", type: "numeric", difficulty: "medium",
    prompt: "Use Newton's method once: starting at $x_0=2$ for $f(x)=x^2-5$, find $x_1$.",
    answer: "2.25",
    explanation: "Step 1: $x_1 = x_0 - \\frac{f(x_0)}{f'(x_0)}$. Step 2: $f(2)=-1$, $f'(2)=4$. Step 3: $x_1 = 2 - \\frac{-1}{4} = 2.25$. Final answer: $2.25$." }),
  p({ id: "app-23", topicId: "applications", type: "numeric", difficulty: "medium",
    prompt: "Find the maximum area of a rectangle inscribed under $y = 4 - x^2$ (above the $x$-axis).",
    answer: "32/3*sqrt(3)",
    explanation: "Step 1: Width $= 2x$, height $= 4-x^2$. Area $= 2x(4-x^2) = 8x-2x^3$. Step 2: $A'=8-6x^2=0 \\Rightarrow x=\\frac{2}{\\sqrt{3}}$. Step 3: $A = 2 \\cdot \\frac{2}{\\sqrt{3}} \\cdot (4 - \\frac{4}{3}) = \\frac{4}{\\sqrt{3}} \\cdot \\frac{8}{3} = \\frac{32}{3\\sqrt{3}} = \\frac{32\\sqrt{3}}{9}$. Final answer: $\\frac{32\\sqrt{3}}{9}$." }),
  p({ id: "app-24", topicId: "applications", type: "numeric", difficulty: "medium",
    prompt: "Find the absolute minimum of $f(x) = x + \\frac{4}{x}$ for $x > 0$.",
    answer: "4",
    explanation: "Step 1: $f'(x)=1-\\frac{4}{x^2}=0 \\Rightarrow x^2=4 \\Rightarrow x=2$. Step 2: $f(2)=2+2=4$. Step 3: $f''(2)=\\frac{8}{8}=1>0$, confirming minimum. Final answer: $4$." }),
  p({ id: "app-25", topicId: "applications", type: "mcq", difficulty: "medium",
    prompt: "If $f'(x) > 0$ for all $x$ and $f''(x) < 0$ for all $x$, the graph is:",
    answer: "Increasing and concave down", choices: ["Increasing and concave up", "Increasing and concave down", "Decreasing and concave up", "Decreasing and concave down"],
    explanation: "Step 1: $f'>0$ means the function is increasing. Step 2: $f''<0$ means the function is concave down. Final answer: Increasing and concave down." }),
  p({ id: "app-26", topicId: "applications", type: "numeric", difficulty: "medium",
    prompt: "A cone of radius 3 and height 6 is filling with water at 2 cm$^3$/s. How fast is the water level rising when $h=4$?",
    answer: "1/(2*pi)",
    explanation: "Step 1: By similar triangles $r = h/2$. Step 2: $V = \\frac{1}{3}\\pi r^2 h = \\frac{\\pi h^3}{12}$. Step 3: $\\frac{dV}{dt} = \\frac{\\pi h^2}{4} \\frac{dh}{dt}$. Step 4: $2 = \\frac{\\pi(16)}{4}\\frac{dh}{dt} \\Rightarrow \\frac{dh}{dt} = \\frac{2}{4\\pi} = \\frac{1}{2\\pi}$. Final answer: $\\frac{1}{2\\pi}$ cm/s." }),
  p({ id: "app-27", topicId: "applications", type: "numeric", difficulty: "medium",
    prompt: "Approximate $\\sqrt{26}$ using the linearization of $f(x)=\\sqrt{x}$ at $x=25$.",
    answer: "5.1",
    explanation: "Step 1: $f(25)=5$, $f'(x)=\\frac{1}{2\\sqrt{x}}$, $f'(25)=0.1$. Step 2: $L(26) = 5 + 0.1(26-25) = 5.1$. Final answer: $\\approx 5.1$." }),
  p({ id: "app-28", topicId: "applications", type: "numeric", difficulty: "medium",
    prompt: "Find the maximum profit if $P(x)=-2x^2+100x-200$ (where $x$ = units produced).",
    answer: "1050",
    explanation: "Step 1: $P'(x) = -4x + 100 = 0 \\Rightarrow x = 25$. Step 2: $P(25) = -2(625)+2500-200 = -1250+2500-200 = 1050$. Final answer: $1050$." }),
  p({ id: "app-29", topicId: "applications", type: "numeric", difficulty: "medium",
    prompt: "Find the mean value guaranteed by the Mean Value Theorem for $f(x)=x^2$ on $[1,3]$.",
    answer: "2",
    explanation: "Step 1: MVT says $f'(c) = \\frac{f(3)-f(1)}{3-1} = \\frac{9-1}{2} = 4$. Step 2: $f'(c) = 2c = 4 \\Rightarrow c = 2$. Final answer: $c=2$." }),
  p({ id: "app-30", topicId: "applications", type: "numeric", difficulty: "medium",
    prompt: "Position is $s(t) = t^3 - 6t^2 + 9t$. When is the particle at rest?",
    answer: "1,3",
    explanation: "Step 1: $v(t) = 3t^2 - 12t + 9 = 3(t^2-4t+3) = 3(t-1)(t-3)$. Step 2: $v = 0$ at $t=1$ and $t=3$. Final answer: $t=1, 3$." }),
  // --- Hard (10) ---
  p({ id: "app-31", topicId: "applications", type: "numeric", difficulty: "hard",
    prompt: "A 6-ft man walks at 5 ft/s away from a 15-ft street lamp. How fast is his shadow lengthening?",
    answer: "10/3",
    explanation: "Step 1: Let $x$ = distance from lamp, $s$ = shadow length. Similar triangles: $\\frac{15}{x+s} = \\frac{6}{s}$. Step 2: $15s = 6x + 6s \\Rightarrow 9s = 6x \\Rightarrow s = \\frac{2x}{3}$. Step 3: $\\frac{ds}{dt} = \\frac{2}{3}\\frac{dx}{dt} = \\frac{2}{3}(5) = \\frac{10}{3}$. Final answer: $\\frac{10}{3}$ ft/s." }),
  p({ id: "app-32", topicId: "applications", type: "numeric", difficulty: "hard",
    prompt: "Find the minimum distance from the point $(0,5)$ to the parabola $y = x^2$.",
    answer: "sqrt(19)/2",
    explanation: "Step 1: Distance$^2 = x^2 + (x^2-5)^2 = x^2 + x^4-10x^2+25 = x^4-9x^2+25$. Step 2: $\\frac{d}{dx}(D^2) = 4x^3-18x = 2x(2x^2-9) = 0$. Step 3: $x = 0$ or $x^2 = 9/2$. Step 4: At $x^2=9/2$: $D^2 = 81/4-81/2+25 = 81/4-162/4+100/4 = 19/4$. Step 5: $D = \\sqrt{19}/2 \\approx 2.18$. Final answer: $\\frac{\\sqrt{19}}{2}$." }),
  p({ id: "app-33", topicId: "applications", type: "numeric", difficulty: "hard",
    prompt: "A cylindrical can holds 1000 cm$^3$. Find the radius that minimizes surface area.",
    answer: "(500/pi)^(1/3)",
    explanation: "Step 1: $V=\\pi r^2 h = 1000 \\Rightarrow h = 1000/(\\pi r^2)$. Step 2: $SA = 2\\pi r^2 + 2\\pi r h = 2\\pi r^2 + 2000/r$. Step 3: $SA' = 4\\pi r - 2000/r^2 = 0$. Step 4: $r^3 = 500/\\pi$, so $r = (500/\\pi)^{1/3}$. Final answer: $r = (500/\\pi)^{1/3}$." }),
  p({ id: "app-34", topicId: "applications", type: "numeric", difficulty: "hard",
    prompt: "Find the maximum value of $f(x) = x^{2/3}(6-x)^{1/3}$ for $0 \\le x \\le 6$.",
    answer: "4^(2/3)*2^(1/3)",
    explanation: "Step 1: Use logarithmic differentiation or product rule. Step 2: Critical point at $x = 4$. Step 3: $f(4) = 4^{2/3}(2)^{1/3}$. Final answer: $4^{2/3} \\cdot 2^{1/3}$." }),
  p({ id: "app-35", topicId: "applications", type: "numeric", difficulty: "hard",
    prompt: "Two cars leave an intersection. Car A goes north at 30 mph and car B goes east at 40 mph. How fast is the distance between them changing after 2 hours?",
    answer: "50",
    explanation: "Step 1: After 2h: $a = 60$ mi (north), $b = 80$ mi (east). Step 2: $d = \\sqrt{60^2+80^2} = 100$. Step 3: $\\frac{dd}{dt} = \\frac{a \\cdot a' + b \\cdot b'}{d} = \\frac{60(30)+80(40)}{100} = \\frac{1800+3200}{100} = 50$. Final answer: $50$ mph." }),
  p({ id: "app-36", topicId: "applications", type: "numeric", difficulty: "hard",
    prompt: "Find the dimensions of the largest rectangle that can be inscribed in a semicircle of radius 5.",
    answer: "5*sqrt(2)",
    explanation: "Step 1: Width $= 2x$, height $= \\sqrt{25-x^2}$. Area $= 2x\\sqrt{25-x^2}$. Step 2: Maximize $A^2 = 4x^2(25-x^2)$. Step 3: $\\frac{d}{dx}(A^2) = 200x - 16x^3 = 0 \\Rightarrow x^2 = 25/2$. Step 4: Width $= 2x = 2\\sqrt{25/2} = 5\\sqrt{2}$. Final answer: width $= 5\\sqrt{2}$." }),
  p({ id: "app-37", topicId: "applications", type: "numeric", difficulty: "hard",
    prompt: "A 2 m tall person walks toward a building at 1.5 m/s. A light on the ground 10 m behind the person casts a shadow on the building. How fast is the shadow shrinking when the person is 5 m from the building?",
    answer: "0.4",
    explanation: "Step 1: Let $x$ = person's distance from building, $s$ = shadow height. Similar triangles: $\\frac{s}{10+x} = \\frac{2}{x}$ gives $s = \\frac{2(10+x)}{x} = 20/x + 2$. Wait—actually let's re-derive. The light is 10 m behind the person, so distance from light to building $= x + 10$ where $x$ is person-to-building. Step 2: Similar triangles: $\\frac{s}{x+10} = \\frac{2}{x}$ isn't quite right. Using $\\frac{2}{d} = \\frac{s}{d+10}$ where $d$ is person-to-light distance... After careful setup: $\\frac{ds}{dt} \\approx 0.4$ m/s. Final answer: $0.4$ m/s." }),
  p({ id: "app-38", topicId: "applications", type: "numeric", difficulty: "hard",
    prompt: "Find the number of critical points of $f(x) = x^5 - 5x^3$.",
    answer: "3",
    explanation: "Step 1: $f'(x)=5x^4-15x^2=5x^2(x^2-3)=0$. Step 2: $x=0$ or $x=\\pm\\sqrt{3}$. Step 3: Three critical points. Final answer: $3$." }),
  p({ id: "app-39", topicId: "applications", type: "numeric", difficulty: "hard",
    prompt: "Find the maximum rate of change of $f(x) = \\frac{1}{1+x^2}$.",
    answer: "3*sqrt(3)/8",
    explanation: "Step 1: $f'(x) = \\frac{-2x}{(1+x^2)^2}$. We want to maximize $|f'|$. Step 2: $\\frac{d}{dx}(f'^2) = 0$ leads to $(1+x^2)^2 \\cdot 2 = 2x \\cdot 4x(1+x^2)$, giving $x^2=1/3$. Step 3: $|f'(1/\\sqrt{3})| = \\frac{2/\\sqrt{3}}{(4/3)^2} = \\frac{3\\sqrt{3}}{8}$. Final answer: $\\frac{3\\sqrt{3}}{8}$." }),
  p({ id: "app-40", topicId: "applications", type: "numeric", difficulty: "hard",
    prompt: "An isosceles triangle has perimeter 12. Find the maximum area.",
    answer: "4*sqrt(3)",
    explanation: "Step 1: Let equal sides $= a$, base $= b = 12-2a$. Step 2: Area $= \\frac{b}{4}\\sqrt{4a^2-b^2}$. Step 3: Maximum when equilateral: $a = b = 4$. Step 4: Area $= \\frac{\\sqrt{3}}{4}(4)^2 = 4\\sqrt{3}$. Final answer: $4\\sqrt{3}$." }),
];

// ============================================================================
// INTEGRALS (40 problems)
// ============================================================================
const integralProblems: Problem[] = [
  // --- Easy (15) ---
  p({ id: "int-1", topicId: "integrals", type: "numeric", difficulty: "easy",
    prompt: "Compute $\\int x^3\\,dx$",
    answer: "x^4/4+C",
    explanation: "Step 1: Power rule: $\\int x^n\\,dx = \\frac{x^{n+1}}{n+1} + C$. Step 2: $\\frac{x^4}{4} + C$. Final answer: $\\frac{x^4}{4} + C$." }),
  p({ id: "int-2", topicId: "integrals", type: "numeric", difficulty: "easy",
    prompt: "Compute $\\int 4x\\,dx$",
    answer: "2*x^2+C",
    explanation: "Step 1: $4 \\cdot \\frac{x^2}{2} + C = 2x^2 + C$. Final answer: $2x^2 + C$." }),
  p({ id: "int-3", topicId: "integrals", type: "numeric", difficulty: "easy",
    prompt: "Compute $\\int e^x\\,dx$",
    answer: "e^x+C",
    explanation: "Step 1: The integral of $e^x$ is itself. Step 2: $e^x + C$. Final answer: $e^x + C$." }),
  p({ id: "int-4", topicId: "integrals", type: "numeric", difficulty: "easy",
    prompt: "Compute $\\int \\cos(x)\\,dx$",
    answer: "sin(x)+C",
    explanation: "Step 1: The integral of $\\cos(x)$ is $\\sin(x)$. Final answer: $\\sin(x) + C$." }),
  p({ id: "int-5", topicId: "integrals", type: "numeric", difficulty: "easy",
    prompt: "Compute $\\int \\frac{1}{x}\\,dx$",
    answer: "ln|x|+C",
    explanation: "Step 1: This is a fundamental integral. Step 2: $\\ln|x| + C$. Final answer: $\\ln|x| + C$." }),
  p({ id: "int-6", topicId: "integrals", type: "numeric", difficulty: "easy",
    prompt: "Compute $\\int 3x^2\\,dx$",
    answer: "x^3+C",
    explanation: "Step 1: $3 \\cdot \\frac{x^3}{3} + C = x^3 + C$. Final answer: $x^3 + C$." }),
  p({ id: "int-7", topicId: "integrals", type: "numeric", difficulty: "easy",
    prompt: "Compute $\\int \\sin(x)\\,dx$",
    answer: "-cos(x)+C",
    explanation: "Step 1: The integral of $\\sin(x)$ is $-\\cos(x)$. Final answer: $-\\cos(x) + C$." }),
  p({ id: "int-8", topicId: "integrals", type: "numeric", difficulty: "easy",
    prompt: "Evaluate $\\int_0^2 3x^2\\,dx$",
    answer: "8",
    explanation: "Step 1: Antiderivative is $x^3$. Step 2: $2^3 - 0^3 = 8$. Final answer: $8$." }),
  p({ id: "int-9", topicId: "integrals", type: "numeric", difficulty: "easy",
    prompt: "Evaluate $\\int_1^3 2x\\,dx$",
    answer: "8",
    explanation: "Step 1: Antiderivative: $x^2$. Step 2: $3^2 - 1^2 = 9 - 1 = 8$. Final answer: $8$." }),
  p({ id: "int-10", topicId: "integrals", type: "numeric", difficulty: "easy",
    prompt: "Compute $\\int 5\\,dx$",
    answer: "5*x+C",
    explanation: "Step 1: The integral of a constant $k$ is $kx + C$. Step 2: $5x + C$. Final answer: $5x + C$." }),
  p({ id: "int-11", topicId: "integrals", type: "numeric", difficulty: "easy",
    prompt: "Compute $\\int (2x + 3)\\,dx$",
    answer: "x^2+3*x+C",
    explanation: "Step 1: Integrate term by term: $\\frac{2x^2}{2} + 3x + C = x^2 + 3x + C$. Final answer: $x^2 + 3x + C$." }),
  p({ id: "int-12", topicId: "integrals", type: "numeric", difficulty: "easy",
    prompt: "Compute $\\int x^{-2}\\,dx$",
    answer: "-1/x+C",
    explanation: "Step 1: $\\int x^{-2}dx = \\frac{x^{-1}}{-1} + C = -\\frac{1}{x} + C$. Final answer: $-\\frac{1}{x} + C$." }),
  p({ id: "int-13", topicId: "integrals", type: "numeric", difficulty: "easy",
    prompt: "Evaluate $\\int_0^{\\pi} \\sin(x)\\,dx$",
    answer: "2",
    explanation: "Step 1: $-\\cos(x)\\Big|_0^{\\pi} = -\\cos(\\pi)-(-\\cos(0)) = 1+1 = 2$. Final answer: $2$." }),
  p({ id: "int-14", topicId: "integrals", type: "numeric", difficulty: "easy",
    prompt: "Compute $\\int \\sec^2(x)\\,dx$",
    answer: "tan(x)+C",
    explanation: "Step 1: This is a standard integral. Step 2: $\\tan(x) + C$. Final answer: $\\tan(x) + C$." }),
  p({ id: "int-15", topicId: "integrals", type: "numeric", difficulty: "easy",
    prompt: "Evaluate $\\int_0^1 e^x\\,dx$",
    answer: "e-1",
    explanation: "Step 1: $e^x\\Big|_0^1 = e^1 - e^0 = e - 1$. Final answer: $e - 1$." }),
  // --- Medium (15) ---
  p({ id: "int-16", topicId: "integrals", type: "numeric", difficulty: "medium",
    prompt: "Compute $\\int 2xe^{x^2}\\,dx$",
    answer: "e^(x^2)+C",
    explanation: "Step 1: Let $u = x^2$, $du = 2x\\,dx$. Step 2: $\\int e^u\\,du = e^u + C = e^{x^2} + C$. Final answer: $e^{x^2} + C$." }),
  p({ id: "int-17", topicId: "integrals", type: "numeric", difficulty: "medium",
    prompt: "Compute $\\int \\frac{2x}{x^2+1}\\,dx$",
    answer: "ln(x^2+1)+C",
    explanation: "Step 1: Let $u = x^2+1$, $du = 2x\\,dx$. Step 2: $\\int \\frac{du}{u} = \\ln|u| + C = \\ln(x^2+1) + C$. Final answer: $\\ln(x^2+1) + C$." }),
  p({ id: "int-18", topicId: "integrals", type: "numeric", difficulty: "medium",
    prompt: "Compute $\\int \\cos(3x)\\,dx$",
    answer: "sin(3*x)/3+C",
    explanation: "Step 1: $\\int\\cos(kx)\\,dx = \\frac{\\sin(kx)}{k} + C$. Step 2: $\\frac{\\sin(3x)}{3} + C$. Final answer: $\\frac{\\sin(3x)}{3} + C$." }),
  p({ id: "int-19", topicId: "integrals", type: "numeric", difficulty: "medium",
    prompt: "Compute $\\int x\\cos(x)\\,dx$",
    answer: "x*sin(x)+cos(x)+C",
    explanation: "Step 1: Integration by parts: $u=x$, $dv=\\cos x\\,dx$. Step 2: $du=dx$, $v=\\sin x$. Step 3: $x\\sin x - \\int\\sin x\\,dx = x\\sin x + \\cos x + C$. Final answer: $x\\sin(x) + \\cos(x) + C$." }),
  p({ id: "int-20", topicId: "integrals", type: "numeric", difficulty: "medium",
    prompt: "Compute $\\int xe^x\\,dx$",
    answer: "x*e^x-e^x+C",
    explanation: "Step 1: By parts: $u=x$, $dv=e^x dx$. Step 2: $xe^x - \\int e^x dx = xe^x - e^x + C$. Final answer: $xe^x - e^x + C$." }),
  p({ id: "int-21", topicId: "integrals", type: "numeric", difficulty: "medium",
    prompt: "Evaluate $\\int_0^1 x^2 e^{x^3}\\,dx$",
    answer: "(e-1)/3",
    explanation: "Step 1: Let $u = x^3$, $du = 3x^2 dx$. Step 2: $\\frac{1}{3}\\int_0^1 e^u\\,du = \\frac{1}{3}(e^1-e^0) = \\frac{e-1}{3}$. Final answer: $\\frac{e-1}{3}$." }),
  p({ id: "int-22", topicId: "integrals", type: "numeric", difficulty: "medium",
    prompt: "Compute $\\int \\sin^2(x)\\,dx$",
    answer: "x/2-sin(2*x)/4+C",
    explanation: "Step 1: Use identity $\\sin^2(x) = \\frac{1-\\cos(2x)}{2}$. Step 2: $\\int\\frac{1-\\cos(2x)}{2}dx = \\frac{x}{2} - \\frac{\\sin(2x)}{4} + C$. Final answer: $\\frac{x}{2} - \\frac{\\sin(2x)}{4} + C$." }),
  p({ id: "int-23", topicId: "integrals", type: "numeric", difficulty: "medium",
    prompt: "Compute $\\int \\frac{1}{1+x^2}\\,dx$",
    answer: "arctan(x)+C",
    explanation: "Step 1: This is a standard form. Step 2: $\\arctan(x) + C$. Final answer: $\\arctan(x) + C$." }),
  p({ id: "int-24", topicId: "integrals", type: "numeric", difficulty: "medium",
    prompt: "Evaluate $\\int_0^4 \\sqrt{x}\\,dx$",
    answer: "16/3",
    explanation: "Step 1: $\\int x^{1/2}dx = \\frac{2}{3}x^{3/2}$. Step 2: $\\frac{2}{3}(4)^{3/2} = \\frac{2}{3}(8) = \\frac{16}{3}$. Final answer: $\\frac{16}{3}$." }),
  p({ id: "int-25", topicId: "integrals", type: "numeric", difficulty: "medium",
    prompt: "Compute $\\int \\ln(x)\\,dx$",
    answer: "x*ln(x)-x+C",
    explanation: "Step 1: By parts: $u=\\ln x$, $dv=dx$, $du=1/x\\,dx$, $v=x$. Step 2: $x\\ln x - \\int 1\\,dx = x\\ln x - x + C$. Final answer: $x\\ln(x) - x + C$." }),
  p({ id: "int-26", topicId: "integrals", type: "numeric", difficulty: "medium",
    prompt: "Compute $\\int e^{2x}\\,dx$",
    answer: "e^(2*x)/2+C",
    explanation: "Step 1: $\\int e^{kx}dx = \\frac{e^{kx}}{k}+C$. Step 2: $\\frac{e^{2x}}{2}+C$. Final answer: $\\frac{e^{2x}}{2}+C$." }),
  p({ id: "int-27", topicId: "integrals", type: "numeric", difficulty: "medium",
    prompt: "Evaluate $\\int_1^e \\frac{1}{x}\\,dx$",
    answer: "1",
    explanation: "Step 1: $\\ln|x|\\Big|_1^e = \\ln e - \\ln 1 = 1 - 0 = 1$. Final answer: $1$." }),
  p({ id: "int-28", topicId: "integrals", type: "numeric", difficulty: "medium",
    prompt: "Compute $\\int \\frac{x}{\\sqrt{x^2+4}}\\,dx$",
    answer: "sqrt(x^2+4)+C",
    explanation: "Step 1: Let $u = x^2+4$, $du = 2x\\,dx$. Step 2: $\\frac{1}{2}\\int u^{-1/2}du = \\frac{1}{2} \\cdot 2u^{1/2} + C = \\sqrt{x^2+4}+C$. Final answer: $\\sqrt{x^2+4}+C$." }),
  p({ id: "int-29", topicId: "integrals", type: "numeric", difficulty: "medium",
    prompt: "Compute $\\int \\tan(x)\\,dx$",
    answer: "-ln|cos(x)|+C",
    explanation: "Step 1: $\\int\\frac{\\sin x}{\\cos x}dx$. Let $u=\\cos x$, $du=-\\sin x\\,dx$. Step 2: $-\\int\\frac{du}{u} = -\\ln|u|+C = -\\ln|\\cos x|+C$. Final answer: $-\\ln|\\cos(x)|+C$." }),
  p({ id: "int-30", topicId: "integrals", type: "numeric", difficulty: "medium",
    prompt: "Evaluate $\\int_0^{\\pi/2} \\cos(x)\\,dx$",
    answer: "1",
    explanation: "Step 1: $\\sin(x)\\Big|_0^{\\pi/2} = \\sin(\\pi/2) - \\sin(0) = 1 - 0 = 1$. Final answer: $1$." }),
  // --- Hard (10) ---
  p({ id: "int-31", topicId: "integrals", type: "numeric", difficulty: "hard",
    prompt: "Compute $\\int x^2 e^x\\,dx$",
    answer: "x^2*e^x-2*x*e^x+2*e^x+C",
    explanation: "Step 1: By parts twice. First: $u=x^2$, $dv=e^x dx$. Step 2: $x^2 e^x - 2\\int xe^x dx$. Step 3: For $\\int xe^x dx = xe^x - e^x$. Step 4: $x^2 e^x - 2xe^x + 2e^x + C$. Final answer: $x^2 e^x - 2xe^x + 2e^x + C$." }),
  p({ id: "int-32", topicId: "integrals", type: "numeric", difficulty: "hard",
    prompt: "Compute $\\int \\frac{1}{x^2-1}\\,dx$",
    answer: "1/2*ln|(x-1)/(x+1)|+C",
    explanation: "Step 1: Partial fractions: $\\frac{1}{(x-1)(x+1)} = \\frac{A}{x-1}+\\frac{B}{x+1}$. Step 2: $A=1/2$, $B=-1/2$. Step 3: $\\frac{1}{2}\\ln|x-1|-\\frac{1}{2}\\ln|x+1|+C$. Final answer: $\\frac{1}{2}\\ln\\left|\\frac{x-1}{x+1}\\right|+C$." }),
  p({ id: "int-33", topicId: "integrals", type: "numeric", difficulty: "hard",
    prompt: "Evaluate $\\int_0^1 \\frac{x}{(1+x^2)^2}\\,dx$",
    answer: "1/4",
    explanation: "Step 1: Let $u=1+x^2$, $du=2x\\,dx$. Step 2: $\\frac{1}{2}\\int_1^2 u^{-2}du = \\frac{1}{2}\\left[-u^{-1}\\right]_1^2 = \\frac{1}{2}(-1/2+1) = \\frac{1}{4}$. Final answer: $\\frac{1}{4}$." }),
  p({ id: "int-34", topicId: "integrals", type: "numeric", difficulty: "hard",
    prompt: "Compute $\\int \\frac{1}{\\sqrt{9-x^2}}\\,dx$",
    answer: "arcsin(x/3)+C",
    explanation: "Step 1: This matches $\\int\\frac{dx}{\\sqrt{a^2-x^2}} = \\arcsin(x/a)+C$. Step 2: Here $a=3$. Final answer: $\\arcsin(x/3)+C$." }),
  p({ id: "int-35", topicId: "integrals", type: "numeric", difficulty: "hard",
    prompt: "Compute $\\int e^x\\sin(x)\\,dx$",
    answer: "e^x*(sin(x)-cos(x))/2+C",
    explanation: "Step 1: By parts twice; the integral repeats. Step 2: Let $I=\\int e^x\\sin x\\,dx$. After two integrations by parts: $I = e^x\\sin x - e^x\\cos x - I$. Step 3: $2I = e^x(\\sin x - \\cos x)$. Step 4: $I = \\frac{e^x(\\sin x - \\cos x)}{2}+C$. Final answer: $\\frac{e^x(\\sin x-\\cos x)}{2}+C$." }),
  p({ id: "int-36", topicId: "integrals", type: "numeric", difficulty: "hard",
    prompt: "Evaluate $\\int_0^{\\pi/4} \\tan^2(x)\\,dx$",
    answer: "1-pi/4",
    explanation: "Step 1: Use $\\tan^2 x = \\sec^2 x - 1$. Step 2: $\\int_0^{\\pi/4}(\\sec^2 x - 1)dx = [\\tan x - x]_0^{\\pi/4}$. Step 3: $(1-\\pi/4)-(0) = 1-\\pi/4$. Final answer: $1-\\frac{\\pi}{4}$." }),
  p({ id: "int-37", topicId: "integrals", type: "numeric", difficulty: "hard",
    prompt: "Compute $\\int \\frac{x^2}{x^2+1}\\,dx$",
    answer: "x-arctan(x)+C",
    explanation: "Step 1: Rewrite: $\\frac{x^2}{x^2+1} = 1 - \\frac{1}{x^2+1}$. Step 2: $\\int\\left(1 - \\frac{1}{x^2+1}\\right)dx = x - \\arctan(x) + C$. Final answer: $x - \\arctan(x) + C$." }),
  p({ id: "int-38", topicId: "integrals", type: "numeric", difficulty: "hard",
    prompt: "Compute $\\int \\frac{\\ln(x)}{x}\\,dx$",
    answer: "(ln(x))^2/2+C",
    explanation: "Step 1: Let $u=\\ln x$, $du = 1/x\\,dx$. Step 2: $\\int u\\,du = \\frac{u^2}{2}+C = \\frac{(\\ln x)^2}{2}+C$. Final answer: $\\frac{(\\ln x)^2}{2}+C$." }),
  p({ id: "int-39", topicId: "integrals", type: "numeric", difficulty: "hard",
    prompt: "Evaluate $\\int_0^{\\ln 2} xe^{-x}\\,dx$",
    answer: "1-3/(2*e^(ln(2)))",
    explanation: "Step 1: By parts: $u=x$, $dv=e^{-x}dx$. Step 2: $-xe^{-x}+\\int e^{-x}dx = -xe^{-x}-e^{-x}$. Step 3: Evaluate from 0 to $\\ln 2$: $(-\\ln 2 \\cdot 1/2 - 1/2) - (0-1) = -\\frac{\\ln 2}{2}-\\frac{1}{2}+1 = \\frac{1}{2}-\\frac{\\ln 2}{2}$. Final answer: $\\frac{1-\\ln 2}{2}$." }),
  p({ id: "int-40", topicId: "integrals", type: "numeric", difficulty: "hard",
    prompt: "Compute $\\int \\frac{1}{x(x+1)}\\,dx$",
    answer: "ln|x|-ln|x+1|+C",
    explanation: "Step 1: Partial fractions: $\\frac{1}{x(x+1)} = \\frac{1}{x} - \\frac{1}{x+1}$. Step 2: $\\ln|x| - \\ln|x+1| + C = \\ln\\left|\\frac{x}{x+1}\\right| + C$. Final answer: $\\ln|x| - \\ln|x+1| + C$." }),
];

// ============================================================================
// SERIES & SEQUENCES (40 problems)
// ============================================================================
const seriesProblems: Problem[] = [
  // --- Easy (15) ---
  p({ id: "series-1", topicId: "series", type: "mcq", difficulty: "easy",
    prompt: "Does the geometric series $\\sum_{n=0}^{\\infty} \\left(\\frac{1}{2}\\right)^n$ converge or diverge?",
    answer: "Converges", choices: ["Converges", "Diverges"],
    explanation: "Step 1: Geometric series with $r = 1/2$. Step 2: Since $|r| = 1/2 < 1$, it converges. Final answer: Converges." }),
  p({ id: "series-2", topicId: "series", type: "numeric", difficulty: "easy",
    prompt: "Find the sum: $\\sum_{n=0}^{\\infty} \\left(\\frac{1}{3}\\right)^n$",
    answer: "3/2",
    explanation: "Step 1: Sum $= \\frac{a}{1-r} = \\frac{1}{1-1/3} = \\frac{1}{2/3} = \\frac{3}{2}$. Final answer: $\\frac{3}{2}$." }),
  p({ id: "series-3", topicId: "series", type: "mcq", difficulty: "easy",
    prompt: "Does $\\sum_{n=1}^{\\infty} \\frac{1}{n}$ converge?",
    answer: "Diverges", choices: ["Converges", "Diverges"],
    explanation: "Step 1: This is the harmonic series. Step 2: The harmonic series diverges (famous result). Final answer: Diverges." }),
  p({ id: "series-4", topicId: "series", type: "numeric", difficulty: "easy",
    prompt: "Find the sum: $\\sum_{n=0}^{\\infty} \\left(\\frac{1}{4}\\right)^n$",
    answer: "4/3",
    explanation: "Step 1: $\\frac{1}{1-1/4} = \\frac{4}{3}$. Final answer: $\\frac{4}{3}$." }),
  p({ id: "series-5", topicId: "series", type: "mcq", difficulty: "easy",
    prompt: "Does $\\sum_{n=1}^{\\infty} \\frac{1}{n^2}$ converge?",
    answer: "Converges", choices: ["Converges", "Diverges"],
    explanation: "Step 1: This is a $p$-series with $p=2>1$. Step 2: $p$-series converges when $p>1$. Final answer: Converges." }),
  p({ id: "series-6", topicId: "series", type: "numeric", difficulty: "easy",
    prompt: "Find the sum: $\\sum_{n=0}^{\\infty} 3 \\cdot \\left(\\frac{1}{2}\\right)^n$",
    answer: "6",
    explanation: "Step 1: $\\frac{3}{1-1/2} = \\frac{3}{1/2} = 6$. Final answer: $6$." }),
  p({ id: "series-7", topicId: "series", type: "mcq", difficulty: "easy",
    prompt: "Does $\\sum_{n=0}^{\\infty} 2^n$ converge?",
    answer: "Diverges", choices: ["Converges", "Diverges"],
    explanation: "Step 1: Geometric series with $r=2$. Step 2: $|r|=2>1$, so it diverges. Final answer: Diverges." }),
  p({ id: "series-8", topicId: "series", type: "numeric", difficulty: "easy",
    prompt: "What is the 5th term of $a_n = \\frac{n}{n+1}$?",
    answer: "5/6",
    explanation: "Step 1: $a_5 = \\frac{5}{5+1} = \\frac{5}{6}$. Final answer: $\\frac{5}{6}$." }),
  p({ id: "series-9", topicId: "series", type: "mcq", difficulty: "easy",
    prompt: "Does the sequence $a_n = \\frac{1}{n}$ converge?",
    answer: "Converges to 0", choices: ["Converges to 0", "Converges to 1", "Diverges"],
    explanation: "Step 1: As $n\\to\\infty$, $1/n \\to 0$. Final answer: Converges to 0." }),
  p({ id: "series-10", topicId: "series", type: "numeric", difficulty: "easy",
    prompt: "Find $\\sum_{n=1}^{4} n^2$",
    answer: "30",
    explanation: "Step 1: $1+4+9+16 = 30$. Final answer: $30$." }),
  p({ id: "series-11", topicId: "series", type: "numeric", difficulty: "easy",
    prompt: "Find the sum: $\\sum_{n=0}^{\\infty} \\left(-\\frac{1}{2}\\right)^n$",
    answer: "2/3",
    explanation: "Step 1: Geometric with $r=-1/2$, $|r|<1$. Step 2: $\\frac{1}{1-(-1/2)} = \\frac{1}{3/2} = \\frac{2}{3}$. Final answer: $\\frac{2}{3}$." }),
  p({ id: "series-12", topicId: "series", type: "mcq", difficulty: "easy",
    prompt: "Does $\\sum_{n=1}^{\\infty} \\frac{1}{n^3}$ converge?",
    answer: "Converges", choices: ["Converges", "Diverges"],
    explanation: "Step 1: $p$-series with $p=3>1$. Converges. Final answer: Converges." }),
  p({ id: "series-13", topicId: "series", type: "numeric", difficulty: "easy",
    prompt: "What does the sequence $a_n = \\frac{3n+1}{n}$ converge to?",
    answer: "3",
    explanation: "Step 1: $\\frac{3n+1}{n} = 3 + \\frac{1}{n} \\to 3$ as $n\\to\\infty$. Final answer: $3$." }),
  p({ id: "series-14", topicId: "series", type: "numeric", difficulty: "easy",
    prompt: "Find $\\sum_{k=1}^{5} k$",
    answer: "15",
    explanation: "Step 1: $1+2+3+4+5 = 15$. Final answer: $15$." }),
  p({ id: "series-15", topicId: "series", type: "mcq", difficulty: "easy",
    prompt: "Does $\\sum_{n=1}^{\\infty}\\frac{1}{\\sqrt{n}}$ converge?",
    answer: "Diverges", choices: ["Converges", "Diverges"],
    explanation: "Step 1: $p$-series with $p=1/2<1$. Step 2: Diverges. Final answer: Diverges." }),
  // --- Medium (15) ---
  p({ id: "series-16", topicId: "series", type: "mcq", difficulty: "medium",
    prompt: "Use the ratio test on $\\sum \\frac{n!}{3^n}$. Does it converge?",
    answer: "Diverges", choices: ["Converges", "Diverges"],
    explanation: "Step 1: $\\frac{a_{n+1}}{a_n} = \\frac{(n+1)!}{3^{n+1}} \\cdot \\frac{3^n}{n!} = \\frac{n+1}{3}$. Step 2: $\\lim_{n\\to\\infty}\\frac{n+1}{3} = \\infty > 1$. Step 3: By ratio test, diverges. Final answer: Diverges." }),
  p({ id: "series-17", topicId: "series", type: "mcq", difficulty: "medium",
    prompt: "Use the ratio test on $\\sum \\frac{2^n}{n!}$. Does it converge?",
    answer: "Converges", choices: ["Converges", "Diverges"],
    explanation: "Step 1: $\\frac{a_{n+1}}{a_n} = \\frac{2}{n+1} \\to 0 < 1$. Step 2: By ratio test, converges. Final answer: Converges." }),
  p({ id: "series-18", topicId: "series", type: "numeric", difficulty: "medium",
    prompt: "Find the radius of convergence of $\\sum \\frac{x^n}{n}$.",
    answer: "1",
    explanation: "Step 1: Ratio test: $\\frac{|x|n}{n+1} \\to |x|$. Step 2: Converges when $|x|<1$. Step 3: Radius of convergence $R=1$. Final answer: $R=1$." }),
  p({ id: "series-19", topicId: "series", type: "numeric", difficulty: "medium",
    prompt: "Find the 3rd-degree Taylor polynomial of $e^x$ centered at $x=0$.",
    answer: "1+x+x^2/2+x^3/6",
    explanation: "Step 1: $e^x = \\sum\\frac{x^n}{n!}$. Step 2: First 4 terms: $1 + x + \\frac{x^2}{2} + \\frac{x^3}{6}$. Final answer: $1+x+\\frac{x^2}{2}+\\frac{x^3}{6}$." }),
  p({ id: "series-20", topicId: "series", type: "mcq", difficulty: "medium",
    prompt: "Does $\\sum_{n=1}^{\\infty} \\frac{(-1)^n}{n}$ converge?",
    answer: "Converges (conditionally)", choices: ["Converges (conditionally)", "Converges absolutely", "Diverges"],
    explanation: "Step 1: Alternating series test: $1/n$ is decreasing and $\\to 0$. Converges. Step 2: But $\\sum 1/n$ diverges, so not absolute. Final answer: Converges (conditionally)." }),
  p({ id: "series-21", topicId: "series", type: "numeric", difficulty: "medium",
    prompt: "Find the Maclaurin series (first 3 nonzero terms) for $\\sin(x)$.",
    answer: "x-x^3/6+x^5/120",
    explanation: "Step 1: $\\sin(x) = x - \\frac{x^3}{3!} + \\frac{x^5}{5!} - \\cdots$. Step 2: $= x - \\frac{x^3}{6} + \\frac{x^5}{120}$. Final answer: $x - \\frac{x^3}{6} + \\frac{x^5}{120}$." }),
  p({ id: "series-22", topicId: "series", type: "numeric", difficulty: "medium",
    prompt: "Find the interval of convergence of $\\sum \\frac{x^n}{2^n}$.",
    answer: "(-2,2)",
    explanation: "Step 1: Geometric with ratio $x/2$. Step 2: Converges when $|x/2|<1$, i.e., $|x|<2$. Step 3: At $x=\\pm 2$: diverges. Final answer: $(-2,2)$." }),
  p({ id: "series-23", topicId: "series", type: "mcq", difficulty: "medium",
    prompt: "Does $\\sum_{n=1}^{\\infty} \\frac{n}{2^n}$ converge?",
    answer: "Converges", choices: ["Converges", "Diverges"],
    explanation: "Step 1: Ratio test: $\\frac{(n+1)/2^{n+1}}{n/2^n} = \\frac{n+1}{2n} \\to \\frac{1}{2} < 1$. Step 2: Converges. Final answer: Converges." }),
  p({ id: "series-24", topicId: "series", type: "numeric", difficulty: "medium",
    prompt: "Find the sum of $\\sum_{n=1}^{\\infty} \\frac{1}{n(n+1)}$ (telescoping).",
    answer: "1",
    explanation: "Step 1: Partial fractions: $\\frac{1}{n(n+1)} = \\frac{1}{n}-\\frac{1}{n+1}$. Step 2: Telescopes to $(1-\\frac{1}{2})+(\\frac{1}{2}-\\frac{1}{3})+\\cdots = 1$. Final answer: $1$." }),
  p({ id: "series-25", topicId: "series", type: "numeric", difficulty: "medium",
    prompt: "Find the radius of convergence of $\\sum \\frac{n!x^n}{n^n}$.",
    answer: "e",
    explanation: "Step 1: Ratio test: $\\frac{(n+1)!|x|^{n+1}}{(n+1)^{n+1}} \\cdot \\frac{n^n}{n!|x|^n} = |x|\\frac{n^n}{(n+1)^n}$. Step 2: $\\frac{n^n}{(n+1)^n} = \\frac{1}{(1+1/n)^n} \\to \\frac{1}{e}$. Step 3: $R = e$. Final answer: $R = e$." }),
  p({ id: "series-26", topicId: "series", type: "mcq", difficulty: "medium",
    prompt: "Does $\\sum_{n=2}^{\\infty}\\frac{1}{n\\ln(n)}$ converge?",
    answer: "Diverges", choices: ["Converges", "Diverges"],
    explanation: "Step 1: Integral test: $\\int_2^{\\infty}\\frac{dx}{x\\ln x} = \\ln(\\ln x)\\Big|_2^\\infty = \\infty$. Step 2: Diverges. Final answer: Diverges." }),
  p({ id: "series-27", topicId: "series", type: "numeric", difficulty: "medium",
    prompt: "Write $\\frac{1}{1-x}$ as a power series and give the radius of convergence.",
    answer: "1",
    explanation: "Step 1: $\\frac{1}{1-x} = \\sum_{n=0}^{\\infty} x^n$ for $|x|<1$. Step 2: Radius $R=1$. Final answer: $R=1$." }),
  p({ id: "series-28", topicId: "series", type: "numeric", difficulty: "medium",
    prompt: "Find the sum $\\sum_{n=0}^{\\infty} \\frac{(-1)^n}{2^n}$.",
    answer: "2/3",
    explanation: "Step 1: Geometric with $r=-1/2$. Step 2: $\\frac{1}{1+1/2} = \\frac{2}{3}$. Final answer: $\\frac{2}{3}$." }),
  p({ id: "series-29", topicId: "series", type: "mcq", difficulty: "medium",
    prompt: "Does $\\sum_{n=1}^{\\infty} \\frac{(-1)^n}{\\sqrt{n}}$ converge?",
    answer: "Converges (conditionally)", choices: ["Converges (conditionally)", "Converges absolutely", "Diverges"],
    explanation: "Step 1: Alternating series: $1/\\sqrt{n}$ decreasing to 0. Converges. Step 2: But $\\sum 1/\\sqrt{n}$ diverges ($p=1/2$). Not absolute. Final answer: Converges (conditionally)." }),
  p({ id: "series-30", topicId: "series", type: "numeric", difficulty: "medium",
    prompt: "The first 3 terms of the Taylor series for $\\cos(x)$ at $x=0$ are:",
    answer: "1-x^2/2+x^4/24",
    explanation: "Step 1: $\\cos x = 1 - \\frac{x^2}{2!} + \\frac{x^4}{4!} - \\cdots$. Step 2: $= 1 - \\frac{x^2}{2} + \\frac{x^4}{24}$. Final answer: $1 - \\frac{x^2}{2} + \\frac{x^4}{24}$." }),
  // --- Hard (10) ---
  p({ id: "series-31", topicId: "series", type: "numeric", difficulty: "hard",
    prompt: "Find the sum $\\sum_{n=0}^{\\infty} \\frac{(-1)^n}{(2n+1)!}$ (hint: think trig).",
    answer: "sin(1)",
    explanation: "Step 1: This is the Maclaurin series for $\\sin(x)$ evaluated at $x=1$. Step 2: $\\sin(1) = \\sum_{n=0}^{\\infty}\\frac{(-1)^n}{(2n+1)!}$. Final answer: $\\sin(1)$." }),
  p({ id: "series-32", topicId: "series", type: "numeric", difficulty: "hard",
    prompt: "Find the radius of convergence of $\\sum_{n=1}^{\\infty} \\frac{n^n x^n}{n!}$.",
    answer: "1/e",
    explanation: "Step 1: Ratio test gives limit $|x| \\cdot e$. Step 2: Converges when $|x|e < 1$, i.e., $|x| < 1/e$. Step 3: $R = 1/e$. Final answer: $R = 1/e$." }),
  p({ id: "series-33", topicId: "series", type: "numeric", difficulty: "hard",
    prompt: "Find $\\sum_{n=1}^{\\infty} \\frac{1}{n \\cdot 2^n}$.",
    answer: "ln(2)",
    explanation: "Step 1: Recall $-\\ln(1-x) = \\sum_{n=1}^{\\infty}\\frac{x^n}{n}$ for $|x|<1$. Step 2: At $x=1/2$: $-\\ln(1/2) = \\ln(2)$. Final answer: $\\ln(2)$." }),
  p({ id: "series-34", topicId: "series", type: "mcq", difficulty: "hard",
    prompt: "Does $\\sum_{n=1}^{\\infty} \\frac{(-1)^n n}{n+1}$ converge?",
    answer: "Diverges", choices: ["Converges", "Diverges"],
    explanation: "Step 1: $\\lim_{n\\to\\infty}\\frac{n}{n+1} = 1 \\neq 0$. Step 2: The $n$-th term doesn't approach 0. Step 3: By the divergence test, diverges. Final answer: Diverges." }),
  p({ id: "series-35", topicId: "series", type: "numeric", difficulty: "hard",
    prompt: "Find the Taylor series of $\\frac{1}{(1-x)^2}$ (first 4 terms).",
    answer: "1+2*x+3*x^2+4*x^3",
    explanation: "Step 1: $\\frac{d}{dx}\\frac{1}{1-x} = \\frac{1}{(1-x)^2}$. Step 2: $\\frac{d}{dx}\\sum x^n = \\sum nx^{n-1} = 1+2x+3x^2+4x^3+\\cdots$. Final answer: $1+2x+3x^2+4x^3$." }),
  p({ id: "series-36", topicId: "series", type: "numeric", difficulty: "hard",
    prompt: "Find the coefficient of $x^3$ in the Taylor series of $e^x\\sin(x)$ around $x=0$.",
    answer: "-1/3",
    explanation: "Step 1: $e^x = 1+x+x^2/2+x^3/6+\\cdots$. $\\sin x = x-x^3/6+\\cdots$. Step 2: Product up to $x^3$: $x + x^2 + (1/2-1/6)x^3 = x+x^2+x^3/3$. Wait, let me recalculate carefully. Step 3: Coefficient of $x^3$: from $1 \\cdot(-x^3/6) + x \\cdot 0 + (x^2/2) \\cdot x = -1/6 + 0 + 1/2 \\cdot 0$... Actually $e^x\\sin x = x + x^2 + x^3/3 - x^5/30+\\cdots$. The coefficient of $x^3$ is $-1/3$. Final answer: $-\\frac{1}{3}$." }),
  p({ id: "series-37", topicId: "series", type: "mcq", difficulty: "hard",
    prompt: "Does $\\sum_{n=1}^{\\infty} \\frac{\\sin(n)}{n^2}$ converge absolutely?",
    answer: "Yes", choices: ["Yes", "No"],
    explanation: "Step 1: $|\\sin(n)| \\le 1$, so $\\left|\\frac{\\sin(n)}{n^2}\\right| \\le \\frac{1}{n^2}$. Step 2: $\\sum 1/n^2$ converges. Step 3: By comparison, converges absolutely. Final answer: Yes." }),
  p({ id: "series-38", topicId: "series", type: "numeric", difficulty: "hard",
    prompt: "Find $\\sum_{n=0}^{\\infty} \\frac{1}{n!}$ (exact value).",
    answer: "e",
    explanation: "Step 1: This is the Taylor series for $e^x$ at $x=1$. Step 2: $e^1 = e$. Final answer: $e$." }),
  p({ id: "series-39", topicId: "series", type: "numeric", difficulty: "hard",
    prompt: "Find the interval of convergence of $\\sum_{n=1}^{\\infty} \\frac{(x-1)^n}{n}$.",
    answer: "[0,2)",
    explanation: "Step 1: Center $c=1$, radius $R=1$ (ratio test). Step 2: At $x=0$: $\\sum(-1)^n/n$ converges (alternating). Step 3: At $x=2$: $\\sum 1/n$ diverges. Final answer: $[0,2)$." }),
  p({ id: "series-40", topicId: "series", type: "numeric", difficulty: "hard",
    prompt: "Find the Maclaurin series for $\\ln(1+x)$ (first 4 terms).",
    answer: "x-x^2/2+x^3/3-x^4/4",
    explanation: "Step 1: $\\ln(1+x) = \\sum_{n=1}^{\\infty}\\frac{(-1)^{n+1}x^n}{n}$. Step 2: First 4 terms: $x - \\frac{x^2}{2} + \\frac{x^3}{3} - \\frac{x^4}{4}$. Final answer: $x - \\frac{x^2}{2} + \\frac{x^3}{3} - \\frac{x^4}{4}$." }),
];

// ============================================================================
// DIFFERENTIAL EQUATIONS (40 problems)
// ============================================================================
const differentialEquationProblems: Problem[] = [
  // --- Easy (15) ---
  p({ id: "de-1", topicId: "differential-equations", type: "numeric", difficulty: "easy",
    prompt: "Solve $\\frac{dy}{dx} = 3$",
    answer: "y=3*x+C",
    explanation: "Step 1: Integrate both sides: $y = \\int 3\\,dx = 3x + C$. Final answer: $y = 3x + C$." }),
  p({ id: "de-2", topicId: "differential-equations", type: "numeric", difficulty: "easy",
    prompt: "Solve $\\frac{dy}{dx} = 2x$",
    answer: "y=x^2+C",
    explanation: "Step 1: $y = \\int 2x\\,dx = x^2 + C$. Final answer: $y = x^2 + C$." }),
  p({ id: "de-3", topicId: "differential-equations", type: "numeric", difficulty: "easy",
    prompt: "Solve $\\frac{dy}{dx} = e^x$",
    answer: "y=e^x+C",
    explanation: "Step 1: $y = \\int e^x\\,dx = e^x + C$. Final answer: $y = e^x + C$." }),
  p({ id: "de-4", topicId: "differential-equations", type: "numeric", difficulty: "easy",
    prompt: "Solve $\\frac{dy}{dx} = 2y$ (general solution)",
    answer: "y=Ce^(2x)",
    explanation: "Step 1: Separate: $\\frac{dy}{y} = 2\\,dx$. Step 2: $\\ln|y| = 2x + C_1$. Step 3: $y = Ce^{2x}$. Final answer: $y = Ce^{2x}$." }),
  p({ id: "de-5", topicId: "differential-equations", type: "numeric", difficulty: "easy",
    prompt: "Solve $\\frac{dy}{dx} = -y$ (general solution)",
    answer: "y=Ce^(-x)",
    explanation: "Step 1: Separate: $\\frac{dy}{y} = -dx$. Step 2: $\\ln|y| = -x + C_1$. Step 3: $y = Ce^{-x}$. Final answer: $y = Ce^{-x}$." }),
  p({ id: "de-6", topicId: "differential-equations", type: "numeric", difficulty: "easy",
    prompt: "Solve $\\frac{dy}{dx} = x^2$ with $y(0) = 1$.",
    answer: "y=x^3/3+1",
    explanation: "Step 1: $y = x^3/3 + C$. Step 2: $y(0) = 1 \\Rightarrow C = 1$. Final answer: $y = \\frac{x^3}{3} + 1$." }),
  p({ id: "de-7", topicId: "differential-equations", type: "numeric", difficulty: "easy",
    prompt: "Solve $\\frac{dy}{dx} = \\cos(x)$",
    answer: "y=sin(x)+C",
    explanation: "Step 1: $y = \\int\\cos x\\,dx = \\sin x + C$. Final answer: $y = \\sin(x) + C$." }),
  p({ id: "de-8", topicId: "differential-equations", type: "numeric", difficulty: "easy",
    prompt: "If $y' = 5y$ and $y(0) = 2$, find $y(t)$.",
    answer: "y=2*e^(5*t)",
    explanation: "Step 1: General solution: $y = Ce^{5t}$. Step 2: $y(0) = C = 2$. Final answer: $y = 2e^{5t}$." }),
  p({ id: "de-9", topicId: "differential-equations", type: "numeric", difficulty: "easy",
    prompt: "Solve $\\frac{dy}{dx} = 3x^2 + 1$",
    answer: "y=x^3+x+C",
    explanation: "Step 1: $y = x^3 + x + C$. Final answer: $y = x^3 + x + C$." }),
  p({ id: "de-10", topicId: "differential-equations", type: "mcq", difficulty: "easy",
    prompt: "What type of DE is $\\frac{dy}{dx} = xy$?",
    answer: "Separable", choices: ["Separable", "Linear (non-separable)", "Exact", "Bernoulli"],
    explanation: "Step 1: We can write $\\frac{dy}{y} = x\\,dx$. Step 2: Variables separate. Final answer: Separable." }),
  p({ id: "de-11", topicId: "differential-equations", type: "numeric", difficulty: "easy",
    prompt: "Solve $\\frac{dy}{dx} = \\frac{1}{x}$ for $x > 0$.",
    answer: "y=ln(x)+C",
    explanation: "Step 1: $y = \\int\\frac{1}{x}dx = \\ln(x) + C$. Final answer: $y = \\ln(x) + C$." }),
  p({ id: "de-12", topicId: "differential-equations", type: "numeric", difficulty: "easy",
    prompt: "Solve $y' = -3y$ with $y(0)=10$.",
    answer: "y=10*e^(-3*t)",
    explanation: "Step 1: General: $y = Ce^{-3t}$. Step 2: $C = 10$. Final answer: $y = 10e^{-3t}$." }),
  p({ id: "de-13", topicId: "differential-equations", type: "numeric", difficulty: "easy",
    prompt: "Solve $\\frac{dy}{dx} = 6x^2 - 2x$",
    answer: "y=2*x^3-x^2+C",
    explanation: "Step 1: $y = 2x^3 - x^2 + C$. Final answer: $y = 2x^3 - x^2 + C$." }),
  p({ id: "de-14", topicId: "differential-equations", type: "mcq", difficulty: "easy",
    prompt: "Is $y = e^{3x}$ a solution to $y' = 3y$?",
    answer: "Yes", choices: ["Yes", "No"],
    explanation: "Step 1: $y' = 3e^{3x}$ and $3y = 3e^{3x}$. Step 2: They're equal. Final answer: Yes." }),
  p({ id: "de-15", topicId: "differential-equations", type: "numeric", difficulty: "easy",
    prompt: "A population doubles every hour. If $P(0)=100$, find $P(t)$.",
    answer: "P=100*2^t",
    explanation: "Step 1: Exponential growth with doubling time 1 hour. Step 2: $P(t) = 100 \\cdot 2^t$. Final answer: $P = 100 \\cdot 2^t$." }),
  // --- Medium (15) ---
  p({ id: "de-16", topicId: "differential-equations", type: "numeric", difficulty: "medium",
    prompt: "Solve $\\frac{dy}{dx} = xy$ (general solution).",
    answer: "y=Ce^(x^2/2)",
    explanation: "Step 1: Separate: $\\frac{dy}{y} = x\\,dx$. Step 2: $\\ln|y| = \\frac{x^2}{2} + C_1$. Step 3: $y = Ce^{x^2/2}$. Final answer: $y = Ce^{x^2/2}$." }),
  p({ id: "de-17", topicId: "differential-equations", type: "numeric", difficulty: "medium",
    prompt: "Solve $\\frac{dy}{dx} + y = e^x$.",
    answer: "y=e^x/2+Ce^(-x)",
    explanation: "Step 1: Integrating factor: $\\mu = e^{\\int 1\\,dx} = e^x$. Step 2: $(e^x y)' = e^{2x}$. Step 3: $e^x y = \\frac{e^{2x}}{2} + C$. Step 4: $y = \\frac{e^x}{2} + Ce^{-x}$. Final answer: $y = \\frac{e^x}{2} + Ce^{-x}$." }),
  p({ id: "de-18", topicId: "differential-equations", type: "numeric", difficulty: "medium",
    prompt: "Solve $\\frac{dy}{dx} = \\frac{y}{x}$ for $x>0$.",
    answer: "y=Cx",
    explanation: "Step 1: Separate: $\\frac{dy}{y} = \\frac{dx}{x}$. Step 2: $\\ln|y| = \\ln|x| + C_1$. Step 3: $y = Cx$. Final answer: $y = Cx$." }),
  p({ id: "de-19", topicId: "differential-equations", type: "numeric", difficulty: "medium",
    prompt: "Solve $y' + 2y = 6$ (general solution).",
    answer: "y=3+Ce^(-2x)",
    explanation: "Step 1: Integrating factor $\\mu = e^{2x}$. Step 2: $(e^{2x}y)' = 6e^{2x}$. Step 3: $e^{2x}y = 3e^{2x}+C$. Step 4: $y = 3 + Ce^{-2x}$. Final answer: $y = 3 + Ce^{-2x}$." }),
  p({ id: "de-20", topicId: "differential-equations", type: "numeric", difficulty: "medium",
    prompt: "Solve $\\frac{dy}{dx} = y^2$ with $y(0) = 1$.",
    answer: "y=1/(1-x)",
    explanation: "Step 1: Separate: $y^{-2}dy = dx$. Step 2: $-1/y = x + C$. Step 3: $y(0)=1 \\Rightarrow C=-1$. Step 4: $y = \\frac{1}{1-x}$. Final answer: $y = \\frac{1}{1-x}$." }),
  p({ id: "de-21", topicId: "differential-equations", type: "numeric", difficulty: "medium",
    prompt: "A substance decays at rate proportional to amount: $N'=-0.05N$, $N(0)=200$. Find the half-life.",
    answer: "ln(2)/0.05",
    explanation: "Step 1: $N = 200e^{-0.05t}$. Step 2: Half-life when $N = 100$: $e^{-0.05t} = 1/2$. Step 3: $t = \\frac{\\ln 2}{0.05}$. Final answer: $\\frac{\\ln 2}{0.05} \\approx 13.86$." }),
  p({ id: "de-22", topicId: "differential-equations", type: "numeric", difficulty: "medium",
    prompt: "Solve $\\frac{dy}{dx} = \\frac{x}{y}$ with $y > 0$ (general solution).",
    answer: "y=sqrt(x^2+C)",
    explanation: "Step 1: $y\\,dy = x\\,dx$. Step 2: $\\frac{y^2}{2} = \\frac{x^2}{2} + C_1$. Step 3: $y^2 = x^2 + C$, so $y = \\sqrt{x^2+C}$. Final answer: $y = \\sqrt{x^2+C}$." }),
  p({ id: "de-23", topicId: "differential-equations", type: "numeric", difficulty: "medium",
    prompt: "Solve $y' - 3y = 0$.",
    answer: "y=Ce^(3x)",
    explanation: "Step 1: This is $y'=3y$. Step 2: $y = Ce^{3x}$. Final answer: $y = Ce^{3x}$." }),
  p({ id: "de-24", topicId: "differential-equations", type: "numeric", difficulty: "medium",
    prompt: "Solve $\\frac{dy}{dx} + \\frac{y}{x} = x$ for $x > 0$.",
    answer: "y=x^2/3+C/x",
    explanation: "Step 1: Integrating factor $\\mu = e^{\\int 1/x\\,dx} = x$. Step 2: $(xy)' = x^2$. Step 3: $xy = x^3/3 + C$. Step 4: $y = x^2/3 + C/x$. Final answer: $y = \\frac{x^2}{3} + \\frac{C}{x}$." }),
  p({ id: "de-25", topicId: "differential-equations", type: "numeric", difficulty: "medium",
    prompt: "Solve $\\frac{dy}{dx} = e^{x+y}$ (hint: $e^{x+y}=e^x e^y$).",
    answer: "y=-ln(C-e^x)",
    explanation: "Step 1: $e^{-y}dy = e^x dx$. Step 2: $-e^{-y} = e^x + C_1$. Step 3: $e^{-y} = C - e^x$. Step 4: $y = -\\ln(C-e^x)$. Final answer: $y = -\\ln(C-e^x)$." }),
  p({ id: "de-26", topicId: "differential-equations", type: "mcq", difficulty: "medium",
    prompt: "Newton's law of cooling says $T' = -k(T-T_s)$ where $T_s$ is ambient temp. What type of solution does this have?",
    answer: "Exponential decay toward $T_s$", choices: ["Exponential decay toward $T_s$", "Exponential growth", "Oscillating", "Linear"],
    explanation: "Step 1: Solution is $T = T_s + (T_0 - T_s)e^{-kt}$. Step 2: Temperature exponentially approaches ambient. Final answer: Exponential decay toward $T_s$." }),
  p({ id: "de-27", topicId: "differential-equations", type: "numeric", difficulty: "medium",
    prompt: "Solve $y'' = 0$ (general solution).",
    answer: "y=Ax+B",
    explanation: "Step 1: Integrate once: $y' = A$. Step 2: Integrate again: $y = Ax + B$. Final answer: $y = Ax + B$." }),
  p({ id: "de-28", topicId: "differential-equations", type: "numeric", difficulty: "medium",
    prompt: "Solve $y'' + y = 0$ (general solution).",
    answer: "y=Acos(x)+Bsin(x)",
    explanation: "Step 1: Characteristic equation: $r^2+1=0 \\Rightarrow r=\\pm i$. Step 2: General solution with complex roots: $y = A\\cos(x) + B\\sin(x)$. Final answer: $y = A\\cos(x) + B\\sin(x)$." }),
  p({ id: "de-29", topicId: "differential-equations", type: "numeric", difficulty: "medium",
    prompt: "Solve $y'' - y = 0$.",
    answer: "y=Ae^x+Be^(-x)",
    explanation: "Step 1: $r^2-1=0 \\Rightarrow r=\\pm 1$. Step 2: $y = Ae^x + Be^{-x}$. Final answer: $y = Ae^x + Be^{-x}$." }),
  p({ id: "de-30", topicId: "differential-equations", type: "numeric", difficulty: "medium",
    prompt: "Solve $y'' - 4y' + 4y = 0$.",
    answer: "y=(A+Bx)e^(2x)",
    explanation: "Step 1: $r^2-4r+4=(r-2)^2=0$, repeated root $r=2$. Step 2: $y = (A+Bx)e^{2x}$. Final answer: $y = (A+Bx)e^{2x}$." }),
  // --- Hard (10) ---
  p({ id: "de-31", topicId: "differential-equations", type: "numeric", difficulty: "hard",
    prompt: "Solve $y'' + 4y = 0$ with $y(0)=1$ and $y'(0)=0$.",
    answer: "y=cos(2x)",
    explanation: "Step 1: $r^2+4=0 \\Rightarrow r=\\pm 2i$. Step 2: $y = A\\cos(2x)+B\\sin(2x)$. Step 3: $y(0)=A=1$. $y'(0)=2B=0 \\Rightarrow B=0$. Final answer: $y = \\cos(2x)$." }),
  p({ id: "de-32", topicId: "differential-equations", type: "numeric", difficulty: "hard",
    prompt: "Solve $y' = \\frac{x^2+y^2}{xy}$ (hint: let $v = y/x$).",
    answer: "y^2=x^2(2*ln|x|+C)",
    explanation: "Step 1: Let $v = y/x$, so $y = vx$ and $y' = v + xv'$. Step 2: Substitute: $v + xv' = \\frac{x^2+v^2x^2}{vx^2} = \\frac{1+v^2}{v}$. Step 3: $xv' = \\frac{1}{v}$, so $v\\,dv = \\frac{dx}{x}$. Step 4: $v^2/2 = \\ln|x|+C_1$. Step 5: $y^2/x^2 = 2\\ln|x| + C$, so $y^2 = x^2(2\\ln|x|+C)$. Final answer: $y^2 = x^2(2\\ln|x|+C)$." }),
  p({ id: "de-33", topicId: "differential-equations", type: "numeric", difficulty: "hard",
    prompt: "Solve the Bernoulli equation $y' + y = y^2$.",
    answer: "y=1/(1+Ce^x)",
    explanation: "Step 1: Divide by $y^2$: $y^{-2}y' + y^{-1} = 1$. Step 2: Let $v = y^{-1}$, $v' = -y^{-2}y'$. Step 3: $-v' + v = 1$, or $v' - v = -1$. Step 4: IF $= e^{-x}$: $(e^{-x}v)' = -e^{-x}$. Step 5: $v = 1 + Ce^x$, so $y = \\frac{1}{1+Ce^x}$. Final answer: $y = \\frac{1}{1+Ce^x}$." }),
  p({ id: "de-34", topicId: "differential-equations", type: "numeric", difficulty: "hard",
    prompt: "Solve $y'' - 5y' + 6y = 0$.",
    answer: "y=Ae^(2x)+Be^(3x)",
    explanation: "Step 1: $r^2-5r+6 = (r-2)(r-3) = 0$. Step 2: $r=2,3$. Step 3: $y = Ae^{2x}+Be^{3x}$. Final answer: $y = Ae^{2x}+Be^{3x}$." }),
  p({ id: "de-35", topicId: "differential-equations", type: "numeric", difficulty: "hard",
    prompt: "Solve $y'' + 2y' + 5y = 0$.",
    answer: "y=e^(-x)*(Acos(2x)+Bsin(2x))",
    explanation: "Step 1: $r^2+2r+5=0 \\Rightarrow r = -1 \\pm 2i$. Step 2: $y = e^{-x}(A\\cos 2x + B\\sin 2x)$. Final answer: $y = e^{-x}(A\\cos(2x)+B\\sin(2x))$." }),
  p({ id: "de-36", topicId: "differential-equations", type: "numeric", difficulty: "hard",
    prompt: "Solve the logistic equation $P' = 0.1P(1-P/1000)$ with $P(0) = 100$. What is the carrying capacity?",
    answer: "1000",
    explanation: "Step 1: The logistic equation $P' = rP(1-P/K)$ has carrying capacity $K$. Step 2: Here $K=1000$. The population approaches this as $t\\to\\infty$. Final answer: $1000$." }),
  p({ id: "de-37", topicId: "differential-equations", type: "numeric", difficulty: "hard",
    prompt: "Solve $y'' + y = \\sin(x)$ (find a particular solution).",
    answer: "y_p=-x*cos(x)/2",
    explanation: "Step 1: Since $\\sin(x)$ is a solution of the homogeneous equation, use $y_p = x(A\\cos x + B\\sin x)$. Step 2: Substituting and solving: $A = -1/2$, $B = 0$. Step 3: $y_p = -\\frac{x\\cos(x)}{2}$. Final answer: $y_p = -\\frac{x\\cos(x)}{2}$." }),
  p({ id: "de-38", topicId: "differential-equations", type: "numeric", difficulty: "hard",
    prompt: "Solve $y' = y\\tan(x)$.",
    answer: "y=C*sec(x)",
    explanation: "Step 1: $\\frac{dy}{y} = \\tan(x)\\,dx$. Step 2: $\\ln|y| = -\\ln|\\cos x| + C_1 = \\ln|\\sec x| + C_1$. Step 3: $y = C\\sec(x)$. Final answer: $y = C\\sec(x)$." }),
  p({ id: "de-39", topicId: "differential-equations", type: "numeric", difficulty: "hard",
    prompt: "Find the Wronskian of $y_1 = e^x$ and $y_2 = e^{2x}$.",
    answer: "e^(3x)",
    explanation: "Step 1: $W = \\begin{vmatrix} e^x & e^{2x} \\\\ e^x & 2e^{2x} \\end{vmatrix} = 2e^{3x} - e^{3x} = e^{3x}$. Final answer: $e^{3x}$." }),
  p({ id: "de-40", topicId: "differential-equations", type: "numeric", difficulty: "hard",
    prompt: "Solve $y'' - y' - 6y = 0$ with $y(0) = 0$, $y'(0) = 5$.",
    answer: "y=e^(3x)-e^(-2x)",
    explanation: "Step 1: $r^2-r-6 = (r-3)(r+2) = 0$. Step 2: $y = Ae^{3x} + Be^{-2x}$. Step 3: $y(0)=A+B=0$ and $y'(0)=3A-2B=5$. Step 4: $B=-A$, so $3A+2A=5 \\Rightarrow A=1, B=-1$. Final answer: $y = e^{3x}-e^{-2x}$." }),
];

export const problems: Problem[] = [
  ...limitsProblems,
  ...derivativeProblems,
  ...applicationProblems,
  ...integralProblems,
  ...seriesProblems,
  ...differentialEquationProblems,
];

export const learningPaths: LearningPath[] = [
  {
    id: "calc-foundations",
    title: "Calculus Foundations",
    description: "Build core skills with limits, derivatives, and integrals.",
    level: "intro",
    steps: [
      { topicId: "limits", targetProblems: 20 },
      { topicId: "derivatives", targetProblems: 25 },
      { topicId: "integrals", targetProblems: 25 },
    ],
  },
  {
    id: "calc-applications",
    title: "Real-World Calculus",
    description: "Master applications like optimization and modeling.",
    level: "intermediate",
    steps: [
      { topicId: "applications", targetProblems: 25 },
      { topicId: "differential-equations", targetProblems: 20 },
    ],
  },
  {
    id: "calc-advanced",
    title: "Advanced Topics",
    description: "Dive into series and advanced techniques.",
    level: "advanced",
    steps: [
      { topicId: "series", targetProblems: 25 },
      { topicId: "integrals", targetProblems: 20 },
    ],
  },
];
