export type FlashCard = {
  id: string;
  topicId: string;
  front: string; // Question / rule name
  back: string;  // Formula / explanation (LaTeX)
  category: "rule" | "formula" | "identity" | "technique";
};

export const flashCards: FlashCard[] = [
  // ── Limits ────────────────────────────────────────────────
  { id: "fc-lim-1", topicId: "limits", category: "rule",
    front: "Direct Substitution",
    back: "If $f$ is continuous at $a$, then $\\lim_{x\\to a} f(x) = f(a)$." },
  { id: "fc-lim-2", topicId: "limits", category: "formula",
    front: "$\\lim_{x\\to 0} \\frac{\\sin x}{x}$",
    back: "$= 1$" },
  { id: "fc-lim-3", topicId: "limits", category: "formula",
    front: "$\\lim_{x\\to 0} \\frac{1-\\cos x}{x}$",
    back: "$= 0$" },
  { id: "fc-lim-4", topicId: "limits", category: "formula",
    front: "$\\lim_{x\\to 0} \\frac{e^x - 1}{x}$",
    back: "$= 1$" },
  { id: "fc-lim-5", topicId: "limits", category: "rule",
    front: "L'Hôpital's Rule",
    back: "If $\\lim \\frac{f(x)}{g(x)}$ is $\\frac{0}{0}$ or $\\frac{\\infty}{\\infty}$, then $\\lim \\frac{f(x)}{g(x)} = \\lim \\frac{f'(x)}{g'(x)}$ (if the right side exists)." },
  { id: "fc-lim-6", topicId: "limits", category: "formula",
    front: "$\\lim_{n\\to\\infty}\\left(1+\\frac{a}{n}\\right)^n$",
    back: "$= e^a$" },
  { id: "fc-lim-7", topicId: "limits", category: "rule",
    front: "Squeeze Theorem",
    back: "If $g(x) \\le f(x) \\le h(x)$ and $\\lim g = \\lim h = L$, then $\\lim f = L$." },

  // ── Derivatives ───────────────────────────────────────────
  { id: "fc-der-1", topicId: "derivatives", category: "rule",
    front: "Power Rule",
    back: "$\\frac{d}{dx}(x^n) = nx^{n-1}$" },
  { id: "fc-der-2", topicId: "derivatives", category: "rule",
    front: "Product Rule",
    back: "$(fg)' = f'g + fg'$" },
  { id: "fc-der-3", topicId: "derivatives", category: "rule",
    front: "Quotient Rule",
    back: "$\\left(\\frac{f}{g}\\right)' = \\frac{f'g - fg'}{g^2}$" },
  { id: "fc-der-4", topicId: "derivatives", category: "rule",
    front: "Chain Rule",
    back: "$\\frac{d}{dx}f(g(x)) = f'(g(x))\\cdot g'(x)$" },
  { id: "fc-der-5", topicId: "derivatives", category: "formula",
    front: "$\\frac{d}{dx}(\\sin x)$",
    back: "$= \\cos x$" },
  { id: "fc-der-6", topicId: "derivatives", category: "formula",
    front: "$\\frac{d}{dx}(\\cos x)$",
    back: "$= -\\sin x$" },
  { id: "fc-der-7", topicId: "derivatives", category: "formula",
    front: "$\\frac{d}{dx}(\\tan x)$",
    back: "$= \\sec^2 x$" },
  { id: "fc-der-8", topicId: "derivatives", category: "formula",
    front: "$\\frac{d}{dx}(e^x)$",
    back: "$= e^x$" },
  { id: "fc-der-9", topicId: "derivatives", category: "formula",
    front: "$\\frac{d}{dx}(\\ln x)$",
    back: "$= \\frac{1}{x}$" },
  { id: "fc-der-10", topicId: "derivatives", category: "formula",
    front: "$\\frac{d}{dx}(\\arctan x)$",
    back: "$= \\frac{1}{1+x^2}$" },
  { id: "fc-der-11", topicId: "derivatives", category: "formula",
    front: "$\\frac{d}{dx}(\\arcsin x)$",
    back: "$= \\frac{1}{\\sqrt{1-x^2}}$" },

  // ── Integrals ─────────────────────────────────────────────
  { id: "fc-int-1", topicId: "integrals", category: "formula",
    front: "$\\int x^n\\,dx$",
    back: "$= \\frac{x^{n+1}}{n+1} + C$ (for $n \\neq -1$)" },
  { id: "fc-int-2", topicId: "integrals", category: "formula",
    front: "$\\int \\frac{1}{x}\\,dx$",
    back: "$= \\ln|x| + C$" },
  { id: "fc-int-3", topicId: "integrals", category: "formula",
    front: "$\\int e^x\\,dx$",
    back: "$= e^x + C$" },
  { id: "fc-int-4", topicId: "integrals", category: "formula",
    front: "$\\int \\sin x\\,dx$",
    back: "$= -\\cos x + C$" },
  { id: "fc-int-5", topicId: "integrals", category: "formula",
    front: "$\\int \\cos x\\,dx$",
    back: "$= \\sin x + C$" },
  { id: "fc-int-6", topicId: "integrals", category: "formula",
    front: "$\\int \\sec^2 x\\,dx$",
    back: "$= \\tan x + C$" },
  { id: "fc-int-7", topicId: "integrals", category: "formula",
    front: "$\\int \\frac{1}{1+x^2}\\,dx$",
    back: "$= \\arctan x + C$" },
  { id: "fc-int-8", topicId: "integrals", category: "formula",
    front: "$\\int \\frac{1}{\\sqrt{1-x^2}}\\,dx$",
    back: "$= \\arcsin x + C$" },
  { id: "fc-int-9", topicId: "integrals", category: "technique",
    front: "Integration by Parts",
    back: "$\\int u\\,dv = uv - \\int v\\,du$. Choose $u$ with LIATE priority: Logs, Inverse trig, Algebraic, Trig, Exponential." },
  { id: "fc-int-10", topicId: "integrals", category: "technique",
    front: "u-Substitution",
    back: "If $\\int f(g(x))g'(x)\\,dx$, let $u = g(x)$: $\\int f(u)\\,du$." },
  { id: "fc-int-11", topicId: "integrals", category: "rule",
    front: "Fundamental Theorem of Calculus",
    back: "$\\int_a^b f(x)\\,dx = F(b) - F(a)$ where $F'(x) = f(x)$." },

  // ── Applications ──────────────────────────────────────────
  { id: "fc-app-1", topicId: "applications", category: "technique",
    front: "Finding Critical Points",
    back: "Set $f'(x) = 0$ and solve. Also check where $f'$ is undefined." },
  { id: "fc-app-2", topicId: "applications", category: "rule",
    front: "Second Derivative Test",
    back: "At critical point $c$: if $f''(c) > 0$ → local min; if $f''(c) < 0$ → local max; if $f''(c) = 0$ → inconclusive." },
  { id: "fc-app-3", topicId: "applications", category: "rule",
    front: "Mean Value Theorem",
    back: "If $f$ is continuous on $[a,b]$ and differentiable on $(a,b)$, then $\\exists\\, c$ where $f'(c) = \\frac{f(b)-f(a)}{b-a}$." },
  { id: "fc-app-4", topicId: "applications", category: "technique",
    front: "Related Rates Strategy",
    back: "1. Draw diagram. 2. Write equation relating variables. 3. Differentiate w.r.t. time. 4. Plug in known values. 5. Solve." },
  { id: "fc-app-5", topicId: "applications", category: "technique",
    front: "Optimization Strategy",
    back: "1. Define objective function. 2. Express in one variable (use constraint). 3. Take derivative and set = 0. 4. Verify with 2nd derivative test." },

  // ── Series ────────────────────────────────────────────────
  { id: "fc-ser-1", topicId: "series", category: "formula",
    front: "Geometric Series Sum",
    back: "$\\sum_{n=0}^{\\infty} ar^n = \\frac{a}{1-r}$ for $|r| < 1$." },
  { id: "fc-ser-2", topicId: "series", category: "rule",
    front: "p-Series Test",
    back: "$\\sum \\frac{1}{n^p}$ converges if $p > 1$, diverges if $p \\le 1$." },
  { id: "fc-ser-3", topicId: "series", category: "rule",
    front: "Ratio Test",
    back: "If $\\lim\\frac{|a_{n+1}|}{|a_n|} = L$: converges if $L<1$, diverges if $L>1$, inconclusive if $L=1$." },
  { id: "fc-ser-4", topicId: "series", category: "rule",
    front: "Alternating Series Test",
    back: "$\\sum(-1)^n b_n$ converges if $b_n$ is decreasing and $\\lim b_n = 0$." },
  { id: "fc-ser-5", topicId: "series", category: "formula",
    front: "Taylor Series for $e^x$",
    back: "$e^x = \\sum_{n=0}^{\\infty}\\frac{x^n}{n!} = 1 + x + \\frac{x^2}{2!} + \\frac{x^3}{3!} + \\cdots$" },
  { id: "fc-ser-6", topicId: "series", category: "formula",
    front: "Taylor Series for $\\sin x$",
    back: "$\\sin x = \\sum_{n=0}^{\\infty}\\frac{(-1)^n x^{2n+1}}{(2n+1)!} = x - \\frac{x^3}{6} + \\frac{x^5}{120} - \\cdots$" },
  { id: "fc-ser-7", topicId: "series", category: "formula",
    front: "Taylor Series for $\\cos x$",
    back: "$\\cos x = \\sum_{n=0}^{\\infty}\\frac{(-1)^n x^{2n}}{(2n)!} = 1 - \\frac{x^2}{2} + \\frac{x^4}{24} - \\cdots$" },
  { id: "fc-ser-8", topicId: "series", category: "rule",
    front: "Divergence Test (nth-term test)",
    back: "If $\\lim_{n\\to\\infty} a_n \\neq 0$, then $\\sum a_n$ diverges. (But $\\lim a_n = 0$ does NOT guarantee convergence.)" },

  // ── Differential Equations ────────────────────────────────
  { id: "fc-de-1", topicId: "differential-equations", category: "technique",
    front: "Separable Equations",
    back: "If $y' = f(x)g(y)$, separate: $\\frac{dy}{g(y)} = f(x)\\,dx$, then integrate both sides." },
  { id: "fc-de-2", topicId: "differential-equations", category: "technique",
    front: "Integrating Factor (Linear 1st order)",
    back: "For $y' + P(x)y = Q(x)$: multiply by $\\mu = e^{\\int P(x)\\,dx}$. Then $(\\mu y)' = \\mu Q$." },
  { id: "fc-de-3", topicId: "differential-equations", category: "formula",
    front: "Exponential Growth/Decay",
    back: "$y' = ky \\Rightarrow y = Ce^{kt}$. Growth if $k>0$, decay if $k<0$." },
  { id: "fc-de-4", topicId: "differential-equations", category: "technique",
    front: "Characteristic Equation (2nd order)",
    back: "For $ay''+by'+cy=0$: solve $ar^2+br+c=0$. Real roots → $Ae^{r_1 x}+Be^{r_2 x}$. Repeated → $(A+Bx)e^{rx}$. Complex $\\alpha\\pm\\beta i$ → $e^{\\alpha x}(A\\cos\\beta x+B\\sin\\beta x)$." },
  { id: "fc-de-5", topicId: "differential-equations", category: "formula",
    front: "Logistic Growth",
    back: "$P' = rP(1 - P/K)$. Solution: $P(t) = \\frac{K}{1+Ae^{-rt}}$. Carrying capacity = $K$." },

  // ── Trig Identities (useful across topics) ────────────────
  { id: "fc-trig-1", topicId: "limits", category: "identity",
    front: "Pythagorean Identity",
    back: "$\\sin^2 x + \\cos^2 x = 1$" },
  { id: "fc-trig-2", topicId: "integrals", category: "identity",
    front: "Double Angle: $\\sin(2x)$",
    back: "$\\sin(2x) = 2\\sin(x)\\cos(x)$" },
  { id: "fc-trig-3", topicId: "integrals", category: "identity",
    front: "Power-Reducing: $\\sin^2(x)$",
    back: "$\\sin^2(x) = \\frac{1 - \\cos(2x)}{2}$" },
  { id: "fc-trig-4", topicId: "integrals", category: "identity",
    front: "Power-Reducing: $\\cos^2(x)$",
    back: "$\\cos^2(x) = \\frac{1 + \\cos(2x)}{2}$" },
];

export function getFlashCardsForTopic(topicId: string): FlashCard[] {
  return flashCards.filter((fc) => fc.topicId === topicId);
}
