/**
 * Test questions - separate from practice questions
 * 20 high-quality, hand-crafted questions per module
 * These are only shown during tests, never in practice mode
 */

export type TestQuestion = {
  id: string;
  topicId: string;
  prompt: string;
  type: "numeric" | "mcq";
  answer: string;
  choices?: string[];
  explanation: string;
  difficulty: "easy" | "medium" | "hard";
};

// ============================================================================
// LIMITS & CONTINUITY TEST QUESTIONS
// ============================================================================
const limitsTestQuestions: TestQuestion[] = [
  {
    id: "test-limits-1",
    topicId: "limits",
    prompt: "Evaluate: $\\lim_{x \\to 2} \\frac{x^3 - 8}{x - 2}$",
    type: "numeric",
    answer: "12",
    explanation: "Step 1: Factor using difference of cubes: $x^3 - 8 = (x-2)(x^2 + 2x + 4)$. Step 2: Cancel $(x-2)$: $\\lim_{x \\to 2}(x^2 + 2x + 4)$. Step 3: Substitute $x = 2$: $4 + 4 + 4 = 12$. Final answer: $12$.",
    difficulty: "medium",
  },
  {
    id: "test-limits-2",
    topicId: "limits",
    prompt: "Find: $\\lim_{x \\to 0} \\frac{1 - \\cos(x)}{x^2}$",
    type: "numeric",
    answer: "1/2",
    explanation: "Step 1: Use L'Hôpital's Rule (gives $\\frac{0}{0}$). Step 2: Differentiate: $\\lim_{x \\to 0} \\frac{\\sin(x)}{2x}$. Step 3: Still $\\frac{0}{0}$, apply again: $\\lim_{x \\to 0} \\frac{\\cos(x)}{2} = \\frac{1}{2}$. Final answer: $\\frac{1}{2}$.",
    difficulty: "hard",
  },
  {
    id: "test-limits-3",
    topicId: "limits",
    prompt: "Compute: $\\lim_{x \\to \\infty} \\frac{3x^2 + 5x - 1}{2x^2 - 7}$",
    type: "numeric",
    answer: "3/2",
    explanation: "Step 1: Divide numerator and denominator by $x^2$. Step 2: Get $\\frac{3 + 5/x - 1/x^2}{2 - 7/x^2}$. Step 3: As $x \\to \\infty$, terms with $x$ vanish: $\\frac{3}{2}$. Final answer: $\\frac{3}{2}$.",
    difficulty: "easy",
  },
  {
    id: "test-limits-4",
    topicId: "limits",
    prompt: "Evaluate: $\\lim_{x \\to 0} \\frac{\\tan(3x)}{\\sin(5x)}$",
    type: "numeric",
    answer: "3/5",
    explanation: "Step 1: Rewrite as $\\frac{\\sin(3x)}{\\cos(3x) \\cdot \\sin(5x)}$. Step 2: Use small angle approximations: $\\sin(kx) \\approx kx$ near 0. Step 3: Get $\\frac{3x}{1 \\cdot 5x} = \\frac{3}{5}$. Final answer: $\\frac{3}{5}$.",
    difficulty: "medium",
  },
  {
    id: "test-limits-5",
    topicId: "limits",
    prompt: "Find: $\\lim_{h \\to 0} \\frac{(2+h)^3 - 8}{h}$",
    type: "numeric",
    answer: "12",
    explanation: "Step 1: This is the derivative of $f(x) = x^3$ at $x = 2$. Step 2: $f'(x) = 3x^2$. Step 3: $f'(2) = 3(4) = 12$. Final answer: $12$.",
    difficulty: "medium",
  },
  {
    id: "test-limits-6",
    topicId: "limits",
    prompt: "Evaluate: $\\lim_{x \\to 4} \\frac{\\sqrt{x} - 2}{x - 4}$",
    type: "numeric",
    answer: "1/4",
    explanation: "Step 1: Rationalize: multiply by $\\frac{\\sqrt{x}+2}{\\sqrt{x}+2}$. Step 2: Get $\\frac{x-4}{(x-4)(\\sqrt{x}+2)} = \\frac{1}{\\sqrt{x}+2}$. Step 3: Substitute $x=4$: $\\frac{1}{2+2} = \\frac{1}{4}$. Final answer: $\\frac{1}{4}$.",
    difficulty: "medium",
  },
  {
    id: "test-limits-7",
    topicId: "limits",
    prompt: "Does the limit exist? $\\lim_{x \\to 0} \\frac{|x|}{x}$",
    type: "mcq",
    answer: "Does not exist",
    choices: ["1", "-1", "0", "Does not exist"],
    explanation: "Step 1: From the right: $\\lim_{x \\to 0^+} \\frac{x}{x} = 1$. Step 2: From the left: $\\lim_{x \\to 0^-} \\frac{-x}{x} = -1$. Step 3: Left ≠ Right, so limit DNE. Final answer: Does not exist.",
    difficulty: "easy",
  },
  {
    id: "test-limits-8",
    topicId: "limits",
    prompt: "Find: $\\lim_{x \\to 0} \\frac{e^x - 1 - x}{x^2}$",
    type: "numeric",
    answer: "1/2",
    explanation: "Step 1: Apply L'Hôpital's: $\\frac{e^x - 1}{2x}$. Step 2: Still $\\frac{0}{0}$, apply again: $\\frac{e^x}{2}$. Step 3: At $x=0$: $\\frac{1}{2}$. Final answer: $\\frac{1}{2}$.",
    difficulty: "hard",
  },
  {
    id: "test-limits-9",
    topicId: "limits",
    prompt: "Compute: $\\lim_{x \\to 1} \\frac{x^4 - 1}{x^3 - 1}$",
    type: "numeric",
    answer: "4/3",
    explanation: "Step 1: Factor: $\\frac{(x-1)(x^3+x^2+x+1)}{(x-1)(x^2+x+1)}$. Step 2: Cancel $(x-1)$. Step 3: Substitute $x=1$: $\\frac{4}{3}$. Final answer: $\\frac{4}{3}$.",
    difficulty: "medium",
  },
  {
    id: "test-limits-10",
    topicId: "limits",
    prompt: "Evaluate: $\\lim_{x \\to \\infty} x \\sin\\left(\\frac{1}{x}\\right)$",
    type: "numeric",
    answer: "1",
    explanation: "Step 1: Let $u = \\frac{1}{x}$, so $x = \\frac{1}{u}$ and $u \\to 0$. Step 2: Limit becomes $\\lim_{u \\to 0} \\frac{\\sin(u)}{u}$. Step 3: This equals $1$. Final answer: $1$.",
    difficulty: "hard",
  },
  {
    id: "test-limits-11",
    topicId: "limits",
    prompt: "Find: $\\lim_{x \\to 0^+} x \\ln(x)$",
    type: "numeric",
    answer: "0",
    explanation: "Step 1: Rewrite as $\\lim_{x \\to 0^+} \\frac{\\ln(x)}{1/x}$ (form $\\frac{-\\infty}{\\infty}$). Step 2: L'Hôpital's: $\\frac{1/x}{-1/x^2} = -x$. Step 3: As $x \\to 0^+$: $0$. Final answer: $0$.",
    difficulty: "hard",
  },
  {
    id: "test-limits-12",
    topicId: "limits",
    prompt: "Evaluate: $\\lim_{x \\to 3} \\frac{x^2 - 5x + 6}{x^2 - 9}$",
    type: "numeric",
    answer: "1/6",
    explanation: "Step 1: Factor: $\\frac{(x-2)(x-3)}{(x-3)(x+3)}$. Step 2: Cancel $(x-3)$: $\\frac{x-2}{x+3}$. Step 3: At $x=3$: $\\frac{1}{6}$. Final answer: $\\frac{1}{6}$.",
    difficulty: "easy",
  },
  {
    id: "test-limits-13",
    topicId: "limits",
    prompt: "Compute: $\\lim_{x \\to \\pi/2} (x - \\frac{\\pi}{2})\\tan(x)$",
    type: "numeric",
    answer: "-1",
    explanation: "Step 1: Let $u = x - \\frac{\\pi}{2}$, so $\\tan(x) = -\\cot(u)$. Step 2: Limit is $\\lim_{u \\to 0} -u \\cot(u) = -\\lim_{u \\to 0} \\frac{u \\cos(u)}{\\sin(u)}$. Step 3: This equals $-1$. Final answer: $-1$.",
    difficulty: "hard",
  },
  {
    id: "test-limits-14",
    topicId: "limits",
    prompt: "Find: $\\lim_{n \\to \\infty} \\left(1 + \\frac{2}{n}\\right)^n$",
    type: "numeric",
    answer: "e^2",
    explanation: "Step 1: This is of the form $\\lim (1 + \\frac{k}{n})^n = e^k$. Step 2: Here $k = 2$. Step 3: Answer is $e^2$. Final answer: $e^2$.",
    difficulty: "medium",
  },
  {
    id: "test-limits-15",
    topicId: "limits",
    prompt: "Evaluate: $\\lim_{x \\to 0} \\frac{\\sin(x) - x}{x^3}$",
    type: "numeric",
    answer: "-1/6",
    explanation: "Step 1: Apply L'Hôpital's repeatedly. Step 2: First: $\\frac{\\cos(x)-1}{3x^2}$, then $\\frac{-\\sin(x)}{6x}$, then $\\frac{-\\cos(x)}{6}$. Step 3: At $x=0$: $-\\frac{1}{6}$. Final answer: $-\\frac{1}{6}$.",
    difficulty: "hard",
  },
  {
    id: "test-limits-16",
    topicId: "limits",
    prompt: "Is $f(x) = \\frac{x^2 - 4}{x - 2}$ continuous at $x = 2$?",
    type: "mcq",
    answer: "No, removable discontinuity",
    choices: ["Yes, continuous", "No, jump discontinuity", "No, removable discontinuity", "No, infinite discontinuity"],
    explanation: "Step 1: $f(2)$ is undefined (division by zero). Step 2: The limit exists: $\\lim_{x \\to 2} (x+2) = 4$. Step 3: Removable discontinuity since limit exists but function undefined. Final answer: No, removable discontinuity.",
    difficulty: "easy",
  },
  {
    id: "test-limits-17",
    topicId: "limits",
    prompt: "Find: $\\lim_{x \\to -\\infty} \\frac{5x^3 - 2x}{x^3 + 1}$",
    type: "numeric",
    answer: "5",
    explanation: "Step 1: Divide by $x^3$. Step 2: Get $\\frac{5 - 2/x^2}{1 + 1/x^3}$. Step 3: As $x \\to -\\infty$, this approaches $5$. Final answer: $5$.",
    difficulty: "easy",
  },
  {
    id: "test-limits-18",
    topicId: "limits",
    prompt: "Compute: $\\lim_{x \\to 0} \\frac{\\arctan(x)}{x}$",
    type: "numeric",
    answer: "1",
    explanation: "Step 1: This is $\\frac{0}{0}$, use L'Hôpital's. Step 2: $\\frac{1/(1+x^2)}{1} = \\frac{1}{1+x^2}$. Step 3: At $x=0$: $1$. Final answer: $1$.",
    difficulty: "medium",
  },
  {
    id: "test-limits-19",
    topicId: "limits",
    prompt: "Evaluate: $\\lim_{x \\to 1^+} \\frac{1}{\\ln(x)}$",
    type: "mcq",
    answer: "+∞",
    choices: ["0", "1", "+∞", "-∞"],
    explanation: "Step 1: As $x \\to 1^+$, $\\ln(x) \\to 0^+$. Step 2: So $\\frac{1}{\\ln(x)} \\to +\\infty$. Final answer: $+\\infty$.",
    difficulty: "medium",
  },
  {
    id: "test-limits-20",
    topicId: "limits",
    prompt: "Find: $\\lim_{x \\to 0} \\frac{\\sqrt{1+x} - \\sqrt{1-x}}{x}$",
    type: "numeric",
    answer: "1",
    explanation: "Step 1: Rationalize by multiplying by $\\frac{\\sqrt{1+x}+\\sqrt{1-x}}{\\sqrt{1+x}+\\sqrt{1-x}}$. Step 2: Numerator becomes $2x$, denominator $x(\\sqrt{1+x}+\\sqrt{1-x})$. Step 3: Simplify and substitute: $\\frac{2}{2} = 1$. Final answer: $1$.",
    difficulty: "hard",
  },
];

// ============================================================================
// DERIVATIVES TEST QUESTIONS
// ============================================================================
const derivativesTestQuestions: TestQuestion[] = [
  {
    id: "test-derivatives-1",
    topicId: "derivatives",
    prompt: "Find $\\frac{d}{dx}\\left(x^2 e^x\\right)$",
    type: "numeric",
    answer: "(2x + x^2)e^x",
    explanation: "Step 1: Use product rule: $(uv)' = u'v + uv'$. Step 2: $u = x^2$, $u' = 2x$; $v = e^x$, $v' = e^x$. Step 3: Result: $2xe^x + x^2e^x = (2x + x^2)e^x$. Final answer: $(2x + x^2)e^x$.",
    difficulty: "medium",
  },
  {
    id: "test-derivatives-2",
    topicId: "derivatives",
    prompt: "Compute $\\frac{d}{dx}\\left(\\ln(\\sin(x))\\right)$",
    type: "numeric",
    answer: "cot(x)",
    explanation: "Step 1: Chain rule: $\\frac{1}{\\sin(x)} \\cdot \\cos(x)$. Step 2: Simplify: $\\frac{\\cos(x)}{\\sin(x)} = \\cot(x)$. Final answer: $\\cot(x)$.",
    difficulty: "medium",
  },
  {
    id: "test-derivatives-3",
    topicId: "derivatives",
    prompt: "Find $\\frac{dy}{dx}$ if $x^2 + y^2 = 25$",
    type: "numeric",
    answer: "-x/y",
    explanation: "Step 1: Differentiate implicitly: $2x + 2y\\frac{dy}{dx} = 0$. Step 2: Solve: $\\frac{dy}{dx} = -\\frac{x}{y}$. Final answer: $-\\frac{x}{y}$.",
    difficulty: "medium",
  },
  {
    id: "test-derivatives-4",
    topicId: "derivatives",
    prompt: "Differentiate: $f(x) = \\tan^{-1}(3x)$",
    type: "numeric",
    answer: "3/(1 + 9x^2)",
    explanation: "Step 1: Use $\\frac{d}{dx}[\\arctan(u)] = \\frac{u'}{1+u^2}$. Step 2: Here $u = 3x$, $u' = 3$. Step 3: Result: $\\frac{3}{1 + 9x^2}$. Final answer: $\\frac{3}{1 + 9x^2}$.",
    difficulty: "medium",
  },
  {
    id: "test-derivatives-5",
    topicId: "derivatives",
    prompt: "Find $\\frac{d}{dx}\\left(x^x\\right)$ at $x = 1$",
    type: "numeric",
    answer: "1",
    explanation: "Step 1: Let $y = x^x$, so $\\ln(y) = x\\ln(x)$. Step 2: Differentiate: $\\frac{y'}{y} = \\ln(x) + 1$. Step 3: $y' = x^x(\\ln(x) + 1)$. At $x=1$: $1^1(0 + 1) = 1$. Final answer: $1$.",
    difficulty: "hard",
  },
  {
    id: "test-derivatives-6",
    topicId: "derivatives",
    prompt: "Compute: $\\frac{d^2}{dx^2}\\left(\\cos(2x)\\right)$",
    type: "numeric",
    answer: "-4cos(2x)",
    explanation: "Step 1: First derivative: $-2\\sin(2x)$. Step 2: Second derivative: $-4\\cos(2x)$. Final answer: $-4\\cos(2x)$.",
    difficulty: "easy",
  },
  {
    id: "test-derivatives-7",
    topicId: "derivatives",
    prompt: "Find $\\frac{d}{dx}\\left(\\frac{e^x}{x^2}\\right)$",
    type: "numeric",
    answer: "(x - 2)e^x/x^3",
    explanation: "Step 1: Quotient rule: $\\frac{u'v - uv'}{v^2}$. Step 2: $u = e^x$, $v = x^2$. Step 3: $\\frac{e^x \\cdot x^2 - e^x \\cdot 2x}{x^4} = \\frac{e^x(x-2)}{x^3}$. Final answer: $\\frac{(x-2)e^x}{x^3}$.",
    difficulty: "medium",
  },
  {
    id: "test-derivatives-8",
    topicId: "derivatives",
    prompt: "If $f(x) = \\sqrt{x^2 + 1}$, find $f'(0)$",
    type: "numeric",
    answer: "0",
    explanation: "Step 1: $f'(x) = \\frac{x}{\\sqrt{x^2+1}}$ by chain rule. Step 2: At $x = 0$: $f'(0) = \\frac{0}{1} = 0$. Final answer: $0$.",
    difficulty: "easy",
  },
  {
    id: "test-derivatives-9",
    topicId: "derivatives",
    prompt: "Find $\\frac{dy}{dx}$ if $e^{xy} = x + y$",
    type: "numeric",
    answer: "(1 - ye^{xy})/(xe^{xy} - 1)",
    explanation: "Step 1: Differentiate: $e^{xy}(y + xy') = 1 + y'$. Step 2: $ye^{xy} + xe^{xy}y' = 1 + y'$. Step 3: Solve for $y'$: $y' = \\frac{1 - ye^{xy}}{xe^{xy} - 1}$. Final answer: $\\frac{1 - ye^{xy}}{xe^{xy} - 1}$.",
    difficulty: "hard",
  },
  {
    id: "test-derivatives-10",
    topicId: "derivatives",
    prompt: "Differentiate: $f(x) = \\sec^2(x)$",
    type: "numeric",
    answer: "2sec^2(x)tan(x)",
    explanation: "Step 1: Chain rule on $(\\sec(x))^2$. Step 2: $2\\sec(x) \\cdot \\sec(x)\\tan(x) = 2\\sec^2(x)\\tan(x)$. Final answer: $2\\sec^2(x)\\tan(x)$.",
    difficulty: "medium",
  },
  {
    id: "test-derivatives-11",
    topicId: "derivatives",
    prompt: "Find $\\frac{d}{dx}\\left(5^x\\right)$",
    type: "numeric",
    answer: "5^x ln(5)",
    explanation: "Step 1: Use formula $\\frac{d}{dx}(a^x) = a^x \\ln(a)$. Step 2: Here $a = 5$. Final answer: $5^x \\ln(5)$.",
    difficulty: "easy",
  },
  {
    id: "test-derivatives-12",
    topicId: "derivatives",
    prompt: "Compute: $\\frac{d}{dx}\\left(\\ln\\left(\\frac{x+1}{x-1}\\right)\\right)$",
    type: "numeric",
    answer: "-2/(x^2 - 1)",
    explanation: "Step 1: Rewrite as $\\ln(x+1) - \\ln(x-1)$. Step 2: Differentiate: $\\frac{1}{x+1} - \\frac{1}{x-1}$. Step 3: Combine: $\\frac{(x-1)-(x+1)}{(x+1)(x-1)} = \\frac{-2}{x^2-1}$. Final answer: $\\frac{-2}{x^2-1}$.",
    difficulty: "medium",
  },
  {
    id: "test-derivatives-13",
    topicId: "derivatives",
    prompt: "Find the slope of $y = x^3 - 3x$ at the point where $x = 2$",
    type: "numeric",
    answer: "9",
    explanation: "Step 1: $y' = 3x^2 - 3$. Step 2: At $x = 2$: $3(4) - 3 = 9$. Final answer: $9$.",
    difficulty: "easy",
  },
  {
    id: "test-derivatives-14",
    topicId: "derivatives",
    prompt: "Find $\\frac{d}{dx}\\left(\\sin^{-1}(2x)\\right)$",
    type: "numeric",
    answer: "2/sqrt(1 - 4x^2)",
    explanation: "Step 1: Use $\\frac{d}{dx}[\\arcsin(u)] = \\frac{u'}{\\sqrt{1-u^2}}$. Step 2: $u = 2x$, $u' = 2$. Step 3: Result: $\\frac{2}{\\sqrt{1-4x^2}}$. Final answer: $\\frac{2}{\\sqrt{1-4x^2}}$.",
    difficulty: "medium",
  },
  {
    id: "test-derivatives-15",
    topicId: "derivatives",
    prompt: "Differentiate: $f(x) = e^{\\sin(x)}$",
    type: "numeric",
    answer: "cos(x)e^{sin(x)}",
    explanation: "Step 1: Chain rule: $e^{\\sin(x)} \\cdot \\cos(x)$. Final answer: $\\cos(x)e^{\\sin(x)}$.",
    difficulty: "easy",
  },
  {
    id: "test-derivatives-16",
    topicId: "derivatives",
    prompt: "Find $\\frac{dy}{dx}$ if $y = (\\ln(x))^3$",
    type: "numeric",
    answer: "3(ln(x))^2/x",
    explanation: "Step 1: Chain rule: $3(\\ln(x))^2 \\cdot \\frac{1}{x}$. Final answer: $\\frac{3(\\ln(x))^2}{x}$.",
    difficulty: "easy",
  },
  {
    id: "test-derivatives-17",
    topicId: "derivatives",
    prompt: "Find the equation of the tangent line to $y = e^x$ at $x = 0$",
    type: "numeric",
    answer: "y = x + 1",
    explanation: "Step 1: At $x = 0$: $y = e^0 = 1$. Step 2: $y' = e^x$, so slope at $x=0$ is $1$. Step 3: Tangent: $y - 1 = 1(x - 0)$, or $y = x + 1$. Final answer: $y = x + 1$.",
    difficulty: "medium",
  },
  {
    id: "test-derivatives-18",
    topicId: "derivatives",
    prompt: "Find $\\frac{d}{dx}\\left(\\cosh(x)\\right)$ where $\\cosh(x) = \\frac{e^x + e^{-x}}{2}$",
    type: "numeric",
    answer: "sinh(x)",
    explanation: "Step 1: Differentiate: $\\frac{e^x - e^{-x}}{2}$. Step 2: This is the definition of $\\sinh(x)$. Final answer: $\\sinh(x)$.",
    difficulty: "medium",
  },
  {
    id: "test-derivatives-19",
    topicId: "derivatives",
    prompt: "If $f(x) = |x^2 - 4|$, find $f'(3)$",
    type: "numeric",
    answer: "6",
    explanation: "Step 1: At $x = 3$: $x^2 - 4 = 5 > 0$, so $f(x) = x^2 - 4$. Step 2: $f'(x) = 2x$. Step 3: $f'(3) = 6$. Final answer: $6$.",
    difficulty: "medium",
  },
  {
    id: "test-derivatives-20",
    topicId: "derivatives",
    prompt: "Find $\\frac{d^3}{dx^3}(e^{2x})$",
    type: "numeric",
    answer: "8e^{2x}",
    explanation: "Step 1: First: $2e^{2x}$. Step 2: Second: $4e^{2x}$. Step 3: Third: $8e^{2x}$. Final answer: $8e^{2x}$.",
    difficulty: "easy",
  },
];

// ============================================================================
// INTEGRALS TEST QUESTIONS
// ============================================================================
const integralsTestQuestions: TestQuestion[] = [
  {
    id: "test-integrals-1",
    topicId: "integrals",
    prompt: "Evaluate: $\\int x e^x dx$",
    type: "numeric",
    answer: "(x - 1)e^x + C",
    explanation: "Step 1: Integration by parts: $u = x$, $dv = e^x dx$. Step 2: $du = dx$, $v = e^x$. Step 3: $xe^x - \\int e^x dx = xe^x - e^x + C = (x-1)e^x + C$. Final answer: $(x-1)e^x + C$.",
    difficulty: "medium",
  },
  {
    id: "test-integrals-2",
    topicId: "integrals",
    prompt: "Compute: $\\int_0^{\\pi/2} \\sin^2(x) dx$",
    type: "numeric",
    answer: "π/4",
    explanation: "Step 1: Use identity $\\sin^2(x) = \\frac{1 - \\cos(2x)}{2}$. Step 2: Integrate: $\\frac{1}{2}[x - \\frac{\\sin(2x)}{2}]_0^{\\pi/2}$. Step 3: $= \\frac{1}{2}[\\frac{\\pi}{2} - 0] = \\frac{\\pi}{4}$. Final answer: $\\frac{\\pi}{4}$.",
    difficulty: "hard",
  },
  {
    id: "test-integrals-3",
    topicId: "integrals",
    prompt: "Find: $\\int \\frac{1}{x^2 + 4} dx$",
    type: "numeric",
    answer: "(1/2)arctan(x/2) + C",
    explanation: "Step 1: Factor: $\\frac{1}{4}\\int \\frac{1}{(x/2)^2 + 1} dx$. Step 2: Substitute $u = x/2$: $\\frac{1}{2}\\arctan(x/2) + C$. Final answer: $\\frac{1}{2}\\arctan(\\frac{x}{2}) + C$.",
    difficulty: "medium",
  },
  {
    id: "test-integrals-4",
    topicId: "integrals",
    prompt: "Evaluate: $\\int \\frac{x}{x^2 + 1} dx$",
    type: "numeric",
    answer: "(1/2)ln(x^2 + 1) + C",
    explanation: "Step 1: Let $u = x^2 + 1$, $du = 2x dx$. Step 2: Integral becomes $\\frac{1}{2}\\int \\frac{du}{u} = \\frac{1}{2}\\ln|u| + C$. Final answer: $\\frac{1}{2}\\ln(x^2+1) + C$.",
    difficulty: "easy",
  },
  {
    id: "test-integrals-5",
    topicId: "integrals",
    prompt: "Compute: $\\int \\sec^2(3x) dx$",
    type: "numeric",
    answer: "(1/3)tan(3x) + C",
    explanation: "Step 1: Antiderivative of $\\sec^2(u)$ is $\\tan(u)$. Step 2: Chain rule gives factor of $\\frac{1}{3}$. Final answer: $\\frac{1}{3}\\tan(3x) + C$.",
    difficulty: "easy",
  },
  {
    id: "test-integrals-6",
    topicId: "integrals",
    prompt: "Find: $\\int_1^e \\frac{\\ln(x)}{x} dx$",
    type: "numeric",
    answer: "1/2",
    explanation: "Step 1: Let $u = \\ln(x)$, $du = \\frac{1}{x}dx$. Step 2: Bounds: $x=1 \\Rightarrow u=0$, $x=e \\Rightarrow u=1$. Step 3: $\\int_0^1 u du = [\\frac{u^2}{2}]_0^1 = \\frac{1}{2}$. Final answer: $\\frac{1}{2}$.",
    difficulty: "medium",
  },
  {
    id: "test-integrals-7",
    topicId: "integrals",
    prompt: "Evaluate: $\\int \\frac{1}{x \\ln(x)} dx$",
    type: "numeric",
    answer: "ln(ln(x)) + C",
    explanation: "Step 1: Let $u = \\ln(x)$, $du = \\frac{1}{x}dx$. Step 2: Integral becomes $\\int \\frac{1}{u} du = \\ln|u| + C$. Final answer: $\\ln(\\ln(x)) + C$.",
    difficulty: "medium",
  },
  {
    id: "test-integrals-8",
    topicId: "integrals",
    prompt: "Compute: $\\int x^2 \\ln(x) dx$",
    type: "numeric",
    answer: "(x^3/3)ln(x) - x^3/9 + C",
    explanation: "Step 1: By parts: $u = \\ln(x)$, $dv = x^2 dx$. Step 2: $v = \\frac{x^3}{3}$, $du = \\frac{1}{x}dx$. Step 3: $\\frac{x^3}{3}\\ln(x) - \\int \\frac{x^2}{3}dx = \\frac{x^3}{3}\\ln(x) - \\frac{x^3}{9} + C$. Final answer: $\\frac{x^3}{3}\\ln(x) - \\frac{x^3}{9} + C$.",
    difficulty: "hard",
  },
  {
    id: "test-integrals-9",
    topicId: "integrals",
    prompt: "Find: $\\int \\frac{1}{\\sqrt{9 - x^2}} dx$",
    type: "numeric",
    answer: "arcsin(x/3) + C",
    explanation: "Step 1: This is of form $\\int \\frac{1}{\\sqrt{a^2-x^2}}dx$ with $a=3$. Step 2: Result is $\\arcsin(\\frac{x}{a}) + C$. Final answer: $\\arcsin(\\frac{x}{3}) + C$.",
    difficulty: "medium",
  },
  {
    id: "test-integrals-10",
    topicId: "integrals",
    prompt: "Evaluate: $\\int_0^1 x e^{-x^2} dx$",
    type: "numeric",
    answer: "(1 - 1/e)/2",
    explanation: "Step 1: Let $u = -x^2$, $du = -2x dx$. Step 2: $-\\frac{1}{2}\\int_0^{-1} e^u du = -\\frac{1}{2}[e^u]_0^{-1}$. Step 3: $= -\\frac{1}{2}(e^{-1} - 1) = \\frac{1-e^{-1}}{2}$. Final answer: $\\frac{1-\\frac{1}{e}}{2}$.",
    difficulty: "hard",
  },
  {
    id: "test-integrals-11",
    topicId: "integrals",
    prompt: "Find: $\\int \\tan(x) dx$",
    type: "numeric",
    answer: "-ln|cos(x)| + C",
    explanation: "Step 1: Rewrite as $\\int \\frac{\\sin(x)}{\\cos(x)}dx$. Step 2: Let $u = \\cos(x)$, $du = -\\sin(x)dx$. Step 3: $-\\int \\frac{du}{u} = -\\ln|u| + C$. Final answer: $-\\ln|\\cos(x)| + C$.",
    difficulty: "easy",
  },
  {
    id: "test-integrals-12",
    topicId: "integrals",
    prompt: "Compute: $\\int_0^{\\pi} x \\sin(x) dx$",
    type: "numeric",
    answer: "π",
    explanation: "Step 1: By parts: $u = x$, $dv = \\sin(x)dx$. Step 2: $[-x\\cos(x)]_0^\\pi + \\int_0^\\pi \\cos(x)dx = \\pi + [\\sin(x)]_0^\\pi = \\pi$. Final answer: $\\pi$.",
    difficulty: "hard",
  },
  {
    id: "test-integrals-13",
    topicId: "integrals",
    prompt: "Find: $\\int \\frac{2x + 3}{x^2 + 3x + 2} dx$",
    type: "numeric",
    answer: "ln|x^2 + 3x + 2| + C",
    explanation: "Step 1: Notice that $2x + 3$ is the derivative of $x^2 + 3x + 2$. Step 2: This is $\\int \\frac{du}{u}$ form. Final answer: $\\ln|x^2 + 3x + 2| + C$.",
    difficulty: "easy",
  },
  {
    id: "test-integrals-14",
    topicId: "integrals",
    prompt: "Evaluate: $\\int \\sin^3(x) dx$",
    type: "numeric",
    answer: "-cos(x) + (cos^3(x))/3 + C",
    explanation: "Step 1: Write as $\\sin(x)(1 - \\cos^2(x))$. Step 2: Let $u = \\cos(x)$. Step 3: $-\\int (1-u^2)du = -u + \\frac{u^3}{3} + C$. Final answer: $-\\cos(x) + \\frac{\\cos^3(x)}{3} + C$.",
    difficulty: "hard",
  },
  {
    id: "test-integrals-15",
    topicId: "integrals",
    prompt: "Find the area under $y = e^{-x}$ from $x = 0$ to $x = 2$",
    type: "numeric",
    answer: "1 - e^{-2}",
    explanation: "Step 1: $\\int_0^2 e^{-x}dx = [-e^{-x}]_0^2$. Step 2: $= -e^{-2} - (-1) = 1 - e^{-2}$. Final answer: $1 - e^{-2}$.",
    difficulty: "easy",
  },
  {
    id: "test-integrals-16",
    topicId: "integrals",
    prompt: "Compute: $\\int \\frac{1}{x^2 - 4} dx$",
    type: "numeric",
    answer: "(1/4)ln|(x-2)/(x+2)| + C",
    explanation: "Step 1: Partial fractions: $\\frac{1}{(x-2)(x+2)} = \\frac{A}{x-2} + \\frac{B}{x+2}$. Step 2: $A = 1/4$, $B = -1/4$. Step 3: Integrate: $\\frac{1}{4}\\ln|x-2| - \\frac{1}{4}\\ln|x+2| + C$. Final answer: $\\frac{1}{4}\\ln|\\frac{x-2}{x+2}| + C$.",
    difficulty: "hard",
  },
  {
    id: "test-integrals-17",
    topicId: "integrals",
    prompt: "Find: $\\int x \\sqrt{x+1} dx$",
    type: "numeric",
    answer: "(2/5)(x+1)^{5/2} - (2/3)(x+1)^{3/2} + C",
    explanation: "Step 1: Let $u = x + 1$, so $x = u - 1$. Step 2: $\\int (u-1)\\sqrt{u} du = \\int (u^{3/2} - u^{1/2})du$. Step 3: $= \\frac{2}{5}u^{5/2} - \\frac{2}{3}u^{3/2} + C$. Final answer: $\\frac{2}{5}(x+1)^{5/2} - \\frac{2}{3}(x+1)^{3/2} + C$.",
    difficulty: "hard",
  },
  {
    id: "test-integrals-18",
    topicId: "integrals",
    prompt: "Evaluate: $\\int \\csc^2(x) dx$",
    type: "numeric",
    answer: "-cot(x) + C",
    explanation: "Step 1: The antiderivative of $\\csc^2(x)$ is $-\\cot(x)$. Final answer: $-\\cot(x) + C$.",
    difficulty: "easy",
  },
  {
    id: "test-integrals-19",
    topicId: "integrals",
    prompt: "Compute: $\\int_0^1 \\frac{1}{1 + x^2} dx$",
    type: "numeric",
    answer: "π/4",
    explanation: "Step 1: Antiderivative is $\\arctan(x)$. Step 2: $[\\arctan(x)]_0^1 = \\arctan(1) - \\arctan(0) = \\frac{\\pi}{4} - 0$. Final answer: $\\frac{\\pi}{4}$.",
    difficulty: "easy",
  },
  {
    id: "test-integrals-20",
    topicId: "integrals",
    prompt: "Find: $\\int e^x \\sin(x) dx$",
    type: "numeric",
    answer: "(e^x/2)(sin(x) - cos(x)) + C",
    explanation: "Step 1: Apply integration by parts twice. Step 2: Let $I = \\int e^x \\sin(x)dx$. After two applications: $I = e^x\\sin(x) - e^x\\cos(x) - I$. Step 3: $2I = e^x(\\sin(x) - \\cos(x))$. Final answer: $\\frac{e^x}{2}(\\sin(x) - \\cos(x)) + C$.",
    difficulty: "hard",
  },
];

// ============================================================================
// APPLICATIONS OF DERIVATIVES TEST QUESTIONS
// ============================================================================
const applicationsTestQuestions: TestQuestion[] = [
  {
    id: "test-applications-1",
    topicId: "applications",
    prompt: "A box with square base and open top has volume 4 m³. Find the dimensions that minimize surface area.",
    type: "numeric",
    answer: "base = 2m, height = 1m",
    explanation: "Step 1: Let base = $x$, height = $h$. Volume: $x^2h = 4$, so $h = 4/x^2$. Step 2: Surface area: $S = x^2 + 4xh = x^2 + 16/x$. Step 3: $S' = 2x - 16/x^2 = 0$ gives $x = 2$. Height: $h = 1$. Final answer: base = 2m, height = 1m.",
    difficulty: "hard",
  },
  {
    id: "test-applications-2",
    topicId: "applications",
    prompt: "A ladder 10 ft long rests against a wall. The bottom slides away at 2 ft/s. How fast is the top sliding down when the bottom is 6 ft from the wall?",
    type: "numeric",
    answer: "3/2 ft/s",
    explanation: "Step 1: $x^2 + y^2 = 100$. Step 2: Differentiate: $2x\\frac{dx}{dt} + 2y\\frac{dy}{dt} = 0$. Step 3: At $x=6$, $y=8$. $2(6)(2) + 2(8)\\frac{dy}{dt} = 0$. Step 4: $\\frac{dy}{dt} = -\\frac{3}{2}$ ft/s (down). Final answer: $\\frac{3}{2}$ ft/s.",
    difficulty: "hard",
  },
  {
    id: "test-applications-3",
    topicId: "applications",
    prompt: "Find the critical points of $f(x) = x^3 - 6x^2 + 9x + 2$",
    type: "numeric",
    answer: "x = 1, x = 3",
    explanation: "Step 1: $f'(x) = 3x^2 - 12x + 9 = 3(x^2 - 4x + 3) = 3(x-1)(x-3)$. Step 2: Set $f'(x) = 0$: $x = 1$ or $x = 3$. Final answer: $x = 1, x = 3$.",
    difficulty: "easy",
  },
  {
    id: "test-applications-4",
    topicId: "applications",
    prompt: "The position of a particle is $s(t) = t^3 - 9t^2 + 24t$. When is the particle at rest?",
    type: "numeric",
    answer: "t = 2, t = 4",
    explanation: "Step 1: Velocity $v(t) = s'(t) = 3t^2 - 18t + 24 = 3(t^2 - 6t + 8) = 3(t-2)(t-4)$. Step 2: At rest when $v = 0$: $t = 2$ or $t = 4$. Final answer: $t = 2, t = 4$.",
    difficulty: "easy",
  },
  {
    id: "test-applications-5",
    topicId: "applications",
    prompt: "Find the absolute maximum of $f(x) = x^4 - 4x^3$ on $[-1, 4]$",
    type: "numeric",
    answer: "5",
    explanation: "Step 1: $f'(x) = 4x^3 - 12x^2 = 4x^2(x-3)$. Critical points: $x = 0, 3$. Step 2: Evaluate: $f(-1) = 5$, $f(0) = 0$, $f(3) = -27$, $f(4) = 0$. Step 3: Maximum is $5$ at $x = -1$. Final answer: $5$.",
    difficulty: "medium",
  },
  {
    id: "test-applications-6",
    topicId: "applications",
    prompt: "If the radius of a circle increases at 3 cm/s, how fast is the area increasing when $r = 10$ cm?",
    type: "numeric",
    answer: "60π cm²/s",
    explanation: "Step 1: $A = \\pi r^2$. Step 2: $\\frac{dA}{dt} = 2\\pi r \\frac{dr}{dt}$. Step 3: At $r = 10$, $\\frac{dr}{dt} = 3$: $\\frac{dA}{dt} = 2\\pi(10)(3) = 60\\pi$. Final answer: $60\\pi$ cm²/s.",
    difficulty: "easy",
  },
  {
    id: "test-applications-7",
    topicId: "applications",
    prompt: "Find where $f(x) = x^3 - 3x + 2$ is concave up",
    type: "numeric",
    answer: "x > 0",
    explanation: "Step 1: $f'(x) = 3x^2 - 3$, $f''(x) = 6x$. Step 2: Concave up when $f''(x) > 0$: $6x > 0 \\Rightarrow x > 0$. Final answer: $x > 0$.",
    difficulty: "easy",
  },
  {
    id: "test-applications-8",
    topicId: "applications",
    prompt: "Water is poured into a cone at 10 cm³/s. The cone has height 12 cm and radius 4 cm at top. How fast is the water level rising when the water is 6 cm deep?",
    type: "numeric",
    answer: "10/(π) cm/s",
    explanation: "Step 1: Similar triangles: $r = h/3$. Volume: $V = \\frac{1}{3}\\pi r^2 h = \\frac{\\pi h^3}{27}$. Step 2: $\\frac{dV}{dt} = \\frac{\\pi h^2}{9}\\frac{dh}{dt}$. Step 3: At $h = 6$: $10 = \\frac{\\pi(36)}{9}\\frac{dh}{dt} = 4\\pi\\frac{dh}{dt}$. Step 4: $\\frac{dh}{dt} = \\frac{10}{4\\pi} = \\frac{5}{2\\pi}$. Final answer: $\\frac{10}{\\pi}$ cm/s.",
    difficulty: "hard",
  },
  {
    id: "test-applications-9",
    topicId: "applications",
    prompt: "Use linearization to approximate $\\sqrt{4.1}$",
    type: "numeric",
    answer: "2.025",
    explanation: "Step 1: Let $f(x) = \\sqrt{x}$, $a = 4$. Step 2: $f(4) = 2$, $f'(x) = \\frac{1}{2\\sqrt{x}}$, $f'(4) = 0.25$. Step 3: $L(x) = 2 + 0.25(x-4)$. Step 4: $L(4.1) = 2 + 0.25(0.1) = 2.025$. Final answer: $2.025$.",
    difficulty: "medium",
  },
  {
    id: "test-applications-10",
    topicId: "applications",
    prompt: "Find the inflection points of $f(x) = x^4 - 6x^2$",
    type: "numeric",
    answer: "x = ±1",
    explanation: "Step 1: $f'(x) = 4x^3 - 12x$, $f''(x) = 12x^2 - 12 = 12(x^2 - 1)$. Step 2: $f''(x) = 0$: $x = \\pm 1$. Step 3: Sign changes at both points (inflection). Final answer: $x = \\pm 1$.",
    difficulty: "medium",
  },
  {
    id: "test-applications-11",
    topicId: "applications",
    prompt: "A farmer has 200 ft of fencing to enclose a rectangular area next to a river (no fence needed along river). Find the maximum area.",
    type: "numeric",
    answer: "5000 sq ft",
    explanation: "Step 1: Let width = $w$, length = $l$. Constraint: $2w + l = 200$, so $l = 200 - 2w$. Step 2: Area: $A = wl = w(200 - 2w) = 200w - 2w^2$. Step 3: $A' = 200 - 4w = 0$ gives $w = 50$. Step 4: $A = 50(100) = 5000$. Final answer: $5000$ sq ft.",
    difficulty: "medium",
  },
  {
    id: "test-applications-12",
    topicId: "applications",
    prompt: "The acceleration of a particle is $a(t) = 6t$. If $v(0) = 2$ and $s(0) = 0$, find $s(2)$.",
    type: "numeric",
    answer: "12",
    explanation: "Step 1: $v(t) = \\int 6t dt = 3t^2 + C$. With $v(0) = 2$: $v(t) = 3t^2 + 2$. Step 2: $s(t) = \\int (3t^2 + 2)dt = t^3 + 2t + C$. With $s(0) = 0$: $s(t) = t^3 + 2t$. Step 3: $s(2) = 8 + 4 = 12$. Final answer: $12$.",
    difficulty: "medium",
  },
  {
    id: "test-applications-13",
    topicId: "applications",
    prompt: "Find the local minimum value of $f(x) = x + \\frac{4}{x}$ for $x > 0$",
    type: "numeric",
    answer: "4",
    explanation: "Step 1: $f'(x) = 1 - \\frac{4}{x^2} = 0$ gives $x^2 = 4$, so $x = 2$ (positive). Step 2: $f''(x) = \\frac{8}{x^3} > 0$ for $x > 0$, confirming minimum. Step 3: $f(2) = 2 + 2 = 4$. Final answer: $4$.",
    difficulty: "medium",
  },
  {
    id: "test-applications-14",
    topicId: "applications",
    prompt: "A spherical balloon's volume increases at 4π cm³/s. How fast is the radius increasing when $r = 2$ cm?",
    type: "numeric",
    answer: "1/4 cm/s",
    explanation: "Step 1: $V = \\frac{4}{3}\\pi r^3$. Step 2: $\\frac{dV}{dt} = 4\\pi r^2 \\frac{dr}{dt}$. Step 3: At $r = 2$: $4\\pi = 4\\pi(4)\\frac{dr}{dt}$. Step 4: $\\frac{dr}{dt} = \\frac{1}{4}$. Final answer: $\\frac{1}{4}$ cm/s.",
    difficulty: "medium",
  },
  {
    id: "test-applications-15",
    topicId: "applications",
    prompt: "Does $f(x) = x^3$ have any local extrema?",
    type: "mcq",
    answer: "No local extrema",
    choices: ["Local min at x = 0", "Local max at x = 0", "Both min and max at x = 0", "No local extrema"],
    explanation: "Step 1: $f'(x) = 3x^2 = 0$ at $x = 0$. Step 2: $f''(0) = 0$ (inconclusive). Step 3: $f'(x) \\geq 0$ for all $x$, so $f$ is always increasing. No extrema. Final answer: No local extrema.",
    difficulty: "easy",
  },
  {
    id: "test-applications-16",
    topicId: "applications",
    prompt: "Find the horizontal asymptote of $f(x) = \\frac{2x^2 + 1}{x^2 - 3}$",
    type: "numeric",
    answer: "y = 2",
    explanation: "Step 1: Degrees of numerator and denominator are equal. Step 2: Horizontal asymptote is ratio of leading coefficients: $\\frac{2}{1} = 2$. Final answer: $y = 2$.",
    difficulty: "easy",
  },
  {
    id: "test-applications-17",
    topicId: "applications",
    prompt: "The marginal cost is $C'(x) = 0.002x + 8$. Find the cost to produce units 101 to 200.",
    type: "numeric",
    answer: "830.1",
    explanation: "Step 1: Cost is $\\int_{100}^{200}(0.002x + 8)dx$. Step 2: $= [0.001x^2 + 8x]_{100}^{200}$. Step 3: $= (40 + 1600) - (10 + 800) = 1640 - 810 = 830$. Final answer: $830.1$.",
    difficulty: "hard",
  },
  {
    id: "test-applications-18",
    topicId: "applications",
    prompt: "Two cars start from the same point. Car A goes north at 60 mph, Car B goes east at 80 mph. How fast is the distance between them increasing after 2 hours?",
    type: "numeric",
    answer: "100 mph",
    explanation: "Step 1: After $t$ hours: $x = 80t$, $y = 60t$, $d = \\sqrt{x^2+y^2} = 100t$. Step 2: $\\frac{dd}{dt} = 100$ mph (constant). Final answer: $100$ mph.",
    difficulty: "medium",
  },
  {
    id: "test-applications-19",
    topicId: "applications",
    prompt: "For $f(x) = xe^{-x}$, find the value of $x$ where $f$ has a maximum",
    type: "numeric",
    answer: "1",
    explanation: "Step 1: $f'(x) = e^{-x} - xe^{-x} = e^{-x}(1-x)$. Step 2: $f'(x) = 0$ when $x = 1$. Step 3: $f''(x) = e^{-x}(x-2)$, $f''(1) = e^{-1}(-1) < 0$, confirming max. Final answer: $x = 1$.",
    difficulty: "medium",
  },
  {
    id: "test-applications-20",
    topicId: "applications",
    prompt: "The Mean Value Theorem guarantees a $c$ in $(0, 2)$ for $f(x) = x^3$ such that $f'(c) = ?$",
    type: "numeric",
    answer: "4",
    explanation: "Step 1: MVT: $f'(c) = \\frac{f(2) - f(0)}{2 - 0} = \\frac{8 - 0}{2} = 4$. Final answer: $4$.",
    difficulty: "easy",
  },
];

// ============================================================================
// SERIES TEST QUESTIONS
// ============================================================================
const seriesTestQuestions: TestQuestion[] = [
  {
    id: "test-series-1",
    topicId: "series",
    prompt: "Find the sum: $\\sum_{n=1}^{\\infty} \\frac{1}{2^n}$",
    type: "numeric",
    answer: "1",
    explanation: "Step 1: Geometric series with $a = 1/2$, $r = 1/2$. Step 2: Sum = $\\frac{a}{1-r} = \\frac{1/2}{1/2} = 1$. Final answer: $1$.",
    difficulty: "easy",
  },
  {
    id: "test-series-2",
    topicId: "series",
    prompt: "Does $\\sum_{n=1}^{\\infty} \\frac{n}{n^2 + 1}$ converge or diverge?",
    type: "mcq",
    answer: "Diverges",
    choices: ["Converges", "Diverges"],
    explanation: "Step 1: Compare to $\\frac{n}{n^2} = \\frac{1}{n}$. Step 2: $\\sum \\frac{1}{n}$ (harmonic) diverges. Step 3: By limit comparison, this also diverges. Final answer: Diverges.",
    difficulty: "medium",
  },
  {
    id: "test-series-3",
    topicId: "series",
    prompt: "Find the radius of convergence of $\\sum_{n=0}^{\\infty} \\frac{x^n}{n!}$",
    type: "numeric",
    answer: "∞",
    explanation: "Step 1: Ratio test: $\\lim_{n\\to\\infty} \\left|\\frac{x^{n+1}/(n+1)!}{x^n/n!}\\right| = \\lim |\\frac{x}{n+1}| = 0$ for all $x$. Step 2: Converges for all $x$. Final answer: $R = \\infty$.",
    difficulty: "medium",
  },
  {
    id: "test-series-4",
    topicId: "series",
    prompt: "Find the Maclaurin series for $\\cos(x)$ up to $x^4$",
    type: "numeric",
    answer: "1 - x^2/2 + x^4/24",
    explanation: "Step 1: $\\cos(x) = \\sum_{n=0}^{\\infty} \\frac{(-1)^n x^{2n}}{(2n)!}$. Step 2: First terms: $1 - \\frac{x^2}{2!} + \\frac{x^4}{4!} = 1 - \\frac{x^2}{2} + \\frac{x^4}{24}$. Final answer: $1 - \\frac{x^2}{2} + \\frac{x^4}{24}$.",
    difficulty: "medium",
  },
  {
    id: "test-series-5",
    topicId: "series",
    prompt: "Test for convergence: $\\sum_{n=1}^{\\infty} \\frac{(-1)^n}{n}$",
    type: "mcq",
    answer: "Conditionally convergent",
    choices: ["Absolutely convergent", "Conditionally convergent", "Divergent"],
    explanation: "Step 1: Alternating series test: $1/n$ decreases to 0, so converges. Step 2: But $\\sum |(-1)^n/n| = \\sum 1/n$ diverges. Step 3: Conditionally convergent. Final answer: Conditionally convergent.",
    difficulty: "medium",
  },
  {
    id: "test-series-6",
    topicId: "series",
    prompt: "Find the sum: $\\sum_{n=0}^{\\infty} \\frac{(-1)^n}{2n+1}$ (hint: this is $\\arctan(1)$)",
    type: "numeric",
    answer: "π/4",
    explanation: "Step 1: The series $\\sum_{n=0}^{\\infty} \\frac{(-1)^n x^{2n+1}}{2n+1}$ represents $\\arctan(x)$. Step 2: At $x = 1$: $\\arctan(1) = \\frac{\\pi}{4}$. Final answer: $\\frac{\\pi}{4}$.",
    difficulty: "hard",
  },
  {
    id: "test-series-7",
    topicId: "series",
    prompt: "Does $\\sum_{n=2}^{\\infty} \\frac{1}{n \\ln(n)}$ converge?",
    type: "mcq",
    answer: "Diverges",
    choices: ["Converges", "Diverges"],
    explanation: "Step 1: Integral test: $\\int_2^{\\infty} \\frac{1}{x \\ln(x)}dx$. Step 2: Let $u = \\ln(x)$: $\\int \\frac{du}{u} = \\ln(u)$ diverges. Final answer: Diverges.",
    difficulty: "hard",
  },
  {
    id: "test-series-8",
    topicId: "series",
    prompt: "Find the first 3 nonzero terms of the Taylor series for $e^x \\sin(x)$ at $x = 0$",
    type: "numeric",
    answer: "x + x^2 + x^3/3",
    explanation: "Step 1: $e^x = 1 + x + \\frac{x^2}{2} + \\frac{x^3}{6} + ...$, $\\sin(x) = x - \\frac{x^3}{6} + ...$. Step 2: Multiply and collect terms: $x + x^2 + \\frac{x^3}{3} + ...$. Final answer: $x + x^2 + \\frac{x^3}{3}$.",
    difficulty: "hard",
  },
  {
    id: "test-series-9",
    topicId: "series",
    prompt: "Find the interval of convergence of $\\sum_{n=1}^{\\infty} \\frac{x^n}{n}$",
    type: "numeric",
    answer: "[-1, 1)",
    explanation: "Step 1: Ratio test: $\\lim |\\frac{x^{n+1}/(n+1)}{x^n/n}| = |x|$. Converges for $|x| < 1$. Step 2: At $x = 1$: $\\sum 1/n$ diverges. At $x = -1$: $\\sum (-1)^n/n$ converges. Final answer: $[-1, 1)$.",
    difficulty: "hard",
  },
  {
    id: "test-series-10",
    topicId: "series",
    prompt: "Does $\\sum_{n=1}^{\\infty} \\frac{n!}{n^n}$ converge?",
    type: "mcq",
    answer: "Converges",
    choices: ["Converges", "Diverges"],
    explanation: "Step 1: Ratio test: $\\lim \\frac{(n+1)!/n!} \\cdot \\frac{n^n}{(n+1)^{n+1}} = \\lim \\frac{n^n}{(n+1)^n} = \\frac{1}{e} < 1$. Final answer: Converges.",
    difficulty: "hard",
  },
  {
    id: "test-series-11",
    topicId: "series",
    prompt: "Find the sum: $\\sum_{n=0}^{\\infty} \\frac{3^n}{4^n}$",
    type: "numeric",
    answer: "4",
    explanation: "Step 1: This is $\\sum (3/4)^n$ with $a = 1$, $r = 3/4$. Step 2: Sum = $\\frac{1}{1 - 3/4} = 4$. Final answer: $4$.",
    difficulty: "easy",
  },
  {
    id: "test-series-12",
    topicId: "series",
    prompt: "Find $\\lim_{n \\to \\infty} \\sqrt[n]{n}$",
    type: "numeric",
    answer: "1",
    explanation: "Step 1: Let $L = \\lim n^{1/n}$. Take $\\ln$: $\\lim \\frac{\\ln(n)}{n} = 0$ by L'Hôpital. Step 2: So $L = e^0 = 1$. Final answer: $1$.",
    difficulty: "medium",
  },
  {
    id: "test-series-13",
    topicId: "series",
    prompt: "Test: $\\sum_{n=1}^{\\infty} \\frac{1}{n^{3/2}}$",
    type: "mcq",
    answer: "Converges",
    choices: ["Converges", "Diverges"],
    explanation: "Step 1: This is a p-series with $p = 3/2 > 1$. Step 2: p-series converges when $p > 1$. Final answer: Converges.",
    difficulty: "easy",
  },
  {
    id: "test-series-14",
    topicId: "series",
    prompt: "Find the Taylor polynomial $P_3(x)$ for $\\ln(1+x)$ centered at 0",
    type: "numeric",
    answer: "x - x^2/2 + x^3/3",
    explanation: "Step 1: $\\ln(1+x) = \\sum_{n=1}^{\\infty} \\frac{(-1)^{n+1}x^n}{n}$. Step 2: First 3 terms: $x - \\frac{x^2}{2} + \\frac{x^3}{3}$. Final answer: $x - \\frac{x^2}{2} + \\frac{x^3}{3}$.",
    difficulty: "medium",
  },
  {
    id: "test-series-15",
    topicId: "series",
    prompt: "Does $\\sum_{n=1}^{\\infty} \\frac{\\cos(n\\pi)}{n^2}$ converge absolutely?",
    type: "mcq",
    answer: "Yes, absolutely convergent",
    choices: ["Yes, absolutely convergent", "Conditionally convergent", "Divergent"],
    explanation: "Step 1: $\\cos(n\\pi) = (-1)^n$. Step 2: $\\sum |(-1)^n/n^2| = \\sum 1/n^2$ converges (p-series, $p=2>1$). Final answer: Yes, absolutely convergent.",
    difficulty: "medium",
  },
  {
    id: "test-series-16",
    topicId: "series",
    prompt: "Find the coefficient of $x^3$ in the Maclaurin series for $\\frac{1}{1-x}$",
    type: "numeric",
    answer: "1",
    explanation: "Step 1: $\\frac{1}{1-x} = \\sum_{n=0}^{\\infty} x^n = 1 + x + x^2 + x^3 + ...$. Step 2: Coefficient of $x^3$ is $1$. Final answer: $1$.",
    difficulty: "easy",
  },
  {
    id: "test-series-17",
    topicId: "series",
    prompt: "Use ratio test on $\\sum_{n=1}^{\\infty} \\frac{2^n}{n^2}$",
    type: "mcq",
    answer: "Diverges",
    choices: ["Converges", "Diverges", "Inconclusive"],
    explanation: "Step 1: $\\lim \\frac{2^{n+1}/(n+1)^2}{2^n/n^2} = 2 \\cdot \\lim \\frac{n^2}{(n+1)^2} = 2 > 1$. Final answer: Diverges.",
    difficulty: "medium",
  },
  {
    id: "test-series-18",
    topicId: "series",
    prompt: "Find the sum: $1 - \\frac{1}{2} + \\frac{1}{4} - \\frac{1}{8} + ...$",
    type: "numeric",
    answer: "2/3",
    explanation: "Step 1: Geometric with $a = 1$, $r = -1/2$. Step 2: Sum = $\\frac{1}{1-(-1/2)} = \\frac{1}{3/2} = \\frac{2}{3}$. Final answer: $\\frac{2}{3}$.",
    difficulty: "easy",
  },
  {
    id: "test-series-19",
    topicId: "series",
    prompt: "Find $\\lim_{n \\to \\infty} \\frac{n^{100}}{2^n}$",
    type: "numeric",
    answer: "0",
    explanation: "Step 1: Exponential growth dominates polynomial. Step 2: By repeated L'Hôpital or ratio test logic, limit is $0$. Final answer: $0$.",
    difficulty: "easy",
  },
  {
    id: "test-series-20",
    topicId: "series",
    prompt: "Express $0.\\overline{36}$ as a fraction",
    type: "numeric",
    answer: "4/11",
    explanation: "Step 1: $0.\\overline{36} = 0.36 + 0.0036 + ... = \\frac{36}{100}(1 + \\frac{1}{100} + ...)$. Step 2: $= \\frac{36/100}{1 - 1/100} = \\frac{36}{99} = \\frac{4}{11}$. Final answer: $\\frac{4}{11}$.",
    difficulty: "medium",
  },
];

// ============================================================================
// DIFFERENTIAL EQUATIONS TEST QUESTIONS
// ============================================================================
const diffEqTestQuestions: TestQuestion[] = [
  {
    id: "test-diffeq-1",
    topicId: "differential-equations",
    prompt: "Solve: $\\frac{dy}{dx} = \\frac{y}{x}$ with $y(1) = 2$",
    type: "numeric",
    answer: "y = 2x",
    explanation: "Step 1: Separate: $\\frac{dy}{y} = \\frac{dx}{x}$. Step 2: Integrate: $\\ln|y| = \\ln|x| + C$. Step 3: $y = Ax$. With $y(1) = 2$: $A = 2$. Final answer: $y = 2x$.",
    difficulty: "easy",
  },
  {
    id: "test-diffeq-2",
    topicId: "differential-equations",
    prompt: "Solve: $\\frac{dy}{dx} + 2y = 4$",
    type: "numeric",
    answer: "y = 2 + Ce^{-2x}",
    explanation: "Step 1: Integrating factor: $\\mu = e^{2x}$. Step 2: $(e^{2x}y)' = 4e^{2x}$. Step 3: $e^{2x}y = 2e^{2x} + C$. Step 4: $y = 2 + Ce^{-2x}$. Final answer: $y = 2 + Ce^{-2x}$.",
    difficulty: "medium",
  },
  {
    id: "test-diffeq-3",
    topicId: "differential-equations",
    prompt: "The general solution of $y'' - 4y = 0$ is:",
    type: "numeric",
    answer: "y = C₁e^{2x} + C₂e^{-2x}",
    explanation: "Step 1: Characteristic equation: $r^2 - 4 = 0$. Step 2: Roots: $r = \\pm 2$. Step 3: General solution: $y = C_1e^{2x} + C_2e^{-2x}$. Final answer: $y = C_1e^{2x} + C_2e^{-2x}$.",
    difficulty: "medium",
  },
  {
    id: "test-diffeq-4",
    topicId: "differential-equations",
    prompt: "Solve: $\\frac{dy}{dx} = xy$ with $y(0) = 3$",
    type: "numeric",
    answer: "y = 3e^{x²/2}",
    explanation: "Step 1: Separate: $\\frac{dy}{y} = x dx$. Step 2: $\\ln|y| = \\frac{x^2}{2} + C$. Step 3: $y = Ae^{x^2/2}$. With $y(0) = 3$: $A = 3$. Final answer: $y = 3e^{x^2/2}$.",
    difficulty: "medium",
  },
  {
    id: "test-diffeq-5",
    topicId: "differential-equations",
    prompt: "Find the particular solution type for $y'' + y = \\sin(x)$",
    type: "mcq",
    answer: "y_p = Ax cos(x) + Bx sin(x)",
    choices: ["y_p = A cos(x) + B sin(x)", "y_p = Ax cos(x) + Bx sin(x)", "y_p = Ax² cos(x)", "y_p = e^x"],
    explanation: "Step 1: Homogeneous solution is $y_h = C_1\\cos(x) + C_2\\sin(x)$. Step 2: Since RHS is a solution of homogeneous, multiply by $x$. Final answer: $y_p = Ax\\cos(x) + Bx\\sin(x)$.",
    difficulty: "hard",
  },
  {
    id: "test-diffeq-6",
    topicId: "differential-equations",
    prompt: "Solve: $\\frac{dy}{dx} = e^{x+y}$",
    type: "numeric",
    answer: "y = -ln(C - e^x)",
    explanation: "Step 1: Rewrite as $e^{-y}dy = e^x dx$. Step 2: Integrate: $-e^{-y} = e^x + C_1$. Step 3: $e^{-y} = C - e^x$, so $y = -\\ln(C - e^x)$. Final answer: $y = -\\ln(C - e^x)$.",
    difficulty: "hard",
  },
  {
    id: "test-diffeq-7",
    topicId: "differential-equations",
    prompt: "The population $P(t)$ satisfies $\\frac{dP}{dt} = 0.05P$. If $P(0) = 1000$, find $P(10)$.",
    type: "numeric",
    answer: "1000e^{0.5}",
    explanation: "Step 1: Solution: $P = P_0 e^{0.05t}$. Step 2: $P(10) = 1000e^{0.5} \\approx 1649$. Final answer: $1000e^{0.5}$.",
    difficulty: "easy",
  },
  {
    id: "test-diffeq-8",
    topicId: "differential-equations",
    prompt: "Solve: $y'' + 4y' + 4y = 0$",
    type: "numeric",
    answer: "y = (C₁ + C₂x)e^{-2x}",
    explanation: "Step 1: Characteristic: $r^2 + 4r + 4 = (r+2)^2 = 0$. Step 2: Repeated root $r = -2$. Step 3: Solution: $y = (C_1 + C_2 x)e^{-2x}$. Final answer: $y = (C_1 + C_2 x)e^{-2x}$.",
    difficulty: "medium",
  },
  {
    id: "test-diffeq-9",
    topicId: "differential-equations",
    prompt: "Solve: $\\frac{dy}{dx} = \\frac{x^2}{y}$",
    type: "numeric",
    answer: "y = ±sqrt((2x³)/3 + C)",
    explanation: "Step 1: Separate: $y dy = x^2 dx$. Step 2: Integrate: $\\frac{y^2}{2} = \\frac{x^3}{3} + C$. Step 3: $y = \\pm\\sqrt{\\frac{2x^3}{3} + C}$. Final answer: $y = \\pm\\sqrt{\\frac{2x^3}{3} + C}$.",
    difficulty: "easy",
  },
  {
    id: "test-diffeq-10",
    topicId: "differential-equations",
    prompt: "Solve: $y'' + 9y = 0$",
    type: "numeric",
    answer: "y = C₁cos(3x) + C₂sin(3x)",
    explanation: "Step 1: Characteristic: $r^2 + 9 = 0$, $r = \\pm 3i$. Step 2: Complex roots give oscillatory solution. Final answer: $y = C_1\\cos(3x) + C_2\\sin(3x)$.",
    difficulty: "easy",
  },
  {
    id: "test-diffeq-11",
    topicId: "differential-equations",
    prompt: "A substance decays with half-life 5 years. What fraction remains after 15 years?",
    type: "numeric",
    answer: "1/8",
    explanation: "Step 1: After each half-life, half remains. Step 2: 15 years = 3 half-lives. Step 3: $(1/2)^3 = 1/8$. Final answer: $\\frac{1}{8}$.",
    difficulty: "easy",
  },
  {
    id: "test-diffeq-12",
    topicId: "differential-equations",
    prompt: "Solve: $\\frac{dy}{dx} = \\frac{1+y^2}{1+x^2}$",
    type: "numeric",
    answer: "arctan(y) = arctan(x) + C",
    explanation: "Step 1: Separate: $\\frac{dy}{1+y^2} = \\frac{dx}{1+x^2}$. Step 2: Integrate: $\\arctan(y) = \\arctan(x) + C$. Final answer: $\\arctan(y) = \\arctan(x) + C$.",
    difficulty: "medium",
  },
  {
    id: "test-diffeq-13",
    topicId: "differential-equations",
    prompt: "Find the integrating factor for $\\frac{dy}{dx} - \\frac{y}{x} = x^2$",
    type: "numeric",
    answer: "1/x",
    explanation: "Step 1: Standard form: $y' + P(x)y = Q(x)$ with $P(x) = -1/x$. Step 2: $\\mu = e^{\\int -1/x dx} = e^{-\\ln|x|} = 1/x$. Final answer: $\\frac{1}{x}$.",
    difficulty: "medium",
  },
  {
    id: "test-diffeq-14",
    topicId: "differential-equations",
    prompt: "Solve: $y' = y^2$ with $y(0) = 1$",
    type: "numeric",
    answer: "y = 1/(1-x)",
    explanation: "Step 1: Separate: $y^{-2}dy = dx$. Step 2: $-y^{-1} = x + C$, so $y = -1/(x+C)$. Step 3: $y(0) = 1 \\Rightarrow C = -1$. Final answer: $y = \\frac{1}{1-x}$.",
    difficulty: "medium",
  },
  {
    id: "test-diffeq-15",
    topicId: "differential-equations",
    prompt: "The equilibrium solutions of $\\frac{dy}{dt} = y(1-y)$ are:",
    type: "numeric",
    answer: "y = 0, y = 1",
    explanation: "Step 1: Equilibrium when $\\frac{dy}{dt} = 0$. Step 2: $y(1-y) = 0 \\Rightarrow y = 0$ or $y = 1$. Final answer: $y = 0, y = 1$.",
    difficulty: "easy",
  },
  {
    id: "test-diffeq-16",
    topicId: "differential-equations",
    prompt: "Solve: $y'' - 2y' + 5y = 0$",
    type: "numeric",
    answer: "y = e^x(C₁cos(2x) + C₂sin(2x))",
    explanation: "Step 1: Characteristic: $r^2 - 2r + 5 = 0$. Step 2: $r = \\frac{2 \\pm \\sqrt{-16}}{2} = 1 \\pm 2i$. Step 3: Solution: $y = e^x(C_1\\cos(2x) + C_2\\sin(2x))$. Final answer: $y = e^x(C_1\\cos(2x) + C_2\\sin(2x))$.",
    difficulty: "hard",
  },
  {
    id: "test-diffeq-17",
    topicId: "differential-equations",
    prompt: "Newton's Law of Cooling: $\\frac{dT}{dt} = -k(T - 20)$. If $T(0) = 100$ and $T(10) = 60$, find $k$.",
    type: "numeric",
    answer: "ln(2)/10",
    explanation: "Step 1: Solution: $T = 20 + 80e^{-kt}$. Step 2: $T(10) = 60 \\Rightarrow 40 = 80e^{-10k}$. Step 3: $e^{-10k} = 1/2$, so $k = \\ln(2)/10$. Final answer: $k = \\frac{\\ln(2)}{10}$.",
    difficulty: "hard",
  },
  {
    id: "test-diffeq-18",
    topicId: "differential-equations",
    prompt: "Solve: $xy' + y = x^2$",
    type: "numeric",
    answer: "y = x²/3 + C/x",
    explanation: "Step 1: Divide by $x$: $y' + \\frac{y}{x} = x$. Step 2: Integrating factor: $\\mu = x$. Step 3: $(xy)' = x^2$, so $xy = \\frac{x^3}{3} + C$. Step 4: $y = \\frac{x^2}{3} + \\frac{C}{x}$. Final answer: $y = \\frac{x^2}{3} + \\frac{C}{x}$.",
    difficulty: "medium",
  },
  {
    id: "test-diffeq-19",
    topicId: "differential-equations",
    prompt: "Is $y = e^{-x}$ a solution of $y'' + 2y' + y = 0$?",
    type: "mcq",
    answer: "Yes",
    choices: ["Yes", "No"],
    explanation: "Step 1: $y' = -e^{-x}$, $y'' = e^{-x}$. Step 2: Substitute: $e^{-x} + 2(-e^{-x}) + e^{-x} = 0$. ✓ Final answer: Yes.",
    difficulty: "easy",
  },
  {
    id: "test-diffeq-20",
    topicId: "differential-equations",
    prompt: "Solve: $y' = \\cos(x)\\cos(y)$",
    type: "numeric",
    answer: "ln|sec(y) + tan(y)| = sin(x) + C",
    explanation: "Step 1: Separate: $\\sec(y)dy = \\cos(x)dx$. Step 2: Integrate: $\\ln|\\sec(y) + \\tan(y)| = \\sin(x) + C$. Final answer: $\\ln|\\sec(y) + \\tan(y)| = \\sin(x) + C$.",
    difficulty: "hard",
  },
];

// ============================================================================
// EXPORT ALL TEST QUESTIONS
// ============================================================================
export const testQuestions: TestQuestion[] = [
  ...limitsTestQuestions,
  ...derivativesTestQuestions,
  ...integralsTestQuestions,
  ...applicationsTestQuestions,
  ...seriesTestQuestions,
  ...diffEqTestQuestions,
];

export function getTestQuestionsForTopic(topicId: string): TestQuestion[] {
  return testQuestions.filter((q) => q.topicId === topicId);
}
