import type { Problem } from "../shared-types";

const p = (problem: Problem) => problem;

export const matrixProblems: Problem[] = [
  // --- Easy (14) ---
  p({ id: "mat-operations-1", topicId: "matrices", section: "operations", type: "numeric", difficulty: "easy",
    prompt: "$A = \\begin{pmatrix}1&2\\\\3&4\\end{pmatrix}$, $B = \\begin{pmatrix}5&6\\\\7&8\\end{pmatrix}$. What is the $(1,2)$ entry of $A+B$?",
    answer: "8",
    explanation: "Step 1: $(A+B)_{12}=2+6=8$. Final answer: $8$." }),
  p({ id: "mat-operations-2", topicId: "matrices", section: "operations", type: "numeric", difficulty: "easy",
    prompt: "What is the $(2,1)$ entry of $A^T$ for $A=\\begin{pmatrix}1&4\\\\2&5\\\\3&6\\end{pmatrix}$?",
    answer: "4",
    explanation: "Step 1: $(A^T)_{21}=A_{12}=4$. Final answer: $4$." }),
  p({ id: "mat-operations-3", topicId: "matrices", section: "operations", type: "numeric", difficulty: "easy",
    prompt: "Compute $3A$ for $A=\\begin{pmatrix}2&-1\\\\0&4\\end{pmatrix}$. What is the $(2,2)$ entry?",
    answer: "12",
    explanation: "Step 1: $(3A)_{22}=3(4)=12$. Final answer: $12$." }),
  p({ id: "mat-operations-4", topicId: "matrices", section: "operations", type: "mcq", difficulty: "easy",
    prompt: "A matrix $A$ is symmetric if:",
    answer: "$A = A^T$",
    choices: ["$A = -A^T$", "$A = A^T$", "$A = A^{-1}$", "$A$ has all positive entries."],
    explanation: "Step 1: Symmetric means $A_{ij}=A_{ji}$ for all $i,j$, i.e., $A=A^T$. Final answer: $A = A^T$." }),
  p({ id: "mat-operations-5", topicId: "matrices", section: "operations", type: "numeric", difficulty: "easy",
    prompt: "What is the $(1,1)$ entry of $A-B$ for $A=\\begin{pmatrix}7&2\\\\3&1\\end{pmatrix}$, $B=\\begin{pmatrix}4&2\\\\1&0\\end{pmatrix}$?",
    answer: "3",
    explanation: "Step 1: $(A-B)_{11}=7-4=3$. Final answer: $3$." }),
  p({ id: "mat-multiplication-1", topicId: "matrices", section: "multiplication", type: "numeric", difficulty: "easy",
    prompt: "$A=\\begin{pmatrix}1&2\\\\3&4\\end{pmatrix}$, $B=\\begin{pmatrix}2&0\\\\1&3\\end{pmatrix}$. What is $(AB)_{11}$?",
    answer: "4",
    explanation: "Step 1: $(AB)_{11}=(1)(2)+(2)(1)=2+2=4$. Final answer: $4$." }),
  p({ id: "mat-multiplication-2", topicId: "matrices", section: "multiplication", type: "numeric", difficulty: "easy",
    prompt: "For $A=\\begin{pmatrix}2&0\\\\0&3\\end{pmatrix}$ and $B=\\begin{pmatrix}1&5\\\\2&4\\end{pmatrix}$, what is $(AB)_{12}$?",
    answer: "10",
    explanation: "Step 1: $(AB)_{12}=(2)(5)+(0)(4)=10$. Final answer: $10$." }),
  p({ id: "mat-multiplication-3", topicId: "matrices", section: "multiplication", type: "mcq", difficulty: "easy",
    prompt: "In general, is matrix multiplication commutative ($AB = BA$)?",
    answer: "No, in general $AB \\neq BA$.",
    choices: ["Yes, always.", "No, in general $AB \\neq BA$.", "Yes, when both matrices are square.", "Yes, when both are $2\\times 2$."],
    explanation: "Step 1: Matrix multiplication is NOT commutative in general. A simple $2\\times 2$ counterexample shows $AB\\neq BA$. Final answer: No, in general $AB \\neq BA$." }),
  p({ id: "mat-inverse-1", topicId: "matrices", section: "inverse", type: "mcq", difficulty: "easy",
    prompt: "A matrix $A$ is invertible if and only if:",
    answer: "$\\det(A) \\neq 0$",
    choices: ["$\\det(A) = 0$", "$\\det(A) \\neq 0$", "$A$ is symmetric.", "$A$ is square."],
    explanation: "Step 1: A square matrix is invertible iff $\\det(A)\\neq 0$. When $\\det(A)=0$ the matrix is singular. Final answer: $\\det(A) \\neq 0$." }),
  p({ id: "mat-inverse-2", topicId: "matrices", section: "inverse", type: "numeric", difficulty: "easy",
    prompt: "For $A=\\begin{pmatrix}2&0\\\\0&5\\end{pmatrix}$, what is the $(1,1)$ entry of $A^{-1}$?",
    answer: "0.5",
    explanation: "Step 1: For a diagonal matrix, $(A^{-1})_{ii}=1/A_{ii}$. Step 2: $(A^{-1})_{11}=1/2=0.5$. Final answer: $0.5$." }),
  p({ id: "mat-operations-6", topicId: "matrices", section: "operations", type: "numeric", difficulty: "easy",
    prompt: "What is the size (number of entries) of the product $AB$ when $A$ is $3\\times 4$ and $B$ is $4\\times 2$?",
    answer: "6",
    explanation: "Step 1: $AB$ is $3\\times 2$, which has $3\\times 2=6$ entries. Final answer: $6$." }),
  p({ id: "mat-multiplication-4", topicId: "matrices", section: "multiplication", type: "numeric", difficulty: "easy",
    prompt: "Compute $AI$ where $A=\\begin{pmatrix}3&7\\\\1&2\\end{pmatrix}$ and $I$ is the $2\\times 2$ identity. What is the $(1,2)$ entry of the result?",
    answer: "7",
    explanation: "Step 1: $AI=A$ for any matrix $A$. Step 2: $(AI)_{12}=A_{12}=7$. Final answer: $7$." }),
  p({ id: "mat-inverse-3", topicId: "matrices", section: "inverse", type: "mcq", difficulty: "easy",
    prompt: "If $A$ and $B$ are invertible matrices of the same size, then $(AB)^{-1}=$",
    answer: "$B^{-1}A^{-1}$",
    choices: ["$A^{-1}B^{-1}$", "$B^{-1}A^{-1}$", "$(A^{-1})(B^{-1})^T$", "$(BA)^{-1}$"],
    explanation: "Step 1: Reverse-order rule: $(AB)^{-1}=B^{-1}A^{-1}$. Verify: $(AB)(B^{-1}A^{-1})=A(BB^{-1})A^{-1}=AIA^{-1}=I$. Final answer: $B^{-1}A^{-1}$." }),
  p({ id: "mat-operations-7", topicId: "matrices", section: "operations", type: "numeric", difficulty: "easy",
    prompt: "What is the trace of $A=\\begin{pmatrix}5&2\\\\-1&3\\end{pmatrix}$?",
    answer: "8",
    explanation: "Step 1: Trace $=$ sum of diagonal entries $=5+3=8$. Final answer: $8$." }),

  // --- Medium (16) ---
  p({ id: "mat-multiplication-5", topicId: "matrices", section: "multiplication", type: "numeric", difficulty: "medium",
    prompt: "$A=\\begin{pmatrix}1&2\\\\3&4\\end{pmatrix}$, $B=\\begin{pmatrix}2&0\\\\1&3\\end{pmatrix}$. What is $(AB)_{22}$?",
    answer: "12",
    explanation: "Step 1: $(AB)_{22}=(3)(0)+(4)(3)=0+12=12$. Final answer: $12$." }),
  p({ id: "mat-inverse-4", topicId: "matrices", section: "inverse", type: "numeric", difficulty: "medium",
    prompt: "Find $\\det(A^{-1})$ if $\\det(A)=5$.",
    answer: "0.2",
    explanation: "Step 1: $\\det(A^{-1})=1/\\det(A)=1/5=0.2$. Final answer: $0.2$." }),
  p({ id: "mat-inverse-5", topicId: "matrices", section: "inverse", type: "numeric", difficulty: "medium",
    prompt: "Compute $A^{-1}$ for $A=\\begin{pmatrix}3&1\\\\5&2\\end{pmatrix}$. What is the $(1,1)$ entry?",
    answer: "2",
    explanation: "Step 1: $\\det(A)=6-5=1$. Step 2: $A^{-1}=\\frac{1}{1}\\begin{pmatrix}2&-1\\\\-5&3\\end{pmatrix}$. Step 3: $(A^{-1})_{11}=2$. Final answer: $2$." }),
  p({ id: "mat-multiplication-6", topicId: "matrices", section: "multiplication", type: "numeric", difficulty: "medium",
    prompt: "Compute $A^2$ for $A=\\begin{pmatrix}1&1\\\\0&1\\end{pmatrix}$. What is the $(1,2)$ entry of $A^2$?",
    answer: "2",
    explanation: "Step 1: $A^2=AA=\\begin{pmatrix}1&1\\\\0&1\\end{pmatrix}\\begin{pmatrix}1&1\\\\0&1\\end{pmatrix}$. Step 2: $(A^2)_{12}=(1)(1)+(1)(1)=2$. Final answer: $2$." }),
  p({ id: "mat-operations-8", topicId: "matrices", section: "operations", type: "mcq", difficulty: "medium",
    prompt: "Which of the following is always true for square matrices $A$ and $B$?",
    answer: "$(A+B)^T = A^T + B^T$",
    choices: ["$(AB)^T = A^T B^T$", "$(A+B)^T = A^T + B^T$", "$AB = BA$", "$(A^T)^T = -A$"],
    explanation: "Step 1: Transpose distributes over addition: $(A+B)^T=A^T+B^T$. Note $(AB)^T=B^TA^T$ (reversed order). Final answer: $(A+B)^T = A^T + B^T$." }),
  p({ id: "mat-inverse-6", topicId: "matrices", section: "inverse", type: "numeric", difficulty: "medium",
    prompt: "For $A=\\begin{pmatrix}4&7\\\\2&6\\end{pmatrix}$, find $\\det(A)$.",
    answer: "10",
    explanation: "Step 1: $\\det(A)=(4)(6)-(7)(2)=24-14=10$. Final answer: $10$." }),
  p({ id: "mat-multiplication-7", topicId: "matrices", section: "multiplication", type: "numeric", difficulty: "medium",
    prompt: "For $A=\\begin{pmatrix}2&1\\\\4&3\\end{pmatrix}$, solve $A\\mathbf{x}=\\begin{pmatrix}5\\\\11\\end{pmatrix}$. What is $x_1$?",
    answer: "2",
    explanation: "Step 1: $A^{-1}=\\frac{1}{2}\\begin{pmatrix}3&-1\\\\-4&2\\end{pmatrix}$. Step 2: $\\mathbf{x}=A^{-1}\\mathbf{b}=\\frac{1}{2}\\begin{pmatrix}15-11\\\\-20+22\\end{pmatrix}=\\frac{1}{2}\\begin{pmatrix}4\\\\2\\end{pmatrix}=\\begin{pmatrix}2\\\\1\\end{pmatrix}$. Step 3: $x_1=2$. Final answer: $2$." }),
  p({ id: "mat-operations-9", topicId: "matrices", section: "operations", type: "mcq", difficulty: "medium",
    prompt: "A matrix $A$ satisfying $A^T = -A$ is called:",
    answer: "Skew-symmetric.",
    choices: ["Symmetric.", "Skew-symmetric.", "Orthogonal.", "Idempotent."],
    explanation: "Step 1: $A^T=-A$ is the definition of a skew-symmetric (anti-symmetric) matrix. Its diagonal entries are all zero. Final answer: Skew-symmetric." }),
  p({ id: "mat-inverse-7", topicId: "matrices", section: "inverse", type: "numeric", difficulty: "medium",
    prompt: "If $A=\\begin{pmatrix}1&2\\\\3&4\\end{pmatrix}$, what is the $(2,1)$ entry of $A^{-1}$?",
    answer: "1.5",
    explanation: "Step 1: $\\det(A)=4-6=-2$. Step 2: $A^{-1}=\\frac{1}{-2}\\begin{pmatrix}4&-2\\\\-3&1\\end{pmatrix}=\\begin{pmatrix}-2&1\\\\3/2&-1/2\\end{pmatrix}$. Step 3: $(A^{-1})_{21}=3/2=1.5$. Final answer: $1.5$." }),
  p({ id: "mat-multiplication-8", topicId: "matrices", section: "multiplication", type: "numeric", difficulty: "medium",
    prompt: "For $A=\\begin{pmatrix}0&1\\\\-1&0\\end{pmatrix}$, compute $A^4$ and find its $(1,1)$ entry.",
    answer: "1",
    explanation: "Step 1: $A^2=\\begin{pmatrix}-1&0\\\\0&-1\\end{pmatrix}=-I$. Step 2: $A^4=(A^2)^2=(-I)^2=I$. Step 3: $(I)_{11}=1$. Final answer: $1$." }),
  p({ id: "mat-operations-10", topicId: "matrices", section: "operations", type: "numeric", difficulty: "medium",
    prompt: "A $3\\times 3$ matrix $A$ has $\\text{tr}(A)=9$ and all diagonal entries equal. What is each diagonal entry?",
    answer: "3",
    explanation: "Step 1: Trace $=$ sum of diagonal entries $= 3x = 9$. Step 2: $x=3$. Final answer: $3$." }),
  p({ id: "mat-inverse-8", topicId: "matrices", section: "inverse", type: "mcq", difficulty: "medium",
    prompt: "If $A^2 = I$, then $A^{-1} =$",
    answer: "$A$",
    choices: ["$A^2$", "$A$", "$-A$", "$I$"],
    explanation: "Step 1: $A^2=I$ means $A\\cdot A=I$. Step 2: By definition of inverse, $A^{-1}=A$. Final answer: $A$." }),
  p({ id: "mat-multiplication-9", topicId: "matrices", section: "multiplication", type: "numeric", difficulty: "medium",
    prompt: "Compute $AB$ for $A=\\begin{pmatrix}1&0\\\\0&2\\end{pmatrix}$ and $B=\\begin{pmatrix}3&1\\\\0&4\\end{pmatrix}$. What is the $(2,2)$ entry?",
    answer: "8",
    explanation: "Step 1: $(AB)_{22}=(0)(1)+(2)(4)=8$. Final answer: $8$." }),
  p({ id: "mat-operations-11", topicId: "matrices", section: "operations", type: "mcq", difficulty: "medium",
    prompt: "An orthogonal matrix $Q$ satisfies:",
    answer: "$Q^TQ = I$",
    choices: ["$Q^2 = I$", "$Q^TQ = I$", "$\\det(Q) = 0$", "$Q = Q^T$"],
    explanation: "Step 1: An orthogonal matrix has orthonormal columns, which means $Q^TQ=I$. This also implies $Q^{-1}=Q^T$ and $|\\det(Q)|=1$. Final answer: $Q^TQ = I$." }),
  p({ id: "mat-inverse-9", topicId: "matrices", section: "inverse", type: "numeric", difficulty: "medium",
    prompt: "Find $\\det(2A)$ for a $3\\times 3$ matrix with $\\det(A)=5$.",
    answer: "40",
    explanation: "Step 1: $\\det(cA)=c^n\\det(A)$ for an $n\\times n$ matrix. Step 2: $\\det(2A)=2^3\\cdot 5=8\\cdot 5=40$. Final answer: $40$." }),
  p({ id: "mat-multiplication-10", topicId: "matrices", section: "multiplication", type: "numeric", difficulty: "medium",
    prompt: "If $AB=BA$ (commute), $A=\\begin{pmatrix}2&0\\\\0&3\\end{pmatrix}$ and $B=\\begin{pmatrix}1&0\\\\0&k\\end{pmatrix}$: $(AB)_{22}$ when $k=4$?",
    answer: "12",
    explanation: "Step 1: $AB=\\begin{pmatrix}2&0\\\\0&3k\\end{pmatrix}$. Step 2: $(AB)_{22}=3(4)=12$. Final answer: $12$." }),

  // --- Hard (10) ---
  p({ id: "mat-inverse-10", topicId: "matrices", section: "inverse", type: "numeric", difficulty: "hard",
    prompt: "Use row reduction to find $A^{-1}$ for $A=\\begin{pmatrix}1&2\\\\3&7\\end{pmatrix}$. What is the $(1,2)$ entry of $A^{-1}$?",
    answer: "-2",
    explanation: "Step 1: $\\det(A)=7-6=1$. Step 2: $A^{-1}=\\begin{pmatrix}7&-2\\\\-3&1\\end{pmatrix}$. Step 3: $(A^{-1})_{12}=-2$. Final answer: $-2$." }),
  p({ id: "mat-multiplication-11", topicId: "matrices", section: "multiplication", type: "numeric", difficulty: "hard",
    prompt: "If $A=\\begin{pmatrix}1&1\\\\0&1\\end{pmatrix}$, find the $(1,2)$ entry of $A^n$.",
    answer: "n",
    explanation: "Step 1: By induction or direct computation: $A^n=\\begin{pmatrix}1&n\\\\0&1\\end{pmatrix}$. Step 2: $(A^n)_{12}=n$. Final answer: $n$." }),
  p({ id: "mat-operations-12", topicId: "matrices", section: "operations", type: "mcq", difficulty: "hard",
    prompt: "For $n\\times n$ matrices: $\\text{tr}(AB) =$",
    answer: "$\\text{tr}(BA)$",
    choices: ["$\\text{tr}(A)\\text{tr}(B)$", "$\\text{tr}(BA)$", "$\\det(AB)$", "$\\text{tr}(A)+\\text{tr}(B)$"],
    explanation: "Step 1: The trace has the cyclic property: $\\text{tr}(AB)=\\text{tr}(BA)$. Note: In general $AB\\neq BA$, but their traces are equal. Final answer: $\\text{tr}(BA)$." }),
  p({ id: "mat-inverse-11", topicId: "matrices", section: "inverse", type: "numeric", difficulty: "hard",
    prompt: "For $A=\\begin{pmatrix}2&1&0\\\\1&3&1\\\\0&1&2\\end{pmatrix}$, use cofactor expansion along row 1 to find $\\det(A)$.",
    answer: "8",
    explanation: "Step 1: Expand along row 1: $\\det(A)=2\\det\\begin{pmatrix}3&1\\\\1&2\\end{pmatrix}-1\\det\\begin{pmatrix}1&1\\\\0&2\\end{pmatrix}+0$. Step 2: $=2(6-1)-1(2-0)=10-2=8$. Final answer: $8$." }),
  p({ id: "mat-multiplication-12", topicId: "matrices", section: "multiplication", type: "numeric", difficulty: "hard",
    prompt: "Find the $(1,1)$ entry of $A^2$ for $A=\\begin{pmatrix}3&-1\\\\2&0\\end{pmatrix}$.",
    answer: "7",
    explanation: "Step 1: $(A^2)_{11}=(3)(3)+(-1)(2)=9-2=7$. Final answer: $7$." }),
  p({ id: "mat-inverse-12", topicId: "matrices", section: "inverse", type: "mcq", difficulty: "hard",
    prompt: "Which condition is NOT equivalent to $A$ being invertible ($A$ is $n\\times n$)?",
    answer: "The columns of $A$ are linearly dependent.",
    choices: ["$\\det(A)\\neq 0$.", "$\\text{rank}(A)=n$.", "The columns of $A$ are linearly dependent.", "$A\\mathbf{x}=\\mathbf{b}$ has a unique solution for every $\\mathbf{b}$."],
    explanation: "Step 1: Invertibility requires linearly independent columns, not dependent. Step 2: All other options are equivalent to invertibility. Final answer: The columns of $A$ are linearly dependent." }),
  p({ id: "mat-operations-13", topicId: "matrices", section: "operations", type: "numeric", difficulty: "hard",
    prompt: "For idempotent $A$ ($A^2=A$), compute $\\det(A)$ if $A$ is $2\\times 2$ with $\\text{tr}(A)=1$ and eigenvalues $0$ and $1$.",
    answer: "0",
    explanation: "Step 1: Eigenvalues of idempotent matrices are $0$ or $1$. Step 2: $\\det(A)=\\lambda_1\\lambda_2=0\\cdot 1=0$. Final answer: $0$." }),
  p({ id: "mat-inverse-13", topicId: "matrices", section: "inverse", type: "numeric", difficulty: "hard",
    prompt: "If $A$ and $B$ are $n\\times n$ invertible matrices, $(A^{-1}BA)^3$ simplifies to $A^{-1}B^3A$. For $B=\\begin{pmatrix}2&0\\\\0&3\\end{pmatrix}$, what is the $(2,2)$ entry of $B^3$?",
    answer: "27",
    explanation: "Step 1: $B$ is diagonal, so $B^3=\\begin{pmatrix}2^3&0\\\\0&3^3\\end{pmatrix}=\\begin{pmatrix}8&0\\\\0&27\\end{pmatrix}$. Step 2: $(B^3)_{22}=27$. Final answer: $27$." }),
  p({ id: "mat-multiplication-13", topicId: "matrices", section: "multiplication", type: "numeric", difficulty: "hard",
    prompt: "Solve $AX=B$ for $X$ given $A=\\begin{pmatrix}1&0\\\\2&1\\end{pmatrix}$ and $B=\\begin{pmatrix}3&1\\\\7&3\\end{pmatrix}$. What is $X_{11}$?",
    answer: "3",
    explanation: "Step 1: $X=A^{-1}B$. Step 2: $A^{-1}=\\begin{pmatrix}1&0\\\\-2&1\\end{pmatrix}$ (lower triangular inverse). Step 3: $X=\\begin{pmatrix}1&0\\\\-2&1\\end{pmatrix}\\begin{pmatrix}3&1\\\\7&3\\end{pmatrix}=\\begin{pmatrix}3&1\\\\1&1\\end{pmatrix}$. Step 4: $X_{11}=3$. Final answer: $3$." }),
  p({ id: "mat-operations-14", topicId: "matrices", section: "operations", type: "numeric", difficulty: "hard",
    prompt: "Show $(AB)^T=B^TA^T$. For $A=\\begin{pmatrix}1&2\\end{pmatrix}$ (1×2) and $B=\\begin{pmatrix}3\\\\4\\end{pmatrix}$ (2×1), what is the single entry of $(AB)^T$?",
    answer: "11",
    explanation: "Step 1: $AB=(1)(3)+(2)(4)=11$ (scalar). Step 2: $(AB)^T=11^T=11$. Final answer: $11$." }),
];
