import type { Problem } from "../shared-types";

const p = (problem: Problem) => problem;

export const spaceProblems: Problem[] = [
  // --- Easy (14) ---
  p({ id: "space-span-1", topicId: "spaces", section: "span", type: "mcq", difficulty: "easy",
    prompt: "The span of $\\{\\langle 1,0\\rangle, \\langle 0,1\\rangle\\}$ is:",
    answer: "All of $\\mathbb{R}^2$.",
    choices: ["A single point.", "A line through the origin.", "All of $\\mathbb{R}^2$.", "A plane in $\\mathbb{R}^3$."],
    explanation: "Step 1: Any $\\langle a,b\\rangle = a\\langle 1,0\\rangle+b\\langle 0,1\\rangle$. Step 2: These vectors span $\\mathbb{R}^2$. Final answer: All of $\\mathbb{R}^2$." }),
  p({ id: "space-basis-1", topicId: "spaces", section: "basis", type: "numeric", difficulty: "easy",
    prompt: "What is the dimension of $\\mathbb{R}^3$?",
    answer: "3",
    explanation: "Step 1: The standard basis $\\{\\mathbf{e}_1,\\mathbf{e}_2,\\mathbf{e}_3\\}$ has $3$ vectors. Step 2: Dimension $=3$. Final answer: $3$." }),
  p({ id: "space-subspaces-1", topicId: "spaces", section: "subspaces", type: "mcq", difficulty: "easy",
    prompt: "The null space of a matrix $A$ is defined as:",
    answer: "$\\{\\mathbf{x}: A\\mathbf{x}=\\mathbf{0}\\}$",
    choices: ["$\\{\\mathbf{x}: A\\mathbf{x}=\\mathbf{x}\\}$", "$\\{\\mathbf{x}: A\\mathbf{x}=\\mathbf{0}\\}$", "$\\{\\mathbf{x}: \\mathbf{x}^TA=\\mathbf{0}\\}$", "$\\{\\mathbf{x}: A+\\mathbf{x}=\\mathbf{0}\\}$"],
    explanation: "Step 1: By definition, $\\text{Null}(A)=\\ker(A)=\\{\\mathbf{x}: A\\mathbf{x}=\\mathbf{0}\\}$. Final answer: $\\{\\mathbf{x}: A\\mathbf{x}=\\mathbf{0}\\}$." }),
  p({ id: "space-independence-1", topicId: "spaces", section: "independence", type: "mcq", difficulty: "easy",
    prompt: "Are $\\langle 1,2\\rangle$ and $\\langle 2,4\\rangle$ linearly independent?",
    answer: "No — one is a scalar multiple of the other.",
    choices: ["Yes, because they are both nonzero.", "Yes, they have different magnitudes.", "No — one is a scalar multiple of the other.", "No — their sum is zero."],
    explanation: "Step 1: $\\langle 2,4\\rangle=2\\langle 1,2\\rangle$. Step 2: Scalar multiple $\\Rightarrow$ linearly dependent. Final answer: No — one is a scalar multiple of the other." }),
  p({ id: "space-basis-2", topicId: "spaces", section: "basis", type: "numeric", difficulty: "easy",
    prompt: "A $3\\times 3$ matrix has rank $2$. What is its nullity?",
    answer: "1",
    explanation: "Step 1: Rank $+$ Nullity $= n=3$. Step 2: Nullity $=3-2=1$. Final answer: $1$." }),
  p({ id: "space-subspaces-2", topicId: "spaces", section: "subspaces", type: "mcq", difficulty: "easy",
    prompt: "Which of the following is always a subspace of $\\mathbb{R}^n$?",
    answer: "The null space of any $m\\times n$ matrix.",
    choices: ["Any set containing the zero vector.", "The null space of any $m\\times n$ matrix.", "Any line in $\\mathbb{R}^n$.", "Any set of two vectors."],
    explanation: "Step 1: The null space is closed under addition and scalar multiplication, and contains $\\mathbf{0}$. Step 2: It is always a subspace. Final answer: The null space of any $m\\times n$ matrix." }),
  p({ id: "space-span-2", topicId: "spaces", section: "span", type: "mcq", difficulty: "easy",
    prompt: "The span of a single nonzero vector $\\mathbf{v}$ in $\\mathbb{R}^3$ is:",
    answer: "A line through the origin.",
    choices: ["A single point.", "A line through the origin.", "A plane.", "All of $\\mathbb{R}^3$."],
    explanation: "Step 1: $\\text{span}\\{\\mathbf{v}\\}=\\{c\\mathbf{v}:c\\in\\mathbb{R}\\}$ — all scalar multiples of $\\mathbf{v}$. Step 2: This is a line through the origin. Final answer: A line through the origin." }),
  p({ id: "space-linear-transformations-1", topicId: "spaces", section: "linear-transformations", type: "numeric", difficulty: "easy",
    prompt: "The linear transformation $T(\\mathbf{x})=A\\mathbf{x}$ with $A=\\begin{pmatrix}2&0\\\\0&3\\end{pmatrix}$. What is the first component of $T(\\langle 4,1\\rangle)$?",
    answer: "8",
    explanation: "Step 1: $T(\\langle 4,1\\rangle)=\\begin{pmatrix}8\\\\3\\end{pmatrix}$. Step 2: First component: $8$. Final answer: $8$." }),
  p({ id: "space-independence-2", topicId: "spaces", section: "independence", type: "numeric", difficulty: "easy",
    prompt: "A set of vectors in $\\mathbb{R}^n$ with more than $n$ vectors is always:",
    answer: "0",
    explanation: "Step 1: More than $n$ vectors in $\\mathbb{R}^n$ must be linearly dependent — enter $0$ for dependent, $1$ for independent. Step 2: Answer is $0$ (dependent). Final answer: $0$." }),
  p({ id: "space-basis-3", topicId: "spaces", section: "basis", type: "mcq", difficulty: "easy",
    prompt: "A basis for a vector space must be:",
    answer: "Both linearly independent and spanning.",
    choices: ["Only spanning.", "Only linearly independent.", "Both linearly independent and spanning.", "Orthogonal."],
    explanation: "Step 1: A basis must be a linearly independent spanning set. Final answer: Both linearly independent and spanning." }),
  p({ id: "space-subspaces-3", topicId: "spaces", section: "subspaces", type: "numeric", difficulty: "easy",
    prompt: "The column space of $A=\\begin{pmatrix}1&2\\\\2&4\\end{pmatrix}$ has dimension:",
    answer: "1",
    explanation: "Step 1: Rank$(A)=1$ (col 2 $=2\\times$ col 1). Step 2: Dim(Col$(A))=$rank$(A)=1$. Final answer: $1$." }),
  p({ id: "space-linear-transformations-2", topicId: "spaces", section: "linear-transformations", type: "mcq", difficulty: "easy",
    prompt: "A transformation $T:\\mathbb{R}^n\\to\\mathbb{R}^m$ is linear if:",
    answer: "$T(c\\mathbf{u}+d\\mathbf{v})=cT(\\mathbf{u})+dT(\\mathbf{v})$ for all $c,d,\\mathbf{u},\\mathbf{v}$.",
    choices: ["$T(\\mathbf{u}+\\mathbf{v})=T(\\mathbf{u})T(\\mathbf{v})$.", "$T(c\\mathbf{u}+d\\mathbf{v})=cT(\\mathbf{u})+dT(\\mathbf{v})$ for all $c,d,\\mathbf{u},\\mathbf{v}$.", "$T$ is one-to-one.", "$T(\\mathbf{0})\\neq\\mathbf{0}$."],
    explanation: "Step 1: Linearity means $T$ respects vector addition and scalar multiplication. Final answer: $T(c\\mathbf{u}+d\\mathbf{v})=cT(\\mathbf{u})+dT(\\mathbf{v})$." }),
  p({ id: "space-span-3", topicId: "spaces", section: "span", type: "mcq", difficulty: "easy",
    prompt: "Two nonzero, non-parallel vectors in $\\mathbb{R}^3$ span:",
    answer: "A plane through the origin.",
    choices: ["A line.", "A plane through the origin.", "All of $\\mathbb{R}^3$.", "A single point."],
    explanation: "Step 1: Two linearly independent vectors span a 2-dimensional subspace — a plane through the origin in $\\mathbb{R}^3$. Final answer: A plane through the origin." }),
  p({ id: "space-independence-3", topicId: "spaces", section: "independence", type: "numeric", difficulty: "easy",
    prompt: "How many vectors are in a basis for $\\mathbb{R}^4$?",
    answer: "4",
    explanation: "Step 1: Any basis for $\\mathbb{R}^4$ must have exactly $4$ vectors (equal to the dimension). Final answer: $4$." }),

  // --- Medium (16) ---
  p({ id: "space-subspaces-4", topicId: "spaces", section: "subspaces", type: "numeric", difficulty: "medium",
    prompt: "Find the dimension of the column space of $A=\\begin{pmatrix}1&2&3\\\\0&1&1\\\\0&0&0\\end{pmatrix}$.",
    answer: "2",
    explanation: "Step 1: Matrix is in REF with 2 pivot rows. Step 2: Rank $=$ dim(Col$(A))=2$. Final answer: $2$." }),
  p({ id: "space-linear-transformations-3", topicId: "spaces", section: "linear-transformations", type: "numeric", difficulty: "medium",
    prompt: "For $T(\\mathbf{x})=A\\mathbf{x}$ with $A=\\begin{pmatrix}1&0\\\\0&0\\end{pmatrix}$, what is the dimension of the range (image) of $T$?",
    answer: "1",
    explanation: "Step 1: Rank$(A)=1$. Step 2: Dim(range of $T$) $=$rank$(A)=1$. Final answer: $1$." }),
  p({ id: "space-independence-4", topicId: "spaces", section: "independence", type: "mcq", difficulty: "medium",
    prompt: "The set $\\{\\langle 1,0,0\\rangle,\\langle 0,1,0\\rangle,\\langle 1,1,0\\rangle\\}$ is:",
    answer: "Linearly dependent.",
    choices: ["Linearly independent.", "Linearly dependent.", "A basis for $\\mathbb{R}^3$.", "Orthonormal."],
    explanation: "Step 1: $\\langle 1,1,0\\rangle=\\langle 1,0,0\\rangle+\\langle 0,1,0\\rangle$. Step 2: One vector is a combination of the others: linearly dependent. Final answer: Linearly dependent." }),
  p({ id: "space-basis-4", topicId: "spaces", section: "basis", type: "numeric", difficulty: "medium",
    prompt: "The subspace $V=\\{\\langle x,y,z\\rangle: x+y+z=0\\}$ of $\\mathbb{R}^3$ has dimension:",
    answer: "2",
    explanation: "Step 1: The constraint $x+y+z=0$ removes one degree of freedom. Step 2: Dim$(V)=3-1=2$. Final answer: $2$." }),
  p({ id: "space-subspaces-5", topicId: "spaces", section: "subspaces", type: "mcq", difficulty: "medium",
    prompt: "The row space of $A$ and the null space of $A$ are:",
    answer: "Orthogonal complements in $\\mathbb{R}^n$.",
    choices: ["Equal.", "Orthogonal complements in $\\mathbb{R}^n$.", "Both equal to $\\mathbb{R}^n$.", "Always of equal dimension."],
    explanation: "Step 1: The Fundamental Theorem of Linear Algebra: Row$(A)\\perp$Null$(A)$ and they are orthogonal complements in $\\mathbb{R}^n$. Final answer: Orthogonal complements in $\\mathbb{R}^n$." }),
  p({ id: "space-linear-transformations-4", topicId: "spaces", section: "linear-transformations", type: "numeric", difficulty: "medium",
    prompt: "The kernel of $T:\\mathbb{R}^3\\to\\mathbb{R}^2$ given by $T(\\mathbf{x})=A\\mathbf{x}$ where $A$ has rank 2 has dimension:",
    answer: "1",
    explanation: "Step 1: By rank-nullity: dim(kernel) $=n-$rank $=3-2=1$. Final answer: $1$." }),
  p({ id: "space-span-4", topicId: "spaces", section: "span", type: "numeric", difficulty: "medium",
    prompt: "Is $\\mathbf{b}=\\langle 3,6\\rangle$ in the span of $\\{\\langle 1,2\\rangle\\}$? Enter $1$ for yes, $0$ for no.",
    answer: "1",
    explanation: "Step 1: $\\langle 3,6\\rangle=3\\langle 1,2\\rangle$. Step 2: Yes, $\\mathbf{b}$ is in the span. Final answer: $1$." }),
  p({ id: "space-independence-5", topicId: "spaces", section: "independence", type: "numeric", difficulty: "medium",
    prompt: "Is $\\mathbf{b}=\\langle 1,0\\rangle$ in the span of $\\{\\langle 1,1\\rangle,\\langle 0,1\\rangle\\}$? If yes, find the coefficient of $\\langle 1,1\\rangle$.",
    answer: "1",
    explanation: "Step 1: $\\langle 1,0\\rangle=a\\langle 1,1\\rangle+b\\langle 0,1\\rangle$. Step 2: $a=1$, $a+b=0\\Rightarrow b=-1$. Step 3: Coefficient of $\\langle 1,1\\rangle$ is $1$. Final answer: $1$." }),
  p({ id: "space-basis-5", topicId: "spaces", section: "basis", type: "mcq", difficulty: "medium",
    prompt: "Which set is a basis for $\\mathbb{R}^2$?",
    answer: "$\\{\\langle 1,1\\rangle,\\langle 1,-1\\rangle\\}$",
    choices: ["$\\{\\langle 1,0\\rangle,\\langle 2,0\\rangle\\}$", "$\\{\\langle 1,1\\rangle,\\langle 1,-1\\rangle\\}$", "$\\{\\langle 0,0\\rangle,\\langle 1,0\\rangle\\}$", "$\\{\\langle 1,2\\rangle,\\langle 2,4\\rangle\\}$"],
    explanation: "Step 1: $\\{\\langle 1,1\\rangle,\\langle 1,-1\\rangle\\}$: det $=(-1-1)=-2\\neq 0$, so linearly independent and spans $\\mathbb{R}^2$. Final answer: $\\{\\langle 1,1\\rangle,\\langle 1,-1\\rangle\\}$." }),
  p({ id: "space-subspaces-6", topicId: "spaces", section: "subspaces", type: "mcq", difficulty: "medium",
    prompt: "Which is NOT a subspace of $\\mathbb{R}^2$?",
    answer: "$\\{\\langle x,y\\rangle: x+y=1\\}$",
    choices: ["$\\{\\langle 0,0\\rangle\\}$", "$\\mathbb{R}^2$", "$\\{\\langle x,y\\rangle: x+y=1\\}$", "$\\{\\langle x,0\\rangle: x\\in\\mathbb{R}\\}$"],
    explanation: "Step 1: A subspace must contain $\\mathbf{0}$. Step 2: $x+y=1$ does not contain $\\langle 0,0\\rangle$ since $0+0\\neq 1$. Not a subspace. Final answer: $\\{\\langle x,y\\rangle: x+y=1\\}$." }),
  p({ id: "space-linear-transformations-5", topicId: "spaces", section: "linear-transformations", type: "mcq", difficulty: "medium",
    prompt: "A linear transformation $T:\\mathbb{R}^n\\to\\mathbb{R}^m$ is one-to-one if and only if:",
    answer: "Its kernel contains only $\\mathbf{0}$.",
    choices: ["$m=n$.", "Its kernel contains only $\\mathbf{0}$.", "It is onto.", "Its matrix has determinant $1$."],
    explanation: "Step 1: $T$ is one-to-one iff $T(\\mathbf{x})=\\mathbf{0}$ implies $\\mathbf{x}=\\mathbf{0}$, i.e., kernel $=\\{\\mathbf{0}\\}$. Final answer: Its kernel contains only $\\mathbf{0}$." }),
  p({ id: "space-span-5", topicId: "spaces", section: "span", type: "numeric", difficulty: "medium",
    prompt: "The span of $\\{\\langle 1,0,0\\rangle,\\langle 0,1,0\\rangle\\}$ in $\\mathbb{R}^3$ has dimension:",
    answer: "2",
    explanation: "Step 1: Two linearly independent vectors span a 2-dimensional subspace. Final answer: $2$." }),
  p({ id: "space-independence-6", topicId: "spaces", section: "independence", type: "numeric", difficulty: "medium",
    prompt: "If the $3\\times 3$ matrix $[\\mathbf{v}_1,\\mathbf{v}_2,\\mathbf{v}_3]$ has det $= -4$, are $\\mathbf{v}_1,\\mathbf{v}_2,\\mathbf{v}_3$ linearly independent? Enter $1$ for yes, $0$ for no.",
    answer: "1",
    explanation: "Step 1: det $\\neq 0 \\Rightarrow$ columns are linearly independent. Final answer: $1$." }),
  p({ id: "space-basis-6", topicId: "spaces", section: "basis", type: "numeric", difficulty: "medium",
    prompt: "The solution space of $A\\mathbf{x}=\\mathbf{0}$ for $A$ a $2\\times 4$ matrix of rank $2$ has dimension:",
    answer: "2",
    explanation: "Step 1: Nullity $= n - $ rank $= 4-2=2$. Final answer: $2$." }),
  p({ id: "space-linear-transformations-6", topicId: "spaces", section: "linear-transformations", type: "numeric", difficulty: "medium",
    prompt: "If $T:\\mathbb{R}^4\\to\\mathbb{R}^3$ is linear with dim(kernel)$=2$, what is dim(range)?",
    answer: "2",
    explanation: "Step 1: dim(range) $= n - $ dim(kernel) $= 4-2=2$. Final answer: $2$." }),
  p({ id: "space-subspaces-7", topicId: "spaces", section: "subspaces", type: "numeric", difficulty: "medium",
    prompt: "For $A$ a $5\\times 3$ matrix of rank $2$, what is dim(Left Null$(A))$?",
    answer: "3",
    explanation: "Step 1: Left null space $= $ Null$(A^T)$. $A^T$ is $3\\times 5$. Nullity of $A^T = 5-$ rank$(A^T)=5-2=3$. Final answer: $3$." }),

  // --- Hard (10) ---
  p({ id: "space-independence-7", topicId: "spaces", section: "independence", type: "numeric", difficulty: "hard",
    prompt: "The set $\\{1, x, x^2\\}$ is a basis for $\\mathcal{P}_2$ (polynomials of degree $\\leq 2$). What is dim($\\mathcal{P}_2$)?",
    answer: "3",
    explanation: "Step 1: The basis has $3$ elements. Step 2: dim $=3$. Final answer: $3$." }),
  p({ id: "space-subspaces-8", topicId: "spaces", section: "subspaces", type: "mcq", difficulty: "hard",
    prompt: "The four fundamental subspaces of an $m\\times n$ matrix $A$ with rank $r$ are: Col$(A)$, Null$(A)$, Row$(A)$, Left Null$(A)$. What is dim(Null$(A))$ + dim(Col$(A)$)?",
    answer: "$n$",
    choices: ["$m$", "$n$", "$r$", "$m+n$"],
    explanation: "Step 1: dim(Null$(A))=n-r$ and dim(Col$(A))=r$. Step 2: Sum $=(n-r)+r=n$. Final answer: $n$." }),
  p({ id: "space-linear-transformations-7", topicId: "spaces", section: "linear-transformations", type: "numeric", difficulty: "hard",
    prompt: "A rotation by $\\theta=90^\\circ$ in $\\mathbb{R}^2$ has matrix $R=\\begin{pmatrix}0&-1\\\\1&0\\end{pmatrix}$. What is the second component of $R\\langle 3,4\\rangle$?",
    answer: "3",
    explanation: "Step 1: $R\\langle 3,4\\rangle=\\langle -4,3\\rangle$. Step 2: Second component: $3$. Final answer: $3$." }),
  p({ id: "space-basis-7", topicId: "spaces", section: "basis", type: "numeric", difficulty: "hard",
    prompt: "A subspace $V\\subset\\mathbb{R}^5$ has dim$(V)=3$. What is dim$(V^\\perp)$?",
    answer: "2",
    explanation: "Step 1: dim$(V)+$dim$(V^\\perp)=5$. Step 2: dim$(V^\\perp)=5-3=2$. Final answer: $2$." }),
  p({ id: "space-linear-transformations-8", topicId: "spaces", section: "linear-transformations", type: "mcq", difficulty: "hard",
    prompt: "A linear transformation $T:\\mathbb{R}^3\\to\\mathbb{R}^3$ with rank 3 is:",
    answer: "An isomorphism (bijective linear map).",
    choices: ["Not invertible.", "An isomorphism (bijective linear map).", "Has a nontrivial kernel.", "Maps to a subspace of dimension less than 3."],
    explanation: "Step 1: Rank $3$ on a $3\\times 3$ matrix means full rank, hence invertible. Step 2: Bijective $+$ linear $=$ isomorphism. Final answer: An isomorphism (bijective linear map)." }),
  p({ id: "space-span-6", topicId: "spaces", section: "span", type: "numeric", difficulty: "hard",
    prompt: "How many vectors are needed to span all of $\\mathbb{R}^n$? (Minimum number.)",
    answer: "n",
    explanation: "Step 1: You need at least $n$ linearly independent vectors to span $\\mathbb{R}^n$. Step 2: Minimum $=n$. Final answer: $n$." }),
  p({ id: "space-subspaces-9", topicId: "spaces", section: "subspaces", type: "numeric", difficulty: "hard",
    prompt: "For $A=\\begin{pmatrix}1&2&0\\\\0&0&1\\\\0&0&0\\end{pmatrix}$, find dim(Null$(A))$.",
    answer: "1",
    explanation: "Step 1: Rank $= 2$. Step 2: Nullity $= 3-2=1$. Final answer: $1$." }),
  p({ id: "space-independence-8", topicId: "spaces", section: "independence", type: "mcq", difficulty: "hard",
    prompt: "The Basis Theorem states: any two bases for the same finite-dimensional vector space have",
    answer: "The same number of vectors.",
    choices: ["Different numbers of vectors.", "The same number of vectors.", "Orthogonal vectors.", "The same vectors."],
    explanation: "Step 1: The dimension of a vector space is well-defined: any two bases contain the same number of elements. Final answer: The same number of vectors." }),
  p({ id: "space-linear-transformations-9", topicId: "spaces", section: "linear-transformations", type: "numeric", difficulty: "hard",
    prompt: "A shear transformation $T:\\mathbb{R}^2\\to\\mathbb{R}^2$ has matrix $\\begin{pmatrix}1&k\\\\0&1\\end{pmatrix}$. For $k=3$, what is the second component of $T(\\langle 2,1\\rangle)$?",
    answer: "1",
    explanation: "Step 1: $T(\\langle 2,1\\rangle)=\\langle 2+3,1\\rangle=\\langle 5,1\\rangle$. Step 2: Second component: $1$. Final answer: $1$." }),
  p({ id: "space-basis-8", topicId: "spaces", section: "basis", type: "numeric", difficulty: "hard",
    prompt: "The matrix $A=\\begin{pmatrix}1&1&0\\\\0&1&1\\\\1&0&1\\end{pmatrix}$ has rank $2$. Dim(Row$(A))=$",
    answer: "2",
    explanation: "Step 1: Dim(Row$(A))=$ rank$(A)=2$. Final answer: $2$." }),
];
