import type { Problem } from "../shared-types";

const p = (problem: Problem) => problem;

export const anovaProblems: Problem[] = [
  // --- Easy (14) ---
  p({ id: "anova-null-1", topicId: "anova", section: "f-test", type: "mcq", difficulty: "easy",
    prompt: "The null hypothesis in one-way ANOVA states that:",
    answer: "All group means are equal: $\\mu_1=\\mu_2=\\cdots=\\mu_k$.",
    choices: ["All group means are equal: $\\mu_1=\\mu_2=\\cdots=\\mu_k$.", "At least one mean differs.", "All variances are equal.", "All sample sizes are equal."],
    explanation: "Step 1: $H_0:\\mu_1=\\mu_2=\\cdots=\\mu_k$. Rejecting tells us at least one differs; follow-up tests identify which. Final answer: All group means are equal." }),
  p({ id: "anova-alt-1", topicId: "anova", section: "f-test", type: "mcq", difficulty: "easy",
    prompt: "The alternative hypothesis in one-way ANOVA states that:",
    answer: "At least one group mean is different.",
    choices: ["All means are equal.", "All means are different.", "At least one group mean is different.", "All variances differ."],
    explanation: "Step 1: $H_a$: at least one $\\mu_i\\neq\\mu_j$. Note: ANOVA doesn't specify which pairs differ. Final answer: At least one group mean is different." }),
  p({ id: "anova-assume-1", topicId: "anova", section: "assumptions", type: "mcq", difficulty: "easy",
    prompt: "One-way ANOVA assumes the populations have:",
    answer: "Equal variances and normal distributions.",
    choices: ["Equal means and normal distributions.", "Equal variances and normal distributions.", "Equal sample sizes only.", "No outliers and equal medians."],
    explanation: "Step 1: ANOVA assumes: (1) independence, (2) normality within groups, (3) equal variances (homoscedasticity). Final answer: Equal variances and normal distributions." }),
  p({ id: "anova-f-1", topicId: "anova", section: "f-test", type: "mcq", difficulty: "easy",
    prompt: "The $F$-statistic in ANOVA is:",
    answer: "$\\text{MS}_{\\text{between}}/\\text{MS}_{\\text{within}}$",
    choices: ["$\\text{MS}_{\\text{within}}/\\text{MS}_{\\text{between}}$", "$\\text{MS}_{\\text{between}}/\\text{MS}_{\\text{within}}$", "$\\text{SS}_{\\text{total}}/n$", "$\\bar{x}_1-\\bar{x}_2$"],
    explanation: "Step 1: $F=\\text{MS}_B/\\text{MS}_W$. Large $F$ means between-group variation exceeds within-group noise. Final answer: $\\text{MS}_{\\text{between}}/\\text{MS}_{\\text{within}}$." }),
  p({ id: "anova-ss-1", topicId: "anova", section: "f-test", type: "mcq", difficulty: "easy",
    prompt: "$SS_{\\text{total}}=SS_{\\text{between}}+SS_{\\text{within}}$. This partition of variance is called:",
    answer: "The ANOVA decomposition.",
    choices: ["Regression decomposition.", "The ANOVA decomposition.", "Chi-square partition.", "Variance inflation."],
    explanation: "Step 1: ANOVA decomposes total variation into explained (between-group) and unexplained (within-group) components. Final answer: The ANOVA decomposition." }),
  p({ id: "anova-posthoc-1", topicId: "anova", section: "post-hoc", type: "mcq", difficulty: "easy",
    prompt: "Post-hoc tests in ANOVA are performed:",
    answer: "After rejecting $H_0$ to identify which specific groups differ.",
    choices: ["Before ANOVA to check assumptions.", "After rejecting $H_0$ to identify which specific groups differ.", "Instead of ANOVA.", "To check normality."],
    explanation: "Step 1: Post-hoc tests (e.g., Tukey, Bonferroni) are pairwise comparisons run after a significant ANOVA to control Type I error. Final answer: After rejecting $H_0$ to identify which specific groups differ." }),
  p({ id: "anova-df-1", topicId: "anova", section: "f-test", type: "numeric", difficulty: "easy",
    prompt: "One-way ANOVA with $k=4$ groups and $N=20$ total observations. Degrees of freedom between $=$",
    answer: "3",
    explanation: "Step 1: $\\text{df}_{\\text{between}}=k-1=4-1=3$. Final answer: $3$." }),
  p({ id: "anova-df-2", topicId: "anova", section: "f-test", type: "numeric", difficulty: "easy",
    prompt: "One-way ANOVA with $k=4$ groups, $N=20$ total observations. Degrees of freedom within $=$",
    answer: "16",
    explanation: "Step 1: $\\text{df}_{\\text{within}}=N-k=20-4=16$. Final answer: $16$." }),
  p({ id: "anova-two-way-1", topicId: "anova", section: "two-way", type: "mcq", difficulty: "easy",
    prompt: "Two-way ANOVA tests for:",
    answer: "Main effects of two factors and their interaction.",
    choices: ["Only the interaction effect.", "Only the main effects.", "Main effects of two factors and their interaction.", "The equality of variances."],
    explanation: "Step 1: Two-way ANOVA simultaneously tests: main effect of Factor A, main effect of Factor B, and the A×B interaction. Final answer: Main effects of two factors and their interaction." }),
  p({ id: "anova-ms-1", topicId: "anova", section: "f-test", type: "mcq", difficulty: "easy",
    prompt: "$\\text{MS}=\\text{SS}/\\text{df}$. Mean square is:",
    answer: "Variance estimate for that source.",
    choices: ["Sum of squares.", "Variance estimate for that source.", "Standard deviation.", "Sample size."],
    explanation: "Step 1: MS is SS divided by df, giving an estimate of variance attributable to that source of variation. Final answer: Variance estimate for that source." }),
  p({ id: "anova-posthoc-2", topicId: "anova", section: "post-hoc", type: "mcq", difficulty: "easy",
    prompt: "Tukey's HSD test controls the:",
    answer: "Family-wise error rate.",
    choices: ["Per-comparison error rate.", "Family-wise error rate.", "Type II error.", "Effect size."],
    explanation: "Step 1: Tukey's HSD (Honestly Significant Difference) controls the family-wise Type I error at $\\alpha$ across all pairwise comparisons. Final answer: Family-wise error rate." }),
  p({ id: "anova-assume-2", topicId: "anova", section: "assumptions", type: "mcq", difficulty: "easy",
    prompt: "Levene's test is used to check the ANOVA assumption of:",
    answer: "Equal variances (homoscedasticity).",
    choices: ["Normality.", "Equal variances (homoscedasticity).", "Independence.", "Equal sample sizes."],
    explanation: "Step 1: Levene's test checks $H_0$: all group variances are equal. Significant result suggests heteroscedasticity. Final answer: Equal variances (homoscedasticity)." }),
  p({ id: "anova-f-2", topicId: "anova", section: "f-test", type: "mcq", difficulty: "easy",
    prompt: "When $H_0$ is true in ANOVA, the $F$-statistic follows an $F$-distribution with expected value approximately:",
    answer: "$1$",
    choices: ["$0$", "$1$", "Equal to $k$.", "Equal to $N$."],
    explanation: "Step 1: When $H_0$ is true, $\\text{MS}_B\\approx\\text{MS}_W$, so $F\\approx1$. Final answer: $1$." }),
  p({ id: "anova-nonpar-1", topicId: "anova", section: "assumptions", type: "mcq", difficulty: "easy",
    prompt: "When ANOVA assumptions are severely violated, the non-parametric alternative is:",
    answer: "Kruskal-Wallis test.",
    choices: ["Mann-Whitney U.", "Kruskal-Wallis test.", "Wilcoxon signed-rank.", "Chi-square test."],
    explanation: "Step 1: Kruskal-Wallis is the non-parametric equivalent of one-way ANOVA, using ranks. Final answer: Kruskal-Wallis test." }),

  // --- Medium (16) ---
  p({ id: "anova-calc-1", topicId: "anova", section: "f-test", type: "numeric", difficulty: "medium",
    prompt: "$\\text{SS}_B=60$, $\\text{df}_B=3$; $\\text{SS}_W=120$, $\\text{df}_W=16$. Find $F$.",
    answer: "2.67",
    explanation: "Step 1: $\\text{MS}_B=60/3=20$. $\\text{MS}_W=120/16=7.5$. $F=20/7.5\\approx2.67$. Final answer: $2.67$." }),
  p({ id: "anova-ss-2", topicId: "anova", section: "f-test", type: "numeric", difficulty: "medium",
    prompt: "$SS_{\\text{total}}=200$, $SS_{\\text{within}}=140$. Find $SS_{\\text{between}}$.",
    answer: "60",
    explanation: "Step 1: $SS_B=SS_T-SS_W=200-140=60$. Final answer: $60$." }),
  p({ id: "anova-assume-3", topicId: "anova", section: "assumptions", type: "mcq", difficulty: "medium",
    prompt: "If group variances are unequal in ANOVA, a robust alternative is:",
    answer: "Welch's ANOVA.",
    choices: ["Paired $t$-test.", "Welch's ANOVA.", "Chi-square test.", "Regression."],
    explanation: "Step 1: Welch's ANOVA relaxes the equal-variance assumption, similar to how Welch's $t$-test extends the $t$-test. Final answer: Welch's ANOVA." }),
  p({ id: "anova-posthoc-3", topicId: "anova", section: "post-hoc", type: "mcq", difficulty: "medium",
    prompt: "With $k=5$ groups, how many pairwise comparisons are possible?",
    answer: "$10$",
    choices: ["$5$", "$10$", "$20$", "$25$"],
    explanation: "Step 1: $\\binom{5}{2}=10$ pairwise comparisons. Final answer: $10$." }),
  p({ id: "anova-two-way-2", topicId: "anova", section: "two-way", type: "mcq", difficulty: "medium",
    prompt: "An interaction effect in two-way ANOVA means:",
    answer: "The effect of Factor A depends on the level of Factor B.",
    choices: ["Both main effects are significant.", "The effect of Factor A depends on the level of Factor B.", "Factor A and B both have no effect.", "Sample sizes must be equal."],
    explanation: "Step 1: Interaction: the combined effect of A and B is not simply additive. The effect of one factor changes across levels of the other. Final answer: The effect of Factor A depends on the level of Factor B." }),
  p({ id: "anova-calc-2", topicId: "anova", section: "f-test", type: "numeric", difficulty: "medium",
    prompt: "Three groups each with $n=5$: $\\bar{x}_1=10$, $\\bar{x}_2=14$, $\\bar{x}_3=12$. Grand mean $\\bar{x}_{..}=12$. Find $SS_{\\text{between}}$.",
    answer: "40",
    explanation: "Step 1: $SS_B=n\\sum(\\bar{x}_i-\\bar{x}_{..})^2=5[(10-12)^2+(14-12)^2+(12-12)^2]=5[4+4+0]=40$. Final answer: $40$." }),
  p({ id: "anova-eta-1", topicId: "anova", section: "f-test", type: "mcq", difficulty: "medium",
    prompt: "Effect size $\\eta^2=SS_B/SS_T$. If $SS_B=60$ and $SS_T=200$, $\\eta^2=$",
    answer: "$0.30$",
    choices: ["$0.10$", "$0.20$", "$0.30$", "$0.40$"],
    explanation: "Step 1: $\\eta^2=60/200=0.30$. This indicates $30\\%$ of total variance is explained by group membership. Final answer: $0.30$." }),
  p({ id: "anova-posthoc-4", topicId: "anova", section: "post-hoc", type: "mcq", difficulty: "medium",
    prompt: "The Bonferroni correction for $k=5$ groups ($10$ pairs) at $\\alpha=0.05$ sets each comparison at $\\alpha^*=$",
    answer: "$0.005$",
    choices: ["$0.05$", "$0.01$", "$0.005$", "$0.025$"],
    explanation: "Step 1: $\\alpha^*=0.05/10=0.005$. Final answer: $0.005$." }),
  p({ id: "anova-two-way-3", topicId: "anova", section: "two-way", type: "mcq", difficulty: "medium",
    prompt: "In two-way ANOVA, if the interaction is significant, you should:",
    answer: "Interpret simple main effects rather than main effects alone.",
    choices: ["Ignore the main effects entirely.", "Interpret simple main effects rather than main effects alone.", "Rerun as one-way ANOVA.", "Remove one factor."],
    explanation: "Step 1: A significant interaction means main effects are qualified by the other factor. Simple main effects (effect of A at each level of B) give a clearer picture. Final answer: Interpret simple main effects rather than main effects alone." }),
  p({ id: "anova-calc-3", topicId: "anova", section: "f-test", type: "numeric", difficulty: "medium",
    prompt: "$k=3$ groups, $N=30$. $\\text{df}_{\\text{between}}=$ and $\\text{df}_{\\text{within}}=$ respectively. Give $\\text{df}_{\\text{within}}$.",
    answer: "27",
    explanation: "Step 1: $\\text{df}_W=N-k=30-3=27$. Final answer: $27$." }),
  p({ id: "anova-assume-4", topicId: "anova", section: "assumptions", type: "mcq", difficulty: "medium",
    prompt: "A Q-Q plot is used in ANOVA to check the assumption of:",
    answer: "Normality of residuals.",
    choices: ["Equal variances.", "Normality of residuals.", "Independence.", "Equal sample sizes."],
    explanation: "Step 1: Q-Q plots compare residuals to a normal distribution. Points near the line indicate normality. Final answer: Normality of residuals." }),
  p({ id: "anova-calc-4", topicId: "anova", section: "f-test", type: "numeric", difficulty: "medium",
    prompt: "$\\text{MS}_B=40$, $\\text{MS}_W=8$. Find $F$.",
    answer: "5",
    explanation: "Step 1: $F=\\text{MS}_B/\\text{MS}_W=40/8=5$. Final answer: $5$." }),
  p({ id: "anova-posthoc-5", topicId: "anova", section: "post-hoc", type: "mcq", difficulty: "medium",
    prompt: "Tukey's HSD is more powerful than Bonferroni when:",
    answer: "All pairwise comparisons are of interest.",
    choices: ["Only one comparison is planned.", "All pairwise comparisons are of interest.", "The sample sizes are unequal.", "The $F$-test is not significant."],
    explanation: "Step 1: Tukey's HSD is designed specifically for all pairwise comparisons and is less conservative than Bonferroni in that setting. Final answer: All pairwise comparisons are of interest." }),
  p({ id: "anova-two-way-4", topicId: "anova", section: "two-way", type: "numeric", difficulty: "medium",
    prompt: "Two-way ANOVA: Factor A has $a=3$ levels, Factor B has $b=2$ levels, $n=5$ per cell. Find $\\text{df}_{\\text{interaction}}$.",
    answer: "2",
    explanation: "Step 1: $\\text{df}_{A\\times B}=(a-1)(b-1)=(3-1)(2-1)=2$. Final answer: $2$." }),
  p({ id: "anova-calc-5", topicId: "anova", section: "f-test", type: "numeric", difficulty: "medium",
    prompt: "ANOVA table: $SS_B=90$, $\\text{df}_B=2$; $SS_W=180$, $\\text{df}_W=27$. Find $\\text{MS}_W$.",
    answer: "6.67",
    explanation: "Step 1: $\\text{MS}_W=SS_W/\\text{df}_W=180/27\\approx6.67$. Final answer: $6.67$." }),

  // --- Hard (10) ---
  p({ id: "anova-f-3", topicId: "anova", section: "f-test", type: "numeric", difficulty: "hard",
    prompt: "ANOVA: $SS_B=90$, $\\text{df}_B=2$; $SS_W=180$, $\\text{df}_W=27$. Find $F$.",
    answer: "6.75",
    explanation: "Step 1: $\\text{MS}_B=90/2=45$. $\\text{MS}_W=180/27\\approx6.667$. $F=45/6.667\\approx6.75$. Final answer: $6.75$." }),
  p({ id: "anova-eta-2", topicId: "anova", section: "f-test", type: "numeric", difficulty: "hard",
    prompt: "Convert $F=6.75$ with $\\text{df}_B=2$ to $\\eta^2$ using $\\eta^2=F\\cdot\\text{df}_B/(F\\cdot\\text{df}_B+\\text{df}_W)$. $\\text{df}_W=27$.",
    answer: "0.333",
    explanation: "Step 1: $\\eta^2=6.75\\times2/(6.75\\times2+27)=13.5/(13.5+27)=13.5/40.5\\approx0.333$. Final answer: $0.333$." }),
  p({ id: "anova-posthoc-6", topicId: "anova", section: "post-hoc", type: "mcq", difficulty: "hard",
    prompt: "Which post-hoc test is most appropriate when group sample sizes are unequal?",
    answer: "Games-Howell or Tukey-Kramer.",
    choices: ["Tukey's HSD (balanced only).", "Games-Howell or Tukey-Kramer.", "LSD (least significant difference).", "Scheffé for all contrasts."],
    explanation: "Step 1: Tukey's HSD assumes equal $n$. Games-Howell (unequal variances too) and Tukey-Kramer handle unequal sample sizes. Final answer: Games-Howell or Tukey-Kramer." }),
  p({ id: "anova-two-way-5", topicId: "anova", section: "two-way", type: "numeric", difficulty: "hard",
    prompt: "Two-way ANOVA: $a=3$, $b=4$, $n=2$ per cell. Find $\\text{df}_{\\text{error}}$.",
    answer: "12",
    explanation: "Step 1: $\\text{df}_{\\text{error}}=ab(n-1)=3\\times4\\times1=12$. Final answer: $12$." }),
  p({ id: "anova-assume-5", topicId: "anova", section: "assumptions", type: "mcq", difficulty: "hard",
    prompt: "ANOVA is considered robust to violations of normality when:",
    answer: "Sample sizes are equal and sufficiently large.",
    choices: ["Sample sizes are very small.", "Sample sizes are equal and sufficiently large.", "Variances are very different.", "There are only two groups."],
    explanation: "Step 1: By the CLT, the sampling distribution of group means approaches normality with large $n$. Balanced designs also mitigate normality violations. Final answer: Sample sizes are equal and sufficiently large." }),
  p({ id: "anova-f-4", topicId: "anova", section: "f-test", type: "mcq", difficulty: "hard",
    prompt: "A significant $F$-test in one-way ANOVA with $k=5$ groups tells you:",
    answer: "At least one pair of group means differs, but not which pair.",
    choices: ["All pairs differ.", "At least one pair of group means differs, but not which pair.", "The largest mean differs from the smallest.", "All groups have different variances."],
    explanation: "Step 1: $F$-test is an omnibus test. It only indicates that at least one mean differs. Post-hoc tests are needed to identify specific pairs. Final answer: At least one pair of group means differs, but not which pair." }),
  p({ id: "anova-two-way-6", topicId: "anova", section: "two-way", type: "mcq", difficulty: "hard",
    prompt: "When interpreting two-way ANOVA with a significant interaction, lines in an interaction plot that:",
    answer: "Cross or are not parallel indicate interaction.",
    choices: ["Are parallel indicate interaction.", "Cross or are not parallel indicate interaction.", "Converge mean no interaction.", "Are horizontal indicate interaction."],
    explanation: "Step 1: Parallel lines in an interaction plot indicate no interaction (additive effects). Non-parallel/crossing lines indicate an interaction. Final answer: Cross or are not parallel indicate interaction." }),
  p({ id: "anova-calc-6", topicId: "anova", section: "f-test", type: "numeric", difficulty: "hard",
    prompt: "Grand mean $\\bar{x}_{..}=10$, 3 groups each $n=4$: group means $8,10,12$. Find $SS_B$.",
    answer: "32",
    explanation: "Step 1: $SS_B=n\\sum(\\bar{x}_i-\\bar{x}_{..})^2=4[(8-10)^2+(10-10)^2+(12-10)^2]=4[4+0+4]=32$. Final answer: $32$." }),
  p({ id: "anova-posthoc-7", topicId: "anova", section: "post-hoc", type: "mcq", difficulty: "hard",
    prompt: "Scheffé's test is the most conservative post-hoc test because it:",
    answer: "Controls for all possible contrasts, not just pairwise comparisons.",
    choices: ["Only tests adjacent means.", "Controls for all possible contrasts, not just pairwise comparisons.", "Uses a $t$-distribution.", "Requires equal sample sizes."],
    explanation: "Step 1: Scheffé controls Type I error for all possible linear contrasts (not just pairwise), making it very conservative but flexible. Final answer: Controls for all possible contrasts, not just pairwise comparisons." }),
  p({ id: "anova-two-way-7", topicId: "anova", section: "two-way", type: "numeric", difficulty: "hard",
    prompt: "Two-way ANOVA: Factor A ($a=2$), Factor B ($b=3$), $n=4$ per cell. Total $N=24$. Find $\\text{df}_{\\text{total}}$.",
    answer: "23",
    explanation: "Step 1: $\\text{df}_{\\text{total}}=N-1=24-1=23$. Final answer: $23$." }),
];
