import type { Problem } from "../shared-types";

const p = (problem: Problem) => problem;

export const descriptiveProblems: Problem[] = [
  // --- Easy (14) ---
  p({ id: "desc-mean-1", topicId: "descriptive", section: "mean", type: "numeric", difficulty: "easy",
    prompt: "Find the mean of $\\{4,8,6,5,7\\}$.",
    answer: "6",
    explanation: "Step 1: Sum $=4+8+6+5+7=30$. Step 2: Mean $=30/5=6$. Final answer: $6$." }),
  p({ id: "desc-median-1", topicId: "descriptive", section: "median", type: "numeric", difficulty: "easy",
    prompt: "Find the median of $\\{3,7,1,9,5\\}$.",
    answer: "5",
    explanation: "Step 1: Sort: $1,3,5,7,9$. Step 2: Middle value (3rd of 5) $=5$. Final answer: $5$." }),
  p({ id: "desc-mean-2", topicId: "descriptive", section: "mean", type: "numeric", difficulty: "easy",
    prompt: "Find the range of $\\{12,5,8,20,3\\}$.",
    answer: "17",
    explanation: "Step 1: Max $=20$, Min $=3$. Step 2: Range $=20-3=17$. Final answer: $17$." }),
  p({ id: "desc-variance-1", topicId: "descriptive", section: "variance", type: "numeric", difficulty: "easy",
    prompt: "The population variance of a dataset is $16$. What is the population standard deviation?",
    answer: "4",
    explanation: "Step 1: $\\sigma=\\sqrt{\\sigma^2}=\\sqrt{16}=4$. Final answer: $4$." }),
  p({ id: "desc-mean-3", topicId: "descriptive", section: "mean", type: "numeric", difficulty: "easy",
    prompt: "Find the mean of $\\{10,20,30,40,50\\}$.",
    answer: "30",
    explanation: "Step 1: Sum $=150$. Step 2: Mean $=150/5=30$. Final answer: $30$." }),
  p({ id: "desc-median-2", topicId: "descriptive", section: "median", type: "numeric", difficulty: "easy",
    prompt: "Find the median of $\\{2,4,6,8\\}$ (even number of values).",
    answer: "5",
    explanation: "Step 1: Sorted: $2,4,6,8$. Step 2: Median $=(4+6)/2=5$. Final answer: $5$." }),
  p({ id: "desc-mean-4", topicId: "descriptive", section: "mean", type: "mcq", difficulty: "easy",
    prompt: "Which measure of central tendency is most affected by outliers?",
    answer: "Mean",
    choices: ["Mean", "Median", "Mode", "Range"],
    explanation: "Step 1: The mean uses all values, so extreme outliers pull it toward them. The median is resistant to outliers. Final answer: Mean." }),
  p({ id: "desc-variance-2", topicId: "descriptive", section: "variance", type: "numeric", difficulty: "easy",
    prompt: "If all values in a dataset are the same (e.g., $\\{5,5,5,5\\}$), the variance is:",
    answer: "0",
    explanation: "Step 1: All deviations from the mean are $0$. Step 2: Variance $=0$. Final answer: $0$." }),
  p({ id: "desc-percentiles-1", topicId: "descriptive", section: "percentiles", type: "mcq", difficulty: "easy",
    prompt: "The median is the same as which percentile?",
    answer: "50th percentile",
    choices: ["25th percentile", "50th percentile", "75th percentile", "100th percentile"],
    explanation: "Step 1: The median divides data at the midpoint: 50% below, 50% above. It is the 50th percentile. Final answer: 50th percentile." }),
  p({ id: "desc-visualization-1", topicId: "descriptive", section: "visualization", type: "mcq", difficulty: "easy",
    prompt: "A histogram shows:",
    answer: "The frequency distribution of a continuous variable.",
    choices: ["Relationship between two variables.", "The frequency distribution of a continuous variable.", "Proportions of categories.", "Only the mean and median."],
    explanation: "Step 1: Histograms display the distribution (frequency or relative frequency) of a single quantitative variable. Final answer: The frequency distribution of a continuous variable." }),
  p({ id: "desc-mean-5", topicId: "descriptive", section: "mean", type: "numeric", difficulty: "easy",
    prompt: "A dataset has $n=5$ values with sum $=45$. What is the mean?",
    answer: "9",
    explanation: "Step 1: Mean $=\\sum x_i/n=45/5=9$. Final answer: $9$." }),
  p({ id: "desc-percentiles-2", topicId: "descriptive", section: "percentiles", type: "mcq", difficulty: "easy",
    prompt: "The interquartile range (IQR) is defined as:",
    answer: "$Q_3-Q_1$",
    choices: ["$Q_2-Q_1$", "$Q_3-Q_1$", "$Q_3-Q_2$", "Max $-$ Min"],
    explanation: "Step 1: IQR $= Q_3-Q_1$, measuring the spread of the middle 50% of data. Final answer: $Q_3-Q_1$." }),
  p({ id: "desc-visualization-2", topicId: "descriptive", section: "visualization", type: "mcq", difficulty: "easy",
    prompt: "A box plot displays:",
    answer: "Minimum, $Q_1$, Median, $Q_3$, Maximum.",
    choices: ["Mean and standard deviation.", "Minimum, $Q_1$, Median, $Q_3$, Maximum.", "Only the median.", "A frequency distribution."],
    explanation: "Step 1: Box plots (box-and-whisker plots) show the five-number summary: Min, $Q_1$, Median, $Q_3$, Max. Final answer: Minimum, $Q_1$, Median, $Q_3$, Maximum." }),
  p({ id: "desc-variance-3", topicId: "descriptive", section: "variance", type: "mcq", difficulty: "easy",
    prompt: "The sample variance uses $n-1$ in the denominator (not $n$) because:",
    answer: "It makes $s^2$ an unbiased estimator of $\\sigma^2$.",
    choices: ["It's easier to compute.", "It makes $s^2$ an unbiased estimator of $\\sigma^2$.", "It always gives a smaller value.", "It matches the population formula."],
    explanation: "Step 1: Dividing by $n-1$ (Bessel's correction) corrects for the underestimate that arises when using $\\bar{x}$ instead of $\\mu$. Final answer: It makes $s^2$ an unbiased estimator of $\\sigma^2$." }),

  // --- Medium (16) ---
  p({ id: "desc-variance-4", topicId: "descriptive", section: "variance", type: "numeric", difficulty: "medium",
    prompt: "Find the population variance of $\\{2,4,4,4,5,5,7,9\\}$. The mean is $5$.",
    answer: "4",
    explanation: "Step 1: Squared deviations: $9,1,1,1,0,0,4,16$. Step 2: Sum $=32$. Step 3: $\\sigma^2=32/8=4$. Final answer: $4$." }),
  p({ id: "desc-mean-6", topicId: "descriptive", section: "mean", type: "numeric", difficulty: "medium",
    prompt: "A student scores $70,80,90,85,75$ on five tests. Find the mean score.",
    answer: "80",
    explanation: "Step 1: Sum $=70+80+90+85+75=400$. Step 2: Mean $=400/5=80$. Final answer: $80$." }),
  p({ id: "desc-percentiles-3", topicId: "descriptive", section: "percentiles", type: "numeric", difficulty: "medium",
    prompt: "For the sorted data $\\{10,20,30,40,50,60,70,80\\}$, find $Q_1$ (25th percentile). Use the method: $Q_1$ is the median of the lower half.",
    answer: "25",
    explanation: "Step 1: Lower half: $\\{10,20,30,40\\}$. Step 2: Median $=(20+30)/2=25$. Final answer: $25$." }),
  p({ id: "desc-visualization-3", topicId: "descriptive", section: "visualization", type: "mcq", difficulty: "medium",
    prompt: "A distribution is positively (right) skewed when:",
    answer: "The mean is greater than the median.",
    choices: ["The mean equals the median.", "The mean is greater than the median.", "The mean is less than the median.", "The mode is the largest value."],
    explanation: "Step 1: Right skew: long tail on the right, pulling the mean rightward past the median. Final answer: The mean is greater than the median." }),
  p({ id: "desc-variance-5", topicId: "descriptive", section: "variance", type: "numeric", difficulty: "medium",
    prompt: "Compute the sample standard deviation of $\\{4,7,13,16\\}$. The mean is $10$.",
    answer: "5.477",
    explanation: "Step 1: Deviations: $-6,-3,3,6$. Squared: $36,9,9,36$. Sum $=90$. Step 2: $s^2=90/(4-1)=30$. Step 3: $s=\\sqrt{30}\\approx5.477$. Final answer: $5.477$." }),
  p({ id: "desc-percentiles-4", topicId: "descriptive", section: "percentiles", type: "numeric", difficulty: "medium",
    prompt: "For data $\\{1,2,3,4,5,6,7,8,9,10\\}$, the IQR is $Q_3-Q_1$. Find the IQR.",
    answer: "5",
    explanation: "Step 1: $Q_1=2.75$ (25th percentile of $1\\ldots10$)… using the lower/upper half method: lower half $\\{1,2,3,4,5\\}$: $Q_1=3$. Upper half $\\{6,7,8,9,10\\}$: $Q_3=8$. Step 2: IQR $=8-3=5$. Final answer: $5$." }),
  p({ id: "desc-mean-7", topicId: "descriptive", section: "mean", type: "numeric", difficulty: "medium",
    prompt: "A weighted mean: scores $60,70,80$ with weights $1,2,3$. Compute the weighted mean.",
    answer: "73.33",
    explanation: "Step 1: Weighted sum $=1(60)+2(70)+3(80)=60+140+240=440$. Step 2: Sum of weights $=6$. Step 3: Weighted mean $=440/6\\approx73.33$. Final answer: $73.33$." }),
  p({ id: "desc-visualization-4", topicId: "descriptive", section: "visualization", type: "mcq", difficulty: "medium",
    prompt: "Which plot is most appropriate for showing the relationship between two quantitative variables?",
    answer: "Scatter plot.",
    choices: ["Histogram.", "Box plot.", "Scatter plot.", "Bar chart."],
    explanation: "Step 1: Scatter plots display pairs of quantitative values to show association. Final answer: Scatter plot." }),
  p({ id: "desc-variance-6", topicId: "descriptive", section: "variance", type: "numeric", difficulty: "medium",
    prompt: "If $\\sigma^2=25$ for a population, what is $\\sigma$?",
    answer: "5",
    explanation: "Step 1: $\\sigma=\\sqrt{25}=5$. Final answer: $5$." }),
  p({ id: "desc-percentiles-5", topicId: "descriptive", section: "percentiles", type: "mcq", difficulty: "medium",
    prompt: "An outlier is conventionally defined as a value:",
    answer: "Below $Q_1-1.5\\cdot\\text{IQR}$ or above $Q_3+1.5\\cdot\\text{IQR}$.",
    choices: ["More than 2 standard deviations from the mean.", "Below $Q_1-1.5\\cdot\\text{IQR}$ or above $Q_3+1.5\\cdot\\text{IQR}$.", "Not equal to the mode.", "Less than the minimum."],
    explanation: "Step 1: The 1.5×IQR rule (Tukey fences) is the standard convention for outlier detection with box plots. Final answer: Below $Q_1-1.5\\cdot\\text{IQR}$ or above $Q_3+1.5\\cdot\\text{IQR}$." }),
  p({ id: "desc-mean-8", topicId: "descriptive", section: "mean", type: "mcq", difficulty: "medium",
    prompt: "For a symmetric, bell-shaped distribution, which is true?",
    answer: "Mean $=$ Median $=$ Mode.",
    choices: ["Mean $>$ Median.", "Mean $=$ Median $=$ Mode.", "Mean $<$ Median.", "Mode is undefined."],
    explanation: "Step 1: For a perfectly symmetric unimodal distribution, all three central tendency measures coincide. Final answer: Mean $=$ Median $=$ Mode." }),
  p({ id: "desc-visualization-5", topicId: "descriptive", section: "visualization", type: "mcq", difficulty: "medium",
    prompt: "The coefficient of variation (CV) is defined as:",
    answer: "$\\text{CV}=(s/\\bar{x})\\times100\\%$",
    choices: ["$\\text{CV}=\\bar{x}/s$", "$\\text{CV}=(s/\\bar{x})\\times100\\%$", "$\\text{CV}=s^2/\\bar{x}$", "$\\text{CV}=\\bar{x}-s$"],
    explanation: "Step 1: CV measures relative variability: $\\text{CV}=s/\\bar{x}\\times100\\%$. Useful for comparing datasets with different units or means. Final answer: $\\text{CV}=(s/\\bar{x})\\times100\\%$." }),
  p({ id: "desc-variance-7", topicId: "descriptive", section: "variance", type: "numeric", difficulty: "medium",
    prompt: "Dataset: $\\{6,6,6,6,6\\}$. What is the standard deviation?",
    answer: "0",
    explanation: "Step 1: All values equal the mean. Step 2: All deviations $=0$, so $s=0$. Final answer: $0$." }),
  p({ id: "desc-mean-9", topicId: "descriptive", section: "mean", type: "numeric", difficulty: "medium",
    prompt: "Find the mode of $\\{1,2,2,3,4,4,4,5\\}$.",
    answer: "4",
    explanation: "Step 1: Count frequencies: $1\\to1,2\\to2,3\\to1,4\\to3,5\\to1$. Step 2: Mode $=4$ (highest frequency). Final answer: $4$." }),
  p({ id: "desc-percentiles-6", topicId: "descriptive", section: "percentiles", type: "numeric", difficulty: "medium",
    prompt: "For sorted data $\\{5,10,15,20,25,30\\}$, find $Q_3$.",
    answer: "25",
    explanation: "Step 1: Upper half: $\\{20,25,30\\}$. Step 2: Median of upper half $=25$. Final answer: $25$." }),

  // --- Hard (10) ---
  p({ id: "desc-variance-8", topicId: "descriptive", section: "variance", type: "numeric", difficulty: "hard",
    prompt: "Find the sample variance of $\\{2,6,4,8,10\\}$. Mean $=6$.",
    answer: "10",
    explanation: "Step 1: Deviations: $-4,0,-2,2,4$. Squared: $16,0,4,4,16$. Sum $=40$. Step 2: $s^2=40/(5-1)=10$. Final answer: $10$." }),
  p({ id: "desc-mean-10", topicId: "descriptive", section: "mean", type: "numeric", difficulty: "hard",
    prompt: "If you remove the outlier $100$ from $\\{2,3,4,5,100\\}$, the mean changes from $22.8$ to:",
    answer: "3.5",
    explanation: "Step 1: Remove $100$: $\\{2,3,4,5\\}$. Step 2: Mean $=(2+3+4+5)/4=14/4=3.5$. Final answer: $3.5$." }),
  p({ id: "desc-percentiles-7", topicId: "descriptive", section: "percentiles", type: "numeric", difficulty: "hard",
    prompt: "For $n=20$ data values, a value at the 90th percentile has approximately $\\lfloor 0.9\\times20\\rfloor=18$ values below it. What is the index position?",
    answer: "18",
    explanation: "Step 1: $L=0.9\\times20=18$. Step 2: The 90th percentile is between the 18th and 19th sorted values; position index $\\approx18$. Final answer: $18$." }),
  p({ id: "desc-visualization-6", topicId: "descriptive", section: "visualization", type: "mcq", difficulty: "hard",
    prompt: "A dataset has mean $\\mu=50$ and $\\sigma=10$. By the empirical rule (68-95-99.7), approximately what percent of data falls within one standard deviation of the mean?",
    answer: "68%",
    choices: ["50%", "68%", "95%", "99.7%"],
    explanation: "Step 1: The empirical rule for roughly normal distributions: $\\sim68\\%$ within $\\mu\\pm\\sigma$, $\\sim95\\%$ within $\\mu\\pm2\\sigma$, $\\sim99.7\\%$ within $\\mu\\pm3\\sigma$. Final answer: $68\\%$." }),
  p({ id: "desc-variance-9", topicId: "descriptive", section: "variance", type: "numeric", difficulty: "hard",
    prompt: "A dataset has $\\bar{x}=10$ and $s=3$. A new dataset is formed by adding $5$ to every value. What is the new standard deviation?",
    answer: "3",
    explanation: "Step 1: Adding a constant shifts all values equally, so deviations from the new mean are unchanged. Step 2: $s$ remains $3$. Final answer: $3$." }),
  p({ id: "desc-mean-11", topicId: "descriptive", section: "mean", type: "numeric", difficulty: "hard",
    prompt: "Group A: $n=10$, $\\bar{x}=15$. Group B: $n=20$, $\\bar{x}=25$. What is the combined mean?",
    answer: "21.67",
    explanation: "Step 1: Total sum $=10(15)+20(25)=150+500=650$. Step 2: Combined mean $=650/30\\approx21.67$. Final answer: $21.67$." }),
  p({ id: "desc-visualization-7", topicId: "descriptive", section: "visualization", type: "numeric", difficulty: "hard",
    prompt: "A distribution has mean $\\mu=100$, $\\sigma=15$. By Chebyshev's inequality, at least what fraction of values fall within $k=2$ standard deviations? (Express as a fraction.)",
    answer: "0.75",
    explanation: "Step 1: Chebyshev: at least $1-1/k^2=1-1/4=3/4=0.75$. Final answer: $0.75$." }),
  p({ id: "desc-variance-10", topicId: "descriptive", section: "variance", type: "numeric", difficulty: "hard",
    prompt: "A dataset has $\\bar{x}=10$ and $s=3$. Every value is multiplied by $2$. What is the new standard deviation?",
    answer: "6",
    explanation: "Step 1: Multiplying all values by $c$ scales the standard deviation by $|c|$. Step 2: New $s=2\\times3=6$. Final answer: $6$." }),
  p({ id: "desc-percentiles-8", topicId: "descriptive", section: "percentiles", type: "mcq", difficulty: "hard",
    prompt: "A $z$-score of $z=2.5$ means the value is:",
    answer: "$2.5$ standard deviations above the mean.",
    choices: ["$2.5$ times the mean.", "$2.5$ standard deviations above the mean.", "At the 2.5th percentile.", "$2.5$ units above the median."],
    explanation: "Step 1: $z=(x-\\mu)/\\sigma$. A $z$-score of $2.5$ means $x$ is $2.5\\sigma$ above $\\mu$. Final answer: $2.5$ standard deviations above the mean." }),
  p({ id: "desc-mean-12", topicId: "descriptive", section: "mean", type: "numeric", difficulty: "hard",
    prompt: "The trimmed mean (10% trim) of $\\{1,2,3,\\ldots,10\\}$ removes the lowest and highest 10% then averages. Remove $1$ and $10$ from the 10-value set and compute the mean.",
    answer: "5.5",
    explanation: "Step 1: Remove lowest 10% ($=1$ value: $1$) and highest 10% ($=1$ value: $10$). Step 2: Remaining: $\\{2,3,4,5,6,7,8,9\\}$. Mean $=44/8=5.5$. Final answer: $5.5$." }),
];
