import type { Problem } from "../shared-types";

const p = (problem: Problem) => problem;

export const discreteDistributionProblems: Problem[] = [
  // --- Easy (14) ---
  p({ id: "disc-ev-1", topicId: "discrete-distributions", section: "expected-value", type: "numeric", difficulty: "easy",
    prompt: "A fair die is rolled. What is the expected value $E(X)$?",
    answer: "3.5",
    explanation: "Step 1: $E(X)=\\sum x_i P(X=x_i)=1(\\frac{1}{6})+2(\\frac{1}{6})+\\cdots+6(\\frac{1}{6})=21/6=3.5$. Final answer: $3.5$." }),
  p({ id: "disc-binom-mean-1", topicId: "discrete-distributions", section: "binomial", type: "numeric", difficulty: "easy",
    prompt: "A binomial random variable has $n=20$ trials and success probability $p=0.4$. What is the mean?",
    answer: "8",
    explanation: "Step 1: $\\mu=np=20\\times0.4=8$. Final answer: $8$." }),
  p({ id: "disc-binom-var-1", topicId: "discrete-distributions", section: "binomial", type: "numeric", difficulty: "easy",
    prompt: "A binomial variable has $n=20$, $p=0.4$. What is the variance?",
    answer: "4.8",
    explanation: "Step 1: $\\sigma^2=np(1-p)=20(0.4)(0.6)=4.8$. Final answer: $4.8$." }),
  p({ id: "disc-poisson-mean-1", topicId: "discrete-distributions", section: "poisson", type: "numeric", difficulty: "easy",
    prompt: "A Poisson random variable has $\\lambda=3$. What is its mean?",
    answer: "3",
    explanation: "Step 1: For Poisson, $E(X)=\\lambda=3$. Final answer: $3$." }),
  p({ id: "disc-poisson-var-1", topicId: "discrete-distributions", section: "poisson", type: "numeric", difficulty: "easy",
    prompt: "A Poisson random variable has $\\lambda=3$. What is its variance?",
    answer: "3",
    explanation: "Step 1: For Poisson, $\\text{Var}(X)=\\lambda=3$. Final answer: $3$." }),
  p({ id: "disc-ev-2", topicId: "discrete-distributions", section: "expected-value", type: "numeric", difficulty: "easy",
    prompt: "A game pays \\$5 with probability $0.4$ and $-$\\$2 with probability $0.6$. What is the expected value?",
    answer: "0.8",
    explanation: "Step 1: $E(X)=5(0.4)+(-2)(0.6)=2.0-1.2=0.8$. Final answer: $0.8$." }),
  p({ id: "disc-binom-1", topicId: "discrete-distributions", section: "binomial", type: "mcq", difficulty: "easy",
    prompt: "For $X\\sim\\text{Binomial}(n,p)$, what are the requirements?",
    answer: "Fixed $n$, independent trials, constant $p$, two outcomes.",
    choices: ["Variable $n$, dependent trials.", "Fixed $n$, independent trials, constant $p$, two outcomes.", "Any number of outcomes.", "Only applicable to normal distributions."],
    explanation: "Step 1: Binomial requires: (1) fixed number of trials $n$, (2) independent trials, (3) constant success probability $p$, (4) binary outcome (success/failure). Final answer: Fixed $n$, independent trials, constant $p$, two outcomes." }),
  p({ id: "disc-poisson-1", topicId: "discrete-distributions", section: "poisson", type: "mcq", difficulty: "easy",
    prompt: "The Poisson distribution is appropriate when modeling:",
    answer: "The number of rare events in a fixed interval.",
    choices: ["The proportion of successes in $n$ trials.", "The number of rare events in a fixed interval.", "A continuous measurement.", "The time until the first event."],
    explanation: "Step 1: Poisson models counts of rare, independent events in a fixed time/space interval with constant average rate $\\lambda$. Final answer: The number of rare events in a fixed interval." }),
  p({ id: "disc-ev-3", topicId: "discrete-distributions", section: "expected-value", type: "numeric", difficulty: "easy",
    prompt: "$X$ takes values $1,2,3$ with equal probability $1/3$. Find $E(X)$.",
    answer: "2",
    explanation: "Step 1: $E(X)=1(1/3)+2(1/3)+3(1/3)=6/3=2$. Final answer: $2$." }),
  p({ id: "disc-binom-2", topicId: "discrete-distributions", section: "binomial", type: "numeric", difficulty: "easy",
    prompt: "A fair die is rolled $60$ times. Expected number of sixes?",
    answer: "10",
    explanation: "Step 1: $p=1/6$, $n=60$. $E(X)=np=60/6=10$. Final answer: $10$." }),
  p({ id: "disc-ev-4", topicId: "discrete-distributions", section: "expected-value", type: "mcq", difficulty: "easy",
    prompt: "For a random variable $X$, $\\text{Var}(X)=E(X^2)-[E(X)]^2$. If $E(X)=4$ and $E(X^2)=20$, $\\text{Var}(X)=$",
    answer: "4",
    choices: ["$0$", "$4$", "$16$", "$20$"],
    explanation: "Step 1: $\\text{Var}(X)=20-4^2=20-16=4$. Final answer: $4$." }),
  p({ id: "disc-poisson-2", topicId: "discrete-distributions", section: "poisson", type: "numeric", difficulty: "easy",
    prompt: "Calls arrive at $\\lambda=5$ per hour. What is the expected number of calls in $2$ hours?",
    answer: "10",
    explanation: "Step 1: $\\lambda_{2h}=5\\times2=10$. Final answer: $10$." }),
  p({ id: "disc-binom-3", topicId: "discrete-distributions", section: "binomial", type: "numeric", difficulty: "easy",
    prompt: "A binomial variable $X\\sim B(10,0.3)$. Compute the standard deviation.",
    answer: "1.449",
    explanation: "Step 1: $\\sigma=\\sqrt{np(1-p)}=\\sqrt{10(0.3)(0.7)}=\\sqrt{2.1}\\approx1.449$. Final answer: $1.449$." }),
  p({ id: "disc-ev-5", topicId: "discrete-distributions", section: "expected-value", type: "mcq", difficulty: "easy",
    prompt: "If $c$ is a constant, then $E(cX)=$",
    answer: "$cE(X)$",
    choices: ["$E(X)+c$", "$cE(X)$", "$c^2E(X)$", "$E(X)$"],
    explanation: "Step 1: Linearity of expectation: $E(cX)=c\\cdot E(X)$. Final answer: $cE(X)$." }),

  // --- Medium (16) ---
  p({ id: "disc-binom-4", topicId: "discrete-distributions", section: "binomial", type: "numeric", difficulty: "medium",
    prompt: "A fair coin is flipped $4$ times. $P(X=2)=$",
    answer: "0.375",
    explanation: "Step 1: $P(X=2)=\\binom{4}{2}(0.5)^2(0.5)^2=6(0.0625)=0.375$. Final answer: $0.375$." }),
  p({ id: "disc-poisson-3", topicId: "discrete-distributions", section: "poisson", type: "numeric", difficulty: "medium",
    prompt: "A call center receives $\\lambda=3$ calls/min. $P(X=0)=e^{-3}\\approx0.050$. Find $P(X=1)$.",
    answer: "0.149",
    explanation: "Step 1: $P(X=1)=e^{-3}\\cdot3^1/1!=3e^{-3}\\approx3(0.04979)\\approx0.149$. Final answer: $0.149$." }),
  p({ id: "disc-binom-5", topicId: "discrete-distributions", section: "binomial", type: "numeric", difficulty: "medium",
    prompt: "For $X\\sim B(5,0.6)$, find $P(X=3)$.",
    answer: "0.3456",
    explanation: "Step 1: $P(X=3)=\\binom{5}{3}(0.6)^3(0.4)^2=10(0.216)(0.16)=10(0.03456)=0.3456$. Final answer: $0.3456$." }),
  p({ id: "disc-ev-6", topicId: "discrete-distributions", section: "expected-value", type: "numeric", difficulty: "medium",
    prompt: "A lottery ticket costs \\$2. You win \\$10 with probability $0.1$ and \\$0 with probability $0.9$. What is the expected profit?",
    answer: "-1",
    explanation: "Step 1: $E(\\text{profit})=10(0.1)+0(0.9)-2=1-2=-1$. Final answer: $-1$." }),
  p({ id: "disc-binom-6", topicId: "discrete-distributions", section: "binomial", type: "numeric", difficulty: "medium",
    prompt: "For $X\\sim B(10,0.5)$, find $P(X\\leq1)=P(X=0)+P(X=1)$.",
    answer: "0.0107",
    explanation: "Step 1: $P(X=0)=(0.5)^{10}=1/1024\\approx0.000977$. Step 2: $P(X=1)=10(0.5)^{10}\\approx0.00977$. Step 3: Sum$\\approx0.0107$. Final answer: $0.0107$." }),
  p({ id: "disc-poisson-4", topicId: "discrete-distributions", section: "poisson", type: "mcq", difficulty: "medium",
    prompt: "For $X\\sim\\text{Poisson}(\\lambda)$, which is true?",
    answer: "$E(X)=\\text{Var}(X)=\\lambda$",
    choices: ["$E(X)=\\lambda,\\;\\text{Var}(X)=\\lambda^2$", "$E(X)=\\text{Var}(X)=\\lambda$", "$E(X)=1/\\lambda$", "$\\text{Var}(X)=\\sqrt{\\lambda}$"],
    explanation: "Step 1: A key property of the Poisson: both mean and variance equal $\\lambda$. Final answer: $E(X)=\\text{Var}(X)=\\lambda$." }),
  p({ id: "disc-ev-7", topicId: "discrete-distributions", section: "expected-value", type: "numeric", difficulty: "medium",
    prompt: "Two independent random variables: $E(X)=3$, $E(Y)=5$. Find $E(2X+3Y)$.",
    answer: "21",
    explanation: "Step 1: Linearity: $E(2X+3Y)=2E(X)+3E(Y)=2(3)+3(5)=6+15=21$. Final answer: $21$." }),
  p({ id: "disc-binom-7", topicId: "discrete-distributions", section: "binomial", type: "numeric", difficulty: "medium",
    prompt: "A basketball player has a free-throw success rate of $0.7$. In $10$ shots, what is the expected number made?",
    answer: "7",
    explanation: "Step 1: $E(X)=np=10(0.7)=7$. Final answer: $7$." }),
  p({ id: "disc-poisson-5", topicId: "discrete-distributions", section: "poisson", type: "numeric", difficulty: "medium",
    prompt: "A factory averages $2$ defects per item. Using Poisson, $P(X=2)=$",
    answer: "0.2707",
    explanation: "Step 1: $P(X=2)=e^{-2}2^2/2!=e^{-2}\\cdot4/2=2e^{-2}\\approx2(0.1353)=0.2707$. Final answer: $0.2707$." }),
  p({ id: "disc-binom-8", topicId: "discrete-distributions", section: "binomial", type: "mcq", difficulty: "medium",
    prompt: "When is the normal approximation to the binomial valid?",
    answer: "When $np\\geq5$ and $n(1-p)\\geq5$.",
    choices: ["When $n>10$.", "When $np\\geq5$ and $n(1-p)\\geq5$.", "When $p=0.5$.", "When $n>100$."],
    explanation: "Step 1: The rule of thumb requires both $np\\geq5$ and $nq\\geq5$ to ensure the binomial is approximately normal. Final answer: When $np\\geq5$ and $n(1-p)\\geq5$." }),
  p({ id: "disc-ev-8", topicId: "discrete-distributions", section: "expected-value", type: "numeric", difficulty: "medium",
    prompt: "If $\\text{Var}(X)=9$ and $\\text{Var}(Y)=16$ and $X,Y$ independent, find $\\text{Var}(X+Y)$.",
    answer: "25",
    explanation: "Step 1: For independent $X,Y$: $\\text{Var}(X+Y)=\\text{Var}(X)+\\text{Var}(Y)=9+16=25$. Final answer: $25$." }),
  p({ id: "disc-poisson-6", topicId: "discrete-distributions", section: "poisson", type: "numeric", difficulty: "medium",
    prompt: "A website gets $\\lambda=10$ visits/hour. $P(X=10)=e^{-10}10^{10}/10!$. $P(X=10)\\approx$",
    answer: "0.1251",
    explanation: "Step 1: $P(X=10)=e^{-10}10^{10}/10!$. Using Stirling or table: $\\approx0.1251$. Final answer: $0.1251$." }),
  p({ id: "disc-binom-9", topicId: "discrete-distributions", section: "binomial", type: "numeric", difficulty: "medium",
    prompt: "For $X\\sim B(n=8,p=0.25)$, find $P(X=0)$.",
    answer: "0.1001",
    explanation: "Step 1: $P(X=0)=(0.75)^8=0.75^8$. $0.75^2=0.5625$, $0.75^4=0.3164$, $0.75^8\\approx0.1001$. Final answer: $0.1001$." }),
  p({ id: "disc-ev-9", topicId: "discrete-distributions", section: "expected-value", type: "mcq", difficulty: "medium",
    prompt: "The geometric distribution models:",
    answer: "The number of trials until the first success.",
    choices: ["The number of successes in $n$ trials.", "The number of trials until the first success.", "Rare events in a fixed interval.", "A continuous waiting time."],
    explanation: "Step 1: Geometric distribution: $X=$ number of trials until (and including) the first success, with $P(X=k)=(1-p)^{k-1}p$. Final answer: The number of trials until the first success." }),
  p({ id: "disc-poisson-7", topicId: "discrete-distributions", section: "poisson", type: "numeric", difficulty: "medium",
    prompt: "If $X\\sim\\text{Poisson}(4)$, find $P(X=0)$.",
    answer: "0.0183",
    explanation: "Step 1: $P(X=0)=e^{-4}\\approx0.01832$. Final answer: $0.0183$." }),

  // --- Hard (10) ---
  p({ id: "disc-binom-10", topicId: "discrete-distributions", section: "binomial", type: "numeric", difficulty: "hard",
    prompt: "For $X\\sim B(6,0.3)$, find $P(X\\geq2)=1-P(X=0)-P(X=1)$.",
    answer: "0.5798",
    explanation: "Step 1: $P(X=0)=(0.7)^6=0.1176$. Step 2: $P(X=1)=6(0.3)(0.7)^5=6(0.3)(0.1681)=0.3025$. Step 3: $P(X\\geq2)=1-0.1176-0.3025=0.5799\\approx0.5798$. Final answer: $0.5798$." }),
  p({ id: "disc-ev-10", topicId: "discrete-distributions", section: "expected-value", type: "numeric", difficulty: "hard",
    prompt: "A geometric distribution with $p=0.2$. Find $E(X)=1/p$.",
    answer: "5",
    explanation: "Step 1: $E(X)=1/p=1/0.2=5$. Final answer: $5$." }),
  p({ id: "disc-poisson-8", topicId: "discrete-distributions", section: "poisson", type: "numeric", difficulty: "hard",
    prompt: "Accidents occur at $\\lambda=2$/week. What is $P(X\\geq1)$ in a given week?",
    answer: "0.8647",
    explanation: "Step 1: $P(X\\geq1)=1-P(X=0)=1-e^{-2}\\approx1-0.1353=0.8647$. Final answer: $0.8647$." }),
  p({ id: "disc-binom-11", topicId: "discrete-distributions", section: "binomial", type: "mcq", difficulty: "hard",
    prompt: "For large $n$ and small $p$ (rare events), the binomial distribution is approximated by:",
    answer: "Poisson with $\\lambda=np$.",
    choices: ["Normal with $\\mu=np$.", "Poisson with $\\lambda=np$.", "Uniform distribution.", "Exponential distribution."],
    explanation: "Step 1: The Poisson approximation to binomial applies when $n$ is large and $p$ is small, with $\\lambda=np$. Final answer: Poisson with $\\lambda=np$." }),
  p({ id: "disc-ev-11", topicId: "discrete-distributions", section: "expected-value", type: "numeric", difficulty: "hard",
    prompt: "For $X\\sim\\text{Geometric}(p=0.4)$, find $\\text{Var}(X)=(1-p)/p^2$.",
    answer: "3.75",
    explanation: "Step 1: $\\text{Var}(X)=(1-0.4)/0.4^2=0.6/0.16=3.75$. Final answer: $3.75$." }),
  p({ id: "disc-poisson-9", topicId: "discrete-distributions", section: "poisson", type: "numeric", difficulty: "hard",
    prompt: "Two independent Poisson variables: $X\\sim P(2)$, $Y\\sim P(3)$. $\\text{Var}(X+Y)=$",
    answer: "5",
    explanation: "Step 1: For independent Poisson: $X+Y\\sim P(\\lambda_1+\\lambda_2)$. $\\text{Var}(X+Y)=2+3=5$. Final answer: $5$." }),
  p({ id: "disc-binom-12", topicId: "discrete-distributions", section: "binomial", type: "numeric", difficulty: "hard",
    prompt: "In a class of $30$ students, each independently passes with probability $0.8$. What is the expected number who pass?",
    answer: "24",
    explanation: "Step 1: $E(X)=np=30(0.8)=24$. Final answer: $24$." }),
  p({ id: "disc-ev-12", topicId: "discrete-distributions", section: "expected-value", type: "mcq", difficulty: "hard",
    prompt: "A negative binomial distribution models:",
    answer: "The number of trials to achieve $r$ successes.",
    choices: ["The number of successes in $n$ trials.", "The number of trials to achieve $r$ successes.", "Rare events per unit time.", "Continuous wait times."],
    explanation: "Step 1: The negative binomial generalizes geometric: count trials until $r$ successes occur. Final answer: The number of trials to achieve $r$ successes." }),
  p({ id: "disc-poisson-10", topicId: "discrete-distributions", section: "poisson", type: "numeric", difficulty: "hard",
    prompt: "An insurance company receives $\\lambda=1.5$ claims per day. $P(X=3)=$",
    answer: "0.1255",
    explanation: "Step 1: $P(X=3)=e^{-1.5}(1.5)^3/3!=e^{-1.5}(3.375)/6\\approx0.2231(0.5625)\\approx0.1255$. Final answer: $0.1255$." }),
  p({ id: "disc-binom-13", topicId: "discrete-distributions", section: "binomial", type: "numeric", difficulty: "hard",
    prompt: "For $X\\sim B(100,0.03)$, approximate with Poisson: $\\lambda=np=3$. $P(X=0)\\approx$",
    answer: "0.0498",
    explanation: "Step 1: $P(X=0)\\approx e^{-3}\\approx0.0498$. Final answer: $0.0498$." }),
];
