import type { Problem } from "../shared-types";

const p = (problem: Problem) => problem;

export const hypothesisTestingProblems: Problem[] = [
  // --- Easy (14) ---
  p({ id: "hyp-pval-1", topicId: "hypothesis-testing", section: "p-value", type: "mcq", difficulty: "easy",
    prompt: "At $\\alpha=0.05$, a test yields $p=0.03$. You should:",
    answer: "Reject $H_0$",
    choices: ["Reject $H_0$", "Fail to reject $H_0$", "Accept $H_0$", "Accept $H_a$"],
    explanation: "Step 1: $p=0.03<0.05=\\alpha\\Rightarrow$ reject $H_0$. Final answer: Reject $H_0$." }),
  p({ id: "hyp-type1-1", topicId: "hypothesis-testing", section: "errors", type: "mcq", difficulty: "easy",
    prompt: "A Type I error occurs when:",
    answer: "Reject $H_0$ when $H_0$ is true.",
    choices: ["Reject $H_0$ when $H_0$ is true.", "Fail to reject $H_0$ when $H_0$ is false.", "Reject $H_a$ when $H_a$ is true.", "Accept $H_0$ when $H_a$ is true."],
    explanation: "Step 1: Type I = false positive: rejecting a true $H_0$. Probability $=\\alpha$. Final answer: Reject $H_0$ when $H_0$ is true." }),
  p({ id: "hyp-type2-1", topicId: "hypothesis-testing", section: "errors", type: "mcq", difficulty: "easy",
    prompt: "A Type II error occurs when:",
    answer: "Fail to reject $H_0$ when $H_0$ is false.",
    choices: ["Reject $H_0$ when $H_0$ is true.", "Fail to reject $H_0$ when $H_0$ is false.", "Correctly reject $H_0$.", "Correctly fail to reject $H_0$."],
    explanation: "Step 1: Type II = false negative: failing to reject a false $H_0$. Probability $=\\beta$. Final answer: Fail to reject $H_0$ when $H_0$ is false." }),
  p({ id: "hyp-pval-2", topicId: "hypothesis-testing", section: "p-value", type: "mcq", difficulty: "easy",
    prompt: "The $p$-value is the probability of observing:",
    answer: "A test statistic as extreme or more extreme, given $H_0$ is true.",
    choices: ["The null hypothesis being true.", "A test statistic as extreme or more extreme, given $H_0$ is true.", "The alternative being true.", "A Type I error."],
    explanation: "Step 1: $p$-value $= P(\\text{statistic}\\geq\\text{observed}\\mid H_0)$. It measures how surprising the data is under $H_0$. Final answer: A test statistic as extreme or more extreme, given $H_0$ is true." }),
  p({ id: "hyp-alpha-1", topicId: "hypothesis-testing", section: "p-value", type: "mcq", difficulty: "easy",
    prompt: "The significance level $\\alpha$ represents:",
    answer: "The probability of a Type I error.",
    choices: ["The probability of a Type II error.", "The probability of a Type I error.", "The $p$-value threshold for Type II error.", "The power of the test."],
    explanation: "Step 1: $\\alpha=P(\\text{Type I error})=P(\\text{reject }H_0\\mid H_0\\text{ true})$. Final answer: The probability of a Type I error." }),
  p({ id: "hyp-null-1", topicId: "hypothesis-testing", section: "p-value", type: "mcq", difficulty: "easy",
    prompt: "The null hypothesis $H_0$ typically states:",
    answer: "No effect or no difference.",
    choices: ["There is an effect.", "No effect or no difference.", "The alternative is true.", "The sample mean equals zero."],
    explanation: "Step 1: $H_0$ is the default assumption of no effect/difference. It is the hypothesis we test against. Final answer: No effect or no difference." }),
  p({ id: "hyp-tstat-1", topicId: "hypothesis-testing", section: "t-test", type: "numeric", difficulty: "easy",
    prompt: "One-sample $t$-test: $\\bar{x}=52$, $\\mu_0=50$, $s=4$, $n=16$. Find $t$.",
    answer: "2",
    explanation: "Step 1: $SE=4/\\sqrt{16}=1$. $t=(52-50)/1=2$. Final answer: $2$." }),
  p({ id: "hyp-power-1", topicId: "hypothesis-testing", section: "errors", type: "mcq", difficulty: "easy",
    prompt: "Power of a test is defined as:",
    answer: "$1-\\beta=P(\\text{reject }H_0\\mid H_0\\text{ false})$.",
    choices: ["$\\alpha$.", "$1-\\alpha$.", "$1-\\beta=P(\\text{reject }H_0\\mid H_0\\text{ false})$.", "$\\beta$"],
    explanation: "Step 1: Power $=1-\\beta$ is the probability of correctly rejecting a false $H_0$ (true positive rate). Final answer: $1-\\beta=P(\\text{reject }H_0\\mid H_0\\text{ false})$." }),
  p({ id: "hyp-ztest-1", topicId: "hypothesis-testing", section: "z-test", type: "numeric", difficulty: "easy",
    prompt: "One-sample $z$-test: $\\bar{x}=105$, $\\mu_0=100$, $\\sigma=10$, $n=25$. Find $z$.",
    answer: "2.5",
    explanation: "Step 1: $SE=10/\\sqrt{25}=2$. $z=(105-100)/2=2.5$. Final answer: $2.5$." }),
  p({ id: "hyp-pval-3", topicId: "hypothesis-testing", section: "p-value", type: "mcq", difficulty: "easy",
    prompt: "A $p$-value of $0.001$ provides:",
    answer: "Very strong evidence against $H_0$.",
    choices: ["No evidence against $H_0$.", "Weak evidence against $H_0$.", "Moderate evidence against $H_0$.", "Very strong evidence against $H_0$."],
    explanation: "Step 1: Very small $p$-values indicate the data is highly unlikely under $H_0$, providing very strong evidence against it. Final answer: Very strong evidence against $H_0$." }),
  p({ id: "hyp-errors-1", topicId: "hypothesis-testing", section: "errors", type: "mcq", difficulty: "easy",
    prompt: "Decreasing $\\alpha$ from $0.05$ to $0.01$:",
    answer: "Decreases Type I error probability but increases Type II error probability.",
    choices: ["Increases Type I error only.", "Decreases Type I error probability but increases Type II error probability.", "Decreases both Type I and Type II errors.", "Has no effect on errors."],
    explanation: "Step 1: Stricter $\\alpha$ (smaller) reduces false positives but makes it harder to detect true effects, increasing $\\beta$. Final answer: Decreases Type I error probability but increases Type II error probability." }),
  p({ id: "hyp-ttest-2", topicId: "hypothesis-testing", section: "t-test", type: "mcq", difficulty: "easy",
    prompt: "A one-sample $t$-test is appropriate when:",
    answer: "$\\sigma$ is unknown and $n$ is small or the population is normal.",
    choices: ["$\\sigma$ is known.", "$\\sigma$ is unknown and $n$ is small or the population is normal.", "The data is categorical.", "$n>1000$."],
    explanation: "Step 1: Use $t$-test when $\\sigma$ is unknown (use $s$ instead) and conditions for normality are met. Final answer: $\\sigma$ is unknown and $n$ is small or the population is normal." }),
  p({ id: "hyp-pval-4", topicId: "hypothesis-testing", section: "p-value", type: "mcq", difficulty: "easy",
    prompt: "We 'fail to reject $H_0$' when:",
    answer: "$p > \\alpha$",
    choices: ["$p<\\alpha$", "$p>\\alpha$", "$p=0$", "$p=1$"],
    explanation: "Step 1: $p>\\alpha$ means the data is not sufficiently extreme to reject $H_0$ at level $\\alpha$. Final answer: $p>\\alpha$." }),
  p({ id: "hyp-ztest-2", topicId: "hypothesis-testing", section: "z-test", type: "mcq", difficulty: "easy",
    prompt: "A one-sample $z$-test is used when:",
    answer: "The population standard deviation $\\sigma$ is known.",
    choices: ["$\\sigma$ is unknown.", "The population standard deviation $\\sigma$ is known.", "The sample is small.", "The data is categorical."],
    explanation: "Step 1: The $z$-test uses the known $\\sigma$ to compute $z=(\\bar{x}-\\mu_0)/(\\sigma/\\sqrt{n})$. Final answer: The population standard deviation $\\sigma$ is known." }),

  // --- Medium (16) ---
  p({ id: "hyp-tstat-2", topicId: "hypothesis-testing", section: "t-test", type: "numeric", difficulty: "medium",
    prompt: "Two-sample $t$-test (equal variances, pooled): $\\bar{x}_1=10$, $\\bar{x}_2=8$, $s_p=3$, $n_1=n_2=10$. Find $t$.",
    answer: "1.491",
    explanation: "Step 1: $SE=s_p\\sqrt{1/n_1+1/n_2}=3\\sqrt{0.2}=3(0.4472)=1.342$. $t=(10-8)/1.342\\approx1.491$. Final answer: $1.491$." }),
  p({ id: "hyp-pval-5", topicId: "hypothesis-testing", section: "p-value", type: "mcq", difficulty: "medium",
    prompt: "For a two-tailed $z$-test with $z=2.0$, the $p$-value $\\approx$",
    answer: "$0.046$",
    choices: ["$0.023$", "$0.046$", "$0.977$", "$0.954$"],
    explanation: "Step 1: Two-tailed: $p=2P(Z>2.0)=2(1-0.9772)=2(0.0228)=0.0456\\approx0.046$. Final answer: $0.046$." }),
  p({ id: "hyp-power-2", topicId: "hypothesis-testing", section: "errors", type: "mcq", difficulty: "medium",
    prompt: "Power increases when:",
    answer: "Effect size increases or sample size increases.",
    choices: ["$\\alpha$ decreases.", "Effect size increases or sample size increases.", "The null hypothesis is true.", "$\\beta$ increases."],
    explanation: "Step 1: Power $=1-\\beta$. Larger effect or larger $n$ makes it easier to detect the true effect, increasing power. Final answer: Effect size increases or sample size increases." }),
  p({ id: "hyp-ttest-3", topicId: "hypothesis-testing", section: "t-test", type: "numeric", difficulty: "medium",
    prompt: "Paired $t$-test: differences $d=\\{2,4,6,2,6\\}$. $\\bar{d}=4$, $s_d=2$, $n=5$. Find $t$.",
    answer: "4.472",
    explanation: "Step 1: $SE=s_d/\\sqrt{n}=2/\\sqrt{5}\\approx0.894$. $t=\\bar{d}/SE=4/0.894\\approx4.472$. Final answer: $4.472$." }),
  p({ id: "hyp-ztest-3", topicId: "hypothesis-testing", section: "z-test", type: "numeric", difficulty: "medium",
    prompt: "Proportion test: $\\hat{p}=0.55$, $p_0=0.5$, $n=400$. $z=(\\hat{p}-p_0)/\\sqrt{p_0(1-p_0)/n}=$",
    answer: "2",
    explanation: "Step 1: $SE=\\sqrt{0.5(0.5)/400}=\\sqrt{0.000625}=0.025$. $z=(0.55-0.5)/0.025=2$. Final answer: $2$." }),
  p({ id: "hyp-errors-2", topicId: "hypothesis-testing", section: "errors", type: "mcq", difficulty: "medium",
    prompt: "A researcher fails to detect a real drug effect. This is:",
    answer: "A Type II error.",
    choices: ["A Type I error.", "A Type II error.", "Correct decision.", "A $p$-value error."],
    explanation: "Step 1: Missing a real effect = failing to reject a false $H_0$ = Type II error. Final answer: A Type II error." }),
  p({ id: "hyp-ttest-4", topicId: "hypothesis-testing", section: "t-test", type: "mcq", difficulty: "medium",
    prompt: "When comparing two independent groups with unknown and unequal variances, you use:",
    answer: "Welch's $t$-test.",
    choices: ["Pooled two-sample $t$-test.", "Welch's $t$-test.", "Paired $t$-test.", "One-sample $z$-test."],
    explanation: "Step 1: Welch's $t$-test does not assume equal variances, using separate $s_1^2,s_2^2$ and adjusted df. Final answer: Welch's $t$-test." }),
  p({ id: "hyp-pval-6", topicId: "hypothesis-testing", section: "p-value", type: "numeric", difficulty: "medium",
    prompt: "For a one-tailed (right) $z$-test with $z=1.645$, $p\\approx$",
    answer: "0.05",
    explanation: "Step 1: $p=P(Z>1.645)=1-\\Phi(1.645)=1-0.95=0.05$. Final answer: $0.05$." }),
  p({ id: "hyp-ztest-4", topicId: "hypothesis-testing", section: "z-test", type: "mcq", difficulty: "medium",
    prompt: "A two-tailed test at $\\alpha=0.05$ rejects $H_0$ if $|z|>$",
    answer: "$1.96$",
    choices: ["$1.28$", "$1.645$", "$1.96$", "$2.576$"],
    explanation: "Step 1: Two-tailed $\\alpha=0.05$: critical value $z_{\\alpha/2}=z_{0.025}=1.96$. Reject if $|z|>1.96$. Final answer: $1.96$." }),
  p({ id: "hyp-power-3", topicId: "hypothesis-testing", section: "errors", type: "numeric", difficulty: "medium",
    prompt: "If $\\beta=0.20$, what is the power of the test?",
    answer: "0.8",
    explanation: "Step 1: Power $=1-\\beta=1-0.20=0.80$. Final answer: $0.8$." }),
  p({ id: "hyp-ttest-5", topicId: "hypothesis-testing", section: "t-test", type: "numeric", difficulty: "medium",
    prompt: "One-sample $t$: $\\bar{x}=48$, $\\mu_0=50$, $s=6$, $n=9$. Find $t$.",
    answer: "-1",
    explanation: "Step 1: $SE=6/\\sqrt{9}=2$. $t=(48-50)/2=-1$. Final answer: $-1$." }),
  p({ id: "hyp-pval-7", topicId: "hypothesis-testing", section: "p-value", type: "mcq", difficulty: "medium",
    prompt: "Statistical significance vs. practical significance: a statistically significant result",
    answer: "Does not necessarily imply practical importance.",
    choices: ["Always has practical importance.", "Does not necessarily imply practical importance.", "Requires $p<0.001$.", "Is only valid for large effects."],
    explanation: "Step 1: With large $n$, trivially small effects can be statistically significant. Practical significance requires assessing effect size. Final answer: Does not necessarily imply practical importance." }),
  p({ id: "hyp-errors-3", topicId: "hypothesis-testing", section: "errors", type: "mcq", difficulty: "medium",
    prompt: "In medical testing, which error is typically more costly: falsely approving an ineffective drug (Type I) or failing to approve an effective drug (Type II)?",
    answer: "Context-dependent; both matter but Type I (false approval) is often prioritized for safety.",
    choices: ["Type II is always worse.", "Type I is always worse.", "Context-dependent; both matter but Type I (false approval) is often prioritized for safety.", "Neither matters."],
    explanation: "Step 1: Regulators set strict $\\alpha$ (e.g., $0.05$ or $0.01$) to limit Type I errors (approving harmful/useless drugs), accepting higher Type II error risk. Final answer: Context-dependent; both matter but Type I (false approval) is often prioritized for safety." }),
  p({ id: "hyp-ztest-5", topicId: "hypothesis-testing", section: "z-test", type: "numeric", difficulty: "medium",
    prompt: "Two-proportion $z$-test: $\\hat{p}_1=0.60$, $n_1=100$; $\\hat{p}_2=0.50$, $n_2=100$. Pooled $\\hat{p}=0.55$. Find $z$.",
    answer: "1.425",
    explanation: "Step 1: $SE=\\sqrt{0.55(0.45)(1/100+1/100)}=\\sqrt{0.00495}\\approx0.0703$. $z=(0.60-0.50)/0.0703\\approx1.423\\approx1.425$. Final answer: $1.425$." }),

  // --- Hard (10) ---
  p({ id: "hyp-tstat-3", topicId: "hypothesis-testing", section: "t-test", type: "numeric", difficulty: "hard",
    prompt: "Two-sample pooled $t$: $n_1=15$, $s_1^2=20$; $n_2=10$, $s_2^2=30$. Find $s_p^2$.",
    answer: "24",
    explanation: "Step 1: $s_p^2=\\frac{(n_1-1)s_1^2+(n_2-1)s_2^2}{n_1+n_2-2}=\\frac{14(20)+9(30)}{23}=\\frac{280+270}{23}=550/23\\approx23.91\\approx24$. Final answer: $24$." }),
  p({ id: "hyp-power-4", topicId: "hypothesis-testing", section: "errors", type: "numeric", difficulty: "hard",
    prompt: "For power $=0.80$ at $\\alpha=0.05$ (two-tailed), $z_{0.025}=1.96$, $z_{0.20}=0.842$, $\\sigma=10$, $\\delta=5$. Find minimum $n=\\lceil((z_{\\alpha/2}+z_\\beta)\\sigma/\\delta)^2\\rceil$.",
    answer: "32",
    explanation: "Step 1: $n=((1.96+0.842)\\times10/5)^2=(2.802\\times2)^2=(5.604)^2\\approx31.4$. Round up: $n=32$. Final answer: $32$." }),
  p({ id: "hyp-pval-8", topicId: "hypothesis-testing", section: "p-value", type: "mcq", difficulty: "hard",
    prompt: "The Bonferroni correction for multiple testing with $m=5$ tests at family-wise $\\alpha=0.05$ sets each test's $\\alpha$ to:",
    answer: "$0.01$",
    choices: ["$0.05$", "$0.01$", "$0.025$", "$0.10$"],
    explanation: "Step 1: Bonferroni: per-test $\\alpha=0.05/5=0.01$. Final answer: $0.01$." }),
  p({ id: "hyp-ttest-6", topicId: "hypothesis-testing", section: "t-test", type: "numeric", difficulty: "hard",
    prompt: "Welch's $t$ df approximation: $s_1^2=20,n_1=10,s_2^2=40,n_2=20$. $\\text{df}\\approx\\frac{(s_1^2/n_1+s_2^2/n_2)^2}{(s_1^2/n_1)^2/(n_1-1)+(s_2^2/n_2)^2/(n_2-1)}$. Compute numerator $(s_1^2/n_1+s_2^2/n_2)^2$.",
    answer: "16",
    explanation: "Step 1: $s_1^2/n_1=2$, $s_2^2/n_2=2$. Sum $=4$. Numerator $=4^2=16$. Final answer: $16$." }),
  p({ id: "hyp-ztest-6", topicId: "hypothesis-testing", section: "z-test", type: "numeric", difficulty: "hard",
    prompt: "Effect size Cohen's $d=(\\mu_1-\\mu_2)/\\sigma_p$. If $\\mu_1-\\mu_2=6$ and $\\sigma_p=12$, find $d$.",
    answer: "0.5",
    explanation: "Step 1: $d=6/12=0.5$. This is a medium effect. Final answer: $0.5$." }),
  p({ id: "hyp-errors-4", topicId: "hypothesis-testing", section: "errors", type: "mcq", difficulty: "hard",
    prompt: "The false discovery rate (FDR) controls:",
    answer: "The expected proportion of false positives among all rejected hypotheses.",
    choices: ["The family-wise error rate.", "The expected proportion of false positives among all rejected hypotheses.", "The Type II error rate.", "The $p$-value threshold."],
    explanation: "Step 1: FDR (Benjamini-Hochberg): expected fraction of rejected $H_0$s that are truly null. Less strict than FWER (Bonferroni). Final answer: The expected proportion of false positives among all rejected hypotheses." }),
  p({ id: "hyp-ttest-7", topicId: "hypothesis-testing", section: "t-test", type: "mcq", difficulty: "hard",
    prompt: "When should you use a paired $t$-test instead of a two-sample $t$-test?",
    answer: "When measurements are from the same subjects before and after treatment.",
    choices: ["When variances are unequal.", "When measurements are from the same subjects before and after treatment.", "When $n>30$.", "When $\\sigma$ is known."],
    explanation: "Step 1: Paired $t$ removes between-subject variability by analyzing differences $d_i=x_{i2}-x_{i1}$. Appropriate for matched pairs or repeated measures. Final answer: When measurements are from the same subjects before and after treatment." }),
  p({ id: "hyp-pval-9", topicId: "hypothesis-testing", section: "p-value", type: "mcq", difficulty: "hard",
    prompt: "A $p$-value does NOT tell you:",
    answer: "The probability that $H_0$ is true.",
    choices: ["How surprising the data is under $H_0$.", "The probability that $H_0$ is true.", "Whether to reject $H_0$ at a given $\\alpha$.", "The minimum of evidence against $H_0$."],
    explanation: "Step 1: $p$-value is $P(\\text{data}\\mid H_0)$, not $P(H_0\\mid\\text{data})$. The latter is a Bayesian posterior. Final answer: The probability that $H_0$ is true." }),
  p({ id: "hyp-ztest-7", topicId: "hypothesis-testing", section: "z-test", type: "numeric", difficulty: "hard",
    prompt: "One-sided $z$-test ($H_a:\\mu>50$): $z=1.7$. $p\\approx\\Phi(-1.7)=1-\\Phi(1.7)$. If $\\Phi(1.7)=0.9554$, find $p$.",
    answer: "0.0446",
    explanation: "Step 1: $p=P(Z>1.7)=1-0.9554=0.0446$. Final answer: $0.0446$." }),
];
