import type { Problem } from "../shared-types";

const p = (problem: Problem) => problem;

export const nonparametricProblems: Problem[] = [
  // --- Easy (14) ---
  p({ id: "nonpar-chisq-1", topicId: "nonparametric", section: "chi-square", type: "mcq", difficulty: "easy",
    prompt: "A chi-square goodness-of-fit test determines whether:",
    answer: "Observed frequencies match expected frequencies.",
    choices: ["Two means are equal.", "Observed frequencies match expected frequencies.", "Two variances are equal.", "A sample is normally distributed."],
    explanation: "Step 1: $\\chi^2=\\sum(O_i-E_i)^2/E_i$. Large $\\chi^2$ indicates poor fit. Final answer: Observed frequencies match expected frequencies." }),
  p({ id: "nonpar-indep-1", topicId: "nonparametric", section: "chi-square", type: "mcq", difficulty: "easy",
    prompt: "A chi-square test for independence tests whether:",
    answer: "Two categorical variables are independent.",
    choices: ["Two numerical variables are correlated.", "Two categorical variables are independent.", "A distribution is normal.", "Two means are equal."],
    explanation: "Step 1: Uses a contingency table. $H_0$: variables are independent. $p<\\alpha\\Rightarrow$ association exists. Final answer: Two categorical variables are independent." }),
  p({ id: "nonpar-mw-1", topicId: "nonparametric", section: "rank-tests", type: "mcq", difficulty: "easy",
    prompt: "The Mann-Whitney U test is a non-parametric alternative to the:",
    answer: "Two-sample $t$-test.",
    choices: ["One-sample $t$-test.", "Two-sample $t$-test.", "Paired $t$-test.", "One-way ANOVA."],
    explanation: "Step 1: Mann-Whitney U compares two independent groups without assuming normality—it's the non-parametric equivalent of the independent-samples $t$-test. Final answer: Two-sample $t$-test." }),
  p({ id: "nonpar-wilcox-1", topicId: "nonparametric", section: "rank-tests", type: "mcq", difficulty: "easy",
    prompt: "The Wilcoxon signed-rank test is a non-parametric alternative to the:",
    answer: "Paired $t$-test.",
    choices: ["Two-sample $t$-test.", "One-way ANOVA.", "Paired $t$-test.", "Chi-square test."],
    explanation: "Step 1: Wilcoxon signed-rank tests for differences in paired data using ranks, without assuming normality. Final answer: Paired $t$-test." }),
  p({ id: "nonpar-kruskal-1", topicId: "nonparametric", section: "rank-tests", type: "mcq", difficulty: "easy",
    prompt: "The Kruskal-Wallis test is a non-parametric alternative to:",
    answer: "One-way ANOVA.",
    choices: ["Two-sample $t$-test.", "One-way ANOVA.", "Paired $t$-test.", "Chi-square test."],
    explanation: "Step 1: Kruskal-Wallis tests for differences among $k\\geq2$ groups using ranks—extends Mann-Whitney to multiple groups. Final answer: One-way ANOVA." }),
  p({ id: "nonpar-spearman-1", topicId: "nonparametric", section: "spearman", type: "mcq", difficulty: "easy",
    prompt: "Spearman's rank correlation measures:",
    answer: "Monotonic association between two variables.",
    choices: ["Linear correlation only.", "Monotonic association between two variables.", "Difference between group means.", "Categorical association."],
    explanation: "Step 1: Spearman's $r_s$ uses ranks and captures any monotonic (not just linear) relationship. Final answer: Monotonic association between two variables." }),
  p({ id: "nonpar-chisq-2", topicId: "nonparametric", section: "chi-square", type: "mcq", difficulty: "easy",
    prompt: "The chi-square statistic is always:",
    answer: "Non-negative.",
    choices: ["Between $-1$ and $1$.", "Non-negative.", "Negative.", "Equal to the $p$-value."],
    explanation: "Step 1: $\\chi^2=\\sum(O-E)^2/E\\geq0$ since it sums squared terms. Final answer: Non-negative." }),
  p({ id: "nonpar-when-1", topicId: "nonparametric", section: "rank-tests", type: "mcq", difficulty: "easy",
    prompt: "Non-parametric tests are preferred when:",
    answer: "Data is ordinal, heavily skewed, or has outliers.",
    choices: ["Data is always normal.", "Sample size is large.", "Data is ordinal, heavily skewed, or has outliers.", "$\\sigma$ is known."],
    explanation: "Step 1: Non-parametric tests make fewer assumptions about the population distribution, making them suitable for ordinal or non-normal data. Final answer: Data is ordinal, heavily skewed, or has outliers." }),
  p({ id: "nonpar-chisq-3", topicId: "nonparametric", section: "chi-square", type: "numeric", difficulty: "easy",
    prompt: "For a $2\\times2$ contingency table, the degrees of freedom for the chi-square test of independence is:",
    answer: "1",
    explanation: "Step 1: $\\text{df}=(r-1)(c-1)=(2-1)(2-1)=1$. Final answer: $1$." }),
  p({ id: "nonpar-spearman-2", topicId: "nonparametric", section: "spearman", type: "mcq", difficulty: "easy",
    prompt: "Spearman's $r_s=1$ means:",
    answer: "A perfect monotonically increasing relationship.",
    choices: ["A perfect linear relationship.", "A perfect monotonically increasing relationship.", "No association.", "A perfect negative relationship."],
    explanation: "Step 1: $r_s=1$ means every increase in $x$ is accompanied by an increase in $y$ (perfectly monotone). Final answer: A perfect monotonically increasing relationship." }),
  p({ id: "nonpar-rank-1", topicId: "nonparametric", section: "rank-tests", type: "mcq", difficulty: "easy",
    prompt: "Rank-based tests transform data to ranks to:",
    answer: "Reduce the influence of outliers and relax distributional assumptions.",
    choices: ["Increase statistical power.", "Reduce the influence of outliers and relax distributional assumptions.", "Require normality.", "Increase sample size."],
    explanation: "Step 1: Replacing values with ranks makes tests robust to outliers and non-normality by discarding magnitude information. Final answer: Reduce the influence of outliers and relax distributional assumptions." }),
  p({ id: "nonpar-chisq-4", topicId: "nonparametric", section: "chi-square", type: "mcq", difficulty: "easy",
    prompt: "The expected count in a chi-square test cell is:",
    answer: "$E=\\frac{\\text{row total}\\times\\text{column total}}{n}$",
    choices: ["The observed count.", "$E=\\frac{\\text{row total}\\times\\text{column total}}{n}$", "$E=n/k$", "$E=O/n$"],
    explanation: "Step 1: Under independence, $E_{ij}=(R_i\\times C_j)/n$. Final answer: $E=\\frac{\\text{row total}\\times\\text{column total}}{n}$." }),
  p({ id: "nonpar-power-1", topicId: "nonparametric", section: "rank-tests", type: "mcq", difficulty: "easy",
    prompt: "Compared to parametric tests, non-parametric tests generally have:",
    answer: "Less power when parametric assumptions are met.",
    choices: ["More power always.", "Less power when parametric assumptions are met.", "Equal power in all cases.", "More power for normal data."],
    explanation: "Step 1: Non-parametric tests sacrifice some power (efficiency) compared to parametric tests when the parametric assumptions hold. Final answer: Less power when parametric assumptions are met." }),
  p({ id: "nonpar-chisq-5", topicId: "nonparametric", section: "chi-square", type: "mcq", difficulty: "easy",
    prompt: "The chi-square goodness-of-fit test requires expected counts to be:",
    answer: "At least $5$ in each cell.",
    choices: ["Exactly equal to observed.", "At least $5$ in each cell.", "At least $1$.", "Equal to $n$."],
    explanation: "Step 1: The chi-square approximation is valid when all $E_i\\geq5$. If not, combine categories or use Fisher's exact test. Final answer: At least $5$ in each cell." }),

  // --- Medium (16) ---
  p({ id: "nonpar-chisq-6", topicId: "nonparametric", section: "chi-square", type: "numeric", difficulty: "medium",
    prompt: "Goodness-of-fit: $O=\\{30,20,50\\}$, $E=\\{25,25,50\\}$. Find $\\chi^2$.",
    answer: "2",
    explanation: "Step 1: $\\chi^2=(30-25)^2/25+(20-25)^2/25+(50-50)^2/50=25/25+25/25+0=1+1+0=2$. Final answer: $2$." }),
  p({ id: "nonpar-indep-2", topicId: "nonparametric", section: "chi-square", type: "numeric", difficulty: "medium",
    prompt: "A $3\\times4$ contingency table. Degrees of freedom for chi-square test of independence?",
    answer: "6",
    explanation: "Step 1: $\\text{df}=(3-1)(4-1)=2\\times3=6$. Final answer: $6$." }),
  p({ id: "nonpar-mw-2", topicId: "nonparametric", section: "rank-tests", type: "mcq", difficulty: "medium",
    prompt: "The Mann-Whitney U test compares distributions by:",
    answer: "Ranking all observations and comparing rank sums between groups.",
    choices: ["Comparing group means directly.", "Ranking all observations and comparing rank sums between groups.", "Using the $t$-distribution.", "Testing variances."],
    explanation: "Step 1: All observations from both groups are ranked together. The test statistic is based on how ranks are distributed between groups. Final answer: Ranking all observations and comparing rank sums between groups." }),
  p({ id: "nonpar-spearman-3", topicId: "nonparametric", section: "spearman", type: "numeric", difficulty: "medium",
    prompt: "Spearman $r_s$: $n=5$ pairs ranked. $\\sum d_i^2=10$. $r_s=1-\\frac{6\\sum d_i^2}{n(n^2-1)}=$",
    answer: "0.5",
    explanation: "Step 1: $r_s=1-6(10)/(5\\times24)=1-60/120=1-0.5=0.5$. Final answer: $0.5$." }),
  p({ id: "nonpar-kruskal-2", topicId: "nonparametric", section: "rank-tests", type: "mcq", difficulty: "medium",
    prompt: "The Kruskal-Wallis test statistic $H$ approximately follows a:",
    answer: "Chi-square distribution with $k-1$ degrees of freedom.",
    choices: ["Normal distribution.", "Chi-square distribution with $k-1$ degrees of freedom.", "$t$-distribution.", "$F$-distribution."],
    explanation: "Step 1: Under $H_0$, $H\\approx\\chi^2(k-1)$ for large samples, where $k$ is the number of groups. Final answer: Chi-square distribution with $k-1$ degrees of freedom." }),
  p({ id: "nonpar-chisq-7", topicId: "nonparametric", section: "chi-square", type: "mcq", difficulty: "medium",
    prompt: "Fisher's exact test is preferred over chi-square when:",
    answer: "Sample size is small or expected cell counts are $<5$.",
    choices: ["$n>100$.", "Sample size is small or expected cell counts are $<5$.", "There are $>5$ categories.", "The test is two-sided."],
    explanation: "Step 1: Chi-square approximation is unreliable for small $n$. Fisher's exact test computes exact probabilities using the hypergeometric distribution. Final answer: Sample size is small or expected cell counts are $<5$." }),
  p({ id: "nonpar-wilcox-2", topicId: "nonparametric", section: "rank-tests", type: "mcq", difficulty: "medium",
    prompt: "In the Wilcoxon signed-rank test, observations with difference $d_i=0$ are:",
    answer: "Discarded from the analysis.",
    choices: ["Assigned rank $0$.", "Discarded from the analysis.", "Assigned the smallest rank.", "Counted as ties."],
    explanation: "Step 1: Pairs with $d_i=0$ (no difference) are excluded; the test is based on ranks of non-zero differences. Final answer: Discarded from the analysis." }),
  p({ id: "nonpar-spearman-4", topicId: "nonparametric", section: "spearman", type: "mcq", difficulty: "medium",
    prompt: "Spearman $r_s=0$ implies:",
    answer: "No monotonic association.",
    choices: ["No linear association only.", "A negative association.", "No monotonic association.", "Perfect independence."],
    explanation: "Step 1: $r_s=0$ means no systematic monotonic trend, though non-monotonic patterns could still exist. Final answer: No monotonic association." }),
  p({ id: "nonpar-chisq-8", topicId: "nonparametric", section: "chi-square", type: "numeric", difficulty: "medium",
    prompt: "Expected count for a cell: row total $=60$, column total $=40$, $n=200$. Find $E$.",
    answer: "12",
    explanation: "Step 1: $E=(60\\times40)/200=2400/200=12$. Final answer: $12$." }),
  p({ id: "nonpar-rank-2", topicId: "nonparametric", section: "rank-tests", type: "mcq", difficulty: "medium",
    prompt: "The sign test is the simplest non-parametric test. It only uses:",
    answer: "The direction (sign) of each difference.",
    choices: ["The magnitude of differences.", "The direction (sign) of each difference.", "The mean of the differences.", "Ranked differences."],
    explanation: "Step 1: The sign test counts positive and negative differences and tests whether $P(+)=0.5$. It ignores magnitude, making it less powerful than Wilcoxon. Final answer: The direction (sign) of each difference." }),
  p({ id: "nonpar-kruskal-3", topicId: "nonparametric", section: "rank-tests", type: "mcq", difficulty: "medium",
    prompt: "After a significant Kruskal-Wallis test, pairwise comparisons use:",
    answer: "Dunn's test (with Bonferroni correction).",
    choices: ["Tukey's HSD.", "Dunn's test (with Bonferroni correction).", "Fisher's LSD.", "Paired $t$-tests."],
    explanation: "Step 1: Dunn's test is the non-parametric post-hoc test for Kruskal-Wallis, comparing pairs with rank-sum differences and controlling for multiple comparisons. Final answer: Dunn's test (with Bonferroni correction)." }),
  p({ id: "nonpar-spearman-5", topicId: "nonparametric", section: "spearman", type: "numeric", difficulty: "medium",
    prompt: "Spearman $r_s$: $\\sum d_i^2=0$, $n=6$. Find $r_s$.",
    answer: "1",
    explanation: "Step 1: $r_s=1-6(0)/(6\\times35)=1-0=1$. Final answer: $1$." }),
  p({ id: "nonpar-chisq-9", topicId: "nonparametric", section: "chi-square", type: "mcq", difficulty: "medium",
    prompt: "Cramér's $V=\\sqrt{\\chi^2/(n\\cdot\\min(r-1,c-1))}$ measures:",
    answer: "The strength of association between two categorical variables.",
    choices: ["The $p$-value.", "The strength of association between two categorical variables.", "Sample size.", "Degrees of freedom."],
    explanation: "Step 1: Cramér's $V\\in[0,1]$ is an effect size for chi-square tests. $V=0$: no association; $V=1$: perfect association. Final answer: The strength of association between two categorical variables." }),
  p({ id: "nonpar-mw-3", topicId: "nonparametric", section: "rank-tests", type: "mcq", difficulty: "medium",
    prompt: "The null hypothesis of the Mann-Whitney U test is:",
    answer: "The two populations have the same distribution.",
    choices: ["The two means are equal.", "The two populations have the same distribution.", "The two variances are equal.", "The two medians are equal."],
    explanation: "Step 1: Mann-Whitney $H_0$: the distributions of the two populations are identical (not just equal means). Final answer: The two populations have the same distribution." }),
  p({ id: "nonpar-wilcox-3", topicId: "nonparametric", section: "rank-tests", type: "mcq", difficulty: "medium",
    prompt: "The Wilcoxon rank-sum test is the same as:",
    answer: "The Mann-Whitney U test.",
    choices: ["The sign test.", "The Wilcoxon signed-rank test.", "The Mann-Whitney U test.", "The Kruskal-Wallis test."],
    explanation: "Step 1: Wilcoxon rank-sum and Mann-Whitney U are equivalent tests for two independent samples. Final answer: The Mann-Whitney U test." }),

  // --- Hard (10) ---
  p({ id: "nonpar-chisq-10", topicId: "nonparametric", section: "chi-square", type: "numeric", difficulty: "hard",
    prompt: "Goodness-of-fit with $k=4$ categories, $n=100$: $O=\\{30,25,30,15\\}$, $E=\\{25,25,25,25\\}$. Find $\\chi^2$.",
    answer: "6",
    explanation: "Step 1: $\\chi^2=(30-25)^2/25+(25-25)^2/25+(30-25)^2/25+(15-25)^2/25=1+0+1+4=6$. Final answer: $6$." }),
  p({ id: "nonpar-spearman-6", topicId: "nonparametric", section: "spearman", type: "numeric", difficulty: "hard",
    prompt: "Spearman $r_s$: $n=4$, $\\sum d_i^2=4$. $r_s=1-6(4)/(4\\times15)=$",
    answer: "0.6",
    explanation: "Step 1: $r_s=1-24/60=1-0.4=0.6$. Final answer: $0.6$." }),
  p({ id: "nonpar-kruskal-4", topicId: "nonparametric", section: "rank-tests", type: "numeric", difficulty: "hard",
    prompt: "Kruskal-Wallis: $k=3$ groups, $N=12$ total, rank sums $R_1=30,R_2=24,R_3=24$, each $n_i=4$. $H=\\frac{12}{N(N+1)}\\sum\\frac{R_i^2}{n_i}-3(N+1)=$",
    answer: "0.5",
    explanation: "Step 1: $H=\\frac{12}{12(13)}[30^2/4+24^2/4+24^2/4]-3(13)=\\frac{12}{156}[225+144+144]-39=(0.0769)(513)-39=39.46-39=0.46\\approx0.5$. Final answer: $0.5$." }),
  p({ id: "nonpar-indep-3", topicId: "nonparametric", section: "chi-square", type: "mcq", difficulty: "hard",
    prompt: "Yates' continuity correction for a $2\\times2$ chi-square test:",
    answer: "Subtracts $0.5$ from each $|O-E|$ to improve the approximation.",
    choices: ["Adds $1$ to each cell.", "Subtracts $0.5$ from each $|O-E|$ to improve the approximation.", "Doubles the chi-square statistic.", "Is required for all chi-square tests."],
    explanation: "Step 1: Yates' correction: $\\chi^2=\\sum(|O_i-E_i|-0.5)^2/E_i$. Applied to $2\\times2$ tables with small $n$ to reduce overestimation. Final answer: Subtracts $0.5$ from each $|O-E|$ to improve the approximation." }),
  p({ id: "nonpar-mw-4", topicId: "nonparametric", section: "rank-tests", type: "numeric", difficulty: "hard",
    prompt: "Group A: $\\{1,3,5\\}$, Group B: $\\{2,4,6\\}$. All ranked $1$–$6$: $R_A=1+3+5=9$, $R_B=2+4+6=12$. $U_A=R_A-n_A(n_A+1)/2=9-6=3$. Find $U_B$.",
    answer: "6",
    explanation: "Step 1: $U_B=n_An_B-U_A=3\\times3-3=9-3=6$. Final answer: $6$." }),
  p({ id: "nonpar-spearman-7", topicId: "nonparametric", section: "spearman", type: "mcq", difficulty: "hard",
    prompt: "To test $H_0:\\rho_s=0$ with $n=20$ and $r_s=0.5$, the test statistic $t=r_s\\sqrt{(n-2)/(1-r_s^2)}=$",
    answer: "2.449",
    explanation: "Step 1: $t=0.5\\sqrt{18/(1-0.25)}=0.5\\sqrt{18/0.75}=0.5\\sqrt{24}=0.5\\times4.899=2.449$. Final answer: $2.449$." }),
  p({ id: "nonpar-chisq-11", topicId: "nonparametric", section: "chi-square", type: "mcq", difficulty: "hard",
    prompt: "In a large chi-square test of independence ($r\\times c$ table), rejecting $H_0$ tells you:",
    answer: "An association exists, but not the strength or direction.",
    choices: ["The variables are causally related.", "An association exists, but not the strength or direction.", "All cells differ significantly.", "The effect size is large."],
    explanation: "Step 1: Chi-square tests only whether an association exists. Effect sizes (Cramér's $V$, odds ratio) and residuals must be examined separately for strength and direction. Final answer: An association exists, but not the strength or direction." }),
  p({ id: "nonpar-wilcox-4", topicId: "nonparametric", section: "rank-tests", type: "mcq", difficulty: "hard",
    prompt: "For the Wilcoxon signed-rank test, the test statistic $W$ is:",
    answer: "The sum of positive ranks (or negative ranks).",
    choices: ["The sum of all ranks.", "The sum of positive ranks (or negative ranks).", "The mean rank difference.", "The number of ties."],
    explanation: "Step 1: After ranking $|d_i|$, assign signs back. $W^+=$ sum of ranks of positive differences. Under $H_0$, $W^+$ and $W^-$ should be similar. Final answer: The sum of positive ranks (or negative ranks)." }),
  p({ id: "nonpar-kruskal-5", topicId: "nonparametric", section: "rank-tests", type: "mcq", difficulty: "hard",
    prompt: "When there are ties in Kruskal-Wallis, the $H$ statistic should be:",
    answer: "Corrected by dividing by a tie-correction factor.",
    choices: ["Left unchanged.", "Corrected by dividing by a tie-correction factor.", "Multiplied by $n$.", "Replaced by the $F$-statistic."],
    explanation: "Step 1: Ties cause the standard $H$ to be slightly too small. The correction: $H_{\\text{corrected}}=H/[1-\\sum(t_j^3-t_j)/(N^3-N)]$ where $t_j$ are tie group sizes. Final answer: Corrected by dividing by a tie-correction factor." }),
  p({ id: "nonpar-chisq-12", topicId: "nonparametric", section: "chi-square", type: "numeric", difficulty: "hard",
    prompt: "McNemar's test is used for paired nominal data. Its statistic is $\\chi^2=(b-c)^2/(b+c)$ where $b,c$ are discordant pairs. If $b=10,c=4$, find $\\chi^2$.",
    answer: "2.571",
    explanation: "Step 1: $\\chi^2=(10-4)^2/(10+4)=36/14\\approx2.571$. Final answer: $2.571$." }),
];
