import type { Problem } from "../shared-types";

const p = (problem: Problem) => problem;

export const probabilityProblems: Problem[] = [
  // --- Easy (14) ---
  p({ id: "prob-basic-1", topicId: "probability", section: "basic", type: "numeric", difficulty: "easy",
    prompt: "A fair die is rolled. What is the probability of rolling a number greater than $4$? (Express as a fraction in decimal form.)",
    answer: "0.333",
    explanation: "Step 1: Favorable: $\\{5,6\\}$, count $=2$. Step 2: $P=2/6=1/3\\approx0.333$. Final answer: $0.333$." }),
  p({ id: "prob-basic-2", topicId: "probability", section: "basic", type: "numeric", difficulty: "easy",
    prompt: "If $P(A)=0.3$, what is $P(A^c)$?",
    answer: "0.7",
    explanation: "Step 1: Complement rule: $P(A^c)=1-P(A)=1-0.3=0.7$. Final answer: $0.7$." }),
  p({ id: "prob-counting-1", topicId: "probability", section: "counting", type: "numeric", difficulty: "easy",
    prompt: "How many ways can you arrange $3$ books on a shelf?",
    answer: "6",
    explanation: "Step 1: $3!=3\\times2\\times1=6$. Final answer: $6$." }),
  p({ id: "prob-basic-3", topicId: "probability", section: "basic", type: "numeric", difficulty: "easy",
    prompt: "A bag has $3$ red and $7$ blue balls. You draw one at random. $P(\\text{red})=$",
    answer: "0.3",
    explanation: "Step 1: $P(\\text{red})=3/10=0.3$. Final answer: $0.3$." }),
  p({ id: "prob-basic-4", topicId: "probability", section: "basic", type: "mcq", difficulty: "easy",
    prompt: "Two events $A$ and $B$ are mutually exclusive. Which is true?",
    answer: "$P(A\\cap B)=0$",
    choices: ["$P(A\\cup B)=0$", "$P(A\\cap B)=0$", "$P(A)=P(B)$", "$P(A\\cup B)=1$"],
    explanation: "Step 1: Mutually exclusive: they cannot both occur. $P(A\\cap B)=0$. Final answer: $P(A\\cap B)=0$." }),
  p({ id: "prob-conditional-1", topicId: "probability", section: "conditional", type: "mcq", difficulty: "easy",
    prompt: "The conditional probability $P(A|B)$ is defined as:",
    answer: "$P(A\\cap B)/P(B)$",
    choices: ["$P(A)\\cdot P(B)$", "$P(A\\cap B)/P(B)$", "$P(A)/P(B)$", "$P(A)+P(B)$"],
    explanation: "Step 1: $P(A|B)=P(A\\cap B)/P(B)$, the probability of $A$ given $B$ has occurred. Final answer: $P(A\\cap B)/P(B)$." }),
  p({ id: "prob-counting-2", topicId: "probability", section: "counting", type: "numeric", difficulty: "easy",
    prompt: "How many ways can you choose $2$ items from $5$ distinct items (order doesn't matter)?",
    answer: "10",
    explanation: "Step 1: $\\binom{5}{2}=5!/(2!3!)=10$. Final answer: $10$." }),
  p({ id: "prob-basic-5", topicId: "probability", section: "basic", type: "numeric", difficulty: "easy",
    prompt: "A fair coin is flipped twice. What is $P(\\text{both heads})$?",
    answer: "0.25",
    explanation: "Step 1: Sample space: $\\{HH,HT,TH,TT\\}$. Step 2: $P(HH)=1/4=0.25$. Final answer: $0.25$." }),
  p({ id: "prob-conditional-2", topicId: "probability", section: "conditional", type: "numeric", difficulty: "easy",
    prompt: "Two independent events: $P(A)=0.4$, $P(B)=0.5$. Find $P(A\\cap B)$.",
    answer: "0.2",
    explanation: "Step 1: Independent: $P(A\\cap B)=P(A)\\cdot P(B)=0.4\\times0.5=0.2$. Final answer: $0.2$." }),
  p({ id: "prob-basic-6", topicId: "probability", section: "basic", type: "mcq", difficulty: "easy",
    prompt: "The addition rule for two events is: $P(A\\cup B)=$",
    answer: "$P(A)+P(B)-P(A\\cap B)$",
    choices: ["$P(A)+P(B)$", "$P(A)+P(B)-P(A\\cap B)$", "$P(A)\\cdot P(B)$", "$P(A|B)+P(B)$"],
    explanation: "Step 1: Inclusion-exclusion: $P(A\\cup B)=P(A)+P(B)-P(A\\cap B)$. Final answer: $P(A)+P(B)-P(A\\cap B)$." }),
  p({ id: "prob-counting-3", topicId: "probability", section: "counting", type: "numeric", difficulty: "easy",
    prompt: "How many $4$-digit PINs can be formed using digits $0$-$9$ (repetition allowed)?",
    answer: "10000",
    explanation: "Step 1: $10^4=10000$ possible PINs. Final answer: $10000$." }),
  p({ id: "prob-basic-7", topicId: "probability", section: "basic", type: "numeric", difficulty: "easy",
    prompt: "In a standard deck of 52 cards, $P(\\text{Ace})=$",
    answer: "0.077",
    explanation: "Step 1: $4$ Aces in $52$ cards. $P=4/52=1/13\\approx0.077$. Final answer: $0.077$." }),
  p({ id: "prob-conditional-3", topicId: "probability", section: "conditional", type: "mcq", difficulty: "easy",
    prompt: "Events $A$ and $B$ are independent if and only if:",
    answer: "$P(A\\cap B)=P(A)\\cdot P(B)$",
    choices: ["$P(A|B)=P(B)$", "$P(A\\cap B)=P(A)\\cdot P(B)$", "$P(A\\cup B)=1$", "$A$ and $B$ are mutually exclusive."],
    explanation: "Step 1: Independence: $P(A\\cap B)=P(A)P(B)$, equivalent to $P(A|B)=P(A)$. Final answer: $P(A\\cap B)=P(A)\\cdot P(B)$." }),
  p({ id: "prob-total-1", topicId: "probability", section: "total", type: "mcq", difficulty: "easy",
    prompt: "The Law of Total Probability states: if $\\{B_1,\\ldots,B_n\\}$ partition the sample space, then $P(A)=$",
    answer: "$\\sum_i P(A|B_i)P(B_i)$",
    choices: ["$\\sum_i P(A\\cap B_i)$", "$\\sum_i P(A|B_i)P(B_i)$", "$P(A|B_1)+P(B_1)$", "$P(A)P(B_1)$"],
    explanation: "Step 1: $P(A)=\\sum_i P(A|B_i)P(B_i)$ for a partition $\\{B_i\\}$. Final answer: $\\sum_i P(A|B_i)P(B_i)$." }),

  // --- Medium (16) ---
  p({ id: "prob-bayes-1", topicId: "probability", section: "bayes", type: "numeric", difficulty: "medium",
    prompt: "If $P(A|B)=0.6$, $P(B)=0.5$, $P(A)=0.4$, find $P(B|A)$ using Bayes' theorem.",
    answer: "0.75",
    explanation: "Step 1: $P(B|A)=P(A|B)P(B)/P(A)=0.6\\times0.5/0.4=0.3/0.4=0.75$. Final answer: $0.75$." }),
  p({ id: "prob-conditional-4", topicId: "probability", section: "conditional", type: "numeric", difficulty: "medium",
    prompt: "Given $P(A\\cap B)=0.12$ and $P(B)=0.4$, find $P(A|B)$.",
    answer: "0.3",
    explanation: "Step 1: $P(A|B)=P(A\\cap B)/P(B)=0.12/0.4=0.3$. Final answer: $0.3$." }),
  p({ id: "prob-counting-4", topicId: "probability", section: "counting", type: "numeric", difficulty: "medium",
    prompt: "How many ways to arrange $5$ people in a row?",
    answer: "120",
    explanation: "Step 1: $5!=120$. Final answer: $120$." }),
  p({ id: "prob-total-2", topicId: "probability", section: "total", type: "numeric", difficulty: "medium",
    prompt: "Factory has two machines. Machine A produces 60% of output, Machine B produces 40%. Defect rate: A is 3%, B is 5%. Find $P(\\text{defect})$.",
    answer: "0.038",
    explanation: "Step 1: $P(D)=P(D|A)P(A)+P(D|B)P(B)=0.03(0.6)+0.05(0.4)=0.018+0.02=0.038$. Final answer: $0.038$." }),
  p({ id: "prob-basic-8", topicId: "probability", section: "basic", type: "numeric", difficulty: "medium",
    prompt: "From a standard deck, two cards are drawn without replacement. $P(\\text{both hearts})=$",
    answer: "0.059",
    explanation: "Step 1: $P=\\frac{13}{52}\\cdot\\frac{12}{51}=\\frac{156}{2652}\\approx0.059$. Final answer: $0.059$." }),
  p({ id: "prob-bayes-2", topicId: "probability", section: "bayes", type: "numeric", difficulty: "medium",
    prompt: "A test for a disease has sensitivity $0.95$ (true positive rate) and specificity $0.90$ (true negative rate). Disease prevalence is $0.01$. Use Bayes to find $P(\\text{disease}|\\text{positive test})$.",
    answer: "0.087",
    explanation: "Step 1: $P(+|D)=0.95,P(-|D^c)=0.90,P(D)=0.01$. $P(+)=0.95(0.01)+0.10(0.99)=0.0095+0.099=0.1085$. $P(D|+)=0.0095/0.1085\\approx0.0875$. Final answer: $0.087$." }),
  p({ id: "prob-counting-5", topicId: "probability", section: "counting", type: "numeric", difficulty: "medium",
    prompt: "How many ways to choose a committee of $3$ from $10$ people?",
    answer: "120",
    explanation: "Step 1: $\\binom{10}{3}=10!/(3!7!)=120$. Final answer: $120$." }),
  p({ id: "prob-conditional-5", topicId: "probability", section: "conditional", type: "numeric", difficulty: "medium",
    prompt: "If $P(A)=0.5$, $P(B)=0.4$, and $P(A\\cup B)=0.7$, find $P(A\\cap B)$.",
    answer: "0.2",
    explanation: "Step 1: $P(A\\cap B)=P(A)+P(B)-P(A\\cup B)=0.5+0.4-0.7=0.2$. Final answer: $0.2$." }),
  p({ id: "prob-total-3", topicId: "probability", section: "total", type: "numeric", difficulty: "medium",
    prompt: "In the defective factory problem, given a defect is found, what is the probability it came from Machine A? ($P(D)=0.038$ from prev.)",
    answer: "0.474",
    explanation: "Step 1: $P(A|D)=P(D|A)P(A)/P(D)=0.018/0.038\\approx0.474$. Final answer: $0.474$." }),
  p({ id: "prob-counting-6", topicId: "probability", section: "counting", type: "numeric", difficulty: "medium",
    prompt: "How many $3$-letter passwords from $\\{A,B,C,D,E\\}$ with no repetition?",
    answer: "60",
    explanation: "Step 1: $P(5,3)=5\\times4\\times3=60$. Final answer: $60$." }),
  p({ id: "prob-bayes-3", topicId: "probability", section: "bayes", type: "mcq", difficulty: "medium",
    prompt: "Bayes' theorem reverses the direction of conditioning. If you know $P(A|B)$, it gives you:",
    answer: "$P(B|A)$",
    choices: ["$P(A\\cap B)$", "$P(B|A)$", "$P(A\\cup B)$", "$P(A)$"],
    explanation: "Step 1: Bayes' theorem: $P(B|A)=P(A|B)P(B)/P(A)$, reversing the conditioning. Final answer: $P(B|A)$." }),
  p({ id: "prob-basic-9", topicId: "probability", section: "basic", type: "numeric", difficulty: "medium",
    prompt: "Roll two fair dice. $P(\\text{sum}=7)=$",
    answer: "0.167",
    explanation: "Step 1: Combinations giving 7: $(1,6),(2,5),(3,4),(4,3),(5,2),(6,1)$: $6$ outcomes. Step 2: $P=6/36=1/6\\approx0.167$. Final answer: $0.167$." }),
  p({ id: "prob-conditional-6", topicId: "probability", section: "conditional", type: "mcq", difficulty: "medium",
    prompt: "If $P(B|A)=P(B)$, then $A$ and $B$ are:",
    answer: "Independent.",
    choices: ["Mutually exclusive.", "Independent.", "Complementary.", "Dependent."],
    explanation: "Step 1: $P(B|A)=P(B)$ means knowing $A$ doesn't change the probability of $B$: they are independent. Final answer: Independent." }),
  p({ id: "prob-counting-7", topicId: "probability", section: "counting", type: "numeric", difficulty: "medium",
    prompt: "In how many ways can $8$ people be seated at a round table? (Circular permutations: fix one person, arrange the rest.)",
    answer: "5040",
    explanation: "Step 1: Circular permutations $=(8-1)!=7!=5040$. Final answer: $5040$." }),
  p({ id: "prob-total-4", topicId: "probability", section: "total", type: "mcq", difficulty: "medium",
    prompt: "The law of total probability is most useful when:",
    answer: "You can condition on a partition that makes conditional probabilities easier to compute.",
    choices: ["All events are independent.", "You can condition on a partition that makes conditional probabilities easier to compute.", "The sample space has only two outcomes.", "All events are mutually exclusive."],
    explanation: "Step 1: The law of total probability decomposes $P(A)$ by conditioning on a convenient partition $\\{B_i\\}$. Final answer: You can condition on a partition that makes conditional probabilities easier to compute." }),

  // --- Hard (10) ---
  p({ id: "prob-bayes-4", topicId: "probability", section: "bayes", type: "numeric", difficulty: "hard",
    prompt: "Three boxes: Box 1 has $2$ red, $1$ blue; Box 2 has $1$ red, $3$ blue; Box 3 has $3$ red, $2$ blue. A box is chosen at random and a red ball drawn. What is $P(\\text{Box 1}|\\text{red})$?",
    answer: "0.44",
    explanation: "Step 1: $P(R|B_1)=2/3$, $P(R|B_2)=1/4$, $P(R|B_3)=3/5$. Each box selected with prob $1/3$. Step 2: $P(R)=\\frac{1}{3}\\left(\\frac{2}{3}+\\frac{1}{4}+\\frac{3}{5}\\right)=\\frac{1}{3}\\cdot\\frac{40+15+36}{60}=\\frac{91}{180}$. Step 3: $P(B_1|R)=\\frac{(2/3)(1/3)}{91/180}=\\frac{2/9}{91/180}=\\frac{40}{91}\\approx0.44$. Final answer: $0.44$." }),
  p({ id: "prob-counting-8", topicId: "probability", section: "counting", type: "numeric", difficulty: "hard",
    prompt: "How many ways to distribute $5$ distinct balls into $3$ distinct boxes?",
    answer: "243",
    explanation: "Step 1: Each ball has $3$ choices: $3^5=243$. Final answer: $243$." }),
  p({ id: "prob-conditional-7", topicId: "probability", section: "conditional", type: "numeric", difficulty: "hard",
    prompt: "A card is drawn. $P(\\text{Heart}|\\text{Red card})=?$",
    answer: "0.5",
    explanation: "Step 1: Given the card is red ($26$ red cards), $13$ are Hearts. $P(\\text{Heart}|\\text{Red})=13/26=0.5$. Final answer: $0.5$." }),
  p({ id: "prob-total-5", topicId: "probability", section: "total", type: "numeric", difficulty: "hard",
    prompt: "Urn A: $3$ red, $2$ blue. Urn B: $1$ red, $4$ blue. Choose urn A with prob $0.6$, urn B with $0.4$. $P(\\text{red})=$",
    answer: "0.44",
    explanation: "Step 1: $P(R)=0.6\\times(3/5)+0.4\\times(1/5)=0.36+0.08=0.44$. Final answer: $0.44$." }),
  p({ id: "prob-basic-10", topicId: "probability", section: "basic", type: "numeric", difficulty: "hard",
    prompt: "Five cards are dealt from a standard deck. $P(\\text{at least one Ace})=1-P(\\text{no Aces})$. Find $P(\\text{no Aces})\\approx$",
    answer: "0.659",
    explanation: "Step 1: $P(\\text{no Ace})=\\binom{48}{5}/\\binom{52}{5}=1712304/2598960\\approx0.659$. Final answer: $0.659$." }),
  p({ id: "prob-bayes-5", topicId: "probability", section: "bayes", type: "mcq", difficulty: "hard",
    prompt: "Prior probability, likelihood, and posterior probability are key concepts in:",
    answer: "Bayesian inference.",
    choices: ["Frequentist hypothesis testing.", "Bayesian inference.", "Descriptive statistics.", "ANOVA."],
    explanation: "Step 1: Bayesian inference updates the prior $P(H)$ via likelihood $P(D|H)$ to get posterior $P(H|D)\\propto P(D|H)P(H)$. Final answer: Bayesian inference." }),
  p({ id: "prob-counting-9", topicId: "probability", section: "counting", type: "numeric", difficulty: "hard",
    prompt: "How many ways can $4$ students be seated in $10$ available seats (order matters)?",
    answer: "5040",
    explanation: "Step 1: $P(10,4)=10\\times9\\times8\\times7=5040$. Final answer: $5040$." }),
  p({ id: "prob-conditional-8", topicId: "probability", section: "conditional", type: "mcq", difficulty: "hard",
    prompt: "If $P(A)>0$ and $P(B)>0$, and $A$ and $B$ are mutually exclusive, then they are:",
    answer: "Dependent (not independent).",
    choices: ["Independent.", "Dependent (not independent).", "Conditionally independent.", "Complementary."],
    explanation: "Step 1: Mutually exclusive: $P(A\\cap B)=0$. Independent would require $P(A\\cap B)=P(A)P(B)>0$. Contradiction: they must be dependent. Final answer: Dependent (not independent)." }),
  p({ id: "prob-total-6", topicId: "probability", section: "total", type: "numeric", difficulty: "hard",
    prompt: "A new medical test: $P(+|\\text{sick})=0.99$, $P(+|\\text{healthy})=0.05$, $P(\\text{sick})=0.002$. Find $P(+)$.",
    answer: "0.0520",
    explanation: "Step 1: $P(+)=0.99(0.002)+0.05(0.998)=0.00198+0.0499=0.05188\\approx0.0520$. Final answer: $0.0520$." }),
  p({ id: "prob-counting-10", topicId: "probability", section: "counting", type: "numeric", difficulty: "hard",
    prompt: "A poker hand is 5 cards from 52. How many distinct 5-card hands are there?",
    answer: "2598960",
    explanation: "Step 1: $\\binom{52}{5}=52!/(5!47!)=2598960$. Final answer: $2598960$." }),
];
