import type { Problem } from "../shared-types";

const p = (problem: Problem) => problem;

export const samplingProblems: Problem[] = [
  // --- Easy (14) ---
  p({ id: "samp-se-1", topicId: "sampling", section: "sampling-distribution", type: "numeric", difficulty: "easy",
    prompt: "A population has $\\sigma=12$. What is the standard error for samples of $n=9$?",
    answer: "4",
    explanation: "Step 1: $SE=\\sigma/\\sqrt{n}=12/\\sqrt{9}=12/3=4$. Final answer: $4$." }),
  p({ id: "samp-lln-1", topicId: "sampling", section: "lln", type: "mcq", difficulty: "easy",
    prompt: "The Law of Large Numbers states that as $n$ increases, the sample mean:",
    answer: "Converges to the population mean.",
    choices: ["Converges to the population mean.", "Converges to zero.", "Becomes more variable.", "Equals the sample median."],
    explanation: "Step 1: LLN: $\\bar{x}\\to\\mu$ as $n\\to\\infty$. Final answer: Converges to the population mean." }),
  p({ id: "samp-pop-1", topicId: "sampling", section: "pop-vs-sample", type: "mcq", difficulty: "easy",
    prompt: "A parameter describes a ___; a statistic describes a ___.",
    answer: "Population; sample.",
    choices: ["Sample; population.", "Population; sample.", "Variable; constant.", "Mean; median."],
    explanation: "Step 1: Parameters are fixed population quantities (e.g., $\\mu$, $\\sigma$). Statistics are computed from samples (e.g., $\\bar{x}$, $s$). Final answer: Population; sample." }),
  p({ id: "samp-se-2", topicId: "sampling", section: "sampling-distribution", type: "numeric", difficulty: "easy",
    prompt: "Population $\\sigma=20$, $n=100$. Find $SE_{\\bar{x}}$.",
    answer: "2",
    explanation: "Step 1: $SE=\\sigma/\\sqrt{n}=20/\\sqrt{100}=20/10=2$. Final answer: $2$." }),
  p({ id: "samp-clt-1", topicId: "sampling", section: "clt", type: "mcq", difficulty: "easy",
    prompt: "The CLT states that the sampling distribution of $\\bar{x}$ approaches normal as:",
    answer: "Sample size $n$ increases.",
    choices: ["Sample size $n$ increases.", "Population size $N$ increases.", "The population becomes normal.", "The variance decreases."],
    explanation: "Step 1: CLT applies regardless of population shape as $n$ grows. Rule of thumb: $n\\geq30$. Final answer: Sample size $n$ increases." }),
  p({ id: "samp-pop-2", topicId: "sampling", section: "pop-vs-sample", type: "mcq", difficulty: "easy",
    prompt: "The sample mean $\\bar{x}$ is an example of a:",
    answer: "Statistic.",
    choices: ["Parameter.", "Statistic.", "Population.", "Variance."],
    explanation: "Step 1: $\\bar{x}$ is computed from sample data, so it is a statistic. Final answer: Statistic." }),
  p({ id: "samp-lln-2", topicId: "sampling", section: "lln", type: "mcq", difficulty: "easy",
    prompt: "Which phenomenon explains why a casino always profits in the long run?",
    answer: "Law of Large Numbers.",
    choices: ["Central Limit Theorem.", "Law of Large Numbers.", "Standard Error.", "Sampling bias."],
    explanation: "Step 1: The LLN guarantees that repeated independent trials average out to the expected value. For a casino, the expected return is negative for the player. Final answer: Law of Large Numbers." }),
  p({ id: "samp-se-3", topicId: "sampling", section: "sampling-distribution", type: "mcq", difficulty: "easy",
    prompt: "As sample size $n$ increases, the standard error $SE=\\sigma/\\sqrt{n}$:",
    answer: "Decreases.",
    choices: ["Increases.", "Decreases.", "Stays the same.", "Doubles."],
    explanation: "Step 1: $SE=\\sigma/\\sqrt{n}$: increasing $n$ increases $\\sqrt{n}$, so $SE$ decreases. Final answer: Decreases." }),
  p({ id: "samp-clt-2", topicId: "sampling", section: "clt", type: "numeric", difficulty: "easy",
    prompt: "Population: $\\mu=50$, $\\sigma=10$. For $n=25$ samples, $E(\\bar{X})=$",
    answer: "50",
    explanation: "Step 1: The expected value of $\\bar{X}$ always equals the population mean: $E(\\bar{X})=\\mu=50$. Final answer: $50$." }),
  p({ id: "samp-pop-3", topicId: "sampling", section: "pop-vs-sample", type: "mcq", difficulty: "easy",
    prompt: "A census collects data from:",
    answer: "Every member of the population.",
    choices: ["A random sample.", "Every member of the population.", "Only outliers.", "A convenience sample."],
    explanation: "Step 1: A census surveys the entire population, not a sample. Final answer: Every member of the population." }),
  p({ id: "samp-sampling-1", topicId: "sampling", section: "sampling-distribution", type: "mcq", difficulty: "easy",
    prompt: "The sampling distribution of $\\bar{x}$ has mean $\\mu_{\\bar{x}}=$",
    answer: "$\\mu$",
    choices: ["$\\mu/n$", "$\\mu$", "$\\sigma/\\sqrt{n}$", "$\\sigma^2$"],
    explanation: "Step 1: The mean of the sampling distribution of $\\bar{X}$ equals the population mean $\\mu$. Final answer: $\\mu$." }),
  p({ id: "samp-lln-3", topicId: "sampling", section: "lln", type: "mcq", difficulty: "easy",
    prompt: "The Weak Law of Large Numbers says $\\bar{X}_n\\to\\mu$ in:",
    answer: "Probability.",
    choices: ["Almost surely.", "Probability.", "Distribution.", "Expectation."],
    explanation: "Step 1: The Weak LLN: $P(|\\bar{X}_n-\\mu|>\\epsilon)\\to0$ for any $\\epsilon>0$ (convergence in probability). Final answer: Probability." }),
  p({ id: "samp-clt-3", topicId: "sampling", section: "clt", type: "mcq", difficulty: "easy",
    prompt: "For the CLT, the sampling distribution of $\\bar{X}$ has standard deviation (standard error):",
    answer: "$\\sigma/\\sqrt{n}$",
    choices: ["$\\sigma$", "$\\sigma/\\sqrt{n}$", "$\\sigma^2/n$", "$\\sigma\\sqrt{n}$"],
    explanation: "Step 1: $\\sigma_{\\bar{X}}=\\sigma/\\sqrt{n}$ (standard error of the mean). Final answer: $\\sigma/\\sqrt{n}$." }),
  p({ id: "samp-pop-4", topicId: "sampling", section: "pop-vs-sample", type: "mcq", difficulty: "easy",
    prompt: "Sampling bias occurs when:",
    answer: "The sample is not representative of the population.",
    choices: ["The sample size is too large.", "The sample is not representative of the population.", "Parameters are estimated.", "The population is large."],
    explanation: "Step 1: Bias arises when the sampling method systematically over- or under-represents parts of the population. Final answer: The sample is not representative of the population." }),

  // --- Medium (16) ---
  p({ id: "samp-se-4", topicId: "sampling", section: "sampling-distribution", type: "numeric", difficulty: "medium",
    prompt: "Population: $\\mu=100$, $\\sigma=15$, $n=25$. Find $SE$ and the $z$-score for $\\bar{x}=106$.",
    answer: "2",
    explanation: "Step 1: $SE=15/\\sqrt{25}=3$. Step 2: $z=(106-100)/3=2$. Final answer: $z=2$." }),
  p({ id: "samp-clt-4", topicId: "sampling", section: "clt", type: "numeric", difficulty: "medium",
    prompt: "Population: $\\mu=40$, $\\sigma=8$, $n=64$. By CLT, $\\bar{X}\\sim N(40,1)$. $P(\\bar{X}>41)\\approx$",
    answer: "0.1587",
    explanation: "Step 1: $SE=8/\\sqrt{64}=1$. $z=(41-40)/1=1$. $P(\\bar{X}>41)=1-\\Phi(1)=1-0.8413=0.1587$. Final answer: $0.1587$." }),
  p({ id: "samp-sampling-2", topicId: "sampling", section: "sampling-distribution", type: "numeric", difficulty: "medium",
    prompt: "If $n$ increases from $25$ to $100$, by what factor does $SE$ decrease?",
    answer: "2",
    explanation: "Step 1: $SE\\propto1/\\sqrt{n}$. Ratio: $SE_{100}/SE_{25}=\\sqrt{25}/\\sqrt{100}=5/10=1/2$. SE halves; decrease factor $=2$. Final answer: $2$." }),
  p({ id: "samp-prop-1", topicId: "sampling", section: "sampling-distribution", type: "numeric", difficulty: "medium",
    prompt: "For sampling distribution of proportion $\\hat{p}$: $n=200$, $p=0.4$. Find $SE_{\\hat{p}}=\\sqrt{p(1-p)/n}$.",
    answer: "0.0346",
    explanation: "Step 1: $SE=\\sqrt{0.4(0.6)/200}=\\sqrt{0.0012}\\approx0.0346$. Final answer: $0.0346$." }),
  p({ id: "samp-clt-5", topicId: "sampling", section: "clt", type: "mcq", difficulty: "medium",
    prompt: "The CLT applies even when the population is skewed, provided:",
    answer: "$n$ is sufficiently large (typically $n\\geq30$).",
    choices: ["$n=5$ always suffices.", "$n$ is sufficiently large (typically $n\\geq30$).", "The population is symmetric.", "The variance is small."],
    explanation: "Step 1: For skewed distributions, a larger $n$ is needed. The common rule of thumb is $n\\geq30$. Final answer: $n$ is sufficiently large (typically $n\\geq30$)." }),
  p({ id: "samp-lln-4", topicId: "sampling", section: "lln", type: "mcq", difficulty: "medium",
    prompt: "The Gambler's Fallacy incorrectly applies the LLN by thinking:",
    answer: "A streak of losses must be followed by wins to 'balance out'.",
    choices: ["Each trial is independent.", "A streak of losses must be followed by wins to 'balance out'.", "The LLN applies to single trials.", "The expected value is always positive."],
    explanation: "Step 1: The LLN applies to averages over many trials, not to individual outcomes. Upcoming results do not 'compensate' for past results in independent trials. Final answer: A streak of losses must be followed by wins to 'balance out'." }),
  p({ id: "samp-se-5", topicId: "sampling", section: "sampling-distribution", type: "numeric", difficulty: "medium",
    prompt: "Population proportion $p=0.6$, $n=150$. Find $SE_{\\hat{p}}$.",
    answer: "0.04",
    explanation: "Step 1: $SE=\\sqrt{p(1-p)/n}=\\sqrt{0.6(0.4)/150}=\\sqrt{0.0016}=0.04$. Final answer: $0.04$." }),
  p({ id: "samp-clt-6", topicId: "sampling", section: "clt", type: "numeric", difficulty: "medium",
    prompt: "Population: $\\mu=500$, $\\sigma=100$, $n=100$. By CLT, $\\bar{X}\\sim N(500,100)$. $P(490<\\bar{X}<510)\\approx$",
    answer: "0.6827",
    explanation: "Step 1: $SE=100/\\sqrt{100}=10$. $z_1=(490-500)/10=-1$, $z_2=(510-500)/10=1$. $P=\\Phi(1)-\\Phi(-1)\\approx0.6827$. Final answer: $0.6827$." }),
  p({ id: "samp-pop-5", topicId: "sampling", section: "pop-vs-sample", type: "mcq", difficulty: "medium",
    prompt: "In random sampling, each member of the population has:",
    answer: "An equal probability of being selected.",
    choices: ["No chance of selection.", "An equal probability of being selected.", "A probability proportional to their value.", "A probability of $1$."],
    explanation: "Step 1: Simple random sampling: every individual has equal probability of selection. Final answer: An equal probability of being selected." }),
  p({ id: "samp-sampling-3", topicId: "sampling", section: "sampling-distribution", type: "mcq", difficulty: "medium",
    prompt: "Which is true about the sampling distribution of $\\bar{X}$ regardless of population shape?",
    answer: "$E(\\bar{X})=\\mu$ always.",
    choices: ["It is always normal.", "$E(\\bar{X})=\\mu$ always.", "$\\text{Var}(\\bar{X})=\\sigma^2$ always.", "It is always symmetric."],
    explanation: "Step 1: $E(\\bar{X})=\\mu$ is always true (unbiasedness), regardless of population shape or $n$. Normality follows from CLT only for large $n$. Final answer: $E(\\bar{X})=\\mu$ always." }),
  p({ id: "samp-clt-7", topicId: "sampling", section: "clt", type: "numeric", difficulty: "medium",
    prompt: "Heights: $\\mu=170$cm, $\\sigma=10$cm. For $n=100$: what is $\\text{Var}(\\bar{X})$?",
    answer: "1",
    explanation: "Step 1: $\\text{Var}(\\bar{X})=\\sigma^2/n=100/100=1$. Final answer: $1$." }),
  p({ id: "samp-lln-5", topicId: "sampling", section: "lln", type: "numeric", difficulty: "medium",
    prompt: "A fair coin flipped $n=10000$ times. By LLN, $E(\\text{proportion of heads})=$",
    answer: "0.5",
    explanation: "Step 1: LLN: sample proportion converges to $p=0.5$. Final answer: $0.5$." }),
  p({ id: "samp-se-6", topicId: "sampling", section: "sampling-distribution", type: "mcq", difficulty: "medium",
    prompt: "To halve the standard error, you must multiply the sample size by:",
    answer: "$4$.",
    choices: ["$2$.", "$4$.", "$\\sqrt{2}$.", "$1/2$."],
    explanation: "Step 1: $SE=\\sigma/\\sqrt{n}$. To halve $SE$: $\\sigma/\\sqrt{4n}=\\frac{1}{2}(\\sigma/\\sqrt{n})$. Must multiply $n$ by $4$. Final answer: $4$." }),
  p({ id: "samp-prop-2", topicId: "sampling", section: "sampling-distribution", type: "mcq", difficulty: "medium",
    prompt: "The sampling distribution of $\\hat{p}$ is approximately normal when:",
    answer: "$np\\geq10$ and $n(1-p)\\geq10$.",
    choices: ["$n>30$.", "$np\\geq10$ and $n(1-p)\\geq10$.", "$p=0.5$.", "$n>100$."],
    explanation: "Step 1: The condition for approximate normality of $\\hat{p}$ is $np\\geq10$ and $n(1-p)\\geq10$ (some texts use $5$). Final answer: $np\\geq10$ and $n(1-p)\\geq10$." }),
  p({ id: "samp-clt-8", topicId: "sampling", section: "clt", type: "mcq", difficulty: "medium",
    prompt: "If the population is already normal, the sampling distribution of $\\bar{X}$ is normal for:",
    answer: "Any sample size $n$.",
    choices: ["Only $n\\geq30$.", "Only $n\\geq100$.", "Any sample size $n$.", "Only $n=1$."],
    explanation: "Step 1: If the population is normal, $\\bar{X}$ is exactly normal for any $n$. The CLT is only needed when the population is non-normal. Final answer: Any sample size $n$." }),

  // --- Hard (10) ---
  p({ id: "samp-clt-9", topicId: "sampling", section: "clt", type: "numeric", difficulty: "hard",
    prompt: "Population: exponential with mean $\\mu=2$, $\\sigma=2$, $n=50$. By CLT, $P(\\bar{X}>2.5)\\approx\\Phi(z)$. Find $z$.",
    answer: "1.77",
    explanation: "Step 1: $SE=2/\\sqrt{50}=2/7.07\\approx0.283$. $z=(2.5-2)/0.283\\approx1.77$. Final answer: $z\\approx1.77$." }),
  p({ id: "samp-se-7", topicId: "sampling", section: "sampling-distribution", type: "numeric", difficulty: "hard",
    prompt: "Population: $\\mu=80$, $\\sigma=15$. $n=36$. $P(\\bar{X}<78)=\\Phi(z)$. Find $z$.",
    answer: "-0.8",
    explanation: "Step 1: $SE=15/\\sqrt{36}=2.5$. $z=(78-80)/2.5=-0.8$. Final answer: $-0.8$." }),
  p({ id: "samp-prop-3", topicId: "sampling", section: "sampling-distribution", type: "numeric", difficulty: "hard",
    prompt: "In a poll, $\\hat{p}=0.52$, $n=1000$. $p_0=0.50$. $z=(\\hat{p}-p_0)/\\sqrt{p_0(1-p_0)/n}=$",
    answer: "1.265",
    explanation: "Step 1: $SE=\\sqrt{0.5(0.5)/1000}=\\sqrt{0.00025}=0.01581$. $z=(0.52-0.50)/0.01581\\approx1.265$. Final answer: $1.265$." }),
  p({ id: "samp-lln-6", topicId: "sampling", section: "lln", type: "mcq", difficulty: "hard",
    prompt: "The Strong Law of Large Numbers says $\\bar{X}_n\\to\\mu$:",
    answer: "Almost surely (with probability 1).",
    choices: ["In probability.", "Almost surely (with probability 1).", "In distribution.", "In mean square."],
    explanation: "Step 1: The Strong LLN states $P(\\lim_{n\\to\\infty}\\bar{X}_n=\\mu)=1$ (almost sure convergence). Final answer: Almost surely (with probability 1)." }),
  p({ id: "samp-clt-10", topicId: "sampling", section: "clt", type: "numeric", difficulty: "hard",
    prompt: "Population: $\\mu=10$, $\\sigma=5$. How large must $n$ be so that $SE\\leq0.5$?",
    answer: "100",
    explanation: "Step 1: $SE=5/\\sqrt{n}\\leq0.5\\Rightarrow\\sqrt{n}\\geq10\\Rightarrow n\\geq100$. Final answer: $100$." }),
  p({ id: "samp-se-8", topicId: "sampling", section: "sampling-distribution", type: "mcq", difficulty: "hard",
    prompt: "The finite population correction factor (FPC) $\\sqrt{(N-n)/(N-1)}$ is applied when:",
    answer: "The sample is more than 5% of the population.",
    choices: ["$n>30$.", "The sample is more than 5% of the population.", "The population is normal.", "The sample size equals $N$."],
    explanation: "Step 1: FPC is used when sampling without replacement from a finite population and $n/N>0.05$. It reduces the SE. Final answer: The sample is more than 5% of the population." }),
  p({ id: "samp-clt-11", topicId: "sampling", section: "clt", type: "numeric", difficulty: "hard",
    prompt: "Sum $S_n=X_1+\\cdots+X_n$ where each $X_i\\sim N(3,4)$. For $n=16$, find $E(S_{16})$.",
    answer: "48",
    explanation: "Step 1: $E(S_n)=n\\mu=16\\times3=48$. Final answer: $48$." }),
  p({ id: "samp-prop-4", topicId: "sampling", section: "sampling-distribution", type: "numeric", difficulty: "hard",
    prompt: "A sample of $n=400$ gives $\\hat{p}=0.45$. Build a 95% CI: $\\hat{p}\\pm1.96\\sqrt{\\hat{p}(1-\\hat{p})/n}$. What is the margin of error?",
    answer: "0.0488",
    explanation: "Step 1: $SE=\\sqrt{0.45(0.55)/400}=\\sqrt{0.000619}\\approx0.02488$. $ME=1.96(0.02488)\\approx0.0488$. Final answer: $0.0488$." }),
  p({ id: "samp-lln-7", topicId: "sampling", section: "lln", type: "mcq", difficulty: "hard",
    prompt: "Which assumption is required for the LLN?",
    answer: "The $X_i$ are independent and identically distributed with finite mean.",
    choices: ["The $X_i$ are normally distributed.", "The $X_i$ are independent and identically distributed with finite mean.", "The sample size is exactly $30$.", "The population variance is known."],
    explanation: "Step 1: LLN requires i.i.d. observations and a finite mean $\\mu$. The population need not be normal. Final answer: The $X_i$ are independent and identically distributed with finite mean." }),
  p({ id: "samp-clt-12", topicId: "sampling", section: "clt", type: "numeric", difficulty: "hard",
    prompt: "Average daily demand $\\mu=200$, $\\sigma=30$, $n=9$ days. $P(\\bar{X}>210)\\approx$",
    answer: "0.1587",
    explanation: "Step 1: $SE=30/3=10$. $z=(210-200)/10=1$. $P(\\bar{X}>210)=1-\\Phi(1)=0.1587$. Final answer: $0.1587$." }),
];
