import type { Problem } from "../shared-types";

const p = (problem: Problem) => problem;

export const determinantProblems: Problem[] = [
  // --- Easy (14) ---
  p({ id: "det-cofactor-1", topicId: "determinants", section: "cofactor", type: "numeric", difficulty: "easy",
    prompt: "Compute $\\det\\begin{pmatrix}3&2\\\\1&4\\end{pmatrix}$.",
    answer: "10",
    explanation: "Step 1: $\\det = ad-bc = 3(4)-2(1) = 10$. Final answer: $10$." }),
  p({ id: "det-cofactor-2", topicId: "determinants", section: "cofactor", type: "numeric", difficulty: "easy",
    prompt: "Compute $\\det\\begin{pmatrix}5&3\\\\2&4\\end{pmatrix}$.",
    answer: "14",
    explanation: "Step 1: $5(4)-3(2)=20-6=14$. Final answer: $14$." }),
  p({ id: "det-cofactor-3", topicId: "determinants", section: "cofactor", type: "numeric", difficulty: "easy",
    prompt: "Compute $\\det\\begin{pmatrix}-1&2\\\\3&4\\end{pmatrix}$.",
    answer: "-10",
    explanation: "Step 1: $(-1)(4)-(2)(3)=-4-6=-10$. Final answer: $-10$." }),
  p({ id: "det-properties-1", topicId: "determinants", section: "properties", type: "mcq", difficulty: "easy",
    prompt: "A matrix $A$ is invertible if and only if $\\det(A)$ is:",
    answer: "Nonzero.",
    choices: ["Zero.", "Nonzero.", "Positive.", "Equal to 1."],
    explanation: "Step 1: Invertibility $\\Leftrightarrow$ $\\det(A)\\neq 0$. Final answer: Nonzero." }),
  p({ id: "det-properties-2", topicId: "determinants", section: "properties", type: "numeric", difficulty: "easy",
    prompt: "What is $\\det(I_3)$ where $I_3$ is the $3\\times 3$ identity?",
    answer: "1",
    explanation: "Step 1: The identity matrix is already in REF with all pivots equal to $1$. Step 2: $\\det(I)=1$. Final answer: $1$." }),
  p({ id: "det-properties-3", topicId: "determinants", section: "properties", type: "numeric", difficulty: "easy",
    prompt: "If $\\det(A)=5$ for a $3\\times 3$ matrix, what is $\\det(2A)$?",
    answer: "40",
    explanation: "Step 1: $\\det(cA)=c^n\\det(A)$. Step 2: $\\det(2A)=2^3\\cdot 5=40$. Final answer: $40$." }),
  p({ id: "det-properties-4", topicId: "determinants", section: "properties", type: "numeric", difficulty: "easy",
    prompt: "What is $\\det(A^T)$ if $\\det(A)=7$?",
    answer: "7",
    explanation: "Step 1: $\\det(A^T)=\\det(A)$ always. Step 2: $\\det(A^T)=7$. Final answer: $7$." }),
  p({ id: "det-properties-5", topicId: "determinants", section: "properties", type: "numeric", difficulty: "easy",
    prompt: "If two rows of $A$ are identical, what is $\\det(A)$?",
    answer: "0",
    explanation: "Step 1: A matrix with two identical rows has determinant $0$ (it's singular). Final answer: $0$." }),
  p({ id: "det-cofactor-4", topicId: "determinants", section: "cofactor", type: "numeric", difficulty: "easy",
    prompt: "Compute $\\det\\begin{pmatrix}2&0\\\\0&6\\end{pmatrix}$.",
    answer: "12",
    explanation: "Step 1: For a diagonal matrix, $\\det=$ product of diagonal entries $=2\\cdot 6=12$. Final answer: $12$." }),
  p({ id: "det-properties-6", topicId: "determinants", section: "properties", type: "mcq", difficulty: "easy",
    prompt: "What happens to $\\det(A)$ when you swap two rows?",
    answer: "It changes sign.",
    choices: ["It doubles.", "It changes sign.", "It stays the same.", "It becomes zero."],
    explanation: "Step 1: Swapping two rows multiplies the determinant by $-1$. Final answer: It changes sign." }),
  p({ id: "det-cramer-1", topicId: "determinants", section: "cramer", type: "mcq", difficulty: "easy",
    prompt: "Cramer's Rule gives the solution to $A\\mathbf{x}=\\mathbf{b}$ as $x_i=$",
    answer: "$\\det(A_i)/\\det(A)$",
    choices: ["$\\det(A)/\\det(A_i)$", "$\\det(A_i)/\\det(A)$", "$\\det(A_i)\\cdot\\det(A)$", "$\\det(A_i)-\\det(A)$"],
    explanation: "Step 1: Cramer's Rule: $x_i=\\frac{\\det(A_i)}{\\det(A)}$ where $A_i$ is $A$ with column $i$ replaced by $\\mathbf{b}$. Final answer: $\\det(A_i)/\\det(A)$." }),
  p({ id: "det-geometric-1", topicId: "determinants", section: "geometric", type: "mcq", difficulty: "easy",
    prompt: "The absolute value of $\\det(A)$ for a $2\\times 2$ matrix equals:",
    answer: "The area of the parallelogram formed by the columns of $A$.",
    choices: ["The perimeter of a rectangle.", "The area of the parallelogram formed by the columns of $A$.", "The sum of the column lengths.", "The angle between the columns."],
    explanation: "Step 1: $|\\det(A)|$ equals the area of the parallelogram spanned by the column vectors of $A$. Final answer: The area of the parallelogram formed by the columns of $A$." }),
  p({ id: "det-properties-7", topicId: "determinants", section: "properties", type: "numeric", difficulty: "easy",
    prompt: "If $\\det(A)=3$ and $\\det(B)=4$, what is $\\det(AB)$?",
    answer: "12",
    explanation: "Step 1: $\\det(AB)=\\det(A)\\cdot\\det(B)=3\\cdot 4=12$. Final answer: $12$." }),
  p({ id: "det-cofactor-5", topicId: "determinants", section: "cofactor", type: "numeric", difficulty: "easy",
    prompt: "Compute $\\det\\begin{pmatrix}1&2&0\\\\0&3&0\\\\0&0&5\\end{pmatrix}$.",
    answer: "15",
    explanation: "Step 1: Upper triangular: $\\det=$ product of diagonal $=1\\cdot 3\\cdot 5=15$. Final answer: $15$." }),

  // --- Medium (16) ---
  p({ id: "det-cofactor-6", topicId: "determinants", section: "cofactor", type: "numeric", difficulty: "medium",
    prompt: "Expand along the first row: $\\det\\begin{pmatrix}2&1&3\\\\0&4&1\\\\0&0&5\\end{pmatrix}$.",
    answer: "40",
    explanation: "Step 1: Upper triangular: $\\det=2\\cdot 4\\cdot 5=40$. Final answer: $40$." }),
  p({ id: "det-cofactor-7", topicId: "determinants", section: "cofactor", type: "numeric", difficulty: "medium",
    prompt: "Compute $\\det\\begin{pmatrix}1&2&3\\\\0&-1&4\\\\0&0&2\\end{pmatrix}$ by expanding along column 1.",
    answer: "-2",
    explanation: "Step 1: Column 1 has only one nonzero entry: $A_{11}=1$. Step 2: $\\det=1\\cdot\\det\\begin{pmatrix}-1&4\\\\0&2\\end{pmatrix}=1(-2-0)=-2$. Final answer: $-2$." }),
  p({ id: "det-properties-8", topicId: "determinants", section: "properties", type: "numeric", difficulty: "medium",
    prompt: "Find $\\det(A^{-1})$ if $\\det(A)=4$.",
    answer: "0.25",
    explanation: "Step 1: $\\det(A^{-1})=1/\\det(A)=1/4=0.25$. Final answer: $0.25$." }),
  p({ id: "det-cramer-2", topicId: "determinants", section: "cramer", type: "numeric", difficulty: "medium",
    prompt: "Use Cramer's Rule to solve $3x+y=7$, $x+2y=4$. What is $x$?",
    answer: "2",
    explanation: "Step 1: $A=\\begin{pmatrix}3&1\\\\1&2\\end{pmatrix}$, $\\det(A)=6-1=5$. Step 2: $A_1=\\begin{pmatrix}7&1\\\\4&2\\end{pmatrix}$, $\\det(A_1)=14-4=10$. Step 3: $x=10/5=2$. Final answer: $2$." }),
  p({ id: "det-cramer-3", topicId: "determinants", section: "cramer", type: "numeric", difficulty: "medium",
    prompt: "Use Cramer's Rule: $2x+y=5$, $x+3y=10$. What is $y$?",
    answer: "3",
    explanation: "Step 1: $\\det(A)=6-1=5$. Step 2: $A_2=\\begin{pmatrix}2&5\\\\1&10\\end{pmatrix}$, $\\det(A_2)=20-5=15$. Step 3: $y=15/5=3$. Final answer: $3$." }),
  p({ id: "det-properties-9", topicId: "determinants", section: "properties", type: "numeric", difficulty: "medium",
    prompt: "If $A=\\begin{pmatrix}1&2\\\\3&k\\end{pmatrix}$ is singular, find $k$.",
    answer: "6",
    explanation: "Step 1: Singular means $\\det(A)=0$. Step 2: $k-6=0 \\Rightarrow k=6$. Final answer: $6$." }),
  p({ id: "det-cofactor-8", topicId: "determinants", section: "cofactor", type: "numeric", difficulty: "medium",
    prompt: "Find $\\det\\begin{pmatrix}0&1&2\\\\1&0&3\\\\2&4&0\\end{pmatrix}$ by cofactor expansion along row 1.",
    answer: "14",
    explanation: "Step 1: Expand along row 1: $0\\cdot C_{11}+1\\cdot C_{12}+2\\cdot C_{13}$. Step 2: $C_{12}=-\\det\\begin{pmatrix}1&3\\\\2&0\\end{pmatrix}=-(0-6)=6$. Step 3: $C_{13}=+\\det\\begin{pmatrix}1&0\\\\2&4\\end{pmatrix}=4$. Step 4: $0+6+8=14$. Final answer: $14$." }),
  p({ id: "det-geometric-2", topicId: "determinants", section: "geometric", type: "numeric", difficulty: "medium",
    prompt: "Find the area of the parallelogram spanned by $\\mathbf{v}_1=\\langle 3,0\\rangle$ and $\\mathbf{v}_2=\\langle 0,4\\rangle$.",
    answer: "12",
    explanation: "Step 1: Area $=|\\det\\begin{pmatrix}3&0\\\\0&4\\end{pmatrix}|=|12|=12$. Final answer: $12$." }),
  p({ id: "det-properties-10", topicId: "determinants", section: "properties", type: "mcq", difficulty: "medium",
    prompt: "Adding a multiple of one row to another row changes $\\det(A)$ by:",
    answer: "Not at all — the determinant stays the same.",
    choices: ["Multiplying it by a scalar.", "Not at all — the determinant stays the same.", "Adding the scalar to it.", "Changing its sign."],
    explanation: "Step 1: Row replacement ($R_i \\leftarrow R_i + cR_j$) does not change $\\det(A)$. Only row swaps (sign change) and row scaling (multiply by scalar) affect it. Final answer: Not at all — the determinant stays the same." }),
  p({ id: "det-cramer-4", topicId: "determinants", section: "cramer", type: "mcq", difficulty: "medium",
    prompt: "Cramer's Rule applies only when:",
    answer: "$\\det(A)\\neq 0$ (the system has a unique solution).",
    choices: ["$\\det(A)=0$.", "$\\det(A)\\neq 0$ (the system has a unique solution).", "The system is homogeneous.", "The matrix is $2\\times 2$."],
    explanation: "Step 1: Cramer's Rule requires dividing by $\\det(A)$, so $\\det(A)\\neq 0$ is necessary. This means the system has a unique solution. Final answer: $\\det(A)\\neq 0$ (the system has a unique solution)." }),
  p({ id: "det-cofactor-9", topicId: "determinants", section: "cofactor", type: "numeric", difficulty: "medium",
    prompt: "Find $\\det\\begin{pmatrix}2&-1&3\\\\0&4&-2\\\\0&0&1\\end{pmatrix}$.",
    answer: "8",
    explanation: "Step 1: Upper triangular: $\\det=2\\cdot 4\\cdot 1=8$. Final answer: $8$." }),
  p({ id: "det-geometric-3", topicId: "determinants", section: "geometric", type: "numeric", difficulty: "medium",
    prompt: "The parallelogram spanned by $\\langle 2,1\\rangle$ and $\\langle 1,3\\rangle$ has area:",
    answer: "5",
    explanation: "Step 1: Area $=|\\det\\begin{pmatrix}2&1\\\\1&3\\end{pmatrix}|=|6-1|=5$. Final answer: $5$." }),
  p({ id: "det-properties-11", topicId: "determinants", section: "properties", type: "numeric", difficulty: "medium",
    prompt: "If $\\det(A)=-3$, what is $\\det(A^2)$?",
    answer: "9",
    explanation: "Step 1: $\\det(A^2)=\\det(A)^2=(-3)^2=9$. Final answer: $9$." }),
  p({ id: "det-cofactor-10", topicId: "determinants", section: "cofactor", type: "numeric", difficulty: "medium",
    prompt: "Find the cofactor $C_{11}$ of $A=\\begin{pmatrix}3&1&2\\\\2&4&0\\\\1&0&5\\end{pmatrix}$.",
    answer: "20",
    explanation: "Step 1: $C_{11}=+M_{11}=+\\det\\begin{pmatrix}4&0\\\\0&5\\end{pmatrix}=20$. Final answer: $20$." }),
  p({ id: "det-cramer-5", topicId: "determinants", section: "cramer", type: "numeric", difficulty: "medium",
    prompt: "For the $2\\times 2$ system with $\\det(A)=6$ and $\\det(A_2)=18$, what is $x_2$?",
    answer: "3",
    explanation: "Step 1: $x_2=\\det(A_2)/\\det(A)=18/6=3$. Final answer: $3$." }),
  p({ id: "det-geometric-4", topicId: "determinants", section: "geometric", type: "mcq", difficulty: "medium",
    prompt: "A linear transformation $T(\\mathbf{x})=A\\mathbf{x}$ scales all areas by a factor of:",
    answer: "$|\\det(A)|$",
    choices: ["$\\det(A)^2$", "$|\\det(A)|$", "$\\text{tr}(A)$", "$\\|A\\|$"],
    explanation: "Step 1: The absolute value of the determinant gives the factor by which the transformation scales areas (volumes in $\\mathbb{R}^n$). Final answer: $|\\det(A)|$." }),

  // --- Hard (10) ---
  p({ id: "det-cofactor-11", topicId: "determinants", section: "cofactor", type: "numeric", difficulty: "hard",
    prompt: "Compute $\\det\\begin{pmatrix}1&2&3\\\\4&5&6\\\\7&8&9\\end{pmatrix}$.",
    answer: "0",
    explanation: "Step 1: Row 3 $= $ Row 1 $+$ Row 2 (since $7=1+4+2$, wait: $7\\neq 5$). Actually $R_3=R_1+2R_2-R_2=R_1+R_2$: $1+4=5\\neq 7$. Try $R_3=R_1+R_2+(R_3-R_1-R_2)$. Easier: columns have constant difference: col $2-$col $1=\\begin{pmatrix}1\\\\1\\\\1\\end{pmatrix}=$ col $3-$col $2$. So columns are linearly dependent, $\\det=0$. Final answer: $0$." }),
  p({ id: "det-properties-12", topicId: "determinants", section: "properties", type: "numeric", difficulty: "hard",
    prompt: "For $A=\\begin{pmatrix}0&1\\\\-1&0\\end{pmatrix}$ (rotation by $90^\\circ$), find $\\det(A)$. What does this say about areas?",
    answer: "1",
    explanation: "Step 1: $\\det(A)=(0)(0)-(1)(-1)=1$. Step 2: $|\\det(A)|=1$ means the transformation preserves area. Final answer: $1$." }),
  p({ id: "det-cramer-6", topicId: "determinants", section: "cramer", type: "numeric", difficulty: "hard",
    prompt: "Use Cramer's Rule to solve $x+2y+z=4$, $2x+y+z=5$, $x+y+2z=5$. What is $z$?",
    answer: "1",
    explanation: "Step 1: $\\det(A)=1(2-1)-2(4-1)+1(2-1)=1-6+1=-4$. Step 2: $A_3$ replaces col 3 by $(4,5,5)^T$: $\\det(A_3)=1(5-5)-2(10-5)+4(2-1)=0-10+4=-4$... wait let me compute carefully. $A=\\begin{pmatrix}1&2&1\\\\2&1&1\\\\1&1&2\\end{pmatrix}$. $\\det(A)=1(2-1)-2(4-1)+1(2-1)=1-6+1=-4$. $A_3=\\begin{pmatrix}1&2&4\\\\2&1&5\\\\1&1&5\\end{pmatrix}$. $\\det(A_3)=1(5-5)-2(10-5)+4(2-1)=0-10+4=-4$. $z=(-4)/(-4)=1$. Final answer: $1$." }),
  p({ id: "det-geometric-5", topicId: "determinants", section: "geometric", type: "numeric", difficulty: "hard",
    prompt: "The volume of the parallelepiped spanned by $\\langle 2,0,0\\rangle$, $\\langle 0,3,0\\rangle$, $\\langle 0,0,4\\rangle$ is:",
    answer: "24",
    explanation: "Step 1: Volume $=|\\det\\begin{pmatrix}2&0&0\\\\0&3&0\\\\0&0&4\\end{pmatrix}|=|2\\cdot3\\cdot4|=24$. Final answer: $24$." }),
  p({ id: "det-properties-13", topicId: "determinants", section: "properties", type: "numeric", difficulty: "hard",
    prompt: "For $A=\\begin{pmatrix}a&b\\\\c&d\\end{pmatrix}$, the $(1,2)$ entry of $\\text{adj}(A)$ (classical adjoint) is $-c$. If $A=\\begin{pmatrix}3&2\\\\5&4\\end{pmatrix}$, find the $(1,2)$ entry of $A^{-1}$.",
    answer: "-1",
    explanation: "Step 1: $\\det(A)=12-10=2$. Step 2: $\\text{adj}(A)=\\begin{pmatrix}4&-2\\\\-5&3\\end{pmatrix}$. Step 3: $A^{-1}=\\frac{1}{2}\\begin{pmatrix}4&-2\\\\-5&3\\end{pmatrix}$. Step 4: $(A^{-1})_{12}=-2/2=-1$. Final answer: $-1$." }),
  p({ id: "det-cofactor-12", topicId: "determinants", section: "cofactor", type: "numeric", difficulty: "hard",
    prompt: "Expand along column 2: $\\det\\begin{pmatrix}1&0&2\\\\3&0&4\\\\5&1&6\\end{pmatrix}$.",
    answer: "2",
    explanation: "Step 1: Only $(3,2)$ entry is nonzero in col 2: $A_{32}=1$. Step 2: Cofactor $C_{32}=(-1)^{3+2}\\det\\begin{pmatrix}1&2\\\\3&4\\end{pmatrix}=-(4-6)=2$. Step 3: $\\det=1\\cdot 2=2$. Final answer: $2$." }),
  p({ id: "det-properties-14", topicId: "determinants", section: "properties", type: "mcq", difficulty: "hard",
    prompt: "If $A$ is $n\\times n$ and $A^2=A$ (idempotent), then $\\det(A)$ equals:",
    answer: "$0$ or $1$.",
    choices: ["Always $1$.", "Always $0$.", "$0$ or $1$.", "$n$ or $1$."],
    explanation: "Step 1: $\\det(A^2)=\\det(A)\\Rightarrow\\det(A)^2=\\det(A)\\Rightarrow\\det(A)(\\det(A)-1)=0$. Step 2: So $\\det(A)=0$ or $\\det(A)=1$. Final answer: $0$ or $1$." }),
  p({ id: "det-cramer-7", topicId: "determinants", section: "cramer", type: "numeric", difficulty: "hard",
    prompt: "For $A=\\begin{pmatrix}2&1\\\\5&3\\end{pmatrix}$ and $\\mathbf{b}=\\begin{pmatrix}8\\\\21\\end{pmatrix}$, use Cramer's Rule to find $x_2$ (i.e., $y$).",
    answer: "2",
    explanation: "Step 1: $\\det(A)=6-5=1$. Step 2: $A_2=\\begin{pmatrix}2&8\\\\5&21\\end{pmatrix}$, $\\det(A_2)=42-40=2$. Step 3: $x_2=2/1=2$. Verify: $x=3,y=2$ satisfies both equations. Final answer: $2$." }),
  p({ id: "det-geometric-6", topicId: "determinants", section: "geometric", type: "numeric", difficulty: "hard",
    prompt: "A linear map scales all areas by $3$. If $\\det(A)=-3$, verify: by what factor does it scale volumes in $\\mathbb{R}^2$? (Enter the factor.)",
    answer: "3",
    explanation: "Step 1: The scaling factor for area is $|\\det(A)|=|-3|=3$. Step 2: Areas scale by $3$. Final answer: $3$." }),
  p({ id: "det-cofactor-13", topicId: "determinants", section: "cofactor", type: "numeric", difficulty: "hard",
    prompt: "Find $\\det(A)$ for $A=\\begin{pmatrix}1&0&0&0\\\\2&3&0&0\\\\4&5&6&0\\\\7&8&9&10\\end{pmatrix}$ (lower triangular).",
    answer: "180",
    explanation: "Step 1: Lower triangular: $\\det=$ product of diagonal $=1\\cdot3\\cdot6\\cdot10=180$. Final answer: $180$." }),
];
