import type { Problem } from "../shared-types";

const p = (problem: Problem) => problem;

export const eigenvalueProblems: Problem[] = [
  // --- Easy (14) ---
  p({ id: "eig-characteristic-1", topicId: "eigenvalues", section: "characteristic", type: "numeric", difficulty: "easy",
    prompt: "A $2\\times 2$ matrix has eigenvalues $\\lambda_1=2$ and $\\lambda_2=-3$. What is its trace?",
    answer: "-1",
    explanation: "Step 1: Trace $=$ sum of eigenvalues $=2+(-3)=-1$. Final answer: $-1$." }),
  p({ id: "eig-characteristic-2", topicId: "eigenvalues", section: "characteristic", type: "numeric", difficulty: "easy",
    prompt: "A $2\\times 2$ matrix has eigenvalues $\\lambda_1=3$ and $\\lambda_2=5$. What is its determinant?",
    answer: "15",
    explanation: "Step 1: $\\det(A)=$ product of eigenvalues $=3\\cdot5=15$. Final answer: $15$." }),
  p({ id: "eig-characteristic-3", topicId: "eigenvalues", section: "characteristic", type: "numeric", difficulty: "easy",
    prompt: "Find the larger eigenvalue of $A=\\begin{pmatrix}4&1\\\\0&3\\end{pmatrix}$.",
    answer: "4",
    explanation: "Step 1: $\\det(A-\\lambda I)=(4-\\lambda)(3-\\lambda)=0$. Step 2: $\\lambda=4$ or $\\lambda=3$. Larger: $4$. Final answer: $4$." }),
  p({ id: "eig-eigenvectors-1", topicId: "eigenvalues", section: "eigenvectors", type: "mcq", difficulty: "easy",
    prompt: "If $A\\mathbf{v}=5\\mathbf{v}$ and $\\mathbf{v}\\neq\\mathbf{0}$, then $\\mathbf{v}$ is:",
    answer: "An eigenvector of $A$ with eigenvalue $5$.",
    choices: ["A null vector of $A$.", "An eigenvector of $A$ with eigenvalue $5$.", "A column of $A$ scaled by $5$.", "A unit vector."],
    explanation: "Step 1: $A\\mathbf{v}=\\lambda\\mathbf{v}$ with $\\mathbf{v}\\neq\\mathbf{0}$ defines an eigenvector with eigenvalue $\\lambda=5$. Final answer: An eigenvector of $A$ with eigenvalue $5$." }),
  p({ id: "eig-characteristic-4", topicId: "eigenvalues", section: "characteristic", type: "mcq", difficulty: "easy",
    prompt: "The characteristic polynomial of $A$ is defined as:",
    answer: "$\\det(A-\\lambda I)$",
    choices: ["$\\det(A+\\lambda I)$", "$\\det(A-\\lambda I)$", "$\\text{tr}(A-\\lambda I)$", "$\\det(A)\\cdot\\lambda$"],
    explanation: "Step 1: Setting $\\det(A-\\lambda I)=0$ gives the eigenvalues. Final answer: $\\det(A-\\lambda I)$." }),
  p({ id: "eig-diagonalization-1", topicId: "eigenvalues", section: "diagonalization", type: "mcq", difficulty: "easy",
    prompt: "If $A=PDP^{-1}$, then $A^k=$",
    answer: "$PD^kP^{-1}$",
    choices: ["$P^kD P^{-k}$", "$PD^kP^{-1}$", "$D^k$", "$P^kD^k$"],
    explanation: "Step 1: $A^k=(PDP^{-1})^k=PD^kP^{-1}$ since $P^{-1}P=I$ in the middle. Final answer: $PD^kP^{-1}$." }),
  p({ id: "eig-characteristic-5", topicId: "eigenvalues", section: "characteristic", type: "numeric", difficulty: "easy",
    prompt: "Find the eigenvalues of the diagonal matrix $A=\\begin{pmatrix}7&0\\\\0&-2\\end{pmatrix}$. What is the larger eigenvalue?",
    answer: "7",
    explanation: "Step 1: For a diagonal matrix, the eigenvalues are the diagonal entries. Step 2: $\\lambda_1=7,\\lambda_2=-2$. Larger: $7$. Final answer: $7$." }),
  p({ id: "eig-eigenvectors-2", topicId: "eigenvalues", section: "eigenvectors", type: "mcq", difficulty: "easy",
    prompt: "The set of all eigenvectors for eigenvalue $\\lambda$ (plus $\\mathbf{0}$) forms:",
    answer: "The eigenspace of $\\lambda$.",
    choices: ["The null space of $A$.", "The eigenspace of $\\lambda$.", "The column space of $A$.", "A subspace of dimension 1 only."],
    explanation: "Step 1: The eigenspace $E_\\lambda=\\text{Null}(A-\\lambda I)$, which is a subspace. Final answer: The eigenspace of $\\lambda$." }),
  p({ id: "eig-characteristic-6", topicId: "eigenvalues", section: "characteristic", type: "numeric", difficulty: "easy",
    prompt: "If $\\lambda$ is an eigenvalue of $A$, what is an eigenvalue of $3A$?",
    answer: "3lambda",
    explanation: "Step 1: $(3A)\\mathbf{v}=3A\\mathbf{v}=3\\lambda\\mathbf{v}$. Step 2: Eigenvalue of $3A$ is $3\\lambda$. Final answer: $3\\lambda$." }),
  p({ id: "eig-diagonalization-2", topicId: "eigenvalues", section: "diagonalization", type: "mcq", difficulty: "easy",
    prompt: "A diagonal matrix $D$ has eigenvalues equal to:",
    answer: "Its diagonal entries.",
    choices: ["Its off-diagonal entries.", "Its diagonal entries.", "The square roots of its entries.", "Its trace."],
    explanation: "Step 1: $D\\mathbf{e}_i=d_{ii}\\mathbf{e}_i$, so $d_{ii}$ is an eigenvalue with eigenvector $\\mathbf{e}_i$. Final answer: Its diagonal entries." }),
  p({ id: "eig-characteristic-7", topicId: "eigenvalues", section: "characteristic", type: "numeric", difficulty: "easy",
    prompt: "If $\\lambda$ is an eigenvalue of invertible $A$, then $A^{-1}$ has eigenvalue:",
    answer: "1/lambda",
    explanation: "Step 1: $A\\mathbf{v}=\\lambda\\mathbf{v}\\Rightarrow A^{-1}\\mathbf{v}=\\frac{1}{\\lambda}\\mathbf{v}$. Final answer: $1/\\lambda$." }),
  p({ id: "eig-eigenvectors-3", topicId: "eigenvalues", section: "eigenvectors", type: "mcq", difficulty: "easy",
    prompt: "Eigenvectors for distinct eigenvalues of a matrix are always:",
    answer: "Linearly independent.",
    choices: ["Orthogonal.", "Linearly independent.", "Unit vectors.", "Equal in length."],
    explanation: "Step 1: Eigenvectors corresponding to distinct eigenvalues are linearly independent. Final answer: Linearly independent." }),
  p({ id: "eig-characteristic-8", topicId: "eigenvalues", section: "characteristic", type: "numeric", difficulty: "easy",
    prompt: "If $A$ is $3\\times 3$ with $\\text{tr}(A)=6$, $\\lambda_1=1$, $\\lambda_2=2$, find $\\lambda_3$.",
    answer: "3",
    explanation: "Step 1: $\\text{tr}(A)=\\lambda_1+\\lambda_2+\\lambda_3=6$. Step 2: $1+2+\\lambda_3=6\\Rightarrow\\lambda_3=3$. Final answer: $3$." }),
  p({ id: "eig-diagonalization-3", topicId: "eigenvalues", section: "diagonalization", type: "mcq", difficulty: "easy",
    prompt: "$A$ is diagonalizable if and only if it has:",
    answer: "$n$ linearly independent eigenvectors.",
    choices: ["$n$ distinct eigenvalues.", "$n$ linearly independent eigenvectors.", "All positive eigenvalues.", "A nonzero determinant."],
    explanation: "Step 1: $A=PDP^{-1}$ requires $n$ linearly independent eigenvectors as columns of $P$. Step 2: Distinct eigenvalues suffice but are not necessary. Final answer: $n$ linearly independent eigenvectors." }),

  // --- Medium (16) ---
  p({ id: "eig-characteristic-9", topicId: "eigenvalues", section: "characteristic", type: "numeric", difficulty: "medium",
    prompt: "Find the eigenvalues of $A=\\begin{pmatrix}3&1\\\\1&3\\end{pmatrix}$. What is the larger eigenvalue?",
    answer: "4",
    explanation: "Step 1: $\\det(A-\\lambda I)=(3-\\lambda)^2-1=0$. Step 2: $(3-\\lambda)^2=1\\Rightarrow 3-\\lambda=\\pm1$. Step 3: $\\lambda=4$ or $\\lambda=2$. Larger: $4$. Final answer: $4$." }),
  p({ id: "eig-eigenvectors-4", topicId: "eigenvalues", section: "eigenvectors", type: "numeric", difficulty: "medium",
    prompt: "Find an eigenvector of $A=\\begin{pmatrix}2&1\\\\0&2\\end{pmatrix}$ for eigenvalue $\\lambda=2$. The first component of the eigenvector (from $\\ker(A-2I)$) is:",
    answer: "1",
    explanation: "Step 1: $A-2I=\\begin{pmatrix}0&1\\\\0&0\\end{pmatrix}$. Step 2: Null space: $x_2=0$, $x_1$ free. So $\\mathbf{v}=\\langle 1,0\\rangle$. First component: $1$. Final answer: $1$." }),
  p({ id: "eig-diagonalization-4", topicId: "eigenvalues", section: "diagonalization", type: "numeric", difficulty: "medium",
    prompt: "Compute $A^3$ for diagonal $A=\\begin{pmatrix}2&0\\\\0&3\\end{pmatrix}$. What is the $(2,2)$ entry?",
    answer: "27",
    explanation: "Step 1: $A^3=\\begin{pmatrix}2^3&0\\\\0&3^3\\end{pmatrix}=\\begin{pmatrix}8&0\\\\0&27\\end{pmatrix}$. Step 2: $(A^3)_{22}=27$. Final answer: $27$." }),
  p({ id: "eig-characteristic-10", topicId: "eigenvalues", section: "characteristic", type: "numeric", difficulty: "medium",
    prompt: "Find the characteristic polynomial of $A=\\begin{pmatrix}5&2\\\\4&3\\end{pmatrix}$. The constant term (value at $\\lambda=0$) equals $\\det(A)$. What is it?",
    answer: "7",
    explanation: "Step 1: $\\det(A)=5\\cdot3-2\\cdot4=15-8=7$. This is also the constant term of the characteristic polynomial $\\lambda^2-8\\lambda+7$. Final answer: $7$." }),
  p({ id: "eig-eigenvectors-5", topicId: "eigenvalues", section: "eigenvectors", type: "mcq", difficulty: "medium",
    prompt: "For $A=\\begin{pmatrix}5&2\\\\4&3\\end{pmatrix}$ with eigenvalue $\\lambda=7$, find the eigenvector direction. $(A-7I)\\mathbf{v}=\\mathbf{0}$: first component?",
    answer: "1",
    explanation: "Step 1: $A-7I=\\begin{pmatrix}-2&2\\\\4&-4\\end{pmatrix}$. Step 2: Row reduce: $-2x+2y=0\\Rightarrow x=y$. Step 3: Eigenvector: $\\langle 1,1\\rangle$. First component: $1$. Final answer: $1$." }),
  p({ id: "eig-diagonalization-5", topicId: "eigenvalues", section: "diagonalization", type: "mcq", difficulty: "medium",
    prompt: "A matrix $A$ with eigenvalues $\\lambda_1=3,\\lambda_2=3$ (repeated) is diagonalizable when:",
    answer: "The eigenspace for $\\lambda=3$ has dimension 2.",
    choices: ["Never — repeated eigenvalues prevent diagonalization.", "The eigenspace for $\\lambda=3$ has dimension 2.", "Always — having 2 eigenvalues is sufficient.", "Only if $A$ is symmetric."],
    explanation: "Step 1: A repeated eigenvalue may still give a diagonalizable matrix if its eigenspace has the full algebraic multiplicity. Step 2: Need geometric multiplicity $=$ algebraic multiplicity $=2$. Final answer: The eigenspace for $\\lambda=3$ has dimension 2." }),
  p({ id: "eig-characteristic-11", topicId: "eigenvalues", section: "characteristic", type: "numeric", difficulty: "medium",
    prompt: "If $\\lambda=0$ is an eigenvalue of $A$, what is $\\det(A)$?",
    answer: "0",
    explanation: "Step 1: $\\det(A)=$ product of eigenvalues. Step 2: If one eigenvalue is $0$, then $\\det(A)=0$. Final answer: $0$." }),
  p({ id: "eig-eigenvectors-6", topicId: "eigenvalues", section: "eigenvectors", type: "numeric", difficulty: "medium",
    prompt: "If $\\mathbf{v}$ is an eigenvector of $A$ with eigenvalue $\\lambda$, what is $A^2\\mathbf{v}$? (Express as $\\lambda^2\\mathbf{v}$; enter the power of $\\lambda$.)",
    answer: "2",
    explanation: "Step 1: $A^2\\mathbf{v}=A(A\\mathbf{v})=A(\\lambda\\mathbf{v})=\\lambda A\\mathbf{v}=\\lambda^2\\mathbf{v}$. Step 2: Power is $2$. Final answer: $2$." }),
  p({ id: "eig-diagonalization-6", topicId: "eigenvalues", section: "diagonalization", type: "numeric", difficulty: "medium",
    prompt: "For $A=PDP^{-1}$ with $D=\\begin{pmatrix}2&0\\\\0&5\\end{pmatrix}$, what is the $(2,2)$ entry of $D^4$?",
    answer: "625",
    explanation: "Step 1: $D^4=\\begin{pmatrix}2^4&0\\\\0&5^4\\end{pmatrix}=\\begin{pmatrix}16&0\\\\0&625\\end{pmatrix}$. Step 2: $(D^4)_{22}=625$. Final answer: $625$." }),
  p({ id: "eig-characteristic-12", topicId: "eigenvalues", section: "characteristic", type: "numeric", difficulty: "medium",
    prompt: "Find the eigenvalues of $A=\\begin{pmatrix}0&1\\\\-2&-3\\end{pmatrix}$. What is the smaller eigenvalue?",
    answer: "-2",
    explanation: "Step 1: $\\det(A-\\lambda I)=\\lambda(\\lambda+3)+2=\\lambda^2+3\\lambda+2=(\\lambda+1)(\\lambda+2)=0$. Step 2: $\\lambda=-1$ or $\\lambda=-2$. Smaller: $-2$. Final answer: $-2$." }),
  p({ id: "eig-eigenvectors-7", topicId: "eigenvalues", section: "eigenvectors", type: "mcq", difficulty: "medium",
    prompt: "A scalar $c$ times an eigenvector $\\mathbf{v}$ (with $c\\neq0$) is:",
    answer: "Also an eigenvector for the same eigenvalue.",
    choices: ["A different eigenvector with eigenvalue $c\\lambda$.", "Also an eigenvector for the same eigenvalue.", "No longer an eigenvector.", "An eigenvector for $-\\lambda$."],
    explanation: "Step 1: $A(c\\mathbf{v})=c(A\\mathbf{v})=c\\lambda\\mathbf{v}=\\lambda(c\\mathbf{v})$. Step 2: $c\\mathbf{v}$ is still an eigenvector for $\\lambda$. Final answer: Also an eigenvector for the same eigenvalue." }),
  p({ id: "eig-diagonalization-7", topicId: "eigenvalues", section: "diagonalization", type: "mcq", difficulty: "medium",
    prompt: "The Cayley-Hamilton theorem states that a matrix satisfies:",
    answer: "Its own characteristic equation.",
    choices: ["Its own characteristic equation.", "$A^n=I$.", "$A^2=A$.", "Every polynomial equation."],
    explanation: "Step 1: If $p(\\lambda)=\\det(A-\\lambda I)$, then Cayley-Hamilton says $p(A)=0$. Final answer: Its own characteristic equation." }),
  p({ id: "eig-characteristic-13", topicId: "eigenvalues", section: "characteristic", type: "numeric", difficulty: "medium",
    prompt: "For $A=\\begin{pmatrix}1&2\\\\2&1\\end{pmatrix}$, the eigenvalues are $\\lambda=3$ and $\\lambda=-1$. Find $\\det(A)$.",
    answer: "-3",
    explanation: "Step 1: $\\det(A)=\\lambda_1\\lambda_2=3\\cdot(-1)=-3$. Final answer: $-3$." }),
  p({ id: "eig-eigenvectors-8", topicId: "eigenvalues", section: "eigenvectors", type: "numeric", difficulty: "medium",
    prompt: "The geometric multiplicity of eigenvalue $\\lambda$ is dim(Null$(A-\\lambda I))$. For $A=I_3$, what is the geometric multiplicity of $\\lambda=1$?",
    answer: "3",
    explanation: "Step 1: $A-I=0$. Step 2: Null$(A-I)=\\mathbb{R}^3$, dimension $3$. Final answer: $3$." }),
  p({ id: "eig-diagonalization-8", topicId: "eigenvalues", section: "diagonalization", type: "numeric", difficulty: "medium",
    prompt: "If $A=PDP^{-1}$, what is $A^0$?",
    answer: "1",
    explanation: "Step 1: $A^0=PD^0P^{-1}=PIP^{-1}=I$. Step 2: Any nonsingular matrix to the power 0 is $I$. The $(1,1)$ entry of $I$ is $1$. Final answer: $1$." }),
  p({ id: "eig-characteristic-14", topicId: "eigenvalues", section: "characteristic", type: "mcq", difficulty: "medium",
    prompt: "If $A$ is $n\\times n$ with all eigenvalues equal to $k$, then $\\det(A)=$",
    answer: "$k^n$",
    choices: ["$nk$", "$k^n$", "$k^2$", "$0$"],
    explanation: "Step 1: $\\det(A)=\\lambda_1\\lambda_2\\cdots\\lambda_n=k\\cdot k\\cdots k=k^n$. Final answer: $k^n$." }),

  // --- Hard (10) ---
  p({ id: "eig-characteristic-15", topicId: "eigenvalues", section: "characteristic", type: "numeric", difficulty: "hard",
    prompt: "Find all eigenvalues of $A=\\begin{pmatrix}2&1&0\\\\1&2&1\\\\0&1&2\\end{pmatrix}$. The largest eigenvalue is $2+\\sqrt{2}$. What is $\\sqrt{2}$ to 2 decimal places?",
    answer: "1.41",
    explanation: "Step 1: Characteristic polynomial: $\\det(A-\\lambda I)=-(\\lambda-2)[(\\lambda-2)^2-2]=0$. Step 2: Eigenvalues: $\\lambda=2$ and $\\lambda=2\\pm\\sqrt{2}$. Step 3: $\\sqrt{2}\\approx1.41$. Final answer: $1.41$." }),
  p({ id: "eig-diagonalization-9", topicId: "eigenvalues", section: "diagonalization", type: "numeric", difficulty: "hard",
    prompt: "For $A=\\begin{pmatrix}3&1\\\\0&3\\end{pmatrix}$, is $A$ diagonalizable? $A$ has only one eigenvalue $\\lambda=3$ with geometric multiplicity 1. Enter $0$ for not diagonalizable, $1$ for diagonalizable.",
    answer: "0",
    explanation: "Step 1: Algebraic multiplicity of $\\lambda=3$ is $2$. Step 2: Geometric multiplicity $=\\dim\\text{Null}(A-3I)=\\dim\\text{Null}\\begin{pmatrix}0&1\\\\0&0\\end{pmatrix}=1$. Step 3: Geo $<$ Alg $\\Rightarrow$ not diagonalizable. Final answer: $0$." }),
  p({ id: "eig-eigenvectors-9", topicId: "eigenvalues", section: "eigenvectors", type: "mcq", difficulty: "hard",
    prompt: "If $A\\mathbf{v}=\\lambda\\mathbf{v}$, then $(A-\\mu I)\\mathbf{v}=$",
    answer: "$(\\lambda-\\mu)\\mathbf{v}$",
    choices: ["$(\\lambda\\mu)\\mathbf{v}$", "$(\\lambda-\\mu)\\mathbf{v}$", "$0$", "$(\\mu-\\lambda)\\mathbf{v}$"],
    explanation: "Step 1: $(A-\\mu I)\\mathbf{v}=A\\mathbf{v}-\\mu\\mathbf{v}=\\lambda\\mathbf{v}-\\mu\\mathbf{v}=(\\lambda-\\mu)\\mathbf{v}$. Final answer: $(\\lambda-\\mu)\\mathbf{v}$." }),
  p({ id: "eig-characteristic-16", topicId: "eigenvalues", section: "characteristic", type: "numeric", difficulty: "hard",
    prompt: "For $A=\\begin{pmatrix}0&0&-6\\\\1&0&-11\\\\0&1&-6\\end{pmatrix}$ (companion matrix), the eigenvalues are the roots of $\\lambda^3+6\\lambda^2+11\\lambda+6=0$. The smallest root is:",
    answer: "-3",
    explanation: "Step 1: $\\lambda^3+6\\lambda^2+11\\lambda+6=(\\lambda+1)(\\lambda+2)(\\lambda+3)=0$. Step 2: Roots: $-1,-2,-3$. Smallest: $-3$. Final answer: $-3$." }),
  p({ id: "eig-diagonalization-10", topicId: "eigenvalues", section: "diagonalization", type: "mcq", difficulty: "hard",
    prompt: "Every real symmetric matrix is diagonalizable via an orthogonal matrix $Q$: $A=Q\\Lambda Q^T$. This is called:",
    answer: "The Spectral Decomposition (Real Spectral Theorem).",
    choices: ["LU decomposition.", "The Spectral Decomposition (Real Spectral Theorem).", "QR decomposition.", "Cholesky decomposition."],
    explanation: "Step 1: The Real Spectral Theorem: every real symmetric matrix has real eigenvalues and orthonormal eigenvectors. Step 2: $A=Q\\Lambda Q^T$ is the spectral decomposition. Final answer: The Spectral Decomposition (Real Spectral Theorem)." }),
  p({ id: "eig-eigenvectors-10", topicId: "eigenvalues", section: "eigenvectors", type: "numeric", difficulty: "hard",
    prompt: "If $A$ is $3\\times 3$ with eigenvalues $2,3,4$, what is $\\det(A+I)$?",
    answer: "60",
    explanation: "Step 1: Eigenvalues of $A+I$ are $2+1,3+1,4+1=3,4,5$. Step 2: $\\det(A+I)=3\\cdot4\\cdot5=60$. Final answer: $60$." }),
  p({ id: "eig-characteristic-17", topicId: "eigenvalues", section: "characteristic", type: "numeric", difficulty: "hard",
    prompt: "Apply the Cayley-Hamilton theorem: $A=\\begin{pmatrix}3&1\\\\2&4\\end{pmatrix}$. The characteristic polynomial is $\\lambda^2-7\\lambda+10$. Verify $A^2-7A+10I=0$. What is the $(1,1)$ entry of $A^2-7A+10I$?",
    answer: "0",
    explanation: "Step 1: $A^2=\\begin{pmatrix}11&7\\\\14&18\\end{pmatrix}$. Step 2: $7A=\\begin{pmatrix}21&7\\\\14&28\\end{pmatrix}$. Step 3: $10I=\\begin{pmatrix}10&0\\\\0&10\\end{pmatrix}$. Step 4: $(1,1): 11-21+10=0$. Final answer: $0$." }),
  p({ id: "eig-diagonalization-11", topicId: "eigenvalues", section: "diagonalization", type: "numeric", difficulty: "hard",
    prompt: "If $A=PDP^{-1}$ with $D=\\begin{pmatrix}2&0\\\\0&-1\\end{pmatrix}$, compute $A^{10}$: what is the $(1,1)$ entry of $D^{10}$?",
    answer: "1024",
    explanation: "Step 1: $D^{10}=\\begin{pmatrix}2^{10}&0\\\\0&(-1)^{10}\\end{pmatrix}=\\begin{pmatrix}1024&0\\\\0&1\\end{pmatrix}$. Step 2: $(D^{10})_{11}=1024$. Final answer: $1024$." }),
  p({ id: "eig-eigenvectors-11", topicId: "eigenvalues", section: "eigenvectors", type: "mcq", difficulty: "hard",
    prompt: "The dimension of the eigenspace $E_\\lambda = \\text{Null}(A-\\lambda I)$ is called the:",
    answer: "Geometric multiplicity of $\\lambda$.",
    choices: ["Algebraic multiplicity.", "Geometric multiplicity of $\\lambda$.", "Rank of $A$.", "Nullity of $A$."],
    explanation: "Step 1: Geometric multiplicity $=\\dim(E_\\lambda)=\\dim\\text{Null}(A-\\lambda I)$. Final answer: Geometric multiplicity of $\\lambda$." }),
  p({ id: "eig-characteristic-18", topicId: "eigenvalues", section: "characteristic", type: "numeric", difficulty: "hard",
    prompt: "If $A$ is similar to $B$ ($A=PBP^{-1}$), what is true about their eigenvalues?",
    answer: "1",
    explanation: "Step 1: Similar matrices have the same characteristic polynomial, hence the same eigenvalues. Enter $1$ for same, $0$ for different. Final answer: $1$ (same eigenvalues)." }),
];
