import type { Problem } from "../shared-types";

const p = (problem: Problem) => problem;

export const orthogonalityProblems: Problem[] = [
  // --- Easy (14) ---
  p({ id: "orth-orthogonal-sets-1", topicId: "orthogonality", section: "orthogonal-sets", type: "mcq", difficulty: "easy",
    prompt: "An orthogonal set of nonzero vectors is always:",
    answer: "Linearly independent.",
    choices: ["Linearly independent.", "Linearly dependent.", "A basis for $\\mathbb{R}^n$.", "Orthonormal."],
    explanation: "Step 1: An orthogonal set of nonzero vectors is always linearly independent. Step 2: It need not be orthonormal or a full basis. Final answer: Linearly independent." }),
  p({ id: "orth-orthogonal-sets-2", topicId: "orthogonality", section: "orthogonal-sets", type: "mcq", difficulty: "easy",
    prompt: "A set is orthonormal if its vectors are:",
    answer: "Mutually orthogonal and each has unit length.",
    choices: ["Mutually orthogonal only.", "Each of unit length only.", "Mutually orthogonal and each has unit length.", "Parallel and unit length."],
    explanation: "Step 1: Orthonormal $=$ orthogonal $+$ normalized (unit length). Final answer: Mutually orthogonal and each has unit length." }),
  p({ id: "orth-projection-1", topicId: "orthogonality", section: "projection", type: "numeric", difficulty: "easy",
    prompt: "Find the scalar projection of $\\mathbf{u}=\\langle 3,4\\rangle$ onto $\\mathbf{v}=\\langle 1,0\\rangle$.",
    answer: "3",
    explanation: "Step 1: $\\text{comp}_{\\mathbf{v}}\\mathbf{u}=\\frac{\\mathbf{u}\\cdot\\mathbf{v}}{\\|\\mathbf{v}\\|}=\\frac{3}{1}=3$. Final answer: $3$." }),
  p({ id: "orth-projection-2", topicId: "orthogonality", section: "projection", type: "numeric", difficulty: "easy",
    prompt: "Find the first component of $\\text{proj}_{\\mathbf{v}}\\mathbf{u}$ where $\\mathbf{u}=\\langle 5,0\\rangle$ and $\\mathbf{v}=\\langle 1,0\\rangle$.",
    answer: "5",
    explanation: "Step 1: $\\text{proj}=\\frac{5}{1}\\langle 1,0\\rangle=\\langle 5,0\\rangle$. First component: $5$. Final answer: $5$." }),
  p({ id: "orth-least-squares-1", topicId: "orthogonality", section: "least-squares", type: "mcq", difficulty: "easy",
    prompt: "The least-squares solution $\\hat{\\mathbf{x}}$ to $A\\mathbf{x}=\\mathbf{b}$ minimizes:",
    answer: "$\\|A\\mathbf{x}-\\mathbf{b}\\|^2$",
    choices: ["$\\|A\\mathbf{x}\\|^2$", "$\\|A\\mathbf{x}-\\mathbf{b}\\|^2$", "$\\|\\mathbf{b}\\|^2$", "$\\det(A)$"],
    explanation: "Step 1: Least-squares minimizes the squared residual $\\|A\\mathbf{x}-\\mathbf{b}\\|^2$. Final answer: $\\|A\\mathbf{x}-\\mathbf{b}\\|^2$." }),
  p({ id: "orth-gram-schmidt-1", topicId: "orthogonality", section: "gram-schmidt", type: "mcq", difficulty: "easy",
    prompt: "The Gram-Schmidt process takes a linearly independent set and produces:",
    answer: "An orthogonal (or orthonormal) set with the same span.",
    choices: ["A larger spanning set.", "An orthogonal (or orthonormal) set with the same span.", "A set of eigenvectors.", "A diagonal matrix."],
    explanation: "Step 1: Gram-Schmidt orthogonalizes a basis while preserving the span. Final answer: An orthogonal (or orthonormal) set with the same span." }),
  p({ id: "orth-orthogonal-sets-3", topicId: "orthogonality", section: "orthogonal-sets", type: "numeric", difficulty: "easy",
    prompt: "Are $\\mathbf{v}_1=\\langle 1,0\\rangle$ and $\\mathbf{v}_2=\\langle 0,1\\rangle$ orthogonal? Enter $1$ for yes, $0$ for no.",
    answer: "1",
    explanation: "Step 1: $\\mathbf{v}_1\\cdot\\mathbf{v}_2=0$. Step 2: Yes, orthogonal. Final answer: $1$." }),
  p({ id: "orth-projection-3", topicId: "orthogonality", section: "projection", type: "numeric", difficulty: "easy",
    prompt: "The orthogonal projection of $\\mathbf{b}=\\langle 3,4\\rangle$ onto the $x$-axis gives the vector $\\langle c,0\\rangle$. What is $c$?",
    answer: "3",
    explanation: "Step 1: Project onto $\\mathbf{e}_1=\\langle 1,0\\rangle$: $c=\\mathbf{b}\\cdot\\mathbf{e}_1=3$. Final answer: $3$." }),
  p({ id: "orth-least-squares-2", topicId: "orthogonality", section: "least-squares", type: "mcq", difficulty: "easy",
    prompt: "The normal equations for the least-squares solution are:",
    answer: "$A^TA\\hat{\\mathbf{x}}=A^T\\mathbf{b}$",
    choices: ["$AA^T\\hat{\\mathbf{x}}=\\mathbf{b}$", "$A^TA\\hat{\\mathbf{x}}=A^T\\mathbf{b}$", "$A\\hat{\\mathbf{x}}=\\mathbf{b}$", "$A^T\\hat{\\mathbf{x}}=\\mathbf{b}$"],
    explanation: "Step 1: The normal equations $A^TA\\hat{\\mathbf{x}}=A^T\\mathbf{b}$ always have a solution and give the least-squares solution. Final answer: $A^TA\\hat{\\mathbf{x}}=A^T\\mathbf{b}$." }),
  p({ id: "orth-gram-schmidt-2", topicId: "orthogonality", section: "gram-schmidt", type: "numeric", difficulty: "easy",
    prompt: "Apply Gram-Schmidt: let $\\mathbf{v}_1=\\langle 3,4\\rangle$. The normalized $\\mathbf{e}_1=\\mathbf{v}_1/\\|\\mathbf{v}_1\\|$ has first component:",
    answer: "0.6",
    explanation: "Step 1: $\\|\\mathbf{v}_1\\|=5$. Step 2: $\\mathbf{e}_1=\\langle 3/5,4/5\\rangle=\\langle 0.6,0.8\\rangle$. First component: $0.6$. Final answer: $0.6$." }),
  p({ id: "orth-orthogonal-sets-4", topicId: "orthogonality", section: "orthogonal-sets", type: "mcq", difficulty: "easy",
    prompt: "An orthogonal matrix $Q$ satisfies $Q^{-1}=$",
    answer: "$Q^T$",
    choices: ["$Q$", "$Q^T$", "$-Q$", "$Q^2$"],
    explanation: "Step 1: For an orthogonal matrix, $Q^TQ=I$, so $Q^{-1}=Q^T$. Final answer: $Q^T$." }),
  p({ id: "orth-projection-4", topicId: "orthogonality", section: "projection", type: "numeric", difficulty: "easy",
    prompt: "The projection matrix onto the line spanned by $\\hat{\\mathbf{u}}=\\langle 1,0\\rangle$ is $P=\\hat{\\mathbf{u}}\\hat{\\mathbf{u}}^T$. What is $P_{11}$?",
    answer: "1",
    explanation: "Step 1: $P=\\langle 1,0\\rangle\\langle 1,0\\rangle^T=\\begin{pmatrix}1&0\\\\0&0\\end{pmatrix}$. Step 2: $P_{11}=1$. Final answer: $1$." }),
  p({ id: "orth-least-squares-3", topicId: "orthogonality", section: "least-squares", type: "mcq", difficulty: "easy",
    prompt: "If $A\\mathbf{x}=\\mathbf{b}$ is inconsistent, the least-squares solution gives the $\\hat{\\mathbf{x}}$ for which $A\\hat{\\mathbf{x}}$ is:",
    answer: "The closest point in Col$(A)$ to $\\mathbf{b}$.",
    choices: ["Equal to $\\mathbf{b}$.", "The closest point in Col$(A)$ to $\\mathbf{b}$.", "Zero.", "Perpendicular to $\\mathbf{b}$."],
    explanation: "Step 1: Least squares projects $\\mathbf{b}$ onto Col$(A)$, giving the closest approximation. Final answer: The closest point in Col$(A)$ to $\\mathbf{b}$." }),
  p({ id: "orth-gram-schmidt-3", topicId: "orthogonality", section: "gram-schmidt", type: "mcq", difficulty: "easy",
    prompt: "QR factorization decomposes $A$ into $Q$ (orthogonal) and $R$ where $R$ is:",
    answer: "Upper triangular.",
    choices: ["Lower triangular.", "Diagonal.", "Upper triangular.", "Symmetric."],
    explanation: "Step 1: Gram-Schmidt orthogonalization produces $A=QR$ where $Q$ has orthonormal columns and $R$ is upper triangular. Final answer: Upper triangular." }),

  // --- Medium (16) ---
  p({ id: "orth-gram-schmidt-4", topicId: "orthogonality", section: "gram-schmidt", type: "numeric", difficulty: "medium",
    prompt: "Apply Gram-Schmidt to $\\mathbf{v}_1=\\langle 1,1\\rangle$, $\\mathbf{v}_2=\\langle 1,0\\rangle$. After orthogonalizing, $\\mathbf{u}_2=\\mathbf{v}_2-\\text{proj}_{\\mathbf{u}_1}\\mathbf{v}_2$ where $\\mathbf{u}_1=\\mathbf{v}_1$. What is the second component of $\\mathbf{u}_2$?",
    answer: "-0.5",
    explanation: "Step 1: $\\text{proj}_{\\mathbf{u}_1}\\mathbf{v}_2=\\frac{1\\cdot1+1\\cdot0}{1^2+1^2}\\langle 1,1\\rangle=\\frac{1}{2}\\langle 1,1\\rangle=\\langle 0.5,0.5\\rangle$. Step 2: $\\mathbf{u}_2=\\langle 1-0.5,0-0.5\\rangle=\\langle 0.5,-0.5\\rangle$. Second component: $-0.5$. Final answer: $-0.5$." }),
  p({ id: "orth-projection-5", topicId: "orthogonality", section: "projection", type: "numeric", difficulty: "medium",
    prompt: "Find the projection of $\\mathbf{b}=\\langle 4,2\\rangle$ onto the subspace spanned by $\\mathbf{u}=\\langle 2,1\\rangle$. What is the first component?",
    answer: "4",
    explanation: "Step 1: $\\text{proj}=\\frac{\\mathbf{b}\\cdot\\mathbf{u}}{\\mathbf{u}\\cdot\\mathbf{u}}\\mathbf{u}=\\frac{10}{5}\\langle 2,1\\rangle=2\\langle 2,1\\rangle=\\langle 4,2\\rangle$. First component: $4$. Final answer: $4$." }),
  p({ id: "orth-least-squares-4", topicId: "orthogonality", section: "least-squares", type: "numeric", difficulty: "medium",
    prompt: "Fit the best-fit line $y=\\beta_0+\\beta_1 x$ through $(1,1),(2,2),(3,4)$ using least squares. Set up $A\\boldsymbol{\\beta}=\\mathbf{b}$: $A^TA\\hat{\\boldsymbol{\\beta}}=A^T\\mathbf{b}$. The $(1,1)$ entry of $A^TA$ is:",
    answer: "3",
    explanation: "Step 1: $A=\\begin{pmatrix}1&1\\\\1&2\\\\1&3\\end{pmatrix}$. Step 2: $A^TA=\\begin{pmatrix}1+1+1&1+2+3\\\\1+2+3&1+4+9\\end{pmatrix}=\\begin{pmatrix}3&6\\\\6&14\\end{pmatrix}$. Step 3: $(1,1)$ entry $=3$. Final answer: $3$." }),
  p({ id: "orth-orthogonal-sets-5", topicId: "orthogonality", section: "orthogonal-sets", type: "numeric", difficulty: "medium",
    prompt: "The set $\\left\\{\\frac{1}{\\sqrt{2}}\\langle 1,1\\rangle, \\frac{1}{\\sqrt{2}}\\langle 1,-1\\rangle\\right\\}$ is orthonormal. What is their dot product?",
    answer: "0",
    explanation: "Step 1: $(\\frac{1}{\\sqrt{2}})(\\frac{1}{\\sqrt{2}})+(\\frac{1}{\\sqrt{2}})(-\\frac{1}{\\sqrt{2}})=\\frac{1}{2}-\\frac{1}{2}=0$. Step 2: Dot product $=0$. Final answer: $0$." }),
  p({ id: "orth-projection-6", topicId: "orthogonality", section: "projection", type: "mcq", difficulty: "medium",
    prompt: "The projection matrix $P=A(A^TA)^{-1}A^T$ satisfies $P^2=$",
    answer: "$P$",
    choices: ["$I$", "$P$", "$P^T$", "$P^{-1}$"],
    explanation: "Step 1: Projection matrices are idempotent: $P^2=P$. Step 2: Applying the projection twice gives the same result. Final answer: $P$." }),
  p({ id: "orth-least-squares-5", topicId: "orthogonality", section: "least-squares", type: "numeric", difficulty: "medium",
    prompt: "For least-squares fit of $y=\\beta x$ (no intercept) through $(1,2),(2,3),(3,5)$: $\\hat{\\beta}=\\frac{\\sum x_iy_i}{\\sum x_i^2}$. Compute $\\hat{\\beta}$.",
    answer: "23/14",
    explanation: "Step 1: $\\sum x_iy_i=1\\cdot2+2\\cdot3+3\\cdot5=2+6+15=23$. Step 2: $\\sum x_i^2=1+4+9=14$. Step 3: $\\hat{\\beta}=23/14$. Final answer: $23/14$." }),
  p({ id: "orth-gram-schmidt-5", topicId: "orthogonality", section: "gram-schmidt", type: "mcq", difficulty: "medium",
    prompt: "After Gram-Schmidt, the resulting orthonormal vectors $\\mathbf{q}_1,\\ldots,\\mathbf{q}_k$ form the columns of $Q$ in $A=QR$. What are the columns of $Q$?",
    answer: "Orthonormal vectors spanning the same space as the columns of $A$.",
    choices: ["The eigenvectors of $A$.", "Orthonormal vectors spanning the same space as the columns of $A$.", "The rows of $A$ normalized.", "The singular vectors of $A$."],
    explanation: "Step 1: Gram-Schmidt orthonormalizes the column space. The $Q$ matrix has orthonormal columns spanning Col$(A)$. Final answer: Orthonormal vectors spanning the same space as the columns of $A$." }),
  p({ id: "orth-projection-7", topicId: "orthogonality", section: "projection", type: "numeric", difficulty: "medium",
    prompt: "The residual $\\mathbf{r}=\\mathbf{b}-A\\hat{\\mathbf{x}}$ in least squares is perpendicular to Col$(A)$. Verify: $\\mathbf{r}\\cdot\\mathbf{a}=0$ for every column $\\mathbf{a}$ of $A$. This is equivalent to: $A^T\\mathbf{r}=$",
    answer: "0",
    explanation: "Step 1: The condition $A^T\\mathbf{r}=\\mathbf{0}$ means the residual is orthogonal to every column of $A$. This is the normal equation condition. Final answer: $0$." }),
  p({ id: "orth-orthogonal-sets-6", topicId: "orthogonality", section: "orthogonal-sets", type: "numeric", difficulty: "medium",
    prompt: "If $Q$ is a $3\\times 3$ orthogonal matrix, what is $|\\det(Q)|$?",
    answer: "1",
    explanation: "Step 1: $Q^TQ=I \\Rightarrow \\det(Q^T)\\det(Q)=1 \\Rightarrow \\det(Q)^2=1$. Step 2: $|\\det(Q)|=1$. Final answer: $1$." }),
  p({ id: "orth-least-squares-6", topicId: "orthogonality", section: "least-squares", type: "mcq", difficulty: "medium",
    prompt: "The least-squares residual $\\|\\mathbf{b}-A\\hat{\\mathbf{x}}\\|$ is minimized when $A\\hat{\\mathbf{x}}$ equals:",
    answer: "The orthogonal projection of $\\mathbf{b}$ onto Col$(A)$.",
    choices: ["$\\mathbf{b}$.", "The zero vector.", "The orthogonal projection of $\\mathbf{b}$ onto Col$(A)$.", "$A^T\\mathbf{b}$."],
    explanation: "Step 1: The minimum distance from $\\mathbf{b}$ to Col$(A)$ is achieved by the orthogonal projection of $\\mathbf{b}$ onto Col$(A)$. Final answer: The orthogonal projection of $\\mathbf{b}$ onto Col$(A)$." }),
  p({ id: "orth-gram-schmidt-6", topicId: "orthogonality", section: "gram-schmidt", type: "numeric", difficulty: "medium",
    prompt: "Starting with $\\mathbf{v}_1=\\langle 1,0,0\\rangle$ and $\\mathbf{v}_2=\\langle 1,1,0\\rangle$, what is the second component of $\\mathbf{u}_2 = \\mathbf{v}_2 - \\text{proj}_{\\mathbf{v}_1}\\mathbf{v}_2$?",
    answer: "1",
    explanation: "Step 1: $\\text{proj}_{\\mathbf{v}_1}\\mathbf{v}_2=\\langle 1,0,0\\rangle$. Step 2: $\\mathbf{u}_2=\\langle 1,1,0\\rangle-\\langle 1,0,0\\rangle=\\langle 0,1,0\\rangle$. Second component: $1$. Final answer: $1$." }),
  p({ id: "orth-projection-8", topicId: "orthogonality", section: "projection", type: "numeric", difficulty: "medium",
    prompt: "Compute the projection matrix $P=\\mathbf{u}\\mathbf{u}^T$ for the unit vector $\\mathbf{u}=\\langle 1/\\sqrt{2},1/\\sqrt{2}\\rangle$. What is $P_{12}$?",
    answer: "0.5",
    explanation: "Step 1: $P=\\begin{pmatrix}1/2&1/2\\\\1/2&1/2\\end{pmatrix}$. Step 2: $P_{12}=1/2=0.5$. Final answer: $0.5$." }),
  p({ id: "orth-orthogonal-sets-7", topicId: "orthogonality", section: "orthogonal-sets", type: "mcq", difficulty: "medium",
    prompt: "If $Q$ is orthogonal, then $\\|Q\\mathbf{x}\\|=$",
    answer: "$\\|\\mathbf{x}\\|$",
    choices: ["$0$", "$\\|\\mathbf{x}\\|$", "$\\|\\mathbf{x}\\|^2$", "$2\\|\\mathbf{x}\\|$"],
    explanation: "Step 1: $\\|Q\\mathbf{x}\\|^2=(Q\\mathbf{x})^T(Q\\mathbf{x})=\\mathbf{x}^TQ^TQ\\mathbf{x}=\\mathbf{x}^T\\mathbf{x}=\\|\\mathbf{x}\\|^2$. Step 2: Orthogonal matrices preserve norms. Final answer: $\\|\\mathbf{x}\\|$." }),
  p({ id: "orth-least-squares-7", topicId: "orthogonality", section: "least-squares", type: "numeric", difficulty: "medium",
    prompt: "Fit a line $y=\\beta x$ (no intercept) to data $(2,4),(4,5)$ via least squares. Find $\\hat{\\beta}=\\frac{\\sum x_iy_i}{\\sum x_i^2}$.",
    answer: "1.4",
    explanation: "Step 1: $\\sum x_iy_i=2\\cdot4+4\\cdot5=8+20=28$. Step 2: $\\sum x_i^2=4+16=20$. Step 3: $\\hat{\\beta}=28/20=1.4$. Final answer: $1.4$." }),
  p({ id: "orth-projection-9", topicId: "orthogonality", section: "projection", type: "mcq", difficulty: "medium",
    prompt: "The complement of the projection: $\\mathbf{b} - \\text{proj}_W \\mathbf{b}$ is always:",
    answer: "Orthogonal to $W$.",
    choices: ["Parallel to $W$.", "Orthogonal to $W$.", "In $W$.", "Equal to $\\mathbf{b}$."],
    explanation: "Step 1: By definition, $\\mathbf{b}-\\text{proj}_W\\mathbf{b}$ is the component of $\\mathbf{b}$ orthogonal to $W$. Final answer: Orthogonal to $W$." }),

  // --- Hard (10) ---
  p({ id: "orth-gram-schmidt-7", topicId: "orthogonality", section: "gram-schmidt", type: "numeric", difficulty: "hard",
    prompt: "Apply Gram-Schmidt to $\\mathbf{v}_1=\\langle 1,1,1\\rangle$, $\\mathbf{v}_2=\\langle 1,1,0\\rangle$. The orthogonalized $\\mathbf{u}_2 = \\mathbf{v}_2 - \\frac{\\mathbf{v}_2\\cdot\\mathbf{u}_1}{\\mathbf{u}_1\\cdot\\mathbf{u}_1}\\mathbf{u}_1$, where $\\mathbf{u}_1=\\mathbf{v}_1$. What is the third component of $\\mathbf{u}_2$?",
    answer: "-2/3",
    explanation: "Step 1: $\\mathbf{u}_1\\cdot\\mathbf{u}_1=3$. Step 2: $\\mathbf{v}_2\\cdot\\mathbf{u}_1=1+1+0=2$. Step 3: $\\mathbf{u}_2=\\langle 1,1,0\\rangle-\\frac{2}{3}\\langle 1,1,1\\rangle=\\langle 1/3,1/3,-2/3\\rangle$. Third component: $-2/3$. Final answer: $-2/3$." }),
  p({ id: "orth-least-squares-8", topicId: "orthogonality", section: "least-squares", type: "numeric", difficulty: "hard",
    prompt: "Normal equations: $A^TA=\\begin{pmatrix}3&6\\\\6&14\\end{pmatrix}$ and $A^T\\mathbf{b}=\\begin{pmatrix}7\\\\16\\end{pmatrix}$. Find $\\hat{\\beta}_0$ (first component of $\\hat{\\boldsymbol{\\beta}}$).",
    answer: "1/3",
    explanation: "Step 1: Solve $\\begin{pmatrix}3&6\\\\6&14\\end{pmatrix}\\hat{\\boldsymbol{\\beta}}=\\begin{pmatrix}7\\\\16\\end{pmatrix}$. Step 2: $\\det(A^TA)=42-36=6$. Step 3: $\\hat{\\beta}_0=\\frac{1}{6}(14\\cdot7-6\\cdot16)=\\frac{98-96}{6}=\\frac{2}{6}=1/3$. Final answer: $1/3$." }),
  p({ id: "orth-projection-10", topicId: "orthogonality", section: "projection", type: "numeric", difficulty: "hard",
    prompt: "Project $\\mathbf{b}=\\langle 1,1,0\\rangle$ onto the plane $x+y+z=0$ (normal $\\mathbf{n}=\\langle 1,1,1\\rangle$). What is the first component of the result?",
    answer: "1/3",
    explanation: "Step 1: Normal component: $\\frac{\\mathbf{b}\\cdot\\mathbf{n}}{\\|\\mathbf{n}\\|^2}\\mathbf{n}=\\frac{2}{3}\\langle 1,1,1\\rangle=\\langle 2/3,2/3,2/3\\rangle$. Step 2: Plane projection $=\\mathbf{b}-\\text{normal}=\\langle 1-2/3,1-2/3,0-2/3\\rangle=\\langle 1/3,1/3,-2/3\\rangle$. First component: $1/3$. Final answer: $1/3$." }),
  p({ id: "orth-orthogonal-sets-8", topicId: "orthogonality", section: "orthogonal-sets", type: "mcq", difficulty: "hard",
    prompt: "If $Q$ is an orthogonal matrix, which is true?",
    answer: "All eigenvalues of $Q$ have absolute value 1.",
    choices: ["All eigenvalues are real and positive.", "All eigenvalues have absolute value 1.", "All eigenvalues are $0$ or $1$.", "$Q$ must be symmetric."],
    explanation: "Step 1: Orthogonal matrices preserve norms: $\\|Q\\mathbf{x}\\|=\\|\\mathbf{x}\\|$. Step 2: If $Q\\mathbf{v}=\\lambda\\mathbf{v}$, then $|\\lambda|\\|\\mathbf{v}\\|=\\|\\mathbf{v}\\|$, so $|\\lambda|=1$. Final answer: All eigenvalues of $Q$ have absolute value 1." }),
  p({ id: "orth-gram-schmidt-8", topicId: "orthogonality", section: "gram-schmidt", type: "numeric", difficulty: "hard",
    prompt: "QR factorization: $A=\\begin{pmatrix}1&1\\\\1&0\\\\0&1\\end{pmatrix}$. After Gram-Schmidt, $R_{11}=\\|\\mathbf{v}_1\\|$ where $\\mathbf{v}_1=$ column 1 of $A$. Find $R_{11}$.",
    answer: "sqrt(2)",
    explanation: "Step 1: $\\mathbf{v}_1=\\langle 1,1,0\\rangle$. Step 2: $R_{11}=\\|\\mathbf{v}_1\\|=\\sqrt{2}$. Final answer: $\\sqrt{2}$." }),
  p({ id: "orth-least-squares-9", topicId: "orthogonality", section: "least-squares", type: "mcq", difficulty: "hard",
    prompt: "If $A$ has linearly independent columns, then $A^TA$ is:",
    answer: "Invertible (positive definite).",
    choices: ["Singular.", "Invertible (positive definite).", "Skew-symmetric.", "Zero."],
    explanation: "Step 1: If columns of $A$ are linearly independent, then $A^TA$ is symmetric positive definite, hence invertible. Step 2: The unique least-squares solution is $\\hat{\\mathbf{x}}=(A^TA)^{-1}A^T\\mathbf{b}$. Final answer: Invertible (positive definite)." }),
  p({ id: "orth-projection-11", topicId: "orthogonality", section: "projection", type: "numeric", difficulty: "hard",
    prompt: "The projection matrix $P=A(A^TA)^{-1}A^T$ for $A=\\begin{pmatrix}1\\\\1\\\\1\\end{pmatrix}$. Find $P_{11}$.",
    answer: "1/3",
    explanation: "Step 1: $A^TA=3$, $(A^TA)^{-1}=1/3$. Step 2: $P=\\frac{1}{3}\\begin{pmatrix}1\\\\1\\\\1\\end{pmatrix}\\begin{pmatrix}1&1&1\\end{pmatrix}=\\frac{1}{3}J$ where $J$ is the all-ones matrix. Step 3: $P_{11}=1/3$. Final answer: $1/3$." }),
  p({ id: "orth-gram-schmidt-9", topicId: "orthogonality", section: "gram-schmidt", type: "mcq", difficulty: "hard",
    prompt: "The QR decomposition is used to solve least-squares problems because:",
    answer: "It is numerically stable and avoids forming $A^TA$.",
    choices: ["It makes $A$ diagonal.", "It is numerically stable and avoids forming $A^TA$.", "It only works for square $A$.", "It always gives the exact solution."],
    explanation: "Step 1: Computing $A^TA$ can cause numerical instability (condition number squares). Step 2: QR decomposition gives a more stable way to solve normal equations. Final answer: It is numerically stable and avoids forming $A^TA$." }),
  p({ id: "orth-orthogonal-sets-9", topicId: "orthogonality", section: "orthogonal-sets", type: "numeric", difficulty: "hard",
    prompt: "Express $\\mathbf{b}=\\langle 5,3\\rangle$ in the orthonormal basis $\\{\\mathbf{q}_1=\\langle 1,0\\rangle,\\mathbf{q}_2=\\langle 0,1\\rangle\\}$. What is the coefficient of $\\mathbf{q}_1$?",
    answer: "5",
    explanation: "Step 1: Coefficient of $\\mathbf{q}_1=\\mathbf{b}\\cdot\\mathbf{q}_1=5$. Final answer: $5$." }),
  p({ id: "orth-least-squares-10", topicId: "orthogonality", section: "least-squares", type: "numeric", difficulty: "hard",
    prompt: "For data $(0,1),(1,3),(2,4),(3,6)$ and slope formula $b=\\frac{n\\sum x_iy_i-\\sum x_i\\sum y_i}{n\\sum x_i^2-(\\sum x_i)^2}$ with $n=4$, $\\sum x_i=6$, $\\sum y_i=14$, $\\sum x_iy_i=26$, $\\sum x_i^2=14$: find $b$.",
    answer: "1",
    explanation: "Step 1: Numerator: $4(26)-6(14)=104-84=20$. Step 2: Denominator: $4(14)-6^2=56-36=20$. Step 3: $b=20/20=1$. Final answer: $1$." }),
];
