import type { Problem } from "../shared-types";

const p = (problem: Problem) => problem;

export const symmetricMatrixProblems: Problem[] = [
  // --- Easy (14) ---
  p({ id: "sym-spectral-1", topicId: "symmetric-matrices", section: "spectral", type: "mcq", difficulty: "easy",
    prompt: "All eigenvalues of a real symmetric matrix are:",
    answer: "Real.",
    choices: ["Real.", "Positive.", "Distinct.", "Equal to 1."],
    explanation: "Step 1: The Real Spectral Theorem guarantees real eigenvalues for symmetric matrices. Final answer: Real." }),
  p({ id: "sym-spectral-2", topicId: "symmetric-matrices", section: "spectral", type: "mcq", difficulty: "easy",
    prompt: "Eigenvectors of a real symmetric matrix corresponding to distinct eigenvalues are:",
    answer: "Orthogonal.",
    choices: ["Parallel.", "Orthogonal.", "Equal.", "Collinear."],
    explanation: "Step 1: For symmetric $A$, if $\\lambda_1\\neq\\lambda_2$, then $A\\mathbf{v}_1=\\lambda_1\\mathbf{v}_1$ and $A\\mathbf{v}_2=\\lambda_2\\mathbf{v}_2$ implies $\\mathbf{v}_1\\cdot\\mathbf{v}_2=0$. Final answer: Orthogonal." }),
  p({ id: "sym-quadratic-forms-1", topicId: "symmetric-matrices", section: "quadratic-forms", type: "mcq", difficulty: "easy",
    prompt: "A quadratic form $Q(\\mathbf{x})=\\mathbf{x}^TA\\mathbf{x}$ is positive definite if:",
    answer: "All eigenvalues of $A$ are positive.",
    choices: ["$\\det(A)>0$.", "All eigenvalues of $A$ are positive.", "$A$ is invertible.", "All entries of $A$ are positive."],
    explanation: "Step 1: $Q$ is positive definite iff $Q(\\mathbf{x})>0$ for all $\\mathbf{x}\\neq\\mathbf{0}$, which happens iff all eigenvalues of $A$ are positive. Final answer: All eigenvalues of $A$ are positive." }),
  p({ id: "sym-svd-1", topicId: "symmetric-matrices", section: "svd", type: "mcq", difficulty: "easy",
    prompt: "In the SVD $A=U\\Sigma V^T$, the singular values in $\\Sigma$ are:",
    answer: "The square roots of the eigenvalues of $A^TA$.",
    choices: ["The eigenvalues of $A$.", "The square roots of the eigenvalues of $A^TA$.", "The diagonal entries of $A$.", "The columns of $U$."],
    explanation: "Step 1: Singular values $\\sigma_i=\\sqrt{\\lambda_i}$ where $\\lambda_i$ are eigenvalues of $A^TA$ (always $\\geq0$). Final answer: The square roots of the eigenvalues of $A^TA$." }),
  p({ id: "sym-positive-definite-1", topicId: "symmetric-matrices", section: "positive-definite", type: "mcq", difficulty: "easy",
    prompt: "A symmetric matrix $A$ is positive semi-definite if:",
    answer: "$Q(\\mathbf{x})=\\mathbf{x}^TA\\mathbf{x}\\geq0$ for all $\\mathbf{x}$.",
    choices: ["$\\det(A)>0$.", "$Q(\\mathbf{x})=\\mathbf{x}^TA\\mathbf{x}\\geq0$ for all $\\mathbf{x}$.", "All entries are positive.", "$A$ is invertible."],
    explanation: "Step 1: PSD means $Q(\\mathbf{x})\\geq0$ with equality possible (eigenvalues $\\geq0$). PD requires strict inequality. Final answer: $Q(\\mathbf{x})=\\mathbf{x}^TA\\mathbf{x}\\geq0$ for all $\\mathbf{x}$." }),
  p({ id: "sym-spectral-3", topicId: "symmetric-matrices", section: "spectral", type: "numeric", difficulty: "easy",
    prompt: "Find the eigenvalues of $A=\\begin{pmatrix}3&0\\\\0&5\\end{pmatrix}$. What is the larger eigenvalue?",
    answer: "5",
    explanation: "Step 1: $A$ is diagonal and symmetric. Eigenvalues are $3$ and $5$. Larger: $5$. Final answer: $5$." }),
  p({ id: "sym-quadratic-forms-2", topicId: "symmetric-matrices", section: "quadratic-forms", type: "numeric", difficulty: "easy",
    prompt: "Compute $Q(\\mathbf{x})=\\mathbf{x}^TA\\mathbf{x}$ for $A=\\begin{pmatrix}2&0\\\\0&3\\end{pmatrix}$ and $\\mathbf{x}=\\langle 1,1\\rangle$.",
    answer: "5",
    explanation: "Step 1: $Q=2(1)^2+3(1)^2=2+3=5$. Final answer: $5$." }),
  p({ id: "sym-positive-definite-2", topicId: "symmetric-matrices", section: "positive-definite", type: "mcq", difficulty: "easy",
    prompt: "The matrix $A=\\begin{pmatrix}1&0\\\\0&-1\\end{pmatrix}$ is:",
    answer: "Indefinite.",
    choices: ["Positive definite.", "Positive semi-definite.", "Negative definite.", "Indefinite."],
    explanation: "Step 1: Eigenvalues are $1$ (positive) and $-1$ (negative). Mix of signs $\\Rightarrow$ indefinite. Final answer: Indefinite." }),
  p({ id: "sym-svd-2", topicId: "symmetric-matrices", section: "svd", type: "mcq", difficulty: "easy",
    prompt: "In $A=U\\Sigma V^T$, the columns of $U$ are:",
    answer: "Left singular vectors (orthonormal eigenvectors of $AA^T$).",
    choices: ["The eigenvalues of $A$.", "Left singular vectors (orthonormal eigenvectors of $AA^T$).", "The columns of $A$.", "The rows of $V$."],
    explanation: "Step 1: $U$ contains the left singular vectors, which are orthonormal eigenvectors of $AA^T$. Final answer: Left singular vectors (orthonormal eigenvectors of $AA^T$)." }),
  p({ id: "sym-spectral-4", topicId: "symmetric-matrices", section: "spectral", type: "mcq", difficulty: "easy",
    prompt: "A real symmetric matrix $A$ can always be written as $A=Q\\Lambda Q^T$ where $Q$ is:",
    answer: "An orthogonal matrix of eigenvectors.",
    choices: ["An arbitrary invertible matrix.", "An orthogonal matrix of eigenvectors.", "A lower triangular matrix.", "A diagonal matrix."],
    explanation: "Step 1: The Spectral Theorem: $A=Q\\Lambda Q^T$ where $Q$ is orthogonal (columns are orthonormal eigenvectors) and $\\Lambda$ is diagonal. Final answer: An orthogonal matrix of eigenvectors." }),
  p({ id: "sym-quadratic-forms-3", topicId: "symmetric-matrices", section: "quadratic-forms", type: "mcq", difficulty: "easy",
    prompt: "The matrix of a quadratic form $Q(x,y)=5x^2+4xy+2y^2$ is symmetric. What is the $(1,2)$ entry of the associated matrix $A$?",
    answer: "2",
    explanation: "Step 1: For $Q=a x^2 + 2bxy + cy^2$, $A=\\begin{pmatrix}a&b\\\\b&c\\end{pmatrix}$. Step 2: Coefficient of $xy$ is $4=2b$, so $b=2$. $(1,2)$ entry $=2$. Final answer: $2$." }),
  p({ id: "sym-positive-definite-3", topicId: "symmetric-matrices", section: "positive-definite", type: "mcq", difficulty: "easy",
    prompt: "For any matrix $A$, $A^TA$ is always:",
    answer: "Symmetric positive semi-definite.",
    choices: ["Symmetric positive definite.", "Symmetric positive semi-definite.", "Skew-symmetric.", "Invertible."],
    explanation: "Step 1: $(A^TA)^T=A^T(A^T)^T=A^TA$ (symmetric). Step 2: $\\mathbf{x}^T(A^TA)\\mathbf{x}=\\|A\\mathbf{x}\\|^2\\geq0$ (PSD). Final answer: Symmetric positive semi-definite." }),
  p({ id: "sym-svd-3", topicId: "symmetric-matrices", section: "svd", type: "numeric", difficulty: "easy",
    prompt: "For $A=\\begin{pmatrix}3&0\\\\0&4\\end{pmatrix}$, the singular values equal the absolute values of eigenvalues. What is the larger singular value?",
    answer: "4",
    explanation: "Step 1: $A$ is diagonal, so singular values are $|3|=3$ and $|4|=4$. Larger: $4$. Final answer: $4$." }),
  p({ id: "sym-spectral-5", topicId: "symmetric-matrices", section: "spectral", type: "numeric", difficulty: "easy",
    prompt: "A real symmetric $n\\times n$ matrix has how many orthonormal eigenvectors?",
    answer: "n",
    explanation: "Step 1: The Spectral Theorem guarantees an orthonormal basis of $n$ eigenvectors. Final answer: $n$." }),

  // --- Medium (16) ---
  p({ id: "sym-spectral-6", topicId: "symmetric-matrices", section: "spectral", type: "numeric", difficulty: "medium",
    prompt: "Find the eigenvalues of $A=\\begin{pmatrix}4&2\\\\2&1\\end{pmatrix}$. What is the larger eigenvalue?",
    answer: "5",
    explanation: "Step 1: $\\text{tr}=5$, $\\det=4-4=0$. Step 2: $\\lambda^2-5\\lambda=0\\Rightarrow\\lambda(\\lambda-5)=0$. Eigenvalues: $0$ and $5$. Larger: $5$. Final answer: $5$." }),
  p({ id: "sym-quadratic-forms-4", topicId: "symmetric-matrices", section: "quadratic-forms", type: "numeric", difficulty: "medium",
    prompt: "Write $Q(x,y)=3x^2+4xy+3y^2$ in matrix form $\\mathbf{x}^TA\\mathbf{x}$. What is $A_{12}$?",
    answer: "2",
    explanation: "Step 1: $A=\\begin{pmatrix}3&2\\\\2&3\\end{pmatrix}$ (symmetric: off-diagonal $=$ half of cross-term coefficient $=4/2=2$). Step 2: $A_{12}=2$. Final answer: $2$." }),
  p({ id: "sym-positive-definite-4", topicId: "symmetric-matrices", section: "positive-definite", type: "mcq", difficulty: "medium",
    prompt: "By Sylvester's criterion, a $2\\times 2$ symmetric matrix $A=\\begin{pmatrix}a&b\\\\b&c\\end{pmatrix}$ is positive definite iff:",
    answer: "$a>0$ and $ac-b^2>0$.",
    choices: ["$a>0$ and $c>0$.", "$a>0$ and $ac-b^2>0$.", "$\\det(A)>0$.", "$a+c>0$."],
    explanation: "Step 1: Sylvester's criterion: leading principal minors must all be positive. For $2\\times 2$: $a>0$ (first minor) and $ac-b^2>0$ (second minor). Final answer: $a>0$ and $ac-b^2>0$." }),
  p({ id: "sym-svd-4", topicId: "symmetric-matrices", section: "svd", type: "numeric", difficulty: "medium",
    prompt: "For $A=\\begin{pmatrix}2\\\\0\\end{pmatrix}$ (2×1 matrix), find the singular value.",
    answer: "2",
    explanation: "Step 1: $A^TA=[4]$ (1×1). Eigenvalue $=4$. Singular value $=\\sqrt{4}=2$. Final answer: $2$." }),
  p({ id: "sym-spectral-7", topicId: "symmetric-matrices", section: "spectral", type: "mcq", difficulty: "medium",
    prompt: "The spectral decomposition $A=\\sum_{i=1}^n\\lambda_i\\mathbf{q}_i\\mathbf{q}_i^T$ expresses $A$ as:",
    answer: "A sum of rank-1 outer products scaled by eigenvalues.",
    choices: ["A product of $A$ and its inverse.", "A sum of rank-1 outer products scaled by eigenvalues.", "A diagonal matrix.", "The QR factorization of $A$."],
    explanation: "Step 1: Each term $\\lambda_i\\mathbf{q}_i\\mathbf{q}_i^T$ is a rank-1 matrix scaled by eigenvalue $\\lambda_i$. Step 2: This is the spectral (eigenvalue) decomposition. Final answer: A sum of rank-1 outer products scaled by eigenvalues." }),
  p({ id: "sym-positive-definite-5", topicId: "symmetric-matrices", section: "positive-definite", type: "numeric", difficulty: "medium",
    prompt: "Is $A=\\begin{pmatrix}2&1\\\\1&1\\end{pmatrix}$ positive definite? Check Sylvester: $a=2>0$ and $\\det(A)=$",
    answer: "1",
    explanation: "Step 1: $\\det(A)=2\\cdot1-1\\cdot1=1>0$. Step 2: Both conditions met: $A$ is positive definite. Final answer: $1$." }),
  p({ id: "sym-quadratic-forms-5", topicId: "symmetric-matrices", section: "quadratic-forms", type: "numeric", difficulty: "medium",
    prompt: "Diagonalize $Q(x,y)=x^2+4xy+y^2$ using the change of variable $\\mathbf{x}=Q\\mathbf{y}$. The eigenvalues of $A=\\begin{pmatrix}1&2\\\\2&1\\end{pmatrix}$ are $3$ and $-1$. What is the larger eigenvalue?",
    answer: "3",
    explanation: "Step 1: $\\det(A-\\lambda I)=(1-\\lambda)^2-4=0\\Rightarrow(1-\\lambda)^2=4\\Rightarrow\\lambda=3$ or $\\lambda=-1$. Larger: $3$. Final answer: $3$." }),
  p({ id: "sym-svd-5", topicId: "symmetric-matrices", section: "svd", type: "mcq", difficulty: "medium",
    prompt: "The rank of a matrix equals:",
    answer: "The number of nonzero singular values.",
    choices: ["The number of singular values.", "The number of nonzero singular values.", "The largest singular value.", "The sum of singular values."],
    explanation: "Step 1: Rank $=$ number of nonzero singular values $=$ number of nonzero diagonal entries of $\\Sigma$. Final answer: The number of nonzero singular values." }),
  p({ id: "sym-spectral-8", topicId: "symmetric-matrices", section: "spectral", type: "numeric", difficulty: "medium",
    prompt: "For $A=\\begin{pmatrix}2&1\\\\1&2\\end{pmatrix}$, find $\\text{tr}(A)$ and $\\det(A)$ to determine both eigenvalues. What is $\\det(A)$?",
    answer: "3",
    explanation: "Step 1: $\\det(A)=4-1=3$. Step 2: Eigenvalues: $\\lambda^2-4\\lambda+3=0\\Rightarrow(\\lambda-1)(\\lambda-3)=0$: eigenvalues $1$ and $3$. Final answer: $3$." }),
  p({ id: "sym-positive-definite-6", topicId: "symmetric-matrices", section: "positive-definite", type: "mcq", difficulty: "medium",
    prompt: "A Cholesky decomposition $A=LL^T$ exists when $A$ is:",
    answer: "Symmetric positive definite.",
    choices: ["Any symmetric matrix.", "Symmetric positive definite.", "Orthogonal.", "Invertible."],
    explanation: "Step 1: Cholesky: every symmetric positive definite matrix has a unique lower triangular $L$ with positive diagonal: $A=LL^T$. Final answer: Symmetric positive definite." }),
  p({ id: "sym-quadratic-forms-6", topicId: "symmetric-matrices", section: "quadratic-forms", type: "mcq", difficulty: "medium",
    prompt: "The signature of a quadratic form refers to the pair $(p,q)$ where $p$ = number of positive eigenvalues, $q$ = negative. For eigenvalues $\\{3,1,-2\\}$, the signature is:",
    answer: "$(2,1)$",
    choices: ["$(1,2)$", "$(2,1)$", "$(3,0)$", "$(0,3)$"],
    explanation: "Step 1: $p=2$ (eigenvalues $3,1>0$), $q=1$ (eigenvalue $-2<0$). Signature $(2,1)$. Final answer: $(2,1)$." }),
  p({ id: "sym-svd-6", topicId: "symmetric-matrices", section: "svd", type: "numeric", difficulty: "medium",
    prompt: "The condition number of a matrix (ratio of largest to smallest singular value) for $A=\\begin{pmatrix}4&0\\\\0&2\\end{pmatrix}$ is:",
    answer: "2",
    explanation: "Step 1: Singular values are $4$ and $2$. Step 2: Condition number $=4/2=2$. Final answer: $2$." }),
  p({ id: "sym-spectral-9", topicId: "symmetric-matrices", section: "spectral", type: "numeric", difficulty: "medium",
    prompt: "If $A$ is symmetric with eigenvalues $\\lambda_1\\leq\\lambda_2$, the maximum of $\\mathbf{x}^TA\\mathbf{x}$ over $\\|\\mathbf{x}\\|=1$ is:",
    answer: "lambda_2",
    explanation: "Step 1: By the min-max theorem (Rayleigh quotient), max over unit sphere $=\\lambda_{\\max}=\\lambda_2$. Final answer: $\\lambda_2$." }),
  p({ id: "sym-positive-definite-7", topicId: "symmetric-matrices", section: "positive-definite", type: "mcq", difficulty: "medium",
    prompt: "$A$ is positive definite iff $A=B^TB$ for some matrix $B$ with:",
    answer: "Linearly independent columns.",
    choices: ["Any $B$.", "Linearly independent columns.", "Square $B$.", "Orthogonal $B$."],
    explanation: "Step 1: $\\mathbf{x}^TA\\mathbf{x}=\\|B\\mathbf{x}\\|^2>0$ for $\\mathbf{x}\\neq\\mathbf{0}$ iff $B$ has linearly independent columns (so $B\\mathbf{x}\\neq\\mathbf{0}$). Final answer: Linearly independent columns." }),
  p({ id: "sym-svd-7", topicId: "symmetric-matrices", section: "svd", type: "mcq", difficulty: "medium",
    prompt: "The pseudo-inverse (Moore-Penrose) $A^+$ of a matrix $A=U\\Sigma V^T$ is:",
    answer: "$V\\Sigma^+U^T$",
    choices: ["$U\\Sigma V^T$", "$V\\Sigma^+U^T$", "$(A^TA)^{-1}A^T$", "$A^{-1}$"],
    explanation: "Step 1: Replace nonzero singular values by their reciprocals: $\\Sigma^+$. Step 2: $A^+=V\\Sigma^+U^T$. Final answer: $V\\Sigma^+U^T$." }),

  // --- Hard (10) ---
  p({ id: "sym-spectral-10", topicId: "symmetric-matrices", section: "spectral", type: "numeric", difficulty: "hard",
    prompt: "For $A=\\begin{pmatrix}4&2\\\\2&1\\end{pmatrix}$, the eigenvalues are $0$ and $5$. Find the unit eigenvector for $\\lambda=5$. Its first component is $2/\\sqrt{5}\\approx$",
    answer: "0.894",
    explanation: "Step 1: $(A-5I)\\mathbf{v}=\\begin{pmatrix}-1&2\\\\2&-4\\end{pmatrix}\\mathbf{v}=0\\Rightarrow\\mathbf{v}=\\langle 2,1\\rangle$. Step 2: $\\|\\mathbf{v}\\|=\\sqrt{5}$. Unit vector: $\\langle 2/\\sqrt{5},1/\\sqrt{5}\\rangle$. First component: $2/\\sqrt{5}\\approx0.894$. Final answer: $0.894$." }),
  p({ id: "sym-positive-definite-8", topicId: "symmetric-matrices", section: "positive-definite", type: "mcq", difficulty: "hard",
    prompt: "The matrix $A=\\begin{pmatrix}1&2\\\\2&3\\end{pmatrix}$ is NOT positive definite because:",
    answer: "$\\det(A)=3-4=-1<0$.",
    choices: ["$\\text{tr}(A)<0$.", "$\\det(A)=3-4=-1<0$.", "$A$ is not symmetric.", "Its eigenvalues are complex."],
    explanation: "Step 1: Sylvester: $a=1>0$ but $\\det(A)=3-4=-1<0$. Step 2: Fails second criterion $\\Rightarrow$ not PD. Final answer: $\\det(A)=3-4=-1<0$." }),
  p({ id: "sym-svd-8", topicId: "symmetric-matrices", section: "svd", type: "numeric", difficulty: "hard",
    prompt: "For $A=\\begin{pmatrix}3&0\\\\4&0\\end{pmatrix}$, find $A^TA$ and its eigenvalue. The singular value of $A$ is:",
    answer: "5",
    explanation: "Step 1: $A^TA=\\begin{pmatrix}9+16&0\\\\0&0\\end{pmatrix}=\\begin{pmatrix}25&0\\\\0&0\\end{pmatrix}$. Step 2: Nonzero eigenvalue $=25$. Step 3: Singular value $=\\sqrt{25}=5$. Final answer: $5$." }),
  p({ id: "sym-quadratic-forms-7", topicId: "symmetric-matrices", section: "quadratic-forms", type: "mcq", difficulty: "hard",
    prompt: "By the Principal Axis Theorem, any quadratic form can be diagonalized (no cross terms) by:",
    answer: "An orthogonal change of variables $\\mathbf{x}=Q\\mathbf{y}$.",
    choices: ["Any invertible change of variables.", "An orthogonal change of variables $\\mathbf{x}=Q\\mathbf{y}$.", "A translation of coordinates.", "Adding a constant."],
    explanation: "Step 1: The Principal Axis Theorem uses the orthonormal eigenvectors of $A$ to rotate axes, eliminating cross terms. Final answer: An orthogonal change of variables $\\mathbf{x}=Q\\mathbf{y}$." }),
  p({ id: "sym-spectral-11", topicId: "symmetric-matrices", section: "spectral", type: "numeric", difficulty: "hard",
    prompt: "If $A$ is symmetric PD with eigenvalues $\\lambda_1,\\ldots,\\lambda_n>0$, express $A^{-1/2}$: eigenvalues of $A^{-1/2}$ are $1/\\sqrt{\\lambda_i}$. For $\\lambda=4$, what is the eigenvalue of $A^{-1/2}$?",
    answer: "0.5",
    explanation: "Step 1: $A^{-1/2}$ has eigenvalues $1/\\sqrt{\\lambda_i}=1/\\sqrt{4}=1/2=0.5$. Final answer: $0.5$." }),
  p({ id: "sym-svd-9", topicId: "symmetric-matrices", section: "svd", type: "numeric", difficulty: "hard",
    prompt: "The best rank-1 approximation of $A$ (in Frobenius norm) using SVD is $\\sigma_1\\mathbf{u}_1\\mathbf{v}_1^T$. For $A=\\begin{pmatrix}4&0\\\\0&2\\end{pmatrix}$, $\\sigma_1=4$. The Frobenius norm of the error $A-\\sigma_1\\mathbf{u}_1\\mathbf{v}_1^T$ is:",
    answer: "2",
    explanation: "Step 1: $A=\\begin{pmatrix}4&0\\\\0&0\\end{pmatrix}+\\begin{pmatrix}0&0\\\\0&2\\end{pmatrix}$. Best rank-1 approx uses $\\sigma_1=4$. Error norm $=\\sigma_2=2$. Final answer: $2$." }),
  p({ id: "sym-positive-definite-9", topicId: "symmetric-matrices", section: "positive-definite", type: "mcq", difficulty: "hard",
    prompt: "If $A$ and $B$ are symmetric positive definite, is $A+B$ positive definite?",
    answer: "Yes, always.",
    choices: ["No, never.", "Yes, always.", "Only if $AB=BA$.", "Only if they share eigenvectors."],
    explanation: "Step 1: $\\mathbf{x}^T(A+B)\\mathbf{x}=\\mathbf{x}^TA\\mathbf{x}+\\mathbf{x}^TB\\mathbf{x}>0+0=0$ for $\\mathbf{x}\\neq\\mathbf{0}$. Final answer: Yes, always." }),
  p({ id: "sym-spectral-12", topicId: "symmetric-matrices", section: "spectral", type: "numeric", difficulty: "hard",
    prompt: "For symmetric $A$, the spectral radius $\\rho(A)=\\max|\\lambda_i|$ equals $\\|A\\|_2$ (spectral norm). For $A=\\begin{pmatrix}3&0\\\\0&-5\\end{pmatrix}$, $\\rho(A)=$",
    answer: "5",
    explanation: "Step 1: Eigenvalues: $3$ and $-5$. Step 2: $\\rho(A)=\\max(|3|,|-5|)=5$. Final answer: $5$." }),
  p({ id: "sym-svd-10", topicId: "symmetric-matrices", section: "svd", type: "mcq", difficulty: "hard",
    prompt: "The SVD exists for:",
    answer: "Any $m\\times n$ matrix (not just square or symmetric).",
    choices: ["Only square matrices.", "Only symmetric matrices.", "Any $m\\times n$ matrix (not just square or symmetric).", "Only positive definite matrices."],
    explanation: "Step 1: The SVD $A=U\\Sigma V^T$ exists for any real $m\\times n$ matrix. This is one of its main advantages over eigendecomposition. Final answer: Any $m\\times n$ matrix (not just square or symmetric)." }),
  p({ id: "sym-quadratic-forms-8", topicId: "symmetric-matrices", section: "quadratic-forms", type: "numeric", difficulty: "hard",
    prompt: "The quadratic form $Q(\\mathbf{x})=5x_1^2-4x_1x_2+5x_2^2$ has matrix $A=\\begin{pmatrix}5&-2\\\\-2&5\\end{pmatrix}$. Eigenvalues are $3$ and $7$. Is $Q$ positive definite? Enter $1$ for yes, $0$ for no.",
    answer: "1",
    explanation: "Step 1: Both eigenvalues $3>0$ and $7>0$ $\\Rightarrow$ positive definite. Final answer: $1$." }),
];
