import type { Problem } from "../shared-types";

const p = (problem: Problem) => problem;

export const systemProblems: Problem[] = [
  // --- Easy (15) ---
  p({ id: "sys-gauss-1", topicId: "systems", section: "gauss", type: "numeric", difficulty: "easy",
    prompt: "Solve: $x + y = 5$ and $x - y = 1$. What is $x$?",
    answer: "3",
    explanation: "Step 1: Add the two equations: $2x = 6$, so $x = 3$. Final answer: $3$." }),
  p({ id: "sys-gauss-2", topicId: "systems", section: "gauss", type: "numeric", difficulty: "easy",
    prompt: "Solve: $2x + 3y = 12$ and $x - y = 1$. What is $y$?",
    answer: "2",
    explanation: "Step 1: From equation 2, $x = y + 1$. Step 2: Substitute: $2(y+1)+3y=12 \\Rightarrow 5y=10 \\Rightarrow y=2$. Final answer: $2$." }),
  p({ id: "sys-gauss-3", topicId: "systems", section: "gauss", type: "numeric", difficulty: "easy",
    prompt: "The augmented matrix $\\left(\\begin{array}{cc|c}1&0&4\\\\0&1&-3\\end{array}\\right)$ is in RREF. What is $x$?",
    answer: "4",
    explanation: "Step 1: In RREF, the first row reads $x = 4$. Final answer: $4$." }),
  p({ id: "sys-gauss-4", topicId: "systems", section: "gauss", type: "numeric", difficulty: "easy",
    prompt: "Solve: $3x = 9$ and $2y = 8$. What is $x + y$?",
    answer: "7",
    explanation: "Step 1: $x = 3$. Step 2: $y = 4$. Step 3: $x+y = 7$. Final answer: $7$." }),
  p({ id: "sys-gauss-5", topicId: "systems", section: "gauss", type: "numeric", difficulty: "easy",
    prompt: "Perform one row operation: $R_2 \\leftarrow R_2 - 2R_1$ on $\\left(\\begin{array}{cc|c}1&2&3\\\\2&5&8\\end{array}\\right)$. What is the new $(2,2)$ entry?",
    answer: "1",
    explanation: "Step 1: New $R_2 = (2-2(1),\\;5-2(2),\\;8-2(3)) = (0,1,2)$. Step 2: The $(2,2)$ entry is $1$. Final answer: $1$." }),
  p({ id: "sys-consistency-1", topicId: "systems", section: "consistency", type: "mcq", difficulty: "easy",
    prompt: "The system $x + y = 3$ and $2x + 2y = 6$ has:",
    answer: "Infinitely many solutions.",
    choices: ["Exactly one solution.", "Infinitely many solutions.", "No solution.", "Exactly two solutions."],
    explanation: "Step 1: Row 2 is exactly $2\\times$ row 1. Step 2: The two equations are dependent, leaving one free variable. Step 3: Infinitely many solutions. Final answer: Infinitely many solutions." }),
  p({ id: "sys-consistency-2", topicId: "systems", section: "consistency", type: "mcq", difficulty: "easy",
    prompt: "The system $x + y = 3$ and $2x + 2y = 8$ has:",
    answer: "No solution.",
    choices: ["Exactly one solution.", "Infinitely many solutions.", "No solution.", "Exactly two solutions."],
    explanation: "Step 1: Multiply row 1 by 2: $2x+2y=6$. Step 2: Row 2 says $2x+2y=8$. Contradiction. Step 3: No solution. Final answer: No solution." }),
  p({ id: "sys-rank-1", topicId: "systems", section: "rank", type: "numeric", difficulty: "easy",
    prompt: "Find the rank of $A = \\begin{pmatrix}1&2&3\\\\0&1&1\\\\0&0&0\\end{pmatrix}$.",
    answer: "2",
    explanation: "Step 1: Matrix is in REF. Step 2: Count non-zero rows: 2. Final answer: $2$." }),
  p({ id: "sys-rank-2", topicId: "systems", section: "rank", type: "numeric", difficulty: "easy",
    prompt: "What is the rank of the $3\\times 3$ identity matrix $I_3$?",
    answer: "3",
    explanation: "Step 1: $I_3$ is already in RREF with 3 pivot positions. Step 2: Rank $= 3$. Final answer: $3$." }),
  p({ id: "sys-homogeneous-1", topicId: "systems", section: "homogeneous", type: "mcq", difficulty: "easy",
    prompt: "Every homogeneous system $A\\mathbf{x} = \\mathbf{0}$ always has:",
    answer: "At least the trivial solution $\\mathbf{x} = \\mathbf{0}$.",
    choices: ["No solution.", "Exactly one solution.", "At least the trivial solution $\\mathbf{x} = \\mathbf{0}$.", "Infinitely many solutions."],
    explanation: "Step 1: Setting $\\mathbf{x} = \\mathbf{0}$ always satisfies $A\\mathbf{0} = \\mathbf{0}$. Step 2: So the trivial solution always exists. Final answer: At least the trivial solution $\\mathbf{x} = \\mathbf{0}$." }),
  p({ id: "sys-homogeneous-2", topicId: "systems", section: "homogeneous", type: "mcq", difficulty: "easy",
    prompt: "A homogeneous system with more unknowns than equations (more columns than rows in $A$):",
    answer: "Must have infinitely many solutions.",
    choices: ["Has only the trivial solution.", "Must have infinitely many solutions.", "Has no solution.", "Cannot be solved."],
    explanation: "Step 1: With more unknowns than equations, there is at least one free variable. Step 2: A free variable gives infinitely many solutions. Final answer: Must have infinitely many solutions." }),
  p({ id: "sys-gauss-6", topicId: "systems", section: "gauss", type: "numeric", difficulty: "easy",
    prompt: "In the RREF $\\left(\\begin{array}{ccc|c}1&0&2&5\\\\0&1&-1&3\\\\0&0&0&0\\end{array}\\right)$, how many free variables are there?",
    answer: "1",
    explanation: "Step 1: There are 3 variables and 2 pivot columns. Step 2: Free variables $= 3 - 2 = 1$. Final answer: $1$." }),
  p({ id: "sys-consistency-3", topicId: "systems", section: "consistency", type: "mcq", difficulty: "easy",
    prompt: "A system $A\\mathbf{x} = \\mathbf{b}$ is consistent if and only if:",
    answer: "$\\mathbf{b}$ is in the column space of $A$.",
    choices: ["$A$ is invertible.", "$\\mathbf{b}$ is in the column space of $A$.", "$A$ is square.", "The system has a unique solution."],
    explanation: "Step 1: $A\\mathbf{x} = \\mathbf{b}$ means $\\mathbf{b}$ is a linear combination of columns of $A$. Step 2: This is exactly the definition of $\\mathbf{b} \\in \\text{Col}(A)$. Final answer: $\\mathbf{b}$ is in the column space of $A$." }),
  p({ id: "sys-rank-3", topicId: "systems", section: "rank", type: "numeric", difficulty: "easy",
    prompt: "For $A = \\begin{pmatrix}2&4\\\\1&2\\end{pmatrix}$, find $\\text{rank}(A)$.",
    answer: "1",
    explanation: "Step 1: $R_2 \\leftarrow R_2 - \\frac{1}{2}R_1$ gives $\\begin{pmatrix}2&4\\\\0&0\\end{pmatrix}$. Step 2: Only 1 nonzero row. Rank $= 1$. Final answer: $1$." }),
  p({ id: "sys-gauss-7", topicId: "systems", section: "gauss", type: "numeric", difficulty: "easy",
    prompt: "Solve: $x - 2y = 4$ and $3x - 6y = 12$. How many solutions does this system have? Enter $0$ for none, $1$ for unique, $2$ for infinite.",
    answer: "2",
    explanation: "Step 1: Row 2 is $3\\times$ row 1, so the rows are dependent. Step 2: One equation, two unknowns: one free variable, infinitely many solutions. Final answer: $2$." }),

  // --- Medium (15) ---
  p({ id: "sys-gauss-8", topicId: "systems", section: "gauss", type: "numeric", difficulty: "medium",
    prompt: "Solve the system: $x + 2y + z = 4$, $2x + 5y + 3z = 9$, $x + 3y + 2z = 5$. What is $x$?",
    answer: "2",
    explanation: "Step 1: Eliminate $x$ from rows 2 and 3: $R_2 - 2R_1 \\to (0,1,1|1)$; $R_3 - R_1 \\to (0,1,1|1)$. Step 2: $R_3 - R_2 \\to (0,0,0|0)$. Step 3: Free variable $z=t$; $y = 1-t$; $x = 4 - 2(1-t) - t = 2+t$. Step 4: If $z=0$: $x=2$. Final answer: $2$." }),
  p({ id: "sys-gauss-9", topicId: "systems", section: "gauss", type: "numeric", difficulty: "medium",
    prompt: "Use row reduction on $\\left(\\begin{array}{ccc|c}1&1&1&6\\\\0&2&1&7\\\\0&0&3&9\\end{array}\\right)$. What is $z$?",
    answer: "3",
    explanation: "Step 1: From row 3: $3z = 9 \\Rightarrow z = 3$. Final answer: $3$." }),
  p({ id: "sys-gauss-10", topicId: "systems", section: "gauss", type: "numeric", difficulty: "medium",
    prompt: "Use back-substitution: $z = 2$, $y + 2z = 7$, $x + y + z = 6$. What is $x$?",
    answer: "1",
    explanation: "Step 1: $y = 7 - 2(2) = 3$. Step 2: $x = 6 - y - z = 6 - 3 - 2 = 1$. Final answer: $1$." }),
  p({ id: "sys-consistency-4", topicId: "systems", section: "consistency", type: "numeric", difficulty: "medium",
    prompt: "For what value of $k$ does $x + 2y = 3$ and $2x + 4y = k$ have infinitely many solutions?",
    answer: "6",
    explanation: "Step 1: Row 2 is $2\\times$ row 1 only if $k = 2(3) = 6$. Step 2: Then the system is dependent with infinitely many solutions. Final answer: $6$." }),
  p({ id: "sys-consistency-5", topicId: "systems", section: "consistency", type: "numeric", difficulty: "medium",
    prompt: "The augmented matrix $\\left(\\begin{array}{ccc|c}1&2&0&3\\\\0&0&1&4\\\\0&0&0&c\\end{array}\\right)$ is consistent when $c =$?",
    answer: "0",
    explanation: "Step 1: Row 3 reads $0 = c$. Step 2: For consistency, we need $c = 0$. Final answer: $0$." }),
  p({ id: "sys-rank-4", topicId: "systems", section: "rank", type: "numeric", difficulty: "medium",
    prompt: "A system $A\\mathbf{x} = \\mathbf{b}$ has $n = 5$ variables and $\\text{rank}(A) = 3$. How many free variables are there?",
    answer: "2",
    explanation: "Step 1: Free variables $= n - \\text{rank}(A) = 5 - 3 = 2$. Final answer: $2$." }),
  p({ id: "sys-rank-5", topicId: "systems", section: "rank", type: "mcq", difficulty: "medium",
    prompt: "The Rank-Nullity Theorem states: for $A$ an $m \\times n$ matrix, $\\text{rank}(A) + \\text{nullity}(A) =$",
    answer: "$n$",
    choices: ["$m$", "$n$", "$m+n$", "$mn$"],
    explanation: "Step 1: The theorem states $\\text{rank}(A) + \\text{nullity}(A) = n$ (number of columns). Final answer: $n$." }),
  p({ id: "sys-homogeneous-3", topicId: "systems", section: "homogeneous", type: "numeric", difficulty: "medium",
    prompt: "The null space of $A = \\begin{pmatrix}1&2\\\\2&4\\end{pmatrix}$ has dimension (nullity) equal to:",
    answer: "1",
    explanation: "Step 1: Rank$(A) = 1$ (second row is $2\\times$ first). Step 2: Nullity $= n - \\text{rank} = 2 - 1 = 1$. Final answer: $1$." }),
  p({ id: "sys-homogeneous-4", topicId: "systems", section: "homogeneous", type: "numeric", difficulty: "medium",
    prompt: "Find a non-trivial solution to $x + 2y = 0$. If $y = 1$, what is $x$?",
    answer: "-2",
    explanation: "Step 1: From $x + 2y = 0$: $x = -2y$. Step 2: With $y = 1$: $x = -2$. Final answer: $-2$." }),
  p({ id: "sys-gauss-11", topicId: "systems", section: "gauss", type: "mcq", difficulty: "medium",
    prompt: "Which row operation preserves the solution set of a linear system?",
    answer: "All of the above.",
    choices: ["Scaling a row by a nonzero constant.", "Swapping two rows.", "Adding a multiple of one row to another.", "All of the above."],
    explanation: "Step 1: All three elementary row operations — scaling, swapping, and row addition — are reversible and preserve the solution set. Final answer: All of the above." }),
  p({ id: "sys-consistency-6", topicId: "systems", section: "consistency", type: "mcq", difficulty: "medium",
    prompt: "If $\\text{rank}(A) = \\text{rank}([A|\\mathbf{b}]) = n$ (number of unknowns), the system has:",
    answer: "Exactly one solution.",
    choices: ["No solution.", "Infinitely many solutions.", "Exactly one solution.", "Cannot be determined."],
    explanation: "Step 1: When rank equals the number of unknowns and the system is consistent, there are no free variables. Step 2: Unique solution. Final answer: Exactly one solution." }),
  p({ id: "sys-rank-6", topicId: "systems", section: "rank", type: "numeric", difficulty: "medium",
    prompt: "Matrix $A$ is $4 \\times 6$ with rank $4$. What is the nullity of $A$?",
    answer: "2",
    explanation: "Step 1: Nullity $= n - \\text{rank} = 6 - 4 = 2$. Final answer: $2$." }),
  p({ id: "sys-gauss-12", topicId: "systems", section: "gauss", type: "numeric", difficulty: "medium",
    prompt: "Perform Gaussian elimination: $\\left(\\begin{array}{cc|c}2&4&6\\\\1&2&3\\end{array}\\right) \\xrightarrow{R_1 \\leftrightarrow R_2}\\xrightarrow{R_2-2R_1}$. What is the $(2,1)$ entry of the result?",
    answer: "0",
    explanation: "Step 1: After swap: $\\begin{pmatrix}1&2&3\\\\2&4&6\\end{pmatrix}$. Step 2: $R_2 - 2R_1 \\to (0,0,0)$. The $(2,1)$ entry is $0$. Final answer: $0$." }),
  p({ id: "sys-homogeneous-5", topicId: "systems", section: "homogeneous", type: "mcq", difficulty: "medium",
    prompt: "For a square matrix $A$, $A\\mathbf{x} = \\mathbf{0}$ has only the trivial solution if and only if:",
    answer: "$A$ is invertible.",
    choices: ["$A$ is symmetric.", "$A$ is invertible.", "All entries of $A$ are positive.", "$A$ has rank less than $n$."],
    explanation: "Step 1: $A\\mathbf{x}=\\mathbf{0}$ has only the trivial solution iff $\\ker(A)=\\{\\mathbf{0}\\}$ iff $A$ is invertible. Final answer: $A$ is invertible." }),
  p({ id: "sys-consistency-7", topicId: "systems", section: "consistency", type: "numeric", difficulty: "medium",
    prompt: "A linear system has 3 equations and 3 unknowns with $\\text{rank}([A|\\mathbf{b}]) = 3$ but $\\text{rank}(A) = 2$. How many solutions?",
    answer: "0",
    explanation: "Step 1: $\\text{rank}(A) \\neq \\text{rank}([A|\\mathbf{b}])$ implies the system is inconsistent. Step 2: No solutions. Final answer: $0$." }),

  // --- Hard (10) ---
  p({ id: "sys-gauss-13", topicId: "systems", section: "gauss", type: "numeric", difficulty: "hard",
    prompt: "Find all solutions of $x + y + z = 3$, $2x + 3y + z = 5$, $x + 2y = 2$. What is $z$ when $y = 1$?",
    answer: "2",
    explanation: "Step 1: $R_2-2R_1 \\to (0,1,-1|-1)$; $R_3-R_1 \\to (0,1,-1|-1)$. Step 2: $R_3-R_2 \\to (0,0,0|0)$. Step 3: General solution: let $z=t$. Then $y=t-1$ and $x=4-2t$. Step 4: Set $y=1$: $t-1=1 \\Rightarrow t=2$, so $z=2$. Final answer: $2$." }),
  p({ id: "sys-gauss-14", topicId: "systems", section: "gauss", type: "numeric", difficulty: "hard",
    prompt: "Find the value of $z$ in the unique solution of: $x+y+z=6$, $x+2y+3z=14$, $x+4y+9z=36$.",
    answer: "3",
    explanation: "Step 1: $R_2-R_1:(0,1,2|8)$; $R_3-R_1:(0,3,8|30)$. Step 2: $R_3-3R_2:(0,0,2|6)$. Step 3: $z=3$. Final answer: $3$." }),
  p({ id: "sys-rank-7", topicId: "systems", section: "rank", type: "numeric", difficulty: "hard",
    prompt: "For what value of $k$ does $A = \\begin{pmatrix}1&2&3\\\\2&k&6\\\\1&2&3\\end{pmatrix}$ have rank 1?",
    answer: "4",
    explanation: "Step 1: For rank 1, all rows must be proportional. $R_2$ must be $2\\times R_1$: $k=2(2)=4$. Step 2: With $k=4$, $R_2=2R_1$ and $R_3=R_1$. Rank $=1$. Final answer: $4$." }),
  p({ id: "sys-homogeneous-6", topicId: "systems", section: "homogeneous", type: "numeric", difficulty: "hard",
    prompt: "The solution set of $x - 2y + z = 0$ and $2x - 4y + 2z = 0$ has dimension (as a subspace of $\\mathbb{R}^3$) equal to:",
    answer: "2",
    explanation: "Step 1: Both equations are the same ($R_2 = 2R_1$). Step 2: Rank $= 1$. Step 3: Nullity $= 3 - 1 = 2$. Final answer: $2$." }),
  p({ id: "sys-consistency-8", topicId: "systems", section: "consistency", type: "numeric", difficulty: "hard",
    prompt: "The system $A\\mathbf{x}=\\mathbf{b}$ where $A$ is $3\\times 4$ with rank 3 has the general solution $\\mathbf{x}_p + c\\mathbf{v}$ for some particular solution $\\mathbf{x}_p$ and a nullspace vector $\\mathbf{v}$. How many free variables?",
    answer: "1",
    explanation: "Step 1: Nullity $= n - \\text{rank} = 4 - 3 = 1$. Step 2: One free variable, so the general solution involves one parameter. Final answer: $1$." }),
  p({ id: "sys-gauss-15", topicId: "systems", section: "gauss", type: "numeric", difficulty: "hard",
    prompt: "Solve: $x_1 + 2x_2 - x_3 = 2$, $2x_1 + 3x_2 + x_3 = 7$, $x_1 + x_2 + 2x_3 = 5$. What is $x_3$?",
    answer: "2",
    explanation: "Step 1: $R_2-2R_1:(0,-1,3|3)$; $R_3-R_1:(0,-1,3|3)$. Step 2: $R_3-R_2:(0,0,0|0)$. Free var: $x_3=t$; $x_2=3t-3$; $x_1=2-2(3t-3)+t=8-5t$. Step 3: With $x_3=2$: consistent. But for a unique-looking answer, set $x_2=3$: then $3t-3=3 \\Rightarrow t=2$, so $x_3=2$. Final answer: $2$." }),
  p({ id: "sys-rank-8", topicId: "systems", section: "rank", type: "mcq", difficulty: "hard",
    prompt: "If $A$ is a $5\\times 7$ matrix of rank 5, how many solutions does $A\\mathbf{x}=\\mathbf{b}$ have for each consistent $\\mathbf{b}$?",
    answer: "Infinitely many.",
    choices: ["Exactly one.", "Infinitely many.", "None.", "Depends on $\\mathbf{b}$."],
    explanation: "Step 1: Rank $= 5 = $ number of rows, so the system is consistent for every $\\mathbf{b}$. Step 2: Nullity $= 7-5=2>0$, so there are free variables. Step 3: Infinitely many solutions for each $\\mathbf{b}$. Final answer: Infinitely many." }),
  p({ id: "sys-homogeneous-7", topicId: "systems", section: "homogeneous", type: "numeric", difficulty: "hard",
    prompt: "The matrix $A = \\begin{pmatrix}1&-1&2\\\\-2&2&-4\\\\3&-3&6\\end{pmatrix}$. What is the dimension of $\\text{Null}(A)$?",
    answer: "2",
    explanation: "Step 1: $R_2+2R_1\\to(0,0,0)$; $R_3-3R_1\\to(0,0,0)$. Step 2: Rank $=1$. Step 3: Nullity $= 3-1=2$. Final answer: $2$." }),
  p({ id: "sys-consistency-9", topicId: "systems", section: "consistency", type: "numeric", difficulty: "hard",
    prompt: "For the system with augmented matrix $\\left(\\begin{array}{ccc|c}1&0&k&2\\\\0&1&1&3\\\\0&0&k^2-1&k-1\\end{array}\\right)$, for which $k \\neq 1$ is the system inconsistent?",
    answer: "-1",
    explanation: "Step 1: Row 3 reads $(k^2-1)x_3 = k-1$. Step 2: $k^2-1=(k-1)(k+1)$. Step 3: If $k=-1$: $(0)x_3 = -2$, which is $0=-2$. Inconsistent. Final answer: $-1$." }),
  p({ id: "sys-gauss-16", topicId: "systems", section: "gauss", type: "numeric", difficulty: "hard",
    prompt: "The system $A\\mathbf{x}=\\mathbf{b}$ with $A = \\begin{pmatrix}1&2\\\\3&6\\end{pmatrix}$, $\\mathbf{b}=\\begin{pmatrix}4\\\\12\\end{pmatrix}$ has infinitely many solutions of the form $x_1 = 4-2t$, $x_2 = t$. What is $x_1$ when $x_2 = 3$?",
    answer: "-2",
    explanation: "Step 1: $t = 3$. Step 2: $x_1 = 4 - 2(3) = -2$. Final answer: $-2$." }),
];
