import type { Problem } from "../shared-types";

const p = (problem: Problem) => problem;

export const vectorProblems: Problem[] = [
  // --- Easy (15) ---
  p({ id: "vec-operations-1", topicId: "vectors", section: "operations", type: "numeric", difficulty: "easy",
    prompt: "Let $\\mathbf{u} = \\langle 2, 3 \\rangle$ and $\\mathbf{v} = \\langle 1, -1 \\rangle$. What is the first component of $\\mathbf{u} + \\mathbf{v}$?",
    answer: "3",
    explanation: "Step 1: Add component-wise: $\\langle 2+1, 3-1 \\rangle = \\langle 3, 2 \\rangle$. Step 2: First component is $3$. Final answer: $3$." }),
  p({ id: "vec-operations-2", topicId: "vectors", section: "operations", type: "numeric", difficulty: "easy",
    prompt: "If $\\mathbf{v} = \\langle 4, -2 \\rangle$, what is the second component of $3\\mathbf{v}$?",
    answer: "-6",
    explanation: "Step 1: $3\\mathbf{v} = \\langle 12, -6 \\rangle$. Step 2: Second component is $-6$. Final answer: $-6$." }),
  p({ id: "vec-operations-3", topicId: "vectors", section: "operations", type: "numeric", difficulty: "easy",
    prompt: "Find $\\|\\mathbf{v}\\|$ for $\\mathbf{v} = \\langle 3, 4 \\rangle$.",
    answer: "5",
    explanation: "Step 1: $\\|\\mathbf{v}\\| = \\sqrt{9+16} = \\sqrt{25} = 5$. Final answer: $5$." }),
  p({ id: "vec-operations-4", topicId: "vectors", section: "operations", type: "numeric", difficulty: "easy",
    prompt: "Find $\\|\\mathbf{v}\\|$ for $\\mathbf{v} = \\langle 0, -5, 12 \\rangle$.",
    answer: "13",
    explanation: "Step 1: $\\|\\mathbf{v}\\| = \\sqrt{0+25+144} = \\sqrt{169} = 13$. Final answer: $13$." }),
  p({ id: "vec-operations-5", topicId: "vectors", section: "operations", type: "numeric", difficulty: "easy",
    prompt: "What is the unit vector in the direction of $\\mathbf{v} = \\langle 6, 0 \\rangle$?",
    answer: "⟨1,0⟩",
    explanation: "Step 1: $\\|\\mathbf{v}\\| = 6$. Step 2: $\\hat{\\mathbf{v}} = \\langle 6/6, 0/6 \\rangle = \\langle 1, 0 \\rangle$. Final answer: $\\langle 1, 0 \\rangle$." }),
  p({ id: "vec-dot-1", topicId: "vectors", section: "dot", type: "numeric", difficulty: "easy",
    prompt: "Compute: $\\langle 1, 2, 3 \\rangle \\cdot \\langle 4, -1, 2 \\rangle$",
    answer: "8",
    explanation: "Step 1: $(1)(4)+(2)(-1)+(3)(2) = 4-2+6 = 8$. Final answer: $8$." }),
  p({ id: "vec-dot-2", topicId: "vectors", section: "dot", type: "numeric", difficulty: "easy",
    prompt: "Compute: $\\langle 3, -2 \\rangle \\cdot \\langle 4, 6 \\rangle$",
    answer: "0",
    explanation: "Step 1: $(3)(4)+(-2)(6) = 12-12 = 0$. Final answer: $0$." }),
  p({ id: "vec-dot-3", topicId: "vectors", section: "dot", type: "mcq", difficulty: "easy",
    prompt: "If $\\mathbf{u} \\cdot \\mathbf{v} = 0$, the vectors are:",
    answer: "Orthogonal.",
    choices: ["Parallel.", "Orthogonal.", "Equal.", "Anti-parallel."],
    explanation: "Step 1: The dot product is zero if and only if the two vectors are orthogonal (perpendicular). Final answer: Orthogonal." }),
  p({ id: "vec-dot-4", topicId: "vectors", section: "dot", type: "numeric", difficulty: "easy",
    prompt: "Find $\\mathbf{u} \\cdot \\mathbf{u}$ for $\\mathbf{u} = \\langle 2, -3, 1 \\rangle$.",
    answer: "14",
    explanation: "Step 1: $\\mathbf{u} \\cdot \\mathbf{u} = 4+9+1 = 14$. Note: $\\mathbf{u}\\cdot\\mathbf{u} = \\|\\mathbf{u}\\|^2$. Final answer: $14$." }),
  p({ id: "vec-operations-6", topicId: "vectors", section: "operations", type: "numeric", difficulty: "easy",
    prompt: "What is the second component of $\\mathbf{u} - \\mathbf{v}$ for $\\mathbf{u}=\\langle 5,3\\rangle$ and $\\mathbf{v}=\\langle 2,7\\rangle$?",
    answer: "-4",
    explanation: "Step 1: $\\mathbf{u}-\\mathbf{v} = \\langle 3, -4 \\rangle$. Step 2: Second component is $-4$. Final answer: $-4$." }),
  p({ id: "vec-operations-7", topicId: "vectors", section: "operations", type: "numeric", difficulty: "easy",
    prompt: "Find $\\|-3\\mathbf{v}\\|$ if $\\|\\mathbf{v}\\| = 4$.",
    answer: "12",
    explanation: "Step 1: $\\|c\\mathbf{v}\\| = |c|\\|\\mathbf{v}\\|$. Step 2: $|-3|\\cdot 4 = 12$. Final answer: $12$." }),
  p({ id: "vec-projection-1", topicId: "vectors", section: "projection", type: "mcq", difficulty: "easy",
    prompt: "The scalar projection of $\\mathbf{u}$ onto $\\mathbf{v}$ is defined as:",
    answer: "$\\dfrac{\\mathbf{u}\\cdot\\mathbf{v}}{\\|\\mathbf{v}\\|}$",
    choices: ["$\\dfrac{\\mathbf{u}\\cdot\\mathbf{v}}{\\|\\mathbf{v}\\|}$", "$\\dfrac{\\mathbf{u}\\cdot\\mathbf{v}}{\\|\\mathbf{u}\\|}$", "$\\dfrac{\\mathbf{u}\\cdot\\mathbf{v}}{\\|\\mathbf{u}\\|\\|\\mathbf{v}\\|}$", "$\\mathbf{u}\\cdot\\mathbf{v}$"],
    explanation: "Step 1: The scalar projection (component of $\\mathbf{u}$ along $\\mathbf{v}$) is $\\text{comp}_{\\mathbf{v}}\\mathbf{u} = \\frac{\\mathbf{u}\\cdot\\mathbf{v}}{\\|\\mathbf{v}\\|}$. Final answer: $\\frac{\\mathbf{u}\\cdot\\mathbf{v}}{\\|\\mathbf{v}\\|}$." }),
  p({ id: "vec-dot-5", topicId: "vectors", section: "dot", type: "numeric", difficulty: "easy",
    prompt: "If $\\mathbf{u} = \\langle 1,0 \\rangle$ and $\\mathbf{v} = \\langle 0,1 \\rangle$, what is the angle between them in degrees?",
    answer: "90",
    explanation: "Step 1: $\\cos\\theta = \\frac{\\mathbf{u}\\cdot\\mathbf{v}}{\\|\\mathbf{u}\\|\\|\\mathbf{v}\\|} = \\frac{0}{1} = 0$. Step 2: $\\theta = 90^\\circ$. Final answer: $90$." }),
  p({ id: "vec-operations-8", topicId: "vectors", section: "operations", type: "numeric", difficulty: "easy",
    prompt: "Compute $2\\mathbf{u} - 3\\mathbf{v}$ where $\\mathbf{u} = \\langle 1,2 \\rangle$ and $\\mathbf{v} = \\langle 0,1 \\rangle$. What is the second component?",
    answer: "1",
    explanation: "Step 1: $2\\mathbf{u} = \\langle 2,4\\rangle$, $3\\mathbf{v}=\\langle 0,3\\rangle$. Step 2: $2\\mathbf{u}-3\\mathbf{v}=\\langle 2,1\\rangle$. Second component: $1$. Final answer: $1$." }),
  p({ id: "vec-operations-9", topicId: "vectors", section: "operations", type: "mcq", difficulty: "easy",
    prompt: "Which property does NOT apply to vector addition?",
    answer: "Commutativity fails: $\\mathbf{u}+\\mathbf{v}\\neq\\mathbf{v}+\\mathbf{u}$.",
    choices: ["Commutativity fails: $\\mathbf{u}+\\mathbf{v}\\neq\\mathbf{v}+\\mathbf{u}$.", "Associativity: $(\\mathbf{u}+\\mathbf{v})+\\mathbf{w}=\\mathbf{u}+(\\mathbf{v}+\\mathbf{w})$.", "The zero vector $\\mathbf{0}$ acts as additive identity.", "Each vector has an additive inverse."],
    explanation: "Step 1: Vector addition IS commutative: $\\mathbf{u}+\\mathbf{v}=\\mathbf{v}+\\mathbf{u}$. Step 2: Therefore the statement 'commutativity fails' is false — it is the one that does NOT apply. Final answer: Commutativity fails: $\\mathbf{u}+\\mathbf{v}\\neq\\mathbf{v}+\\mathbf{u}$." }),

  // --- Medium (15) ---
  p({ id: "vec-dot-6", topicId: "vectors", section: "dot", type: "numeric", difficulty: "medium",
    prompt: "Find the angle in degrees between $\\mathbf{u}=\\langle 1,1 \\rangle$ and $\\mathbf{v}=\\langle 1,0 \\rangle$.",
    answer: "45",
    explanation: "Step 1: $\\mathbf{u}\\cdot\\mathbf{v}=1$. Step 2: $\\|\\mathbf{u}\\|=\\sqrt{2}$, $\\|\\mathbf{v}\\|=1$. Step 3: $\\cos\\theta=\\frac{1}{\\sqrt{2}}$. Step 4: $\\theta=45^\\circ$. Final answer: $45$." }),
  p({ id: "vec-projection-2", topicId: "vectors", section: "projection", type: "numeric", difficulty: "medium",
    prompt: "Find the scalar projection of $\\mathbf{u}=\\langle 3,4 \\rangle$ onto $\\mathbf{v}=\\langle 1,0 \\rangle$.",
    answer: "3",
    explanation: "Step 1: $\\text{comp}_{\\mathbf{v}}\\mathbf{u} = \\frac{\\mathbf{u}\\cdot\\mathbf{v}}{\\|\\mathbf{v}\\|} = \\frac{3}{1} = 3$. Final answer: $3$." }),
  p({ id: "vec-projection-3", topicId: "vectors", section: "projection", type: "numeric", difficulty: "medium",
    prompt: "Find the first component of the vector projection of $\\mathbf{u}=\\langle 3,4 \\rangle$ onto $\\mathbf{v}=\\langle 1,0 \\rangle$.",
    answer: "3",
    explanation: "Step 1: $\\text{proj}_{\\mathbf{v}}\\mathbf{u} = \\frac{\\mathbf{u}\\cdot\\mathbf{v}}{\\|\\mathbf{v}\\|^2}\\mathbf{v} = \\frac{3}{1}\\langle 1,0\\rangle = \\langle 3,0\\rangle$. Step 2: First component is $3$. Final answer: $3$." }),
  p({ id: "vec-dot-7", topicId: "vectors", section: "dot", type: "numeric", difficulty: "medium",
    prompt: "Two vectors have $\\|\\mathbf{u}\\|=5$, $\\|\\mathbf{v}\\|=4$, and $\\mathbf{u}\\cdot\\mathbf{v}=10$. Find $\\cos\\theta$.",
    answer: "0.5",
    explanation: "Step 1: $\\cos\\theta = \\frac{\\mathbf{u}\\cdot\\mathbf{v}}{\\|\\mathbf{u}\\|\\|\\mathbf{v}\\|} = \\frac{10}{20} = 0.5$. Final answer: $0.5$." }),
  p({ id: "vec-operations-10", topicId: "vectors", section: "operations", type: "mcq", difficulty: "medium",
    prompt: "The vectors $\\langle 1, 2, 3 \\rangle$ and $\\langle 2, 4, 6 \\rangle$ are:",
    answer: "Parallel.",
    choices: ["Orthogonal.", "Parallel.", "Neither parallel nor orthogonal.", "Identical."],
    explanation: "Step 1: $\\langle 2,4,6\\rangle = 2\\langle 1,2,3\\rangle$. Step 2: One is a scalar multiple of the other, so they are parallel. Final answer: Parallel." }),
  p({ id: "vec-projection-4", topicId: "vectors", section: "projection", type: "numeric", difficulty: "medium",
    prompt: "Find the scalar projection of $\\mathbf{b}=\\langle 2,3 \\rangle$ onto $\\mathbf{a}=\\langle 4,0 \\rangle$.",
    answer: "2",
    explanation: "Step 1: $\\mathbf{a}\\cdot\\mathbf{b} = 8$. Step 2: $\\|\\mathbf{a}\\| = 4$. Step 3: $\\text{comp} = 8/4 = 2$. Final answer: $2$." }),
  p({ id: "vec-dot-8", topicId: "vectors", section: "dot", type: "numeric", difficulty: "medium",
    prompt: "Vectors $\\mathbf{u}=\\langle 2,1,-1\\rangle$ and $\\mathbf{v}=\\langle -1,k,3\\rangle$ are orthogonal. Find $k$.",
    answer: "5",
    explanation: "Step 1: $\\mathbf{u}\\cdot\\mathbf{v} = -2+k-3=0$. Step 2: $k=5$. Final answer: $5$." }),
  p({ id: "vec-operations-11", topicId: "vectors", section: "operations", type: "numeric", difficulty: "medium",
    prompt: "Find the unit vector in the direction of $\\mathbf{v}=\\langle 3,-4 \\rangle$. What is the first component?",
    answer: "0.6",
    explanation: "Step 1: $\\|\\mathbf{v}\\|=5$. Step 2: $\\hat{\\mathbf{v}}=\\langle 3/5,-4/5\\rangle = \\langle 0.6,-0.8\\rangle$. First component: $0.6$. Final answer: $0.6$." }),
  p({ id: "vec-projection-5", topicId: "vectors", section: "projection", type: "numeric", difficulty: "medium",
    prompt: "Find the component of $\\mathbf{u}=\\langle 1,2,2\\rangle$ orthogonal to $\\mathbf{v}=\\langle 1,0,0\\rangle$. What is the magnitude?",
    answer: "sqrt(8)",
    explanation: "Step 1: $\\text{proj}_{\\mathbf{v}}\\mathbf{u}=\\langle 1,0,0\\rangle$. Step 2: Orthogonal component $= \\langle 0,2,2\\rangle$. Step 3: $\\|\\langle 0,2,2\\rangle\\|=\\sqrt{8}$. Final answer: $\\sqrt{8}$." }),
  p({ id: "vec-dot-9", topicId: "vectors", section: "dot", type: "numeric", difficulty: "medium",
    prompt: "Compute $\\|\\mathbf{u}+\\mathbf{v}\\|^2$ where $\\mathbf{u}=\\langle 1,2\\rangle$ and $\\mathbf{v}=\\langle 3,4\\rangle$.",
    answer: "52",
    explanation: "Step 1: $\\mathbf{u}+\\mathbf{v}=\\langle 4,6\\rangle$. Step 2: $\\|\\langle 4,6\\rangle\\|^2 = 16+36=52$. Final answer: $52$." }),
  p({ id: "vec-operations-12", topicId: "vectors", section: "operations", type: "numeric", difficulty: "medium",
    prompt: "Are $\\mathbf{u}=\\langle 1,-1,2\\rangle$, $\\mathbf{v}=\\langle 0,1,3\\rangle$, $\\mathbf{w}=\\langle 2,-1,7\\rangle$ linearly dependent? Enter $1$ for yes, $0$ for no.",
    answer: "1",
    explanation: "Step 1: Check if $\\mathbf{w}=a\\mathbf{u}+b\\mathbf{v}$. Try $a=2, b=1$: $2\\langle 1,-1,2\\rangle+\\langle 0,1,3\\rangle=\\langle 2,-1,7\\rangle=\\mathbf{w}$. Step 2: Yes, linearly dependent. Final answer: $1$." }),
  p({ id: "vec-dot-10", topicId: "vectors", section: "dot", type: "mcq", difficulty: "medium",
    prompt: "By the Cauchy-Schwarz inequality, $|\\mathbf{u}\\cdot\\mathbf{v}|$ is:",
    answer: "At most $\\|\\mathbf{u}\\|\\|\\mathbf{v}\\|$.",
    choices: ["Always equal to $\\|\\mathbf{u}\\|\\|\\mathbf{v}\\|$.", "At most $\\|\\mathbf{u}\\|\\|\\mathbf{v}\\|$.", "At least $\\|\\mathbf{u}\\|\\|\\mathbf{v}\\|$.", "Always equal to $0$."],
    explanation: "Step 1: Cauchy-Schwarz: $|\\mathbf{u}\\cdot\\mathbf{v}|\\leq\\|\\mathbf{u}\\|\\|\\mathbf{v}\\|$, with equality iff the vectors are parallel. Final answer: At most $\\|\\mathbf{u}\\|\\|\\mathbf{v}\\|$." }),
  p({ id: "vec-operations-13", topicId: "vectors", section: "operations", type: "numeric", difficulty: "medium",
    prompt: "Find the distance between points $P=(1,2,3)$ and $Q=(4,6,3)$.",
    answer: "5",
    explanation: "Step 1: $\\overrightarrow{PQ}=\\langle 3,4,0\\rangle$. Step 2: $\\|\\overrightarrow{PQ}\\|=\\sqrt{9+16+0}=5$. Final answer: $5$." }),
  p({ id: "vec-projection-6", topicId: "vectors", section: "projection", type: "numeric", difficulty: "medium",
    prompt: "Project $\\mathbf{u}=\\langle 5,5 \\rangle$ onto $\\mathbf{v}=\\langle 1,1 \\rangle$. What is the first component of the result?",
    answer: "5",
    explanation: "Step 1: $\\frac{\\mathbf{u}\\cdot\\mathbf{v}}{\\|\\mathbf{v}\\|^2}=\\frac{10}{2}=5$. Step 2: $\\text{proj}_{\\mathbf{v}}\\mathbf{u}=5\\langle 1,1\\rangle=\\langle 5,5\\rangle$. First component: $5$. Final answer: $5$." }),
  p({ id: "vec-dot-11", topicId: "vectors", section: "dot", type: "numeric", difficulty: "medium",
    prompt: "Use the dot product to find the angle (in degrees) between $\\mathbf{u}=\\langle 1,0,0\\rangle$ and $\\mathbf{v}=\\langle 1,1,0\\rangle$.",
    answer: "45",
    explanation: "Step 1: $\\mathbf{u}\\cdot\\mathbf{v}=1$. Step 2: $\\|\\mathbf{u}\\|=1$, $\\|\\mathbf{v}\\|=\\sqrt{2}$. Step 3: $\\cos\\theta=1/\\sqrt{2}$. Step 4: $\\theta=45^\\circ$. Final answer: $45$." }),

  // --- Hard (10) ---
  p({ id: "vec-projection-7", topicId: "vectors", section: "projection", type: "numeric", difficulty: "hard",
    prompt: "Decompose $\\mathbf{b}=\\langle 3,4 \\rangle$ into $\\mathbf{b}_{\\parallel}+\\mathbf{b}_{\\perp}$ where $\\mathbf{b}_{\\parallel}$ is parallel to $\\mathbf{a}=\\langle 1,0\\rangle$. What is the magnitude of $\\mathbf{b}_{\\perp}$?",
    answer: "4",
    explanation: "Step 1: $\\mathbf{b}_{\\parallel}=\\text{proj}_{\\mathbf{a}}\\mathbf{b}=\\langle 3,0\\rangle$. Step 2: $\\mathbf{b}_{\\perp}=\\langle 0,4\\rangle$. Step 3: $\\|\\mathbf{b}_{\\perp}\\|=4$. Final answer: $4$." }),
  p({ id: "vec-dot-12", topicId: "vectors", section: "dot", type: "numeric", difficulty: "hard",
    prompt: "Find $k$ such that $\\mathbf{u}=\\langle k,1,2 \\rangle$ and $\\mathbf{v}=\\langle 2,-1,1 \\rangle$ are orthogonal.",
    answer: "-0.5",
    explanation: "Step 1: $\\mathbf{u}\\cdot\\mathbf{v}=2k-1+2=0$. Step 2: $2k+1=0 \\Rightarrow k=-1/2=-0.5$. Final answer: $-0.5$." }),
  p({ id: "vec-operations-14", topicId: "vectors", section: "operations", type: "numeric", difficulty: "hard",
    prompt: "Show that $\\|\\mathbf{u}+\\mathbf{v}\\|^2 + \\|\\mathbf{u}-\\mathbf{v}\\|^2 = 2(\\|\\mathbf{u}\\|^2+\\|\\mathbf{v}\\|^2)$ (Parallelogram Law). For $\\mathbf{u}=\\langle 1,2\\rangle$, $\\mathbf{v}=\\langle 3,1\\rangle$: compute the right-hand side.",
    answer: "30",
    explanation: "Step 1: $\\|\\mathbf{u}\\|^2=5$, $\\|\\mathbf{v}\\|^2=10$. Step 2: RHS $= 2(5+10) = 30$. Step 3: Verify: $\\|\\mathbf{u}+\\mathbf{v}\\|^2=\\|\\langle 4,3\\rangle\\|^2=25$, $\\|\\mathbf{u}-\\mathbf{v}\\|^2=\\|\\langle -2,1\\rangle\\|^2=5$. Sum $=30$. Final answer: $30$." }),
  p({ id: "vec-projection-8", topicId: "vectors", section: "projection", type: "numeric", difficulty: "hard",
    prompt: "Find the distance from the point $P=(2,3)$ to the line through the origin in the direction $\\mathbf{d}=\\langle 1,1\\rangle/\\sqrt{2}$.",
    answer: "0.5*sqrt(2)",
    explanation: "Step 1: Scalar projection of $\\overrightarrow{OP}=\\langle 2,3\\rangle$ onto $\\hat{\\mathbf{d}}$: $\\frac{\\langle 2,3\\rangle\\cdot\\langle 1,1\\rangle}{\\sqrt{2}}=\\frac{5}{\\sqrt{2}}$. Step 2: Vector projection $=\\frac{5}{\\sqrt{2}}\\cdot\\frac{\\langle 1,1\\rangle}{\\sqrt{2}}=\\langle 5/2,5/2\\rangle$. Step 3: Perpendicular component $=\\langle 2-5/2,3-5/2\\rangle=\\langle -1/2,1/2\\rangle$. Step 4: Distance $=\\sqrt{1/4+1/4}=1/\\sqrt{2}=\\frac{\\sqrt{2}}{2}$. Final answer: $\\frac{\\sqrt{2}}{2}$." }),
  p({ id: "vec-dot-13", topicId: "vectors", section: "dot", type: "numeric", difficulty: "hard",
    prompt: "If $\\|\\mathbf{u}\\|=3$, $\\|\\mathbf{v}\\|=4$, and the angle between them is $60^\\circ$, find $\\mathbf{u}\\cdot\\mathbf{v}$.",
    answer: "6",
    explanation: "Step 1: $\\mathbf{u}\\cdot\\mathbf{v}=\\|\\mathbf{u}\\|\\|\\mathbf{v}\\|\\cos 60^\\circ = 3\\cdot 4\\cdot 0.5 = 6$. Final answer: $6$." }),
  p({ id: "vec-operations-15", topicId: "vectors", section: "operations", type: "mcq", difficulty: "hard",
    prompt: "A set of vectors $\\{\\mathbf{v}_1,\\ldots,\\mathbf{v}_k\\}$ is linearly independent if and only if:",
    answer: "The only solution to $c_1\\mathbf{v}_1+\\cdots+c_k\\mathbf{v}_k=\\mathbf{0}$ is $c_1=\\cdots=c_k=0$.",
    choices: ["Any one vector can be written as a linear combination of the others.", "The vectors all have unit length.", "The only solution to $c_1\\mathbf{v}_1+\\cdots+c_k\\mathbf{v}_k=\\mathbf{0}$ is $c_1=\\cdots=c_k=0$.", "The vectors are mutually orthogonal."],
    explanation: "Step 1: Linear independence means the only way to produce $\\mathbf{0}$ from the set is the trivial combination (all coefficients zero). Final answer: The only solution to $c_1\\mathbf{v}_1+\\cdots+c_k\\mathbf{v}_k=\\mathbf{0}$ is $c_1=\\cdots=c_k=0$." }),
  p({ id: "vec-projection-9", topicId: "vectors", section: "projection", type: "numeric", difficulty: "hard",
    prompt: "Find the second component of $\\text{proj}_{\\mathbf{a}}\\mathbf{b}$ where $\\mathbf{a}=\\langle 1,2,2\\rangle$ and $\\mathbf{b}=\\langle 3,0,6\\rangle$.",
    answer: "10/3",
    explanation: "Step 1: $\\mathbf{a}\\cdot\\mathbf{b}=3+0+12=15$. Step 2: $\\|\\mathbf{a}\\|^2=1+4+4=9$. Step 3: $\\text{proj}=\\frac{15}{9}\\langle 1,2,2\\rangle=\\langle 5/3,10/3,10/3\\rangle$. Step 4: Second component is $10/3$. Final answer: $10/3$." }),
  p({ id: "vec-dot-14", topicId: "vectors", section: "dot", type: "numeric", difficulty: "hard",
    prompt: "The cross product $\\mathbf{u}\\times\\mathbf{v}$ is defined for vectors in $\\mathbb{R}^3$. For $\\mathbf{u}=\\langle 1,0,0\\rangle$ and $\\mathbf{v}=\\langle 0,1,0\\rangle$, find the third component of $\\mathbf{u}\\times\\mathbf{v}$.",
    answer: "1",
    explanation: "Step 1: $\\mathbf{u}\\times\\mathbf{v}=\\det\\begin{vmatrix}\\mathbf{i}&\\mathbf{j}&\\mathbf{k}\\\\1&0&0\\\\0&1&0\\end{vmatrix}$. Step 2: $=(0-0)\\mathbf{i}-(0-0)\\mathbf{j}+(1-0)\\mathbf{k}=\\langle 0,0,1\\rangle$. Step 3: Third component: $1$. Final answer: $1$." }),
  p({ id: "vec-operations-16", topicId: "vectors", section: "operations", type: "numeric", difficulty: "hard",
    prompt: "Compute $\\|\\mathbf{u}\\times\\mathbf{v}\\|$ for $\\mathbf{u}=\\langle 2,0,0\\rangle$ and $\\mathbf{v}=\\langle 0,3,0\\rangle$.",
    answer: "6",
    explanation: "Step 1: $\\mathbf{u}\\times\\mathbf{v}=\\langle 0,0,6\\rangle$. Step 2: $\\|\\langle 0,0,6\\rangle\\|=6$. Note: $\\|\\mathbf{u}\\times\\mathbf{v}\\|=\\|\\mathbf{u}\\|\\|\\mathbf{v}\\|\\sin\\theta=2\\cdot 3\\cdot 1=6$. Final answer: $6$." }),
  p({ id: "vec-projection-10", topicId: "vectors", section: "projection", type: "numeric", difficulty: "hard",
    prompt: "For $\\mathbf{u}=\\langle 2,1,3\\rangle$ and $\\mathbf{v}=\\langle 1,0,1\\rangle$, find the scalar projection of $\\mathbf{u}$ onto $\\mathbf{v}$.",
    answer: "5/sqrt(2)",
    explanation: "Step 1: $\\mathbf{u}\\cdot\\mathbf{v}=2+0+3=5$. Step 2: $\\|\\mathbf{v}\\|=\\sqrt{2}$. Step 3: Scalar projection $=5/\\sqrt{2}$. Final answer: $5/\\sqrt{2}$." }),
];
