import type { ModuleContent } from "../types";

/**
 * Series & Sequences
 * Extracted from the original monolithic modules.ts
 */
export const seriesModule: ModuleContent = {
    topicId: "series",
    title: "Series & Sequences",
    intro: [
      "Sequences are ordered lists of numbers, and series are their sums. The fundamental question of this entire topic: when you add up infinitely many numbers, can you get a finite answer?",
      "Series are not just theoretical: they underpin how computers calculate $\\sin x$, $e^x$, and $\\ln x$. Taylor series let you approximate any smooth function with a polynomial. Power series extend calculus into the realm of infinite-degree polynomials.",
      "This module covers convergence tests (the toolkit for determining if a series converges), power series, and Taylor/Maclaurin series. Master the tests systematically and you'll always know which tool to reach for.",
    ],
    sections: [
      {
        title: "Sequences and their limits",
        section: "sequences",
        body: [
          "A sequence $\\{a_n\\}$ is an ordered list: $a_1, a_2, a_3, \\ldots$ The sequence converges if $\\lim_{n\\to\\infty} a_n = L$ for some finite $L$. If no such $L$ exists, the sequence diverges.",
          "Common sequences: $a_n = 1/n \\to 0$, $a_n = (1+1/n)^n \\to e$ (the definition of $e$), $a_n = (-1)^n$ diverges (oscillates between $-1$ and $1$, never settling), $a_n = n^2$ diverges to $\\infty$.",
          "Tools for evaluating sequence limits: L'Hôpital's Rule (treat $n$ as a continuous variable and apply to $f(x)$), the Squeeze Theorem (trap the sequence between two that converge to the same limit), and the growth-rate hierarchy: $\\ln n \\ll n^p \\ll a^n \\ll n! \\ll n^n$ for $a > 1$, $p > 0$. This hierarchy means, for example, that $n^{100}/2^n \\to 0$ — any exponential eventually crushes any polynomial.",
          "A sequence is monotonic if it is always increasing ($a_{n+1} \\geq a_n$) or always decreasing ($a_{n+1} \\leq a_n$). A bounded monotonic sequence always converges (Monotone Convergence Theorem). This is useful for proving convergence when you can't find the limit directly.",
          "A sequence is bounded if there exist numbers $m$ and $M$ such that $m \\leq a_n \\leq M$ for all $n$. Bounded alone doesn't guarantee convergence ($(-1)^n$ is bounded but divergent). You need bounded plus monotonic.",
        ],
        eli5: [
          "A sequence is just a list of numbers generated by a pattern. The question is: does the list settle down to a single value as you go further and further? If $a_n = 1/n$, the list is $1, 1/2, 1/3, 1/4, \\ldots$ — it's getting closer and closer to $0$. The limit is $0$.",
          "Some sequences never settle: $(-1)^n$ bounces between $-1$ and $1$ forever. That's divergence. A sequence can also diverge by growing without bound, like $n^2 = 1, 4, 9, 16, \\ldots$",
        ],
      },
      {
        title: "Series: partial sums and convergence",
        section: "partialsums",
        body: [
          "A series $\\sum_{n=1}^{\\infty} a_n$ is the limit of its partial sums: $S_N = \\sum_{n=1}^{N} a_n$. If $\\lim_{N\\to\\infty} S_N$ exists and is finite, the series converges.",
          "Key distinction: a sequence $\\{a_n\\}$ converging to $0$ is necessary for the series to converge, but not sufficient. $a_n = 1/n \\to 0$, yet $\\sum 1/n$ diverges.",
          "The harmonic series $\\sum 1/n$ diverges. This is one of the most important facts in the theory of series. It shows that terms going to zero isn't enough.",
        ],
        eli5: [
          "Imagine stacking blocks. Each block is thinner than the last. The question is: does the tower reach a finite height, or does it grow forever?",
          "If each block is half as thick as the previous one (like $1, 1/2, 1/4, 1/8, \\ldots$), the tower settles at height 2. That's a convergent series. But if each block is $1, 1/2, 1/3, 1/4, \\ldots$ (harmonic series), the blocks get thinner but not fast enough — the tower grows forever, just very slowly.",
          "So 'the pieces get smaller' isn't enough. They have to get smaller fast enough. The convergence tests are all about measuring whether 'fast enough' is satisfied.",
        ],
      },
      {
        title: "Geometric series",
        section: "geometric",
        body: [
          "A geometric series has the form $\\sum_{n=0}^{\\infty} ar^n$ where $a$ is the first term and $r$ is the common ratio.",
          "It converges if and only if $|r| < 1$, and the sum is $\\frac{a}{1-r}$.",
          "Example: $\\sum_{n=0}^{\\infty} \\frac{3}{2^n} = \\frac{3}{1-1/2} = 6$.",
          "This is the only common series where we can easily compute the exact sum. Many convergence tests compare other series to geometric ones.",
        ],
        examples: [
          {
            title: "Summing a geometric series",
            steps: [
              "Compute $\\sum_{n=0}^{\\infty} \\frac{(-1)^n}{4^n}$.",
              "Rewrite: this is $\\sum_{n=0}^{\\infty} \\left(-\\frac{1}{4}\\right)^n$. So $a = 1$ and $r = -1/4$.",
              "Check: $|r| = 1/4 < 1$, so it converges.",
              "Apply the formula: $\\frac{a}{1-r} = \\frac{1}{1-(-1/4)} = \\frac{1}{5/4} = \\frac{4}{5}$.",
              "The sum is $\\frac{4}{5}$. Note: even though terms alternate sign, the geometric series formula handles this perfectly.",
            ],
          },
        ],
      },
      {
        title: "Telescoping series",
        section: "telescoping",
        body: [
          "A telescoping series is one where consecutive terms in the partial sum cancel, leaving only a few surviving terms — like a collapsing telescope.",
          "The classic example: $\\sum_{n=1}^{\\infty} \\frac{1}{n(n+1)}$. Use partial fractions: $\\frac{1}{n(n+1)} = \\frac{1}{n} - \\frac{1}{n+1}$.",
          "Write out the partial sum: $S_N = \\left(1 - \\frac{1}{2}\\right) + \\left(\\frac{1}{2} - \\frac{1}{3}\\right) + \\left(\\frac{1}{3} - \\frac{1}{4}\\right) + \\cdots + \\left(\\frac{1}{N} - \\frac{1}{N+1}\\right)$. Almost everything cancels! What survives: $S_N = 1 - \\frac{1}{N+1}$. As $N \\to \\infty$, $S_N \\to 1$.",
          "To recognize telescoping: use partial fractions to split the general term into a difference $f(n) - f(n+1)$ (or $f(n) - f(n+k)$ for wider telescoping). If consecutive terms cancel, the partial sum collapses to a simple expression.",
          "Telescoping series are one of the few types where you can find the exact sum, not just determine convergence. Always check for this pattern when partial fractions reveal a clean difference.",
        ],
        eli5: [
          "Imagine a row of dominoes where each one knocks down the next, but also picks up the previous one. After all the dominoes have fallen, only the first and last are still standing. That's telescoping — massive cancellation leaves only the endpoints.",
        ],
        examples: [
          {
            title: "Telescoping with a shifted difference",
            steps: [
              "Compute $\\sum_{n=1}^{\\infty} \\frac{1}{n(n+2)}$.",
              "Partial fractions: $\\frac{1}{n(n+2)} = \\frac{1}{2}\\left(\\frac{1}{n} - \\frac{1}{n+2}\\right)$.",
              "This is a 'step-2' telescope. Write out terms: $\\frac{1}{2}\\left[\\left(\\frac{1}{1}-\\frac{1}{3}\\right) + \\left(\\frac{1}{2}-\\frac{1}{4}\\right) + \\left(\\frac{1}{3}-\\frac{1}{5}\\right) + \\left(\\frac{1}{4}-\\frac{1}{6}\\right) + \\cdots\\right]$.",
              "After cancellation, only $\\frac{1}{1}$ and $\\frac{1}{2}$ survive from the positive terms. $S = \\frac{1}{2}\\left(1 + \\frac{1}{2}\\right) = \\frac{3}{4}$.",
            ],
          },
        ],
      },
      {
        title: "The Divergence Test (nth-term test)",
        section: "divergence",
        body: [
          "If $\\lim_{n\\to\\infty} a_n \\neq 0$, then $\\sum a_n$ diverges. Full stop. If the terms don't approach zero, they can't possibly add up to a finite sum — the partial sums keep jumping by non-negligible amounts.",
          "This should always be your first check for any series. It's quick and catches obvious divergence. Example: $\\sum \\frac{n}{n+1}$ diverges because $a_n = \\frac{n}{n+1} \\to 1 \\neq 0$.",
          "Critical limitation: if $\\lim_{n\\to\\infty} a_n = 0$, the test tells you nothing. The series might converge ($\\sum 1/n^2$ converges) or diverge ($\\sum 1/n$ diverges). Terms going to zero is necessary for convergence but not sufficient. You need another test to decide.",
          "Think of this test as a 'quick rejection filter.' It can rule out convergence (if terms don't go to zero), but it can never confirm convergence.",
        ],
        eli5: [
          "If you keep adding amounts that don't shrink to zero, the total will keep growing forever — it can never settle at a finite number. That's the divergence test: 'Are the terms even getting small?' If not, don't bother — the series diverges.",
          "But terms getting small doesn't guarantee the sum is finite. You can add smaller and smaller amounts and still accumulate an infinite total ($1 + 1/2 + 1/3 + 1/4 + \\cdots = \\infty$). So '$a_n \\to 0$' just means 'we need to investigate further.'",
        ],
      },
      {
        title: "p-series and the harmonic series",
        section: "pseries",
        body: [
          "A p-series has the form $\\sum_{n=1}^{\\infty} \\frac{1}{n^p}$ where $p$ is a positive constant. These are the most important benchmark series in all of convergence testing.",
          "The rule: converges if $p > 1$, diverges if $p \\leq 1$. The critical boundary is $p = 1$.",
          "Key examples: $p=1$: the harmonic series $\\sum 1/n$ diverges (this is the most important single fact about series). $p=2$: $\\sum 1/n^2 = \\pi^2/6$ (Euler proved this in 1734 — a celebrated result). $p=1/2$: $\\sum 1/\\sqrt{n}$ diverges (the terms shrink, but too slowly).",
          "Why $p=1$ diverges: group terms in powers of 2. $1 + \\frac{1}{2} + (\\frac{1}{3}+\\frac{1}{4}) + (\\frac{1}{5}+\\frac{1}{6}+\\frac{1}{7}+\\frac{1}{8}) + \\cdots > 1 + \\frac{1}{2} + \\frac{1}{2} + \\frac{1}{2} + \\cdots = \\infty$. Each group contributes at least $1/2$.",
          "p-series serve as the go-to comparison: when you encounter a series with terms that 'look like' $1/n^p$ for large $n$, use the limit comparison test against the appropriate p-series.",
        ],
        eli5: [
          "The harmonic series is the ultimate counterexample in mathematics: the terms $1, 1/2, 1/3, 1/4, \\ldots$ clearly shrink to zero, yet their sum is infinite! It grows incredibly slowly (you need about $e^{10^{43}}$ terms to reach a partial sum of $100$), but it does grow forever. The p-series rule tells you exactly how fast the terms need to shrink: faster than $1/n$ (meaning $p > 1$) to get a finite sum.",
        ],
      },
      {
        title: "The Integral Test",
        section: "integraltest",
        body: [
          "If $f(x)$ is positive, continuous, and decreasing for $x \\geq N$, and $a_n = f(n)$, then $\\sum_{n=N}^{\\infty} a_n$ and $\\int_N^{\\infty} f(x)\\,dx$ either both converge or both diverge. The series and the integral live or die together.",
          "Why it works: the sum $\\sum a_n$ is a left Riemann sum for $\\int f(x)\\,dx$ (or a right Riemann sum, depending on the direction). Since $f$ is decreasing, these Riemann sums sandwich the integral. If one is finite, the other must be too.",
          "The integral test does not give the exact sum — just convergence or divergence. The integral's value is related to but not equal to the series sum.",
          "Example: does $\\sum_{n=2}^{\\infty} \\frac{1}{n(\\ln n)^2}$ converge? Let $f(x) = \\frac{1}{x(\\ln x)^2}$. It's positive, continuous, and decreasing for $x \\geq 2$. $\\int_2^\\infty \\frac{1}{x(\\ln x)^2}\\,dx$: substitute $u = \\ln x$, giving $\\int_{\\ln 2}^{\\infty} u^{-2}\\,du = \\frac{1}{\\ln 2}$. The integral converges, so the series converges.",
          "Remainder estimate: $\\int_{N+1}^{\\infty} f(x)\\,dx \\leq R_N \\leq \\int_N^{\\infty} f(x)\\,dx$ where $R_N = \\sum_{n=N+1}^{\\infty} a_n$ is the error from truncating at $N$ terms. This gives concrete error bounds.",
        ],
        eli5: [
          "Drawing rectangles under a curve approximates the area (integral). Each rectangle's height is $a_n = f(n)$, and its width is $1$. Since the function is decreasing, the rectangles' total area is close to the integral's area. If the area under the infinite curve is finite, the total rectangle area is finite too — and vice versa.",
        ],
      },
      {
        title: "Comparison and Limit Comparison Tests",
        section: "comparison",
        body: [
          "Direct comparison: if $0 \\leq a_n \\leq b_n$ for all sufficiently large $n$ and $\\sum b_n$ converges, then $\\sum a_n$ converges (a smaller series is forced to converge if a larger one does). Conversely, if $\\sum a_n$ diverges, then $\\sum b_n$ diverges.",
          "Direct comparison requires an inequality that holds term by term. This can be tricky to establish. The limit comparison test removes that difficulty.",
          "Limit comparison: if $\\lim_{n\\to\\infty} a_n / b_n = L$ where $0 < L < \\infty$, then $\\sum a_n$ and $\\sum b_n$ either both converge or both diverge. The series behave the same because their terms are proportional for large $n$.",
          "Strategy: look at your series for large $n$ and simplify by dropping lower-order terms. $\\frac{n}{n^3+1}$ behaves like $\\frac{n}{n^3} = \\frac{1}{n^2}$ for large $n$. Use $b_n = 1/n^2$ in the limit comparison test. Since $\\sum 1/n^2$ converges ($p = 2 > 1$), the original series converges.",
          "Choosing $b_n$: almost always a p-series or geometric series. Keep only the highest-power terms in the numerator and denominator, cancel, and you'll get $b_n = 1/n^p$ for some $p$. Then the p-series rule tells you the answer.",
        ],
        eli5: [
          "Direct comparison: 'I earn less than my neighbor, and my neighbor can afford rent, so I can too.' (If a bigger series converges, a smaller one must as well.)",
          "Limit comparison: 'For large $n$, my series and a known series look practically the same — they differ by just a constant multiple. So if one converges, the other must too.' You're comparing behavior, not individual terms.",
        ],
      },
      {
        title: "Ratio and Root Tests",
        section: "ratioroot",
        body: [
          "Ratio test: compute $L = \\lim_{n\\to\\infty} \\left|\\frac{a_{n+1}}{a_n}\\right|$. If $L < 1$: converges absolutely. $L > 1$: diverges. $L = 1$: inconclusive.",
          "Root test: compute $L = \\lim_{n\\to\\infty} \\sqrt[n]{|a_n|}$. Same criteria as the ratio test.",
          "The ratio test excels for series with factorials (like $n!/3^n$) or products. The root test is ideal for terms raised to the $n$th power (like $(2/3)^n$).",
          "Warning: both tests are inconclusive when $L=1$. This happens for all p-series, so you can't use ratio/root tests on $\\sum 1/n^p$.",
        ],
        examples: [
          {
            title: "Ratio test on a factorial series",
            steps: [
              "Does $\\sum_{n=1}^{\\infty} \\frac{n!}{3^n}$ converge or diverge?",
              "Use the ratio test. Compute $\\frac{a_{n+1}}{a_n} = \\frac{(n+1)!}{3^{n+1}} \\cdot \\frac{3^n}{n!}$.",
              "Simplify: $(n+1)!/n! = n+1$ and $3^n/3^{n+1} = 1/3$.",
              "So $\\frac{a_{n+1}}{a_n} = \\frac{n+1}{3}$.",
              "Take the limit: $L = \\lim_{n\\to\\infty} \\frac{n+1}{3} = \\infty$.",
              "Since $L > 1$ (in fact $L = \\infty$), the series diverges. The factorial grows so much faster than $3^n$ that the terms blow up.",
            ],
          },
        ],
      },
      {
        title: "Alternating Series Test",
        section: "alternating",
        body: [
          "An alternating series has terms that switch sign: $\\sum (-1)^n a_n$ or $\\sum (-1)^{n+1} a_n$ where $a_n > 0$. The positive and negative terms partially cancel each other.",
          "The Alternating Series Test (Leibniz's test): the series converges if two conditions hold: (1) $\\{a_n\\}$ is eventually decreasing ($a_{n+1} \\leq a_n$ for large enough $n$), and (2) $\\lim_{n\\to\\infty} a_n = 0$.",
          "Example: the alternating harmonic series $\\sum_{n=1}^{\\infty} \\frac{(-1)^{n+1}}{n} = 1 - 1/2 + 1/3 - 1/4 + \\cdots = \\ln 2$. The regular harmonic series diverges, but the alternation saves it — the positive and negative terms cancel just enough to give a finite sum.",
          "Alternating series estimation theorem: the error from truncating after $N$ terms satisfies $|R_N| \\leq a_{N+1}$ (the first omitted term). This is an exceptionally convenient error bound — you know exactly how accurate your partial sum is. If $a_{N+1} = 0.001$, your approximation is within $0.001$ of the true sum.",
          "This estimation theorem is why alternating series are 'friendly' — they come with a built-in accuracy guarantee, unlike most other convergent series.",
        ],
        eli5: [
          "An alternating series is like a pendulum. First you overshoot (positive), then you overcorrect (negative), then you overshoot again, but less. Each swing is smaller than the last. As long as the swings shrink to zero, the pendulum settles — the series converges.",
          "The error bound says: the pendulum is never more than one swing away from its final resting place. So after $N$ swings, the farthest you could be off is the size of the next swing ($a_{N+1}$).",
        ],
      },
      {
        title: "Absolute vs. conditional convergence",
        section: "absconv",
        body: [
          "A series $\\sum a_n$ converges absolutely if $\\sum |a_n|$ converges. It converges conditionally if $\\sum a_n$ converges but $\\sum |a_n|$ diverges.",
          "Absolute convergence implies convergence. So if the absolute value series converges, you're done.",
          "Example: $\\sum (-1)^n/n^2$ converges absolutely because $\\sum 1/n^2$ converges.",
          "Example: $\\sum (-1)^n/n$ converges conditionally. It converges by the alternating series test, but $\\sum 1/n$ diverges.",
          "Why it matters: absolutely convergent series can be rearranged freely without changing the sum. Conditionally convergent series cannot (Riemann rearrangement theorem).",
        ],
        eli5: [
          "Think of absolute convergence like having money in the bank. Even if some terms are positive and some are negative, if the total amount of money moving around (ignoring direction) is finite, you're safe. The sum is solid and reliable.",
          "Conditional convergence is like balancing on a tightrope. The positive and negative terms cancel each other out just right to give a finite sum, but it's fragile. If you rearrange the order you add them, you can get a completely different answer (or no answer at all). It only works because of the specific order.",
        ],
      },
      {
        title: "Power series",
        section: "power",
        body: [
          "A power series centered at $a$ is $\\sum_{n=0}^{\\infty} c_n(x-a)^n = c_0 + c_1(x-a) + c_2(x-a)^2 + \\cdots$. It's an 'infinite polynomial' with infinitely many terms.",
          "The radius of convergence $R$ determines where it converges: $|x-a| < R$ (converges absolutely), $|x-a| > R$ (diverges). At $|x-a| = R$ (the endpoints), you must check separately — the series may converge at one, both, or neither endpoint.",
          "Three possible scenarios: $R = 0$ (converges only at $x = a$), $0 < R < \\infty$ (converges on a finite interval), or $R = \\infty$ (converges for all $x$, like the series for $e^x$).",
          "Find $R$ using the ratio test: $R = \\lim_{n\\to\\infty} \\left|\\frac{c_n}{c_{n+1}}\\right|$ (or equivalently, $1/R = \\lim_{n\\to\\infty}|c_{n+1}/c_n|$). The root test also works: $1/R = \\limsup_{n\\to\\infty} |c_n|^{1/n}$.",
          "Inside the radius, power series behave like polynomials: you can differentiate and integrate them term by term, and the radius of convergence stays the same (endpoints may change).",
          "The simplest power series: $\\frac{1}{1-x} = \\sum_{n=0}^{\\infty} x^n$ for $|x| < 1$ ($R = 1$). From this, many other series can be derived by substitution, differentiation, or integration.",
        ],
        eli5: [
          "A power series is like a polynomial that never ends. Regular polynomials have a fixed number of terms. Power series keep going: $c_0 + c_1 x + c_2 x^2 + c_3 x^3 + \\cdots$. The question is: for which values of $x$ does this infinite sum make sense (converge)?",
          "The radius of convergence is the 'safe zone.' Inside the radius, the terms shrink fast enough to give a finite sum. Outside, they blow up. At the boundary, it's a coin flip — you have to check by hand.",
        ],
      },
      {
        title: "Taylor and Maclaurin series",
        section: "taylor",
        body: [
          "The Taylor series of $f(x)$ centered at $a$ is: $f(x) = \\sum_{n=0}^{\\infty} \\frac{f^{(n)}(a)}{n!}(x-a)^n$.",
          "A Maclaurin series is a Taylor series centered at $a=0$.",
          "Essential Maclaurin series to memorize:",
          "$e^x = \\sum_{n=0}^{\\infty} \\frac{x^n}{n!} = 1 + x + \\frac{x^2}{2!} + \\frac{x^3}{3!} + \\cdots$ for all $x$.",
          "$\\sin x = \\sum_{n=0}^{\\infty} \\frac{(-1)^n x^{2n+1}}{(2n+1)!} = x - \\frac{x^3}{3!} + \\frac{x^5}{5!} - \\cdots$ for all $x$.",
          "$\\cos x = \\sum_{n=0}^{\\infty} \\frac{(-1)^n x^{2n}}{(2n)!} = 1 - \\frac{x^2}{2!} + \\frac{x^4}{4!} - \\cdots$ for all $x$.",
          "$\\ln(1+x) = \\sum_{n=1}^{\\infty} \\frac{(-1)^{n+1} x^n}{n} = x - \\frac{x^2}{2} + \\frac{x^3}{3} - \\cdots$ for $-1 < x \\leq 1$.",
          "$\\frac{1}{1-x} = \\sum_{n=0}^{\\infty} x^n$ for $|x| < 1$.",
        ],
        eli5: [
          "A Taylor series is like building a copy of a function out of simple polynomial building blocks ($1, x, x^2, x^3, \\ldots$).",
          "Imagine you want to recreate a complicated curve. First, you match the value at one point (constant term). Then you match the slope (linear term). Then the curvature ($x^2$ term). Each new term makes your copy more accurate, like adding more detail to a sketch.",
          "With enough terms, your polynomial copy becomes indistinguishable from the original function. That's how your calculator computes $\\sin(0.5)$ — it's not drawing a circle, it's evaluating a polynomial like $0.5 - 0.5^3/6 + 0.5^5/120 - \\cdots$ that happens to equal $\\sin(0.5)$ to many decimal places.",
        ],
        examples: [
          {
            title: "Computing a Taylor series from scratch",
            steps: [
              "Find the Maclaurin series for $f(x) = e^x$ (centered at $a = 0$).",
              "We need $f^{(n)}(0)$ for each $n$. Since $\\frac{d}{dx}e^x = e^x$, every derivative of $e^x$ is $e^x$.",
              "So $f(0) = 1$, $f'(0) = 1$, $f''(0) = 1$, $f'''(0) = 1$, and so on. Every derivative at $0$ equals $1$.",
              "Plug into the Taylor formula: $e^x = \\sum_{n=0}^{\\infty} \\frac{f^{(n)}(0)}{n!} x^n = \\sum_{n=0}^{\\infty} \\frac{x^n}{n!}$.",
              "Written out: $e^x = 1 + x + \\frac{x^2}{2} + \\frac{x^3}{6} + \\frac{x^4}{24} + \\cdots$",
              "This converges for all $x$. For example, $e^1 \\approx 1 + 1 + 0.5 + 0.167 + 0.042 + 0.008 + \\cdots \\approx 2.718$.",
            ],
          },
          {
            title: "Deriving a series by substitution",
            steps: [
              "Find the Maclaurin series for $e^{-x^2}$.",
              "Instead of computing derivatives (which get very messy), use the known series for $e^x$ and substitute $-x^2$ for $x$.",
              "We know: $e^x = \\sum_{n=0}^{\\infty} \\frac{x^n}{n!}$.",
              "Replace $x$ with $-x^2$: $e^{-x^2} = \\sum_{n=0}^{\\infty} \\frac{(-x^2)^n}{n!} = \\sum_{n=0}^{\\infty} \\frac{(-1)^n x^{2n}}{n!}$.",
              "Written out: $e^{-x^2} = 1 - x^2 + \\frac{x^4}{2} - \\frac{x^6}{6} + \\cdots$",
              "This is the Gaussian function used in probability and statistics. Its integral $\\int_0^\\infty e^{-x^2}dx = \\frac{\\sqrt{\\pi}}{2}$ has no closed form — but we can integrate the series term by term!",
            ],
          },
        ],
      },
      {
        title: "Taylor remainder and error bounds",
        section: "remainder",
        body: [
          "The $n$th degree Taylor polynomial $T_n(x)$ approximates $f(x)$ near $x = a$. The error (remainder) is $R_n(x) = f(x) - T_n(x)$ — the difference between the true function and the polynomial approximation.",
          "Taylor's inequality (Lagrange error bound): $|R_n(x)| \\leq \\frac{M}{(n+1)!}|x-a|^{n+1}$, where $M$ is an upper bound for $|f^{(n+1)}(t)|$ on the interval between $a$ and $x$. The $(n+1)!$ in the denominator grows extremely fast, which is why Taylor polynomials get accurate quickly.",
          "For alternating Taylor series (like $\\sin x$, $\\cos x$, $\\ln(1+x)$), the alternating series estimation applies: $|R_n| \\leq |a_{n+1}|$ (the first omitted term). This is usually easier to use than the Lagrange bound.",
          "Practical use: 'How many terms of the Maclaurin series for $e^x$ do I need to approximate $e^{0.5}$ to within $0.0001$?' Find the smallest $n$ such that $\\frac{(0.5)^{n+1}}{(n+1)!} < 0.0001$. With $n = 5$: $\\frac{0.5^6}{720} \\approx 0.0000217 < 0.0001$. So 6 terms suffice (through the $x^5$ term).",
          "This is how calculators and computers evaluate functions like $\\sin$, $\\cos$, and $e^x$ — they use Taylor polynomials with enough terms to guarantee the desired precision.",
        ],
        eli5: [
          "When you approximate a function with a Taylor polynomial, you're sketching it with a limited number of pencil strokes. The error bound tells you: 'your sketch is at most this far from the real thing.' Add more terms (more pencil strokes), and the bound shrinks — your sketch gets closer to the original.",
          "The $(n+1)!$ in the denominator is your best friend here. Factorials grow so fast that even a few extra terms dramatically improve accuracy. That's why Taylor series work so well in practice.",
        ],
      },
      {
        title: "Building new series from known ones",
        section: "building",
        body: [
          "Instead of computing Taylor coefficients from scratch (which requires evaluating $n$ derivatives), you can derive new series from known ones using three operations: substitution, differentiation, and integration.",
          "Substitution: replace $x$ in a known series with an expression. $e^{-x^2}$? Start with $e^u = \\sum u^n/n!$ and substitute $u = -x^2$: $e^{-x^2} = \\sum \\frac{(-1)^n x^{2n}}{n!}$. No derivatives needed.",
          "Term-by-term differentiation: differentiate a known series to get a new one. $\\frac{1}{1-x} = \\sum x^n$ for $|x|<1$. Differentiate both sides: $\\frac{1}{(1-x)^2} = \\sum n x^{n-1}$. The radius of convergence is preserved.",
          "Term-by-term integration: integrate a known series. $\\frac{1}{1+t^2} = \\sum (-1)^n t^{2n}$ for $|t|<1$. Integrate from $0$ to $x$: $\\arctan x = \\sum \\frac{(-1)^n x^{2n+1}}{2n+1}$. This gives the series for $\\arctan$ without ever differentiating $\\arctan$.",
          "Multiplication and addition: you can add or multiply series. $\\frac{x}{1-x^2} = x \\cdot \\frac{1}{1-x^2} = x \\sum x^{2n} = \\sum x^{2n+1}$.",
          "These techniques are immensely powerful. In practice, almost every Taylor series you encounter can be derived from the five basic series ($e^x$, $\\sin x$, $\\cos x$, $\\ln(1+x)$, $1/(1-x)$) using these operations.",
        ],
        eli5: [
          "You've memorized five basic series. From those five, you can build hundreds of others — just by plugging in different expressions, differentiating, or integrating. It's like having five LEGO base plates and building anything on top of them.",
        ],
      },
      {
        title: "Choosing the right convergence test (strategy)",
        section: "strategy",
        body: [
          "1. Divergence test first: if $a_n \\not\\to 0$, done (diverges).",
          "2. Is it geometric? Check if $a_n = ar^n$.",
          "3. Is it a p-series? Check if $a_n = 1/n^p$.",
          "4. Does it telescope? Try partial fractions.",
          "5. Are there factorials or $n$th powers? Try ratio or root test.",
          "6. Does it look like a known series? Try comparison or limit comparison.",
          "7. Is it alternating? Try the alternating series test.",
          "8. Is $f(n) = a_n$ easy to integrate? Try the integral test.",
        ],
      },
    ],
    examples: [],
    commonMistakes: [
      "Using the divergence test to 'prove' convergence. If $a_n \\to 0$, the test tells you nothing. It can only prove divergence.",
      "Applying the ratio or root test to a p-series. These tests always give $L = 1$ (inconclusive) for $\\sum 1/n^p$.",
      "Forgetting to check the endpoints of a power series interval. The series may converge at one endpoint, both, or neither.",
      "Confusing absolute and conditional convergence. Absolute convergence ($\\sum |a_n|$ converges) is strictly stronger than conditional convergence.",
      "Computing Taylor coefficients incorrectly: the $n$th coefficient is $\\frac{f^{(n)}(a)}{n!}$, not $f^{(n)}(a)$. Don't forget the $n!$ in the denominator.",
      "Trying to determine the sum of a series when the question only asks about convergence. Most convergent series don't have nice closed-form sums.",
      "Not simplifying before choosing a test. Algebra can often reveal the right comparison or simplify the ratio test calculation.",
    ],
  };
