import type { SubjectSpec } from "../seed-tier1-diagnostics-types";

function link(label: string, href: string) {
  return { label, href };
}

export const ABSTRACT_ALGEBRA: SubjectSpec = {
  slug: "abstract-algebra",
  idPrefix: "aa-diag-",
  prerequisites: [
    {
      id: "algebra-manipulation",
      slug: "alg",
      label: "Algebra manipulation",
      description:
        "Manipulate polynomials, factor expressions, and work with symbolic algebra used in ring theory.",
      reviewLinks: [
        link("Polynomials & factoring", "/algebra/modules/polynomials-factoring"),
        link("Polynomial rings", "/abstract-algebra/modules/polynomial-rings"),
      ],
      questions: [
        { prompt: "Expand $(x+2)(x+3)$.", type: "numeric", answer: "x^2+5x+6", explanation: "FOIL gives $x^2+5x+6$.", difficulty: "easy" },
        { prompt: "Factor $x^2-16$.", type: "mcq", answer: "$(x-4)(x+4)$", choices: ["$(x-4)(x+4)$", "$(x-8)^2$", "$(x-4)^2$", "$x(x-16)$"], explanation: "Difference of squares.", difficulty: "easy" },
        { prompt: "Solve $2x+3=11$.", type: "numeric", answer: "4", explanation: "$2x=8$, $x=4$.", difficulty: "easy" },
        { prompt: "Simplify $\\frac{x^2-1}{x-1}$ for $x\\ne 1$.", type: "numeric", answer: "x+1", explanation: "Factor and cancel.", difficulty: "easy" },
        { prompt: "Compute $(x^2+1)-(x^2-1)$.", type: "numeric", answer: "2", explanation: "Subtract: $2$.", difficulty: "easy" },
        { prompt: "In $\\mathbb{Z}$, is $6$ divisible by $3$?", type: "mcq", answer: "Yes", choices: ["Yes", "No", "Only in $\\mathbb{R}$", "Undefined"], explanation: "$6=2\\cdot 3$.", difficulty: "medium" },
        { prompt: "How many roots does $x^2+1$ have in $\\mathbb{R}$?", type: "numeric", answer: "0", explanation: "No real roots.", difficulty: "medium" },
        { prompt: "Is $x^2+1$ irreducible over $\\mathbb{R}$?", type: "mcq", answer: "Yes", choices: ["Yes", "No", "Only if $x=0$", "Cannot tell"], explanation: "No real factorization.", difficulty: "medium" },
        { prompt: "Compute the remainder when $x^3-1$ is divided by $x-1$.", type: "numeric", answer: "0", explanation: "$x=1$ is a root.", difficulty: "medium" },
        { prompt: "How many elements in $\\mathbb{Z}_{12}$?", type: "numeric", answer: "12", explanation: "Residue classes mod $12$.", difficulty: "medium" },
        { prompt: "In $\\mathbb{Z}_5$, what is $3+4$?", type: "numeric", answer: "2", explanation: "$7\\equiv 2\\pmod 5$.", difficulty: "medium" },
        { prompt: "Which set is closed under addition?", type: "mcq", answer: "$\\mathbb{Z}$", choices: ["Positive reals only", "$\\mathbb{Z}$", "Odd integers only", "Prime numbers"], explanation: "Sum of integers is an integer.", difficulty: "medium" },
        { prompt: "Degree of $3x^4-2x+7$ is:", type: "numeric", answer: "4", explanation: "Highest power is $4$.", difficulty: "medium" },
        { prompt: "In $F[x]$, if $\\deg f=2$ and $\\deg g=3$, then $\\deg(fg)=$", type: "numeric", answer: "5", explanation: "Degrees add for nonzero polynomials.", difficulty: "hard" },
        { prompt: "Is $\\mathbb{Z}$ a field?", type: "mcq", answer: "No", choices: ["Yes", "No", "Only for addition", "Only for multiplication"], explanation: "Most integers lack multiplicative inverses.", difficulty: "hard" },
        { prompt: "If $a\\equiv b\\pmod n$, then $a-b$ is:", type: "mcq", answer: "Divisible by $n$", choices: ["Prime", "Divisible by $n$", "Always $1$", "Always $0$ in $\\mathbb{Z}$"], explanation: "Definition of congruence.", difficulty: "hard" },
      ],
    },
    {
      id: "matrix-basics",
      slug: "mat",
      label: "Matrix basics",
      description:
        "Read matrix dimensions, perform row operations, and connect matrices to linear systems.",
      reviewLinks: [
        link("Matrix algebra", "/linear-algebra/modules/matrices"),
        link("Systems of equations", "/linear-algebra/modules/systems"),
      ],
      questions: [
        { prompt: "What are the dimensions of a $2\\times 3$ matrix?", type: "mcq", answer: "$2$ rows, $3$ columns", choices: ["$3$ rows, $2$ columns", "$2$ rows, $3$ columns", "$6$ rows, $1$ column", "$2+3=5$ entries only"], explanation: "Rows $\\times$ columns.", difficulty: "easy" },
        { prompt: "Compute $\\begin{pmatrix}1&2\\\\0&1\\end{pmatrix}+\\begin{pmatrix}0&1\\\\1&0\\end{pmatrix}$ entry $(1,2)$.", type: "numeric", answer: "3", explanation: "$2+1=3$.", difficulty: "easy" },
        { prompt: "If $A$ is $2\\times 3$ and $B$ is $3\\times 4$, what size is $AB$?", type: "mcq", answer: "$2\\times 4$", choices: ["$3\\times 3$", "$2\\times 4$", "$2\\times 3$", "Undefined"], explanation: "Inner dimensions must match.", difficulty: "easy" },
        { prompt: "Identity matrix $I_2$ has diagonal entries:", type: "numeric", answer: "1", explanation: "Ones on the diagonal.", difficulty: "easy" },
        { prompt: "Elementary row operation: swap two rows.", type: "mcq", answer: "Preserves solution set of $Ax=b$", choices: ["Changes solutions randomly", "Preserves solution set of $Ax=b$", "Always makes system inconsistent", "Only for square matrices"], explanation: "Row swaps are equivalence operations.", difficulty: "easy" },
        { prompt: "Solve by matrix thinking: $x+y=3$, $x-y=1$. Find $x$.", type: "numeric", answer: "2", explanation: "Add equations: $2x=4$.", difficulty: "medium" },
        { prompt: "A matrix in reduced row echelon form has leading entries:", type: "mcq", answer: "$1$", choices: ["$0$", "$1$", "Any nonzero number", "Always $2$"], explanation: "Leading coefficients are normalized to $1$.", difficulty: "medium" },
        { prompt: "If $A=\\begin{pmatrix}1&0\\\\0&2\\end{pmatrix}$, find $(A^{-1})_{22}$.", type: "numeric", answer: "1/2", explanation: "Invert diagonal entries.", difficulty: "medium" },
        { prompt: "How many pivots can a $3\\times 4$ augmented matrix have at most?", type: "numeric", answer: "3", explanation: "At most one per row.", difficulty: "medium" },
        { prompt: "If $\\det(A)=0$ for square $A$, then $A$ is:", type: "mcq", answer: "Not invertible", choices: ["Always invertible", "Not invertible", "Always identity", "Orthogonal"], explanation: "Zero determinant means singular.", difficulty: "medium" },
        { prompt: "Transpose of $\\begin{pmatrix}1&2&3\\end{pmatrix}$ is:", type: "mcq", answer: "$\\begin{pmatrix}1\\\\2\\\\3\\end{pmatrix}$", choices: ["Same row", "$\\begin{pmatrix}1\\\\2\\\\3\\end{pmatrix}$", "$\\begin{pmatrix}3&2&1\\end{pmatrix}$", "Undefined"], explanation: "Rows become columns.", difficulty: "medium" },
        { prompt: "If $Ax=0$ has only $x=0$, columns of $A$ are:", type: "mcq", answer: "Linearly independent", choices: ["Linearly dependent", "Linearly independent", "Always zero", "Always infinite"], explanation: "Trivial null space means independence.", difficulty: "medium" },
        { prompt: "Rank of $\\begin{pmatrix}1&2\\\\2&4\\end{pmatrix}$ is:", type: "numeric", answer: "1", explanation: "Second row is multiple of first.", difficulty: "hard" },
        { prompt: "Adding a multiple of one row to another:", type: "mcq", answer: "Is an elementary row operation", choices: ["Changes rank always", "Is an elementary row operation", "Only for determinants", "Invalid"], explanation: "Type III elementary operation.", difficulty: "hard" },
        { prompt: "For $2\\times 2$ system with infinite solutions, RREF has:", type: "mcq", answer: "A free variable", choices: ["No pivots", "A free variable", "Two pivots in one column", "Identity block"], explanation: "Fewer pivots than variables.", difficulty: "hard" },
        { prompt: "If $A$ is invertible, $\\det(A^{-1})=$", type: "mcq", answer: "$1/\\det(A)$", choices: ["$\\det(A)$", "$1/\\det(A)$", "$0$", "$-\\det(A)$"], explanation: "Determinant of inverse.", difficulty: "hard" },
      ],
    },
    {
      id: "vector-spaces",
      slug: "vec",
      label: "Vector spaces",
      description:
        "Work with vectors, linear combinations, span, independence, basis, and dimension.",
      reviewLinks: [
        link("Vectors", "/linear-algebra/modules/vectors"),
        link("Vector spaces", "/linear-algebra/modules/spaces"),
      ],
      questions: [
        { prompt: "Compute $(1,2)+(3,4)$.", type: "mcq", answer: "$(4,6)$", choices: ["$(4,6)$", "$(2,6)$", "$(3,6)$", "$(4,8)$"], explanation: "Add componentwise.", difficulty: "easy" },
        { prompt: "Compute $3(1,-1)$.", type: "mcq", answer: "$(3,-3)$", choices: ["$(3,-3)$", "$(1,-3)$", "$(4,-1)$", "$(3,1)$"], explanation: "Scale each component.", difficulty: "easy" },
        { prompt: "Is $(2,4)$ a scalar multiple of $(1,2)$?", type: "mcq", answer: "Yes", choices: ["Yes", "No", "Only in $\\mathbb{R}^3$", "Cannot tell"], explanation: "$(2,4)=2(1,2)$.", difficulty: "easy" },
        { prompt: "The zero vector in $\\mathbb{R}^2$ is:", type: "mcq", answer: "$(0,0)$", choices: ["$(1,1)$", "$(0,0)$", "$(0,1)$", "No zero vector"], explanation: "Additive identity.", difficulty: "easy" },
        { prompt: "Are $(1,0)$ and $(0,1)$ linearly independent in $\\mathbb{R}^2$?", type: "mcq", answer: "Yes", choices: ["Yes", "No", "Only if orthogonal", "Only in $\\mathbb{R}^3$"], explanation: "Neither is a multiple of the other.", difficulty: "easy" },
        { prompt: "Span of $(1,0)$ in $\\mathbb{R}^2$ is:", type: "mcq", answer: "The $x$-axis", choices: ["All of $\\mathbb{R}^2$", "The $x$-axis", "A single point", "The $y$-axis"], explanation: "All multiples of $(1,0)$.", difficulty: "medium" },
        { prompt: "Dimension of $\\mathbb{R}^3$ is:", type: "numeric", answer: "3", explanation: "Standard basis has three vectors.", difficulty: "medium" },
        { prompt: "If $v_1,v_2$ span a plane in $\\mathbb{R}^3$, they are:", type: "mcq", answer: "Linearly independent (if plane is 2D)", choices: ["Always dependent", "Linearly independent (if plane is 2D)", "Always zero", "Always three vectors needed"], explanation: "Two independent vectors span a 2D subspace.", difficulty: "medium" },
        { prompt: "Is $(1,1)$ in span$\\{(1,0),(0,1)\\}$?", type: "mcq", answer: "Yes", choices: ["Yes", "No", "Only with negatives", "Only in $\\mathbb{R}^1$"], explanation: "$(1,1)=(1,0)+(0,1)$.", difficulty: "medium" },
        { prompt: "A subspace must contain:", type: "mcq", answer: "The zero vector", choices: ["Only unit vectors", "The zero vector", "No zero vector", "Only basis vectors"], explanation: "Subspaces are closed and contain $0$.", difficulty: "medium" },
        { prompt: "If $\\{v_1,v_2,v_3\\}$ is a basis of $\\mathbb{R}^3$, how many vectors?", type: "numeric", answer: "3", explanation: "Basis size equals dimension.", difficulty: "medium" },
        { prompt: "Rank-nullity for $A$ with $3$ columns and nullity $1$ gives rank:", type: "numeric", answer: "2", explanation: "rank + nullity = number of columns.", difficulty: "medium" },
        { prompt: "Are $(1,2,3)$ and $(2,4,6)$ linearly dependent?", type: "mcq", answer: "Yes", choices: ["Yes", "No", "Independent", "Orthogonal only"], explanation: "Second is $2$ times the first.", difficulty: "medium" },
        { prompt: "If $W$ is a subspace of $V$, then $0\\in W$ because:", type: "mcq", answer: "Subspaces are closed under addition and scalar multiplication", choices: ["Definition of vector", "Subspaces are closed under addition and scalar multiplication", "Basis includes zero", "Always false"], explanation: "$0=0\\cdot v$.", difficulty: "hard" },
        { prompt: "Maximal number of independent vectors in $\\mathbb{R}^n$ is:", type: "numeric", answer: "n", explanation: "Dimension bound.", difficulty: "hard" },
        { prompt: "If $S$ spans $V$ and contains a basis, $|S|$ is at least:", type: "mcq", answer: "$\\dim V$", choices: ["$0$", "$\\dim V$", "$2\\dim V$", "$\\dim V-1$ always"], explanation: "Spanning set size lower bound.", difficulty: "hard" },
      ],
    },
    {
      id: "linear-transformations",
      slug: "lin",
      label: "Linear transformations",
      description:
        "Recognize linear maps, matrix representations, kernels, images, and eigenvalues.",
      reviewLinks: [
        link("Eigenvalues", "/linear-algebra/modules/eigenvalues"),
        link("Group homomorphisms", "/abstract-algebra/modules/group-homomorphisms"),
      ],
      questions: [
        { prompt: "A map $T:V\\to W$ is linear if $T(u+v)=T(u)+T(v)$ and:", type: "mcq", answer: "$T(cv)=cT(v)$", choices: ["$T(0)=1$", "$T(cv)=cT(v)$", "$T(u)=T(v)$ always", "$T$ is injective"], explanation: "Linearity requires both additivity and homogeneity.", difficulty: "easy" },
        { prompt: "Must every linear map satisfy $T(0)=0$?", type: "mcq", answer: "Yes", choices: ["Yes", "No", "Only if surjective", "Only in finite dimension"], explanation: "$T(0)=T(0\\cdot 0)=0\\cdot T(0)=0$.", difficulty: "easy" },
        { prompt: "Matrix of rotation by $90^\\circ$ in $\\mathbb{R}^2$ has determinant:", type: "numeric", answer: "1", explanation: "Rotation preserves area.", difficulty: "easy" },
        { prompt: "If $T(x)=2x$ on $\\mathbb{R}$, then $T$ is:", type: "mcq", answer: "Linear", choices: ["Linear", "Not linear", "Only affine", "Constant"], explanation: "Scaling is linear.", difficulty: "easy" },
        { prompt: "Kernel of $T$ is the set of vectors with:", type: "mcq", answer: "$T(v)=0$", choices: ["$T(v)=1$", "$T(v)=0$", "$T(v)=v$", "$T(v)$ maximal"], explanation: "Kernel is preimage of zero.", difficulty: "easy" },
        { prompt: "If $A=\\begin{pmatrix}1&0\\\\0&0\\end{pmatrix}$, rank of $A$ is:", type: "numeric", answer: "1", explanation: "One pivot.", difficulty: "medium" },
        { prompt: "Eigenvalue $\\lambda$ satisfies:", type: "mcq", answer: "$Av=\\lambda v$ for some nonzero $v$", choices: ["$Av=0$ always", "$Av=\\lambda v$ for some nonzero $v$", "$\\det A=\\lambda$", "$A=\\lambda I$"], explanation: "Eigenvector equation.", difficulty: "medium" },
        { prompt: "For $A=\\begin{pmatrix}2&0\\\\0&3\\end{pmatrix}$, eigenvalues are:", type: "mcq", answer: "$2$ and $3$", choices: ["$0$ and $5$", "$2$ and $3$", "$1$ and $1$", "None"], explanation: "Diagonal entries for diagonal matrix.", difficulty: "medium" },
        { prompt: "Image of $T$ is:", type: "mcq", answer: "Set of all outputs $T(v)$", choices: ["Kernel", "Set of all outputs $T(v)$", "Domain only", "Zero vector only"], explanation: "Image = range.", difficulty: "medium" },
        { prompt: "If $T:\\mathbb{R}^2\\to\\mathbb{R}^2$ projects onto $x$-axis, nullity is:", type: "numeric", answer: "1", explanation: "Kernel is $y$-axis, dimension $1$.", difficulty: "medium" },
        { prompt: "Composition of linear maps is:", type: "mcq", answer: "Linear", choices: ["Always nonlinear", "Linear", "Only if invertible", "Only in $\\mathbb{R}^2$"], explanation: "Linearity is preserved under composition.", difficulty: "medium" },
        { prompt: "If $\\ker T=\\{0\\}$, then $T$ is:", type: "mcq", answer: "Injective", choices: ["Surjective", "Injective", "Zero map", "Identity"], explanation: "Trivial kernel means one-to-one.", difficulty: "medium" },
        { prompt: "Trace of $\\begin{pmatrix}1&2\\\\3&4\\end{pmatrix}$ is:", type: "numeric", answer: "5", explanation: "$1+4=5$.", difficulty: "medium" },
        { prompt: "A homomorphism of groups preserves:", type: "mcq", answer: "The group operation", choices: ["Only identity", "The group operation", "Only inverses", "Cardinality only"], explanation: "$\\varphi(ab)=\\varphi(a)\\varphi(b)$.", difficulty: "hard" },
        { prompt: "If $A$ is $n\\times n$ with $n$ distinct eigenvalues, eigenvectors are:", type: "mcq", answer: "Linearly independent", choices: ["Always dependent", "Linearly independent", "Always zero", "Undefined"], explanation: "Distinct eigenvalues give independent eigenvectors.", difficulty: "hard" },
        { prompt: "Dimension theorem: $\\dim V = \\dim\\ker T + $", type: "mcq", answer: "$\\dim\\operatorname{im} T$", choices: ["$\\dim W$ always", "$\\dim\\operatorname{im} T$", "$\\dim\\ker T$ again", "$0$"], explanation: "Rank-nullity for linear maps.", difficulty: "hard" },
      ],
    },
    {
      id: "proof-reasoning",
      slug: "proof",
      label: "Proof maturity",
      description:
        "Understand equivalence relations, induction, and proof techniques used in algebra.",
      reviewLinks: [
        link("Formal systems & proofs", "/mathematical-logic/modules/formal-systems"),
        link("Groups", "/abstract-algebra/modules/groups"),
      ],
      questions: [
        { prompt: "To prove a statement for all $n\\in\\mathbb{N}$, induction needs:", type: "mcq", answer: "Base case and inductive step", choices: ["Only base case", "Base case and inductive step", "Only examples", "Contradiction only"], explanation: "Standard induction template.", difficulty: "easy" },
        { prompt: "An equivalence relation must be reflexive, symmetric, and:", type: "mcq", answer: "Transitive", choices: ["Commutative", "Transitive", "Associative", "Invertible"], explanation: "Three defining properties.", difficulty: "easy" },
        { prompt: "Cosets of a subgroup partition the group because equivalence $a\\sim b$ iff $a^{-1}b\\in H$ is:", type: "mcq", answer: "An equivalence relation", choices: ["Always false", "An equivalence relation", "Only for abelian groups", "Only for finite groups"], explanation: "Subgroup cosets form a partition.", difficulty: "easy" },
        { prompt: "If $G$ is a group, the identity element is:", type: "mcq", answer: "Unique", choices: ["Not unique", "Unique", "Always $0$", "Always $1$ only in rings"], explanation: "Group axioms imply unique identity.", difficulty: "easy" },
        { prompt: "A bijection is:", type: "mcq", answer: "Injective and surjective", choices: ["Only injective", "Injective and surjective", "Only surjective", "Always linear"], explanation: "One-to-one and onto.", difficulty: "easy" },
        { prompt: "If $\\varphi:G\\to H$ is a homomorphism, then $\\varphi(e_G)=$", type: "mcq", answer: "$e_H$", choices: ["$0$ only", "$e_H$", "Arbitrary", "$e_G$ only if injective"], explanation: "Identities map to identities.", difficulty: "medium" },
        { prompt: "Kernel of a group homomorphism is always:", type: "mcq", answer: "A normal subgroup", choices: ["A ring", "A normal subgroup", "The whole group", "Empty"], explanation: "Kernels are normal subgroups.", difficulty: "medium" },
        { prompt: "Lagrange's theorem applies to:", type: "mcq", answer: "Finite groups", choices: ["All rings", "Finite groups", "Only abelian groups", "Vector spaces only"], explanation: "Order of subgroup divides order of group.", difficulty: "medium" },
        { prompt: "If $|G|=p$ is prime, $G$ is:", type: "mcq", answer: "Cyclic", choices: ["Always $S_3$", "Cyclic", "Not a group", "Always infinite"], explanation: "Groups of prime order are cyclic.", difficulty: "medium" },
        { prompt: "A ring must have operations $+$ and $\\cdot$ where $+$ makes it:", type: "mcq", answer: "An abelian group", choices: ["A monoid only", "An abelian group", "A field always", "A vector space"], explanation: "Additive structure of a ring.", difficulty: "medium" },
        { prompt: "In a ring, $0\\cdot a$ equals:", type: "numeric", answer: "0", explanation: "Zero annihilates in rings.", difficulty: "medium" },
        { prompt: "Is every subgroup normal?", type: "mcq", answer: "No", choices: ["Yes always", "No", "Only in rings", "Only for $S_n$"], explanation: "Normality is extra in nonabelian groups.", difficulty: "medium" },
        { prompt: "First isomorphism theorem connects:", type: "mcq", answer: "$G/\\ker\\varphi$ and $\\operatorname{im}\\varphi$", choices: ["Two unrelated sets", "$G/\\ker\\varphi$ and $\\operatorname{im}\\varphi$", "Only fields", "Only $\\mathbb{Z}$"], explanation: "Fundamental homomorphism theorem.", difficulty: "hard" },
        { prompt: "If $H\\le G$ and $|H|=|G|$, then $H=$", type: "mcq", answer: "$G$", choices: ["$\\{e\\}$", "$G$", "Empty", "Cannot determine"], explanation: "Equal finite cardinalities in subgroup chain.", difficulty: "hard" },
        { prompt: "A field is a commutative ring where every nonzero element has:", type: "mcq", answer: "A multiplicative inverse", choices: ["Only additive inverse", "A multiplicative inverse", "No inverse", "Zero divisor"], explanation: "Field axioms.", difficulty: "hard" },
        { prompt: "To show two groups are isomorphic, exhibit:", type: "mcq", answer: "A bijective homomorphism", choices: ["Any function", "A bijective homomorphism", "Only injection", "Only same order"], explanation: "Isomorphism = bijective homomorphism.", difficulty: "hard" },
      ],
    },
    {
      id: "modular-arithmetic",
      slug: "mod",
      label: "Modular arithmetic",
      description:
        "Work with congruences, residue classes, and inverses mod $n$ — a bridge to finite groups and rings.",
      reviewLinks: [
        link("Modular arithmetic", "/number-theory/modules/modular-arithmetic"),
        link("Rings", "/abstract-algebra/modules/rings"),
      ],
      questions: [
        { prompt: "Compute $17 \\bmod 5$.", type: "numeric", answer: "2", explanation: "$17=3\\cdot5+2$.", difficulty: "easy" },
        { prompt: "Compute $-1 \\bmod 7$.", type: "numeric", answer: "6", explanation: "$-1\\equiv 6\\pmod 7$.", difficulty: "easy" },
        { prompt: "Is $10\\equiv 3\\pmod 7$?", type: "mcq", answer: "Yes", choices: ["Yes", "No", "Only in $\\mathbb{Z}_5$", "Undefined"], explanation: "$10-3=7$.", difficulty: "easy" },
        { prompt: "In $\\mathbb{Z}_6$, $4+4=$", type: "numeric", answer: "2", explanation: "$8\\equiv 2\\pmod 6$.", difficulty: "easy" },
        { prompt: "Multiplicative inverse of $3$ in $\\mathbb{Z}_7$ is:", type: "numeric", answer: "5", explanation: "$3\\cdot5=15\\equiv1\\pmod 7$.", difficulty: "easy" },
        { prompt: "How many elements in $\\mathbb{Z}_n$?", type: "mcq", answer: "$n$", choices: ["$n-1$", "$n$", "$2n$", "Infinite"], explanation: "Residue classes $0,\\ldots,n-1$.", difficulty: "medium" },
        { prompt: "If $\\gcd(a,n)=1$, then $a$ has:", type: "mcq", answer: "A multiplicative inverse mod $n$", choices: ["No inverse", "A multiplicative inverse mod $n$", "Only additive inverse", "Zero divisor"], explanation: "Units are coprime to modulus.", difficulty: "medium" },
        { prompt: "Solve $3x\\equiv 1\\pmod{11}$. Find $x$.", type: "numeric", answer: "4", explanation: "$3\\cdot4=12\\equiv1$.", difficulty: "medium" },
        { prompt: "Fermat's little theorem: if $p$ prime and $p\\nmid a$, then $a^{p-1}\\equiv$", type: "numeric", answer: "1", explanation: "Mod $p$ exponent reduction.", difficulty: "medium" },
        { prompt: "Units of $\\mathbb{Z}$ under multiplication are:", type: "mcq", answer: "$\\pm 1$", choices: ["All integers", "$\\pm 1$", "Only $0$", "Only primes"], explanation: "Invertible integers.", difficulty: "medium" },
        { prompt: "In $\\mathbb{Z}_8$, is $4$ a unit?", type: "mcq", answer: "No", choices: ["Yes", "No", "Only if $8$ prime", "Always"], explanation: "$\\gcd(4,8)\\ne1$.", difficulty: "medium" },
        { prompt: "If $a\\equiv b\\pmod n$, then $a+c\\equiv b+c\\pmod n$ means congruences:", type: "mcq", answer: "Respect addition", choices: ["Are unrelated", "Respect addition", "Only work for primes", "Break multiplication"], explanation: "Congruences are compatible with $+$.", difficulty: "medium" },
        { prompt: "Order of $\\mathbb{Z}_p^\\times$ for prime $p$ is:", type: "numeric", answer: "p-1", explanation: "All nonzero residues mod prime.", difficulty: "medium" },
        { prompt: "Chinese Remainder Theorem needs moduli:", type: "mcq", answer: "Pairwise coprime", choices: ["All equal", "Pairwise coprime", "All even", "Arbitrary"], explanation: "Coprimality ensures solution mod product.", difficulty: "hard" },
        { prompt: "In a ring $\\mathbb{Z}_n$, zero divisors exist when $n$ is:", type: "mcq", answer: "Composite", choices: ["Prime only", "Composite", "Always impossible", "Only for $n=1$"], explanation: "Composite moduli have zero divisors.", difficulty: "hard" },
        { prompt: "If $H$ is subgroup of finite abelian group $G$, is $G/H$ a group?", type: "mcq", answer: "Yes (quotient group)", choices: ["No", "Yes (quotient group)", "Only if $H=G$", "Only for rings"], explanation: "Normal subgroups give quotient groups; all subgroups normal in abelian case.", difficulty: "hard" },
      ],
    },
  ],
};