import type { SubjectSpec } from "../seed-tier1-diagnostics-types";

function link(label: string, href: string) {
  return { label, href };
}

export const NUMBER_THEORY: SubjectSpec = {
  slug: "number-theory",
  idPrefix: "nt-diag-",
  prerequisites: [
    {
      id: "divisibility",
      slug: "div",
      label: "Divisibility",
      description:
        "Use divisors, multiples, and basic divisibility rules for integers.",
      reviewLinks: [
        link("Divisors & primes", "/number-theory/modules/divisibility-primes"),
        link("Algebra foundations", "/algebra/modules/algebra-foundations"),
      ],
      questions: [
        { prompt: "Does $12$ divide $48$?", type: "mcq", answer: "Yes", choices: ["Yes", "No", "Only if $48$ is prime", "Only in $\\mathbb{R}$"], explanation: "$48=4\\cdot12$.", difficulty: "easy" },
        { prompt: "How many positive divisors does $6$ have?", type: "numeric", answer: "4", explanation: "$1,2,3,6$.", difficulty: "easy" },
        { prompt: "Is $1$ a prime number?", type: "mcq", answer: "No", choices: ["Yes", "No", "Sometimes", "Only in $\\mathbb{Z}_p$"], explanation: "Primes need exactly two positive divisors.", difficulty: "easy" },
        { prompt: "If $a\\mid b$ and $b\\mid c$, then $a\\mid c$. This property is:", type: "mcq", answer: "Transitivity of divisibility", choices: ["Symmetry", "Transitivity of divisibility", "Commutativity", "Reflexivity only"], explanation: "Divisors chain.", difficulty: "easy" },
        { prompt: "Is $91$ divisible by $7$?", type: "mcq", answer: "Yes", choices: ["Yes", "No", "Only by $13$", "Cannot tell"], explanation: "$91=7\\cdot13$.", difficulty: "easy" },
        { prompt: "Greatest common divisor of $12$ and $18$ is:", type: "numeric", answer: "6", explanation: "Common divisors peak at $6$.", difficulty: "medium" },
        { prompt: "Least common multiple of $4$ and $6$ is:", type: "numeric", answer: "12", explanation: "$\\mathrm{lcm}(4,6)=12$.", difficulty: "medium" },
        { prompt: "If $n$ is even, then $n^2$ is:", type: "mcq", answer: "Even", choices: ["Odd", "Even", "Prime", "Always $0$"], explanation: "Square preserves evenness.", difficulty: "medium" },
        { prompt: "If $a\\mid b$ and $a\\mid c$, then $a\\mid (b+c)$. This uses closure under:", type: "mcq", answer: "Addition", choices: ["Multiplication only", "Addition", "Division by zero", "Squaring only"], explanation: "Linear combinations stay divisible.", difficulty: "medium" },
        { prompt: "How many integers divide $17$ positively?", type: "numeric", answer: "2", explanation: "$17$ is prime: $1$ and $17$.", difficulty: "medium" },
        { prompt: "If $d=\\gcd(a,b)$, then $\\gcd(a/d,b/d)=$", type: "numeric", answer: "1", explanation: "Quotient pair is coprime.", difficulty: "medium" },
        { prompt: "Is every integer a divisor of $0$?", type: "mcq", answer: "Yes (with $0/0$ undefined)", choices: ["No", "Yes (with $0/0$ undefined)", "Only $1$", "Only primes"], explanation: "$0$ is divisible by any nonzero integer.", difficulty: "medium" },
        { prompt: "If $p$ is prime and $p\\mid ab$, then:", type: "mcq", answer: "$p\\mid a$ or $p\\mid b$", choices: ["$p\\mid a$ always", "$p\\mid a$ or $p\\mid b$", "$p\\mid ab$ only", "Nothing"], explanation: "Euclid's lemma.", difficulty: "hard" },
        { prompt: "Number of positive divisors of $p^2$ for prime $p$ is:", type: "numeric", answer: "3", explanation: "$1,p,p^2$.", difficulty: "hard" },
        { prompt: "If $\\gcd(a,b)=1$, we say $a$ and $b$ are:", type: "mcq", answer: "Coprime", choices: ["Equal", "Coprime", "Both prime", "Both even"], explanation: "Relatively prime.", difficulty: "hard" },
        { prompt: "For integers $a,b$, $a\\mid b$ and $b\\mid a$ implies:", type: "mcq", answer: "$|a|=|b|$", choices: ["$a=b=0$ always", "$|a|=|b|$", "$a=1$", "Nothing"], explanation: "Mutual divisibility gives equal magnitude.", difficulty: "hard" },
      ],
    },
    {
      id: "prime-factorization",
      slug: "pf",
      label: "Prime factorization",
      description:
        "Factor integers into primes and use unique factorization consequences.",
      reviewLinks: [
        link("Divisors & primes", "/number-theory/modules/divisibility-primes"),
        link("Polynomials & factoring", "/algebra/modules/polynomials-factoring"),
      ],
      questions: [
        { prompt: "Prime factorization of $12$ is:", type: "mcq", answer: "$2^2\\cdot 3$", choices: ["$2^2\\cdot 3$", "$2\\cdot 6$", "$3\\cdot 4$", "$12$"], explanation: "$12=4\\cdot3$.", difficulty: "easy" },
        { prompt: "Is $29$ prime?", type: "mcq", answer: "Yes", choices: ["Yes", "No", "Only in $\\mathbb{Z}_5$", "Composite"], explanation: "No divisors besides $1$ and $29$.", difficulty: "easy" },
        { prompt: "How many primes are there?", type: "mcq", answer: "Infinitely many", choices: ["Finitely many", "Infinitely many", "Exactly $100$", "None"], explanation: "Euclid's theorem.", difficulty: "easy" },
        { prompt: "Prime factorization of $30$ includes which primes?", type: "mcq", answer: "$2,3,5$", choices: ["$2,3,5$", "$2,15$", "$3,10$", "$6,5$ only"], explanation: "$30=2\\cdot3\\cdot5$.", difficulty: "easy" },
        { prompt: "Smallest prime is:", type: "numeric", answer: "2", explanation: "Only even prime.", difficulty: "easy" },
        { prompt: "If $n=p_1^{a_1}\\cdots p_k^{a_k}$, number of positive divisors is:", type: "mcq", answer: "$(a_1+1)\\cdots(a_k+1)$", choices: ["$a_1+\\cdots+a_k$", "$(a_1+1)\\cdots(a_k+1)$", "$k$", "$2k$"], explanation: "Divisor-counting formula.", difficulty: "medium" },
        { prompt: "Prime factorization of $72$ is:", type: "mcq", answer: "$2^3\\cdot 3^2$", choices: ["$2^3\\cdot 3^2$", "$8\\cdot 9$", "$2^2\\cdot 18$", "$6^2\\cdot 2$"], explanation: "$72=8\\cdot9$.", difficulty: "medium" },
        { prompt: "If $p$ is prime, $\\gcd(p,n)>1$ means:", type: "mcq", answer: "$p\\mid n$", choices: ["$n\\mid p$", "$p\\mid n$", "$n=p$ always", "Impossible"], explanation: "Prime divides $n$.", difficulty: "medium" },
        { prompt: "Fundamental Theorem of Arithmetic says factorization is:", type: "mcq", answer: "Unique up to order", choices: ["Not unique", "Unique up to order", "Only for evens", "Only in $\\mathbb{R}$"], explanation: "Canonical prime factorization.", difficulty: "medium" },
        { prompt: "Is $51$ prime?", type: "mcq", answer: "No", choices: ["Yes", "No", "Only mod $17$", "Yes in $\\mathbb{Z}$"], explanation: "$51=3\\cdot17$.", difficulty: "medium" },
        { prompt: "Largest prime factor of $84$ is:", type: "numeric", answer: "7", explanation: "$84=2^2\\cdot3\\cdot7$.", difficulty: "medium" },
        { prompt: "If $\\gcd(a,b)=1$ and $p\\mid ab$, then by Euclid's lemma:", type: "mcq", answer: "$p\\mid a$ or $p\\mid b$", choices: ["$p\\mid a$ always", "$p\\mid a$ or $p\\mid b$", "$p=1$", "$ab$ prime"], explanation: "Prime divides product.", difficulty: "medium" },
        { prompt: "Squarefree means no $p^2$ in factorization. Is $30$ squarefree?", type: "mcq", answer: "Yes", choices: ["Yes", "No", "Only if $30$ prime", "Undefined"], explanation: "All exponents $1$.", difficulty: "medium" },
        { prompt: "If $n>1$ is composite, it has a prime factor at most:", type: "mcq", answer: "$\\sqrt{n}$", choices: ["$n$", "$\\sqrt{n}$", "$n/2$ only", "$1$"], explanation: "Trial division bound.", difficulty: "hard" },
        { prompt: "Number of primes between $10$ and $20$ is:", type: "numeric", answer: "4", explanation: "$11,13,17,19$.", difficulty: "hard" },
        { prompt: "If $p,q$ distinct primes, $\\gcd(pq,p)=$", type: "numeric", answer: "p", explanation: "$p$ divides both.", difficulty: "hard" },
      ],
    },
    {
      id: "modular-arithmetic",
      slug: "mod",
      label: "Modular arithmetic",
      description:
        "Compute with congruences, residues, and modular inverses.",
      reviewLinks: [
        link("Modular arithmetic", "/number-theory/modules/modular-arithmetic"),
        link("Classical theorems", "/number-theory/modules/classical-theorems"),
      ],
      questions: [
        { prompt: "Compute $23 \\bmod 5$.", type: "numeric", answer: "3", explanation: "$23=4\\cdot5+3$.", difficulty: "easy" },
        { prompt: "Compute $100 \\bmod 7$.", type: "numeric", answer: "2", explanation: "$98$ divisible by $7$.", difficulty: "easy" },
        { prompt: "Is $25\\equiv 1\\pmod{8}$?", type: "mcq", answer: "Yes", choices: ["Yes", "No", "Only mod $4$", "Undefined"], explanation: "$25-1=24$ divisible by $8$.", difficulty: "easy" },
        { prompt: "In $\\mathbb{Z}_9$, $5+7=$", type: "numeric", answer: "3", explanation: "$12\\equiv3\\pmod9$.", difficulty: "easy" },
        { prompt: "Inverse of $2$ mod $7$ is:", type: "numeric", answer: "4", explanation: "$2\\cdot4=8\\equiv1$.", difficulty: "easy" },
        { prompt: "If $a\\equiv b\\pmod n$, then $a^2\\equiv b^2\\pmod n$ because:", type: "mcq", answer: "Congruences respect multiplication", choices: ["Luck", "Congruences respect multiplication", "Only for primes", "Never true"], explanation: "Multiply congruent residues.", difficulty: "medium" },
        { prompt: "Solve $5x\\equiv 3\\pmod{11}$. Find $x$.", type: "numeric", answer: "5", explanation: "$5\\cdot5=25\\equiv3$.", difficulty: "medium" },
        { prompt: "Wilson's theorem: $(p-1)!\\equiv$ mod prime $p$:", type: "numeric", answer: "-1", explanation: "Factorial residue mod prime.", difficulty: "medium" },
        { prompt: "Fermat: $2^{10}\\equiv 1\\pmod{11}$ because:", type: "mcq", answer: "$11$ is prime and $\\gcd(2,11)=1$", choices: ["$2$ is even", "$11$ is prime and $\\gcd(2,11)=1$", "Always true mod any $n$", "$10=2\\cdot5$"], explanation: "FLT applies.", difficulty: "medium" },
        { prompt: "Chinese Remainder: $x\\equiv 2\\pmod3$, $x\\equiv 3\\pmod5$. Smallest positive $x$?", type: "numeric", answer: "8", explanation: "Check $8$: works.", difficulty: "medium" },
        { prompt: "If $\\gcd(a,n)>1$, then $a$ has no inverse mod $n$ because:", type: "mcq", answer: "Would imply $1\\equiv 0\\pmod{\\gcd}$", choices: ["Inverses always exist", "Would imply $1\\equiv 0\\pmod{\\gcd}$", "Only for evens", "Only mod primes"], explanation: "Coprimality required.", difficulty: "medium" },
        { prompt: "Euler $\\varphi(p)=p-1$ for prime $p$ counts:", type: "mcq", answer: "Units mod $p$", choices: ["All residues", "Units mod $p$", "Divisors of $p$", "Zero only"], explanation: "Nonzero residues mod prime.", difficulty: "medium" },
        { prompt: "Compute $7^{100}\\bmod 5$.", type: "numeric", answer: "1", explanation: "$7\\equiv2$, and $2^4\\equiv1\\pmod5$.", difficulty: "medium" },
        { prompt: "Quadratic residue mod $p$ means:", type: "mcq", answer: "$\\exists x$ with $x^2\\equiv a\\pmod p$", choices: ["$a$ is prime", "$\\exists x$ with $x^2\\equiv a\\pmod p$", "$a$ is even", "$a\\equiv0$"], explanation: "Square root exists mod $p$.", difficulty: "hard" },
        { prompt: "If $p$ odd prime, exactly how many quadratic residues mod $p$ (excluding $0$)?", type: "numeric", answer: "(p-1)/2", explanation: "Squares partition nonzero residues.", difficulty: "hard" },
        { prompt: "Legendre symbol $\\left(\\frac{a}{p}\\right)=-1$ means:", type: "mcq", answer: "$a$ is a nonzero non-residue mod $p$", choices: ["$a$ is residue", "$a$ is a nonzero non-residue mod $p$", "$a=0$", "$p$ composite"], explanation: "Non-residue case.", difficulty: "hard" },
      ],
    },
    {
      id: "gcd-euclidean",
      slug: "gcd",
      label: "GCD and the Euclidean algorithm",
      description:
        "Compute GCD via the Euclidean algorithm and use Bezout identities.",
      reviewLinks: [
        link("Divisors & primes", "/number-theory/modules/divisibility-primes"),
        link("Modular arithmetic", "/number-theory/modules/modular-arithmetic"),
      ],
      questions: [
        { prompt: "$\\gcd(8,12)=$", type: "numeric", answer: "4", explanation: "Common factor $4$.", difficulty: "easy" },
        { prompt: "$\\gcd(9,16)=$", type: "numeric", answer: "1", explanation: "Coprime.", difficulty: "easy" },
        { prompt: "$\\gcd(n,0)=$", type: "mcq", answer: "$|n|$", choices: ["$0$", "$|n|$", "$1$", "Undefined"], explanation: "Convention $\\gcd(a,0)=|a|$.", difficulty: "easy" },
        { prompt: "Euclidean step: $\\gcd(48,18)=\\gcd(18,?)$", type: "numeric", answer: "12", explanation: "$48\\bmod18=12$.", difficulty: "easy" },
        { prompt: "$\\gcd(105,35)=$", type: "numeric", answer: "35", explanation: "$35$ divides $105$.", difficulty: "easy" },
        { prompt: "If $\\gcd(a,b)=d$, then $\\gcd(a/d,b/d)=$", type: "numeric", answer: "1", explanation: "Reduced pair coprime.", difficulty: "medium" },
        { prompt: "Bezout: $\\gcd(35,11)=1$ means $\\exists x,y$ with:", type: "mcq", answer: "$35x+11y=1$", choices: ["$35x+11y=0$", "$35x+11y=1$", "$35+11=1$", "$xy=1$"], explanation: "Linear combination equals gcd.", difficulty: "medium" },
        { prompt: "Run Euclidean algorithm on $(1071,462)$. First remainder?", type: "numeric", answer: "147", explanation: "$1071=2\\cdot462+147$.", difficulty: "medium" },
        { prompt: "$\\mathrm{lcm}(a,b)\\cdot\\gcd(a,b)=$", type: "mcq", answer: "$|ab|$", choices: ["$a+b$", "$|ab|$", "$\\gcd(a,b)$", "$1$"], explanation: "Classic identity.", difficulty: "medium" },
        { prompt: "If $\\gcd(a,n)=1$, then $a$ has inverse mod $n$ by:", type: "mcq", answer: "Extended Euclidean algorithm", choices: ["Guessing", "Extended Euclidean algorithm", "Factoring $n$ only", "Never"], explanation: "Bezout gives inverse.", difficulty: "medium" },
        { prompt: "$\\gcd(2,6,9)=$", type: "numeric", answer: "1", explanation: "Only common divisor $1$.", difficulty: "medium" },
        { prompt: "If $d\\mid a$ and $d\\mid b$, then $d\\mid \\gcd(a,b)$ shows gcd is:", type: "mcq", answer: "Greatest common divisor", choices: ["Smallest", "Greatest common divisor", "Always $1$", "Prime"], explanation: "Universal property.", difficulty: "medium" },
        { prompt: "Euclidean algorithm terminates because remainders:", type: "mcq", answer: "Strictly decrease", choices: ["Increase", "Strictly decrease", "Stay constant", "Are random"], explanation: "Well-founded descent.", difficulty: "medium" },
        { prompt: "If $\\gcd(a,b)=1$ and $a\\mid bc$, then:", type: "mcq", answer: "$a\\mid c$", choices: ["$a\\mid b$ only", "$a\\mid c$", "Impossible", "$b\\mid c$"], explanation: "Coprime cancellation lemma.", difficulty: "hard" },
        { prompt: "Running the Euclidean algorithm on $(1071,462)$, the final $\\gcd$ is:", type: "numeric", answer: "21", explanation: "$1071=2\\cdot462+147$, continuing yields $\\gcd=21$.", difficulty: "hard" },
        { prompt: "If $\\gcd(a,b)=1$, then $\\gcd(a,bc)=$ when $\\gcd(b,c)=1$:", type: "mcq", answer: "$1$", choices: ["$c$", "$1$", "$bc$", "$a$"], explanation: "Coprimality propagates under suitable hypotheses.", difficulty: "hard" },
      ],
    },
    {
      id: "proof-reasoning",
      slug: "proof",
      label: "Basic proof",
      description:
        "Use direct proof, contrapositive, contradiction, and induction for elementary number theory.",
      reviewLinks: [
        link("Formal systems & proofs", "/mathematical-logic/modules/formal-systems"),
        link("Classical theorems", "/number-theory/modules/classical-theorems"),
      ],
      questions: [
        { prompt: "To prove '$n^2$ even $\\Rightarrow n$ even', the clean approach is:", type: "mcq", answer: "Contrapositive", choices: ["Direct on $n^2$", "Contrapositive", "Counterexample", "Graph"], explanation: "Prove odd $\\Rightarrow n^2$ odd.", difficulty: "easy" },
        { prompt: "Proof that there are infinitely many primes is by:", type: "mcq", answer: "Contradiction", choices: ["Induction only", "Contradiction", "Construction of formula", "Computer check"], explanation: "Euclid's classic proof.", difficulty: "easy" },
        { prompt: "If $n$ is odd, $n^2$ is:", type: "mcq", answer: "Odd", choices: ["Even", "Odd", "Prime", "Zero"], explanation: "Odd times odd is odd.", difficulty: "easy" },
        { prompt: "Strong induction differs from ordinary induction by:", type: "mcq", answer: "Assuming all cases below $k$ when proving $k$", choices: ["Using bigger base", "Assuming all cases below $k$ when proving $k$", "No base case", "Only for primes"], explanation: "Strong IH assumes $P(0),\\ldots,P(k)$.", difficulty: "easy" },
        { prompt: "To show $\\sqrt{2}$ irrational, assume:", type: "mcq", answer: "$\\sqrt{2}=p/q$ in lowest terms and derive contradiction", choices: ["$\\sqrt{2}=2$", "$\\sqrt{2}=p/q$ in lowest terms and derive contradiction", "$\\sqrt{2}$ is integer", "$p=q$"], explanation: "Classic irrationality proof.", difficulty: "easy" },
        { prompt: "If $3\\mid n^2$, then $3\\mid n$ because $3$ is:", type: "mcq", answer: "Prime", choices: ["Composite", "Prime", "Even", "Unit"], explanation: "Prime divides square $\\Rightarrow$ divides $n$.", difficulty: "medium" },
        { prompt: "Divisibility proof: if $a\\mid b$ and $b\\mid c$, conclude:", type: "mcq", answer: "$a\\mid c$", choices: ["$c\\mid a$", "$a\\mid c$", "$a=c$", "$b=1$"], explanation: "Transitivity.", difficulty: "medium" },
        { prompt: "Smallest counterexample method is useful when:", type: "mcq", answer: "A minimal failing case contradicts assumptions", choices: ["Always illegal", "A minimal failing case contradicts assumptions", "Only in calculus", "Only for graphs"], explanation: "Well-ordering argument.", difficulty: "medium" },
        { prompt: "If $p$ prime and $p\\mid a^2$, then:", type: "mcq", answer: "$p\\mid a$", choices: ["$a$ prime", "$p\\mid a$", "$p\\mid p$ only", "Nothing"], explanation: "Euclid's lemma.", difficulty: "medium" },
        { prompt: "To prove $\\sum_{i=1}^n i = n(n+1)/2$, use:", type: "mcq", answer: "Induction", choices: ["Contradiction", "Induction", "Only examples", "Calculus"], explanation: "Standard induction exercise.", difficulty: "medium" },
        { prompt: "The statement '$\\forall n, P(n)$' is false if:", type: "mcq", answer: "One $n$ fails $P(n)$", choices: ["All $n$ fail", "One $n$ fails $P(n)$", "Two $n$ work", "Never"], explanation: "Single counterexample suffices.", difficulty: "medium" },
        { prompt: "If $\\gcd(a,b)=1$ and $a\\mid c$, $b\\mid c$, then:", type: "mcq", answer: "$ab\\mid c$", choices: ["$a+b\\mid c$", "$ab\\mid c$", "$1\\mid c$ only", "Impossible"], explanation: "Coprime lcm divides $c$.", difficulty: "medium" },
        { prompt: "Pigeonhole with $n$ pigeons, $n-1$ holes forces:", type: "mcq", answer: "Some hole has at least $2$ pigeons", choices: ["All holes empty", "Some hole has at least $2$ pigeons", "All holes equal", "No collision"], explanation: "Basic pigeonhole.", difficulty: "medium" },
        { prompt: "Proof by cases for parity splits integers into:", type: "mcq", answer: "Even and odd", choices: ["Positive and negative", "Even and odd", "Prime and composite", "Rational and irrational"], explanation: "Parity case split.", difficulty: "hard" },
        { prompt: "If $a\\equiv b\\pmod n$ and $c\\equiv d\\pmod n$, then $ac\\equiv bd\\pmod n$ shows congruences:", type: "mcq", answer: "Respect multiplication", choices: ["Break multiplication", "Respect multiplication", "Only work for addition", "Require $n$ prime"], explanation: "Multiplicative compatibility.", difficulty: "hard" },
        { prompt: "To prove a property for all $n\\ge n_0$, induction starts at:", type: "mcq", answer: "Base case $n_0$", choices: ["$n=0$ always", "Base case $n_0$", "No base", "$n=\\infty$"], explanation: "Shifted induction base.", difficulty: "hard" },
      ],
    },
    {
      id: "basic-algebra",
      slug: "balg",
      label: "Basic algebra",
      description:
        "Manipulate expressions, solve equations, and work with integer arithmetic fluently.",
      reviewLinks: [
        link("Algebra foundations", "/algebra/modules/algebra-foundations"),
        link("Linear equations", "/algebra/modules/linear-equations-systems"),
      ],
      questions: [
        { prompt: "Solve $x+7=12$.", type: "numeric", answer: "5", explanation: "$x=5$.", difficulty: "easy" },
        { prompt: "Evaluate $3^2-4$.", type: "numeric", answer: "5", explanation: "$9-4=5$.", difficulty: "easy" },
        { prompt: "Simplify $2(x+3)$.", type: "numeric", answer: "2x+6", explanation: "Distribute.", difficulty: "easy" },
        { prompt: "Solve $4x=20$.", type: "numeric", answer: "5", explanation: "$x=5$.", difficulty: "easy" },
        { prompt: "Which is even?", type: "mcq", answer: "$14$", choices: ["$13$", "$14$", "$15$", "$17$"], explanation: "$14=2\\cdot7$.", difficulty: "easy" },
        { prompt: "Compute $(-3)^2$.", type: "numeric", answer: "9", explanation: "Square is nonnegative.", difficulty: "medium" },
        { prompt: "Solve $x^2=49$ for positive $x$.", type: "numeric", answer: "7", explanation: "$x=7$.", difficulty: "medium" },
        { prompt: "Simplify $\\frac{6}{9}$ to lowest terms (fraction).", type: "numeric", answer: "2/3", explanation: "Divide by $3$.", difficulty: "medium" },
        { prompt: "If $n=2k$, then $n$ is:", type: "mcq", answer: "Even", choices: ["Odd", "Even", "Prime", "Square"], explanation: "Definition of even.", difficulty: "medium" },
        { prompt: "Compute $7\\cdot8$.", type: "numeric", answer: "56", explanation: "Basic multiplication.", difficulty: "medium" },
        { prompt: "Solve $2x+1=9$.", type: "numeric", answer: "4", explanation: "$2x=8$.", difficulty: "medium" },
        { prompt: "Expand $(n+1)^2$.", type: "mcq", answer: "$n^2+2n+1$", choices: ["$n^2+1$", "$n^2+2n+1$", "$n^2+n+1$", "$2n^2+1$"], explanation: "Binomial square.", difficulty: "medium" },
        { prompt: "Sum of first $5$ positive integers is:", type: "numeric", answer: "15", explanation: "$1+2+3+4+5=15$.", difficulty: "medium" },
        { prompt: "If $a+b=10$ and $a-b=2$, then $a=$", type: "numeric", answer: "6", explanation: "Add equations: $2a=12$.", difficulty: "hard" },
        { prompt: "Which expression equals $n(n+1)$?", type: "mcq", answer: "Product of consecutive integers", choices: ["Always a square", "Product of consecutive integers", "Always prime", "Always odd"], explanation: "Two consecutive integers.", difficulty: "hard" },
        { prompt: "Solve $x^2-3x=0$.", type: "mcq", answer: "$x=0$ or $x=3$", choices: ["$x=0$ only", "$x=3$ only", "$x=0$ or $x=3$", "No solutions"], explanation: "$x(x-3)=0$.", difficulty: "hard" },
      ],
    },
  ],
};
