import type { SubjectSpec } from "../seed-tier1-diagnostics-types";

function link(label: string, href: string) {
  return { label, href };
}

export const PRECALCULUS: SubjectSpec = {
  slug: "precalculus",
  idPrefix: "precalc-diag-",
  prerequisites: [
    {
      id: "algebra-manipulation",
      slug: "alg",
      label: "Algebra manipulation",
      description:
        "Simplify expressions, factor polynomials, solve linear and quadratic equations, and manipulate rational expressions.",
      reviewLinks: [
        link("Polynomials & factoring", "/algebra/modules/polynomials-factoring"),
        link("Algebra foundations", "/algebra/modules/algebra-foundations"),
      ],
      questions: [
        { prompt: "Solve for $x$: $2x + 5 = 13$.", type: "numeric", answer: "4", explanation: "Subtract $5$: $2x = 8$. Divide by $2$: $x = 4$.", difficulty: "easy" },
        { prompt: "Solve for $x$: $3x - 7 = 2$.", type: "numeric", answer: "3", explanation: "Add $7$: $3x = 9$. Divide by $3$: $x = 3$.", difficulty: "easy" },
        { prompt: "Expand $2(x + 4)$.", type: "numeric", answer: "2x+8", explanation: "Distribute: $2x + 8$.", difficulty: "easy" },
        { prompt: "Factor $x^2 - 9$.", type: "mcq", answer: "$(x-3)(x+3)$", choices: ["$(x-3)(x+3)$", "$(x-9)(x+1)$", "$(x-3)^2$", "$x(x-9)$"], explanation: "Difference of squares: $x^2 - 9 = (x-3)(x+3)$.", difficulty: "easy" },
        { prompt: "Simplify $\\frac{4x + 8}{4}$ for $x \\ne -2$.", type: "numeric", answer: "x+2", explanation: "Factor numerator: $\\frac{4(x+2)}{4} = x + 2$.", difficulty: "easy" },
        { prompt: "Factor $x^2 + 5x + 6$.", type: "mcq", answer: "$(x+2)(x+3)$", choices: ["$(x+1)(x+6)$", "$(x+2)(x+3)$", "$(x-2)(x-3)$", "$(x+5)(x+1)$"], explanation: "$2$ and $3$ multiply to $6$ and add to $5$.", difficulty: "medium" },
        { prompt: "Simplify $\\frac{x^2 - 9}{x - 3}$ for $x \\ne 3$.", type: "numeric", answer: "x+3", explanation: "Factor and cancel: $(x-3)(x+3)/(x-3) = x+3$.", difficulty: "medium" },
        { prompt: "Solve $x^2 - 5x + 6 = 0$.", type: "mcq", answer: "$x = 2$ or $x = 3$", choices: ["$x = 2$ or $x = 3$", "$x = -2$ or $x = -3$", "$x = 1$ or $x = 6$", "No real solutions"], explanation: "$(x-2)(x-3)=0$ gives $x=2$ or $x=3$.", difficulty: "medium" },
        { prompt: "Simplify $\\frac{3x^2}{x}$ for $x \\ne 0$.", type: "numeric", answer: "3x", explanation: "Cancel one factor of $x$.", difficulty: "easy" },
        { prompt: "Complete the square for $x^2 + 6x$. What constant is added?", type: "numeric", answer: "9", explanation: "Half of $6$ is $3$; $3^2 = 9$.", difficulty: "medium" },
        { prompt: "Simplify $\\frac{x^2 - 4x + 4}{x - 2}$ for $x \\ne 2$.", type: "numeric", answer: "x-2", explanation: "Numerator is $(x-2)^2$; cancel one factor.", difficulty: "medium" },
        { prompt: "If $\\frac{a}{b} = \\frac{3}{4}$ and $b = 8$, find $a$.", type: "numeric", answer: "6", explanation: "$a/8 = 3/4 \\Rightarrow a = 6$.", difficulty: "medium" },
        { prompt: "Which expression is equivalent to $(2x)^3$?", type: "mcq", answer: "$8x^3$", choices: ["$6x^3$", "$8x^3$", "$2x^3$", "$8x$"], explanation: "$(2x)^3 = 2^3 x^3 = 8x^3$.", difficulty: "medium" },
        { prompt: "Solve $\\frac{2}{x} + \\frac{1}{3} = 1$ for $x \\ne 0$.", type: "numeric", answer: "3", explanation: "Multiply by $3x$: $6 + x = 3x \\Rightarrow x = 3$.", difficulty: "hard" },
        { prompt: "For which $x$ is $\\frac{x+1}{x^2-1}$ undefined?", type: "mcq", answer: "$x = 1$ and $x = -1$", choices: ["$x = 1$ only", "$x = -1$ only", "$x = 1$ and $x = -1$", "Never undefined"], explanation: "Denominator $x^2-1=(x-1)(x+1)$ is zero at $\\pm 1$.", difficulty: "hard" },
        { prompt: "If $x^2 + bx + 9$ is a perfect square, find $b > 0$.", type: "numeric", answer: "6", explanation: "$(x+3)^2 = x^2 + 6x + 9$, so $b = 6$.", difficulty: "hard" },
      ],
    },
    {
      id: "functions-graphs",
      slug: "fg",
      label: "Functions and graphs",
      description:
        "Evaluate functions, read graphs and tables, and interpret domain, range, and transformations.",
      reviewLinks: [
        link("Functions & graphs (algebra)", "/algebra/modules/functions-and-graphs"),
        link("Functions & graphs (precalculus)", "/precalculus/modules/functions-and-graphs"),
      ],
      questions: [
        { prompt: "If $f(x)=2x+3$, what is $f(4)$?", type: "numeric", answer: "11", explanation: "$f(4)=2(4)+3=11$.", difficulty: "easy" },
        { prompt: "If $g(x)=x^2-1$, what is $g(3)$?", type: "numeric", answer: "8", explanation: "$g(3)=9-1=8$.", difficulty: "easy" },
        { prompt: "If $f(x)=\\frac{1}{x}$, which value is NOT in the domain?", type: "mcq", answer: "$0$", choices: ["$1$", "$-1$", "$0$", "$2$"], explanation: "Division by zero excludes $x=0$.", difficulty: "easy" },
        { prompt: "If $h(x)=5-3x$, what is $h(2)$?", type: "numeric", answer: "-1", explanation: "$h(2)=5-6=-1$.", difficulty: "easy" },
        { prompt: "What is the domain of $f(x)=\\sqrt{x-4}$?", type: "mcq", answer: "$x \\ge 4$", choices: ["$x > 4$", "$x \\ge 4$", "$x \\le 4$", "All real $x$"], explanation: "Need $x-4 \\ge 0$.", difficulty: "easy" },
        { prompt: "If $f(x)=x+1$ and $g(x)=2x$, what is $f(g(2))$?", type: "numeric", answer: "5", explanation: "$g(2)=4$, then $f(4)=5$.", difficulty: "medium" },
        { prompt: "If $f(x)=3x-7$, what $x$ makes $f(x)=2$?", type: "numeric", answer: "3", explanation: "$3x-7=2 \\Rightarrow x=3$.", difficulty: "medium" },
        { prompt: "If $f(x)=|x-3|$, what is $f(0)$?", type: "numeric", answer: "3", explanation: "$|0-3|=3$.", difficulty: "medium" },
        { prompt: "The graph of $y=f(x)$ passes through $(3,7)$. The graph of $y=f(x)+2$ passes through $(3,k)$. Find $k$.", type: "numeric", answer: "9", explanation: "Vertical shift adds $2$ to outputs.", difficulty: "medium" },
        { prompt: "If $f(x)=x^2$ and $g(x)=x-1$, what is $(f \\circ g)(2)$?", type: "numeric", answer: "1", explanation: "$g(2)=1$, $f(1)=1$.", difficulty: "medium" },
        { prompt: "If $f(x)=-x^2+4$, what is the maximum value of $f(x)$?", type: "numeric", answer: "4", explanation: "Downward parabola with vertex at $(0,4)$.", difficulty: "medium" },
        { prompt: "If $f(x)=x^3$, is $f$ odd?", type: "mcq", answer: "Yes", choices: ["Yes", "No", "Only for $x \\ge 0$", "Cannot determine"], explanation: "$f(-x)=-x^3=-f(x)$.", difficulty: "medium" },
        { prompt: "If $f(2x)=4x+5$, what is $f(6)$?", type: "numeric", answer: "17", explanation: "$2x=6 \\Rightarrow x=3$; $f(6)=17$.", difficulty: "hard" },
        { prompt: "Let $f(x)=\\begin{cases} 2x & x < 1 \\\\ x+3 & x \\ge 1 \\end{cases}$. What is $f(0)$?", type: "numeric", answer: "0", explanation: "Use $2x$ since $0<1$.", difficulty: "medium" },
        { prompt: "Which transformation turns $y=x^2$ into $y=(x-2)^2$?", type: "mcq", answer: "Shift right $2$ units", choices: ["Shift left $2$", "Shift right $2$ units", "Shift up $2$", "Reflect over $x$-axis"], explanation: "Replacing $x$ with $x-2$ shifts right.", difficulty: "hard" },
        { prompt: "If $f(x)=\\frac{x+1}{x-1}$, what is $f(2)$?", type: "numeric", answer: "3", explanation: "$f(2)=3/1=3$.", difficulty: "hard" },
      ],
    },
    {
      id: "exponents-logs",
      slug: "exp",
      label: "Exponents and logs",
      description:
        "Apply exponent rules, rational exponents, and logarithm properties used in precalculus models.",
      reviewLinks: [
        link("Exponents & logarithms", "/algebra/modules/exponents-radicals-logarithms"),
        link("Exponential & log functions", "/precalculus/modules/exponential-logarithmic-functions"),
      ],
      questions: [
        { prompt: "Simplify $2^3 \\cdot 2^4$.", type: "numeric", answer: "128", explanation: "$2^{3+4}=2^7=128$.", difficulty: "easy" },
        { prompt: "Evaluate $5^0$.", type: "numeric", answer: "1", explanation: "Any nonzero number to the zero power is $1$.", difficulty: "easy" },
        { prompt: "Simplify $\\frac{3^6}{3^2}$.", type: "numeric", answer: "81", explanation: "$3^{6-2}=3^4=81$.", difficulty: "easy" },
        { prompt: "Write $\\sqrt{x^4}$ using exponents ($x \\ge 0$).", type: "numeric", answer: "x^2", explanation: "$\\sqrt{x^4}=(x^4)^{1/2}=x^2$.", difficulty: "easy" },
        { prompt: "Which equals $8^{2/3}$?", type: "mcq", answer: "$4$", choices: ["$2$", "$4$", "$16$", "$64$"], explanation: "$8^{2/3}=(\\sqrt[3]{8})^2=2^2=4$.", difficulty: "easy" },
        { prompt: "Solve $2^x = 32$.", type: "numeric", answer: "5", explanation: "$32=2^5$, so $x=5$.", difficulty: "medium" },
        { prompt: "If $\\log_2 8 = k$, find $k$.", type: "numeric", answer: "3", explanation: "$2^3=8$.", difficulty: "medium" },
        { prompt: "Simplify $\\log(10^4)$ using base $10$.", type: "numeric", answer: "4", explanation: "$\\log_{10}(10^4)=4$.", difficulty: "medium" },
        { prompt: "Expand $\\log(xy)$ (single log of a product).", type: "mcq", answer: "$\\log x + \\log y$", choices: ["$\\log x + \\log y$", "$\\log x - \\log y$", "$\\log(x/y)$", "$\\log x \\cdot \\log y$"], explanation: "Product rule: $\\log(xy)=\\log x + \\log y$.", difficulty: "medium" },
        { prompt: "Solve $10^x = 0.01$.", type: "numeric", answer: "-2", explanation: "$0.01=10^{-2}$.", difficulty: "medium" },
        { prompt: "Simplify $(x^{1/2})^4$ for $x>0$.", type: "numeric", answer: "x^2", explanation: "Multiply exponents: $x^{2}$.", difficulty: "medium" },
        { prompt: "If $3^{2x}=81$, find $x$.", type: "numeric", answer: "2", explanation: "$81=3^4$, so $2x=4$.", difficulty: "medium" },
        { prompt: "Which is equivalent to $\\ln(e^5)$?", type: "mcq", answer: "$5$", choices: ["$1$", "$5$", "$e^5$", "$\\ln 5$"], explanation: "$\\ln$ and $e^x$ are inverses.", difficulty: "medium" },
        { prompt: "Solve $\\log_3(x-1)=2$.", type: "numeric", answer: "10", explanation: "$x-1=3^2=9$, so $x=10$.", difficulty: "hard" },
        { prompt: "Simplify $\\frac{2^{n+1}}{2^{n-1}}$.", type: "mcq", answer: "$4$", choices: ["$2$", "$4$", "$2^n$", "$1$"], explanation: "Subtract exponents: $2^{(n+1)-(n-1)}=2^2=4$.", difficulty: "hard" },
        { prompt: "If $a^x = b$ and $a,b>0$, $a\\ne 1$, express $x$ using logs.", type: "mcq", answer: "$x = \\log_a b$", choices: ["$x = \\log_a b$", "$x = \\log_b a$", "$x = a^b$", "$x = b/a$"], explanation: "By definition of logarithm.", difficulty: "hard" },
      ],
    },
    {
      id: "coordinate-geometry",
      slug: "coord",
      label: "Coordinate geometry",
      description:
        "Work with distances, midpoints, slopes, lines, and points in the coordinate plane.",
      reviewLinks: [
        link("Functions & graphs", "/algebra/modules/functions-and-graphs"),
        link("Complex & polar", "/precalculus/modules/complex-and-polar"),
      ],
      questions: [
        { prompt: "Find the distance between $(0,0)$ and $(3,4)$.", type: "numeric", answer: "5", explanation: "$\\sqrt{3^2+4^2}=5$.", difficulty: "easy" },
        { prompt: "Find the midpoint of $(2,4)$ and $(6,8)$.", type: "mcq", answer: "$(4,6)$", choices: ["$(4,6)$", "$(3,5)$", "$(8,12)$", "$(2,2)$"], explanation: "Average coordinates: $(4,6)$.", difficulty: "easy" },
        { prompt: "What is the slope of the line through $(1,2)$ and $(3,6)$?", type: "numeric", answer: "2", explanation: "$(6-2)/(3-1)=2$.", difficulty: "easy" },
        { prompt: "What is the $y$-intercept of $y=3x+5$?", type: "numeric", answer: "5", explanation: "Set $x=0$: $y=5$.", difficulty: "easy" },
        { prompt: "Which equation represents a vertical line?", type: "mcq", answer: "$x=4$", choices: ["$y=4$", "$x=4$", "$y=x$", "$y=2x+1$"], explanation: "Vertical lines have form $x=c$.", difficulty: "easy" },
        { prompt: "Find the distance between $(1,1)$ and $(4,5)$.", type: "numeric", answer: "5", explanation: "$\\sqrt{9+16}=5$.", difficulty: "medium" },
        { prompt: "Line $L$ has slope $-2$ and passes through $(0,3)$. What is $y$ when $x=2$?", type: "numeric", answer: "-1", explanation: "$y=-2(2)+3=-1$.", difficulty: "medium" },
        { prompt: "Are the lines $y=2x+1$ and $y=2x-3$ parallel?", type: "mcq", answer: "Yes", choices: ["Yes", "No", "Perpendicular", "Same line"], explanation: "Equal slopes, different intercepts.", difficulty: "medium" },
        { prompt: "Find the slope of a line perpendicular to $y=\\frac{1}{3}x+2$.", type: "numeric", answer: "-3", explanation: "Negative reciprocal of $1/3$ is $-3$.", difficulty: "medium" },
        { prompt: "What is the $x$-intercept of $2x+5y=10$?", type: "numeric", answer: "5", explanation: "Set $y=0$: $2x=10$, $x=5$.", difficulty: "medium" },
        { prompt: "The center of a circle is $(2,-1)$ and radius is $3$. Which point lies on it?", type: "mcq", answer: "$(5,-1)$", choices: ["$(5,-1)$", "$(2,2)$", "$(0,0)$", "$(2,-5)$"], explanation: "$(5,-1)$ is $3$ units right of center.", difficulty: "medium" },
        { prompt: "Reflect $(3,4)$ across the $x$-axis. What is the new $y$-coordinate?", type: "numeric", answer: "-4", explanation: "Reflection negates $y$.", difficulty: "medium" },
        { prompt: "Find the area of a triangle with vertices $(0,0)$, $(4,0)$, $(0,3)$.", type: "numeric", answer: "6", explanation: "Right triangle: $\\frac{1}{2}(4)(3)=6$.", difficulty: "hard" },
        { prompt: "A line passes through $(1,2)$ with slope $m$ and $(3,8)$. Find $m$.", type: "numeric", answer: "3", explanation: "$(8-2)/(3-1)=3$.", difficulty: "hard" },
        { prompt: "Which point is closest to the origin?", type: "mcq", answer: "$(1,2)$", choices: ["$(3,4)$", "$(1,2)$", "$(-5,0)$", "$(0,6)$"], explanation: "Distances: $\\sqrt{5}$, $\\sqrt{5}$, $5$, $6$; $(1,2)$ ties smallest.", difficulty: "hard" },
        { prompt: "Find the slope of the line $3x-2y=6$.", type: "numeric", answer: "3/2", explanation: "$y=\\frac{3}{2}x-3$, slope $3/2$.", difficulty: "hard" },
      ],
    },
    {
      id: "trigonometry",
      slug: "trig",
      label: "Trigonometry",
      description:
        "Use the unit circle, basic trig ratios, identities, and solve simple trigonometric equations.",
      reviewLinks: [
        link("Trigonometric functions", "/precalculus/modules/trigonometric-functions"),
        link("Analytic trigonometry", "/precalculus/modules/analytic-trigonometry"),
      ],
      questions: [
        { prompt: "In a right triangle, if opposite $=3$ and hypotenuse $=5$, find $\\sin\\theta$.", type: "numeric", answer: "3/5", explanation: "$\\sin\\theta = \\text{opp}/\\text{hyp} = 3/5$.", difficulty: "easy" },
        { prompt: "What is $\\cos(0^\\circ)$?", type: "numeric", answer: "1", explanation: "On the unit circle, $(1,0)$ gives cosine $1$.", difficulty: "easy" },
        { prompt: "What is $\\sin(90^\\circ)$?", type: "numeric", answer: "1", explanation: "Top of unit circle.", difficulty: "easy" },
        { prompt: "Which angle in radians equals $180^\\circ$?", type: "mcq", answer: "$\\pi$", choices: ["$\\pi/2$", "$\\pi$", "$2\\pi$", "$\\pi/4$"], explanation: "$180^\\circ = \\pi$ radians.", difficulty: "easy" },
        { prompt: "What is $\\tan(45^\\circ)$?", type: "numeric", answer: "1", explanation: "Equal legs in $45^\\circ$-$45^\\circ$-$90^\\circ$ triangle.", difficulty: "easy" },
        { prompt: "If $\\sin\\theta = 1/2$ and $\\theta$ is acute, find $\\theta$ in degrees.", type: "numeric", answer: "30", explanation: "$\\sin 30^\\circ = 1/2$.", difficulty: "medium" },
        { prompt: "Simplify $\\sin^2\\theta + \\cos^2\\theta$.", type: "mcq", answer: "$1$", choices: ["$0$", "$1$", "$\\sin 2\\theta$", "$\\tan\\theta$"], explanation: "Pythagorean identity.", difficulty: "medium" },
        { prompt: "What is $\\cos(\\pi/3)$?", type: "numeric", answer: "1/2", explanation: "Unit circle value at $60^\\circ$.", difficulty: "medium" },
        { prompt: "Convert $\\pi/6$ radians to degrees.", type: "numeric", answer: "30", explanation: "$(\\pi/6)(180/\\pi)=30$.", difficulty: "medium" },
        { prompt: "What is the period of $y=\\sin x$ (in radians)?", type: "mcq", answer: "$2\\pi$", choices: ["$\\pi$", "$2\\pi$", "$\\pi/2$", "$4\\pi$"], explanation: "Sine repeats every $2\\pi$.", difficulty: "medium" },
        { prompt: "If $\\cos\\theta = -1/2$ and $\\theta$ in $[0,\\pi]$, find $\\theta$ in radians.", type: "numeric", answer: "2pi/3", explanation: "Second quadrant angle with cosine $-1/2$.", difficulty: "medium" },
        { prompt: "Simplify $\\tan\\theta \\cdot \\cos\\theta$.", type: "mcq", answer: "$\\sin\\theta$", choices: ["$\\sin\\theta$", "$\\cos\\theta$", "$\\tan\\theta$", "$1$"], explanation: "$(\\sin\\theta/\\cos\\theta)\\cos\\theta=\\sin\\theta$.", difficulty: "medium" },
        { prompt: "Solve $\\sin x = 0$ on $[0,2\\pi)$. How many solutions?", type: "numeric", answer: "2", explanation: "Solutions at $x=0$ and $x=\\pi$ in $[0,2\\pi)$.", difficulty: "hard" },
        { prompt: "What is $\\sin(\\pi/2)$?", type: "numeric", answer: "1", explanation: "Top of the unit circle.", difficulty: "easy" },
        { prompt: "Using $\\cos(2\\theta)=\\cos^2\\theta-\\sin^2\\theta$, if $\\cos\\theta=0$, find $\\cos(2\\theta)$.", type: "numeric", answer: "-1", explanation: "$\\cos\\theta=0$ at $\\theta=\\pi/2$ gives $\\cos(\\pi)=-1$.", difficulty: "hard" },
        { prompt: "Which identity is correct?", type: "mcq", answer: "$1+\\tan^2\\theta=\\sec^2\\theta$", choices: ["$1+\\tan^2\\theta=\\sec^2\\theta$", "$\\sin^2\\theta-\\cos^2\\theta=1$", "$\\tan\\theta=\\cos\\theta/\\sin\\theta$", "$\\sec\\theta=1/\\tan\\theta$"], explanation: "Standard Pythagorean identity for tangent and secant.", difficulty: "hard" },
      ],
    },
    {
      id: "limits-intuition",
      slug: "lim",
      label: "Limits intuition",
      description:
        "Understand approaching behavior, one-sided limits, and removable discontinuities before formal calculus.",
      reviewLinks: [
        link("Introduction to limits", "/precalculus/modules/introduction-to-limits"),
        link("Functions & graphs", "/precalculus/modules/functions-and-graphs"),
      ],
      questions: [
        { prompt: "As $x \\to 2$, what does $3x+1$ approach?", type: "numeric", answer: "7", explanation: "Substitute $x=2$: $7$.", difficulty: "easy" },
        { prompt: "As $x \\to 0$, what does $x^2$ approach?", type: "numeric", answer: "0", explanation: "Squaring a small number stays small.", difficulty: "easy" },
        { prompt: "Evaluate $\\lim_{x\\to 1} (2x+3)$.", type: "numeric", answer: "5", explanation: "Polynomials are continuous: plug in $x=1$.", difficulty: "easy" },
        { prompt: "As $x \\to 3$, does $1/(x-3)$ approach a finite number?", type: "mcq", answer: "No", choices: ["Yes", "No", "Yes, equals $0$", "Yes, equals $3$"], explanation: "Denominator goes to $0$; magnitude blows up.", difficulty: "easy" },
        { prompt: "Evaluate $\\lim_{x\\to 0} \\frac{\\sin x}{x}$ (classic limit).", type: "numeric", answer: "1", explanation: "Standard limit: approaches $1$.", difficulty: "easy" },
        { prompt: "For $f(x)=\\frac{x^2-4}{x-2}$, what is $\\lim_{x\\to 2} f(x)$?", type: "numeric", answer: "4", explanation: "Cancel $(x-2)$: limit is $x+2 \\to 4$.", difficulty: "medium" },
        { prompt: "If $\\lim_{x\\to a} f(x)=5$ but $f(a)=2$, what kind of discontinuity?", type: "mcq", answer: "Removable (if redefined)", choices: ["No discontinuity", "Jump", "Removable (if redefined)", "Always infinite"], explanation: "Limit exists but differs from value — hole.", difficulty: "medium" },
        { prompt: "Evaluate $\\lim_{x\\to \\infty} \\frac{1}{x}$.", type: "numeric", answer: "0", explanation: "Reciprocals of large $x$ shrink to $0$.", difficulty: "medium" },
        { prompt: "As $x \\to 0^+$, what does $1/x$ do?", type: "mcq", answer: "Increases without bound", choices: ["Approaches $0$", "Approaches $1$", "Increases without bound", "Approaches $-1$"], explanation: "Positive numbers dividing into $1$ grow large.", difficulty: "medium" },
        { prompt: "Evaluate $\\lim_{x\\to 4} \\sqrt{x}$.", type: "numeric", answer: "2", explanation: "$\\sqrt{4}=2$.", difficulty: "medium" },
        { prompt: "If $\\lim_{x\\to 1^-} f(x)=3$ and $\\lim_{x\\to 1^+} f(x)=3$, what is $\\lim_{x\\to 1} f(x)$?", type: "numeric", answer: "3", explanation: "Equal one-sided limits give the two-sided limit.", difficulty: "medium" },
        { prompt: "Evaluate $\\lim_{x\\to 0} \\frac{|x|}{x}$.", type: "mcq", answer: "Does not exist", choices: ["$0$", "$1$", "$-1$", "Does not exist"], explanation: "Right limit $1$, left limit $-1$.", difficulty: "medium" },
        { prompt: "Evaluate $\\lim_{x\\to 2} \\frac{x^2-5x+6}{x-2}$.", type: "numeric", answer: "-1", explanation: "Factor $(x-2)(x-3)$; cancel; $x-3 \\to -1$.", difficulty: "hard" },
        { prompt: "True or false: if $\\lim_{x\\to a} f(x)$ exists, it is unique.", type: "mcq", answer: "True", choices: ["True", "False", "True only for polynomials", "True only if $f(a)$ exists"], explanation: "Limits are unique when they exist.", difficulty: "hard" },
        { prompt: "Evaluate $\\lim_{x\\to \\infty} \\frac{3x^2+1}{x^2-4}$.", type: "numeric", answer: "3", explanation: "Leading coefficients ratio: $3/1=3$.", difficulty: "hard" },
        { prompt: "For $f(x)=\\begin{cases} x+1 & x<0 \\\\ x^2 & x\\ge 0 \\end{cases}$, find $\\lim_{x\\to 0} f(x)$ if it exists.", type: "mcq", answer: "Does not exist", choices: ["$0$", "$1$", "Does not exist", "$2$"], explanation: "Left limit $1$, right limit $0$.", difficulty: "hard" },
      ],
    },
  ],
};