import type { SubjectSpec } from "../seed-tier1-diagnostics-types";

function link(label: string, href: string) {
  return { label, href };
}

export const REAL_ANALYSIS: SubjectSpec = {
  slug: "real-analysis",
  idPrefix: "ra-diag-",
  prerequisites: [
    {
      id: "limits-continuity",
      slug: "lc",
      label: "Limits and continuity",
      description:
        "Evaluate limits, identify discontinuities, and apply continuity ideas from calculus.",
      reviewLinks: [
        link("Limits (calculus)", "/calculus/modules/limits"),
        link("Limits & continuity", "/real-analysis/modules/limits-and-continuity"),
      ],
      questions: [
        { prompt: "Evaluate $\\lim_{x\\to 2} (x^2-1)$.", type: "numeric", answer: "3", explanation: "$4-1=3$.", difficulty: "easy" },
        { prompt: "Is $f(x)=|x|$ continuous at $x=0$?", type: "mcq", answer: "Yes", choices: ["Yes", "No", "Only from the right", "Only if redefined"], explanation: "Absolute value is continuous everywhere.", difficulty: "easy" },
        { prompt: "Evaluate $\\lim_{x\\to 0} \\frac{\\sin x}{x}$.", type: "numeric", answer: "1", explanation: "Fundamental trigonometric limit.", difficulty: "easy" },
        { prompt: "At $x=1$, $f(x)=\\frac{1}{x-1}$ is:", type: "mcq", answer: "Undefined", choices: ["Continuous", "Undefined", "Equal to $0$", "Equal to $1$"], explanation: "Denominator is zero at $x=1$.", difficulty: "easy" },
        { prompt: "Evaluate $\\lim_{x\\to 3} \\frac{x^2-9}{x-3}$.", type: "numeric", answer: "6", explanation: "Cancel $(x-3)$: limit is $x+3 \\to 6$.", difficulty: "easy" },
        { prompt: "If $f$ is continuous on $[a,b]$, must it attain a maximum on $[a,b]$?", type: "mcq", answer: "Yes (Extreme Value Theorem)", choices: ["Yes (Extreme Value Theorem)", "No, never", "Only if differentiable", "Only on open intervals"], explanation: "Continuous functions on closed bounded intervals attain extrema.", difficulty: "medium" },
        { prompt: "Evaluate $\\lim_{x\\to 0} \\frac{1-\\cos x}{x^2}$.", type: "numeric", answer: "1/2", explanation: "Standard limit using Taylor or trig identities.", difficulty: "medium" },
        { prompt: "A function has $\\lim_{x\\to 2} f(x)=5$ but $f(2)=1$. This suggests:", type: "mcq", answer: "A removable discontinuity at $x=2$", choices: ["No issue", "A removable discontinuity at $x=2$", "An infinite discontinuity", "$f$ is constant"], explanation: "Limit exists but differs from the function value.", difficulty: "medium" },
        { prompt: "Evaluate $\\lim_{x\\to \\infty} \\frac{2x+1}{x-3}$.", type: "numeric", answer: "2", explanation: "Ratio of leading coefficients.", difficulty: "medium" },
        { prompt: "If $f(x)=\\begin{cases} x^2 & x<1 \\\\ 2x & x\\ge 1 \\end{cases}$, is $f$ continuous at $x=1$?", type: "mcq", answer: "Yes", choices: ["Yes", "No", "Only from the left", "Cannot determine"], explanation: "Both pieces give $f(1)=2$ and limits agree.", difficulty: "medium" },
        { prompt: "Evaluate $\\lim_{x\\to 0^+} \\ln x$.", type: "mcq", answer: "Approaches $-\\infty$", choices: ["$0$", "$1$", "Approaches $-\\infty$", "Does not exist"], explanation: "Logarithm blows up negatively near $0^+$.", difficulty: "medium" },
        { prompt: "Evaluate $\\lim_{x\\to 4} \\sqrt{x-1}$.", type: "numeric", answer: "sqrt(3)", explanation: "$\\sqrt{3}$ by direct substitution.", difficulty: "medium" },
        { prompt: "True or false: if $f$ is continuous at $a$, then $\\lim_{x\\to a} f(x)=f(a)$.", type: "mcq", answer: "True", choices: ["True", "False", "True only for polynomials", "True only if $f'(a)$ exists"], explanation: "This is the definition of continuity at $a$.", difficulty: "medium" },
        { prompt: "Evaluate $\\lim_{x\\to 0} \\frac{e^x-1}{x}$.", type: "numeric", answer: "1", explanation: "Derivative of $e^x$ at $0$, or standard limit.", difficulty: "hard" },
        { prompt: "If $f$ is continuous on $[0,1]$ with $f(0)=-1$ and $f(1)=2$, must $f(c)=0$ for some $c$?", type: "mcq", answer: "Yes (Intermediate Value Theorem)", choices: ["Yes (Intermediate Value Theorem)", "No", "Only if differentiable", "Only if $f$ is linear"], explanation: "IVT guarantees a zero crossing.", difficulty: "hard" },
        { prompt: "Evaluate $\\lim_{x\\to 0} \\frac{\\sqrt{1+x}-1}{x}$.", type: "numeric", answer: "1/2", explanation: "Multiply by conjugate or use binomial approximation.", difficulty: "hard" },
      ],
    },
    {
      id: "differentiation",
      slug: "diff",
      label: "Differentiation",
      description:
        "Compute derivatives, interpret rates of change, and apply basic differentiation rules.",
      reviewLinks: [
        link("Derivatives", "/calculus/modules/derivatives"),
        link("Differentiation", "/real-analysis/modules/differentiation"),
      ],
      questions: [
        { prompt: "Find $\\frac{d}{dx}(x^3)$.", type: "numeric", answer: "3x^2", explanation: "Power rule.", difficulty: "easy" },
        { prompt: "Find $\\frac{d}{dx}(5x)$.", type: "numeric", answer: "5", explanation: "Derivative of linear function.", difficulty: "easy" },
        { prompt: "Find $\\frac{d}{dx}(\\sin x)$.", type: "mcq", answer: "$\\cos x$", choices: ["$\\cos x$", "$-\\cos x$", "$\\sin x$", "$-\\sin x$"], explanation: "Standard derivative of sine.", difficulty: "easy" },
        { prompt: "Find $\\frac{d}{dx}(e^x)$.", type: "numeric", answer: "e^x", explanation: "Exponential is its own derivative.", difficulty: "easy" },
        { prompt: "Find $\\frac{d}{dx}(x^2+3x+1)$.", type: "numeric", answer: "2x+3", explanation: "Sum rule and power rule.", difficulty: "easy" },
        { prompt: "Find $\\frac{d}{dx}(\\ln x)$ for $x>0$.", type: "numeric", answer: "1/x", explanation: "Derivative of natural log.", difficulty: "medium" },
        { prompt: "Find $\\frac{d}{dx}(x\\sin x)$.", type: "mcq", answer: "$\\sin x + x\\cos x$", choices: ["$\\sin x + x\\cos x$", "$x\\cos x$", "$\\cos x$", "$\\sin x$"], explanation: "Product rule.", difficulty: "medium" },
        { prompt: "Find $\\frac{d}{dx}\\left(\\frac{1}{x}\\right)$ for $x\\ne 0$.", type: "numeric", answer: "-1/x^2", explanation: "Rewrite as $x^{-1}$.", difficulty: "medium" },
        { prompt: "If $f(x)=x^2$, what is $f'(2)$?", type: "numeric", answer: "4", explanation: "$f'(x)=2x$, so $f'(2)=4$.", difficulty: "medium" },
        { prompt: "Find $\\frac{d}{dx}(\\cos x)$.", type: "mcq", answer: "$-\\sin x$", choices: ["$\\sin x$", "$-\\sin x$", "$\\cos x$", "$-\\cos x$"], explanation: "Derivative of cosine.", difficulty: "medium" },
        { prompt: "Find $\\frac{d}{dx}(\\sqrt{x})$ for $x>0$.", type: "numeric", answer: "1/(2sqrt(x))", explanation: "Power rule on $x^{1/2}$.", difficulty: "medium" },
        { prompt: "If $f'(x)>0$ on an interval, then $f$ is:", type: "mcq", answer: "Increasing", choices: ["Decreasing", "Increasing", "Constant", "Undefined"], explanation: "Positive derivative means increasing.", difficulty: "medium" },
        { prompt: "Find $\\frac{d}{dx}(\\tan x)$.", type: "mcq", answer: "$\\sec^2 x$", choices: ["$\\sec^2 x$", "$\\tan^2 x$", "$1/\\cos^2 x$", "Both first and third"], explanation: "$\\sec^2 x = 1/\\cos^2 x$.", difficulty: "hard" },
        { prompt: "Find $\\frac{d}{dx}(x^2 e^x)$.", type: "numeric", answer: "e^x(x^2+2x)", explanation: "Product rule: $2xe^x + x^2 e^x$.", difficulty: "hard" },
        { prompt: "If $f(x)=|x|$, is $f$ differentiable at $x=0$?", type: "mcq", answer: "No", choices: ["Yes", "No", "Yes, with derivative $0$", "Yes, with derivative $1$"], explanation: "Corner at the origin breaks differentiability.", difficulty: "hard" },
        { prompt: "Find $\\frac{d}{dx}\\left(\\frac{x}{x+1}\\right)$ for $x\\ne -1$.", type: "numeric", answer: "1/(x+1)^2", explanation: "Quotient rule or simplify first.", difficulty: "hard" },
      ],
    },
    {
      id: "integration",
      slug: "int",
      label: "Integration",
      description:
        "Evaluate basic integrals, interpret area accumulation, and use the fundamental theorem of calculus.",
      reviewLinks: [
        link("Integrals", "/calculus/modules/integrals"),
        link("Riemann integration", "/real-analysis/modules/riemann-integration"),
      ],
      questions: [
        { prompt: "Evaluate $\\int_0^1 2x\\,dx$.", type: "numeric", answer: "1", explanation: "Antiderivative $x^2$, evaluate $1-0=1$.", difficulty: "easy" },
        { prompt: "Evaluate $\\int_0^{\\pi} \\sin x\\,dx$.", type: "numeric", answer: "2", explanation: "$[-\\cos x]_0^{\\pi} = 2$.", difficulty: "easy" },
        { prompt: "Evaluate $\\int 3x^2\\,dx$ (indefinite, $+C$ omitted).", type: "numeric", answer: "x^3", explanation: "Reverse power rule.", difficulty: "easy" },
        { prompt: "Evaluate $\\int_0^1 1\\,dx$.", type: "numeric", answer: "1", explanation: "Length of interval.", difficulty: "easy" },
        { prompt: "If $F'(x)=f(x)$, then $\\int_a^b f(x)\\,dx$ equals:", type: "mcq", answer: "$F(b)-F(a)$", choices: ["$F(b)-F(a)$", "$F(a)-F(b)$", "$F'(b)-F'(a)$", "$f(b)-f(a)$"], explanation: "Fundamental Theorem of Calculus Part II.", difficulty: "easy" },
        { prompt: "Evaluate $\\int_0^2 (x+1)\\,dx$.", type: "numeric", answer: "4", explanation: "$[x^2/2 + x]_0^2 = 2+2=4$.", difficulty: "medium" },
        { prompt: "Evaluate $\\int_1^e \\frac{1}{x}\\,dx$.", type: "numeric", answer: "1", explanation: "$\\ln x$ from $1$ to $e$ gives $1$.", difficulty: "medium" },
        { prompt: "Evaluate $\\int_0^{\\pi/2} \\cos x\\,dx$.", type: "numeric", answer: "1", explanation: "$[\\sin x]_0^{\\pi/2}=1$.", difficulty: "medium" },
        { prompt: "Which integral gives the area under $y=x$ from $0$ to $3$?", type: "mcq", answer: "$\\int_0^3 x\\,dx$", choices: ["$\\int_0^3 x\\,dx$", "$\\int_0^3 x^2\\,dx$", "$\\int_0^1 x\\,dx$", "$\\int_3^0 x\\,dx$"], explanation: "Area requires integrating on $[0,3]$.", difficulty: "medium" },
        { prompt: "Evaluate $\\int_0^1 x^2\\,dx$.", type: "numeric", answer: "1/3", explanation: "$[x^3/3]_0^1 = 1/3$.", difficulty: "medium" },
        { prompt: "If $\\int_0^2 f(x)\\,dx = 5$, what is $\\int_0^2 3f(x)\\,dx$?", type: "numeric", answer: "15", explanation: "Constants factor out of integrals.", difficulty: "medium" },
        { prompt: "Evaluate $\\int (e^x)\\,dx$.", type: "numeric", answer: "e^x", explanation: "$e^x$ is its own antiderivative.", difficulty: "medium" },
        { prompt: "Evaluate $\\int_0^1 (4x^3)\\,dx$.", type: "numeric", answer: "1", explanation: "Antiderivative $x^4$.", difficulty: "hard" },
        { prompt: "True or false: $\\int_a^a f(x)\\,dx = 0$.", type: "mcq", answer: "True", choices: ["True", "False", "True only if $f(a)=0$", "Depends on $f$"], explanation: "Zero-width interval gives zero integral.", difficulty: "hard" },
        { prompt: "Evaluate $\\int_0^{\\pi} x\\sin x\\,dx$ (to nearest integer).", type: "numeric", answer: "pi", explanation: "Integration by parts yields $\\pi$.", difficulty: "hard" },
        { prompt: "If $f$ is odd, $\\int_{-a}^a f(x)\\,dx$ equals:", type: "mcq", answer: "$0$", choices: ["$0$", "$2\\int_0^a f(x)\\,dx$", "$a$", "Undefined"], explanation: "Odd integrands cancel over symmetric intervals.", difficulty: "hard" },
      ],
    },
    {
      id: "sequences-series",
      slug: "seq",
      label: "Sequences and series",
      description:
        "Analyze convergence of sequences and series, and apply basic convergence tests.",
      reviewLinks: [
        link("Series & sequences", "/calculus/modules/series"),
        link("Sequences & series", "/real-analysis/modules/sequences-and-series"),
      ],
      questions: [
        { prompt: "What is $\\lim_{n\\to\\infty} \\frac{1}{n}$?", type: "numeric", answer: "0", explanation: "Reciprocals shrink to zero.", difficulty: "easy" },
        { prompt: "What is $\\lim_{n\\to\\infty} \\frac{n}{n+1}$?", type: "numeric", answer: "1", explanation: "Divide numerator and denominator by $n$.", difficulty: "easy" },
        { prompt: "Is the sequence $a_n=(-1)^n$ convergent?", type: "mcq", answer: "No", choices: ["Yes", "No", "Yes, to $0$", "Yes, to $1$"], explanation: "It oscillates between $-1$ and $1$.", difficulty: "easy" },
        { prompt: "What is the sum $\\sum_{n=1}^{\\infty} \\frac{1}{2^n}$?", type: "numeric", answer: "1", explanation: "Geometric series with $r=1/2$.", difficulty: "easy" },
        { prompt: "Does $\\sum_{n=1}^{\\infty} \\frac{1}{n}$ converge?", type: "mcq", answer: "No (harmonic series diverges)", choices: ["Yes", "No (harmonic series diverges)", "Only conditionally", "Converges to $0$"], explanation: "Harmonic series diverges.", difficulty: "easy" },
        { prompt: "What is $\\lim_{n\\to\\infty} \\left(1+\\frac{1}{n}\\right)^n$?", type: "numeric", answer: "e", explanation: "Definition of $e$.", difficulty: "medium" },
        { prompt: "For $\\sum a_n$, if $\\lim_{n\\to\\infty} a_n \\ne 0$, the series:", type: "mcq", answer: "Diverges", choices: ["Converges", "Diverges", "May still converge", "Converges absolutely"], explanation: "Terms must approach zero for convergence.", difficulty: "medium" },
        { prompt: "Does $\\sum_{n=1}^{\\infty} \\frac{1}{n^2}$ converge?", type: "mcq", answer: "Yes", choices: ["Yes", "No", "Only if truncated", "Oscillates"], explanation: "$p$-series with $p=2>1$.", difficulty: "medium" },
        { prompt: "What is $\\lim_{n\\to\\infty} \\frac{3n^2+1}{n^2+4}$?", type: "numeric", answer: "3", explanation: "Leading-term ratio.", difficulty: "medium" },
        { prompt: "A sequence bounded and monotone must:", type: "mcq", answer: "Converge", choices: ["Diverge", "Converge", "Oscillate forever", "Be constant"], explanation: "Monotone convergence theorem for sequences.", difficulty: "medium" },
        { prompt: "What is the $n$th partial sum of $1+1+1+\\cdots$ after $n$ terms?", type: "numeric", answer: "n", explanation: "Each term is $1$.", difficulty: "medium" },
        { prompt: "Does $\\sum_{n=0}^{\\infty} r^n$ converge for $r=1/3$?", type: "mcq", answer: "Yes", choices: ["Yes", "No", "Only for $r=1$", "Only if $r<0$"], explanation: "Geometric series converges when $|r|<1$.", difficulty: "medium" },
        { prompt: "If $a_n\\to L$ and $b_n\\to M$, then $a_n+b_n\\to$:", type: "mcq", answer: "$L+M$", choices: ["$L+M$", "$LM$", "$L-M$", "Need not converge"], explanation: "Limit laws for sequences.", difficulty: "hard" },
        { prompt: "Is $\\sum_{n=1}^{\\infty} \\frac{(-1)^{n+1}}{n}$ convergent?", type: "mcq", answer: "Yes (conditionally)", choices: ["No", "Yes (conditionally)", "Yes (absolutely)", "Diverges to $\\infty$"], explanation: "Alternating harmonic series converges conditionally.", difficulty: "hard" },
        { prompt: "What is $\\lim_{n\\to\\infty} \\frac{\\sin n}{n}$?", type: "numeric", answer: "0", explanation: "Bounded numerator, growing denominator.", difficulty: "hard" },
        { prompt: "If $\\sum |a_n|$ converges, we say the series is:", type: "mcq", answer: "Absolutely convergent", choices: ["Conditionally convergent", "Absolutely convergent", "Divergent", "Oscillatory"], explanation: "Definition of absolute convergence.", difficulty: "hard" },
      ],
    },
    {
      id: "proof-reasoning",
      slug: "proof",
      label: "Proof reasoning",
      description:
        "Read and write direct proofs, contrapositives, contradictions, and quantified statements.",
      reviewLinks: [
        link("Formal systems & proofs", "/mathematical-logic/modules/formal-systems"),
        link("Predicate logic", "/mathematical-logic/modules/predicate-logic"),
      ],
      questions: [
        { prompt: "To prove $P\\Rightarrow Q$ by contrapositive, you prove:", type: "mcq", answer: "$\\neg Q \\Rightarrow \\neg P$", choices: ["$Q \\Rightarrow P$", "$\\neg Q \\Rightarrow \\neg P$", "$P \\Rightarrow \\neg Q$", "$\\neg P \\Rightarrow Q$"], explanation: "Contrapositive is logically equivalent.", difficulty: "easy" },
        { prompt: "Proof by contradiction starts by assuming:", type: "mcq", answer: "The negation of what you want to prove", choices: ["The conclusion is true", "The negation of what you want to prove", "Nothing", "Both $P$ and $\\neg P$"], explanation: "Assume opposite and derive contradiction.", difficulty: "easy" },
        { prompt: "The statement $\\forall x\\,\\exists y\\,P(x,y)$ means:", type: "mcq", answer: "For every $x$ there is some $y$ (possibly depending on $x$)", choices: ["There is one $y$ for all $x$", "For every $x$ there is some $y$ (possibly depending on $x$)", "For some $x$, for all $y$", "There exist no such $x,y$"], explanation: "Order of quantifiers matters.", difficulty: "easy" },
        { prompt: "Which is the negation of $\\forall x, P(x)$?", type: "mcq", answer: "$\\exists x, \\neg P(x)$", choices: ["$\\forall x, \\neg P(x)$", "$\\exists x, \\neg P(x)$", "$\\neg\\forall x, P(x)$ only", "$\\exists x, P(x)$"], explanation: "Negating universal gives existential.", difficulty: "easy" },
        { prompt: "A direct proof of $P\\Rightarrow Q$ assumes:", type: "mcq", answer: "$P$ and derives $Q$", choices: ["$Q$ and derives $P$", "$P$ and derives $Q$", "$\\neg P$", "Nothing"], explanation: "Direct proof: assume hypothesis, prove conclusion.", difficulty: "easy" },
        { prompt: "If $n$ is even, then $n^2$ is even. The hypothesis is:", type: "mcq", answer: "$n$ is even", choices: ["$n^2$ is even", "$n$ is even", "$n$ is odd", "$n^2$ is odd"], explanation: "Hypothesis follows 'if'.", difficulty: "medium" },
        { prompt: "To disprove $\\forall x, P(x)$, you must:", type: "mcq", answer: "Find one $x$ with $\\neg P(x)$", choices: ["Prove $P(x)$ for all $x$", "Find one $x$ with $\\neg P(x)$", "Assume $P(x)$", "Use induction"], explanation: "One counterexample refutes a universal claim.", difficulty: "medium" },
        { prompt: "Mathematical induction proves statements about:", type: "mcq", answer: "Natural numbers (or well-ordered sets)", choices: ["All real numbers", "Natural numbers (or well-ordered sets)", "Only finite sets", "Only primes"], explanation: "Induction is for integer-indexed claims.", difficulty: "medium" },
        { prompt: "Which is logically equivalent to $P\\Rightarrow Q$?", type: "mcq", answer: "$\\neg P \\lor Q$", choices: ["$P \\land Q$", "$\\neg P \\lor Q$", "$\\neg Q \\Rightarrow \\neg P$ only", "$P \\lor Q$"], explanation: "Material implication equivalence.", difficulty: "medium" },
        { prompt: "In a proof, 'WLOG' usually means:", type: "mcq", answer: "Without loss of generality", choices: ["With lots of generality", "Without loss of generality", "We leave out generality", "When logic obtains generality"], explanation: "Reduce to a representative case.", difficulty: "medium" },
        { prompt: "If $a\\mid b$ and $b\\mid c$, then:", type: "mcq", answer: "$a\\mid c$", choices: ["$a\\mid c$", "$c\\mid a$", "$a=c$", "Nothing necessarily"], explanation: "Divisibility is transitive.", difficulty: "medium" },
        { prompt: "A statement and its contrapositive are:", type: "mcq", answer: "Logically equivalent", choices: ["Always opposites", "Logically equivalent", "Never equivalent", "Independent"], explanation: "$P\\Rightarrow Q \\equiv \\neg Q\\Rightarrow \\neg P$.", difficulty: "medium" },
        { prompt: "Proof by cases is appropriate when:", type: "mcq", answer: "The hypothesis splits into exhaustive scenarios", choices: ["You cannot write anything", "The hypothesis splits into exhaustive scenarios", "Only for geometry", "Only for contradiction"], explanation: "Cover all cases separately.", difficulty: "hard" },
        { prompt: "The converse of $P\\Rightarrow Q$ is:", type: "mcq", answer: "$Q\\Rightarrow P$", choices: ["$\\neg P\\Rightarrow \\neg Q$", "$Q\\Rightarrow P$", "$\\neg Q\\Rightarrow \\neg P$", "$P\\Rightarrow \\neg Q$"], explanation: "Swap hypothesis and conclusion.", difficulty: "hard" },
        { prompt: "If a proof uses an undefined term without definition, it is:", type: "mcq", answer: "Incomplete or invalid", choices: ["Always fine", "Incomplete or invalid", "Preferred style", "Only wrong in logic courses"], explanation: "Definitions are required for rigor.", difficulty: "hard" },
        { prompt: "To prove $\\exists x, P(x)$ constructively, you should:", type: "mcq", answer: "Exhibit a specific $x$ and verify $P(x)$", choices: ["Assume no such $x$", "Exhibit a specific $x$ and verify $P(x)$", "Prove for all $x$", "Use only contradiction"], explanation: "Existence proofs often give an example.", difficulty: "hard" },
      ],
    },
    {
      id: "epsilon-delta-comfort",
      slug: "ed",
      label: "Epsilon-delta comfort",
      description:
        "Interpret $\\varepsilon$-$\\delta$ definitions of limits and continuity at an intuitive level.",
      reviewLinks: [
        link("Limits & continuity", "/real-analysis/modules/limits-and-continuity"),
        link("Real number system", "/real-analysis/modules/real-number-system"),
      ],
      questions: [
        { prompt: "In $\\lim_{x\\to a} f(x)=L$, the number $\\varepsilon$ represents:", type: "mcq", answer: "How close we want $f(x)$ to $L$", choices: ["How close $x$ is to $a$", "How close we want $f(x)$ to $L$", "The value of $f(a)$", "The slope at $a$"], explanation: "$\\varepsilon$ controls output tolerance.", difficulty: "easy" },
        { prompt: "In an $\\varepsilon$-$\\delta$ proof, $\\delta$ controls:", type: "mcq", answer: "How close $x$ must be to $a$", choices: ["How close $f(x)$ is to $L$", "How close $x$ must be to $a$", "The derivative", "The integral"], explanation: "$\\delta$ is input closeness.", difficulty: "easy" },
        { prompt: "To show $\\lim_{x\\to 2} 3x = 6$, given $\\varepsilon>0$, we can pick $\\delta=$:", type: "mcq", answer: "$\\varepsilon/3$", choices: ["$\\varepsilon$", "$\\varepsilon/3$", "$3\\varepsilon$", "$\\sqrt{\\varepsilon}$"], explanation: "$|3x-6|=3|x-2|<\\varepsilon$ when $|x-2|<\\varepsilon/3$.", difficulty: "easy" },
        { prompt: "If $\\lim_{x\\to a} f(x)=L$, must $f(a)=L$ for the limit definition to matter?", type: "mcq", answer: "No", choices: ["Yes, always", "No", "Only for polynomials", "Only if continuous"], explanation: "Limits concern approach, not necessarily the value.", difficulty: "easy" },
        { prompt: "Uniform continuity is stronger than continuity because:", type: "mcq", answer: "One $\\delta$ works for all points for each $\\varepsilon$", choices: ["It uses bigger $\\varepsilon$", "One $\\delta$ works for all points for each $\\varepsilon$", "It only applies at one point", "It ignores $\\varepsilon$"], explanation: "Uniformity: $\\delta$ depends only on $\\varepsilon$.", difficulty: "medium" },
        { prompt: "If $f(x)=x^2$, proving $\\lim_{x\\to 1} f(x)=1$ requires controlling:", type: "mcq", answer: "$|x^2-1|$ near $x=1$", choices: ["$|x-1|$ only", "$|x^2-1|$ near $x=1$", "$f'(1)$", "$\\int f$"], explanation: "Output distance from $L=1$.", difficulty: "medium" },
        { prompt: "The phrase '$f$ is continuous at $a$' in $\\varepsilon$-$\\delta$ form means:", type: "mcq", answer: "For every $\\varepsilon>0$ there exists $\\delta>0$ with $|x-a|<\\delta \\Rightarrow |f(x)-f(a)|<\\varepsilon$", choices: ["$f(a)=0$", "For every $\\varepsilon>0$ there exists $\\delta>0$ with $|x-a|<\\delta \\Rightarrow |f(x)-f(a)|<\\varepsilon$", "$f'(a)$ exists", "$\\lim_{x\\to a} f(x)$ need not exist"], explanation: "Continuity ties limit to function value.", difficulty: "medium" },
        { prompt: "If a limit fails to exist at $a$, can $f$ still satisfy an $\\varepsilon$-$\\delta$ limit definition there?", type: "mcq", answer: "No", choices: ["Yes", "No", "Sometimes", "Only for rationals"], explanation: "No limit means no $\\varepsilon$-$\\delta$ satisfaction.", difficulty: "medium" },
        { prompt: "For $f(x)=\\frac{1}{x}$ on $(0,1)$, uniform continuity fails because:", type: "mcq", answer: "Near $0$, small $x$-changes cause large output changes", choices: ["It is constant", "Near $0$, small $x$-changes cause large output changes", "It is bounded", "It is differentiable"], explanation: "Blow-up near $0$ breaks uniform $\\delta$.", difficulty: "medium" },
        { prompt: "Completeness of $\\mathbb{R}$ is used in analysis to ensure:", type: "mcq", answer: "Cauchy sequences converge in $\\mathbb{R}$", choices: ["All functions are continuous", "Cauchy sequences converge in $\\mathbb{R}$", "No irrational numbers", "All sets are open"], explanation: "Completeness underpins limit existence.", difficulty: "medium" },
        { prompt: "If $|f(x)-L|<\\varepsilon$ whenever $0<|x-a|<\\delta$, we say:", type: "mcq", answer: "$\\lim_{x\\to a} f(x)=L$", choices: ["$f(a)=L$ necessarily", "$\\lim_{x\\to a} f(x)=L$", "$f$ is differentiable", "$f$ is bounded"], explanation: "This is the limit definition.", difficulty: "medium" },
        { prompt: "A sequential definition of limit uses:", type: "mcq", answer: "Sequences $x_n\\to a$ with $x_n\\ne a$", choices: ["Only derivatives", "Sequences $x_n\\to a$ with $x_n\\ne a$", "Only integrals", "Only rationals"], explanation: "Heine definition via sequences.", difficulty: "hard" },
        { prompt: "To disprove $\\lim_{x\\to 0} f(x)=0$, you can:", type: "mcq", answer: "Find $\\varepsilon>0$ such that no $\\delta$ works", choices: ["Pick any $\\delta$", "Find $\\varepsilon>0$ such that no $\\delta$ works", "Assume the limit is $0$", "Only graph $f$"], explanation: "Negation: some output tolerance cannot be met.", difficulty: "hard" },
        { prompt: "Lipschitz continuity implies:", type: "mcq", answer: "Uniform continuity", choices: ["Only pointwise continuity", "Uniform continuity", "Differentiability always", "Constant function"], explanation: "Lipschitz is a strong uniform control.", difficulty: "hard" },
        { prompt: "In analysis, '$\\forall \\varepsilon>0, \\exists \\delta>0$' quantifier order matters because:", type: "mcq", answer: "$\\delta$ may depend on $\\varepsilon$", choices: ["$\\varepsilon$ depends on $\\delta$ always", "$\\delta$ may depend on $\\varepsilon$", "They are independent always", "Order never matters"], explanation: "Standard limit form: $\\delta=\\delta(\\varepsilon)$.", difficulty: "hard" },
        { prompt: "If $f$ is continuous on $[a,b]$, it is uniformly continuous on $[a,b]$ because:", type: "mcq", answer: "Closed bounded interval (Heine–Cantor)", choices: ["Open intervals always work", "Closed bounded interval (Heine–Cantor)", "Only if linear", "Never true"], explanation: "Heine–Cantor theorem.", difficulty: "hard" },
      ],
    },
  ],
};