import type { Problem } from "../shared-types";

const p = (problem: Problem) => problem;

export const continuousDistributionProblems: Problem[] = [
  // --- Easy (14) ---
  p({ id: "cont-zscore-1", topicId: "continuous-distributions", section: "normal", type: "numeric", difficulty: "easy",
    prompt: "A dataset has $\\mu=50$, $\\sigma=10$. What is the $z$-score for $x=65$?",
    answer: "1.5",
    explanation: "Step 1: $z=(x-\\mu)/\\sigma=(65-50)/10=1.5$. Final answer: $1.5$." }),
  p({ id: "cont-empirical-1", topicId: "continuous-distributions", section: "normal", type: "mcq", difficulty: "easy",
    prompt: "By the empirical rule, approximately what $\\%$ of data falls within $\\pm2\\sigma$ of the mean?",
    answer: "95%",
    choices: ["68%", "95%", "99.7%", "50%"],
    explanation: "Step 1: 68-95-99.7 rule: $\\pm1\\sigma\\to68\\%$, $\\pm2\\sigma\\to95\\%$, $\\pm3\\sigma\\to99.7\\%$. Final answer: $95\\%$." }),
  p({ id: "cont-normal-std-1", topicId: "continuous-distributions", section: "normal", type: "mcq", difficulty: "easy",
    prompt: "The standard normal $Z\\sim N(\\mu,\\sigma)$ has:",
    answer: "$\\mu=0$, $\\sigma=1$",
    choices: ["$\\mu=0$, $\\sigma=1$", "$\\mu=1$, $\\sigma=0$", "$\\mu=0$, $\\sigma=0$", "$\\mu=1$, $\\sigma=1$"],
    explanation: "Step 1: $Z\\sim N(0,1)$ by definition. Final answer: $\\mu=0$, $\\sigma=1$." }),
  p({ id: "cont-exp-mean-1", topicId: "continuous-distributions", section: "exponential", type: "numeric", difficulty: "easy",
    prompt: "An exponential distribution has rate $\\lambda=2$. What is its mean?",
    answer: "0.5",
    explanation: "Step 1: $E(X)=1/\\lambda=1/2=0.5$. Final answer: $0.5$." }),
  p({ id: "cont-normal-1", topicId: "continuous-distributions", section: "normal", type: "numeric", difficulty: "easy",
    prompt: "For $X\\sim N(100,15^2)$, what is the $z$-score of $x=130$?",
    answer: "2",
    explanation: "Step 1: $z=(130-100)/15=30/15=2$. Final answer: $2$." }),
  p({ id: "cont-pdf-1", topicId: "continuous-distributions", section: "pdf", type: "mcq", difficulty: "easy",
    prompt: "For a continuous random variable, $P(X=c)$ for any specific value $c$ is:",
    answer: "$0$",
    choices: ["$f(c)$", "$0$", "$F(c)$", "$1$"],
    explanation: "Step 1: For continuous distributions, the probability of any single exact point is $0$: $P(X=c)=\\int_c^c f(x)\\,dx=0$. Final answer: $0$." }),
  p({ id: "cont-uniform-1", topicId: "continuous-distributions", section: "exponential", type: "numeric", difficulty: "easy",
    prompt: "For $X\\sim\\text{Uniform}(0,10)$, what is $E(X)$?",
    answer: "5",
    explanation: "Step 1: $E(X)=(a+b)/2=(0+10)/2=5$. Final answer: $5$." }),
  p({ id: "cont-normal-2", topicId: "continuous-distributions", section: "normal", type: "mcq", difficulty: "easy",
    prompt: "A normal distribution is symmetric about its:",
    answer: "Mean.",
    choices: ["Median only.", "Mode only.", "Mean.", "Standard deviation."],
    explanation: "Step 1: The normal distribution is perfectly symmetric about $\\mu$, where mean $=$ median $=$ mode. Final answer: Mean." }),
  p({ id: "cont-pdf-2", topicId: "continuous-distributions", section: "pdf", type: "mcq", difficulty: "easy",
    prompt: "For a valid PDF $f(x)$, which must hold?",
    answer: "$f(x)\\geq0$ and $\\int_{-\\infty}^{\\infty}f(x)\\,dx=1$",
    choices: ["$f(x)\\leq1$ for all $x$.", "$f(x)\\geq0$ and $\\int_{-\\infty}^{\\infty}f(x)\\,dx=1$", "$f(x)=1/\\sigma$", "$f(x)$ is increasing."],
    explanation: "Step 1: A valid PDF requires non-negativity and total area of 1. Final answer: $f(x)\\geq0$ and $\\int_{-\\infty}^{\\infty}f(x)\\,dx=1$." }),
  p({ id: "cont-exp-var-1", topicId: "continuous-distributions", section: "exponential", type: "numeric", difficulty: "easy",
    prompt: "Exponential distribution with $\\lambda=4$: what is the variance?",
    answer: "0.0625",
    explanation: "Step 1: $\\text{Var}(X)=1/\\lambda^2=1/16=0.0625$. Final answer: $0.0625$." }),
  p({ id: "cont-normal-3", topicId: "continuous-distributions", section: "normal", type: "numeric", difficulty: "easy",
    prompt: "$X\\sim N(0,1)$. What is $P(Z<0)$?",
    answer: "0.5",
    explanation: "Step 1: The standard normal is symmetric about $0$: $P(Z<0)=0.5$. Final answer: $0.5$." }),
  p({ id: "cont-pdf-3", topicId: "continuous-distributions", section: "pdf", type: "mcq", difficulty: "easy",
    prompt: "The CDF $F(x)$ is defined as:",
    answer: "$P(X\\leq x)$",
    choices: ["$P(X=x)$", "$P(X\\leq x)$", "$f(x)$", "$P(X>x)$"],
    explanation: "Step 1: $F(x)=P(X\\leq x)=\\int_{-\\infty}^x f(t)\\,dt$. Final answer: $P(X\\leq x)$." }),
  p({ id: "cont-uniform-2", topicId: "continuous-distributions", section: "exponential", type: "numeric", difficulty: "easy",
    prompt: "$X\\sim\\text{Uniform}(2,8)$. Find $\\text{Var}(X)=(b-a)^2/12$.",
    answer: "3",
    explanation: "Step 1: $\\text{Var}(X)=(8-2)^2/12=36/12=3$. Final answer: $3$." }),
  p({ id: "cont-approximation-1", topicId: "continuous-distributions", section: "approximation", type: "mcq", difficulty: "easy",
    prompt: "The normal approximation to the binomial uses continuity correction. $P(X=k)\\approx P(k-0.5<Y<k+0.5)$ where $Y\\sim N(np,np(1-p))$. This is called:",
    answer: "Continuity correction.",
    choices: ["Central limit theorem.", "Continuity correction.", "Poisson approximation.", "Delta method."],
    explanation: "Step 1: When approximating a discrete binomial with a continuous normal, continuity correction adds $\\pm0.5$ for better accuracy. Final answer: Continuity correction." }),

  // --- Medium (16) ---
  p({ id: "cont-normal-4", topicId: "continuous-distributions", section: "normal", type: "numeric", difficulty: "medium",
    prompt: "For $X\\sim N(70,10^2)$, find $P(60<X<80)$ using the empirical rule.",
    answer: "0.68",
    explanation: "Step 1: $60=70-10=\\mu-\\sigma$, $80=70+10=\\mu+\\sigma$. By empirical rule, $P(\\mu-\\sigma<X<\\mu+\\sigma)\\approx0.68$. Final answer: $0.68$." }),
  p({ id: "cont-exp-2", topicId: "continuous-distributions", section: "exponential", type: "numeric", difficulty: "medium",
    prompt: "For $X\\sim\\text{Exp}(\\lambda=0.5)$, find $P(X>2)=e^{-\\lambda\\cdot2}$.",
    answer: "0.3679",
    explanation: "Step 1: $P(X>2)=e^{-0.5\\times2}=e^{-1}\\approx0.3679$. Final answer: $0.3679$." }),
  p({ id: "cont-zscore-2", topicId: "continuous-distributions", section: "normal", type: "numeric", difficulty: "medium",
    prompt: "$X\\sim N(50,10^2)$. Using standard normal table $\\Phi(1.5)=0.9332$, find $P(X<65)$.",
    answer: "0.9332",
    explanation: "Step 1: $z=(65-50)/10=1.5$. Step 2: $P(X<65)=\\Phi(1.5)=0.9332$. Final answer: $0.9332$." }),
  p({ id: "cont-pdf-4", topicId: "continuous-distributions", section: "pdf", type: "numeric", difficulty: "medium",
    prompt: "For $X\\sim\\text{Uniform}(0,5)$, find $P(1\\leq X\\leq3)$.",
    answer: "0.4",
    explanation: "Step 1: $f(x)=1/(5-0)=0.2$. Step 2: $P(1\\leq X\\leq3)=(3-1)\\times0.2=2\\times0.2=0.4$. Final answer: $0.4$." }),
  p({ id: "cont-normal-5", topicId: "continuous-distributions", section: "normal", type: "numeric", difficulty: "medium",
    prompt: "$X\\sim N(\\mu,\\sigma^2)$. Find the $z$-score corresponding to the 84th percentile. ($\\Phi(1)=0.84$)",
    answer: "1",
    explanation: "Step 1: We need $z$ such that $\\Phi(z)=0.84$. Since $\\Phi(1)\\approx0.84$, $z=1$. Final answer: $1$." }),
  p({ id: "cont-exp-3", topicId: "continuous-distributions", section: "exponential", type: "mcq", difficulty: "medium",
    prompt: "The exponential distribution is memoryless, meaning:",
    answer: "$P(X>s+t|X>s)=P(X>t)$",
    choices: ["$P(X>s+t)=P(X>s)+P(X>t)$", "$P(X>s+t|X>s)=P(X>t)$", "$E(X|X>s)=E(X)$", "The CDF is constant."],
    explanation: "Step 1: Memoryless property: given survival past $s$, the remaining lifetime has the same distribution. Formally: $P(X>s+t|X>s)=P(X>t)$. Final answer: $P(X>s+t|X>s)=P(X>t)$." }),
  p({ id: "cont-normal-6", topicId: "continuous-distributions", section: "normal", type: "numeric", difficulty: "medium",
    prompt: "$\\Phi(1.96)\\approx0.975$. For $Z\\sim N(0,1)$, find $P(-1.96<Z<1.96)$.",
    answer: "0.95",
    explanation: "Step 1: $P(-1.96<Z<1.96)=\\Phi(1.96)-\\Phi(-1.96)=0.975-0.025=0.95$. Final answer: $0.95$." }),
  p({ id: "cont-pdf-5", topicId: "continuous-distributions", section: "pdf", type: "numeric", difficulty: "medium",
    prompt: "For $X\\sim\\text{Uniform}(0,1)$, find $E(X^2)=\\int_0^1 x^2\\,dx$.",
    answer: "0.333",
    explanation: "Step 1: $E(X^2)=\\int_0^1 x^2\\,dx=[x^3/3]_0^1=1/3\\approx0.333$. Final answer: $0.333$." }),
  p({ id: "cont-approximation-2", topicId: "continuous-distributions", section: "approximation", type: "numeric", difficulty: "medium",
    prompt: "$X\\sim B(100,0.5)$. Approximate using $N(50,25)$. Find $P(X\\leq55)\\approx\\Phi((55.5-50)/5)$.",
    answer: "0.8643",
    explanation: "Step 1: With continuity correction: $z=(55.5-50)/5=1.1$. $\\Phi(1.1)\\approx0.8643$. Final answer: $0.8643$." }),
  p({ id: "cont-exp-4", topicId: "continuous-distributions", section: "exponential", type: "numeric", difficulty: "medium",
    prompt: "Bus waiting times follow $\\text{Exp}(\\lambda=0.25)$ (mean $4$ min). $P(X\\leq4)=$",
    answer: "0.6321",
    explanation: "Step 1: $P(X\\leq4)=1-e^{-0.25\\times4}=1-e^{-1}\\approx1-0.3679=0.6321$. Final answer: $0.6321$." }),
  p({ id: "cont-normal-7", topicId: "continuous-distributions", section: "normal", type: "mcq", difficulty: "medium",
    prompt: "If $X\\sim N(\\mu,\\sigma^2)$, then $aX+b\\sim$",
    answer: "$N(a\\mu+b,a^2\\sigma^2)$",
    choices: ["$N(\\mu+b,\\sigma^2)$", "$N(a\\mu+b,a^2\\sigma^2)$", "$N(a\\mu,\\sigma^2+b)$", "$N(a\\mu+b,\\sigma^2)$"],
    explanation: "Step 1: Linear transformation of normal: $a X+b\\sim N(a\\mu+b,a^2\\sigma^2)$. Final answer: $N(a\\mu+b,a^2\\sigma^2)$." }),
  p({ id: "cont-pdf-6", topicId: "continuous-distributions", section: "pdf", type: "mcq", difficulty: "medium",
    prompt: "If $F(x)$ is the CDF, the PDF is:",
    answer: "$f(x)=F'(x)$",
    choices: ["$f(x)=F(x)$", "$f(x)=F'(x)$", "$f(x)=1-F(x)$", "$f(x)=\\int F(x)\\,dx$"],
    explanation: "Step 1: The PDF is the derivative of the CDF: $f(x)=dF/dx$. Final answer: $f(x)=F'(x)$." }),
  p({ id: "cont-approximation-3", topicId: "continuous-distributions", section: "approximation", type: "numeric", difficulty: "medium",
    prompt: "$X\\sim B(200,0.4)$. Normal approximation: $\\mu=80$, $\\sigma^2=48$, $\\sigma\\approx6.93$. Find $P(X\\geq90)\\approx P(Z\\geq(89.5-80)/6.93)$.",
    answer: "0.0857",
    explanation: "Step 1: $z=(89.5-80)/6.93\\approx1.37$. $P(Z\\geq1.37)=1-\\Phi(1.37)\\approx1-0.9147=0.0853\\approx0.0857$. Final answer: $0.0857$." }),
  p({ id: "cont-uniform-3", topicId: "continuous-distributions", section: "exponential", type: "numeric", difficulty: "medium",
    prompt: "For $X\\sim\\text{Uniform}(a,b)$, the PDF is $f(x)=1/(b-a)$. For $\\text{Uniform}(3,7)$, find $f(5)$.",
    answer: "0.25",
    explanation: "Step 1: $f(x)=1/(7-3)=1/4=0.25$. Final answer: $0.25$." }),
  p({ id: "cont-normal-8", topicId: "continuous-distributions", section: "normal", type: "numeric", difficulty: "medium",
    prompt: "IQ scores: $N(100,15^2)$. What score is at the 97.5th percentile? ($z_{0.975}=1.96$)",
    answer: "129.4",
    explanation: "Step 1: $x=\\mu+z\\sigma=100+1.96(15)=100+29.4=129.4$. Final answer: $129.4$." }),

  // --- Hard (10) ---
  p({ id: "cont-normal-9", topicId: "continuous-distributions", section: "normal", type: "numeric", difficulty: "hard",
    prompt: "$X\\sim N(60,100)$. $\\Phi(0.8)=0.7881$, $\\Phi(-0.4)=0.3446$. Find $P(56\\leq X\\leq68)$.",
    answer: "0.4435",
    explanation: "Step 1: $z_1=(56-60)/10=-0.4$, $z_2=(68-60)/10=0.8$. Step 2: $P=\\Phi(0.8)-\\Phi(-0.4)=0.7881-0.3446=0.4435$. Final answer: $0.4435$." }),
  p({ id: "cont-exp-5", topicId: "continuous-distributions", section: "exponential", type: "numeric", difficulty: "hard",
    prompt: "Light bulb lifetimes follow $\\text{Exp}(\\lambda=0.01)$ hr. Find the median lifetime: solve $1-e^{-0.01m}=0.5$.",
    answer: "69.31",
    explanation: "Step 1: $e^{-0.01m}=0.5\\Rightarrow m=\\ln(2)/0.01\\approx0.6931/0.01=69.31$. Final answer: $69.31$." }),
  p({ id: "cont-pdf-7", topicId: "continuous-distributions", section: "pdf", type: "numeric", difficulty: "hard",
    prompt: "For $f(x)=cx^2$ on $[0,3]$ and $0$ elsewhere to be a valid PDF, find $c$.",
    answer: "0.111",
    explanation: "Step 1: $\\int_0^3 cx^2\\,dx=c[x^3/3]_0^3=c(9)=1\\Rightarrow c=1/9\\approx0.111$. Final answer: $0.111$." }),
  p({ id: "cont-approximation-4", topicId: "continuous-distributions", section: "approximation", type: "mcq", difficulty: "hard",
    prompt: "For $X\\sim B(50,0.1)$, should you use the normal or Poisson approximation?",
    answer: "Poisson with $\\lambda=5$, since $p$ is small.",
    choices: ["Normal with $\\mu=5$, since $n$ is large.", "Poisson with $\\lambda=5$, since $p$ is small.", "Either approximation is equally valid.", "Neither; exact binomial must be used."],
    explanation: "Step 1: $np=5$ and $n(1-p)=45\\geq5$ passes normal rule, but $p=0.1$ is small and $n$ is moderate. Step 2: Poisson approximation ($\\lambda=np=5$) is preferred when $p$ is small. Final answer: Poisson with $\\lambda=5$, since $p$ is small." }),
  p({ id: "cont-normal-10", topicId: "continuous-distributions", section: "normal", type: "numeric", difficulty: "hard",
    prompt: "The sum of $n=25$ independent $N(4,9)$ variables has what distribution? Give the mean.",
    answer: "100",
    explanation: "Step 1: $\\sum X_i\\sim N(25\\times4,25\\times9)=N(100,225)$. Mean $=100$. Final answer: $100$." }),
  p({ id: "cont-exp-6", topicId: "continuous-distributions", section: "exponential", type: "numeric", difficulty: "hard",
    prompt: "Phone calls arrive following Poisson($\\lambda=3$/hr). Waiting time between calls follows $\\text{Exp}(3)$. $P(\\text{wait}>30\\text{ min}=0.5\\text{ hr})=$",
    answer: "0.2231",
    explanation: "Step 1: $P(X>0.5)=e^{-3(0.5)}=e^{-1.5}\\approx0.2231$. Final answer: $0.2231$." }),
  p({ id: "cont-pdf-8", topicId: "continuous-distributions", section: "pdf", type: "numeric", difficulty: "hard",
    prompt: "For $X\\sim\\text{Uniform}(0,1)$, find $\\text{Var}(X)=(b-a)^2/12$.",
    answer: "0.0833",
    explanation: "Step 1: $\\text{Var}(X)=(1-0)^2/12=1/12\\approx0.0833$. Final answer: $0.0833$." }),
  p({ id: "cont-normal-11", topicId: "continuous-distributions", section: "normal", type: "mcq", difficulty: "hard",
    prompt: "If $Z\\sim N(0,1)$, then $Z^2\\sim$",
    answer: "Chi-squared with $1$ degree of freedom.",
    choices: ["$N(0,1)$", "Chi-squared with $1$ degree of freedom.", "$t$ distribution.", "Exponential."],
    explanation: "Step 1: The square of a standard normal follows a chi-squared distribution with $1$ df: $Z^2\\sim\\chi^2(1)$. Final answer: Chi-squared with $1$ degree of freedom." }),
  p({ id: "cont-exp-7", topicId: "continuous-distributions", section: "exponential", type: "numeric", difficulty: "hard",
    prompt: "For $X\\sim\\text{Exp}(\\lambda)$, $E(X^2)=2/\\lambda^2$. With $\\lambda=2$, find $\\text{Var}(X)=E(X^2)-[E(X)]^2$.",
    answer: "0.25",
    explanation: "Step 1: $E(X)=1/2$, $E(X^2)=2/4=0.5$. Step 2: $\\text{Var}(X)=0.5-(0.5)^2=0.5-0.25=0.25$. Final answer: $0.25$." }),
  p({ id: "cont-approximation-5", topicId: "continuous-distributions", section: "approximation", type: "numeric", difficulty: "hard",
    prompt: "$X\\sim B(400,0.5)$. $\\mu=200$, $\\sigma=10$. $P(X\\leq210)\\approx\\Phi((210.5-200)/10)$.",
    answer: "0.8531",
    explanation: "Step 1: $z=(210.5-200)/10=1.05$. $\\Phi(1.05)\\approx0.8531$. Final answer: $0.8531$." }),
];
