import type { Problem } from "../shared-types";

const p = (problem: Problem) => problem;

export const estimationProblems: Problem[] = [
  // --- Easy (14) ---
  p({ id: "est-t-vs-z-1", topicId: "estimation", section: "confidence-intervals", type: "mcq", difficulty: "easy",
    prompt: "When $\\sigma$ is unknown and $n$ is small, use a confidence interval based on the:",
    answer: "$t$-distribution",
    choices: ["$t$-distribution", "$z$-distribution", "Chi-squared distribution", "F-distribution"],
    explanation: "Step 1: Unknown $\\sigma$ replaced by $s$ requires the $t$-distribution with $n-1$ df. Final answer: $t$-distribution." }),
  p({ id: "est-ci-basic-1", topicId: "estimation", section: "confidence-intervals", type: "mcq", difficulty: "easy",
    prompt: "A 95% confidence interval means:",
    answer: "95% of such intervals constructed from repeated samples would contain the true parameter.",
    choices: ["There is a 95% chance the parameter is in this interval.", "95% of such intervals constructed from repeated samples would contain the true parameter.", "95% of data falls in the interval.", "The sample mean is within 5% of the truth."],
    explanation: "Step 1: A CI is a frequentist concept: 95% of all CIs from repeated sampling capture $\\mu$. Final answer: 95% of such intervals constructed from repeated samples would contain the true parameter." }),
  p({ id: "est-se-1", topicId: "estimation", section: "confidence-intervals", type: "numeric", difficulty: "easy",
    prompt: "Sample: $n=100$, $s=20$. What is the standard error of the mean?",
    answer: "2",
    explanation: "Step 1: $SE=s/\\sqrt{n}=20/\\sqrt{100}=2$. Final answer: $2$." }),
  p({ id: "est-mle-1", topicId: "estimation", section: "mle", type: "mcq", difficulty: "easy",
    prompt: "The MLE selects the parameter value that:",
    answer: "Maximizes the likelihood of observing the sample data.",
    choices: ["Minimizes the sample variance.", "Maximizes the likelihood of observing the sample data.", "Equals the sample mean always.", "Minimizes sum of squared residuals."],
    explanation: "Step 1: MLE: $\\hat{\\theta}=\\arg\\max L(\\theta)$ where $L(\\theta)=P(\\text{data}|\\theta)$. Final answer: Maximizes the likelihood of observing the sample data." }),
  p({ id: "est-point-1", topicId: "estimation", section: "point-estimate", type: "mcq", difficulty: "easy",
    prompt: "An unbiased estimator $\\hat{\\theta}$ satisfies:",
    answer: "$E(\\hat{\\theta})=\\theta$",
    choices: ["$\\hat{\\theta}=\\theta$ always.", "$E(\\hat{\\theta})=\\theta$", "$\\text{Var}(\\hat{\\theta})=0$", "$\\hat{\\theta}\\leq\\theta$"],
    explanation: "Step 1: Unbiasedness: on average the estimator equals the true parameter, $E(\\hat{\\theta})=\\theta$. Final answer: $E(\\hat{\\theta})=\\theta$." }),
  p({ id: "est-ci-width-1", topicId: "estimation", section: "confidence-intervals", type: "mcq", difficulty: "easy",
    prompt: "To decrease the width of a confidence interval, you can:",
    answer: "Increase the sample size.",
    choices: ["Increase the confidence level.", "Increase the sample size.", "Decrease the sample size.", "Increase $\\sigma$."],
    explanation: "Step 1: CI width $=2z^*\\cdot SE=2z^*\\sigma/\\sqrt{n}$. Increasing $n$ decreases $SE$, narrowing the interval. Final answer: Increase the sample size." }),
  p({ id: "est-mle-2", topicId: "estimation", section: "mle", type: "mcq", difficulty: "easy",
    prompt: "The MLE for the mean $\\mu$ of a normal distribution $N(\\mu,\\sigma^2)$ given data $x_1,\\ldots,x_n$ is:",
    answer: "$\\bar{x}$",
    choices: ["$s$", "$\\bar{x}$", "$s^2$", "$\\text{median}$"],
    explanation: "Step 1: For normal data, maximizing the log-likelihood w.r.t. $\\mu$ gives $\\hat{\\mu}=\\bar{x}$. Final answer: $\\bar{x}$." }),
  p({ id: "est-point-2", topicId: "estimation", section: "point-estimate", type: "mcq", difficulty: "easy",
    prompt: "The sample mean $\\bar{x}$ is a ___ estimator of $\\mu$:",
    answer: "Unbiased",
    choices: ["Biased", "Unbiased", "Inconsistent", "Inefficient"],
    explanation: "Step 1: $E(\\bar{X})=\\mu$, so $\\bar{X}$ is an unbiased estimator. Final answer: Unbiased." }),
  p({ id: "est-ci-2", topicId: "estimation", section: "confidence-intervals", type: "numeric", difficulty: "easy",
    prompt: "Margin of error for a 95% CI: $z^*=1.96$, $SE=2$. What is the margin of error?",
    answer: "3.92",
    explanation: "Step 1: $ME=z^*\\cdot SE=1.96\\times2=3.92$. Final answer: $3.92$." }),
  p({ id: "est-mle-3", topicId: "estimation", section: "mle", type: "mcq", difficulty: "easy",
    prompt: "For a Bernoulli distribution with $n$ trials and $k$ successes, the MLE for $p$ is:",
    answer: "$k/n$",
    choices: ["$k/n$", "$n/k$", "$1-k/n$", "$\\sqrt{k/n}$"],
    explanation: "Step 1: Likelihood $=p^k(1-p)^{n-k}$. Maximizing gives $\\hat{p}=k/n$. Final answer: $k/n$." }),
  p({ id: "est-ci-level-1", topicId: "estimation", section: "confidence-intervals", type: "mcq", difficulty: "easy",
    prompt: "A 99% CI is ___ than a 95% CI (all else equal):",
    answer: "Wider",
    choices: ["Narrower", "Wider", "The same width", "Shorter"],
    explanation: "Step 1: Higher confidence requires a larger $z^*$ (2.576 vs 1.96), widening the interval. Final answer: Wider." }),
  p({ id: "est-point-3", topicId: "estimation", section: "point-estimate", type: "mcq", difficulty: "easy",
    prompt: "The sample proportion $\\hat{p}$ is an estimator of the population proportion $p$. It is:",
    answer: "Unbiased, because $E(\\hat{p})=p$.",
    choices: ["Biased.", "Unbiased, because $E(\\hat{p})=p$.", "Inconsistent.", "Only valid for large $n$."],
    explanation: "Step 1: $E(\\hat{p})=p$, so $\\hat{p}$ is unbiased. Final answer: Unbiased, because $E(\\hat{p})=p$." }),
  p({ id: "est-ci-3", topicId: "estimation", section: "confidence-intervals", type: "mcq", difficulty: "easy",
    prompt: "Which $z^*$ value corresponds to a 90% confidence interval?",
    answer: "$1.645$",
    choices: ["$1.28$", "$1.645$", "$1.96$", "$2.576$"],
    explanation: "Step 1: 90% CI: $\\alpha=0.10$, $\\alpha/2=0.05$. $z_{0.95}=1.645$. Final answer: $1.645$." }),
  p({ id: "est-mle-4", topicId: "estimation", section: "mle", type: "mcq", difficulty: "easy",
    prompt: "The MLE for the variance $\\sigma^2$ of a normal distribution is $\\frac{1}{n}\\sum(x_i-\\bar{x})^2$. This estimator is:",
    answer: "Biased (uses $n$ not $n-1$).",
    choices: ["Unbiased.", "Biased (uses $n$ not $n-1$).", "Consistent but not unbiased always.", "Equal to $s^2$."],
    explanation: "Step 1: The MLE $\\hat{\\sigma}^2=\\frac{1}{n}\\sum(x_i-\\bar{x})^2$ is biased: $E[\\hat{\\sigma}^2]=\\frac{n-1}{n}\\sigma^2\\neq\\sigma^2$. The unbiased version divides by $n-1$. Final answer: Biased (uses $n$ not $n-1$)." }),

  // --- Medium (16) ---
  p({ id: "est-ci-1", topicId: "estimation", section: "confidence-intervals", type: "numeric", difficulty: "medium",
    prompt: "Sample: $\\bar{x}=80$, $s=10$, $n=100$. Using $z^*=1.96$, find the upper bound of the 95% CI.",
    answer: "81.96",
    explanation: "Step 1: $SE=10/\\sqrt{100}=1$. Step 2: Upper $=80+1.96(1)=81.96$. Final answer: $81.96$." }),
  p({ id: "est-ci-4", topicId: "estimation", section: "confidence-intervals", type: "numeric", difficulty: "medium",
    prompt: "95% CI for $\\mu$: $\\bar{x}=50$, $\\sigma=8$, $n=64$. Find the CI half-width.",
    answer: "1.96",
    explanation: "Step 1: $SE=8/\\sqrt{64}=1$. Half-width $=1.96\\times1=1.96$. Final answer: $1.96$." }),
  p({ id: "est-mle-5", topicId: "estimation", section: "mle", type: "numeric", difficulty: "medium",
    prompt: "Data: $\\{1,0,1,1,0\\}$ from Bernoulli$(p)$. Find the MLE $\\hat{p}$.",
    answer: "0.6",
    explanation: "Step 1: $k=3$ successes, $n=5$. $\\hat{p}=k/n=3/5=0.6$. Final answer: $0.6$." }),
  p({ id: "est-point-4", topicId: "estimation", section: "point-estimate", type: "numeric", difficulty: "medium",
    prompt: "The mean squared error of an estimator: $\\text{MSE}(\\hat{\\theta})=\\text{Var}(\\hat{\\theta})+[\\text{Bias}(\\hat{\\theta})]^2$. If $\\text{Var}=4$ and $\\text{Bias}=3$, find MSE.",
    answer: "13",
    explanation: "Step 1: $\\text{MSE}=4+3^2=4+9=13$. Final answer: $13$." }),
  p({ id: "est-ci-5", topicId: "estimation", section: "confidence-intervals", type: "numeric", difficulty: "medium",
    prompt: "A sample of $n=25$ from a normal population has $\\bar{x}=10$, $s=4$. Using $t_{0.025,24}=2.064$, find the upper bound of the 95% CI.",
    answer: "11.651",
    explanation: "Step 1: $SE=4/\\sqrt{25}=0.8$. Upper $=10+2.064(0.8)=10+1.651=11.651$. Final answer: $11.651$." }),
  p({ id: "est-ci-6", topicId: "estimation", section: "confidence-intervals", type: "numeric", difficulty: "medium",
    prompt: "A proportion CI: $\\hat{p}=0.6$, $n=100$, $z^*=1.96$. Find the margin of error.",
    answer: "0.096",
    explanation: "Step 1: $SE=\\sqrt{0.6(0.4)/100}=\\sqrt{0.0024}\\approx0.049$. $ME=1.96(0.049)\\approx0.096$. Final answer: $0.096$." }),
  p({ id: "est-mle-6", topicId: "estimation", section: "mle", type: "mcq", difficulty: "medium",
    prompt: "For an exponential distribution $f(x)=\\lambda e^{-\\lambda x}$, the MLE for $\\lambda$ given $n$ observations with sample mean $\\bar{x}$ is:",
    answer: "$1/\\bar{x}$",
    choices: ["$\\bar{x}$", "$1/\\bar{x}$", "$n\\bar{x}$", "$\\sqrt{\\bar{x}}$"],
    explanation: "Step 1: Log-likelihood: $\\ell(\\lambda)=n\\ln\\lambda-\\lambda\\sum x_i$. Setting $d\\ell/d\\lambda=n/\\lambda-\\sum x_i=0$ gives $\\hat{\\lambda}=n/\\sum x_i=1/\\bar{x}$. Final answer: $1/\\bar{x}$." }),
  p({ id: "est-ci-7", topicId: "estimation", section: "confidence-intervals", type: "mcq", difficulty: "medium",
    prompt: "The degrees of freedom for a one-sample $t$ CI with $n=20$ is:",
    answer: "$19$",
    choices: ["$20$", "$19$", "$18$", "$21$"],
    explanation: "Step 1: df $=n-1=20-1=19$. Final answer: $19$." }),
  p({ id: "est-point-5", topicId: "estimation", section: "point-estimate", type: "mcq", difficulty: "medium",
    prompt: "A consistent estimator $\\hat{\\theta}_n$ satisfies:",
    answer: "$\\hat{\\theta}_n\\to\\theta$ in probability as $n\\to\\infty$.",
    choices: ["$E(\\hat{\\theta}_n)=\\theta$ for all $n$.", "$\\hat{\\theta}_n\\to\\theta$ in probability as $n\\to\\infty$.", "$\\text{Var}(\\hat{\\theta}_n)=0$.", "$\\hat{\\theta}_n=\\theta$ always."],
    explanation: "Step 1: Consistency: $P(|\\hat{\\theta}_n-\\theta|>\\epsilon)\\to0$ for any $\\epsilon>0$. Final answer: $\\hat{\\theta}_n\\to\\theta$ in probability as $n\\to\\infty$." }),
  p({ id: "est-ci-8", topicId: "estimation", section: "confidence-intervals", type: "numeric", difficulty: "medium",
    prompt: "What sample size is needed for a 95% CI with margin of error $\\leq3$ when $\\sigma=15$?",
    answer: "97",
    explanation: "Step 1: $ME=z^*\\sigma/\\sqrt{n}\\leq3$. $n\\geq(1.96\\times15/3)^2=(9.8)^2=96.04$. Round up: $n=97$. Final answer: $97$." }),
  p({ id: "est-mle-7", topicId: "estimation", section: "mle", type: "mcq", difficulty: "medium",
    prompt: "MLE is consistent, meaning as $n\\to\\infty$:",
    answer: "$\\hat{\\theta}_{MLE}\\to\\theta$ in probability.",
    choices: ["$\\hat{\\theta}_{MLE}=\\theta$.", "$\\hat{\\theta}_{MLE}\\to\\theta$ in probability.", "$\\text{Var}(\\hat{\\theta}_{MLE})=0$.", "$\\hat{\\theta}_{MLE}$ is always unbiased."],
    explanation: "Step 1: Under regularity conditions, MLE is consistent: converges to the true parameter in probability. Final answer: $\\hat{\\theta}_{MLE}\\to\\theta$ in probability." }),
  p({ id: "est-ci-9", topicId: "estimation", section: "confidence-intervals", type: "numeric", difficulty: "medium",
    prompt: "CI for proportion: $\\hat{p}=0.3$, $n=200$, $z^*=1.96$. Find the lower bound.",
    answer: "0.2366",
    explanation: "Step 1: $SE=\\sqrt{0.3(0.7)/200}=\\sqrt{0.00105}\\approx0.0324$. Lower $=0.3-1.96(0.0324)=0.3-0.0635=0.2365\\approx0.2366$. Final answer: $0.2366$." }),
  p({ id: "est-point-6", topicId: "estimation", section: "point-estimate", type: "mcq", difficulty: "medium",
    prompt: "Among all unbiased estimators, the one with the smallest variance is called:",
    answer: "UMVUE (Uniformly Minimum Variance Unbiased Estimator).",
    choices: ["MLE.", "UMVUE (Uniformly Minimum Variance Unbiased Estimator).", "Method of moments estimator.", "Consistent estimator."],
    explanation: "Step 1: UMVUE achieves the Cramér-Rao lower bound and has minimum variance among all unbiased estimators. Final answer: UMVUE (Uniformly Minimum Variance Unbiased Estimator)." }),
  p({ id: "est-ci-10", topicId: "estimation", section: "confidence-intervals", type: "mcq", difficulty: "medium",
    prompt: "A wider confidence interval corresponds to:",
    answer: "Higher confidence level or smaller sample size.",
    choices: ["Lower confidence level.", "Higher confidence level or smaller sample size.", "Larger sample size only.", "Smaller population variance."],
    explanation: "Step 1: CI width increases with higher $z^*$ (higher confidence) or smaller $n$ (larger SE). Final answer: Higher confidence level or smaller sample size." }),

  // --- Hard (10) ---
  p({ id: "est-ci-11", topicId: "estimation", section: "confidence-intervals", type: "numeric", difficulty: "hard",
    prompt: "$\\bar{x}=45$, $s=12$, $n=16$. $t_{0.025,15}=2.131$. Find the 95% CI lower bound.",
    answer: "38.61",
    explanation: "Step 1: $SE=12/4=3$. Lower $=45-2.131(3)=45-6.393=38.607\\approx38.61$. Final answer: $38.61$." }),
  p({ id: "est-mle-8", topicId: "estimation", section: "mle", type: "numeric", difficulty: "hard",
    prompt: "For a Poisson$(\\lambda)$, you observe $\\{2,3,1,4,2\\}$. Find the MLE $\\hat{\\lambda}=\\bar{x}$.",
    answer: "2.4",
    explanation: "Step 1: $\\bar{x}=(2+3+1+4+2)/5=12/5=2.4$. Final answer: $2.4$." }),
  p({ id: "est-ci-12", topicId: "estimation", section: "confidence-intervals", type: "numeric", difficulty: "hard",
    prompt: "For what sample size does the 95% CI half-width equal $2$ when $\\sigma=10$?",
    answer: "97",
    explanation: "Step 1: $1.96(10/\\sqrt{n})=2\\Rightarrow\\sqrt{n}=9.8\\Rightarrow n=96.04$. Round up: $n=97$. Final answer: $97$." }),
  p({ id: "est-point-7", topicId: "estimation", section: "point-estimate", type: "mcq", difficulty: "hard",
    prompt: "The Cramér-Rao lower bound states that for any unbiased estimator $\\hat{\\theta}$:",
    answer: "$\\text{Var}(\\hat{\\theta})\\geq1/I(\\theta)$ where $I(\\theta)$ is the Fisher information.",
    choices: ["$\\text{Var}(\\hat{\\theta})=0$.", "$\\text{Var}(\\hat{\\theta})\\geq1/I(\\theta)$ where $I(\\theta)$ is the Fisher information.", "$E(\\hat{\\theta})=\\theta$.", "$\\hat{\\theta}$ is always consistent."],
    explanation: "Step 1: The Cramér-Rao bound gives a lower limit on the variance of any unbiased estimator: $\\text{Var}(\\hat{\\theta})\\geq1/I(\\theta)$. Final answer: $\\text{Var}(\\hat{\\theta})\\geq1/I(\\theta)$ where $I(\\theta)$ is the Fisher information." }),
  p({ id: "est-ci-13", topicId: "estimation", section: "confidence-intervals", type: "numeric", difficulty: "hard",
    prompt: "Two-sample CI: $\\bar{x}_1=50$, $\\bar{x}_2=45$, $s_1=s_2=8$, $n_1=n_2=36$. $z^*=1.96$. Find the 95% CI lower bound for $\\mu_1-\\mu_2$.",
    answer: "1.306",
    explanation: "Step 1: $SE=\\sqrt{64/36+64/36}=\\sqrt{128/36}=\\sqrt{3.556}\\approx1.886$. Lower $=(50-45)-1.96(1.886)=5-3.694=1.306$. Final answer: $1.306$." }),
  p({ id: "est-mle-9", topicId: "estimation", section: "mle", type: "mcq", difficulty: "hard",
    prompt: "The asymptotic distribution of $\\sqrt{n}(\\hat{\\theta}_{MLE}-\\theta)$ is:",
    answer: "$N(0,1/I(\\theta))$",
    choices: ["$N(0,1)$", "$N(0,1/I(\\theta))$", "$t_{n-1}$", "Uniform."],
    explanation: "Step 1: Asymptotic normality of MLE: $\\sqrt{n}(\\hat{\\theta}_{MLE}-\\theta)\\overset{d}{\\to}N(0,1/I(\\theta))$. Final answer: $N(0,1/I(\\theta))$." }),
  p({ id: "est-ci-14", topicId: "estimation", section: "confidence-intervals", type: "mcq", difficulty: "hard",
    prompt: "A bootstrap confidence interval is useful when:",
    answer: "The sampling distribution of the statistic is unknown or hard to derive analytically.",
    choices: ["The sample is very large.", "The sampling distribution of the statistic is unknown or hard to derive analytically.", "The population is normal.", "The parameter is a mean."],
    explanation: "Step 1: Bootstrap resamples from data to estimate the sampling distribution empirically, useful when analytical formulas aren't available. Final answer: The sampling distribution of the statistic is unknown or hard to derive analytically." }),
  p({ id: "est-point-8", topicId: "estimation", section: "point-estimate", type: "numeric", difficulty: "hard",
    prompt: "Method of moments estimator: match $E(X)=\\mu$ to $\\bar{x}$. For $\\text{Uniform}(0,\\theta)$, $E(X)=\\theta/2$. Given $\\bar{x}=3.5$, find $\\hat{\\theta}$.",
    answer: "7",
    explanation: "Step 1: $\\theta/2=\\bar{x}=3.5\\Rightarrow\\hat{\\theta}=7$. Final answer: $7$." }),
  p({ id: "est-ci-15", topicId: "estimation", section: "confidence-intervals", type: "numeric", difficulty: "hard",
    prompt: "CI for variance: $\\chi^2_{L}=8.231$, $\\chi^2_{U}=31.526$, $n=20$, $s^2=25$. Find the lower bound of the 95% CI for $\\sigma^2$.",
    answer: "15.07",
    explanation: "Step 1: 95% CI for $\\sigma^2$: $[(n-1)s^2/\\chi^2_U,(n-1)s^2/\\chi^2_L]=[19(25)/31.526,19(25)/8.231]=[15.07,57.71]$. Lower $=15.07$. Final answer: $15.07$." }),
  p({ id: "est-mle-10", topicId: "estimation", section: "mle", type: "mcq", difficulty: "hard",
    prompt: "For normal data, the MLE for $\\sigma^2$ is $\\hat{\\sigma}^2=\\frac{1}{n}\\sum(x_i-\\bar{x})^2$. Compared to $s^2=\\frac{1}{n-1}\\sum(x_i-\\bar{x})^2$:",
    answer: "$\\hat{\\sigma}^2<s^2$ (MLE underestimates).",
    choices: ["$\\hat{\\sigma}^2>s^2$.", "$\\hat{\\sigma}^2<s^2$ (MLE underestimates).", "$\\hat{\\sigma}^2=s^2$.", "They are equal for large $n$."],
    explanation: "Step 1: $\\hat{\\sigma}^2=(n-1)/n\\cdot s^2<s^2$. The MLE systematically underestimates $\\sigma^2$ (biased downward). Final answer: $\\hat{\\sigma}^2<s^2$ (MLE underestimates)." }),
];
