import type { Problem } from "../shared-types";

const p = (problem: Problem) => problem;

export const regressionProblems: Problem[] = [
  // --- Easy (14) ---
  p({ id: "reg-corr-1", topicId: "regression", section: "correlation", type: "mcq", difficulty: "easy",
    prompt: "A correlation $r=-0.92$ indicates:",
    answer: "A strong negative linear relationship.",
    choices: ["A weak positive relationship.", "A strong positive relationship.", "A strong negative linear relationship.", "No linear relationship."],
    explanation: "Step 1: $|r|=0.92$ is close to $1$ (strong). Negative sign: as $x$ increases, $y$ decreases. Final answer: A strong negative linear relationship." }),
  p({ id: "reg-r2-1", topicId: "regression", section: "linear", type: "mcq", difficulty: "easy",
    prompt: "If $R^2=0.81$, the model explains what percent of variance in $y$?",
    answer: "81%",
    choices: ["9%", "19%", "81%", "90%"],
    explanation: "Step 1: $R^2=0.81$ means $81\\%$ of the variability in $y$ is explained. Final answer: $81\\%$." }),
  p({ id: "reg-residual-1", topicId: "regression", section: "residuals", type: "numeric", difficulty: "easy",
    prompt: "Observed $y=15$, predicted $\\hat{y}=12$. Find the residual.",
    answer: "3",
    explanation: "Step 1: Residual $=y-\\hat{y}=15-12=3$. Final answer: $3$." }),
  p({ id: "reg-slope-1", topicId: "regression", section: "linear", type: "numeric", difficulty: "easy",
    prompt: "$\\hat{y}=3+2x$. Predict $y$ when $x=5$.",
    answer: "13",
    explanation: "Step 1: $\\hat{y}=3+2(5)=13$. Final answer: $13$." }),
  p({ id: "reg-interpret-1", topicId: "regression", section: "linear", type: "mcq", difficulty: "easy",
    prompt: "In $\\hat{y}=10+3x$, the slope $3$ means:",
    answer: "For each unit increase in $x$, $y$ is predicted to increase by $3$.",
    choices: ["When $x=0$, $y=3$.", "For each unit increase in $x$, $y$ is predicted to increase by $3$.", "The correlation is $0.3$.", "The model explains $30\\%$ of variance."],
    explanation: "Step 1: Slope $b_1=3$: for each $+1$ in $x$, predicted $y$ increases by $3$. Final answer: For each unit increase in $x$, $y$ is predicted to increase by $3$." }),
  p({ id: "reg-intercept-1", topicId: "regression", section: "linear", type: "mcq", difficulty: "easy",
    prompt: "In $\\hat{y}=10+3x$, the intercept $10$ means:",
    answer: "When $x=0$, the predicted value of $y$ is $10$.",
    choices: ["The slope is $10$.", "When $x=0$, the predicted value of $y$ is $10$.", "$y$ increases by $10$ per unit.", "The model is $10\\%$ accurate."],
    explanation: "Step 1: $b_0=10$ is the $y$-intercept: the predicted $y$ when $x=0$. Final answer: When $x=0$, the predicted value of $y$ is $10$." }),
  p({ id: "reg-corr-2", topicId: "regression", section: "correlation", type: "mcq", difficulty: "easy",
    prompt: "For simple linear regression, $R^2=r^2$ where $r$ is the Pearson correlation. If $r=0.7$, $R^2=$",
    answer: "$0.49$",
    choices: ["$0.07$", "$0.30$", "$0.49$", "$0.70$"],
    explanation: "Step 1: $R^2=r^2=0.7^2=0.49$. Final answer: $0.49$." }),
  p({ id: "reg-conditions-1", topicId: "regression", section: "conditions", type: "mcq", difficulty: "easy",
    prompt: "One condition for linear regression is linearity. This means:",
    answer: "The relationship between $x$ and $y$ is linear.",
    choices: ["$y$ must be normally distributed.", "The relationship between $x$ and $y$ is linear.", "Residuals must be zero.", "The slope must be positive."],
    explanation: "Step 1: The linearity condition requires that $E(y|x)=\\beta_0+\\beta_1 x$, i.e., the mean response is a linear function of $x$. Final answer: The relationship between $x$ and $y$ is linear." }),
  p({ id: "reg-residual-2", topicId: "regression", section: "residuals", type: "mcq", difficulty: "easy",
    prompt: "The sum of residuals in OLS regression equals:",
    answer: "$0$",
    choices: ["$1$", "$0$", "The residual standard error.", "The slope."],
    explanation: "Step 1: OLS minimizes $\\sum e_i^2$ and the first-order conditions force $\\sum e_i=0$. Final answer: $0$." }),
  p({ id: "reg-corr-3", topicId: "regression", section: "correlation", type: "mcq", difficulty: "easy",
    prompt: "Correlation $r=0$ means:",
    answer: "No linear relationship (but could be non-linear).",
    choices: ["No relationship whatsoever.", "No linear relationship (but could be non-linear).", "Perfect relationship.", "Negative relationship."],
    explanation: "Step 1: $r$ measures linear association. $r=0$ means no linear relationship, but a non-linear pattern could still exist. Final answer: No linear relationship (but could be non-linear)." }),
  p({ id: "reg-linear-1", topicId: "regression", section: "linear", type: "mcq", difficulty: "easy",
    prompt: "OLS (Ordinary Least Squares) minimizes the:",
    answer: "Sum of squared residuals $\\sum(y_i-\\hat{y}_i)^2$.",
    choices: ["Sum of residuals.", "Sum of squared residuals $\\sum(y_i-\\hat{y}_i)^2$.", "Sum of absolute residuals.", "Maximum residual."],
    explanation: "Step 1: OLS criterion: minimize $\\sum e_i^2=\\sum(y_i-\\hat{y}_i)^2$. Final answer: Sum of squared residuals $\\sum(y_i-\\hat{y}_i)^2$." }),
  p({ id: "reg-conditions-2", topicId: "regression", section: "conditions", type: "mcq", difficulty: "easy",
    prompt: "The condition of homoscedasticity in regression means:",
    answer: "Residuals have constant variance across all values of $x$.",
    choices: ["Residuals are zero.", "Residuals have constant variance across all values of $x$.", "Residuals are normally distributed.", "There is no multicollinearity."],
    explanation: "Step 1: Homoscedasticity: $\\text{Var}(\\varepsilon_i)=\\sigma^2$ (constant) for all $i$. Violated: heteroscedasticity. Final answer: Residuals have constant variance across all values of $x$." }),
  p({ id: "reg-extrapolation-1", topicId: "regression", section: "conditions", type: "mcq", difficulty: "easy",
    prompt: "Extrapolation in regression is:",
    answer: "Predicting $y$ for $x$ values outside the range of the data.",
    choices: ["Using the model within the data range.", "Predicting $y$ for $x$ values outside the range of the data.", "Adding more predictors.", "Removing outliers."],
    explanation: "Step 1: Extrapolation extends predictions beyond observed $x$ values. It is risky since the linear relationship may not hold outside the data range. Final answer: Predicting $y$ for $x$ values outside the range of the data." }),
  p({ id: "reg-corr-4", topicId: "regression", section: "correlation", type: "mcq", difficulty: "easy",
    prompt: "Correlation is unitless and ranges from:",
    answer: "$-1$ to $+1$.",
    choices: ["$0$ to $1$.", "$-1$ to $+1$.", "$-\\infty$ to $+\\infty$.", "$0$ to $\\infty$."],
    explanation: "Step 1: Pearson $r\\in[-1,1]$. $r=-1$ perfect negative, $r=+1$ perfect positive, $r=0$ no linear association. Final answer: $-1$ to $+1$." }),

  // --- Medium (16) ---
  p({ id: "reg-slope-2", topicId: "regression", section: "linear", type: "numeric", difficulty: "medium",
    prompt: "$\\bar{x}=3$, $\\bar{y}=10$, $\\sum(x_i-\\bar{x})(y_i-\\bar{y})=30$, $\\sum(x_i-\\bar{x})^2=10$. Find slope $b_1$.",
    answer: "3",
    explanation: "Step 1: $b_1=\\frac{\\sum(x_i-\\bar{x})(y_i-\\bar{y})}{\\sum(x_i-\\bar{x})^2}=30/10=3$. Final answer: $3$." }),
  p({ id: "reg-intercept-2", topicId: "regression", section: "linear", type: "numeric", difficulty: "medium",
    prompt: "Using $b_1=3$, $\\bar{x}=3$, $\\bar{y}=10$. Find intercept $b_0=\\bar{y}-b_1\\bar{x}$.",
    answer: "1",
    explanation: "Step 1: $b_0=10-3(3)=10-9=1$. Final answer: $1$." }),
  p({ id: "reg-r2-2", topicId: "regression", section: "linear", type: "numeric", difficulty: "medium",
    prompt: "$SS_{\\text{regression}}=120$, $SS_{\\text{total}}=200$. Find $R^2$.",
    answer: "0.6",
    explanation: "Step 1: $R^2=SS_{\\text{reg}}/SS_{\\text{total}}=120/200=0.6$. Final answer: $0.6$." }),
  p({ id: "reg-residual-3", topicId: "regression", section: "residuals", type: "numeric", difficulty: "medium",
    prompt: "$\\hat{y}=2+4x$. For $x=3$, $y=15$. Find the residual.",
    answer: "1",
    explanation: "Step 1: $\\hat{y}=2+4(3)=14$. Residual $=15-14=1$. Final answer: $1$." }),
  p({ id: "reg-conditions-3", topicId: "regression", section: "conditions", type: "mcq", difficulty: "medium",
    prompt: "A residual plot showing a fan-shaped pattern (residuals increasing with $\\hat{y}$) indicates:",
    answer: "Heteroscedasticity.",
    choices: ["Normality.", "Heteroscedasticity.", "No pattern.", "Autocorrelation."],
    explanation: "Step 1: Fan-shaped residual plots indicate variance is not constant—heteroscedasticity. Remedies: log transform, weighted least squares. Final answer: Heteroscedasticity." }),
  p({ id: "reg-corr-5", topicId: "regression", section: "correlation", type: "numeric", difficulty: "medium",
    prompt: "Pearson $r$: $n=5$, $\\sum(x_i-\\bar{x})(y_i-\\bar{y})=40$, $\\sqrt{\\sum(x_i-\\bar{x})^2}=8$, $\\sqrt{\\sum(y_i-\\bar{y})^2}=10$. Find $r$.",
    answer: "0.5",
    explanation: "Step 1: $r=40/(8\\times10)=40/80=0.5$. Final answer: $0.5$." }),
  p({ id: "reg-se-1", topicId: "regression", section: "residuals", type: "mcq", difficulty: "medium",
    prompt: "The residual standard error $s_e=\\sqrt{SS_e/(n-2)}$ estimates:",
    answer: "The standard deviation of the residuals.",
    choices: ["The slope.", "The standard deviation of the residuals.", "The correlation coefficient.", "$R^2$."],
    explanation: "Step 1: $s_e$ measures typical vertical scatter of points around the regression line (root mean squared residual). Final answer: The standard deviation of the residuals." }),
  p({ id: "reg-inference-1", topicId: "regression", section: "linear", type: "mcq", difficulty: "medium",
    prompt: "The test statistic for $H_0:\\beta_1=0$ is:",
    answer: "$t=b_1/SE_{b_1}$",
    choices: ["$F=R^2/(1-R^2)$", "$t=b_1/SE_{b_1}$", "$z=b_1/\\sigma$", "$\\chi^2=b_1^2$"],
    explanation: "Step 1: To test whether the slope is significant, use $t=b_1/SE_{b_1}$ with $n-2$ df. Final answer: $t=b_1/SE_{b_1}$." }),
  p({ id: "reg-conditions-4", topicId: "regression", section: "conditions", type: "mcq", difficulty: "medium",
    prompt: "When residuals are correlated over time (time-series data), this violates:",
    answer: "Independence of errors.",
    choices: ["Normality.", "Homoscedasticity.", "Independence of errors.", "Linearity."],
    explanation: "Step 1: Autocorrelation in residuals violates the independence assumption. Durbin-Watson test can detect this. Final answer: Independence of errors." }),
  p({ id: "reg-r2-3", topicId: "regression", section: "linear", type: "mcq", difficulty: "medium",
    prompt: "Adjusted $R^2$ is used over $R^2$ when:",
    answer: "Comparing models with different numbers of predictors.",
    choices: ["$n$ is small.", "Comparing models with different numbers of predictors.", "$R^2>0.5$.", "The intercept is zero."],
    explanation: "Step 1: Adjusted $R^2$ penalizes for extra predictors: $\\bar{R}^2=1-(1-R^2)\\frac{n-1}{n-p-1}$. It does not automatically increase when adding predictors. Final answer: Comparing models with different numbers of predictors." }),
  p({ id: "reg-slope-3", topicId: "regression", section: "linear", type: "numeric", difficulty: "medium",
    prompt: "$\\hat{y}=5+0.8x$. What is the predicted $y$ when $x=20$?",
    answer: "21",
    explanation: "Step 1: $\\hat{y}=5+0.8(20)=5+16=21$. Final answer: $21$." }),
  p({ id: "reg-corr-6", topicId: "regression", section: "correlation", type: "mcq", difficulty: "medium",
    prompt: "Correlation does not imply causation. The best way to establish causation is:",
    answer: "A randomized controlled experiment.",
    choices: ["A large observational study.", "A randomized controlled experiment.", "A high $r$ value.", "Extrapolation."],
    explanation: "Step 1: Only random assignment of treatment eliminates confounding, allowing causal inference. Final answer: A randomized controlled experiment." }),
  p({ id: "reg-conditions-5", topicId: "regression", section: "conditions", type: "mcq", difficulty: "medium",
    prompt: "Multicollinearity in multiple regression occurs when:",
    answer: "Predictor variables are highly correlated with each other.",
    choices: ["The response is non-linear.", "Predictor variables are highly correlated with each other.", "Residuals are non-normal.", "The intercept is zero."],
    explanation: "Step 1: Multicollinearity inflates standard errors of coefficients, making it hard to identify individual predictor effects. Measured by VIF. Final answer: Predictor variables are highly correlated with each other." }),
  p({ id: "reg-ss-1", topicId: "regression", section: "residuals", type: "numeric", difficulty: "medium",
    prompt: "$SS_{\\text{total}}=500$, $R^2=0.64$. Find $SS_{\\text{residual}}$.",
    answer: "180",
    explanation: "Step 1: $SS_{\\text{reg}}=0.64\\times500=320$. $SS_{\\text{res}}=500-320=180$. Final answer: $180$." }),
  p({ id: "reg-linear-2", topicId: "regression", section: "linear", type: "mcq", difficulty: "medium",
    prompt: "The regression line always passes through:",
    answer: "$(\\bar{x},\\bar{y})$",
    choices: ["$(0,0)$", "$(\\bar{x},\\bar{y})$", "$(1,b_0)$", "The highest data point."],
    explanation: "Step 1: Since $b_0=\\bar{y}-b_1\\bar{x}$, substituting $x=\\bar{x}$ gives $\\hat{y}=\\bar{y}$. The line passes through $(\\bar{x},\\bar{y})$. Final answer: $(\\bar{x},\\bar{y})$." }),

  // --- Hard (10) ---
  p({ id: "reg-slope-4", topicId: "regression", section: "linear", type: "numeric", difficulty: "hard",
    prompt: "$n=6$, $\\sum x_i=30$, $\\sum y_i=60$, $\\sum x_iy_i=340$, $\\sum x_i^2=200$. Find $b_1$.",
    answer: "0.8",
    explanation: "Step 1: $\\bar{x}=5$, $\\bar{y}=10$. $SS_{xx}=\\sum x_i^2-n\\bar{x}^2=200-150=50$. $SS_{xy}=\\sum x_iy_i-n\\bar{x}\\bar{y}=340-300=40$. $b_1=SS_{xy}/SS_{xx}=40/50=0.8$. Final answer: $0.8$." }),
  p({ id: "reg-inference-2", topicId: "regression", section: "linear", type: "numeric", difficulty: "hard",
    prompt: "$b_1=2.5$, $SE_{b_1}=1.0$, $n=12$. Find $t$ for $H_0:\\beta_1=0$.",
    answer: "2.5",
    explanation: "Step 1: $t=b_1/SE_{b_1}=2.5/1.0=2.5$. Degrees of freedom $=n-2=10$. Final answer: $2.5$." }),
  p({ id: "reg-conditions-6", topicId: "regression", section: "conditions", type: "mcq", difficulty: "hard",
    prompt: "The Durbin-Watson statistic tests for:",
    answer: "Autocorrelation in residuals.",
    choices: ["Normality of residuals.", "Autocorrelation in residuals.", "Homoscedasticity.", "Multicollinearity."],
    explanation: "Step 1: Durbin-Watson $d\\approx2$ means no autocorrelation. $d<2$: positive autocorrelation. $d>2$: negative autocorrelation. Final answer: Autocorrelation in residuals." }),
  p({ id: "reg-r2-4", topicId: "regression", section: "linear", type: "numeric", difficulty: "hard",
    prompt: "ANOVA for regression: $SS_{\\text{reg}}=300$, $df_{\\text{reg}}=1$; $SS_{\\text{res}}=200$, $df_{\\text{res}}=18$. Find $F$.",
    answer: "27",
    explanation: "Step 1: $MS_{\\text{reg}}=300/1=300$. $MS_{\\text{res}}=200/18\\approx11.11$. $F=300/11.11\\approx27$. Final answer: $27$." }),
  p({ id: "reg-corr-7", topicId: "regression", section: "correlation", type: "mcq", difficulty: "hard",
    prompt: "Spearman's rank correlation is preferred over Pearson's when:",
    answer: "Data is ordinal or the relationship is monotonic but not necessarily linear.",
    choices: ["Data is continuous and normal.", "Data is ordinal or the relationship is monotonic but not necessarily linear.", "Sample size is large.", "$r>0.9$."],
    explanation: "Step 1: Spearman ranks the data and computes $r$ on ranks. Robust to outliers and non-normality, captures monotonic relationships. Final answer: Data is ordinal or the relationship is monotonic but not necessarily linear." }),
  p({ id: "reg-residual-4", topicId: "regression", section: "residuals", type: "mcq", difficulty: "hard",
    prompt: "Leverage in regression measures:",
    answer: "How far an observation's $x$-value is from the mean of $x$.",
    choices: ["How large the residual is.", "How far an observation's $x$-value is from the mean of $x$.", "The slope of the regression.", "$R^2$."],
    explanation: "Step 1: High-leverage points have unusual $x$ values ($h_{ii}$ large). They pull the regression line toward themselves but don't necessarily have large residuals. Final answer: How far an observation's $x$-value is from the mean of $x$." }),
  p({ id: "reg-conditions-7", topicId: "regression", section: "conditions", type: "mcq", difficulty: "hard",
    prompt: "Cook's distance measures:",
    answer: "The overall influence of each observation on the regression coefficients.",
    choices: ["The residual size.", "The leverage only.", "The overall influence of each observation on the regression coefficients.", "The correlation."],
    explanation: "Step 1: Cook's $D$ combines residual and leverage: $D_i=e_i^2 h_{ii}/[ps^2(1-h_{ii})^2]$. Large $D_i$ suggests the $i$-th observation is highly influential. Final answer: The overall influence of each observation on the regression coefficients." }),
  p({ id: "reg-inference-3", topicId: "regression", section: "linear", type: "numeric", difficulty: "hard",
    prompt: "95% CI for $\\beta_1$: $b_1=3$, $SE_{b_1}=0.5$, $t_{0.025,18}=2.101$. Lower bound $=$",
    answer: "1.949",
    explanation: "Step 1: Lower $=b_1-t^*\\cdot SE=3-2.101(0.5)=3-1.051=1.949$. Final answer: $1.949$." }),
  p({ id: "reg-r2-5", topicId: "regression", section: "linear", type: "mcq", difficulty: "hard",
    prompt: "In multiple regression, adding an irrelevant predictor will:",
    answer: "Increase $R^2$ but decrease adjusted $R^2$.",
    choices: ["Decrease $R^2$.", "Increase $R^2$ but decrease adjusted $R^2$.", "Have no effect.", "Increase both $R^2$ and adjusted $R^2$."],
    explanation: "Step 1: $R^2$ can only increase when adding predictors. Adjusted $R^2$ penalizes for unnecessary predictors; it decreases if the predictor doesn't improve the fit enough. Final answer: Increase $R^2$ but decrease adjusted $R^2$." }),
];
